### ISSUE TITLE
[Ruby] Fail to highlight Ruby code with variable name 'index' correctly

### ISSUE THREAD

**Issue by taroxd** [sublimehq/Packages#1006]
![image](https://cloud.githubusercontent.com/assets/6070540/26526545/a2df197c-43b1-11e7-9631-d59cb0bfd04d.png)

This issue is similar to <https://bitbucket.org/birkenfeld/pygments-main/issues/1063/fail-to-highlight-ruby-code-with-index>.
#923 seems to be a similar issue.

**Comment by varyform** [comment]
Similar issue here:
<img width="592" alt="screen shot 2017-07-08 at 21 36 50" src="https://user-images.githubusercontent.com/20039/27988219-95160ca8-6425-11e7-9dff-dae23affa167.png">

Live demo: https://drive.google.com/open?id=0B4Q_EtN4ZKF9bHRwM0cwZUlxb1k
