### ISSUE TITLE
YAML syntax highlighting: unbalanced quotation marks

### ISSUE THREAD

**Issue by bcolborn** [sublimehq/Packages#1026]
Unbalanced quotation marks in Sublime look as if there is no problem:
![image](https://user-images.githubusercontent.com/8205015/26987733-8d494778-4d01-11e7-8c86-00777ed509d6.png)

A Slack text snippet correctly shows that something is wrong with the line:
![image](https://user-images.githubusercontent.com/8205015/26987694-629ee140-4d01-11e7-8425-862ffd692c9b.png)

**Comment by FichteFoll** [comment]
The problem is that the syntax matches the unquoted scalar after the quoted string scalar as well, even though it's not a valid token after a quoted scalas. That should be doable.
