### ISSUE TITLE
Perl highlighting issue in regexp

### ISSUE THREAD

**Issue by mnowaksuse** [sublimehq/Packages#1029]
`r` at the end of the regexp is causing following text to wrongly highlight. If removed, it's OK.
```perl
if (get_var('REPO_0')) {
     my $sles_debug_repo = get_var('REPO_0') =~ s/(Server|Desktop)/\U$1\E/r;
     $sles_debug_repo =~ s/DVD/POOL/;
 ```
![image](https://user-images.githubusercontent.com/16148464/27035914-57bdd7f2-4f83-11e7-91f6-e04fc2e9f714.png)

**Comment by gullevek** [comment]
I see the same issue. It seems that /r is not supported in the regex highlighter.

![screen shot 2017-11-24 at 14 12 12](https://user-images.githubusercontent.com/855861/33196202-7cd205fc-d121-11e7-8dc9-f8606009fcdf.png)
