### ISSUE TITLE
Javascript syntax highlighter issue

### ISSUE THREAD

**Issue by Shay12tg** [sublimehq/Packages#1031]
Javascript syntax highlighter regex issue:

'str'.match(/[" ]+/g);

a space and any type of quote in a collection breaks the highlighting

Operating system and version:
Windows10
Monitor:
Resolution 1080p
Sublime Text:
Build 3135
64bit

**Comment by mbloch** [comment]
Here's a screenshot showing a similar issue in a JS file (the entire document starting with the closing regex forward-slash is colored the same way).

MacOs Sierra
MacbookPro 15" laptop
Sublime build 3136

![image](https://user-images.githubusercontent.com/1232222/27135642-0dfd2d92-50e7-11e7-9483-dff188c5bdc9.png)

**Comment by alexcme** [comment]
Have the same issue - first parameter in "replace" incorrectly closed:

![image](https://user-images.githubusercontent.com/8837157/27180933-051ab0e6-519b-11e7-90ab-12afcf9ad16a.png)

**Comment by wbond** [comment]
@Thom1729 It seems 464579bea51f59d483254acde1b41e0e42faeacb broke some regex detection. Mind taking a look, or should I?

**Comment by alexcme** [comment]
Sorry, cannot do that, still in learning curve, but, operation above was to globally replace:
"RTP/SAVPF ....." with "RTP/SAVPF <whatever is in mline>". 
It was fine in previous builds, not sure when it was broken though.

**Comment by Thom1729** [comment]
I fixed it. There was an error in the lookahead that broke regexes containing space.
