### ISSUE TITLE
[C++] Template Default Arguments Incorrect Syntax Highlighting

### ISSUE THREAD

**Issue by pgrit** [sublimehq/Packages#1032]
The default arguments for non-type template parameters are not highlighted correctly (that is, not at all). See the following example:
![screenshot from 2017-06-14 15-12-20](https://user-images.githubusercontent.com/12607894/27133841-effca8fe-5113-11e7-8e71-430f5a909efa.png)

**Comment by rwols** [comment]
Even arbitrary constexpr expressions are possible:
```cpp
constexpr std::size_t f() { return 128; }
template <std::size_t Count = f()>
class fixed_array : public std::array<int, Count> {};
```

**Comment by rwols** [comment]
I took the time to refactor the template handling logic a bit, see the newly added syntax tests.

**Comment by rwols** [comment]
Tangentially related obscure template usage (these fail but should not):

```c++
sequence.push_back(item.template as<typename T::value_type>());
/*                     ^ punctuation.accessor                           */
/*                      ^ storage.type - variable.other                 */
/*                               ^ variable.function                    */

T* p2 = p->template alloc<200>();
/*        ^ punctuation.accessor           */
/*         ^ storage.type - variable.other */
/*                  ^ variable.function    */

T::template adjust<100>();
/* <- - variable.function                    */
/*^ punctuation.accessor                     */
/* ^ storage.type - variable.other           */
/* ^^^^^^^^^^^^^^^^^^^^^^ meta.function-call */
/*          ^ variable.function              */
```

See: http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n4296.pdf section 14.2/4

I'll be updating my PR with fixes for these cases.
