### ISSUE TITLE
[Scala] Incorrect highlighting for modifier preceded by abstract method

### ISSUE THREAD

**Issue by krnhotwings** [sublimehq/Packages#1054]
If a `lazy val`, `override def`, etc. line is immediately preceded by an abstract `def` with a return type, the highlighting is incorrect

```scala
trait A {
  def a: Int
  lazy val b: Int = 123 // "lazy val b" is incorrect

  def c: String
  override def d = "blah" // also incorrect
}
```

The highlighting seems to affected specifically if the preceding line is an abstract `def`

(I'm using build 3139 on Ubuntu)

**Comment by djspiewak** [comment]
Thanks for the report. Sorry I didn't see this until just now. I'm on it.
