### ISSUE TITLE
[D] Invalid comment block when /** syntax is used.

### ISSUE THREAD

**Issue by Soulsbane** [sublimehq/Packages#1058]
I use this type of comment style in dlang:
/**
  My Description
*/
Notice the two asterisks in the first line. This causes the entire block to be highlighted pink. This is a valid dlang style since two asterisks are needed in order to generate documentation.

Tldr:
Pink
/**
  My Description
*/

Highlights correctly but dlang can't generate documentation files from this block.
/*
  My Description
*/

Thanks!

**Comment by keith-hall** [comment]
It looks like [the D syntax definition just includes the JavaDoc one](https://github.com/sublimehq/Packages/blob/91e023c31eb090f9346177222104c6cc6a3da37e/D/D.sublime-syntax#L17), so this is essentially the same issue as https://github.com/SublimeTextIssues/DefaultPackages/issues/151 on the old repo.

I believe we can use the same logic as discussed at https://github.com/sublimehq/Packages/issues/68#issuecomment-174312638, to terminate the JavaDoc context and continue with the regular block comment context when a line without an asterisk as its first non-whitespace character is encountered.

**Comment by rwols** [comment]
Leading asterisks are optional both in Doxygen as well as in [JavaDoc](http://docs.oracle.com/javase/7/docs/technotes/tools/solaris/javadoc.html#leadingasterisks), so I suggest to remove the `invalid.illegal` scopes actually.

**Comment by keith-hall** [comment]
this has been fixed by https://github.com/sublimehq/Packages/pull/1351
