### ISSUE TITLE
[C#] Incorrect 'Stray Brace' detection in certain cases

### ISSUE THREAD

**Issue by OdatNurd** [sublimehq/Packages#1059]
Using the syntax for C# as shipped with Sublime 3139, the following code is not correctly highlighted:

```c#
public class Test
{
    static void Main (string[] args)
    {
        int[] items = new int[4];
        items[0]  = 12;
        items[ 1] = 34;
        items[2 ] = 56;
        items[ 3 ] = 78;
        Console.WriteLine("{0}, {1}, {2}, {3}", 
            items[0], items[ 1], items[2 ], items[ 3 ]);
    }
}
```

In particular, in the assignments of `items[ 1]` and `item[ 3 ]` the closing square brace is scoped  as `invalid.illegal.stray.brace.cs`, while it is correctly highlighted for `items[0]` and `items[2 ]`, presumably due to the presence of leading white space.

This only occurs in the assignment; the same code as used in the `WriteLine` highlights correctly in all cases here.

**Comment by wbond** [comment]
This seems to be an issue with the highlighting in general, and the stray brace detection is just making it more noticeable. Here it is with the stray stuff reverted:

![screen shot 2017-06-28 at 8 22 11 pm](https://user-images.githubusercontent.com/41734/27666159-e3031e26-5c3f-11e7-96e0-4c3429a9ce57.png)

It is scoping the 2nd and 4th `items` as a `support.type`.
