### ISSUE TITLE
[C++] Sublime does not support C++14 digit separators

### ISSUE THREAD

**Issue by BillyONeal** [sublimehq/Packages#107]
![2015-10-30_12-39-29](https://cloud.githubusercontent.com/assets/1544943/10856199/4bcc9d72-7f03-11e5-9f4d-14e2c372f702.png)
Note how << std::endl is being interpreted as a string, not an integer literal.

**Comment by BillyONeal** [comment]
I was able to mess with my local `C++.sublime-package` to do this:

![2015-10-30_13-56-37](https://cloud.githubusercontent.com/assets/1544943/10857876/0f75fb38-7f0e-11e5-9075-c5209e394fb9.png)

but the "hack" I have will break other languages that use C style strings like XML and company. Not sure how to redefine how this works for C++ only since the edit I made was in `C.tmLanguage`.

**Comment by jfcherng** [comment]
![2015-10-31_05-06-37](https://cloud.githubusercontent.com/assets/6594915/10858081/31d20fa8-7f8d-11e5-9a51-fc9f24028b14.png)

Using `([0-9]+('[0-9]+)*\.?([0-9]+('[0-9]+)*)?)|(\.[0-9]+('[0-9]+)*)`.
Not sure what you mean `C style integer literals`.

**Comment by BillyONeal** [comment]
>Not sure what you mean `C style integer literals`.

I mean that C, for example, does not allow this syntax, so it may be desirable to specialize this to C++ mode only.

(And I may have gotten confused between this and the raw string literal issue)

**Comment by jfcherng** [comment]
There is an `C++.sublime-syntax`.

**Comment by BillyONeal** [comment]
Yeah, but this wasn't declared in there. (And I don't know how any of this stuff works -- I just found something that looked like a regex and added `'` to some character classes)

**Comment by jfcherng** [comment]
![2015-10-31_05-22-39](https://cloud.githubusercontent.com/assets/6594915/10858387/945c91be-7f8f-11e5-90f8-36389e19f79d.png)
Write another pattern which matches digit separators in `C++.sublime-syntax` and put it before include `c.source` could work.

**Comment by BillyONeal** [comment]
Neat :)

**Comment by wbond** [comment]
I believe this should be resolved by 06c9d4b2134894d1b4e9f37f1b54fa5b923e654f.
