### ISSUE TITLE
[JavaScript] Is there a purpose to `meta.function.anonymous`?

### ISSUE THREAD

**Issue by Thom1729** [sublimehq/Packages#1071]
While reviewing changes for #1009, I've discovered that the current JavaScript syntax sometimes gives a function the scope `meta.function.anonymous`. The intent seems to be that a function is "anonymous" in this sense when it does not have a name and is not immediately assigned to a variable.

In JavaScript, an ordinary function defined with the `function` keyword may have a name (e.g. `function foo() {}`). This is mandatory for function declarations but optional for function expressions and for functions defined in `export default`. In addition, the syntax tries to specially handle statements like `var foo = function(){};` and object keys like `foo: function(){},` by marking `foo` as `entity.name.function`. When it does so, it does not mark the function expression as `meta.function.anonymous`.

The usefulness of this distinction is dubious. It does not correspond to any significant semantic distinction in the language, and I can't think of a situation in which a tool should work differently on a function depending on whether it has the `meta.function.anonymous` scope.

In either case, it is not generally possible to make this distinction correctly. Because of the limitations of the parser, it can always be stymied by newlines:

```
var f =
     function foo(){};

export default function
    g() {};
```

As a result, the `meta.function.anonymous` scope is unreliable and dependent on lookaheads and guesswork that complicate the syntax (causing problems in #1009). Now, the same could be said about trying to infer indirect function names in the first place (e.g. `var f = function(){}`), but that has the clear goal of highlighting names that represent functions and adding them to the symbol list, which is very helpful for pre-ES6 code. On the other hand, the `meta.function.anonymous` scope isn't used for syntax highlighting (and, as a meta scope, never should be) and it doesn't seem very useful for tooling purposes.

Is there any compelling reason not to drop the `meta.function.anonymous` scope entirely? If it's useful, then I will make sure that the changes in #1009 maintain it as best as possible. If it's cruft, then I will remove it.

**Comment by rwols** [comment]
I think this is a good question and can be applied to all languages where functions are first-class citizens (e.g. Lua).

**Comment by Thom1729** [comment]
That might be precisely the crux of the issue. Plenty of languages have some sort of discernible syntactic distinction between a function declaration and a function expression. It might be useful to denote this with a meta scope.

The current JavaScript syntax, however, draws a distinction along a different, murkier line. A function is “anonymous” if it does not have an explicit name and it is not identified as a method. But the first criterion can't be correctly implemented because it would require looking over line boundaries, and the second criterion itself relies on an expansive notion of a “method” that doesn't exactly correspond to the native notion and suffers from even deeper parsing issues. The result is unreliable, but even if it were perfect I'm not sure that it's good for anything.

How should I proceed in #1009?

1. Try to preserve the existing `meta.function.anonymous` behavior. This could be done, although I'd basically be reimplementing it from scratch. There might be some questions regarding things like `export default function() {}`. And, of course, this would preserve some fundamentally unfixable bugs.
2. Replace it with a more relevant scheme that distinguishes function declaration statements from function expressions. The changes in #1009 make this trivially easy, when before it might have been impossible.
3. Just rip it out. If it's not good for anything, then it's cruft. We can always implement (1) or (2) later on top of clean code.

Obviously, I lean toward (3) myself, but I do wonder if there could be someone, somewhere, who relies upon the existing behavior. If I had any conceivable guess as to some plausible use for it, then this concern might push me to prefer (1).

Option (3b) might be to do (3), but implement (1) in a branch so that if anyone complained that their workflow was affected, we could push out a replica of the old functionality in a hurry.

**Comment by Thom1729** [comment]
`meta.function.anonymous` has been gone since #1009 was merged and no one's complained.
