### ISSUE TITLE
PHP: Wrap Lines (Cmd+Opt+Q) works badly with doc blocks

### ISSUE THREAD

**Issue by okdana** [sublimehq/Packages#1073]
I think this feature is called 'Wrap Lines' but i'm not sure. It's the one assigned to <kbd>Cmd</kbd>+<kbd>Opt</kbd>+<kbd>Q</kbd> on Mac which reflows the text so that it's hard-wrapped to your ruler. Here's what happens when i use it:

**Before**  
<img width="743" alt="before" src="https://user-images.githubusercontent.com/122095/27987237-ec63735c-63cf-11e7-8b60-52b4e74e0a20.png">

**After**  
<img width="743" alt="after" src="https://user-images.githubusercontent.com/122095/27987239-f144f60c-63cf-11e7-9040-e7ad67c4093d.png">

As you can see, it's an absolute mess.

It works perfectly with the C syntax, so i think someone could just borrow the comment rules from there.

ETA: This is with Sublime 3126. Affects both the PHP package that ships with it and the one taken directly from the repo as of today.

**Comment by deathaxe** [comment]
Can't reproduce with ST4113 on Windows 10.
