### ISSUE TITLE
Update highlighting on rename within Sublime Text

### ISSUE THREAD

**Issue by ivme** [sublimehq/Packages#1074]
Minor request:
After renaming an open file with a new extension in Sublime Text, syntax highlighting doesn't change to reflect the change until after the file is closed and reopened.  It would be nice if the highlighting changed immediately on rename.

**Comment by wbond** [comment]
This type of request should be posted at https://github.com/SublimeTextIssues/Core/issues. This repository is just for the actual syntax definitions themselves.

**Comment by ivme** [comment]
Got it!  Will repost over there and close here.

**Comment by keith-hall** [comment]
This has already been logged at https://github.com/SublimeTextIssues/Core/issues/854
