### ISSUE TITLE
[C#] Inconsistent highlighting and colour coding in Build 3141

### ISSUE THREAD

**Issue by bdjones** [sublimehq/Packages#1076]
The C# syntax highlighting exhibits inconsistent behaviour depending on whitespace. Given these two lines (identical except for the whitespace), the colour coding is different, and the line with the extra spacing has a weird pink highlight:

```csharp
dice[i].state = DieState.Rolling;
dice[ i ].state = DieState.Rolling;
```

![Example](http://i.imgur.com/7x8ZmF5.png)

I'm not sure what the intended colouring is, but the pink highlight definitely seems like a bug 😅

**Comment by keith-hall** [comment]
I believe this was fixed by https://github.com/sublimehq/Packages/pull/1060, but unfortunately it didn't make it into Dev Build 3141

**Comment by wbond** [comment]
Looks fixed in the current commit to master, so I am closing.
