### ISSUE TITLE
[C++] Sublime does not support C++11 raw string literals

### ISSUE THREAD

**Issue by BillyONeal** [sublimehq/Packages#108]
![2015-10-30_12-53-41](https://cloud.githubusercontent.com/assets/1544943/10856492/5601b46a-7f05-11e5-918e-6fab94958c0b.png)

**Comment by jfcherng** [comment]
Is this fixed by @jbw3's PR #105 ?

**Comment by BillyONeal** [comment]
Doesn't look like it -- I only see u, u8, U, and L in that CR, not R.

**Comment by jfcherng** [comment]
There is a `R` in Line 51.

**Comment by BillyONeal** [comment]
Ah, I see, looks like that should work, yeah.

**Comment by wbond** [comment]
This should be resolved by 387808053c796620f416bd0f3e5ff984f5296541.
