### ISSUE TITLE
[PHP] Snippet suggestion inside double and single quotes

### ISSUE THREAD

**Issue by carlevison** [sublimehq/Packages#1080]
I am getting unwanted snippet suggestions popping up inside single and double quotes inside of php.

![screen shot 2017-07-22 at 11 09 26](https://user-images.githubusercontent.com/6619631/28490286-59875dd2-6ece-11e7-9997-76eaa15ee58c.png)

**Comment by rwols** [comment]
I'm guessing it's also undesirable to trigger these snippets in comment blocks, no?

**Comment by carlevison** [comment]
Yeah, I don't see a reason to need them there either.
