### ISSUE TITLE
[Java] Comment isn't parsed correctly in last element of enum

### ISSUE THREAD

**Issue by rodmendozao** [sublimehq/Packages#1086]
Both Sublime and Markdown show the code below with comment3 highlighted incorrectly
```java
enum MyEnum {
  FIRST_VALUE, // comment1
  MID_VALUE,   // comment2
  LAST_VALUE   // comment3
}
```

**Comment by keith-hall** [comment]
This looks fine to me on build 3144:

![image](https://user-images.githubusercontent.com/11882719/30485140-324b35e4-9a35-11e7-882a-75e29b0f6a9c.png)

**Comment by wbond** [comment]
I've added a test in 39d9979
