### ISSUE TITLE
[JavaScript] Auto complete backquote

### ISSUE THREAD

**Issue by PaperFlu** [sublimehq/Packages#1101]
**1.** Write a left quotation mark, ST won't auto complete the right backwards quotation mark(\`\`) while the right single quotation marks('') or double quotation marks("") will be completed.

**2.** In the part of backwards quotation mark, auto complete `${}` when write down '${' will be better.

Thanks!

**Comment by Thom1729** [comment]
You might want to split this into two issues. The destructuring is a syntax change, whereas the auto-pairing would be a new keybind.

**Comment by PaperFlu** [comment]
@Thom1729 OK!

**Comment by wbond** [comment]
This should be resolved with the latest changes in master.
