### ISSUE TITLE
[JavaScript] ES6: Destructuring assignment in parentheses in functions support

### ISSUE THREAD

**Issue by PaperFlu** [sublimehq/Packages#1102]
### Destructuring assignment in parentheses in functions

The special color shows that ST hasn't support this..or it's the right color whereas I just want you to noticed if you haven't know about this.

![Destructuring Assignment](https://user-images.githubusercontent.com/22674396/28993435-e1e17a9e-79e8-11e7-9c0a-699147995479.png)

Thanks!

**Comment by Thom1729** [comment]
This should probably wait on #1009, because the syntax is largely restructured. Once those changes are merged, I should be able to implement this in short order.

**Comment by wbond** [comment]
This should be resolved with the latest changes in master.
