### ISSUE TITLE
(YAML) missing comment highlighting in sequence declaration

### ISSUE THREAD

**Issue by pdknsk** [sublimehq/Packages#1113]
![1](https://user-images.githubusercontent.com/1097609/29523862-9bdecd8c-868e-11e7-86bf-31337b59307c.png)

And oddly, `y` is always highlighted incorrectly, unrelated to this bug.

**Comment by kleinfreund** [comment]
Please include snippets as text in order for others to reproduce.
 
```yaml
x:
  - hello
y:
  - #1
    z: #2
```

**Comment by pdknsk** [comment]
I didn't know that. It turns out `y` and [many more](http://yaml.org/type/bool.html) are only valid in _YAML <= 1.1_.

**Comment by FichteFoll** [comment]
True, it was considered a bad idea to have this many implicit booleans, which is why there were removed for 1.2: http://www.yaml.org/spec/1.2/spec.html#id2805071

I'll see about the comment thing.
