### ISSUE TITLE
Need to add double quote " to legal matlab String syntax

### ISSUE THREAD

**Issue by apassy** [sublimehq/Packages#1114]
I tried, but can't get it to work.  It's legal as of R2017a.

**Comment by FichteFoll** [comment]
How does this issue surface and how can we reproduce it? Please explain it for someone who is not experienced with Matlab, since I'm not sure one of the regular contributors is.

**Comment by apassy** [comment]
Matlab used to have one syntax for strings 
a='lksjdfl' which would create one kind of string.
" was illegal, and the syntax definitions flag that as illegal.
as of r2017a (Feb of this year) " is legal.
b = "new string" is a new type of string, so needs to be flagged as a string.

**Comment by TheClams** [comment]
I think this can be closed now, it is part of the latest ST3 dev
