### ISSUE TITLE
Start-Docblock.sublime-snippet Broken On Latest Build

### ISSUE THREAD

**Issue by taylorotwell** [sublimehq/Packages#1116]
Recent changes to this snippet have broken starting Docblocks on the latest dev build on Sublime 3. Reverting to a previous build fixes the issue.

To recreate, simple attempt to start a Docblock. Nothing happens.

**Comment by rwols** [comment]
Related: https://github.com/sublimehq/Packages/issues/1080 and https://github.com/sublimehq/Packages/pull/1117.

**Comment by wbond** [comment]
This was fixed by #1117
