### ISSUE TITLE
ruby indenting {} within block not 'closing' the indent

### ISSUE THREAD

**Issue by ConfusedVorlon** [sublimehq/Packages#1123]
version 'Stable Channel, Builld 3126'
Mac OS 10.12.6

within a block (do end, or def xxx end) code within {} is creating an indent, and not 'closing' it.

after edit/line/reindent, the following code within file.rb is wrongly indented

```
require 'rails_helper'

RSpec.describe StaticController, type: :controller do

	expect{
		post :create, xhr: true
		}.to change(Job, :count).by(1)

	end

	def thing

		expect{
			post :create, xhr: true
			}.to change(Job, :count).by(1)

		end
```

where it should be:

```
require 'rails_helper'

RSpec.describe StaticController, type: :controller do

	expect{
		post :create, xhr: true
	}.to change(Job, :count).by(1)

end

def thing

	expect{
		post :create, xhr: true
		}.to change(Job, :count).by(1)

end
```

removing the {} section fixes the indentation problem

**Comment by keith-hall** [comment]
looks like the indentation rules will currently only unident `}` if it is only followed by (optional) whitespace on the line: https://github.com/sublimehq/Packages/blob/c98e4d2da049996ca597b37399dfea4272060874/Ruby/Miscellaneous.tmPreferences#L11

**Comment by ConfusedVorlon** [comment]
thanks - that works as a workaround.
