### ISSUE TITLE
Apparent recursion ... error

### ISSUE THREAD

**Issue by marxo** [sublimehq/Packages#113]
Since this morning any syntax scheme I choose returns this error.

`Apparent recursion within a with_prototype action: 25000 context sanity limit hit`

![2015-11-25_15-28-05](https://cloud.githubusercontent.com/assets/431616/11399657/2aad0196-9389-11e5-883e-c9e7bf2d09e8.png)

**Comment by wbond** [comment]
Can you provide the contents of your console?

**Comment by marxo** [comment]
Sorry @wbond I ended up uninstalling, clearing all cache, and reinstalling both ST3 and Packages, and error went away. I hope it won't come back but if it does I'll paste the logs.

**Comment by wbond** [comment]
Ok, great!
