### ISSUE TITLE
(JavaScript) unicode highlighting missing with many nested functions

### ISSUE THREAD

**Issue by pdknsk** [sublimehq/Packages#1130]
```JavaScript
x.y(function() {
x.y(function() {
x.y(function() {
x.y(function() {
x.y(function() {
x.y(function() {
var z = '\u1000';
});
});
});
});
});  
});
```
![1](https://user-images.githubusercontent.com/1097609/29954543-faf0d688-8ed8-11e7-803a-233909cfd253.png)

One less and it works.

![2](https://user-images.githubusercontent.com/1097609/29954544-faf466cc-8ed8-11e7-890b-6b006ec5e3ec.png)

**Comment by pdknsk** [comment]
Alternatively, each callback function can be replaced with no less than `3` regular functions.

```JavaScript
x.y(function() {
x.y(function() {
x.y(function() {
x.y(function() {
x.y(function() {
function() {
function() {
function() {
var z = '\u1000';
};
};
};
});
});
});
});
});
```

![1](https://user-images.githubusercontent.com/1097609/29954743-5b3b3c80-8eda-11e7-92cf-c6d476af6ae9.png)

**Comment by keith-hall** [comment]
Which ST build are you seeing this on? It seems fine for me in 3142 with the default JavaScript syntax.

**Comment by pdknsk** [comment]
Your comment made me try *Monokai* – works. Only happens with *Blackboard*, and perhaps others.

**Comment by keith-hall** [comment]
I enabled legacy color schemes and tried, but it still looks okay to me:
![image](https://user-images.githubusercontent.com/11882719/29957149-8b4e639c-8ef4-11e7-8cef-64a375a49cf2.png)

It seems to me like a similar issue to https://github.com/sublimehq/Packages/issues/403, but that was solved in build 3115. Can you confirm what ST build you are using please?

**Comment by pdknsk** [comment]
I'm on `3126` and tried both the default and the most-recent from-here package.

**Comment by pdknsk** [comment]
I only noticed after commenting that your image exhibits the bug!

**Comment by keith-hall** [comment]
Oh I see it now too :) sorry, not used to that color scheme so wasn't sure what to look for.

It looks like the scoring given for the scope selector `string` and the scope selector `constant` used in `Blackboard.tmTheme` are the same:

```python
>>> sublime.score_selector('source.js meta.function-call.method.js meta.group.js meta.block.js meta.function-call.method.js meta.group.js meta.block.js meta.function-call.method.js meta.group.js meta.block.js meta.function-call.method.js meta.group.js meta.block.js meta.function-call.method.js meta.group.js meta.block.js meta.block.js meta.block.js meta.block.js string.quoted.single.js constant.character.escape.js', 'constant')
1152921504606846976
>>> sublime.score_selector('source.js meta.function-call.method.js meta.group.js meta.block.js meta.function-call.method.js meta.group.js meta.block.js meta.function-call.method.js meta.group.js meta.block.js meta.function-call.method.js meta.group.js meta.block.js meta.function-call.method.js meta.group.js meta.block.js meta.block.js meta.block.js meta.block.js string.quoted.single.js constant.character.escape.js', 'string')
1152921504606846976
```

Normally `constant` would indeed have a higher match score, but I guess that is the largest scope stack / match score that ST can deal with:

```python
>>> sublime.score_selector('source.js string.quoted.single.js constant.character.escape.js', 'string')
64
>>> sublime.score_selector('source.js string.quoted.single.js constant.character.escape.js', 'constant')
512
```

As `string` is defined on line 93, and `constant` on line 41, `string` takes precedence when the scores are equal - you can "fix" this by moving the `constant` rules lower down in the `tmTheme` file so they will take precedence over `string`.

As this is a legacy color scheme, I'm not sure if such a change will be made to the version that comes with ST.

**Comment by pdknsk** [comment]
Thanks! Works for me. It seems inevitable to eventually move off of *Blackboard*. I noticed some nice features in *Monokai* missing in *Blackboard*, like cursive formatting.
