### ISSUE TITLE
[Default] Use edit_settings instead of open_file when opening prefrences

### ISSUE THREAD

**Issue by stoivo** [sublimehq/Packages#1134]
In Default (OSX).sublime-keymap we have
```
	{ "keys": ["super+,"], "command": "open_file", "args": {"file": "${packages}/User/Preferences.sublime-settings"} },
```
and I think it would be better if we changed it to 
```
  { "keys": ["super+,"],
    "command": "edit_settings",
    "args": {
      "base_file": "${packages}/Default/Preferences.sublime-settings",
      "default": "// Settings in here override those in \"Default/Preferences.sublime-settings\",\n// and are overridden in turn by syntax-specific settings.\n{\n\t$0\n}\n"
    }
  },
```
This is the command which get's called when command `preferences: Settings` is triggered.

I would open a PR but I don't know where I should open it. Please point me where I should do so.

**Comment by keith-hall** [comment]
The Default package isn't open source ([as is mentioned in the readme](https://github.com/sublimehq/Packages/blob/211a27c8c6b5fb42a85a5139028ca5efc5470e58/README.md#missing-packages)), so we can't make PRs for it, but we can request an enhancement or report a bug to SublimeHQ - typically we do so on this repo: https://github.com/SublimeTextIssues/Core/issues

**Comment by stoivo** [comment]
OK, Thanks. Then we won't need this issue anymore.

**Comment by wbond** [comment]
Build 3142 already uses `edit_settings` for Preferences. You may have an override in place?

**Comment by FichteFoll** [comment]
"Upstream" issue: https://github.com/SublimeTextIssues/Core/issues/1891

**Comment by stoivo** [comment]
@wbond, I am on 3126. Thanks anyway :)

**Comment by wbond** [comment]
@stoivo Side-by-side settings the associated key binding change were made in build 3116.

You should consider trying https://packagecontrol.io/packages/OverrideAudit to see if you have an override causing this behavior.

**Comment by stoivo** [comment]
I have Some overwriting settings, Thanks.
`super + ,` opens Side-by-sid now.
