### ISSUE TITLE
[Java] Syntax highlighting failure if method name ends with 'class'

### ISSUE THREAD

**Issue by StrangeNoises** [sublimehq/Packages#1141]
If the sequence of letters in the word 'class' appears at the *end* of a method name, syntax colouring is broken from that point on.

As per this example, which compiles and runs:

<img width="1390" alt="screen shot 2017-09-14 at 16 04 09" src="https://user-images.githubusercontent.com/1295001/30437377-5d95d77e-9966-11e7-8d3f-5e8f1dc3122e.png">

If you change any letter in the 'class' part of 'asSubclass', or add any letters to the end, eg: to '.asSublass(' or '.asSubclasse(' it all goes right. But of course, that's not the name of the method in java.lang.Class, so it doesn't compile...

(I've seen other problems with Java highlighting. This is just the first I've been able to isolate.)

Herewith pasted the code as well so you can try it...

```java
import java.text.*;

public class Test {
	public static void main(String... args) {
		try {
			Number n = NumberFormat.getInstance().parse("1234.56");
			System.out.println("Value "+n+" is a "+n.getClass().getName());
			Class<? extends Double> cdbl = n.getClass().asSubclass(Double.class);
			System.out.println("If we got here it's a Double as expected.");
			System.out.println("But nothing is syntax coloured any more");
			System.out.println("Nothing. It's all blank. Except the word 'class'");
			System.out.println("But remove one letter from the 'class' in 'asSubclass' and it all goes right.");
			System.out.println("(Except of course it doesn't compile because that's not the name of the method.)");
		} catch (ParseException pe) {
			// it's gone wrong here too hasn't it...
			System.err.println("Give us a number!");
		} catch (ClassCastException cce) {
			System.err.println("It wasn't a Double?");
		}
	}
}
```

**Comment by StrangeNoises** [comment]
Just came in to note that it affects methods ending in 'interface' too. It looks like your fix should catch that already though.

**Comment by ismell** [comment]
Is this still valid? Just tried with the latest dev build

**Comment by StrangeNoises** [comment]
I'll check tomorrow. I'm in no state to do so tonight, and don't have the dev machine to hand; on the other similar tickets was trusting to my earlier comments that they were fixed. Contextually I expect it probably is though as I haven't been aware of ongoing issues in recent usage.

**Comment by HugoLamarche** [comment]
I have the same issue with the following code : 
`class Foo {
	private int crazyclass;
	public void bar();
}`

if you change crazyclass to crazyclas for example the color highlight is ok on void bar();

**Comment by StrangeNoises** [comment]
I'm sorry I never got back after Jan 22.

On the dev build (3157) it all looks correct, including HugoLamarche's example above.

**Comment by wbond** [comment]
This issue has been solved by a previous commit, hence it is being closed.
