### ISSUE TITLE
Tcl syntax highlighting wrong in nested lists

### ISSUE THREAD

**Issue by jumarkka** [sublimehq/Packages#1145]
The second item, "{ 2 }",  below is no more highlighted at all. This problem causes large sections of standard Tcl code not be highlighted at all.

set x { 1 { 2 } }

**Comment by FichteFoll** [comment]
What should it be highlighted as? Is it also part of the string?
I'm not a Tcl expert.

**Comment by jumarkka** [comment]
> What should it be highlighted as? Is it also part of the string?
> I'm not a Tcl expert.
> 
> 


It good starting point would be if the coloring would work as in the build 3126. My example was with the build 3143. So, in the case of the example, the second number in the list should be coloured in the same way as the first one. 

Tcl does not have much inherent structure and so any colouring is I think somewhat arbitrary. (On the other hand, therefore I good colouring would be a really great help).

I have attached in this mail a more extensive example, the file "colouring_test.tcl", and also screenshots of the colouring in the "Monokai" colour scheme, taken under the two sublime builds 3126 and 3143. 

Lines 27-38 in the test file are actual code, just to show how much colouring details are lost when moving from 3126 to 3143.

Line 1 is (more or less) the example in the problem report. There,too,  the old version is more useful.

Line 3-6 shows a rather curious problem which I noticed only after the problem report: The keyword "if" is not correctly recognised in EITHER build ... 

...unless (on lines 8-11) an extra, and redundant, set of braces are added around the first item if the "if" command. 
 
Lines 12-18 show a toy version of the problem of the more real-live code of lines 27-38.

It is possible to get the newer build to color the real-life code in the better, old-built way, by adding a pair of (redundant) braces around the [catch ...] on line 28, so this is not a show-stopper. 

If there is a quick fix to get back the 3126 behaviour, I can surely live with the non-recognized keyword (as it still is coloured at least as a command ). Otherwise, I guess I need to try to dig into the sublime colouring system myself at some point.

Thanks anyway for a quick reply, I did not really expect any.

---

I'm using Mac os sierra, 10.12.6.





---
Jussi Markkanen
jussi.i.markkanen@gmail.com
www.sgo.fi/~jussi/

**Comment by rwols** [comment]
I don't see any attachment here, could you paste it here in this GitHub issue on the website?

**Comment by jumarkka** [comment]
<img width="689" alt="screenshot_3126" src="https://user-images.githubusercontent.com/27737328/30495320-1aa4369c-9a3b-11e7-8e5e-5d28473b9e1c.png">
![screenshot_3143](https://user-images.githubusercontent.com/27737328/30495324-20f42728-9a3b-11e7-9f59-000b863097c7.png)

[coloring_test.txt](https://github.com/sublimehq/Packages/files/1307151/coloring_test.txt)

**Comment by jumarkka** [comment]
![screenshot_3143](https://user-images.githubusercontent.com/27737328/30495749-c30c06f6-9a3c-11e7-9c9c-3c15d6598236.png)

**Comment by jumarkka** [comment]
The problem is most visible in the lines 29->, in the 3143 build. All coloring has been lost.

**Comment by rwols** [comment]
Thanks, this seems like a major issue.

**Comment by wbond** [comment]
Just a note, generally changes are made to the syntaxes based on:

 1. User bug reports
 2. The syntax being blatantly wrong
 3. Updating scope names to be consistent across schemes so color schemes will work for more than one syntax

The idea of just going back to 3126 would be silly. We would be throwing away all sorts of fixes and improvement.

So, the path forward is to figure out exactly what is wrong, and how to fix it.

----

You provided an example that you've indicated is broken. The next step is to figure out the correct fix.

Many of the contributors here have a *lot* of experience working with different syntaxes, how to make them work in Sublime Text, how to test them, and the scope names they should use.

What we need from you is to understand what `{ 1 { 2 } }` *means*. From my experience of working on the TCL syntax, it is a very loose, abstract language, which can make things a little trickier to get "right".

Right now the `{` is marked as the beginning of a block. If I recall correctly, TCL technically treats everything as strings, which isn't very useful when syntax highlighting, so we try to give them their semantic meaning. Generally `{` and `}` are used to pass code to be evaluated to another bit of code. In other words, a "block" of code.

However, in this situation it seems as if perhaps it is more of an array or list of some sort?

----

In terms of the issue on line 29 of your newer example, there is likely a context that isn't being exited properly. It appears the `if` statement on line 28 isn't be detected as an if statement, but a "function call". My hunch is the issue has something to do with the curlies containing the if condition on line 27.

----

In the future when providing a big block of code, please try to paste it into a fenced code block so we can copy-paste it easily.

**Comment by jumarkka** [comment]
<wbond> says that "What we need from you is to understand what { 1 { 2 } } means." 

Short answer: It is either a two element list, or a single string.

But it can be either a list of two integers; or two strings; or one integer and one string. It all depends on how it will be used later (after it has been first defined by  a set command). With Tcl it is perhaps more problematic than with some other languages to attempt to base code coloring to semantics. The semantics may not knowable at the time when the coloring needs to be done. What the editors normally seem to do is to color "manifestly number-looking" entities as numbers, entities that are given within double quotes as strings, entities that start with dollar sign as variables, and in addition color "keywords", and "comments". (None of the editors I know unfortunately color user-commands, which is pretty lamentable because in Tcl "everything is a command", control stuctures included.) 

And that is about it. All Tcl coloring I have seen is pretty simplistic. Probably with reason.  

In the particular case of the example, all the editors I know opt  for the "two integers" interpretation, ignoring the brackets around the second list element. 

In general, the editors seem pretty much ignore the nested braces altogether and color as if they would be absent, apart from the brace that is used to quote newlines. 

Since my previous comments, I have found several futher problems, but I would need some further clarification about how one should now proceed with the fixing the coloring. Should I just give show the "broken" pieces, and indicate how I would hope them to handled, or what?

**Comment by conej730** [comment]
I've also noticed that nested code blocks are now being treated as just a string and no longer have the syntax highlighting applied.  For example if I have a command, and one of the parameters to that command is some code then that block does not get syntax highlighting.  I've attached an example.  The 5th argument to pg_select is code to be executed on each row in the resultset, and in previous builds syntax highlighting was applied, but now it's all just given the string color.  It's tough to tell when we're passing a code block vs just a list or string looking at the { }, but generally when it's a code block then the opening { is followed by a newline.

![screen shot 2017-10-23 at 2 51 38 pm](https://user-images.githubusercontent.com/13803101/31910024-bb47fcf8-b801-11e7-9df5-5f8f864fa3a5.png)

**Comment by wbond** [comment]
> It's tough to tell when we're passing a code block vs just a list or string looking at the { }, but generally when it's a code block then the opening { is followed by a newline.

This sounds like it could be a decent heuristic.

The nice thing about refining the syntax is that we have testing for it now, so as we codify how things should be highlighted, we can help ensure we don't regress. Obviously there can be edge cases, but hopefully we'll generally be moving forward.

**Comment by wbond** [comment]
This should be resolved by f2d9706. I revamped handling of braces to better follow (my understanding) of how TCL is used. Please open new issues if you find new TCL syntax bugs.
