### ISSUE TITLE
Java Syntax Highlighting

### ISSUE THREAD

**Issue by Palidino** [sublimehq/Packages#1146]
Version 3126: https://imgur.com/RZGvEIP
Version 3143: https://imgur.com/bYjHcvm

EDIT: Monokai, 3126 next to 3143: https://imgur.com/ciJ4NJN

Final/capitalized variables are no longer being colored correctly. Method return types are no longer highlighting, and periods (though this may be intentional) no longer use the color previously associated with them. This issue happens with the default and adaptive theme, and also a custom theme I use.

Here's a piece of code demonstrating the issues displayed in the image. These issues occur with any of the default themes and color schemes with #3143, but were fine in #3126.

```
public class ClassDemo implements Runnable {
    public static final Object COLOR_INCORRECT = new Object();
    public static final Object COLOR_INCORRECT_2 = new Object(), COLLOR_CORRECT = new Object();

    @Override
    public void run() {  }

    public Object returnTypeColorIncorrect() {
        //The 'Object' return type is not the right color (should be the same
        //as void return type up above).
        //Periods using current return type color, unsure if this is correct. It
        //previously used the colors associated with things such as the if,
        //else, new, this, super, etc keywords.
        return COLLOR_CORRECT.toString();
    }
}
```

**Comment by wbond** [comment]
> This issue happens with the default and adaptive theme, and also a custom theme I use.

Theme's don't control the color of the code. Color schemes do. Try Mariana and see if you get a different experience.

> Annotations and final/capitalized variables are no longer being colored correctly.

The scope names for annotations have changed, so unless you've kept up with the scope naming standards, they will look different. This is on purpose since the old scope names for Java annotations were poor or incorrect.

Unfortunately your first link is broken, so I am unsure as to the differences in final/capitalized variables.

**Comment by Palidino** [comment]
Sorry I updated my post, and I had meant to say that I did use the color schemes that come with sublime and the issues still remain, I also copied the images from the forum post over incorrectly. Outside of the annotation color, the other issues did happen with the other color schemes.

Mariana color scheme, you can see the inconsistency between the final keywords at the top of the class and the return type keywords (void and Object) being different.
https://imgur.com/lPmds3G

**Comment by wbond** [comment]
The `final` and `return` keywords look highlighted properly to me in 3143 and (especially `final`) broken in 3126.

It appears the Java syntax used to give some sort of scope to uppercase identifiers, which it no longer does. Does Java treat uppercase identifiers differently in some way, or is it more of a style thing?

**Comment by Palidino** [comment]
Capitalizing final keywords is more of a style thing. However, look closely at the method that returns COLLOR_CORRECT. It's the same seperate/unique color that the variable uses when it's defined, seperate from the COLOR_INCORRECT and COLOR_INCORRECT_2 colors.

**Comment by wbond** [comment]
So it appears the bugs are:

 1. Not scoping `Object` as `support.class` when a return type
 2. Not scoping uppercase identifiers when defining (class?) constants

**Comment by Palidino** [comment]
For #1, it applies to anything capitalized I think. In this example, ClassDemo as a method is white instead of orange or blue. https://imgur.com/Sfq2frW

For #2, that is correct however a comma to separate them makes the following constants the expected color.

**Comment by wbond** [comment]
The orange is for the definition of a class (`entity.name.class`), whereas the blue is for a usage of it (`support.class`).

**Comment by Palidino** [comment]
I thought the blue is the correct color, I was simply pointing out that neither were being used beyond just specifically 'Object'. Any class object as a method return type is now colored as white with Mariana and 3143.

**Comment by Palidino** [comment]
I should have thought of this sooner as a better example. Monokai on 3126 and 3143. I would have used Mariana but the coloring on 3126 with Mariana has too many things the same color to properly show what's wrong.

3126: https://imgur.com/CK5ciQg
3143: https://imgur.com/6kr4jdo

If you look at them side by side it should be more clear what I'm trying to explain.

**Comment by StrangeNoises** [comment]
Adding my plus-one and subscribing. I see this too; it looked funny but I wasn't sure what was wrong until I saw your side-by-side screenshot. I'm getting the same thing, method return types are only coloured if they're primitives.

**Comment by FichteFoll** [comment]
For the future, please look into embedding images directly instead of linking to an image hoster's overview page. It makes following the issue much easier.

The syntax is as follows: `![Image of Yaktocat](https://octodex.github.com/images/yaktocat.png)`

You can also upload images directly to Github in the comment form, either by drag'n'drop or selecting and uploading them normally. (There's a note at the end of the comment text area input.)

**Comment by Palidino** [comment]
Thanks for the heads up, I guess I've just gotten so used to using imgur for everything that I don't even think to check if the sites I use have an image uploading option anymore.

**Comment by djspiewak** [comment]
@wbond 

> Not scoping uppercase identifiers when defining (class?) constants

Slight terminology correction: ALL_UPPERCASE identifiers in Java are just constants, and they can be static (the equivalent of "class constants") or local.

I'm not entirely certain if it is appropriate to scope them.  Could be swayed either way.  There is no semantic meaning attached to the capitalization (e.g. *unlike* in Ruby), but by the same token, it's an incredibly pervasive convention.  We've done scoping of pervasive conventions before in other languages, so there's some precedent for it, and this convention is definitely as pervasive as it gets.

**Comment by Palidino** [comment]
At the very least it should be consistently either scoped everywhere or not at all. Having an error of it being scoped on some lines and not others just doesn't feel right.

**Comment by FichteFoll** [comment]
I intend to add highlighting for CAPS_CONSTANTS to Python, because they are very commonly used and having proper highlighting (and symbol navigation) for these would be quite useful imho.

See also this separate issue: https://github.com/sublimehq/Packages/issues/458 (not tagged as RFC, @wbond?).

**Comment by Palidino** [comment]
I'd like to update this in that the latest build has not fixed this issue (the capitalizing), only changed it. Capitalized fields are now highlighted green and purple on Monokai, rather than the previous error 3143 brought of being white and purple.
<img width="578" alt="screen shot 2017-11-28 at 12 29 20 pm" src="https://user-images.githubusercontent.com/22652413/33334487-ff420b7c-d437-11e7-890b-1f16a46acf4d.png">

**Comment by wbond** [comment]
This seems to have been resolved by recent work on the Java syntax
