### ISSUE TITLE
[Java] Annotations at the start of method declaration lines break colouring

### ISSUE THREAD

**Issue by StrangeNoises** [sublimehq/Packages#1148]
This is a case where it does the right thing if the coder has followed the current Java style guides perfectly, but not if they haven't (perhaps the code pre-dates the current style guide) or have chosen to do it that way for concision, but the syntax is still correct and valid as far as the compiler is concerned (because white-space is white-space).

Style guide says you put method annotations on their own line before the method itself. This works, but if they're on the same line the rest of the line, the rest of the line loses most of its colour:

<img width="640" alt="screen shot 2017-09-15 at 09 47 53" src="https://user-images.githubusercontent.com/1295001/30474637-3f7336ce-99fc-11e7-9d26-02b00982b16c.png">

vs

<img width="640" alt="screen shot 2017-09-15 at 09 47 59" src="https://user-images.githubusercontent.com/1295001/30474643-4688c244-99fc-11e7-8230-da8bc53c0853.png">

**Comment by keith-hall** [comment]
I believe this can be fixed by adding `pop: true` after https://github.com/sublimehq/Packages/blob/bdc2c74157ba58bf4b0189ce16ea526249c95339/Java/Java.sublime-syntax#L92

**Comment by StrangeNoises** [comment]
Looks like you might be right there (about my theme). Bug shows in Monokai too, but there I can see the rest of the line is coloured as per the annotation as opposed to uncoloured.

AFAIR if an annotation has anything more to it than its name, it should be in brackets. So if the next thing (besides whitespace) isn't an open-bracket, the annotation is over.

**Comment by StrangeNoises** [comment]
OK, I can see that this is only affecting annotations with no parameters (like '@Override', the most likely case). If there are (parenthetised) parameters, the syntax colouring knows when it ends, and a method decl on the remainder of the line is correctly coloured.

Though of course if an annotation *has* parameters it's longer, so you're far more likely to put a linefeed at the end of it!

**Comment by StrangeNoises** [comment]
minor note; found a machine i hadn't upgraded sublime text on yet (still on 3126), and my theme, Material Theme, *is* colouring annotations on that version.

**Comment by ismell** [comment]
Can you try again, i think this is fixed

**Comment by StrangeNoises** [comment]
Confirmed, this is fixed for me in 3150

**Comment by ismell** [comment]
Can this be closed?

**Comment by StrangeNoises** [comment]
As far as I'm concerned yes. Sorry I didn't realise I had to do that. :-)
