### ISSUE TITLE
[PHP] /**[tab] no longer starts comment block

### ISSUE THREAD

**Issue by MJPA** [sublimehq/Packages#1149]
Before the 3143 final build, I could type `/**` then press tab and I'd end up with:

    /**
     * [cursor here]
     */

this no longer happens. Intentional / bug?

**Comment by keith-hall** [comment]
it wasn't intentional, there is a PR to fix it here: https://github.com/sublimehq/Packages/pull/1117

**Comment by MJPA** [comment]
Cheers, did scan the issues but didn't find anything, probably didn't go back far enough.

Added the snippet from that pull request manually and it's fixed, will remove it once that's merged and in a release.
