### ISSUE TITLE
(Python) tuple parameter unpacking highlighted as invalid

### ISSUE THREAD

**Issue by pdknsk** [sublimehq/Packages#1151]
https://www.python.org/dev/peps/pep-3113/

Was still considered valid before the update to `3143`.
```Python
map(lambda (x, y): x, [])
           ^    ^
```

**Comment by FichteFoll** [comment]
Same issue for normal function definitions: https://github.com/sublimehq/Packages/issues/990

Lambda highlighting is stricter and more accurate now, but tuple parameter unpacking was not considered during it (mostly because I've never used or seen it once and am only writing Python 3 code).

**Comment by pdknsk** [comment]
I use it frequently. Have you considered splitting Python into `2` and `3`? The former could be just copied from the current common package, and only have bug fixes applied.

**Comment by FichteFoll** [comment]
Splitting them is not worth it imo. The differences are only small and it would be quite annoying having to switch between the two syntaxes depending on which version you're currently working on.

I suppose we might consider this when python 2 is eol'd, but currently I don't see any reason to.

**Comment by capissimo** [comment]
My wayaround looks like this (it really annoys to have to invent gotchas - employing the unnecessary code to convert to iterable & then using next()):

def median(xs):
    return pipe(xs,
                       lambda xs: len(xs),
                       lambda n: iter((n, n // 2)),
                       lambda tup: sorted(xs)[next(tup)]
                                                if next(tup) % 2 == 1
                                                else mean( sorted(xs)[next(tup)-1:][:2] )
                     )

**Comment by FichteFoll** [comment]
Through #1519, this issue can be closed.

**Comment by deathaxe** [comment]
@wbond

**Comment by wbond** [comment]
Thanks!
