### ISSUE TITLE
[Ruby] Incorrect Indentation when private is on the same line as method definition

### ISSUE THREAD

**Issue by shalecraig** [sublimehq/Packages#1152]
### Summary

When parsing ruby, sublime text doesn't correctly recognize method definitions when they occur on the same line as `private` modifiers.

### Steps to Reproduce

1. Type this snippet.
```ruby
private def foo
  a = 1
  b = 2
end
private
def var
  a = 1
  b = 2
end
```
2. Choose `Indentation: Reindent Lines` from the command palette.

### Expected behavior

3. Expected formatting:
```ruby
private def foo
  a = 1
  b = 2
end
private
def var
  a = 1
  b = 2
end
```

### Actual behavior
3. Actual formatting:
```ruby
private def foo
a = 1
b = 2
end
private
def var
  a = 1
  b = 2
end
```

## Second Repro Case

This also comes up while typing new code:

### Repro Steps

1. Type this snippet.
```ruby
private def foo[enter]
```

### Expected behaviour
```ruby
private def foo
  # Leading spaces.
```

### Actual behaviour
```ruby
private def foo
# No leading spaces.
```

## Other interesting cases:
All these cases seem to be un-indented.
```ruby
private def foo(bar)
  x = 1;
end
public def foo(bar)
  x = 1;
end
protected def foo(bar)
  x = 1;
end
```

### Environment

* Sublime Text Build 3143

Routed here from https://github.com/SublimeTextIssues/Core/issues/1923

**Comment by keith-hall** [comment]
if I understand right, `def` can be preceded by `public`, `private` or `protected`, but the [current indentation rules](https://github.com/sublimehq/Packages/blob/6870abc638d05dbdb70bf5968dea36e1a50c91ef/Ruby/Miscellaneous.tmPreferences#L16) don't take that into account. Is it possible for those access modifiers to also preceed `class` or `module`? I don't know Ruby at all, but I do know how to improve the indentation rules ;)

**Comment by FichteFoll** [comment]
I don't think they are allowed before module, and class depends on whether inline classes are supported. They are in Java, for example.
