### ISSUE TITLE
[Markdown] Scope break if an non-letter is followed by underscore within bold markers

### ISSUE THREAD

**Issue by Mikaz-fr** [sublimehq/Packages#1163]
With the following text:
```
__test!_test__
```
The syntax leaves a scope `invalid.illegal.non-terminated.bold-italic.markdown`.
It actually appears when the middle '_' has a non alphanumerical character in front.

I guess the regex for detecting bold/italic end marker should be improved, but I didn't check.

**Comment by keith-hall** [comment]
the way [CommonMark interprets this](http://spec.commonmark.org/dingus/?text=%23%20test%0A__test!_test__%0Ahello%0A) is with a literal `_` at the front, so I'm kinda inclined to say that ST is right to warn that it looks odd. 

```xml
  <paragraph>
    <text>_</text>
    <emph>
      <text>test</text>
      <text>!</text>
      <emph>
        <text>test</text>
      </emph>
    </emph>
  </paragraph>
```

**Comment by Mikaz-fr** [comment]
I see. What would be the proper way of having a bolded non-alpha followed by underscore ?
Github parser seems ok with: `**test!_test**` (see: **test!_test**).
But Sublime's Markdown parser provide the same illegal scope with this version too.

**Comment by kleinfreund** [comment]
Is it okay to escape as in `**test!\_test**` or `__test!\_test__`?

**test!\_test**

__test!\_test__

**Comment by keith-hall** [comment]
Probably we can tweak the highlighting for that case, its tricky working with only one line at a time :) thanks for reporting :)

@kleinfreund yes, escaping the middle underscore works properly 👍
