### ISSUE TITLE
[Java] lambda code erroneously detected inside string constants

### ISSUE THREAD

**Issue by StrangeNoises** [sublimehq/Packages#1165]
A sequence of characters that matches the pattern for a lambda is recognised even if it occurs within a string constant that's used as a method parameter. As per the screenshot:

<img width="943" alt="screen shot 2017-09-20 at 16 03 48" src="https://user-images.githubusercontent.com/1295001/30651338-4f8faf36-9e1d-11e7-998d-cdf3aca02847.png">

Remove any of the characters in the string on line 5 and the problem disappears. Conversely, fill it out with whitespace, parameters inside the paranthesis, and actual code after the `->` and it sticks. It looks like it's doing the pattern detection for a bit of lambda code inside string constant parameter values.

Also, note it *doesn't* happen on lines 2 or 4, both where the string constant is used in a simple assignment. Only on line 5 where it's being sent directly as a parameter. (

(This code compiles and runs. Included below for reproducibility.)

```java
public class Test {
	public static final String STRING = "()->";
	public static void main(String... args) {
		String string = "()->";
		System.out.println("()->");
			System.out.println("And now it has all gone wrong.");
			System.out.println("See also where the auto-indenting is leaving me!");
	}
}
```

It's making it awkward editing some code-generation code we have. But instead of boring you with that, the minimal string that breaks it is just `"()->"`.

**Comment by StrangeNoises** [comment]
By the way, something doesn't show up in Monokai, but does in the theme I usually use, Material:

<img width="943" alt="screen shot 2017-09-20 at 17 18 34" src="https://user-images.githubusercontent.com/1295001/30655085-d3e88f0a-9e27-11e7-90d4-30eea5874c3f.png">

See how the close bracket inside the string constant is being matched to the open bracket outside of it? Is that a clue?

**Comment by wbond** [comment]
> See how the close bracket inside the string constant is being matched to the open bracket outside of it? Is that a clue?

Possibly. The way that we diagnose these issues is to copy-paste the code, set the syntax and then use the `show_scope_name` command (ctrl+shift+p on Mac, ctrl+alt+shift+p on Win/Linux) to see what scope is applied. This helps us understand if a context wasn't popped properly (because a scope continues beyond where it should be), or if an incorrect context was pushed into (because an incorrect scope has been added).

**Comment by FichteFoll** [comment]
Looks to me like the opening quotation mark in line 5 isn't recognized, possible due to a lambda lookahead, messing with the following quotation marks.

**Comment by ismell** [comment]
Can you try this with the latest dev build, I think it's fixed.

**Comment by StrangeNoises** [comment]
Confirmed; fixed for me in 3150. Including the auto-indent behaviour.

**Comment by ismell** [comment]
Can we close this?

**Comment by StrangeNoises** [comment]
Yes, sorry, again didn't realise that was on me (more used to ubuntu's bug report system!)

**Comment by FichteFoll** [comment]
Sometimes maintainers just forget to close issues. 🤷‍

**Comment by StrangeNoises** [comment]
I'm not a maintainer I work for a living! (Using Sublime, of course 😅)
