### ISSUE TITLE
Ruby 1.0 / @var highlighting issue

### ISSUE THREAD

**Issue by AntonSynytsia** [sublimehq/Packages#1172]
The Ruby dark theme highlighter highlights the rest of the code in yellow when adding the @ symbol after the divide sign: /@

Edit: Just figured it's a duplicate of an issue below. But this occurs in build 3143.

**Comment by FichteFoll** [comment]
Will be fixed in 3145.

**Comment by wbond** [comment]
This issue has been solved by a previous commit, hence it is being closed.
