### ISSUE TITLE
[C] meta_include_prototype

### ISSUE THREAD

**Issue by ksherlock** [sublimehq/Packages#1174]
I'm trying to embed C within another scope (think lex, yacc, etc) using `with_prototype:` to terminate the C context and pop back.  However, comments and strings don't use `meta_include_prototype: false` so my injected prototype is still active within strings and comments and it doesn't pop correctly. (there are also other places where it would pop incorrectly but they're less likely to contain the terminator text)

I can work around that but it would be nice if strings and comments were updated with `meta_include_prototype: false`

**Comment by jcberquist** [comment]
@ksherlock: have you tested this? According to the docs at https://www.sublimetext.com/docs/3/syntax.html, `meta_include_prototype` only works with the `prototype` context in the same syntax. It has no effect when `with_prototype` is used:
> Note that with_prototype is conceptually similar to the prototype context, however it will be always be inserted into every referenced context irrespective of their meta_include_prototype setting.

**Comment by ksherlock** [comment]
That's a good point.  thanks!
