### ISSUE TITLE
Auto-indent is indenting too far after inline if-statements in PHP

### ISSUE THREAD

**Issue by xluryan** [sublimehq/Packages#1175]
### Summary
After an inline if-statement **containing a string with a colon somewhere on the line**, ST3 is inserting an extra indent after pressing ENTER.

### Expected behavior
The indent should match the above line, not be further indented.

### Actual behavior
There is too much indentation.

### Steps to reproduce
1. Create a blank PHP file and open it in ST3.
2. Paste the following code:
```php
<?php
if ('a:b') return;
if ('a:b') { return; }
if (true) echo('a:b');
?>
```
3. Set the cursor after any line 2-4 and press ENTER.

### Environment
* Operating system and version: Windows 10 64-bit
* Monitor:
  * Resolution 1920x1080
* Sublime Text:
  * Version 3.0, Build 3143

**Comment by keith-hall** [comment]
If the strings don't contain a colon, then the `if` doesn't cause the next line to get indented. So it looks like this regex needs to be smarter: https://github.com/sublimehq/Packages/blob/54340707ecbf7de99ab5b02b9414258bd27ed403/PHP/Indentation%20Rules.tmPreferences#L30

**Comment by xluryan** [comment]
Appreciate your work Keith! Looking forward to the next update.
