### ISSUE TITLE
[Java] Some `punctuation` scopes are missing

### ISSUE THREAD

**Issue by ihodev** [sublimehq/Packages#1179]
![punctuation](https://user-images.githubusercontent.com/9801624/30923409-734a6dde-a3b4-11e7-9323-1dcbf9e0b158.png)

```java
public abstract class Conventions {

    private static final String PLURAL_SUFFIX = "List";

    private static final Set<Class<?>> IGNORED_INTERFACES;

    static {
        IGNORED_INTERFACES = Collections.unmodifiableSet(new HashSet<>(Arrays.asList(
                Serializable.class, Externalizable.class, Cloneable.class, Comparable.class)));
    }

    public static String getVariableName(Object value) {
        Assert.notNull(value, "Value must not be null");
        Class<?> valueClass;
        boolean pluralize = false;

        if (value.getClass().isArray()) {
            valueClass = value.getClass().getComponentType();
            pluralize = true;
        }
    }
}
```

**Comment by FichteFoll** [comment]
In your Screenshot, the caret is behind the brace where it wouldn't have a punctuation scope. Can't check myself whether the scope would be correct when actually checking the brace.

**Comment by ihodev** [comment]
I've just checked, the scope is the same when it's actually checking the brace.

**Comment by ihodev** [comment]
Note `public abstract class Conventions` **`{`** has the right scope:

```
source.java 
meta.class.body.java 
punctuation.section.class.begin.java
```

**Comment by ismell** [comment]
Can you try now that #890 is merged?

**Comment by ihodev** [comment]
Awesome :fireworks:  Thanks a lot for your hard work!

P.S. It seems your changes are not included to the latest dev build, I've tested it manually, everything is good.
