### ISSUE TITLE
Java syntax: RHS termination not detected without semicolon

### ISSUE THREAD

**Issue by StrangeNoises** [sublimehq/Packages#118]
PR #117 (from me, today) introduces a problem with try-with-resource syntax:

![screen shot 2016-01-18 at 17 43 24](https://cloud.githubusercontent.com/assets/1295001/12398347/014b86f4-be0b-11e5-898f-e7cfe9daeb6d.png)

That PR attempts to solve a problem with out-of-method assignment code being incorrectly parsed as a method definition. In so doing it creates a new meta-scope of `meta.assignment.rhs.java` which should encompass the expression to the right of the equals sign in an assignment.

There's a situation where this can go wrong. First discovered with respect to try-with-resource declarations, where the last, or only, declaration is not terminated by a semicolon. Thus:

```java
try (Stream<String> lines = Files.lines(path)) {
    lines.forEach(System.out::println);
}
```

It can also affect for-loops, but only if the final clause has an assignment. This trips it:

```java
for (int i = 0; i < 10; i+=2) {
    System.out.println(i);
}
```

Ideally we'd want a reliable way of "consuming" an expression without needing a terminator, but that may not be doable in regex. If the problem can be confined to `try (...)` and `for (...)` that might offer some more restricted-scope solutions.

**Comment by wbond** [comment]
I am thinking the simplest way around this is to tweak the new push you introduced in #117 to only happen for assignments outside of a method body. I presume that `try` and `for` don't work outside of a method, correct?

**Comment by StrangeNoises** [comment]
pretty much; they can conceivably happen in a static initialiser (valid but probably more honoured in the breach...) but I think the surrounding curly braces already put that in `code:` (Earlier, I'd tried surrounding the private and static declaration/assignments with curly braces and that fixed the syntax colouring although of course it wasn't correct java.)

I'm ok for doing it that way but I don't know how - i.e.: to do what I did for an = that's in `meta.class.body.java` but not in `meta.method.body.java`

Of course what I was originally trying was in `class-body:` and in `methods:` to just prevent it catching e.g.: `String.valueOf(` as a method definition as it's only a method *call*. But I couldn't make that work without killing its ability to find real method definitions.

**Comment by wbond** [comment]
Completed by #119
