### ISSUE TITLE
[Markdown] HTML can get `markup.raw.block` scope

### ISSUE THREAD

**Issue by ihodev** [sublimehq/Packages#1185]
I don't know if that is really important, but I've decided to file the issue :wink: 

![image](https://user-images.githubusercontent.com/9801624/31109821-1f54730e-a80b-11e7-9d88-2153a7e7abd0.png)

```md
<p>
    <details>
        <summary><strong>Eighties Dark</strong></summary><p></p>
        <p><img src="https://raw.githubusercontent.com/ihodev/sublime-da-cs/master/assets/showcase/eighties-dark.png" alt="Eighties Dark" title="Eighties Dark"></p>
    </details>
</p>
```

**Comment by keith-hall** [comment]
thanks for reporting - it looks like I have already fixed this in https://github.com/sublimehq/Packages/pull/1181

**Comment by keith-hall** [comment]
I believe this can be closed now :)
