### ISSUE TITLE
[Markdown] Single space between ` ` is treated as invalid.deprecated.unescaped-backticks.markdown

### ISSUE THREAD

**Issue by evandrocoan** [sublimehq/Packages#1187]
![image](https://user-images.githubusercontent.com/5332158/31203545-fbbc1d5a-a93d-11e7-92a9-ef1b95dfb197.png)

```markdown
` `
```

` `

The space has the scope:

`text.html.markdown meta.paragraph.markdown invalid.deprecated.unescaped-backticks.markdown`

**Comment by keith-hall** [comment]
Thanks for reporting - looks like I need to make some tweaks to get http://spec.commonmark.org/0.28/#example-315 and http://spec.commonmark.org/0.28/#example-316 working.
