### ISSUE TITLE
[Ruby] Broken highlighting for multi-line regex

### ISSUE THREAD

**Issue by garyking** [sublimehq/Packages#1188]
Version 3.0, Build 3143

```ruby
testing = /
  \n
/x

puts testing
```
![ruby screenshot](https://user-images.githubusercontent.com/343940/31211198-2d7a2158-a965-11e7-90ae-9658c24e480f.png)

**Comment by michaelblyons** [comment]
Is this the sort of thing that 4xxx non-determinism can fix?

**Comment by michaelblyons** [comment]
Works on master now.
