### ISSUE TITLE
[Bash] Proposal: Give "sudo" a special parsing path

### ISSUE THREAD

**Issue by jfcherng** [sublimehq/Packages#1191]
![image](https://user-images.githubusercontent.com/6594915/31256577-072b1302-aa66-11e7-94a7-d86fa1c610d2.png)

It would be good if a `sudo` command could be highlight as the 3rd one in the above screenshot. What do you guys think?

Or, at least, the `-rf` is not really an option of `sudo`.

**Comment by FichteFoll** [comment]
I like that, especially the more prominent highlighting, which you probably did with a special selector. 

Generally, this should be done for xargs as well.
