### ISSUE TITLE
[PHP] Scope inconsistent?

### ISSUE THREAD

**Issue by jfcherng** [sublimehq/Packages#1195]
```php
$a  .= $b; // $a = $a  . $b;
$a >>= $b; // $a = $a >> $b; // $a >>= $b; 
$a  ~= $b; // $a = $a  ~ $b; // $a  ~= $b; 
```

![image](https://user-images.githubusercontent.com/6594915/31286049-8ffd4d4c-aaef-11e7-9ae6-2823aeaf459a.png)

After using a ligature font, I found 

- `.=` is the same scope. (so ligature works)
- `~=`, `>>=`, ... etc are cut into two scopes (for example `~` and `=`).

They all work well in comments since they are all under the `comment` scope in that case.

**Comment by wbond** [comment]
I believe you fixed this in #1198
