### ISSUE TITLE
python docstring highlighting error

### ISSUE THREAD

**Issue by jbrockmendel** [sublimehq/Packages#1200]
Take a look at the class-level docstring for [statsmodels.regression.linear_model.RegressionResults](https://github.com/statsmodels/statsmodels/blob/master/statsmodels/regression/linear_model.py#L1287).  Syntax highlighting doesn't recognize the docstring as being closed on line 1425.

Changing the `r"""` to just `"""` fixes this.

Not an especially big deal, but worth reporting.  If unskilled labor can be useful, I'm happy to help.

**Comment by keith-hall** [comment]
This seems to work okay for me:
![image](https://user-images.githubusercontent.com/11882719/31310972-18078a2a-abab-11e7-9236-a128a6b87336.png)

Do you perhaps have some [overrides](https://packagecontrol.io/packages/OverrideAudit) or are using a third party Python syntax definition?

**Comment by jbrockmendel** [comment]
> Do you perhaps have some overrides or are using a third party Python syntax definition?

Not that I'm aware of, but I'll take a look.  User error is a pretty likely explanation.

FWIW I'm using 2.0.2 on OSX

**Comment by keith-hall** [comment]
The ST2 syntaxes haven't been updated for a long time - you should really consider upgrading to ST3.

**Comment by jbrockmendel** [comment]
Yep, looks like the problem goes away in ST3.  Thanks.  Will the license transfer?

**Comment by keith-hall** [comment]
depends when you bought it: https://www.sublimetext.com/upgrade

**Comment by jbrockmendel** [comment]
Great.  Worst case scenario I buy a new license.  Still a great deal for a tool I use every day.  Your hard work is appreciated.

**Comment by jfcherng** [comment]
If you dont want to pay for it at this moment, you could technically use the latest public beta (`3142`, iirc) with your ST2 license.
