### ISSUE TITLE
[bash] colorization bugs with -- and backticks

### ISSUE THREAD

**Issue by mulle-nat** [sublimehq/Packages#1203]
The highlighting in bash is broken, since I just updated to 3147

echo "foo"
echo "`dirname -- foo/bar`"
echo "bar"

Somehow the end of the string is not recognized and echo "bar" is colored incorrectly.

**Comment by rwols** [comment]
Should be fixed by https://github.com/sublimehq/Packages/pull/1199

**Comment by mulle-nat** [comment]
Thanks for the highlighting support! I can't script without it anymore.

**Comment by wbond** [comment]
This is fixed by #1199
