### ISSUE TITLE
[*] Add CODEOWNERS file

### ISSUE THREAD

**Issue by jrappen** [sublimehq/Packages#1205]
<https://help.github.com/articles/about-codeowners/#codeowners-file-example>

Possible locations:

* `./CODEOWNERS`
* `./.github/CODEOWNERS` (I suggest here)
* `/docs/CODEOWNERS`

**Comment by FichteFoll** [comment]
Related: https://github.com/sublimehq/Packages/wiki/Contributors-by-Package

**Comment by jrappen** [comment]
Article from the blog introducing the feature:

* <https://github.com/blog/2392-introducing-code-owners>

**Comment by jrappen** [comment]
Closing as stale.
