### ISSUE TITLE
[Java] change variable.function.java color

### ISSUE THREAD

**Issue by ismell** [sublimehq/Packages#1208]
variable.function looks very annoying using the default Monokai theme. This is a result of method calls now being labeled with variable.function after #890.

Can we add a `- variable.function.java` to the Monokai theme?

		<dict>
			<key>name</key>
			<string>Function call</string>
			<key>scope</key>
			<string>variable.function, variable.annotation</string>
			<key>settings</key>
			<dict>
				<key>fontStyle</key>
				<string></string>
				<key>foreground</key>
				<string>#66D9EF</string>
			</dict>
		</dict>

```Java
    foo.callBar(123).callFoo(234).callSomethingElse();
```

**Comment by wbond** [comment]
I would probably create your own copy of Monokai if you want this enhancement.
