### ISSUE TITLE
[Markdown] Is there a way to consume the full width of a line without matching \n?

### ISSUE THREAD

**Issue by dubeg** [sublimehq/Packages#1214]
This is for fenced code blocks.
I like to set their background to a different color than the buffer's bgcolor, and having the lines of the delimiters with that same color, but it's not working if the delimiter line is the last line of the buffer.

Ex:
![md](https://user-images.githubusercontent.com/6020602/31396143-9667a0f6-adb0-11e7-9b61-85d6cb9ec458.PNG)

**Comment by keith-hall** [comment]
Nope, this is currently not possible - the only way to get background highlighting for the full width of the view is with a `\n` character. You may want to consider having a blank line at the end of your files. For example by setting `"ensure_newline_at_eof_on_save": true,` in your preferences.

**Comment by wbond** [comment]
If you are still interested in this @dubeg, would you mind opening an issue on the core tracker, or seeing if there is an existing issue that covers this?

**Comment by dubeg** [comment]
Thank you @wbond, I don't really care anymore. I'll close it.
