### ISSUE TITLE
[Java] Javadoc can 'escape' its bounds

### ISSUE THREAD

**Issue by lastsecondsave** [sublimehq/Packages#1216]
From JDK's `HashMap`:

![sketch 1](https://user-images.githubusercontent.com/6729879/31411174-70eb7514-ae19-11e7-9e73-b9d46c311088.png)

Second angle from `<<` opens tag and it never closes. Here is that comment in text:
```
/**
 * The maximum capacity, used if a higher value is implicitly specified
 * by either of the constructors with arguments.
 * MUST be a power of two <= 1<<30.
 */
static final int MAXIMUM_CAPACITY = 1 << 30;
```

**Comment by wbond** [comment]
This was fixed with the Javadoc refactor
