### ISSUE TITLE
[C/C++] Inconsistent scope naming.

### ISSUE THREAD

**Issue by jfcherng** [sublimehq/Packages#1231]
As described in https://github.com/sublimehq/Packages/commit/928a7a618d99631ea424c45e74fb01d1fb6f6853.

**Comment by FichteFoll** [comment]
People are lazy.

> In PHP, currently, 
>
> - `<<|>>` are scoped as `keyword.operator.bitwise.php`.
> - `&&|\|\|` are scoped as keyword.operator.logical.php.
>
>https://github.com/sublimehq/Packages/blob/928a7a618d99631ea424c45e74fb01d1fb6f6853/PHP/PHP%20Source.sublime-syntax#L229
