### ISSUE TITLE
JavaScript: unsupported class properties 

### ISSUE THREAD

**Issue by Kronuz** [sublimehq/Packages#1238]
Support class properties.

```javascript
class Foo {
  static fooProp = {};

  // scope here no longer has meta.class.js mets.block.js
  fooMethod() {
  }
}
```

**Comment by Thom1729** [comment]
This should be added on top of #1009. (I know, I say that about everything.)

The [class fields proposal](https://github.com/tc39/proposal-class-fields) is in Stage 3, meaning that it's not finalized yet, but it's probably stable enough to implement as long as there's no philosophical objection to adding features that are on the standards track but are technically unfinished. The risk is that a change in the feature would impel a breaking change in the syntax. In practice, lots of developers are already using class properties using Babel, so there's good reason to implement them now despite that risk.

Now, the proposal specifies both public and private fields. Private fields are not yet implemented in Babel (or anywhere else). In addition, the risk of a spec change is probably greater. It may or may not be worthwhile to add support for private fields at this time.

**Comment by Kronuz** [comment]
Yes, those are not Stage 4 yet, but very used... as well as many Stage 2 and 1 things. I suppose, since this is for highlighting, we should support as much as possible as long as it’s commonly implemented, so “it just works” when someone tries/uses something. Other proposals not yet implemented I think should not land here yet
