### ISSUE TITLE
[Bash] Syntax highlighting breaks in double-quotes

### ISSUE THREAD

**Issue by exbuddha** [sublimehq/Packages#1245]
**Version:** 3.0
**Build:** 3143

**Repro Steps:**
1. Open a new tab
2. Set syntax to _Shell Script (Bash)_
3. Copy and paste the code below in editor
```
f() {
  echo "$(g)()"

  # syntax is broken after this point
}

g() {
  return
}
```

**Problem:**
- Syntax break after the first echo command
- Removing one of the two ending parentheses in _echo_ command resolves the problem

**Comment by rwols** [comment]
This is fixed in Build 3146.

**Comment by michaelblyons** [comment]
Can this be closed?

**Comment by wbond** [comment]
This issue has been solved by a previous commit, hence it is being closed.
