### ISSUE TITLE
C# highlighting incorrect after method attribute with arguments

### ISSUE THREAD

**Issue by hickford** [sublimehq/Packages#125]
This  code highlights incorrectly in Sublime Text 3 (build 3095)

    class X
    {
        void Run([Usage("help text")] int x, int y)
        {
        }
    }

**Comment by kleinfreund** [comment]
Screenshot:

![Incorrect code highlight in C#](https://cloud.githubusercontent.com/assets/5774638/12612607/3cf1b5b2-c4f4-11e5-99e6-87f737e6c8a9.png)

**Comment by wbond** [comment]
This should be fixed by 8a89b57a467ecc89b5534695800a3a8a11db0ed9
