### ISSUE TITLE
[Python] import .unicode highlighting issue

### ISSUE THREAD

**Issue by deathaxe** [sublimehq/Packages#1250]
The `.unicode` in the following code snippet is highlighted as `support.type.python` while it is actually a module and should be scoped by `meta.generic-name.python` as all the other modules.

```python
from .unicode import unicode_from_os
```

**Comment by FichteFoll** [comment]
Hm, that is probably an embarrassing oversight and easily fixed. Someone else can look into this as I won't be at a pc until next week.
