### ISSUE TITLE
[Python] input variable is highlighted as function

### ISSUE THREAD

**Issue by deathaxe** [sublimehq/Packages#1251]
The `input` variable in the following code snippet is highlighted/scoped as `support.function.builtin.python`.

```python
if input and isinstance(input, str_cls):
    input = input.encode(encoding)
```

It should be `meta.generic-name.python`

Source:

https://github.com/wbond/package_control/blob/ccae5b79d9ef60a645b1bab2988072095f21faee/package_control/cmd.py#L141-L142

**Comment by keith-hall** [comment]
As [it's a built in Python function](https://docs.python.org/3/library/functions.html#input), I'd argue that highlighting it as such is correct - it's generally bad practice to use a built in name as a variable name, and having it highlight as such serves as a useful reminder that you're hiding built-in functionality and potentially confusing other programmers reading your code.

**Comment by FichteFoll** [comment]
I agree with this.

The only situations where this might be annoying is when you are writing python 2 code and use built-ins from 3 as variable names (or vice versa).
