### ISSUE TITLE
[Graphviz] Comments not working

### ISSUE THREAD

**Issue by svivian** [sublimehq/Packages#1254]
When using the Graphviz syntax, the comment command (Edit > Comment > Toggle Comment, or `Cmd+/`) doesn't add a comment. Comments starting with `//` are allowed in `.dot` files so this should work.

I'm not familiar with the sublime-syntax format but [looking here](https://github.com/sublimehq/Packages/blob/master/Graphviz/DOT.sublime-syntax) I can see some stuff for comments so presumably it is intended to allow comments, but the syntax is wrong somehow.

Using Sublime Text Version 3.0, Build 3143.

**Comment by keith-hall** [comment]
Toggle comment functionality is independent from the syntax definition, I've just made a PR which adds the required metadata to support toggle comments in Graphviz :)
