### ISSUE TITLE
[Ruby] Weird Issue with Forward Slashes and Some Symbols

### ISSUE THREAD

**Issue by dyeje** [sublimehq/Packages#1257]
# Summary

A forward flash followed by some special characters  (!, @, #, $, %, ^, *, {, and probably more) highlights everything after as a string unless terminated by another forward flash.

# Replicate issue

Set Sublime syntax to Ruby. Paste the following 

```
@totally / @valid_code
@but = @everything_is_highlighted_like_a_string # except comments
@me = @sad # here's a weird / edge case with the terminating forward flash in a comment
```

**Comment by hasbrettn** [comment]
I believe this is actually a bug in the regex highlighting, not string highlighting.

Here's an example of what string highlighting looks like:
![image](https://user-images.githubusercontent.com/8270925/32287299-96851340-beed-11e7-8ae1-5702f567fa65.png)

And, what regex highlighting looks like:
![image](https://user-images.githubusercontent.com/8270925/32287329-b1ea3246-beed-11e7-9b8f-4b70c330849a.png)

Here's the example of division being highlighted as a regex:
![image](https://user-images.githubusercontent.com/8270925/32287307-9bd604ee-beed-11e7-9077-80745d5421dd.png)

This is what it should look like:
![image](https://user-images.githubusercontent.com/8270925/32287345-c034c8f2-beed-11e7-9975-73189f159682.png)

I'm using material theme in all these examples.

**Comment by hasbrettn** [comment]
Looks like this was fixed here: https://github.com/sublimehq/Packages/pull/1173

**Comment by dyeje** [comment]
Has that been released?  Still seeing the issue.

**Comment by FichteFoll** [comment]
The commit was first included in 3148: https://github.com/sublimehq/Packages/pull/1173/commits/fe1c2dd07348e4644384b27cdbca222e8b068607

**Comment by mcrampon** [comment]
@FichteFoll when can we expect a release?

**Comment by FichteFoll** [comment]
It'd expect a couple weeks at least.
