### ISSUE TITLE
[Go] Syntax highlighting picks up commented code

### ISSUE THREAD

**Issue by stevekuznetsov** [sublimehq/Packages#126]
Using `base16.monokai-dark` color scheme, I see the following if I create a Go source file as such:
```go
	// 	var userKey key = 0
	// 	func NewContext(ctx context.Context, u *User) context.Context {
```
![commentshighlighted](https://cloud.githubusercontent.com/assets/7328370/12661287/b9077cb6-c5e6-11e5-8a0f-014c24aae356.png)

If I add a package declaration to the file, as such:
```go
package test

// 	var userKey key = 0
// 	func NewContext(ctx context.Context, u *User) context.Context {
```

I see this:
![comment](https://cloud.githubusercontent.com/assets/7328370/12661349/21335daa-c5e7-11e5-8da7-2edb7d3331c7.png)

**Comment by ottob** [comment]
Yes, something is fishy with the var keyword. I have this:
```go
v := "var f"
fmt.Println(v)
```
resulting in:
<img width="154" alt="screen shot 2016-01-29 at 08 35 14" src="https://cloud.githubusercontent.com/assets/67104/12669762/4458aa7a-c663-11e5-9e4f-40b7e42f33cc.png">

Notice that `fmt.Println(v)` is highlighted as a comment, as is the rest of the file after the var keyword. If I edit the string to be just "var" or "varf" the highlighting doesn't break.

**Comment by ottob** [comment]
Adding a string with comment slashes seem to reset the highlighting:
<img width="113" alt="works" src="https://cloud.githubusercontent.com/assets/67104/12673041/9389494e-c67a-11e5-85fe-cf6ecd182408.png">
If I remove the slashes, the comment highlighting continues:
<img width="122" alt="nope" src="https://cloud.githubusercontent.com/assets/67104/12673040/93599ece-c67a-11e5-823a-f86ae1d1dc2f.png">

**Comment by wbond** [comment]
There is a bug in Sublime Text's sregex engine that is treating the `[[:blank:]]` posix range as all of ascii. Should be fixed in the next dev build.

**Comment by FichteFoll** [comment]
I see that the Go syntax definition uses `[[:blank:]]` twice and `\s` everywhere else. Any particular reason?

From what I can tell, they differ in that `\s` also matches Line_Separator (U+2028), Paragraph_Separator (U+2029) and 000A, 000B, 000C, 000D, 0085(NEL) characters, so mostly characters separating lines. Regular expressions are never applied on "multiple lines" though, except for when ST does not implement a unicode line separator character as an actual line separator (which is anything but 000A and 000D; see https://github.com/SublimeTextIssues/Core/issues/548).

**Comment by wbond** [comment]
@FichteFoll I believe the reason, in this case, is that someone wrote the `.tmLanguage` version and it was converted to `.sublime-syntax`. I have noticed that in general the syntax tends to handle unicode better than many, such as by using `[[:alpha:]]` and `[[:alnum:]]` instead of just `[a-zA-Z]` and `[a-zA-Z0-9]`. My guess is that they used `[[:blank:]]` for such a reason.

**Comment by wbond** [comment]
In the process of testing the fixes in ST for ``[[:blank:]]` I fixed a few small issues with the syntax in 380a68ea807d65ae45acf2b4a268286c9a09843b.

**Comment by stevekuznetsov** [comment]
@wbond thanks so much for doing this work. If I'm trying to pick up your changes, is there a faster way than waiting for a new beta build?

**Comment by FichteFoll** [comment]
@stevekuznetsov you can follow the 'Installation' guide in the readme.

**Comment by ottob** [comment]
My issues are fixed now. Thanks @wbond!
