### ISSUE TITLE
[JavaScript] tagged templates don't auto-close backtick

### ISSUE THREAD

**Issue by caub** [sublimehq/Packages#1266]
If I type
```js 
const x = `
```
it'll autoclose it fine to
```js 
const x = ``
```

But when I type 
```js
const x = foo`
```
it doesn't (where foo is a "tagged template function", basically any function can be used as such)

**Comment by keith-hall** [comment]
Which language syntax is this for? Are you perhaps using a third party package? as [I can't see any `.sublime-keymap` file in this repo with a binding for <kbd>`</kbd>](https://github.com/search?utf8=%E2%9C%93&q=repo%3Asublimehq%2FPackages+extension%3Asublime-keymap&type=Code&ref=advsearch&l=&l=)...

**Comment by caub** [comment]
I use JavaScript (babel) but I carefully tried with the default Javascript syntax as well, same behavior for the tagged functions, trailing backtick not autocompleted

**Comment by kleinfreund** [comment]
@caub I think the point is, that the backticks aren’t supposed to auto-completed right now. My Sublime certainly doesn’t autoclose them in the second example.

**Comment by caub** [comment]
@kleinfreund I don't see why it shouldn't auto-close the backtick

**Comment by kleinfreund** [comment]
@caub What I mean is that Sublime doesn’t do that *right now*. It probably should. But the behavior you show in the second example is not a Sublime default.

**Comment by caub** [comment]
Yes, sure I know, I'd like it to become one :)

**Comment by FichteFoll** [comment]
While we're at it, Markdown could also benefit from more auto-pairing with backticks and asterisks in particular.

**Comment by Thom1729** [comment]
@caub I could not reproduce this issue on the latest build. I presume it's been fixed at some point. Can this be closed?

**Comment by caub** [comment]
yes, this bug occurs with Javascript (Babel) not with Javascript
