### ISSUE TITLE
JSP syntax: <%@ gets "stuck" in keyword scope

### ISSUE THREAD

**Issue by Pointy** [sublimehq/Packages#1271]
In a directive like

    <%@ include file="foo.bar" %>

the editor gets stuck and the entire remainder of the file is sort-of weird. I think the problem is that inside `punctuation.section.directive.jsp` scope, a string of word characters (`\w+`) pushes into `keyword.other.directive.jsp` scope. From that scope, there is no `pop`.

I was able to make things generally less weird by adding

         - match: \s+
           scope: keyword.other.directive.jsp
           pop: true

I don't know if that's correct or optimal; it's the first time I've messed with a syntax file at all. The problem is not subtle however.

**Comment by mortalis13** [comment]
Confirm. If you put in the first line any text with `<%@` the next lines don't have the correct syntax coloring. In addition comment toggling not working in the whole text (except the first line), the comments are accumulated.

As in the example below:

    <%@taglib
     -->

Coloring cases:

![image 1](https://user-images.githubusercontent.com/10464927/33759496-d3256c96-dc02-11e7-8505-4124484b8e4f.png)
![image 2](https://user-images.githubusercontent.com/10464927/33759501-d638149c-dc02-11e7-9068-ad82df37e1a5.png)

The second one is with correct colors.
(Clean Sublime install with the default color scheme)

**Comment by AaronAsAChimp** [comment]
It seems linked to [this change](https://github.com/sublimehq/Packages/commit/839bfe07fdf67e4966796ede0bad946ea5abcfd3#diff-8660dca8dbb5ca771e910b917e17bc16L27-L28). Adding those two lines fixes the issue for me.

**Comment by wbond** [comment]
This is fixed by 1c1aa09
