### ISSUE TITLE
[LaTeX] tabular with column width destroys syntax highlighting

### ISSUE THREAD

**Issue by monofox** [sublimehq/Packages#1286]
Hi,
as per the [wikibook](https://en.wikibooks.org/wiki/LaTeX/Tables) i define column width for a tabular cell in order to make proper word wrapping possible.

I'm using build 3153 of sublime text 3.

The code is following:
```latex	
    \section{Termine}
	\rowcolors{2}{gray!25}{white}
	\begin{tabular}{l p{14cm}}
		\textbf{Datum} & \textbf{Veranstaltung} \\
		\hline
		\textbf{22.-24.09.17} & Delegiertenversammlung \\
		\textbf{03.10.17} & Vorbereitung Dankeschönessen 2017 und Jubiläum 2018 (Annelie, Sigi, Nicole und Christoph) \\
	\end{tabular}
```
And result is:
![Bug Screenshot ST 3](http://paste.fls-wiesbaden.de/5wh1dy)

The reason is the `p{14cm}` in the tabular cell alignments. It works if the `p` is removed, it is shown fine again. But `p` is a valid value.

**Comment by randy3k** [comment]
#1281 has fixed it

**Comment by wbond** [comment]
This issue has been solved by a previous commit, hence it is being closed.
