### ISSUE TITLE
[Diff] Trailing Whitespace should be highlighted somehow

### ISSUE THREAD

**Issue by Redoubts** [sublimehq/Packages#1304]
When I do a git diff in the terminal, lines with trailing whitespace are especially highlighted to indicate I'm adding needless characters. 

![capture](https://user-images.githubusercontent.com/2435101/32695730-ec20d248-c718-11e7-88ae-fc56e2752b46.PNG)

It would be nice to see this in Sublime Text too.

**Comment by FichteFoll** [comment]
https://packagecontrol.io/search/trailing

**Comment by Redoubts** [comment]
I'm referring to what is seen with `git diff | subl`

**Comment by FichteFoll** [comment]
Okay, this could be done with a syntax-specific setting overwrite. You can test this locally by creating one with the "Preferences: Settings - Syntax Specific" command entry.
