### ISSUE TITLE
[HTML] Embed Actions

### ISSUE THREAD

**Issue by willrowe** [sublimehq/Packages#1308]
I described an issue [in the forum](https://forum.sublimetext.com/t/dev-build-3153/33014/76) related to a template syntax not working with the new embed actions used in the HTML syntax.

Here is an excerpt of that:
> The template language can be used to generate any type of file and I specifically have a syntax for use with HTML.
>Using the with_prototype I was able to inject the template syntax into the existing HTML syntax and everything worked fine until this build.
> The issue specifically happens when a template tag is used in the style attribute, other attributes work fine.

> Example:
> `<div class="{{ "this-works-fine" }}" style="background-image: url({{ "this-does-not.jpg" }});"></div>`

@wbond responded that he would take a look at a way to handle this case.

My question now is, would it be possible to revert the addition of the embed actions to the HTML syntax? At least until it can be addressed. I'd be glad to submit a PR if so.

**Comment by wbond** [comment]
@willrowe No, rather than spending time undoing it, I'd rather spend the time on fixing with_prototype combined with embed.

You can fix it for yourself by creating your own HTML syntax (using an package override as described at http://www.sublimetext.com/docs/3/packages.html) based on the old version (grab it from the tag v3152 on this repo) and then your with_prototype should work.

**Comment by willrowe** [comment]
No problem, just wanted to check.
I'll leave this open until `with_prototype` is fixed.

I also noticed that the same thing is happening in the PHP syntax when a PHP tag is used inside of a style attribute and contains double quotes.

Example:
`<div class="<?= "this-works-fine"; ?>" style="background-image: url(<?= "this-does-not.jpg"; ?>);"></div>`

**Comment by willrowe** [comment]
This has been fixed in [build 3155](https://forum.sublimetext.com/t/dev-build-3155/33683/5?u=willrowe).
