### ISSUE TITLE
[Haskell] Function definition spread over multiple lines not correctly highlighted or lexed correctly

### ISSUE THREAD

**Issue by JoeMShanahan** [sublimehq/Packages#1321]
Given the valid syntax:

```haskell
handlePaymentCreated
  :: EventProcessor Model m
  => PaymentId
  -> Maybe PaymentType
  -> PaymentLink
  -> PaymentAmount
  -> UserId
  -> Maybe Text
  -> Day
  -> m ()
```
which is helpful for adding argument comments where they are needed, .e.g.

````haskell
-> Maybe Text -- ^ Optional granter's note on payment
````

is not highlighted correctly.

This is what it currently looks like:

![image](https://user-images.githubusercontent.com/29176664/33065669-69b3a8cc-cea1-11e7-95cc-f6894960e8e3.png)

This is what it _should_ look like:

![image](https://user-images.githubusercontent.com/29176664/33065929-cd2e59ec-cea1-11e7-9401-612611dd4bc8.png)

The incorrect highlight also leads to the definition itself not being correctly lexed (could have that backwards..). The result is that I can not use Sublime's 'Goto Definition' feature to easily jump to this code.

I assume this is because of the separation between `handlePaymentCreated` and `::`. I believed this to be impossible to fix but @FichteFoll thought otherwise: https://github.com/SublimeTextIssues/Core/issues/1412#issuecomment-337299102

**Comment by Thom1729** [comment]
I'm not a Haskell user. If Haskell sees this:

```haskell
handlePaymentCreated
```

Is this ambiguous? Is there anything else it could be other than the beginning of a type declaration? If so, then there's no way to mark it correctly, and it's just a matter of making the best guess.

However, it absolutely *is* possible for the syntax to guess wrong, see the `::`, and get on the correct path, parsing subsequent code correctly. This is fixable.

**Comment by JoeMShanahan** [comment]
A top level (no identation) expression that isn't followed up by either the function signature (`f ::`) or implementation (`f =`) is a compile error as it's a 'naked expression'. Indenastion is important, so the following is valid:

```haskell
f
  = undefined
```

The highlighter doesn't recognise the above correctly either! (See https://github.com/sublimehq/Packages/issues/1320)

However some keywords used for other syntax (`module`, `type`, `data`, `class`, `instance`) are allowed; Sublime is already aware of these, as they correctly get their own branding of syntax highlight.

**Comment by Thom1729** [comment]
It sounds like `handlePaymentCreated` is ambiguous, because it could be the beginning of either a function signature or a function implementation. It looks like the existing syntax would highlight `handlePaymentCreated` differently depending on which one it is. When the syntax sees that name followed by the end of line, it could guess one of them, and then gracefully recover on the next line of it guessed wrong.

It looks like the Haskell syntax is rather simplistic; probably, it hasn't diverged much from a prior `tmLanguage`. It might be a significant job to bring it up to date, especially because whitespace is significant.

**Comment by JoeMShanahan** [comment]
How does one go about fixing such a thing? How do I develop the syntax locally, in a repository?

**Comment by rwols** [comment]
The best way IMO is to symlink some folders to your Packages folder, [explained here](https://github.com/sublimehq/Packages#installation).
