### ISSUE TITLE
[JavaScript] `export class Foo {}` not highlighting 

### ISSUE THREAD

**Issue by clwainwright** [sublimehq/Packages#1322]
In my javascript files I often use the ES6 export syntax `export class Foo { ... }`. I'm pretty sure that this used to be highlighted correctly, but as of build 3154 the `class` keyword has scope `variable.other.readwrite` instead of `storage.type.class`, and the subsequent class definition doesn't have the proper scope either. This messes up "go to symbol", since neither the class name nor any of its methods are treated as symbols.

Digging into the sublime syntax file, it looks like the problem is in the `export-extended` definition. If I comment out `push: ... - export-extended` within `keywords-top-level` the problem goes away.

**Comment by Thom1729** [comment]
It looks like I overlooked this case when I rewrote the export logic. I should have a fix out within the next day or two.
