### ISSUE TITLE
[Ruby] Invalid String#match? highlighting

### ISSUE THREAD

**Issue by ilnurnasyrov** [sublimehq/Packages#1324]
![image](https://user-images.githubusercontent.com/3808127/33668958-3209f90e-dab2-11e7-987f-f59863c700d1.png)

**Comment by pRdm** [comment]
I believe the issue comes from line `269` in `Ruby.sublime-syntax`:

```yaml
- match: '\?(\\(x\h{1,2}\b|0[0-7]{0,2}\b|[^x0MC]\b)|(\\[MC]-)+\w\b|[a-zA-Z0-9_]\b(?!\s*:)|[^a-zA-Z0-9_\s\\])'
```

adding a negative lookahead `(?!\()` fixes the issue but not sure if it introduces any other bugs:
```yaml
- match: '\?(?!\()(\\(x\h{1,2}\b|0[0-7]{0,2}\b|[^x0MC]\b)|(\\[MC]-)+\w\b|[a-zA-Z0-9_]\b(?!\s*:)|[^a-zA-Z0-9_\s\\])'
```

**Comment by ilnurnasyrov** [comment]
I believe problem is there:
```
    # Methods that may be followed by a regex
    - match: |-
        (?x:
          \b(
            gsub!|
            sub!
          )(?=\s)
          |
          \b(
            assert_match|
            gsub|
            index|
            match|
            scan|
            sub
          )\b
        )
```
I just don't known how to solves problem with invalid highlighting. Removing `match|` solves this problem, but `match?` is not highlighted in this case. Replacing `match|` with `match\?|` doesn't highlight `match?` correctly.

**Comment by michaelblyons** [comment]
@ilnurnasyrov The `\?` messes with the `\b` at the bottom of the group. Maybe this?

``` yaml
    # Methods that may be followed by a regex
    - match: |-
        (?x:
          \b(
            gsub!|
            sub!
          )(?=\s)
          |
          \b(
            assert_match|
            gsub|
            index|
            match|
            scan|
            sub
          )\b\??    # put the optional `?` here?
        )
```

I don't use Ruby, so I don't know what the `?` is for, or if it needs to be scoped separately.


Also, here's the snippet, for future tests:

``` ruby
# correct highighting
def qwe; end
'qweqweqwe'.matches?(/qwe/)
def qwe; end

# incorrect highlighting
def qwe; end
'qweqweqwe'.match?(/qwe/)
def qwe; end
```

**Comment by FichteFoll** [comment]
`? ` is a valid character for identifiers in Ruby and conventionally used at the end of method names to indicate a boolean return value, afaik.

**Comment by Thom1729** [comment]
I can't find an authoritative reference, but [this source](https://en.wikibooks.org/wiki/Ruby_Programming/Syntax/Lexicology#Identifiers) indicates that `?`, `!`, and `=` are not universally valid identifier characters but may appear at the end of method names.

**Comment by ilnurnasyrov** [comment]
Another interesting screenshot:
![image](https://user-images.githubusercontent.com/3808127/38115309-34cb4336-33b4-11e8-9fd0-9f745371260a.png)

snippet for future tests
```ruby
# Correct
"foo".sub! /t{1,}/i
# Incorrect
"foo".sub!(/t{1,}/i)
# Incorrect
"qwe".eql? /qweqwe/i
# Correct
"qwe".eql?(/qweqwe/i)
```
