### ISSUE TITLE
Perl variable highlighting with variables that start with an _ (underscore) is broken

### ISSUE THREAD

**Issue by gullevek** [sublimehq/Packages#1326]
Variables that are named $foo are ok, but if they are named $_foo they do not highlight correctly. This is also the case for @ or % arrays/hashes.

compare screenshot between vim and Sublime Text 3 built 3143

![screen shot 2017-11-24 at 14 30 26](https://user-images.githubusercontent.com/855861/33196673-0eff3132-d124-11e7-91df-ac82095188c0.png)
![screen shot 2017-11-24 at 14 30 31](https://user-images.githubusercontent.com/855861/33196674-0f29af3e-d124-11e7-8d71-a898943d8772.png)

**Comment by michaelblyons** [comment]
Looks good now.

``` perl
#!/usr/bin/perl

$foo = 'bar';
$_foo = 'bar';
@bar = ();
@_bar = ();
%foobar = ();
%_foobar = ();

${%_foobar} = '';
%{$foobar} = 12;
%{$_foobar} = 13;
%{$foo{'bar'}{'bar'}} = 'excl';
```

![Screen Shot 2019-07-30 at 1 51 27 PM](https://user-images.githubusercontent.com/2701605/62152733-262e7a80-b2d1-11e9-91ed-ae0ef8f54992.png)
