### ISSUE TITLE
[Matlab] Function declaration highlighting not working correctly

### ISSUE THREAD

**Issue by RomeshA** [sublimehq/Packages#1328]
The latest version of `Matlab.sublime-syntax` no longer highlights some valid function declarations. In particular, while a full function declaration is

    function x = foo(bar)

both the return value and the arguments are optional. The following are also all valid function declarations

    function foo(bar)
    function x = foo
    function foo
 
These are highlighted correctly in 73da0fa5ff0642bb0746f9a496227d0b7d36a745 but don't seem to work in 9034abe330712c3cd91d074ee0267a237fdfe2ee. This is especially problematic because the incorrect identification of the function declaration means that syntax highlighting for the body of the function following the declaration fails.

**Comment by wbond** [comment]
This was resolved in #1353
