### ISSUE TITLE
(YAML?) word-wrap after parenthesis

### ISSUE THREAD

**Issue by pdknsk** [sublimehq/Packages#1350]
This has been bothering me lately when writing YAML, although it doesn't seem to be YAML-specific.
```YAML
item: |
  text ... text (
  text) text
```
In the above example, replace `...` with enough `text` to cause line-wrap.

I don't know if this can be adjusted language-specific, or if it's a _feature_ in _Sublime_ itself.

**Comment by pdknsk** [comment]
Please note that only `(` and `[` are affected, but not `{` and other non-alphanumeric characters.

**Comment by keith-hall** [comment]
upstream issue: https://github.com/SublimeTextIssues/Core/issues/218

**Comment by deathaxe** [comment]
Can't be fixed by syntax definitions
