### ISSUE TITLE
[C/C++] bug in parsing `!=` for syntax highlighting

### ISSUE THREAD

**Issue by VirgilMing** [sublimehq/Packages#1357]
Currently the `c.sublime-syntax` file parses `!=` as two parts: `keyword.operator.arithmetic.c` for `!` and `keyword.operator.assignment.c` for `=`.

I suppose a negative lookahead `(?!=)` in `match` field in `arithmetic` scope should be enough?

**Comment by jfcherng** [comment]
Can't reproduce.

![image](https://user-images.githubusercontent.com/6594915/34069259-f70378e8-e287-11e7-91e3-fce33d49f1d6.png)

**Comment by Poyeyo** [comment]
Related bug, ligature != doesn't work with C++.

The ligature works with JS, PHP, etc.

**Comment by rwols** [comment]
Works fine in `v3154`:

<img width="420" alt="schermafbeelding 2018-01-21 om 14 53 37" src="https://user-images.githubusercontent.com/2431823/35194877-f2f77246-feba-11e7-8f4f-f52062827f69.png">

**Comment by rwols** [comment]
Is this still relevant?

**Comment by jfcherng** [comment]
I am afraid they were not using the master branch at that moment.

**Comment by wbond** [comment]
This issue has been solved by a previous commit, hence it is being closed.
