### ISSUE TITLE
[Go] Test file uses tabs for indentation

### ISSUE THREAD

**Issue by FichteFoll** [sublimehq/Packages#1361]
Noticed this via https://github.com/SublimeText/PackageDev/issues/177.

Using tabs is not recommended because it will break your tests if you find yourself with mixed indentation between code and test lines or when they don't start at the same indent level, which isn't that hard to run into.

**Comment by deathaxe** [comment]
@FichteFoll @wbond  fixed by the Go Rework

**Comment by FichteFoll** [comment]
:tada: https://github.com/sublimehq/Packages/commit/14a35f641f348b4ee0ead558e5ee474f7255b50f
