### ISSUE TITLE
[JavaScript] Highlighting breaks after named export of expression without semi-colon.

### ISSUE THREAD

**Issue by thomaswelter** [sublimehq/Packages#1365]
There is a bug in the syntax highlighting for javascript.

```javascript
a => new a()
// export will turn white instead of red (in monokai theme)
export a
```

when you remove the brackets the problem vanishes. When the value is not an arrow function there also isn't a problem.

**Comment by kleinfreund** [comment]
Cannot reproduce on buuld 3156.

The export is scoped like this:

```
source.js meta.export.js
```

**Comment by thomaswelter** [comment]
ah i did not know there was a dev build. it seems to be fixed in the dev build.

**Comment by thomaswelter** [comment]
I updated to the latest dev build and there still seems to be a problem with the following syntax

```javascript
// first export does work (source.js meta-export.js keyword.control.import-export.js)
export let test = 123

// second export fails (source.js meta-export.js variable.other.read-write.js)
export test
```
same for `const `and `var`. All of this isn't a problem when closing with semicollons, but this is valid JS

**Comment by kleinfreund** [comment]
Your example is invalid. Exporting a named symbol looks like this:

```
// first export does work (source.js meta-export.js keyword.control.import-export.js)
export let test = 123

// second export fails (source.js meta-export.js variable.other.read-write.js)
export { test }
```

The second `export` is correctly scoped as `source.js meta.export.js`, but it is not highlighted. Only when adding a semi-colon to the first export statement will it be highlighted correctly.

Can you please change the title to something descriptive?

For example: [JavaScript] Highlighting breaks after named export of expression without semi-colon.

**Comment by thomaswelter** [comment]
That was a little confusing of me, ofcourse `export test` is not valid. What i meant was that it doens't matter what comes after the last export statement, as far as i can see it is always white. I'm not quite sure how the sublime scoping system works but the words after the failed export do not have `meta.export.js` (where they do in the working export statement)

```javascript
export let foo = 123
// has meta.export.js

export function bar() {}
// export has meta.export.js but function does not
```

**Comment by kleinfreund** [comment]
Indeed. Subsequent export statements are not scoped correctly after an export statement of an expression that is not followed by a semi-colon. This is a bug.

**Comment by Thom1729** [comment]
From skimming the relevant contexts, it looks like the export statement isn't properly ending after the variable declaration, so when the variable declaration ends it tries to match the subsequent `export` as a continuation of the original export statement rather than bailing to the `statements` context. Probably, the `export-extended` context shouldn't be including `variable-declaration`, but instead setting it upon a lookahead.

I'll take a look in the next couple of days. It's probably an easy fix, although I'll have to see how it interacts with the other changes in the pipeline, particularly the changes to variable declarations..
