### ISSUE TITLE
[snippets] Customize coding convention : bracket at end of line, space before parenthesis...

### ISSUE THREAD

**Issue by gbersac** [sublimehq/Packages#137]
### Problem
I have a problem with snippets. Some of them doesn't match my coding convention. For instance, in c++, i always write a space after parenthesis and put the begin bracket on the same line as the scope declaration. I also use space instead of tabs. Example, I write:

```c
if (a > 5) {
    // spaces at begin of line
}
```

while the snippet write :

```c
if (a > 5) {
	// tab at begin of line
}
```

### Solution
- add the possibility to overload or deactivate default snippets.
- enforce the use of tabs in snippets definition and auto convert space in snippets definition in spaces according to the settings of the user.
- let the user define synthax for snippets. Example :

```
    <content><![CDATA[if (${1:/* condition */})
{
	${0:/* code */}
}]]></content>
```

switch to :

```
    <content><![CDATA[if${block_open_parenthesis}${1:/* condition */}${blick_close_parenthesis}${block_open_bracket}
	${0:/* code */}
${block_close_bracket}]]></content>
```

We could set `block_open_bracket` to ` \n{\n` or `{\n` according to our taste.

- it would be great to have the abillity to create language specific option. For instance, I use tabs in c++ and space for rust and python.

**Comment by wbond** [comment]
Sublime Text has a built-in way to override things like snippets. The end of http://www.sublimetext.com/docs/3/packages.html gives a brief explanation. http://docs.sublimetext.info/en/latest/extensibility/packages.html#customizing-or-overriding-packages has more details.

I just tested out C++ and the `if` snippet, and it properly respected the buffer's tab/spaces setting.

**Comment by FichteFoll** [comment]
> enforce the use of tabs in snippets definition and auto convert space in snippets definition in spaces according to the settings of the user.

This is already the case and has been for many years.

Your shellVariables approach is doable at the moment and can also be syntax-specific, but it would require to make most default snippets *next to* unreadable for anyone who is not used to it.

**Comment by gbersac** [comment]
Ok, thanks.
