### ISSUE TITLE
[PHP] Syntax Highlight issue for multi-line asterisk comments

### ISSUE THREAD

**Issue by Mestika** [sublimehq/Packages#1378]
When creating a comment in PHP with this syntax, the highlighter "breaks" rest of the file.

***Not working***
```<?php
/**
 * PHP comment
 *
 * @see
 * @author
 * @package
 * @version
 NOTE: Modified */
```  

The issue lies in the last sentence **NOTE: Modified** which does not begins with a asterisk (*) and thus breaks the syntax highlight.

***Working***
```<?php
/**
 * PHP comment
 *
 * @see
 * @author
 * @package
 * @version
 * NOTE: Modified */
```

**Comment by wbond** [comment]
@jfcherng Would you be interested in taking a peek?

**Comment by jfcherng** [comment]
@wbond I dont have access to a computer on this weekend though.
