### ISSUE TITLE
[PHP] Gray out unused variables within a function [Suggestion]

### ISSUE THREAD

**Issue by BrandonSurowiec** [sublimehq/Packages#138]
Can Sublime tell if a variable is unused within a function or method? It would be great if syntax highlighting can be written to mute unused variables.

```php
// Both $foo and $bar would be muted. They are both unused.
function foo($bar) {
    return $foo;
}
```

**Comment by jfcherng** [comment]
It should be done by a plugin IMO.

**Comment by wbond** [comment]
No, this would require something like a PHP linter/code analysis tool. The syntax highlighting processes one line at a time and can't track anything other than the current parser state/context.

**Comment by BrandonSurowiec** [comment]
Thank you for the information!

**Comment by FichteFoll** [comment]
Try one of these: https://packagecontrol.io/search/linter%20php
