### ISSUE TITLE
HTML Tag not support!

### ISSUE THREAD

**Issue by QuestionPython** [sublimehq/Packages#1382]
Example : marquee Tag(https://github.com/SublimeTextIssues/Core/issues/2153)
---------

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/marquee
```
<marquee bgcolor="yellow" behavior="alternate">
	IN THE NAME OF GOD!
</marquee>
```

  
More Sample:
-------
```
<marquee>This text will scroll from right to left</marquee>

<marquee direction="up">This text will scroll from bottom to top</marquee>

<marquee direction="down" width="250" height="200" behavior="alternate" style="border:solid">
  <marquee behavior="alternate">
    This text will bounce
  </marquee>
</marquee>
```

**Comment by FichteFoll** [comment]
What do you mean with "not supported"? Where is this not supported? What should it do and what is it actually doing?

**Comment by questionpython** [comment]
not supported mean , not suggest in auto-complate editor. @FichteFoll

**Comment by FichteFoll** [comment]
As indicated by the MDN reference in OP, the tag is long deprecated and not to be used anymore. It is not sensical to suggest using it in a completion.

You can add a snippet locally if you really need to, but this isn't something that every ST user should be bothered with.

**Comment by kleinfreund** [comment]
I think this can be closed, no?

**Comment by wbond** [comment]
This issue is being closed since the tag is deprecated, and thus we don't want to suggest it to users.
