### ISSUE TITLE
Two embeds in the same line breaks second embed

### ISSUE THREAD

**Issue by skyronic** [sublimehq/Packages#1385]
If a line has two sections with embedded scope, the second one isn't syntax highlighted.

I have a HTML file like this (latest dev build):

```
<script>foo() {} </script> <script>bar() {}</script>
```

![image](https://user-images.githubusercontent.com/80173/34820508-c42b455e-f6e6-11e7-956b-fbdb819738af.png)

I noticed this trying to fix vuejs/vue-syntax-highlight#114, having two embeds with scope as `source.js` breaks the highlighting of second embed in the line.

(cc @Thom1729)

**Comment by Thom1729** [comment]
Here's a fun pair of cases:

Works:
```html
<script>42</script><script>42</script>
```

Doesn't:
```html
<script>42;</script><script>42</script>
```

I'll take a deeper look later today if I can.

**Comment by Thom1729** [comment]
All of these pass:

```html
<script>42/*;</script><script>42</script>
<script>42;43</script><script>42</script>
<script>42;@</script><script>42</script> (@ is not matched by any syntax rule)

<script>42</script><script>42;</script><script>42</script>

<script>42;</script><style>div{}</style>
<style>div{}</style><script>42;</script>

<style>div {</style><style>div {}</style>
```

But these fail:

```html
<script>42;</script> <div></div> <script>42</script>
<script>42;</script> <!-- --> <script>42</script>
<script>42/**/;</script><script>42</script>
<script>42;</script><script>42</script><script>42</script>

<div><script>42;</script></div><script>42</script>

<style>div {}</style><style>div {}</style>
```

It seems that the problem depends on the content of the first tag and affects all subsequent tags of the same type on the same line. Adding a newline between the `<script>` tags fixes the problem. Adding a newline *within* a bugged `<script>` tag causes highlighting to begin after the newline; the content in the bugged tag before the newline is not processed at all.

Replacing the `embed` logic in the HTML syntax with the corresponding `push`/`with_prototype` fixes the problem. It does seem likely that this is a bug in the `embed` implementation.

**Comment by wbond** [comment]
This is fixed in build 3157
