### ISSUE TITLE
[Makefile] Makefile syntax highlighting matches wrong parenthesis

### ISSUE THREAD

**Issue by mckern** [sublimehq/Packages#1392]
I have a Makefile that uses `$(shell)` to define some values that will later be used as dependencies. The trivial example looks like this:

```make
APP_LIST := apps.json
APPS := $(shell jq -S -r 'keys | join(" ")' $(APP_LIST))

test: $(APPS)
	@echo dependencies: $(^)
```

Unexpectedly, syntax highlighting is terminating on the first close-paren in the statement, not the last:

<img width="558" alt="screen shot 2018-01-16 at 5 17 27 pm" src="https://user-images.githubusercontent.com/344926/35020543-8479cefe-fae1-11e7-9eeb-dd94e9d46b31.png">

I'm using Sublime Text 3156, but I also have this problem using stable 3143.

**Comment by rwols** [comment]
Can you open the console, and type this:

```
view.settings().get("syntax")
```

It should print this:
```
>>> view.settings().get("syntax")
'Packages/Makefile/Makefile.sublime-syntax'
```
Your snippet seems to work fine on the `v5154` git tag here:
<img width="629" alt="schermafbeelding 2018-01-21 om 11 35 12" src="https://user-images.githubusercontent.com/2431823/35193166-3bf87c90-fe9f-11e7-8317-12400526fc49.png">

**Comment by mckern** [comment]
Now that's interesting:

```
>>> view.settings().get("syntax")
'Packages/Autotools/Makefile2.tmLanguage'
```

And sure enough, removing the 3rd party [Autotools package](https://packagecontrol.io/packages/Autotools) results in the highlighting I'd expect to see:

![screen shot 2018-01-21 at 4 19 54 am](https://user-images.githubusercontent.com/344926/35194105-7fba2fe2-fe62-11e7-8f5f-e4429bb17ea8.png)

I had no idea that package was even providing syntax highlighting for Makefiles! I'll take this bug over to their repo. Thanks for your help!
