### ISSUE TITLE
[Lua] match "end" keyword BUG

### ISSUE THREAD

**Issue by RobinCodeX** [sublimehq/Packages#1394]
![123](https://user-images.githubusercontent.com/8408783/35192450-6fd7f6ac-fecd-11e7-9e13-d5c284c8bd34.gif)

This `Spend()` is matched to `end`

**Comment by keith-hall** [comment]
The problem is with the `increaseIndentPattern` regex [here](https://github.com/sublimehq/Packages/blob/61bfd68ea07a3aede68cd6a65c80be702b3d6db8/Lua/Indent.tmPreferences#L13). PHP used to have similar problems: https://github.com/sublimehq/Packages/issues/1175
