### ISSUE TITLE
Simplifying html_completion.py

### ISSUE THREAD

**Issue by kleinfreund** [sublimehq/Packages#14]
Right now, the `html_completion.py` file is mapping attributes to tags in a pretty crude manner ([have a look](https://github.com/sublimehq/Packages/blob/master/HTML/html_completions.py#L19-L84)).

I was thinking about saving the global attributes ([see Mozilla Developer Network](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes)) that are common to all HTML elements as a list and adding them to all available tags.

```python
global_attributes = ['accesskey', 'class', 'contenteditable', 'contextmenu', 'dir', 'hidden', 'id', 'lang', 'style', 'tabindex', 'title', 'translate']
```

I have a few questions about this.

1. Do you want this?
2. Can we assume that the global event handler attributes listed on the MDN page are common to all HTML elements as well?
3. Should attributes marked as _obsolete API_ (such as `bgcolor`) be removed from the existing map?

**Comment by sublimehq** [comment]
1 and 2 sound good to me.

I wouldn't want to see the obsolete attributes removed: some users are unaware that they're obsolete, and will be unhappy to see them missing. The costs outweigh the benefits on this.

**Comment by sublimehq** [comment]
Closing now that 9fdcf95 has been merged in

**Comment by sublimehq** [comment]
btw, thanks for the patch!
