### ISSUE TITLE
[C++] DLL Macros causes bad syntax highlighting

### ISSUE THREAD

**Issue by jasjuang** [sublimehq/Packages#1400]
I am on sublime version 3143. Color scheme is mac classic.

Please check the below minimal code

```
namespace abc
{
class MyClass
{
 public:

  WINDOWS_DLL MyClass();

  WINDOWS_DLL ~MyClass();
};

}
```

The destructor is not being treated as a function, because if it is, the color of the destructor will become blue instead of remaining in black. However, if I remove the `WINDOWS_DLL` macro, the destructor will become blue like it supposed to be. Can we fix it so the destructor will be treated as a function regardless of the existence of the dll macro? Packages like doxydoxygen actually relies on this to generate the correct doxygen comment template https://github.com/20Tauri/DoxyDoxygen/issues/98. The author of doxydoxygen also pointed out that this problem actually wasn't there in sublime text 3084.

**Comment by jfcherng** [comment]
![image](https://user-images.githubusercontent.com/6594915/35491818-eeee14a0-04e3-11e8-8494-89ac155512c6.png)

Looks good to me with the latest syntax definition in this repo.

**Comment by jasjuang** [comment]
You are right, it is already fixed in the latest dev build.
