### ISSUE TITLE
[Java] Hexadecimal floating-point literals not recognized

### ISSUE THREAD

**Issue by lastsecondsave** [sublimehq/Packages#1404]
Some 'hidden' feature of the Java: https://blogs.oracle.com/darcy/hexadecimal-floating-point-literals.

The only example I've ever seen in the wild is JDK's `java.lang.Double`:

<img width="589" alt="screen shot 2018-01-31 at 14 55 29" src="https://user-images.githubusercontent.com/6729879/35621847-db1f99e4-0696-11e8-8738-73ded4262199.png">

**Comment by djspiewak** [comment]
This is less niche of a feature than the OP makes it sound.  (e.g. it's very common in bit manipulation for data structures and protocol definitions)  It actually sort of surprises me that we didn't catch this before.
