### ISSUE TITLE
[C++] Redundant meta.group scope for methods without parameters in class definition

### ISSUE THREAD

**Issue by papadokolos** [sublimehq/Packages#1406]
In the following case, it seems that the closing round brace in the method's signature gets an extra `meta.group.c++` scope, which seems wrong. I discovered it while trying to create a color scheme that draws pairs of nested braces with different colors:

<table>
<tr><td>
Code Sample
</td></tr>
<tr><td>
<pre lang="c++">
struct Lemonade : public MassiveDropAttack
{
    // See how the closing brace gets TWO meta.group.c++ scopes instead of one
    virtual int PureFunc() override
    {
        return 10;
    }
};
</pre></td></tr>
</table>

<table>
<tr><td>
Screenshot
</td></tr>
<tr><td>

<img src="https://user-images.githubusercontent.com/13286080/35740050-48950652-083c-11e8-84d5-1f01402162c7.png" alt="Screenshot demonstrating the bug" height="739" width="671"/>

</td></tr>
</table>

<table>
<tr><td>
Relevant part in the color scheme
</td></tr>
<tr><td>
<pre lang="XML">
&lt;dict&gt;
    &lt;key&gt;name&lt;/key&gt;
    &lt;string&gt;Braces Level 1&lt;/string&gt;
    &lt;key&gt;scope&lt;/key&gt;
    &lt;string&gt;meta.group punctuation.section.group&lt;/string&gt;
    &lt;key&gt;settings&lt;/key&gt;
    &lt;dict&gt;
        &lt;key&gt;foreground&lt;/key&gt;
        &lt;string&gt;#00D93D&lt;/string&gt;
    &lt;/dict&gt;
&lt;/dict&gt;
&lt;dict&gt;
    &lt;key&gt;name&lt;/key&gt;
    &lt;string&gt;Braces Level 2&lt;/string&gt;
    &lt;key&gt;scope&lt;/key&gt;
    &lt;string&gt;meta.group meta.group punctuation.section.group&lt;/string&gt;
    &lt;key&gt;settings&lt;/key&gt;
    &lt;dict&gt;
        &lt;key&gt;foreground&lt;/key&gt;
        &lt;string&gt;#EAFF00&lt;/string&gt;
    &lt;/dict&gt;
&lt;/dict&gt;
</pre></td></tr>
</table>

What do you think? Is this really a bug, or is it the right syntax behaviour, and I'm just using it wrong in my color scheme?

Thank you for your time,
Have a lovely weekend :smile:

**Comment by rwols** [comment]
It seems to be because of this accidental `meta.group.c++` [on line 1337](https://github.com/sublimehq/Packages/blob/master/C%2B%2B/C%2B%2B.sublime-syntax#L1337). Maybe you can fix this and turn it into a pull request?
