### ISSUE TITLE
Double quotation marks containing parens leads to improper highlight 

### ISSUE THREAD

**Issue by ixixit** [sublimehq/Packages#1411]
When using double quotation marks to contain parentheses, the quotation marks are improperly escaped in display context leading to a highlighted exception after the final quotation mark, which is misinterpreted as an unmatched quotation mark.

`set arg1=%1
:existchk
if "%1"=="" (
	set /p %1 ="Input extract directory, please (i.e. C:\Adobe): "
)`

![image](https://user-images.githubusercontent.com/21322945/35931627-62fafa74-0bf2-11e8-8862-4e1aae89f409.png)

**Comment by wbond** [comment]
This was fixed in #1412
