### ISSUE TITLE
Angular event bindings in .html files

### ISSUE THREAD

**Issue by ssistoza** [sublimehq/Packages#1419]
Angular event bindings may give wrong syntax coloring. This normally happens when there is an equal sign nested in the event bind. 

Example:
`<ngb-alert (close)="message=null" >{{ message }}</ngb-alert>`

Everything after `null` will have string syntax coloring.

![screen shot 2018-02-10 at 11 20 46 am](https://user-images.githubusercontent.com/17445445/36064199-3e5fdb98-0e55-11e8-8646-0b578711f6ce.png)

**Comment by Thom1729** [comment]
The problem is that the HTML syntax definition does not recognize `(close)` as an attribute name. The [HTML5 spec](https://html.spec.whatwg.org/multipage/syntax.html#attributes-2) is characteristically lenient here; the syntax definition should be updated accordingly.
