### ISSUE TITLE
[Python] invalid.deprecated.character.escape in double quoted strings

### ISSUE THREAD

**Issue by evandrocoan** [sublimehq/Packages#1428]
![image](https://user-images.githubusercontent.com/5332158/36240903-47ef9cc2-11fa-11e8-8b83-c56faf50c478.png)

These red things have:

`source.python meta.function-call.python meta.function-call.arguments.python meta.string.python string.quoted.double.python invalid.deprecated.character.escape.python`

I think they are non deprecated valid python. I am using the latest version from master branch.

```python
	tag = re.search("<\s*(["+NEEDLE_CHARACTERS+"]*)\s*[^>]*$", prefix_line)
	# print("tag 1: `%s`" % tag)

	if tag:
		tag = tag.group(1)
		# print("tag:", tag)

	propertyName = re.search("[\s\"\'']*(["+NEEDLE_CHARACTERS+"]*)[\s\"\']*\:[^\:]*$", prefix_line)
```

**Comment by keith-hall** [comment]
see https://github.com/sublimehq/Packages/pull/1240 for the reasoning why this was added

**Comment by FichteFoll** [comment]
These back slashes aren't doing what you think they do because you aren't using raw strings. This feature is also supposed to hint at that. `"\$"` is the same as `"$"`.

**Comment by FichteFoll** [comment]
This works currently, but as mentioned has been deprecated in 3.6 and will eventually be removed entirely. You should be using raw strings, which will also add syntax highlighting to your regular expressions.

**Comment by evandrocoan** [comment]
Thanks!

> and will eventually be removed entirely

In python 4 I hope, otherwise would break current Python 3 code running.
