### ISSUE TITLE
[PHP] PHP files (.php, and starting with <?php) are detected as HTML

### ISSUE THREAD

**Issue by jaimeeee** [sublimehq/Packages#143]
I have .php files that both start and don't start with <?php, and they are not detected as PHP they are detected as HTML.

**Comment by FichteFoll** [comment]
This was fixed via 007b2ef9be6ffd69d5bd2097ecf08d9170627d44 ( #136).

**Comment by wbond** [comment]
@jaimeeee Can you check your `Packages/` folder and see if you have an `HTML` folder or `PHP` folder in there?

I know some packages were duplicating syntax files and editing them on the fly to try and add highlighting features. This has the downside that it can easily conflict with the primary `Packages/PHP/PHP.sublime-syntax` file.

Also, note that the commit @FichteFoll referenced only helps with function ending in an unknown file extension. File extensions always take precedence over content detection.

**Comment by jaimeeee** [comment]
@wbond after checking it, it was my mistake. For some reason I had a syntax preference or always opening php files as HTML (never did that, don't know what happened).

So closing this anyway. Thanks!
