### ISSUE TITLE
[C++] Templates and operator overloading throws off grammar

### ISSUE THREAD

**Issue by TheGag96** [sublimehq/Packages#1433]
I was writing up some homework the other day and I ran into a syntax highlighting issue.

![](https://i.imgur.com/D9bjph4.png)

`template` should be highlighted, but it isn't after the first one there. Removing both the firs `<T>` the `<` in `operator<` will make them highlight again:

![](https://i.imgur.com/Li0Z4vc.png)

![](https://i.imgur.com/WLhcyld.png)

Also, shouldn't `polarNum<T>::funcName` highlight regardless of whether the `<T>` is there?

**Comment by rwols** [comment]
Could you post the faulty snippet as text instead of a picture?

**Comment by rwols** [comment]
Never mind, I think I have a fix for this.
