### ISSUE TITLE
update snakemake/.Snakefile/.snakefile/.smk syntax highlighting in Python

### ISSUE THREAD

**Issue by scottkall** [sublimehq/Packages#1434]
Hi, I'm not sure exactly how to do the latter or I would -- could someone:

1. add lowercase `.snakemake` and `.smk` to [this document](https://github.com/sublimehq/Packages/blob/1602e19b6ae3b2c031fda6f4c7d8c32c560b8bbf/Python/Python.sublime-syntax) and then 

2. find a way so that triple-quoted shell commands in Snakefiles render as something other than a gray Python comment? 

Example in Sublime Text with sublimehq (current clone):

![pipe_smk](https://user-images.githubusercontent.com/3195509/36324600-f4e73a4c-1322-11e8-8bb4-84a892e2cfff.png)

versus the ATOM editor (1.24.0 x64):

![pipe_smk_atom](https://user-images.githubusercontent.com/3195509/36324650-2dfcd9fe-1323-11e8-8285-dee6e2b607d9.png)

I'm on Mac OS 10.13.3 and Sublime Text 3.0 build 3143.

Really, really appreciated if you can.

Tagging @wbond @karel-brinda @jskinner @guillermooo, who contributed to the Python.sublime-syntax doc.

Appendix: [details on Snakemake](https://snakemake.readthedocs.io/en/stable/)

**Comment by FichteFoll** [comment]
Trying to get the python syntax to work for this special format would be impractical. It seems like you should be better off with the bash highlighting, for now at least. Ideally you would have a custom syntax for this format that could for example include the shell syntax for the quoted shell block and add a prototype match for custom variable interpolation.

**Comment by karel-brinda** [comment]
@FichteFoll Snakemake is a domain-specific language built on top of Python. It would be nice to make bash highlighting work (for `shell:`), but support for highlighting Python code has, in my opinion, a higher priority.

The issue here is that `"""..."""` after `shell:` never corresponds to a doc string, but to a string carring some code. Therefore, it should not become almost invisible.

Maybe would it possible to check what's the preceding work, and if it `shell:`, don't interpret it a doc string?

**Comment by karel-brinda** [comment]
This is the Snakemake grammar: http://snakemake.readthedocs.io/en/latest/snakefiles/writing_snakefiles.html. Unfortunately, the page is somehow old and doesn't include newer keywords (e.g., `conda:` or `singularity:`).

**Comment by johanneskoester** [comment]
Oh yeah, I should update the grammar. Thanks for pointing this out!

**Comment by wbond** [comment]
If snakemake is a DSL based on Python syntax, but with different semantics, we won't be able to properly support it in the Python syntax. With more than a few syntaxes the semantics matter more than the syntax.

We may have a better way to extend syntaxes in the future, but nothing right now. You may be interested in using a third-party solution like YAML Macros to take the default Python syntax and create one for Snakemake.

**Comment by diazdc** [comment]
Just in case anyone is still watching this, I've started to hack the default Python syntax file as I come across differences between python and snakemake highlighting.

https://github.com/diazdc/sublime-text-settings/blob/master/snakemake.sublime-syntax

Commenting out lines 1253 through 1275 in the syntax file gives the desired result:

<img width="710" alt="Screen Shot 2019-08-11 at 11 56 38 AM" src="https://user-images.githubusercontent.com/32173539/62837072-94a7fc80-bc30-11e9-82bf-c9204aaf0528.png">

It's not elegant by any means, but hopefully someone with more know-how can develop a package in the near future.
