### ISSUE TITLE
[Bash] Redirection at start of line breaks highlighting of command

### ISSUE THREAD

**Issue by zx8** [sublimehq/Packages#1437]
![image](https://user-images.githubusercontent.com/8544900/36341962-44ee0ebe-13ee-11e8-987b-b41220ed98d9.png)

**Comment by rwols** [comment]
This was fixed here https://github.com/sublimehq/Packages/pull/1369 and should turn up in a new build.

<img width="233" alt="schermafbeelding 2018-02-17 om 16 10 12" src="https://user-images.githubusercontent.com/2431823/36342332-10a3c914-13fd-11e8-8cc0-04ae63ac1130.png">

**Comment by zx8** [comment]
Aha, missed that, closing!
