### ISSUE TITLE
Having enabled the setting 'draw_white_space', the whitespace is drawn too bold, as if it's part of the text

### ISSUE THREAD

**Issue by darkred** [sublimehq/Packages#1445]
Using ST 3 dev build 3157 in win10x64.

Since last July when I clean installed Sublime Text (so I probably it was dev build 3141 ) in my desktop pc, and right after I installed inside it the SublimeLinter 3 package,
the following scheme file was generated and selected: [Monokai (SL).tmTheme](https://gist.github.com/darkred/3e227ec68537bdb0f618ee9bf169035f). _I guess that was just a slightly modified version of the default Monokai scheme file of Sublime Text._
I had kept using it (in fact I hadn't noticed that it was selected at all) until today (currently using dev build 3157) 
when SublimeLinter 4 has been released, and I noticed that SublimeLinter no longer generates its own 'Monokai (SL).tmTheme' file.

I tried switching to the default, built-in Monokai scheme (which is in the new format, `.sublime-color-scheme`), 
but I noticed that unfortunately the whitespace is drawn (spaces as middle dots ( · ) and tabs as em dashes (—)) too bold, as if it's part of the text.

Here's two current screenshots to see what I mean: 
the one using the default Monokai scheme,
and the other using the old `Monokai (SL).tmTheme`, i.e. spaces and tabs being drawn much more subtle:
![2018-03-02_183545](https://user-images.githubusercontent.com/723651/36910797-662200de-1e4a-11e8-9a2e-c305a7e1b4fb.jpg) ![2018-03-02_184745](https://user-images.githubusercontent.com/723651/36910814-6eda9f74-1e4a-11e8-9cac-2a91a7c7ad85.jpg)

I want to permanently switch to the new format Monokai scheme (`Monokai.sublime-color-scheme`), instead of being stuck with the old `Monokai (SL).tmTheme` scheme.
So, my question is this:  **can I modify it (using PackageResourceViewer) to make the drawn whitespace appear be subtle?**

Thank you

PS. For reference, here is the current, [Monokai.sublime-color-scheme](https://gist.github.com/darkred/8f60611050e4372050008822c9630539) file, as displayed via PackageResourceViewer.

**Comment by keith-hall** [comment]
Change the alpha value for `invisibles` maybe :)

**Comment by darkred** [comment]
Thanks a lot for the quick reply!
Changing the alpha value from 0.35 to 0.10 fixed it.

Maybe the default value in the scheme (as it ships in the installer) should change to 0.10?
I believe it's much more comfortable this way.
