### ISSUE TITLE
[C++] Syntax highlighting different for code in C vs C++, build 3103

### ISSUE THREAD

**Issue by digikata** [sublimehq/Packages#145]
For this code, the syntax highlighter correctly highlights when applied as C syntax, but misses the highlight for the last "#endif" when treating it as C++.

  #ifndef IGUARD_
  #define IGUARD_
  struct foo;
  struct foo*  alloc_foo();
  #endif

I'm running build 3103,  Linux 64bit on Ubuntu 14.04.3.

**Comment by wbond** [comment]
This was resolved with PR #151
