### ISSUE TITLE
Bad highlighting in Groovy string interpolation

### ISSUE THREAD

**Issue by tobia** [sublimehq/Packages#1451]
Sometimes the Groovy package seems to fail at highlighting expressions within the `"${...}"` string interpolation construct. For instance, this is valid Groovy code, but it throws the syntax highlighter into a panic:

![groovy](https://user-images.githubusercontent.com/48756/37090014-fbd3b85a-2202-11e8-869a-b3937f148f88.png)

I took the screenshot with the latest build (3157) and an empty `~/.config/sublime-text-3` directory.

**Comment by wbond** [comment]
This issue has been solved by a previous commit, hence it is being closed.
