### ISSUE TITLE
[Markdown] Ligatures that start with < aren't rendering

### ISSUE THREAD

**Issue by appsforartists** [sublimehq/Packages#1453]
Ligatures that begin with `<` are rendering as two characters in Markdown.  They will draw correctly if placed immediately after a backtick or in in a syntax like TypeScript.

<img width="134" alt="screen shot 2018-03-08 at 12 37 02 am" src="https://user-images.githubusercontent.com/926648/37141115-dfd9e2ee-2268-11e8-8c12-4c7bbfb85bf6.png">

**Comment by appsforartists** [comment]
I'm using [Inconsolata](https://github.com/alexeiva/Inconsolata/tree/master/fonts/ttf), but I can reproduce with Fira Code too.

**Comment by keith-hall** [comment]
I guess this is due to https://github.com/sublimehq/Packages/blob/2027e62cf47466b6ffab78c2af6660f8ab0062ee/Markdown/Markdown.sublime-syntax#L508-L513. It could be solved by removing the meta scope, but I think it is useful to have the scope there.

**Comment by appsforartists** [comment]
I bet there's an exclusion character in whatever flavor of regex sublime uses.  You could presumably whitelist `<=` and `<-` without affecting HTML parsing.

**Comment by FichteFoll** [comment]
An option would be to match these two specifically before this match to ensure they end up in the same token.

@keith-hall iirc tokenization happens regardless of whether a scope is assigned or not, so removing the meta scope wouldn't help.

**Comment by deathaxe** [comment]
Looks fixed in ST 3207

**Comment by wbond** [comment]
@appsforartists Are you still seeing this with the latest version of Sublime Text 3?

**Comment by appsforartists** [comment]
I can reproduce the original issue in 3211.
