### ISSUE TITLE
do not support right to left languages

### ISSUE THREAD

**Issue by 2dvision** [sublimehq/Packages#146]
Sublime Text do not support right to left languages like Persian (Farsi) and Arabic. In the picture you can see that the Persian word (سلام) is written left to right and broken. 
(Ubuntu 14.04 64bit, Sublime Text Build 3103)

![Sublime Text do not support right to left languages](http://oi64.tinypic.com/2wd7fc9.jpg)

**Comment by FichteFoll** [comment]
[related](https://github.com/SublimeTextIssues/Core/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+rtl)

**Comment by wbond** [comment]
This is an issue with the core of Sublime Text itself, not the packages. I believe there is already a thread about this on the forum, and @FichteFoll referenced some issues in the SublimeTextIssues/Core bugtracker.
