### ISSUE TITLE
[Python3] Tuple unpacking in the context of a with statement confuses the highligher

### ISSUE THREAD

**Issue by fake-name** [sublimehq/Packages#1467]
![image](https://user-images.githubusercontent.com/1401239/37572383-6e90ae12-2ac7-11e8-8fba-affaabff397c.png)

```
	with self.row_sess_context(dbid=relid) as (row, sess):
		print(row, sess)
```

This is completely valid python, but the trailing parenthesis is highlighted in red.

**Comment by keith-hall** [comment]
This seems to be a duplicate of https://github.com/sublimehq/Packages/issues/1397, and was fixed by https://github.com/sublimehq/Packages/pull/1418

**Comment by FichteFoll** [comment]
Whops, I should update my local repo :+1:

**Comment by fake-name** [comment]
@keith-hall - Yeah, looks like it. I must have missed that issue because I was searching for `parenthesis`, not `brackets`
