### ISSUE TITLE
[LaTeX] Separate Quote and Footnote scopes

### ISSUE THREAD

**Issue by DOFfactory** [sublimehq/Packages#1472]
Hi, I am really missing the quote and footnote scopes from the LaTeX syntax. It would be great if the scope can be for

- ``some text'' and \`some other text' the scope `text.tex.latex meta.group.brace.latex quote.latex`
- `\footnote{some footnote}` the scope `text.tex.latex meta.group.brace.latex footnote.latex`

... or something similar. It would help immensely to introduce new syntax highlighting for these two scopes.

**Comment by randy3k** [comment]
It should not be very difficult to support these. Any contributions are appreciated.

**Comment by DOFfactory** [comment]
Great to hear that. Can you please kindly provide any starting point for this? Which file needs editing?

**Comment by r-stein** [comment]
You need to edit this file: https://github.com/sublimehq/Packages/blob/master/LaTeX/LaTeX.sublime-syntax
However setting up your editor such that you can create a PR and learning the syntax definition syntax will take way longer than adding this feature.

**Comment by DOFfactory** [comment]
I see, so can you @r-stein add these features pls? 🥇

**Comment by deathaxe** [comment]
Fixed by merged PR #1509.

**Comment by wbond** [comment]
This issue has been solved by a previous commit, hence it is being closed.
