### ISSUE TITLE
[JavaScript] ES6 Decorators

### ISSUE THREAD

**Issue by Thom1729** [sublimehq/Packages#1477]
The core JavaScript syntax does not support [decorators](https://github.com/tc39/proposal-decorators).

Usually, we would implement an experimental JavaScript feature if it is in Stage 3 or if it is in Stage 2, the syntax is stable, and there is at least one implementation. The decorators proposal does not satisfy that criterion: it is in Stage 2 and the syntax is probably stable, but there is currently no implementation.

However, Babel (the transpiler, not the Babel-sublime package) *used* to have an implementation for an earlier version of the spec. As a result, there is a fair bit of JavaScript in the wild using decorators. The specified *semantics* changed (though the syntax didn't change much), and the Babel plugin was deprecated. A new implementation for the current spec is a priority for Babel 7.

As a result, the decorators proposal is in an odd place where the spec is still under development but the syntax should be stable, and there are no current implementations yet there's real code out there. My opinion (which I hope will be confirmed when the March TC39 meeting notes drop) is that the decorators proposal will inevitably advance and that the syntax will not substantially change. Therefore, I think that it would be appropriate to implement the decorator syntax in core. JS Custom has an optional implementation that could easily be ported.

The question is somewhat time-sensitive, because I would like to use the next stable release as a baseline when reworking Babel-sublime.

**Comment by kleinfreund** [comment]
Isn’t there like 2 or 3 concurring proposals for this kind of thing? I’ll see if I can dig up something.

**Comment by Thom1729** [comment]
There is [one proposal](https://github.com/tc39/proposal-decorators) at Stage 2.
