### ISSUE TITLE
SQL Syntax in Python file

### ISSUE THREAD

**Issue by PMickael** [sublimehq/Packages#148]
Like said [here](https://forum.sublimetext.com/t/sublime-text-3-latest-has-broken-sql-syntax-highlighting-inside-python-files/17361), there is a problem with the latest version of sublime text build 3103 of syntax highlighting of SQL query in Python

I tried MagicPyhon too.

**Comment by robindowling** [comment]
:+1:

**Comment by wbond** [comment]
Can you post an example snippet of code you that contains a string you expect to be highlighted?

**Comment by robindowling** [comment]
`cursor.execute('SELECT id FROM table WHERE statistics_id = %(last_id)s', {'last_id': last_id})`

Pretty much any SQL string, starting with SELECT, UPDATE, INSERT  or DELETE. It was working right up until the last update of Sublime.

**Comment by PMickael** [comment]
It's not the only problem of highlighting, in HTML/PHP, template file with .html extension do not highlight PHP like <?= or <?php

**Comment by wbond** [comment]
@PMickael That sounds like a different issue. Please create a new issue and provide a sample of the code that triggers it and a screenshot of what it looks like.

**Comment by PMickael** [comment]
@wbond yes maybe, but the problem appear also with this build, and it seem's to be highlighting problem when 2 different type of syntax is in the same file, like SQL in Python // PHP in HTML // Jinja in HTML

Screenshots :
![image](https://cloud.githubusercontent.com/assets/122271/12952090/93a85254-d015-11e5-8168-e21a807b1e53.png)

![image](https://cloud.githubusercontent.com/assets/122271/12952214/ff56b298-d015-11e5-8c94-d56515e7abde.png)


Should be :
![image](https://cloud.githubusercontent.com/assets/122271/12952236/15fcea4e-d016-11e5-90bd-8c990f8a15ea.png)

![image](https://cloud.githubusercontent.com/assets/122271/12952228/0d6bda5c-d016-11e5-8115-5d44e4e816d9.png)

But I have to set the syntax manually

**Comment by wbond** [comment]
@PMickael Just because it was introduced with this build does not mean it is really related to this. Please move your last post to a new issue, otherwise it may get lost when this issue gets fixed.

**Comment by benjolitz** [comment]
I submitted the original complaint.

I've thousands of lines of code in the format:

```
query = \
    ''' SELECT
            table.field
        FROM schema.table
        WHERE
            conditions = table.field2 ...
    '''
```

The most recent update ruined that strategy by destroying the syntax highlighting (`SELECT, FROM, WHERE` were colored red, `table.field, table.field2, schema.table` were colored blue and `conditions =` was left the default text color)

This is highly distressing as my primary reason to use Sublime was that wonderful feature that made maintaining complex SQL queries in a proprietary project doable.

**Comment by wbond** [comment]
Highlighting of embedded SQL and regexp in Python is fixed in 80aa6a0c681d715534e90c9fe92828735ab22366, along with a number of edge-cases resolved.

**Comment by benjolitz** [comment]
I've updated/overwritten all my packages via package control and I see no change.

What should I do to make use of this commit?

**Comment by wbond** [comment]
@benjolitz Currently Package Control does not interact with default packages at all.

Your options are:

 1. Wait for the next **dev** build of Sublime Text
 2. Copy the version of `Python.sublime-syntax` from this repo into your `Packages/Python/` folder and restart Sublime Text

If you pick the second option, please be aware that you'll need to remove the file when the next build comes out, or you will miss out on any future fixes.

**Comment by benjolitz** [comment]
I just did option 2 by unzipping the `/Applications/Sublime Text.app/Contents/MacOS/Packages/Python.sublime-package` into a temp dir, patching the sublime-syntax file, rezipping it and replacing the zip package.

Considering I've replaced the zip file, future fixes should be compatible as they'll simply overwrite the file, correct?

**Comment by wbond** [comment]
Yes, that method will work the way you described since you replaced the version in the .app.

**Comment by benjolitz** [comment]
Thanks @wbond 

For other people who've been bitten by this bug, the fix procedure (until the next dev release is out is as follows:

```
laptop:~$ mkdir /tmp/Python.sublime-package
laptop:~$ cd /tmp/Python.sublime-package
laptop:~$ rm Python.sublime-syntax
laptop:~$ wget https://raw.githubusercontent.com/sublimehq/Packages/master/Python/Python.sublime-syntax
laptop:~$ zip /tmp/Python.sublime-package.zip *
laptop:~$ mv Python.sublime-package.zip /Applications/Sublime\ Text.app/Contents/MacOS/Packages/Python.sublime-package
```

Then restart sublime text.
