### ISSUE TITLE
Reconsider how autocomplete works on javascript functions

### ISSUE THREAD

**Issue by madprops** [sublimehq/Packages#1480]
https://github.com/sublimehq/Packages/blob/master/JavaScript/Completion%20Rules.tmPreferences

Basically on javascript, if I write down a function call first. Like test_function() When I define it I have to write it all again: function test_function()

I've encountered this problem quite a bit, leaving to have to guess, make sure, I write it correctly.

But maybe there's a good reason why it works that way, so I'm leaving it open for discussion.

**Comment by keith-hall** [comment]
For reference, there's also a video showing the problem at https://github.com/SublimeTextIssues/Core/issues/2238

[The original intention seems to be to hide autocomplete when its not useful](https://forum.sublimetext.com/t/dev-build-2176/4314?u=kingkeith), clearly in this case it is helpful to have completions, so I vote for removing the `tmPreferences` file inhibiting this behavior, or trying to work out how it could be useful (i.e. check for a `{` before EOL) and amending the regex accordingly.

**Comment by madprops** [comment]
This is still a problem. I'd make a PR but I don't feel like I know enough about the codebase to make a change :/
