### ISSUE TITLE
[JavaScript] For loop of & in operators not highlighting correctly

### ISSUE THREAD

**Issue by philipbordallo** [sublimehq/Packages#1481]
[Line 614](https://github.com/sublimehq/Packages/blob/ab54689a03e7740e42b54005f2595eeafef66747/JavaScript/JavaScript.sublime-syntax#L614) seems to not be working as they are being set as `variable.other.readwrite.js` not `keyword.operator.word.js`.

This is on Build 3157
<img width="266" alt="screen shot 2018-03-27 at 10 14 53 am" src="https://user-images.githubusercontent.com/9970403/37983307-edf5743a-31a7-11e8-9133-1b858d659e57.png">

```js
for (let item of items) {
  console.log(item);
}

for (let thing in things) {
  console.log(thing);
}
```

**Comment by jcberquist** [comment]
I believe this was fixed in https://github.com/sublimehq/Packages/pull/1469 (but will obviously only show up in the next build).

**Comment by Thom1729** [comment]
Definitely fixed in 3158.
