### ISSUE TITLE
[Lua] No syntax highlighting for a method name definition

### ISSUE THREAD

**Issue by isRyven** [sublimehq/Packages#1494]
If table name, you are defining method for, is ending with a number, then the name won't be highlighted. 
To illustrate issue, here are the screenshots:

How it normally looks:

![alt](https://i.imgur.com/YOmqVuq.png)

How it looks if table name ends with number:

![alt](https://i.imgur.com/zlSY5UL.png)

**Comment by deathaxe** [comment]
Seems to be fixed by #1461
