### ISSUE TITLE
Perl. Syntax highlight. // operator as a comment

### ISSUE THREAD

**Issue by axlewdev** [sublimehq/Packages#1495]
After // operator all lines is highlighted as comment.
Version 3.0 3143

**Comment by alexqfredrickson** [comment]
+1 as I am facing this issue as well in Sublime Text 3.0 (Build 3143).

This also happens with `split / /`, for example:

    use XML::XPath;

    $file_handler = XML::XPath->new(filename => "$filename");
    my @config_info = split / /, get_configuration( "//foo/config", $file_handler );

    sub get_configuration {
        my $param1 = shift;
        my $param2 = shift;
        return "configuration";
    }

**Comment by deathaxe** [comment]
Should be fixed by the merged PR #1564

**Comment by KES777** [comment]
Is there instruction which steps I should take to be updated to latest version?

**Comment by rwols** [comment]
@KES777:

1) clone this repository like any other repository, say /path/to/Packages
2) make a symlink to /path/to/Packages/Perl from
  - $XDG_CONFIG_HOME/sublime-text-3/Packages/Perl (linux), or
  - ~/Library/"Application Support"/"Sublime Text 3"/Packages/Perl (osx), or
  - %APPDATA%\Sublime Text 3\Packages\Perl (windows)

This is just for Perl, you can make more symlinks for other languages.

**Comment by KES777** [comment]
1. I did that. Now code is pink =) May you advice some theme editor so I can fix colors?

2. The same part of code may be highlighted differently:

![delete1](https://user-images.githubusercontent.com/799021/41648896-d674d06c-7482-11e8-97db-c03fd6a41901.jpg)

3. Regular expressions are not highlighted correct

![delete2](https://user-images.githubusercontent.com/799021/41648924-e5a60c22-7482-11e8-98a2-e69dd3b1500e.jpg)
as you can see third and forth lines are broken

**Comment by KES777** [comment]
The text of target sub:
```
sub _is_email {
  state $email_rfc5322_re = do {
    my $atom           = qr;[a-zA-Z0-9_!#\$\%&'*+/=?\^`{}~|\-]+;o;
    my $quoted_string  = qr/"(?:\\[^\r\n]|[^\\"])*"/o;
    my $domain_literal = qr/\[(?:\\[\x01-\x09\x0B-\x0c\x0e-\x7f]|[\x21-\x5a\x5e-\x7e])*\]/o;
    my $dot_atom       = qr/$atom(?:[.]$atom)*/o;
    my $local_part     = qr/(?:$dot_atom|$quoted_string)/o;
    my $domain         = qr/(?:$dot_atom|$domain_literal)/o;

    qr/$local_part\@$domain/o;
  };

  return $_[0] =~ $email_rfc5322_re;
}
```

**Comment by deathaxe** [comment]
Are you sure to have the latest Perl.sublime-syntax to be applied?

If I enter your example from the screenshots and paste your latest snippet into ST it looks like that

![screenshot](https://user-images.githubusercontent.com/16542113/41669767-de72a75a-74b2-11e8-9ff7-c7002476dd39.png)

**Comment by KES777** [comment]
I am sure. Now `//` works fine.

and without that plugin the code displayed as:

![delete1](https://user-images.githubusercontent.com/799021/41674854-bc5c0d16-74c9-11e8-9640-4fc002aa4d82.jpg)

What problem can be?

**Comment by deathaxe** [comment]
What means "Now // works fine"? Does it mean the current Perl syntax works or does it mean you deleted it to make it work?

Just tried the default Perl.sublime-syntax which is bundled with ST3176. It does not highlight everything but at least does not break the code. So I can't tell you the reason as everything works for me.

**Comment by KES777** [comment]
After installing as *rwols* said the `//` started to work fine.

If I remove installed `Packages/Perl` the code is highlighted as this:

![delete1](https://user-images.githubusercontent.com/799021/41674854-bc5c0d16-74c9-11e8-9640-4fc002aa4d82.jpg)

**Comment by vsespb** [comment]
still broken in 3176 under debian 9

**Comment by wbond** [comment]
@vsespb This isn't part of the 3176 release. Did you install from this git repo?

**Comment by vsespb** [comment]
no. i get it - need wait new release after 3176

**Comment by michaelblyons** [comment]
Looks good in 3208.

**Comment by KES777** [comment]
At the version `5163f2ef3d5` I see next results:

![_2](https://user-images.githubusercontent.com/799021/61993369-9fc92d00-b073-11e9-82ad-5f9338c4f003.jpg)

They are OK
