### ISSUE TITLE
[Bash] `readonly` not highlighted when prefixed with "local"

### ISSUE THREAD

**Issue by zx8** [sublimehq/Packages#1498]
`readonly` is not highlighted in the following code (notice GitHub _does_ highlight correctly):

```sh
local readonly a=b
```

Whereas Sublime doesn't:

![image](https://user-images.githubusercontent.com/8544900/38672832-46478884-3e47-11e8-9608-9577b9065f83.png)

**Comment by zx8** [comment]
False alarm!

As [pointed out here](https://github.com/koalaman/shellcheck/issues/1178#issuecomment-383418057], I just created a local variable named `readonly`. The highlighting is in fact correct.

Confirmed by executing the following:

```sh
#!/bin/bash

set -o nounset

#!/bin/bash

function foo() {
  local readonly bar=baz
  echo "$bar $readonly"
}

foo
```

Yields:
```sh
foo.sh: line 9: readonly: unbound variable
```

**Comment by rwols** [comment]
Woops! Thanks for pointing this out. I just checked if bash parsed it.
