### ISSUE TITLE
[C++] Open/Closing braces within class definition get different scopes

### ISSUE THREAD

**Issue by papadokolos** [sublimehq/Packages#1500]
With the newest C++ syntax highlighting available, when coloring the braces based on the number of the number of `meta.group.c++` scopes they contain, the braces of method declaration seems to get different scopes:

![screen](https://user-images.githubusercontent.com/13286080/38831309-9d0e7294-41c7-11e8-9cf0-e6dc686d7687.png)

That seems like a bug in the syntax file..

**Comment by FichteFoll** [comment]
The closing paren has an additional `meta.group.c++` scope. Does your color sheme employ different colors for nested groups/parenthesis?

The exact scopes are as follows:

```
source.c++ meta.class.c++ meta.block.c++ meta.method.parameters.c++ meta.group.c++ punctuation.section.group.begin.c++

source.c++ meta.class.c++ meta.block.c++ meta.method.parameters.c++ meta.group.c++ meta.group.c++ punctuation.section.group.end.c++
```

Code:

```c++
class Check {
public:
    Check();
}
```

**Comment by papadokolos** [comment]
Yes. I've created a syntax file which imports Sublime's C++ syntax, and adds a unique scope for each brace, depending on how nested it is. This, I assume, is determined by the number of `meta.group.c++` scopes assigned to it.

You mention that the closing paren gets an additional `meta.group.c++`. This is the reason for the difference in colors.

It seems wrong to me that there is such a difference between the opening and the closing paren, given that this behavior is not consistent with other cases. For example, when parents are used within a function implementation in a CPP file, both of the parens are assigned with the same amount of `meta.group.c++`.

**Comment by FichteFoll** [comment]
Yes, this is a bug.

**Comment by gwenzek** [comment]
BTW do we really need to have the `meta.block.c++` ?
They seem redundant with `meta.class.c++` in this context.

**Comment by gwenzek** [comment]
Also this issue seems similar to #1406

**Comment by papadokolos** [comment]
Haha, I forgot that I already opened an issue for it! Silly me 😅

However, my former issue describes that bug only for parameter-less methods, and this issue reveals that it is a broader problem.

I guess that one of the issues should be closed, and the other one should be edited to contain all the details?
