### ISSUE TITLE
[LaTeX] `\|` should have a better scope name

### ISSUE THREAD

**Issue by rwols** [sublimehq/Packages#1512]
The `\|` character sequence renders as two vertical parallel lines, usually to denote a metric, e.g. `\| a - b\|^2`. It can also be used in conjunction with `\left` and `\right`, for example `\left\| a - b\right\|^2`. It is currently scoped as

```
\|
% <- punctuation.definition.backslash.latex
%^ constant character.escape.tex
```
However, it seems fitting to scope this the same way as either braces, brackets or parentheses. For example `punctuation.definition.group` or `constant.character.metric` or something. ping @r-stein @randy3k .

**Comment by randy3k** [comment]
it is also used in the form of `x^2 \|_{x=2}`. I am not sure if we should classify it as a group or a metric.

**Comment by rwols** [comment]
I'm not convinced of my own suggestion anymore.
