### ISSUE TITLE
Go to symbol should (could) list the method in the current file as first hit

### ISSUE THREAD

**Issue by saveriomiroddi** [sublimehq/Packages#1513]
(I'm not sure if this is a Packages issue or a Core one; in doubt, I've posted here)

I very frequently use the "Go to symbol" functionality (F12 hotkey) to go to a method definition from an invocation token.

Since the codebase is relatively large, there are colllisions in method names. This is expected, and ST shows a list of the detected definitions.

The UX problem I'm experiencing is that almost all the times, when the definition is inside the same file of the invocation token, the list does not deterministically show that definition first in the list.  
Display in-file matches as first hit in the list would be a significant UX improvement for this functionality, as one would confidently tap F12+Enter, instead of scanning/parsing the list of entries.

I can't say for sure if this is a valid heuristic in general, however, I think it is.

**Comment by keith-hall** [comment]
https://github.com/SublimeTextIssues/Core/issues/14#issuecomment-337143702

**Comment by saveriomiroddi** [comment]
Thanks! Closing the issue.
