### ISSUE TITLE
issue #1521

### ISSUE THREAD

**Issue by advanceddeveloper** [sublimehq/Packages#1521]
```js
'use strict';

var a = {
  ['abc'](a){
    if(a === null)
      return 5;
  },
};

var b = (async a => a)().
  then(a => a).
  catch(a => a);

var c = class{
  async a(){
    await (async a => a);
  }
};

var d = {
  async a(){
    await (async a => a);
  }
};
```

several problems here:

1. computed property name (here method name) `'abc'` is not recognized and method body is messed up
2. in the second example `catch` is highlighted as a keyword, while it is not a keyword, but a method of the promise's prototype
3. asynchronous functions are not recognized in classes
4. same for object literals

this is very annoying and horribly looking highlight, I tried to solve it myself somehow but couldn't, sublime syntax notation seems very confusing and counterintuitive to me. Can this be fixed soon?

**Comment by Thom1729** [comment]
Thanks for finding these. The `async` thing was a simple oversight. The computed property name issue is a mess for technical reasons, and it shouldn't be hard to find examples that break under the new fix, but hopefully those examples shouldn't come up in practical code. I'll have to look at what compromises other parsers make in those situations.

**Comment by advanceddeveloper** [comment]
Fixing computed property names is not much important, I'm happy to hear that you fixed async method handling.

> The lookahead handling computed property names is a bit problematic. The bracket could contain an arbitrary expression, so it's not really possible to look over it with a regexp.

Despite the fact that I don't know much about sublime syntax notation, from logical point of view I'm failing to see why is handling computed property names a problem. Simply parse it like an array literal and if the next character is open parenthese `(`, then it is a method, otherwise it is a property (which can be a method though, but syntactically it's just an ordinary property). I'm unable to see why would it be harder than parsing ordinary array literals...

**Comment by Thom1729** [comment]
The problem is that the syntax tries to apply a `meta.function` scope to methods. Doing this correctly is not possible for computed property/method names.
