### ISSUE TITLE
[Go] syntax chokes on brackets inside function

### ISSUE THREAD

**Issue by JeanMertz** [sublimehq/Packages#1540]
<img width="353" alt="screen shot 2018-05-07 at 20 14 42" src="https://user-images.githubusercontent.com/383250/39717400-76a888fc-5233-11e8-9d85-a90540cda3ed.png">

The above is valid Go syntax, but the syntax rules choke on the brackets inside the function.

**Comment by deathaxe** [comment]
Fixed in ST 3207

**Comment by wbond** [comment]
This issue has been solved by a previous commit, hence it is being closed.
