### ISSUE TITLE
Groovy Syntax Highlighting Choking on Variables in Strings

### ISSUE THREAD

**Issue by ajguyot** [sublimehq/Packages#1542]
The below is valid Groovy String syntax, but seems the Groovy syntax highlighting is failing to pick up the closing curly bracket. This is new in Build 3170.

<img width="941" alt="screen shot 2018-05-07 at 5 45 09 pm" src="https://user-images.githubusercontent.com/3618472/39728903-cf0b20dc-521e-11e8-941f-084b4d5d15b8.png">

**Comment by deathaxe** [comment]
Possible duplicate of #1451.

Fix proposed in #1485.

**Comment by wbond** [comment]
This issue has been solved by a previous commit, hence it is being closed.
