### ISSUE TITLE
PHP syntax highlight error on meta.include

### ISSUE THREAD

**Issue by LucaRosaldi** [sublimehq/Packages#1545]
This bug was introduced on build 3170.

The PHP syntax highlighting does not detect the closing PHP tag `?>`, after a PHP import function (`require`, `require_once`, `include`, `include_once`) when the closing semicolon is omitted.

This is undesirable for programmers who use PHP one-liners such as `<?php include_once(  'some-file.php' ) ?>`.

---

### Summary
The PHP syntax highlighting fails to detect the closing PHP tag `?>` after a PHP import function when the closing semicolon is omitted.

...

### Expected behavior
![expected](https://user-images.githubusercontent.com/1115658/39749234-70e63cbe-52b2-11e8-95ed-c45d932dab1c.png)

...

### Actual behavior
![actual](https://user-images.githubusercontent.com/1115658/39749248-7a3ad310-52b2-11e8-960a-2d831e140d26.png)

...

### Steps to reproduce

Insert a PHP import statement in a html document, without the semicolon at the end

### Environment

* Operating system and version:
  * Mac OS 10.13.4
* Sublime Text:
  * Build 3170

**Comment by keith-hall** [comment]
I would guess it was introduced in https://github.com/sublimehq/Packages/pull/1222, and maybe can be fixed by also popping on `?>` at https://github.com/sublimehq/Packages/pull/1222/files#diff-1e446a02188b28f39505f6fd68756a27R118

**Comment by jfcherng** [comment]
@keith-hall working on it :D
