### ISSUE TITLE
[ASP] Error loading, apparent recursion

### ISSUE THREAD

**Issue by peterh-capella** [sublimehq/Packages#1555]
Environment: Mac OS 10.11.6
Build: Version 3.0, Build 3170

On load of a Classic ASP file (with or without included HTML), the following error appears:

![screen shot 2018-05-10 at 7 48 23 am](https://user-images.githubusercontent.com/1122723/39870889-90a71c7c-5428-11e8-8181-6dca0aa57701.png)

**Comment by keith-hall** [comment]
What third party packages do you have installed? There is no recursion limit in a [clean state](https://www.sublimetext.com/docs/3/revert.html), so knowing which package is causing this will help us determine why.

**Comment by peterh-capella** [comment]
Did a Preferences > Browse Packages... and then listed the contents:

ASP				Sublime-JSHint			pygments
BracketHighlighter		User				pymdownx
CSScomb				backrefs			python-jinja2
Solarized (dark).tmTheme	markupsafe			python-markdown
Solarized (light).tmTheme	mdpopups			pyyaml

(The ASP is new after using the commands under "Installation" on the main repo page.)

Thank for your help and quick reply!

**Comment by peterh-capella** [comment]
Went through Package Control to disable packages in an attempt to find the culprit. Looks like the problem package might be CSS3 from https://github.com/y0ssar1an/CSS3. Disabling that package removed the error. I'll open an issue on that repo.

**Comment by deathaxe** [comment]
Changes in ST core and a different strategy to embedd ASP into HTML (see: https://github.com/sublimehq/Packages/pull/2435) should help reducing the chance to hit sanity limit significantly.

**Comment by wbond** [comment]
This should be fixed now
