### ISSUE TITLE
[HTML] Nested angle brackets <> not highlighted correctly inside DOCTYPE tags

### ISSUE THREAD

**Issue by evandrocoan** [sublimehq/Packages#1565]
`text.html.basic meta.tag.sgml.html meta.tag.sgml.doctype.html entity.name.tag.doctype.html `

![image](https://user-images.githubusercontent.com/5332158/39949413-0da90478-5551-11e8-879b-c0f48d79a0b0.png)

```html
<!DOCTYPE html [
    <!ENTITY nbsp "&#160;">
]>
```

**Comment by deathaxe** [comment]
Neither XML nor HTML support any kind of DTD within the doctypes. PR #985 attempted to add support for it to the XML language without conclusion. It could easily be extended to be used by HTML as well if someone was interested in.

**Comment by wbond** [comment]
This issue has been solved by a previous commit, hence it is being closed.
