### ISSUE TITLE
[Python] Placeholders within parentheses are not highlighted

### ISSUE THREAD

**Issue by deathaxe** [sublimehq/Packages#1568]
In both versions the `author-ts` placeholder is not highlighted as placeholder while `author` and `summery` are.

```python
message = '%(author)s (%(author-ts)s) | %(summary)s' % blame_meta
message = '{author} ({author-ts}) | {summary}'.format(**blame_meta)
```

![screenshot](https://user-images.githubusercontent.com/16542113/39970463-57af72e0-56ec-11e8-93c2-cfd2621d78de.png)

**Comment by FichteFoll** [comment]
The issue is the hyphen within `author-ts`. Iirc the pattern matches for standard identifier names, while both string formatting methods actually operate on dictionaries and (probably) accept arbitrary strings.

**Comment by FichteFoll** [comment]
I've never seen non-identifier placeholders in the wild and I've read a lot of Python code so far. For our own sanity, I'd vote to close.
