### ISSUE TITLE
Multiple regressions with Shell syntax coloring after B3170

### ISSUE THREAD

**Issue by dmilith** [sublimehq/Packages#1570]
Explained on twitter here - https://twitter.com/dmilith/status/995787436973346816

There are plenty examples:

http://s.verknowsys.com/5a552250b3953542905b182aa2d28167.png
http://s.verknowsys.com/55f6f0ec99473612b424d9dbc8cc5c65.png

also "unset" is not colored anymore.. () are colored differently than casething) and so on

**Comment by dmilith** [comment]
If you want full Shell project (to use it as syntax highlighting test), try this one - https://github.com/VerKnowSys/sofin or https://github.com/VerKnowSys/sofin-definitions - all files are shell scripts.

**Comment by wbond** [comment]
Pasting snippets of code here in fenced code blocks here, along with a description of what you perceive the issue to be will be most helpful in terms of looking into issues.

Unfortunately a series of tweets isn’t all that helpful since the lifetime of those tweets may be different than the lifetime of this repository, and it is helpful to be able to look through history in the future to figure out why changes are made.

**Comment by rwols** [comment]
@dmilith, I checked out your repository and things render fine.

If I may guess, it feels like you're using a somewhat older color scheme. The new syntax targets the "minimal scope coverage" scopes [from this document](https://www.sublimetext.com/docs/3/scope_naming.html).

From experience I know that some older color schemes do not highlight such scopes as

* `variable.function`: command invocations receive this scope, e.g. `./path/to/some/script.sh`
* `support.function`: *built-in* command invocations receive this scope, e.g. `unset`, `echo`, `set`, `[ ]`.
* `punctuation.definition.variable`: the dollar-sign in expansion, e.g. `$foo`.
* `punctuation.definition.compound`: the braces of compound statements, e.g. `{ foo }`
* `punctuation.definition.parameter`: the dashes before an option passed to a command, e.g. `foo --some-option`.
* `punctuation.section`: most braces receive this scope, e.g. the braces in `${foo}`, but also the braces in brace expansions.
* `variable.parameter`: the options passed to a command (except for the dashes in front of it), e.g. `tar -x -f`.
* `variable.other.readwrite.assignment`: variable assignments

A sample from your code with the bundled "Mariana" color scheme, which has support for all modern scope names:

![screenshot from 2018-05-14 09-14-38](https://user-images.githubusercontent.com/2431823/39983974-dbf1a52e-5759-11e8-8731-bd02e3f5d7b4.png)

**Comment by dmilith** [comment]
Thank you for your responses. Actually I got it solved by just "telling SLT again" what is default file format for given extensions. It was using something other than "Shell (Bash)" and that was reason of majority of rendering issues I reported.

Indeed I use older syntax coloring (self made), I will use given info to extend it in free time :)

Thanks! <3

**Comment by dmilith** [comment]
Works like a charm :) Even with my super old theme in tmTheme format from times of Textmate :) Thanks again!
