### ISSUE TITLE
[Ruby] Format string syntax highlighted in single-quoted strings

### ISSUE THREAD

**Issue by Nnnes** [sublimehq/Packages#1573]
In `'fe80::1%eth0'`, the `%e` is highlighted as `constant.other.placeholder.ruby`. This would be fine for double-quoted strings, but not single-quoted ones.

I think the problem is line 852 in `Ruby.sublime-syntax`:

            - include: string-placeholder

**Comment by deathaxe** [comment]
I guess you are not right. While string interpolation or escapes other than `\'` or `\\` are not allowed in single quoted strings, something like `puts '%05d' % 123` is valid syntax and outputs `00123`.

Therefore the syntax seems correct.
