### ISSUE TITLE
[html] comments in script tags type=text/html loose color

### ISSUE THREAD

**Issue by greggreenhaw** [sublimehq/Packages#1575]
I use knockoutjs templates where the html exists in a script tac with the type text/html

<script type="text/html" id="tradein.edit" >

HTML comments loose their syntax highlighting in 3.1
![screen shot 2018-05-14 at 6 19 47 pm](https://user-images.githubusercontent.com/1399863/40026468-763ca93c-57a3-11e8-8d59-194a85e06a9e.jpg)

**Comment by Thom1729** [comment]
Please post the code in text form so that it can be tested.

**Comment by greggreenhaw** [comment]
<script type="text/html" id="tradein.edit" >

</script>

**Comment by Thom1729** [comment]
Like so:

\```html
your code here
\```

**Comment by deathaxe** [comment]
PR #1566 contains commit https://github.com/sublimehq/Packages/pull/1566/commits/be2905b899f48ec518c21d85968e7598e15ae659 to move the comment lexer rules into a dedicated section, which could be included in several other contexts requiring comment highlighting.
