### ISSUE TITLE
[JavaScript] Build 3176 | Go to symbol stopped working after upgrade.

### ISSUE THREAD

**Issue by sowizz** [sublimehq/Packages#1576]
Recent Sublime Text upgrade broke _Go to symbol_ functionality for me.
Here is a snippet of a JavaScript class:

    Sc.class.B = class extends Sc.class.A
      {
      /** @protected */
      init()
        {
        }

      /** @protected */
      render()
        {
        }
    };

Previously _init_ and _render_ methods were inside symbol list as you could see below:

![prev](https://user-images.githubusercontent.com/1541634/40106088-1bd87a72-58f5-11e8-9d52-d758c6bb57ef.png)

Currently the list is empty: 

![](https://forum.sublimetext.com/uploads/default/original/3X/f/5/f505f4e30100955f96141311627b804d820f9921.png)

**Comment by Thom1729** [comment]
Fixed by #1614.

**Comment by Thom1729** [comment]
@sowizz Can you confirm that this problem is fixed?

**Comment by sowizz** [comment]
@Thom1729 Yes, @deathaxe fix solved the issue.

**Comment by wbond** [comment]
This issue has been solved by a previous commit, hence it is being closed.
