### ISSUE TITLE
// TODO ..., // FIXME... and other annotations

### ISSUE THREAD

**Issue by gerardroche** [sublimehq/Packages#1579]
None of the syntaxes seem to match annotations in the form: 

```
{COMMENT_START} (FIXME|NOTE|README|TODO|XXX|WIP).*
```

In PHP 

```
// TODO ...
```

In Python 

```
# TODO ...
```

They are sometimes matched when starting with `@`, but usually only in multiline comments e.g. in PHP:

```
/**
 * @todo ...
 */
```

I propose adding scopes for annotations in the form, where the `@` is not required, the annotations are case-sensitive, and they are valid in both single line and multiline comments:

```
^COMMENT_START @?(annotation_names...).*`$
```

If that's agreeable, the only question is what should the scope names be?

**Comment by keith-hall** [comment]
this has previously been discussed at https://github.com/sublimehq/Packages/issues/212 and [on the forums](https://forum.sublimetext.com/t/todo-syntax-highlighting/27604/9?u=kingkeith)

**Comment by michaelblyons** [comment]
FWIW, I use the [annotations][1] plugin for [SublimeLinter][2] to do this. I don't think it should be part of a language syntax.

[1]: https://packagecontrol.io/packages/SublimeLinter-annotations
[2]: https://packagecontrol.io/packages/SublimeLinter

**Comment by Thom1729** [comment]
[JS Custom](https://github.com/Thom1729/Sublime-JS-Custom) highlights `// @flow` comments, but it doesn't support general comment-based annotations. It would be possible to modify the core syntax to allow extensions to easily add such annotations.

**Comment by lepczynski** [comment]
I propose it would NOT be case sensitive, I use
// toDo:
and I've seen ToDo, TODO and todo all over the place : )

**Comment by michaelblyons** [comment]
Thanks to @TheSecEng, there is also the [Colored Comments](https://packagecontrol.io/packages/Colored%20Comments) package. I still assert this should not be a part of a syntax definition.

**Comment by lepczynski** [comment]
> Thanks to @TheSecEng, there is also the [Colored Comments](https://packagecontrol.io/packages/Colored%20Comments) package.  
That does the trick, thanks so much!
