### ISSUE TITLE
Syntax Highlighting odd?

### ISSUE THREAD

**Issue by jensstalder** [sublimehq/Packages#158]
Looks like slashes mess up the highlights now after recent update: 3103

![screen shot 2016-02-11 at 09 45 42](https://cloud.githubusercontent.com/assets/4964495/12972306/5b49f3ce-d0a4-11e5-8e94-6c226b108713.png)

**Comment by wbond** [comment]
Is this the built in JavaScript syntax? If so, it is not designed to handle JSX. For that, I recommend https://packagecontrol.io/packages/Babel.

**Comment by jensstalder** [comment]
ok thanks thats even better.
