### ISSUE TITLE
Show the value of an enum element

### ISSUE THREAD

**Issue by Naor-D** [sublimehq/Packages#1580]
Let's say I have this enum

```
enum {
   Red = 0,
   Blue,
   Green
};
```

And somewhere else the function

```
void foo()
{
    int num1 = Green;
}
```

Is there a way that sublime will show that Green's value is 2 on mouse-hover or something?

**Comment by rwols** [comment]
@TheMan654, your best bet is using clang tooling, e.g. [clangd](https://clang.llvm.org/extra/clangd.html) as a language server together with the [LSP plugin](https://packagecontrol.io/packages/LSP) for the text-editor client.
