### ISSUE TITLE
wrong highlight

### ISSUE THREAD

**Issue by user-982634** [sublimehq/Packages#1589]
* **Language:** JavaScript
* **Sublime version:** 3.0 build 3143
* **Color scheme:** Monaki

### Issue

Division operator is colored like it is a regular expression.

### Test case

Raw code:

```js
~(m,j
/Q,f)(y|Y)<s(N),i,o=i=>a[a(9)](`${a()}${1/i?a(i):1}`)
```

JSON encoded:

```
"~(m,j\n/Q,f)(y|Y)<s(N),i,o=i=>a[a(9)](`${a()}${1/i?a(i):1}`)"
```

Base64 encoded:

```
fihtLGoKL1EsZikoeXxZKTxzKE4pLGksbz1pPT5hW2EoOSldKGAke2EoKX0kezEvaT9hKGkpOjF9YCk=
```

UTF-8 hexadecimal encoded:

```
7e286d2c6a0a2f512c662928797c59293c73284e292c692c6f3d693d3e615b61
2839295d2860247b6128297d247b312f693f612869293a317d6029
```

The test case file can be downloaded [here](https://github.com/sublimehq/Packages/files/2015761/Test.case.zip)

### Screenshot

![](https://user-images.githubusercontent.com/39399001/40220021-06c14e46-5a78-11e8-90d9-b3bfdca6b608.png)

**Comment by keith-hall** [comment]
have you tried with a more recent build of ST or the version of the syntax definition from this repo?

**Comment by github-user-38475** [comment]
Hey, but I've just noticed there is another issue with the latest sublime version: the following `if` statement is not colored properly:

```js
try{}catch{}if(0);
```

I didnt see such issue in old version. can this be fixed somehow?

**Comment by Thom1729** [comment]
The binding identifier in `catch` statements is not optional; your code is invalid. I have opened a PR to improve highlighting in this situation.

**Comment by ghost-98** [comment]
@Thom1729 

> The binding identifier in catch statements is not optional; your code is invalid.

Sorry, but incomplete catch block statements are approved by TC39 and such syntax is implemented in all modern browsers (Chrome, Firefox) and is implemented in Node.js, so I think it is considered as a valid syntax.

But anyway thanks for the fix, amazing!

**Comment by user-982634** [comment]
Closing this, because I opened another issue: #1600
