### ISSUE TITLE
Where to find SublimeText language grammar scope?

### ISSUE THREAD

**Issue by igauravsehrawat** [sublimehq/Packages#159]
I am writing a syntax for new language but I couldn't find a clue, closest I have been is text mate language grammar scope/naming convention which sublime uses http://manual.macromates.com/en/language_grammars
But I noticed it's not complete.

Am i making sense? This should give a context http://stackoverflow.com/questions/10834765/where-to-find-a-list-of-scopes-for-sublime2-or-textmate

Thanks 
Cheers

**Comment by wbond** [comment]
Please see the discussion at https://forum.sublimetext.com/t/a-convention-for-scope-naming/17105.

**Comment by igauravsehrawat** [comment]
Thanks.
