### ISSUE TITLE
Make Vintage nomal mode cursor a pointer (oppose to I-beam)

### ISSUE THREAD

**Issue by gerardroche** [sublimehq/Packages#1592]
In ST the cursor is always an I-beam:

![i-beam](https://user-images.githubusercontent.com/44148/40250771-45fa0646-5acf-11e8-85f3-c2d802f3e365.png)

But in Vintage/Vim normal mode this can be quite jarring and it can be difficult, very difficulty, to make precision selections with the mouse, because we're dealing with a block-like caret.   

I'd like to suggest making normal mode use a pointer, at providing a way to configure it as it pointer for normal mode: 

![pointer](https://user-images.githubusercontent.com/44148/40250773-46243254-5acf-11e8-97d3-1b1062904822.png)

**Comment by deathaxe** [comment]
How is that request related with the syntax packages of this repo?

**Comment by gerardroche** [comment]
It's not, wrong issue tracker: https://github.com/SublimeTextIssues/Core/issues/2323
