### ISSUE TITLE
[javascript] syntax .bind on anonymous functions in object

### ISSUE THREAD

**Issue by greggreenhaw** [sublimehq/Packages#1593]
The following breaks the js syntax highlighting until u add a comma after .bind(this),

var buttons	= [
		{
			classname	: 'autopencil--option--hide',
			label		: '<span class="panel-btn--icon fa fa-eye"></span>',
			click		: function(data,event){

				this.hideMode(!this.hideMode());
				if(!event) return;
				if(this.hideMode())
					$(event.srcElement).css('color','white');
				else 
					$(event.srcElement).removeAttr('style');
			}.bind(this)
		}
	];

**Comment by ghost-98** [comment]
Minimal test case:

```js
~{a:function(){}.a()}
```
