### ISSUE TITLE
[Python] function-call scope not being applied inside if statement parenthesizes

### ISSUE THREAD

**Issue by evandrocoan** [sublimehq/Packages#1599]
Originally reported on:

1. https://github.com/evandrocoan/NotepadPlusPlusColorScheme/issues/2 Python highlighting inconsistent

![image](https://user-images.githubusercontent.com/5332158/40283069-20165944-5c4f-11e8-9341-bfedc7d1bde1.png)

When comparing both scopes, we got the if's one missing the `function-call` scoping:
```
source.python meta.statement.if.python meta.function-call.python meta.qualified-name.python variable.function.python 
source.python meta.statement.if.python meta.group.python meta.function-call.python meta.qualified-name.python variable.function.python 
```

```python
#! /usr/bin/env python
# -*- coding: utf-8 -*-

class Stuff():
    attribute = None

    def add(self):
        local_var = None
        sorted(self.attribute, local_var)

        if ctx.attribute() is not None:
            self.attribute( local_var.varing )

        if( ctx.attribute() is not None ):
            self.attribute = local_var.varing
```

Related:

1. https://github.com/sublimehq/Packages/issues/1441 [Python] Poor invalid scopes while typing

**Comment by deathaxe** [comment]
Are you sure to use the builtin python syntax?

The screenshot shows your snippet with ST3176 vanilla install with Monokai color scheme.

![screenshot](https://user-images.githubusercontent.com/16542113/40305340-6573dede-5cfa-11e8-92c7-9a7df1c35b86.png)

The `ctx.attribute()` is scoped with `meta.function-call` in both if statements. The only difference between both is the additional `meta.group` of the later one.

This is actually what your first post reveals, too.

So maybe I am blind, but from my point of view everything is ok.

**Comment by evandrocoan** [comment]
Thanks, I missed this:

![image](https://user-images.githubusercontent.com/5332158/40333801-b7aee78a-5d30-11e8-89f4-09e6ecda4575.png)

On my theme file. It is excluding the `meta.group`, as the paren from the scope.
