### ISSUE TITLE
[XSL] Build 8103: Error loading XSL syntax package

### ISSUE THREAD

**Issue by RickParmenter** [sublimehq/Packages#160]
Upon opening a XSL file, the following error is presented:

"Error loading syntax ifle 'Packages/XML/XSL/tmLanguage': Unable to open packages/XML/XSL.tmLanguage".

This only became an issue with the latest build, and I currently do not have any issues with XML syntax.

**Comment by titoBouzout** [comment]
related https://github.com/SublimeTextIssues/DefaultPackages/issues/135

**Comment by RickParmenter** [comment]
My thanks, I browsed through open issues and didn't notice any related. Will be closing the issue as such.

**Comment by FichteFoll** [comment]
@RickParmenter thst issue is from a different repositiory.
