### ISSUE TITLE
[ShellScript] Indented comments break syntax highlighting

### ISSUE THREAD

**Issue by rolfbjarne** [sublimehq/Packages#1603]
And quotes in the comment make things even worse

![output_rkjqwi](https://user-images.githubusercontent.com/249268/40422306-425996f0-5e8f-11e8-8ae1-af0bf838747f.gif)

v3.1.1, build 3176

**Comment by rwols** [comment]
I see you have your syntax set to "Shell-Unix-Generic". If you set it to "Bourne Again Shell (bash)", comments should work. See also: https://forum.sublimetext.com/t/problem-with-shell-syntax-for-comments/37087

**Comment by rolfbjarne** [comment]
Yes, hacking around ApplySyntax' decisions made it work. Thanks!
