### ISSUE TITLE
Select .. case coloring in JS

### ISSUE THREAD

**Issue by matt1986** [sublimehq/Packages#1605]
Hi,

Sublime text has been asking me to update for a few weeks, finally did it this morning. The last update seems to have broken the code coloring in Javascript for switch cases when you use brackets in the cases.

For example:

```
switch ($a) {
    case 1:
        functionA();
        break;
    case 2:
        functionB();
        break;
}
```
is okay, but:

```
switch ($a) {
    case 1: {
        functionA();
        break;
    }
    case 2: {
        functionB();
        break;
   }
}
```

Breaks the code coloring. I always, ALWAYS use brackets. To quote my team lead: Life is way too short not to put your brackets. This is a small issue that is very frustrating for me... It leads me to think I have a syntax error, which I tried to find for 10 minutes until I figured it's a problem with ST, and not my code.

I've been using ST for 2 years now and I do love it thoroughly... but this bug makes my life more difficult. I've installed Visual Studio Code for now, please fix this fast before I get used to it! XD

Thanks!

**Comment by matt1986** [comment]
Well I mean... it does work... but I'm not adding semicolons everywhere in my code just so that an IDE is coloring my stuff correctly... I'll use an IDE that simply works better over polluting my code, any day of the week... I have nearly 50 000 lines of code in my website. There is no way I'm going to make a temporary fix just so that ST can color my cases right.

Thank you, but I guess I'll use Visual Studio Code for now, we'll see if I get used to it before this is fixed in ST!

**Comment by Thom1729** [comment]
If the simple workaround is inconvenient, you can just use [the fixed version](https://github.com/Thom1729/Packages/blob/1b39356dac00695124d09ece3c2dc9dcc572b7d3/JavaScript/JavaScript.sublime-syntax). Save that file to `Packages/JavaScript/JavaScript.sublime-syntax`. Then, just remember to remove it when the patch is released and you update Sublime.

**Comment by user-982634** [comment]
@matt1986 Why are your `switch` and `case` statements uppercased (capitalized)? You code is not a valid JavaScript snippet.

**Comment by matt1986** [comment]
Forget the uppercases, I wrote these snippets inside of my browser, I have no clue why I have put uppercase there, of course I have no uppercase in my code :)
