### ISSUE TITLE
[Python] All-caps identifiers mis-highlighted if they contain digits

### ISSUE THREAD

**Issue by davepeck** [sublimehq/Packages#1607]
This is with `3175`.

![bad_highlight](https://user-images.githubusercontent.com/53165/40443579-a14a058c-5e7b-11e8-9b3f-4b711a341edc.png)

My theory is that `THIS_IS_FINE` is properly highlighted but `THIS_IS_FINE8` is not. Perhaps it should be the other way around; I'd just like to make sure they're consistent. 

(Secondarily, perhaps this is all fine and there's simply something I don't know about python that makes combining all caps identifiers with digits un-cool?)

**Comment by keith-hall** [comment]
this is already being fixed in https://github.com/sublimehq/Packages/pull/1577

**Comment by davepeck** [comment]
Closing as duplicate. Thanks!
