### ISSUE TITLE
[Erlang] Syntax highlighting does not work when using Macros with paramters

### ISSUE THREAD

**Issue by tiaanvz** [sublimehq/Packages#1609]
Sublime build 3143

When using macros with parameters (?macroname(par1, par2)), after a while syntax highlighting stops working.

The scope piles on after every statement, e.g.
![image](https://user-images.githubusercontent.com/2661280/40477212-2647ea36-5f46-11e8-81d2-250f4ed5ea80.png)

with scope at cursor as:

source.erlang meta.function.erlang meta.structure.list.erlang meta.structure.tuple.erlang meta.structure.list.erlang meta.expression.fun.erlang meta.structure.list.erlang meta.structure.tuple.erlang meta.structure.list.erlang meta.expression.fun.erlang meta.structure.list.erlang meta.structure.tuple.erlang meta.structure.list.erlang meta.expression.fun.erlang meta.structure.list.erlang meta.structure.tuple.erlang meta.structure.list.erlang meta.expression.fun.erlang meta.structure.list.erlang meta.structure.tuple.erlang meta.structure.list.erlang meta.expression.fun.erlang meta.structure.list.erlang meta.structure.tuple.erlang meta.structure.list.erlang meta.expression.fun.erlang meta.structure.list.erlang meta.structure.tuple.erlang meta.structure.list.erlang meta.expression.fun.erlang meta.structure.list.erlang meta.structure.tuple.erlang meta.structure.list.erlang meta.expression.fun.erlang meta.structure.list.erlang meta.structure.tuple.erlang meta.structure.list.erlang meta.expression.fun.erlang meta.structure.list.erlang meta.structure.tuple.erlang meta.structure.list.erlang meta.expression.fun.erlang meta.structure.list.erlang meta.structure.tuple.erlang meta.structure.list.erlang meta.expression.fun.erlang 

It seems the capture groups for macro-usage does not take parameters into account:

https://github.com/sublimehq/Packages/blob/1cb4c3ec368c751d6f7ecfa16fe02ceff23a1f6b/Erlang/Erlang.sublime-syntax#L441

**Comment by FichteFoll** [comment]
Please provide an excerpt or example file that reproduces the issue.
