### ISSUE TITLE
[JavaScript] Syntax highlighting broken after escaped single quote followed by colon

### ISSUE THREAD

**Issue by wbond** [sublimehq/Packages#161]
```js
var str = '\':';
var str2;
```

From https://github.com/SublimeTextIssues/Core/issues/1098

**Comment by wbond** [comment]
This is fixed by 10073d7f7d559514c9a48230ba6b9986ed4687fa

**Comment by titoBouzout** [comment]
Ok, thank you. This means the current policy for filling bugs related to packages should be done in sublimehq/Packages instead of SublimeTextIssues/DefaultPackages ?

**Comment by wbond** [comment]
In my opinion having the code and the issues in the same place is ideal. I haven't really looked at the DefaultPackages repo yet. Right now we've got four different places for people to report issues, so it can be a bit of work just to keep track of it all.
