### ISSUE TITLE
Java: Syntax problem

### ISSUE THREAD

**Issue by wildeee** [sublimehq/Packages#162]
Problem in argument "finality" colors. It's identifying first the keyword "final", but it's a argument, and should be colored in orange, not red.

Example:

```java
public class ArgumentColor {
	public static void main(String[] args){
		String foo = "Bar";
		new AnyClass().anyMethod(foo);
	}

	
}

class AnyClass {
	public void anyMethod(String finality){
		System.out.println("Printed: " + finality);
	}
}
```

**Comment by wbond** [comment]
This is resolved in df55b74810fa9bed7537d61af02640f3a2800607

**Comment by FichteFoll** [comment]
I like how github's lexer has the same issue. Iirc theirs is based on textmate bundles as well.

**Comment by wbond** [comment]
Yeah, a number of the bugs being fixed are present on GitHub, most likely due to them using the same source tmLanguage files.
