### ISSUE TITLE
[Perl] parenthesis and left shift highlight error

### ISSUE THREAD

**Issue by anmith** [sublimehq/Packages#1620]
Hi,
seems there is an error in the synax highlighting:

$ccc = ($aaa << ($bbb))

The parenthesis around $bbb breaks the highlighting in combination with the left shift, see screenshot:

![perl](https://user-images.githubusercontent.com/3750050/40589513-ba7b0652-61ee-11e8-896d-1216ba48e754.PNG)

Sublime Text 3.1.1 Build 3176

**Comment by deathaxe** [comment]
The current package has a couple of issues.

You could try the syntax definition from PR #1564 and help debugging. It fixes your issue, already.

**Comment by anmith** [comment]
Hi,
thanks for the quick response. I downloaded the file and put it into my Packages directory, solved the problem.
How can I help debugging?

**Comment by rwols** [comment]
@anmith Try to break this new syntax. If you found a bug, report it over at https://github.com/sublimehq/Packages/pull/1564.

**Comment by anmith** [comment]
Haven't found any problem (yet), but will report if I will encounter one.
