### ISSUE TITLE
[Batch] Parentheses in comments are mishighlighted as an invalid syntax

### ISSUE THREAD

**Issue by user-9826342** [sublimehq/Packages#1629]
```batch
rem ()
```

![](https://user-images.githubusercontent.com/39801377/40862177-f24840d0-65eb-11e8-8475-a9680798c9d3.png)

**Comment by rwols** [comment]
This is a duplicate of https://github.com/sublimehq/Packages/issues/1301

**Comment by user-9826342** [comment]
ok then, I'm closing this.
