### ISSUE TITLE
Bash malformed substring operations on variable

### ISSUE THREAD

**Issue by stdedos** [sublimehq/Packages#1632]
Code:

```bash
function pos {
  local CURPOS
  read -sdR -p $'\E[6n' CURPOS
  CURPOS=${CURPOS#*[} # Strip decoration characters <ESC>[
  echo "${CURPOS}"    # Return position in "row;col" format
}

function row {
    local COL
    local ROW
    IFS=';' read -sdR -p $'\E[6n' ROW COL
    echo "${ROW#*[}"
}

function col {
    local COL
    local ROW
    IFS=';' read -sdR -p $'\E[6n' ROW COL
    echo "${COL}"
}
```

Visual:

![image](https://user-images.githubusercontent.com/133706/41164984-240c6d18-6b45-11e8-8361-9cfed79744e1.png)
![image](https://user-images.githubusercontent.com/133706/41165055-4fd75d40-6b45-11e8-80e0-09c4a6e186df.png)
vs
![image](https://user-images.githubusercontent.com/133706/41165007-3251f99c-6b45-11e8-89a7-aeb0f27652b7.png)
![image](https://user-images.githubusercontent.com/133706/41165043-461948f4-6b45-11e8-90cf-adcdf2849cce.png)

_Not sure how to explain it, or search for it. However, I think it's unique and a bug :smile:_

**Comment by rwols** [comment]
The `[` character in `${CURPOS#*[}` is seen as the start of a regex character group. (You can close it by ending the line with `#]`).

In the bash reference manual, the [Shell Parameter Expansion](https://tiswww.case.edu/php/chet/bash/bashref.html#Shell-Parameter-Expansion) tells us that in `${parameter#word}`, The *word* is expanded to produce a pattern just as in filename expansion. Looking at [Filename Expansion](https://tiswww.case.edu/php/chet/bash/bashref.html#Filename-Expansion), we see it is subject to [Pattern Matching](https://tiswww.case.edu/php/chet/bash/bashref.html#Pattern-Matching). Now at this point it's a bit unclear if we should match `[` and wait for a closing `]`, or look-ahead for a pair `[...]`. I'll add a look-ahead for the regex character group.

**Comment by rwols** [comment]
> and I think that whatever pattern should stop in-between the curly braces at-most.

Well...

> what about ${var#[}]} and variants.

Yeah :)

By the way, "file expansion" is also subject to "string expansion", so you can put the offending character in quotes: `CURPOS=${CURPOS#*'['}` will behave the same as `CURPOS=${CURPOS#*[}`
