### ISSUE TITLE
[Markdown] Interpreter highlights Swift function signature as error

### ISSUE THREAD

**Issue by ijaureguialzo** [sublimehq/Packages#1638]
### Summary

Markdown interpreter highlights a function signature written in Swift as a markup error.

### Expected behavior

The text should be taken as plain text.

### Actual behavior

A pink error bar is displayed.

### Steps to reproduce

1. Create a new file and paste this text:
```
updateValue(_:forKey:)
```
<img width="672" alt="captura de pantalla 2018-06-14 a las 11 44 35" src="https://user-images.githubusercontent.com/6746736/41404807-6f4f2356-6fc8-11e8-9232-8c2ab9218e99.png">
2. Change file mode to markdown:
<img width="672" alt="captura de pantalla 2018-06-14 a las 11 44 45" src="https://user-images.githubusercontent.com/6746736/41404831-7f9992d2-6fc8-11e8-9205-e8542b2956c0.png">
3. Press enter and add a blank line:
<img width="672" alt="captura de pantalla 2018-06-14 a las 11 44 49" src="https://user-images.githubusercontent.com/6746736/41404843-874e17a0-6fc8-11e8-8d68-5b8d4f19b6e1.png">
Maybe this is intended behaviour, I'm not sure about that.

### Environment

* Operating system and version:
  * Mac OS 10.13.5 (17F77) 
* Sublime Text:
  * Build 3.1.1, Build 3176

**Comment by FichteFoll** [comment]
If you're using the Markdown syntax, you should be writing Markdown. In Markdown, `_` underscores are used for emphasis, i.e. italics, and should be pairs. If you want literal underscores, you need to escape them with a backslash like `\_`.

When embedding code in Markdown, you can either indent it by 4 spaces or wrap them in triple fences (```` ``` ````), e.g.

``````
```
updateValue(_:forKey:)
```
``````

**Comment by ijaureguialzo** [comment]
Ok, I will close the issue as I understand the parser shouldn't be able to chew anything we throw at it. 

Thank you for your explanation.
