### ISSUE TITLE
css broken?

### ISSUE THREAD

**Issue by ghost** [sublimehq/Packages#1645]
have no idea if thisis the right place for issue report

im using sublime for python and css, but here is weird something that breaks colouring words

![](https://user-images.githubusercontent.com/40703353/42134001-79c9bbc0-7d33-11e8-97f3-39dec856ddf1.png)

see on picture of screen? word "calc" is has different colour than other calc words. And another problem, "important is also not in color itsblack

is this issue or it should be like this is right now? if issue, how can i fix it?

**Comment by rwols** [comment]
Could you please paste the raw text?
