### ISSUE TITLE
[Matlab] Transpose comma as string comma

### ISSUE THREAD

**Issue by turgaybatbat** [sublimehq/Packages#1647]
After transpose comma system is recognizing all lines as string. This can be solved using if there is no new comma on the same line or after three dot on the next line this comma is transpose.

![scshoot](https://user-images.githubusercontent.com/11030535/42205096-21c35060-7eac-11e8-9b93-ac11429f82d7.png)

**Comment by JonathanShor** [comment]
Was this bug introduced recently?

I'm noticing it now, but don't recall seeing it before.

**Comment by thengineer** [comment]
I found another situation where a transpose is wrongly interpreted as string termination:
when transposing a field of a structure, ie. `c = a.b';`. Anything after the `'` will be interpreted as string.

**Comment by blizzardwj** [comment]
> I found another situation where a transpose is wrongly interpreted as string termination:
> when transposing a field of a structure, ie. `c = a.b';`. Anything after the `'` will be interpreted as string.

I have the same problem. But it is OK when I enter `c = (a.b)'`

**Comment by deathaxe** [comment]
My Matlab experiences are quite outdated, but according to https://de.mathworks.com/help/matlab/ref/transpose.html the transpose operator consist of two characters - a dot and a single quotation mark `.'`

So I wonder, whether something like `{...}'` would need to be modified to `{...}.'` or `a.b'` to `a.b.'`?

**Comment by jwortmann** [comment]
A single quotation mark without preceding dot is the conjugate transpose of a complex valued matrix, see [https://www.mathworks.com/help/matlab/ref/ctranspose.html](https://www.mathworks.com/help/matlab/ref/ctranspose.html). For real valued matrices both operators of course have the same effect, and from my experience I would say a single quotation mark without the dot is what most people use in that case.
