### ISSUE TITLE
PHP: syntax highlight bug when "::" operator is used twice

### ISSUE THREAD

**Issue by TomaszGasior** [sublimehq/Packages#1652]
Please see the screenshots:
-> original code: https://i.imgur.com/O6WG1wC.png
-> when a line is commented (by adding `//` manually to the beginning of a line):  https://i.imgur.com/AYtqFZV.png
-> when line is commented (by Ctrl+/ shortcut): https://i.imgur.com/LwwsIrw.png
-> when I removed the second `::`: https://i.imgur.com/2EDyLlj.png

I am able to reproduce this bug:
- on Arch Linux (ST installed from official repository) and on Windows 8.1.,
- with my preferences and with a clean profile,
- with stable builds 3176 and 3170.

The file shown on screenshots is here: https://github.com/TomaszGasior/WizyTowka/blob/master/tests/AddonTest.php

This bug does not exist in 3143 build. I copied "PHP" syntax package from 3143 build to "Installed Packages" and then I started ST 3176 build — the bug doesn't occur.

**Comment by jfcherng** [comment]
Cannot reproduce with the latest syntax. Probably had been fixed by https://github.com/sublimehq/Packages/pull/1588.

**Comment by hrebeniuk** [comment]
Have same trouble with ::

**Comment by TomaszGasior** [comment]
Yes. The bug does not occur when I try to use PHP package from master.
