### ISSUE TITLE
Unable To Import Python Global Libraries

### ISSUE THREAD

**Issue by lbhdc** [sublimehq/Packages#1654]
## Env
```
$ uname -ro  # returns: 4.17.3-200.fc28.x86_64 GNU/Linux
$ python --version # returns: Python 3.6.5
$ which python # returns: /usr/bin/python3
$ subl --version # returns: Sublime Text Build 3176
```
## Sublime Install Method
I followed the `dnf` instructions found here: `https://www.sublimetext.com/docs/3/linux_repositories.html`

## Python Site-Package Locations:
```
/usr/lib/python3.6/site-packages # Default location
$HOME/.local/lib/python3.6/site-packages # User specific libraries from PIP
```
## Error
When I import a package installed locally by PIP I am able to execute without issue. For example when running `test.py`:
```
import numpy
returns:
[Finished in 0.1s]
```

However, if I change `test.py` to:
```
import statistics
returns:
Traceback (most recent call last):
  File "/home/<username>/test.py", line 1, in <module>
    import statistics
ImportError: No module named statistics
[Finished in 0.0s with exit code 1]
[shell_cmd: python -u "/home/<username>/test.py"]
[dir: /home/<username>]
[path: /home/<username>/.cargo/bin:/usr/share/Modules/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/home/<username>/.cargo/bin:/home/<username>/workspaces/go/bin:/home/<username>/.local/bin:/home/<username>/bin]
```
From the python console launched from bash:
```
>>> import statistics
>>> 
```

## Solutions I've Tried
Setting `PYTHONPATH` in `.bashrc` to `/usr/lib/python3.6`
Setting `PYTHONPACKAGES` in `.bashrc` to `/usr/lib/python3.6/site-packages`
Setting `PATH` in `.bashrc` to `$PATH:/usr/lib/python3.6/site-packages`
These changes had no effect on Sublimes behavior.

I created my own python build system `Python3.sublime-build` in `packages/user`. That file contained the following:
```
{
  "cmd": ["/usr/bin/python3", "$file"], 
  "selector": "source.python", 
  "file_regex": "file \"(...*?)\", line ([0-9]+)"
}
```
This solved the import error but broke all of the python related packages I had installed from `package control` (syntax highlighting, autocomplete, linting, etc). That is a non-starter for me as that is the whole reason I am using Sublime-Text.

I tried a number of other things, including editing the defualt python3 build system, and the global default settings. None of which had any effect on the PATH that sublime seems to be searching.

I reverted to the backups I made and am back at a default installation. Any advice would be greatly appreciated.

**Comment by wbond** [comment]
This doesn't sound like an issue with the default syntaxes, which is what this repository contains.

> I created my own python build system Python3.sublime-build in packages/user. That file contained the following:
> This solved the import error but broke all of the python related packages I had installed from package control (syntax highlighting, autocomplete, linting, etc). That is a non-starter for me as that is the whole reason I am using Sublime-Text.

Build systems don't interact with syntax highlighting, autocomplete or linting. That sounds like a different issue. You may have luck seeking help at https://forum.sublimetext.com.
