### ISSUE TITLE
[Javascript] source.js meta.block.js meta.group.js string.template.js is not pushed to the stack when it should

### ISSUE THREAD

**Issue by evandrocoan** [sublimehq/Packages#1657]
I am using the latest javascript syntax from the master branch.

Github renders it correctly:
```javascript
  render() {
      <ol>
          {array_length ?
            reversed_strings.map(function(value, index) {
              console.log(`render() Mapping index ${index} value: ${value}`);
              return <li key={index}>{value}</li>
            })
            :<b></b>
          }
      </ol>
    )
  }
```

But Sublime Text does not: (Does not push `string.template.js` when it is the time )

![image](https://user-images.githubusercontent.com/5332158/42603195-32e525ba-8543-11e8-9976-ce75d19117cf.png)

**Comment by FichteFoll** [comment]
Your code is not correct JavaScript (or ECMAScript) because it has `<ol>` in it. What you are looking for is JSX support, which the default syntax does not provide. JSX support is being tracked at #860.

For now, you should use https://packagecontrol.io/packages/JSCustom.

**Comment by evandrocoan** [comment]
I am using that package, but it has the same problem. Then I opened the standard Javascript syntax, and had the same problem.

**Comment by Thom1729** [comment]
I can confirm that JS Custom supports JSX and should be highlighting that correctly.
