### ISSUE TITLE
Error loading php syntax

### ISSUE THREAD

**Issue by G4Zz0L1** [sublimehq/Packages#1665]
On sublime 3.1.1 build 3176

Without changing, or adding any plugin, suddenly sublime starts complaining this:

`Error loading syntax file "Packages/PHP/PHP.sublime-syntax": Apparent recursion within a with_prototype action: 25000 context sanity limit hit`

**Comment by jfcherng** [comment]
Could you provide a test case to reproduce this problem?

**Comment by G4Zz0L1** [comment]
I just have to open a .php file, and this pops up

![image](https://user-images.githubusercontent.com/13220636/42807378-eb1268f2-89b0-11e8-98cd-bfcbd7b6a8eb.png)

The strange thing it's that it always have worked, for the last 4+ years, with the same identical setup

```json
"installed_packages":
	[
		"1337 Color Scheme",
		"Alignment",
		"All Autocomplete",
		"AndyPHP",
		"ApacheConf",
		"ApplySyntax",
		"AutoFileName",
		"BetterFindBuffer",
		"Bootstrap 3 Snippets",
		"BracketHighlighter",
		"CodeFormatter",
		"Color Highlighter",
		"Color Scheme - Rainbow",
		"ColorPicker",
		"Colorsublime",
		"CSS3",
		"CSScomb",
		"Dayle Rees Color Schemes",
		"Devastate",
		"DocBlockr",
		"DocPHPManualer",
		"EditorConfig",
		"Emmet",
		"ExpandRegion",
		"FileDiffs",
		"Git",
		"GitGutter",
		"GotoDocumentation",
		"HTML Extended",
		"HTML Head Snippets",
		"HTML Snippets",
		"HTML5",
		"HTMLAttributes",
		"HTMLBeautify",
		"HTMLEntity Snippets",
		"ImprovedSQL",
		"Incrementor",
		"INI",
		"JavaScriptNext - ES6 Syntax",
		"jQuery",
		"jQuery Mobile 14 Snippets",
		"jQuery Mobile Snippets",
		"jQuery Snippets pack",
		"Local History",
		"Material Theme",
		"Minify",
		"MySQL Snippets",
		"Neon Color Scheme",
		"Numix Theme",
		"Open-Include",
		"Package Control",
		"Package Syncing",
		"PHP Companion",
		"PHP Completions Kit",
		"PHP-Twig",
		"Phpcs",
		"phpfmt",
		"PHPIntel",
		"PHPSnippets",
		"Predawn",
		"Predawn Monokai",
		"Rainglow",
		"Restart",
		"SFTP",
		"SideBarEnhancements",
		"Smarty",
		"SqlBeautifier",
		"SublimeCodeIntel",
		"Sublimerge 3",
		"Sync View Scroll",
		"Tag",
		"Text Pastry",
		"Theme - Asphalt",
		"Theme - Augmented Reaction",
		"Theme - Brogrammer",
		"Theme - Cyanide",
		"Theme - Flatland",
		"Theme - Freesia",
		"Theme - Glacier",
		"Theme - itg.flat",
		"Theme - Numix",
		"Theme - Orchis",
		"Theme - Phoenix",
		"Theme - Piatto",
		"Theme - Spacegray",
		"Theme - Tech49",
		"Theme - Watson",
		"Tomorrow Color Schemes",
		"Trimmer",
		"WordCount"
	]
```

**Comment by keith-hall** [comment]
Most likely one of those packages has recently been updated and is now causing this issue in your environment. It doesn't happen in a [clean state](https://www.sublimetext.com/docs/3/revert.html).

**Comment by G4Zz0L1** [comment]
I'll try to revert to clean asap and report

**Comment by petrowsky** [comment]
Just reporting in that I started getting the same today.

![screen shot 2018-07-17 at 5 51 25 pm](https://user-images.githubusercontent.com/96553/42829919-a442ecdc-89ea-11e8-9440-c816db474cc3.png)

![screen shot 2018-07-17 at 5 49 45 pm](https://user-images.githubusercontent.com/96553/42829933-a97d562e-89ea-11e8-8989-6b1465b4c064.png)

I've disabled "SublimeLinter", "SublimeLinter-php", "SublimeLinter-phpcs", "SublimeLinter-phplint" and other php related packages. So far,  getting no luck.

**Comment by G4Zz0L1** [comment]
I haven't had a chance to reset sublime on my workstation, I'll check as soon as I get to home, if it does the same.

**Comment by mybooam** [comment]
remove CSS3 work for me

but php syntax not load

**Comment by petrowsky** [comment]
Yep, I think you found the culprit.

I just disabled that and re-enabled all the supporting php mods, such as the linter, and the error is gone. For me the syntax coloring is back for PHP and the linter is working. Of course embedded scopes such as CSS are not coloring.

I don't know enough about the environment to know what is causing the error, but here's the top part of my console output after disabling CSS3. Obviously, the **Error loading scope:source.css: Unable to find syntax file for scope source.css** is going to happen because I don't have anything loading for the CSS scope.

```
startup, version: 3176 osx x64 channel: stable
executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
working dir: /
packages path: /Users/username/Library/Application Support/Sublime Text 3/Packages
state path: /Users/username/Library/Application Support/Sublime Text 3/Local
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/username/Library/Application Support/Sublime Text 3/Installed Packages
ignored_packages: ["CSS", "CSS3", "Emmet", "Emmet Css Snippets", "LiveStyle", "Markdown", "PlainTasks", "Six", "SublimeLinter-jshint", "Vintage", "Vintageous"]
Errors parsing theme:
icon_folder_loading is missing layer0.opacity, setting to 1.0 for backwards compatibility
pre session restore time: 0.942442
using gpu buffer for window
using gpu buffer for window
using gpu buffer for window
using gpu buffer for window
startup time: 1.21789
Error loading scope:source.css: Unable to find syntax file for scope source.css in Packages/PHP/PHP.sublime-syntax
scan: symlink to /Users/username/Sites/drupal/docroot/sites/www.filemakermagazine.com has been seen before, superseding (using inode) previous path: /Users/username/Sites/drupal/docroot/sites/default inode: 12711147
Packages/PHP/PHP.sublime-syntax: embed scope:source.css#rule-list-body could not be found
scan: /Users/username/Sites/drupal/docroot/sites/www.filemakermagazine.com/private has been seen before, skipping (using inode) previous path: /Users/username/Sites/drupal/docroot/files-mag-private inode: 13142668
scan: /Users/username/Sites/drupal/docroot/sites/www.filemakermagazine.com/files has been seen before, skipping (using inode) previous path: /Users/username/Sites/drupal/docroot/files-mag-public inode: 13139542
scan: /Users/username/Sites/drupal/docroot/sites/www.filemakermagazine.com/modules/o_contrib_seven has been seen before, skipping (using inode) previous path: /Users/username/Sites/drupal/docroot/o_contrib_seven inode: 13141216
environment variables loaded using: /bin/zsh -l

```

**Comment by petrowsky** [comment]
And... after disabling CSS3 you'll then get this for any .css file. :)

<img width="532" alt="screen shot 2018-07-18 at 12 08 55 pm" src="https://user-images.githubusercontent.com/96553/42875224-807ee870-8a83-11e8-97de-dafbc1054e47.png">

**Comment by G4Zz0L1** [comment]
So, we have to move the culprit to css3 plugin?

**Comment by petrowsky** [comment]
Yeah, I can confirm that reverting back on the CSS3 does not work. I uninstalled CSS3 via Package Control and pulled the repo directly into Packages then checked out previous tags. Going back 2.1.13 and trying everything up to 2.1.17 didn't fix. Don't know what is causing the issue.

**Comment by G4Zz0L1** [comment]
I've opened an issue on that repo, let's see what they can do. I think we can close this as it's not related to this package.

**Comment by FichteFoll** [comment]
Make sure to enable the default css package shipped with ST after removing or disabling css3 because it asks/requires you to ignore it when installed.

**Comment by petrowsky** [comment]
I did notice this oddball highlight in a .css file. The last paren and semi colon?

<img width="795" alt="screen shot 2018-07-18 at 12 43 43 pm" src="https://user-images.githubusercontent.com/96553/42876943-7ca016e8-8a88-11e8-944e-d1f93a149d2f.png">

**Comment by petrowsky** [comment]
Just throwing out a guess here, but looking at the commit history would this one be a potential cause?

https://github.com/sublimehq/Packages/pull/1562 **More precise php-end-tag scoping**
9f14041368019396f4993eedabf99aaca9efe0cc

I'm not in Sublime on a daily basis so I don't have an exact start date/time for when the issue started for me. But maybe this introduced the conflict with CSS3.

**Comment by seanCodes** [comment]
Disabling the CSS3 package was the solution for me.

**Comment by G4Zz0L1** [comment]
It seems fixed from the CSS3 part, with the https://github.com/y0ssar1an/CSS3/pull/108, I think we can close this

**Comment by DavidPr0** [comment]
Personal just to reinforce, here was also with this same problem and I decided to remove this same package "CSS3".

**Comment by thomashermant** [comment]
I don't have the CSS3 package install and I got this error on Sublime Merge here ...

**Comment by RrNn** [comment]
@thomashermant , not sure why, but I remove the package Naomi and PHP code was highlighted properly. I was having the issue too and I don't have the CSS3 package installed. If you probably have Naomi installed too, you can remove it and restart Sublime.

**Comment by jfcherng** [comment]
Not sure why people prefer that BIG syntax bundle. But if you are using ST 4, the built-in PHP syntax should've caught up PHP 8 syntax. JSX/TS syntax is now built-in. And CSS is always good I assume...
