### ISSUE TITLE
[JavaScript] \u1234 not recognized as function name!

### ISSUE THREAD

**Issue by bounc3-paradise-on-e** [sublimehq/Packages#1679]
Hello!

Take a look at this:

```js
+function \u1234(){}/1//*

console.log('THIS IS NOT A COMMENT!');

//*/
```

the line containing console.log is highlighted like a comment, while it isn't. The problem, is, I think, that st doesn't recognize \u1234 as a function name and then it probably thinks that `{}` is an object and therefore it thinks that `/1/` is a regular expression, and then it thinks that `/*` is start of a multiline comment, and so on, until it reaches the second line and highlights actual code like a comment and messes everything up!

I did my best to format this code snippet like it is formated in the table in issue #1600, I hope I did it correctly. Couldn't attach screenshot atm.

This must be fixed, I think. Any opinions?

**Comment by Thom1729** [comment]
I never got around to implementing unicode escapes in JavaScript identifiers, partly because I thought they were more complicated than they actually are and partly because no one has ever noticed that they weren't supported. The new PR should solve your problem.
