### ISSUE TITLE
[Javascript] Code coloring doesn’t color my code further

### ISSUE THREAD

**Issue by bomenick** [sublimehq/Packages#1685]
I have a problem with Sublime Text 3. My code coloring is not working anymore. A small part in the middle of my code isn't coloring. I'm coding in Javascript and my guess is that I've gone too far with the brackets. And I mean function in function and alot of if-statements. The reason why I think that this is the problem is because when I remove an if-statement. The a small part of the uncolored code will be colored again. My question is, how do I fix it? Without having to remove the if-statements and functions. Because the cleanup is too huge for that small part. There should be a simple fix right ?

Here is an example code of what is happening.

`function coloringTest() {
	if (){
		if (){
			if (){
			if (){
			if (){
			if (){
			if (){
			if (){
			if (){
			if (){
			if (){
			if (){
			if (){
			if (){
		if (){
		if (){
		if (){
		if (){
		if (){
		if (){
		if (){
		if (){
		if (){
		if (){
		if (){
		if (){
		if (){
		if (){
		if (){
		if (){
		if (){
		if (){
			function noColorAtAll() {
			}
		}	
		}	
		}	
		}	
		}	
		}	
		}	
		}	
		}	
		}	
		}	
		}	
		}	
		}	
		}	
		}	
		}	
		}	
		}
		}
		}
		}
		}
		}
		}
		}
		}
		}
		}
		}
		}
	}
}`

**Comment by keith-hall** [comment]
related: https://github.com/sublimehq/Packages/issues/1130

**Comment by rwols** [comment]
I am counting 30 `meta.block.js`, maybe the number of contexts on the stack has a limit?

**Comment by rwols** [comment]
Never mind, it seems to scope the function correctly, it just has no color.

**Comment by bomenick** [comment]
If I remove a couple of if-statements, the function will get color again. So are you sure it has not a limit?

**Comment by bomenick** [comment]
I'm Monokai. The default one. With Sublime Text 3 version 3.1.1 build 3176

**Comment by bounc3-paradise-on-e** [comment]
That is a side effect of the current implementation used for scope name specificity checking. ST is usinga 64-bit integer as a bit flag, with a bit used for sign and a couple for other purposes. It isn't something you can configure. [Source](https://forum.sublimetext.com/t/javascript-highlight-stops-at-61th-nested-level/25271)

**Comment by bomenick** [comment]
Well, that's the end of the line. So I have two options. Try using another editor or fixing our code.

**Comment by Thom1729** [comment]
This issue should probably be migrated to the [core issues tracker](https://github.com/SublimeTextIssues/Core/issues).

**Comment by deathaxe** [comment]
This issue was reported as https://github.com/sublimehq/sublime_text/issues/5283 in the meanwhile.
