### ISSUE TITLE
[JavaScript] Character escapes in object key strings for function definitions not captured

### ISSUE THREAD

**Issue by FichteFoll** [sublimehq/Packages#170]
As mentioned in 10073d7f7d559514c9a48230ba6b9986ed4687fa.

This is not a trivial issue because the entire line is captured in order to highlight the key name as `entitiy.name.function` but it is possible. It would require a "hefty" look-ahead and then some sub-patterns however.

You can close this if considered infeasable.

Example:

```js
let obj = {
    "key with \\escapes\"": function anonymous() {}
};
```

**Comment by wbond** [comment]
This should be fixed with 409ccb469bca8bcc2a5c70c562d1db3428d3015f
