### ISSUE TITLE
[C] enum scope does not close

### ISSUE THREAD

**Issue by ismell** [sublimehq/Packages#1712]
In the following example, void is not scoped as a storage.type

```
static enum APIC_CAPABILITY apic_capabilities(void)
{
....
}
```

**Comment by rwols** [comment]
Here's a minimal C program that compiles

```c
#include <stdlib.h>

#define APIC_CAPABILITY TheEnum
enum TheEnum { kFoo, kBar };

static enum APIC_CAPABILITY apic_capabilities(void) { return kFoo; };

int main() {
  enum TheEnum x = apic_capabilities();
  return EXIT_SUCCESS;
}
```

**Comment by ismell** [comment]
I should have given more code. Not that it matters, but the enum name was capitalized 

    enum APIC_CAPABILITY { kFoo, kBar };

**Comment by ismell** [comment]
https://github.com/sublimehq/Packages/pull/1831 should have fixed it as well.

**Comment by wbond** [comment]
@ismell I've been going through the PRs in chronological order and just got to that and thought it may be the case. 🙂
