### ISSUE TITLE
:line not working for any file except the last one

### ISSUE THREAD

**Issue by gituser823** [sublimehq/Packages#1716]
Hello,

I have a bash script, that opens sublime in the following manner:

subl $DIR $file1 $file2 $file3:10000 $file4:100000 $file5 $file6:1000000

The Problem is now, that it only scrolls to the end of the $file6.
So :line only seems to work for the last file.
Please fix this bug, so lines can be used for every file.
I am on Linux Kernel 4.4.0, Linux Mint.
My Sublime Version is 3.1.1 Build 3176.

Thanks!

**Comment by FichteFoll** [comment]
Please post this issue on the core issues tracker here: https://github.com/SublimeTextIssues/Core/issues

This repository is about the default packages only (which are open source).

**Comment by wbond** [comment]
Closing since this is on the wrong repo. I believe this may have been fixed in the 4xxx build anyway.
