### ISSUE TITLE
[JavaScript] Syntax highlighting – Support for keyword.operator.js missing?

### ISSUE THREAD

**Issue by lehni** [sublimehq/Packages#172]
I have a theme that uses the `keyword.operator.js` key to style JS operators. As of version 3103, that styling is being ignored, and the operators appear to receive the same style as the `keyword` ley. Is this intentional, or am I missing something?

**Comment by lehni** [comment]
It looks like using the `keyword.operator.js` key doesn't work anymore, and all operators fall back to the styling for the `keyword` key. I now have to explicitly specify all keys to match operators: `keyword.operator.js, keyword.operator.assignment.js, keyword.operator.logical.js, keyword.operator.assignment.augmented.js keyword.operator.bitwise.js, keyword.operator.relational.js, keyword.operator.comparison.js`

**Comment by FichteFoll** [comment]
`source.js keyword.operator`

**Comment by lehni** [comment]
That works, splendid!

**Comment by lehni** [comment]
But why the change? This used to work up to now...

**Comment by FichteFoll** [comment]
Because it's better. The scopes are more elaborate now and allow color schemes to specify their colors more precisely. It's just not backwards compatible, but that's okay (in a beta anyway).

**Comment by lehni** [comment]
Thanks for the explanation! I converted my theme now, wasn't hard at all.
