### ISSUE TITLE
[Erlang] incorrect syntax highlighting with first class functions

### ISSUE THREAD

**Issue by StevieSong** [sublimehq/Packages#1724]
The picture below shows that the erlang highlighting is being used and that it is capable of highlighting functions and makes 'valid' green:

![valid](https://user-images.githubusercontent.com/26208374/45723983-1e1a9000-bb82-11e8-90fb-3f581e44bcf5.PNG)

However when we create another function that has a higher order function as an argument, F, and then call F in that function, the syntax highlighter no longer highlights 'valid' as green.

![invalid](https://user-images.githubusercontent.com/26208374/45724127-a5680380-bb82-11e8-8a68-3a91e3f042c6.PNG)

The code compiles and works as expected, where foo returns a new function that calls F so I believe my syntax is correct but please correct me if not as I haven't delved too deep into the languages semantics.

**Comment by deathaxe** [comment]
Will have a closer look into the Erlang syntax. It seems to suffer from a couple more issues.

**Comment by rwols** [comment]
It is hopelessly outdated.

**Comment by deathaxe** [comment]
Yep. That's why I already started cutting it into pieces. Guess it will end up in a rewrite of nearly everything. But the language itself looks pretty deterministic. So rewriting seems not to be too difficult.
