### ISSUE TITLE
[C] Incorrect variable scope

### ISSUE THREAD

**Issue by ismell** [sublimehq/Packages#1729]
Here is an example:

    struct cb_boot_media_params *const bmp =
			(struct cb_boot_media_params *)ptr;

The closing `)` highlights as invalid.

**Comment by rwols** [comment]
not here on the master branch:
<img width="402" alt="schermafbeelding 2018-09-20 om 18 59 31" src="https://user-images.githubusercontent.com/2431823/45834410-57c8d380-bd07-11e8-937e-d2735aabd55e.png">

**Comment by ismell** [comment]
Cool, guessing it's been fixed then?

**Comment by rwols** [comment]
Well, not entirely sure. Perhaps it's caused by something higher up in the file?
