### ISSUE TITLE
Incorrect function

### ISSUE THREAD

**Issue by freebooks123** [sublimehq/Packages#1738]
```c++
void ca(int x, int y, int z){
  /* ... */
}

void checkAct(void **ptrs){
  /* ... */
}

void checkAction(Action *act){
  /* ... */
}
```

Press <kbd>Ctrl</kbd>+<kbd>R</kbd> and type `ca`

### Expected

Navigate to function `ca`

### Actual

st navigates to `checkAct`

![](https://user-images.githubusercontent.com/43790300/46450344-14ec0e80-c791-11e8-8d75-6f3e29815fe2.png)

# Issue

I don't like this behavior. When I type function name (call it *name*), I want the following behavior:

1. If there is a function with name *name* then navigate to it.
2. Otherwise enumerate all functions that literally contain *name* in their name
3. If there is at least one such function, then navigate to the function with the shortest name (and among shortest names, the one with alphabetical precedence)
4. Otherwise, enumerate all function names that contain letters of *name* in the same order
5. If there is at least one such function, then navigate to the function with the shortest name (and among shortest names, the one with alphabetical precedence)
6. Otherwise do whatever.

I want the behvaior I explained above. How to achieve it? Basically, if I type `ca`, I want function `ca` and not `checkAct`. Also, when I type `act` I want `checkAct` and not `checkAction`. Can this be fixed somehow? I believe that st selects `checkAct` because st probably looks for starting letters of words (**c**heck**A**ct - **ca**), but I don't like it.

I believe average user like it so I'm not asking this to be fixed. I just ask how can I fix it for myself only, so that it works for me like I want it to work, like explained above.

Which settings do I need to configure? Do I need a plugin (just to mention, don't recommend plugins, they just need to be like a last resort, but I would like to fix it somehow in settings if possible, I don't want new plugins).

---

*(Edit: removed redundant pings)*

Sorry for the pings, but I'm a bit desperate about this problem, I aksed on forum but got no response for a long time and now I need to finish my project and this searching behavior is making me so mad. Please help.

Thanks!

**Comment by keith-hall** [comment]
I believe the internal fuzzy matching algorithm ST uses to match and order results is not configurable. Can you link to your forum post please?

**Comment by freebooks123** [comment]
Ok if not possible to modify internal algorithm, can we export symbols in such way that the current algorithm properly matches them?

See [this article](https://github.com/sublimehq/Packages/files/2444916/sublime-text-unofficial-documentation.pdf). It says that a user may configure syntax such that function and class and struct names are exported differently as searchable symbols.

So, is it feasible? I don't really care what will be displayed in the popup box, I just want to type `ca` and navigate to `ca`, that's all. See pages 103 and 104 in the provided article. It explains that using oniguruma regex a user may modify symbols before exporting. Can we therefore lowercase function names and thus prevent st from looking at capital letters and searching by it? Or something like that?

---

Also, another example of how insane the algorithm is:

```c++
// C++
void P(int x, int y=5);
void PQ(int z);
```

![](https://user-images.githubusercontent.com/43790300/46453158-44564780-c7a0-11e8-9c2e-4a9c6fa1bd08.png)

```js
// JavaScript
function P(x, y=5){}
function PQ(z){}
```

![](https://user-images.githubusercontent.com/43790300/46453170-52a46380-c7a0-11e8-9b23-31ac28b9060a.png)

How absurd is this? Same code, but in one programming language it selects `P` and in another selects `PQ`. So, my questions is, can we export symbols in such a way to always select the function whose name literally contains the typed text?

**Comment by djspiewak** [comment]
This is kind of the downside of fuzzy matching. There's really no way to configure it. Without knowing the internals of ST's index database, I would guess that the reason the C index shows the functions in an inverse order from the JavaScript index comes down to the fact that the text in the JavaScript names is different, meaning that the index content will be different and likely resulting in a different hash order.

**Comment by keith-hall** [comment]
it's also worth nothing that ST disables some functionality like goto definition when the symbol name consists of less than 3 characters, in some cases it can make sense to use more descriptive/verbose names,then presumably this fuzzy matching behaior will also be less of an issue

**Comment by cixtor** [comment]
@freebooks123 what are you mentioning me in this issue for? I don't work for Sublime HQ.

**Comment by kleinfreund** [comment]
Please don't ping a random list of contributors to an open source project. This is not appropriate.

**Comment by freebooks123** [comment]
@kleinfreund 

![](https://user-images.githubusercontent.com/43790300/46466701-4a621d80-c7cc-11e8-9506-fe37cba20137.png)

@keith-hall 

Have you taken a look at the article? Can we export the symbols in lowercased form? Can you write an example of what I need to put in my .tmpreferences file?

**Comment by freebooks123** [comment]
As it seems, this community is so stupid, along with the text editor itself. I'm definitely moving to atom or notepad++ or some other normal text editor.

also I'm not going to say thanks, because I didnt get any help here.
