### ISSUE TITLE
[Go] Factored import statements are awkward

### ISSUE THREAD

**Issue by twhb** [sublimehq/Packages#1754]
Option 1: Type it manually. Sublime doesn't auto-indent after you type `import ({enter}` so you need to do it manually; the `)` trails your cursor as you type; Sublime doesn't auto-dedent when you're done so you need to do it manually; your cursor ends up before the `)` so it's a little more work to move on.

Option 2: Use the included `Import` snippet. You need to type your first import, then type `({enter}`, then manually indent but without using tab or you'll exit the snippet, then type the rest of your imports, then delete the indent, then type `)`. It's much more awkward than just doing it manually.

I think this is an important thing to get right. Virtually all Go files have multiple imports, and Golang specifies this style for them.

Suggestion 1: Pressing enter in Go when the cursor is between `()` should act as it does when the cursor is between `{}`, or between `<tag></tag>` in HTML: put the closing character on its own line, put the cursor in a middle line, and indent the cursor.

Suggestion 2: change the Import snippet to `import ({newline}{indent}$0{newline})`. Single imports are more rare, and even when they are used, it's arguably a good idea to write them factored anyway (consistency, ease of adding imports (likely to happen), good git diffs when adding imports).

**Comment by twhb** [comment]
@deathaxe Yep, just tried it and manual typing behavior matches my first suggestion. There's no snippet, but I think that's no big loss with the first part resolved. I'd consider that syntax rework to be a resolution to this issue, if it gets merged.

**Comment by deathaxe** [comment]
A couple of snippets were deleted by the PR, keeping only some basic ones. Snippets/Completions tend to interfere with 3rd-party packages or even language-servers. So it is better to not have too much of them in the default syntaxes. They are easier and more flexible to handle via packages.

**Comment by deathaxe** [comment]
@wbond Seems fixed

**Comment by twhb** [comment]
Confirmed fixed in build 3184, not yet in current stable (3176). Thank you!
