### ISSUE TITLE
Ambiguity about license 

### ISSUE THREAD

**Issue by shivarajnaidu** [sublimehq/Packages#176]
I have seen license file in this repository.
but i got confused . is that license indicating sublime as open source to freely share and modify ?
 [ Packages/LICENSE ](https://github.com/sublimehq/Packages/blob/master/LICENSE)

**Comment by jfcherng** [comment]
This repo is only for Default Packages in Sublime Text.

**Comment by shivarajnaidu** [comment]
Oh .. OK .. So its not full code of sublime text ?

**Comment by jfcherng** [comment]
Obviously, no.

**Comment by wbond** [comment]
Only the default packages in this repo are covered by the license file.
