### ISSUE TITLE
Escape key doesn't close many pop ups

### ISSUE THREAD

**Issue by lucidsushi** [sublimehq/Packages#1765]
Using Version 3.1.1, Build 3176

`Ctrl + Shift + P` to bring up the command pallet, but pressing `escape` does not close it, same for a bunch of other things like `find..` / `replace..` bottom menus..

It only partially works when I hit `ctrl+;` to show overlay, and now suddenly the `escape` would be able to close the pop up

**Comment by deathaxe** [comment]
This would better be filed at https://github.com/SublimeTextIssues/Core/issues

This repo is for syntax related packages only.

**Comment by FichteFoll** [comment]
Escape should be able to close all of these. You might have a third-party package or a user key binding interfering. Try disabling a couple plugins, checking for key overrides or reverting.

**Comment by lucidsushi** [comment]
Thanks everyone, sorry for opening in the wrong place. I disabled all the packages and and it indeed was an issue with the plugin, will look into it from that angle... closing this!
