### ISSUE TITLE
[JavaScript] Comments

### ISSUE THREAD

**Issue by ghost** [sublimehq/Packages#1766]
valid js:

```js
console.log(!1-<!--1-->1<1);/*
(1*/1/));
```

wrongly highlighted:

![](https://user-images.githubusercontent.com/45014721/48437245-13930600-e781-11e8-8ae7-7e16ac8a34f5.png)

please fix
/cc @Thom1729 and others
read spec:

![](https://user-images.githubusercontent.com/45014721/48437622-222ded00-e782-11e8-873b-74f42e91b282.png)

**Comment by Thom1729** [comment]
That's [Annex B](http://www.ecma-international.org/ecma-262/#sec-additional-ecmascript-features-for-web-browsers) behavior:

> These features are not considered part of the core ECMAScript language. Programmers should not use or assume the existence of these features and behaviours when writing new ECMAScript code. ECMAScript implementations are discouraged from implementing these features unless the implementation is part of a web browser or is required to run the same legacy ECMAScript code that web browsers encounter.

In particular, it is not "valid JS".

The core JavaScript syntax used to support HTML comments, but it was buggy. That support was removed in #928. The HTML syntax was simultaneously augmented to handle the ancient practice of wrapping script contents in HTML comments.

The spec further stipulates:

> this extension is not allowed when parsing source code using the goal symbol Module

So we probably don't want to put this behavior in the JavaScript syntax. (There is no reasonable way of knowing from Sublime whether a JavaScript file is a script or a module, but it's very unlikely that anyone would use this misfeature in a JavaScript file anyway; it's a compatibility hack designed for code in `<script>` tags.)

Have you encountered this in real-world JavaScript code?  I'm not opposed to implementing Annex B features in principle, but I'm not sure there's a realistic use case here. It's a clunky compatibility hack for pre-1996 browsers that was never properly part of the language. It was documented in the spec, but only in a historical annex a decade or more after it was functionally obsolete. The spec warns developers not to use it and recommends against implementing it. The HTML syntax definition should handle the comments in most practical cases, and when it doesn't it's unlikely that highlighting will be significantly affected.

That's not to say that I'd complain if someone managed to bodge an Annex-B-compliant implementation into the HTML syntax somehow, as long as it didn't cause other problems.
