### ISSUE TITLE
[C and C++] Incomplete tagging of operators/punctuation

### ISSUE THREAD

**Issue by cschreib** [sublimehq/Packages#177]
I use a custom color theme that highlights punctuation and operators in C and C++. For example, the ```::``` and ```()```in ```MyClass::MyFunction()```. I find it very convenient since these languages use a fair amount of punctuation, and I find that coloring these symbols clearly improves readability. Unfortunately, the current C and C++ parser in Sublime are very selective in which punctuation symbols they actually declare as, e.g., ```punctuation.definition.parameters.c```.

Below is an example of what I am currently seeing. The code is silly, and is only meant to display the inconsistencies.

![screenshot-area-2016-02-15-010245](https://cloud.githubusercontent.com/assets/2236577/13037382/dcd943bc-d37f-11e5-9c65-cfac08468aab.png)

And here is a list of what should be identified as punctuation in this snippet, but that is missed by the current parser:
* line 1: the ```:``` signalling inheritance
* line 1: the ```,``` separating the base classes
* line 2: the ```:``` following ```public``` (which should also be highlighted as a keyword in this context, by the way, as well as ```private``` and ```protected```)
* line 3 and 14: the ```()``` enclosing the function parameters
* line 3, 9, 14 and 16: the ```{}``` enclosing the function body
* line 4: the ```()``` enclosing the condition of a control keyword (```if``` in this case); note that currently only the first parenthesis is properly tagged
* line 4 and 6: the ```{}``` delimiting control scope
* line 5: all C and C++ operators: ```=```, ```+```, ```*```, ```/```, ```,```, ```()```, ```%```, ```^```, ```&```, ```&&```, ```==```, ```!=```, ```<```, ```<=```, ```!```, etc
* line 5, 8, 10 and 15 (etc) : the ending ```;```
* line 8 and 15: the "namespace operator" ```::```
* line 13 and 17: the ```{}``` enclosing the namespace content
* line 13: the ```<>``` enclosing template parameter declarations
* line 13: the ```,``` separating the template parameters
* line 13: the ```...``` marking variadic templates
* line 14: the ```,``` separating function arguments
* line 14: the ```&```, ```&&``` and ```*``` type qualifiers
* line 14: the ```...``` marking template argument packs
* line 15: the ```<>``` enclosing template parameters
* line 15: the ```()``` enclosing parameters of the function call
* line 15: the ```...``` marking pack expansion
* line 20: the ```,``` separating multiple declarations
* line 22: the ```()``` enclosing parameter initialization and the ```,``` separating them
* line 23: fixing this line, which should appear as the one above (missing coloring for ```()``` enclosing parameters, and ```:``` indicating initalization of members) 
* line 26: the ```{}``` enclosing an initializer list and the ```,``` separating the values
* line 27: the ```[]``` operator
* line 28: the ```.``` and ```->``` access operators

Here is what I would expect it to look like (manual editing of the above image):

![screenshot-area-2016-02-15-0102452](https://cloud.githubusercontent.com/assets/2236577/13037513/5fb07d76-d382-11e5-9a63-76905f2e28e0.png)

I had achieved such kind of result by tweaking the previous syntax system (tmLanguage) and did not notice any performance issue.

**Comment by cschreib** [comment]
The code snippet, for testing.

```c++
struct test1 : testbase1, testbase2 {
    public :
    void function1() {
        if (test) {
            a = *b + &c;
        }

        addr = test1::function1;
    }
};

namespace test2 {
    template<typename T, typename ... Args>
    void function2(int& param1, int* param2, Args&& ... args) {
        std::string s = std::get<0>(args)...;
    }
}

struct test3 {
    int i, j, k;

    test3() : i(0), j(1), k(2) {}
    explicit test3(int) : i(0), j(1), k(2) {}

    void foo() {
        a = {1,2,3,4};
        a[0] = a[1];
        a.b += a.b->c;
    }
};
```

**Comment by wbond** [comment]
There is a version of the C/C++ rewrite at https://github.com/sublimehq/Packages/tree/c-rewrite if you want to do some testing. To do so, you should check out the c-rewrite branch and follow the directions at https://github.com/sublimehq/Packages#installation.

Just note that Objective C and Objective C++ are broken right now since I need to rewrite them to work with the new C and C++ syntaxes.

I haven't specifically used your example during development, but from looking over the list, it does seem like many/most of them now have scopes.

**Comment by cschreib** [comment]
Great! I'll try it out as soon as I can and report back. Thanks for the feedback.

**Comment by wbond** [comment]
The rewrite has been merged into master. Let me know if you see any issues.

**Comment by cschreib** [comment]
Looks better indeed! I found a glitch though:
```c++
template <typename T = U<V>>
//                         ^ keyword.operator.comparison.c
```

**Comment by cschreib** [comment]
And another one with lambda functions:
```c++
auto lambda = []() { return 0; };
//            ^^ source.c++
```

**Comment by wbond** [comment]
The issues from your last two comments have been addressed in recent commits to the master branch.

**Comment by cschreib** [comment]
Confirmed, thank you very much!
