### ISSUE TITLE
Bash: '#' (comment) overrides command-substitution range

### ISSUE THREAD

**Issue by stdedos** [sublimehq/Packages#1781]
I found a fancy way to add comments in a multiline command:
```bash
bc | ` # get quarks ` \
ac |  ` # remove flair` \
ab ` # important; this and that ` "${USELESS_TEXT}" | ` # match text` \
cat

```

Bash is running it _(not ... it, but the un-obsfucated one :stuck_out_tongue_closed_eyes:)_, Github is (as of commit time) highlighting them correctly, however, Sublime is not:
![image](https://user-images.githubusercontent.com/133706/49222042-7ae8c100-f3e3-11e8-9cce-2e84e2580668.png)

_Note that his "fancy syntax" **does not apply** to `$()`!_

Build 3176

**Comment by rwols** [comment]
I was playing around with `embed` to solve this problem (i.e. embed the syntax itself when encountering a backtick), but the idea starts to fall apart when you're trying to use yet another pair of escaped backticks, as in
```
echo `echo \`echo hello, world!\``
```
note that this is the same as
```
echo $(echo $(echo hello, world!))
```
What needs to happen is that the `escape` rule of the `embed` should come *after* the prototype, not *before* the prototype. I'm not sure if asking for such a feature is too much of a hassle for the sublime text team.

I do like to note that using `embed` allows me to remove a ton of boilerplate code. The only problem seems to be backticks-in-backticks. Tradeoffs...

**Comment by stdedos** [comment]
> ```
> echo `echo \`echo hello, world!\``
> ```
> note that this is the same as
> 
> ```
> echo $(echo $(echo hello, world!))
> ```

Indeed, but, as I noted:

> _Note that his "fancy syntax" **does not apply** to `$()`!_

so writing

```bash
bc | ` # get quarks ` \
ac |  $(# remove flair) \
ab ` # important; this and that ` "${USELESS_TEXT}" | ` # match text` \
cat
```

It's not working (`#` starts a comment, and then the rest never get to close `)`) -- i.e. Github Markdown does the formatting correct again!

```bash
bc | ` # get quarks ` ac |  $(# remove flair) ab ` # important; this and that ` "${USELESS_TEXT}" | ` # match text` cat

# vs

bc | ` # get quarks ` ac |  ` # remove flair` ab ` # important; this and that ` "${USELESS_TEXT}" | ` # match text` cat
```

and also this is highlighted correctly (leaving an image here for the sake of archiving it, just in case Github decides to "update" the syntax ![image](https://user-images.githubusercontent.com/133706/49568871-f2b27080-f93a-11e8-8b82-72493c45ebce.png))

Obviously fix, or no fix, it's up to the one who decides what is what. But it _**is**_ a limitation 😄

**Comment by deathaxe** [comment]
I've got a fix for that issue which can be pushed once #2310 is merged.

Here's a little teaser.

![grafik](https://user-images.githubusercontent.com/16542113/77582403-9da7be80-6edf-11ea-8559-fbd0610e89c2.png)

**Comment by stdedos** [comment]
Oho! It would look **so much more awesome** if Github-image-scaling wasnt doing _this_ ...

I am wondering, what's your theme / font?

**Comment by deathaxe** [comment]
```
	"color_scheme": "Packages/Brackets Color Scheme/Brackets Dark.sublime-color-scheme",
	"font_face": "iosevka SS09 Light",
	"theme": "DAneo Elegant.sublime-theme",
```

The font is a customized one with a bit more horizontal character spacing (thanks to @odatnurd).

The color scheme received some local patches to correctly highlight operators and punctuations (and some other tweaks).

**Comment by stdedos** [comment]
Sounds pretty basic @deathaxe 😄

Thanks for sharing
