### ISSUE TITLE
Highlight Frontmatter in Markdown as YAML

### ISSUE THREAD

**Issue by FichteFoll** [sublimehq/Packages#1783]
Markdown documents may occasionally have a so-called "frontmatter" that is frequently using YAML syntax.

Using an embed, highlighting of this should be trivial.

Before settling onto YAML, however, have you seen other kinds of frontmatter in Markdown documents and if yes, which syntax do they use and how are they separated from the body?

**Comment by deathaxe** [comment]
The only situation I saw frontmatter was with mdpopups, which uses YAML.

**Comment by FichteFoll** [comment]
Jekyll (and github issue templates) are other examples of YAML front matter.

**Comment by jrappen** [comment]
dropping a few related links for reference

---

### Codemirror

* https://codemirror.net/mode/yaml-frontmatter/index.html

### Gatsby JS

* https://www.gatsbyjs.org/docs/adding-markdown-pages/#note-on-creating-markdown-files

### Hugo

* https://gohugo.io/content-management/urls/#yaml-front-matter

### Jekyll

* https://jekyllrb.com/docs/front-matter/

### Python Frontmatter

* https://github.com/eyeseast/python-frontmatter

### Remark JS

* https://github.com/remarkjs/remark-frontmatter

### VuePress

* https://vuepress.vuejs.org/guide/markdown.html#front-matter
* https://vuepress.vuejs.org/guide/frontmatter.html#front-matter
