### ISSUE TITLE
[C++] "downto" opreator breaks highlighting

### ISSUE THREAD

**Issue by xavierholt** [sublimehq/Packages#1791]
I'm on Sublime 3.1.1 build 3176, and the ["downto operator"](https://stackoverflow.com/questions/1642028/what-is-the-operator-in-c) seems to break syntax highlighting:

<img width="253" alt="screen shot 2018-12-02 at 9 14 43 pm" src="https://user-images.githubusercontent.com/1435765/49354344-51e05e80-f677-11e8-87a6-fd77a2c7f065.png">

The same code gets highlighted just fine when interpreted as C instead of C++ - maybe it's something to do with template syntax?

**Comment by xavierholt** [comment]
Might be related to / fixed by https://github.com/sublimehq/Packages/issues/1456.

**Comment by rwols** [comment]
This was fixed by https://github.com/sublimehq/Packages/pull/1558 and is present in dev builds.

**Comment by xavierholt** [comment]
Thanks for the reference!  I'd thought I was testing with the latest syntax definition, but I must have misconfigured it somehow.
