### ISSUE TITLE
[C/C++] references none-existent C# scopes

### ISSUE THREAD

**Issue by deathaxe** [sublimehq/Packages#1792]
The following example shows one of multiple scope includes from C# syntax which don't exist. The issue exists for all C style syntaxes.

https://github.com/sublimehq/Packages/blob/14a35f641f348b4ee0ead558e5ee474f7255b50f/C%2B%2B/C%2B%2B.sublime-syntax#L1862-L1864

**Comment by deathaxe** [comment]
Sorry mates, missunderstood the `#` :)

**Comment by FichteFoll** [comment]
That's what I get for only adding a punctuation scope to the `#` in PackageDev, huh. :thinking:
