### ISSUE TITLE
[javascript] How to prevent the Tag like {/if} recognizes as a Regexp String begin?

### ISSUE THREAD

**Issue by Totn** [sublimehq/Packages#180]
Use: ST3
when I use the tags such as:
`{if $a}
.....
{/if}`
in the js code,
then the tag `{/if}` will be identified to A Regexp String start,  and the code after the tag will highlight as 
Regexp content until meeting the end tag of Regexp like '/';
How can I make ST3 ignore the tags '{/if}', '{/loop}'

**Comment by wbond** [comment]
What templating library are you using? I could be mistaken, but I don't think native JavaScript supports this, hence the issue with the JavaScript syntax getting confused.

The correct solution would be to use a syntax designed for the templating language you are using.

**Comment by Totn** [comment]
@wbond The templating library is HTML, which I use for PHP outputting
the tags `{if $a} ... {/if}` is defined in PHP and using in the JavaScript code of HTML;
I had try to modify the HTML.sublime-syntax, but didn't found anything about JavaScript's Regexp;
Now what I want is that the tags like '{/if}' or '{/loop}' in the HTML'script will not recognizes as Regexp ...
PS: this issue came out when ST3 update to the latest version;

**Comment by wbond** [comment]
It was just by chance that the syntax highlighting worked for you before.

It isn't clear to me the name of the templating language you are using. From looking at the syntax, it appears to be similar to Smarty. Perhaps try the syntax at https://packagecontrol.io/packages/Smarty.

**Comment by Totn** [comment]
Yes, the templating language is simple version of Smarty, less tags and simple syntax;
and thinks for your idea, but it's not working well;
after intalling the Smarty package and change to it;
the issue still show like that:
![bug_one](https://cloud.githubusercontent.com/assets/8908697/13131299/85bfa76c-d625-11e5-8845-ecacb46a05fb.jpg)
![bug_two](https://cloud.githubusercontent.com/assets/8908697/13131310/9a8b08e4-d625-11e5-9a5e-108c79b19eff.jpg)

**Comment by wbond** [comment]
There won't be a way to support Smarty-like syntax via the JavaScript syntax. You would need to use a third party syntax designed to handle it.
