### ISSUE TITLE
[Python] meta.function-call.python scope no longer applied inside function calls

### ISSUE THREAD

**Issue by kylebebak** [sublimehq/Packages#1802]
## Env
OSX 10.12.6, ST 3184.

## Description
The `meta.function-call.python` scope is no longer being applied inside Python function calls. It's applied outside the function, but inside only the `meta.function-call.arguments.python` scope is applied.

From what I understand, ST's Python syntax is based on MagicPython, which applies `meta.function-call-python` [to **all** of the function call, including its args](https://github.com/MagicStack/MagicPython/blob/master/test/calls/call1.py).

In any case, this is probably a regression. I have a package, Requester, which depends on the application of `meta.function-call.python` to all of the function call for some of its functionality, and this change caused part of the package to break.

This may have been introduced [in 3181](http://www.sublimetext.com/updates/3/dev/release_notes.html), which added some improvements to syntax highlighting for various languages.

Here's a screenshot showing the problem.

<img width="731" alt="screen shot 2018-12-07 at 5 13 43 pm" src="https://user-images.githubusercontent.com/1524088/49677266-7ce5fc00-fa43-11e8-853b-e14054adafd0.png">

**Comment by kylebebak** [comment]
@FichteFoll 

I found the commit, 60e1b60, that stopped `meta.function-call.python` from being applied to the entire function call.

If I revert the Python syntax file to its state before this commit, `meta.function-call.python` is applied correctly.

I don't know enough about syntax highlighting to submit a PR, but I figure the fix is relatively simple because we know which commit caused the problem.

Here's a screenshot showing how it used to work.

<img width="803" alt="screen shot 2018-12-07 at 9 43 25 pm" src="https://user-images.githubusercontent.com/1524088/49681537-44f1af80-fa69-11e8-8de3-cf143f8b0fea.png">

**Comment by michaelblyons** [comment]
I confess I do not know much about plugin architecture, but could you not change [the selector you look for][1] to be `source.python meta.function-call` rather than [`meta.function-call.python`][1]?

[1]: https://github.com/kylebebak/Requester/blob/660ebaf93aff0081c70c84f3af645537b4dc5a53/commands/request.py#L182

**Comment by kylebebak** [comment]
@michaelblyons 

Regardless of what you know about plugin architecture, you definitely know a lot more than I do about syntax highlighting!

That fixed the problem, and you taught me two things: you can target multiple scopes with a selector, and you can target the prefix of a scope without having to match all of it.

Thanks a bunch! I'll close this.
