### ISSUE TITLE
[Go] argument indexed fmt verb is not set to constant.other.placeholder.go

### ISSUE THREAD

**Issue by kortschak** [sublimehq/Packages#1804]
Go fmt verbs allow the inclusion of a parameter list index. The current Go syntax definition misses this.

For example in `"a:%q a again:%[1]q\n"` where `%[1]q` should be given constant.other.placeholder.go scope just as `%q` is.

![screenshot from 2018-12-08 21-45-52](https://user-images.githubusercontent.com/275221/49685406-c82b0800-fb32-11e8-9fcb-ed5dcbc3dda9.png)

**Comment by mitranim** [comment]
Fixed via #1840. Thanks for reporting!
