### ISSUE TITLE
[JavaScript] yield template string aren't highlighted property

### ISSUE THREAD

**Issue by kufii** [sublimehq/Packages#1809]
When yielding template strings, yield doesn't seem to be highlighted properly. When yielding any other type of object it is.

![image](https://user-images.githubusercontent.com/4913552/49830386-07d63780-fd5f-11e8-8c4a-c3050ea0b03b.png)

**Comment by philipbordallo** [comment]
@kufii it helps to put the text version of an syntax highlighting example
```js
yield { x: 10 };
yield 5;
yield 'test';
yield `test${10}`;
```

The last `yield` is scoped as `source.js variable.function.tagged-template.js`

**Comment by Thom1729** [comment]
Sorry I missed this earlier. The problem is that the syntax was looking for tagged template strings before looking for yield expressions. The PR should fix it.
