### ISSUE TITLE
[C++] "Size" shouldn't be identified as a type

### ISSUE THREAD

**Issue by jasjuang** [sublimehq/Packages#1816]
For the below code, the keyword `int` will be highlighted differently because it is identified as a type by Sublime.

```
int main(){
  int a=1;
  return 0;
}
```
and if we change it to something random like `abc` it wouldn't

```
int main(){
  abc a=1;
  return 0;
}
```

however if we change it to `Size` for some reason sublime identifies it as a type. Can we fix this?

```
int main(){
  Size a=1;
  return 0;
}
```

Note that this only happens when "S" is capitalized, because if I change it so `size` it didn't highlight it as a type 

```
int main(){
  size a=1;
  return 0;
}
```

My sublime version is the latest paid dev version. The problem appears on both Ubuntu 18.04 and Windows 10.

**Comment by wbond** [comment]
`Size` is a Carbon data type, highlighted with other Carbon types at:

https://github.com/sublimehq/Packages/blob/1810c735e363e478a0ed6762d6835ba09ecc9f7c/C%2B%2B/C.sublime-syntax#L165-L166

**Comment by jasjuang** [comment]
I googled "carbon data type" and it looks like a type defined by Apache SDK. I don't think types defined by Apache SDK should get special treatment because only a small small percentage of C++ programmers use Apache related code.
