### ISSUE TITLE
emmet expansions slow in large files

### ISSUE THREAD

**Issue by vistuleB** [sublimehq/Packages#1829]
I've noticed that typing `p` on its own line in an HTML file and hitting TAB takes very long to make `<p></p>` appear when Emmet is active, when the file is large (in my case 1.5MB) and when the line is towards the end of the file.

When the line is towards the start of the file or when Emmet is disabled, no problem.

This may be related to https://github.com/Microsoft/vscode/issues/43470 where they mention something about parsers.

Platform: OSX 10.12.6
Build: 3176

PS: When I say "slow" I mean: 15 seconds + spinning beachball of death.

**Comment by Thom1729** [comment]
Emmet is a third-party package that is known to be extremely buggy and to break things. You should post this issue on the Emmet package's tracker.

**Comment by wbond** [comment]
Closing, since this appears to be due to a third-party package.

**Comment by vistuleB** [comment]
(OK, filed an issue at the Emmet repo.)
