### ISSUE TITLE
[Lua] Indentation issues

### ISSUE THREAD

**Issue by Resike** [sublimehq/Packages#1832]
### Summary
Some indentation settings seems to act weird when their related code block start with the start of the line. Every second indentation seems to get ignored and doesn't get decreased. Some other languages are also might be affected besides Lua.

### Expected behavior
Indentation should work properly at any scenario.

### Actual behavior, Steps to reproduce
Default Lua package, default Lua indentation settings:
![2019-01-09_20-09-20](https://user-images.githubusercontent.com/3955703/50923013-30c81600-144c-11e9-9661-fbf666a2f521.gif)

Works fine with a prefixed whitespaces:
![2019-01-09_20-15-48](https://user-images.githubusercontent.com/3955703/50923168-94eada00-144c-11e9-870e-4e559b7780ec.gif)

### Environment

- Operating system and version:
    - Windows 7 x64 6.1 build 7601
- Sublime Text:
    - Build 3184 64 bit

**Comment by keith-hall** [comment]
presumably this is just a manifestation of https://github.com/SublimeTextIssues/Core/issues/1262 as opposed to a problem with the Lua indentation rules, as there seems to be nothing that would cause this behavior in the [regex pattern](https://github.com/sublimehq/Packages/blob/61bfd68ea07a3aede68cd6a65c80be702b3d6db8/Lua/Indent.tmPreferences#L11).
