### ISSUE TITLE
[Go] "Goto Reference" integration

### ISSUE THREAD

**Issue by frou** [sublimehq/Packages#1838]
Everyone knows about Sublime's _"Goto Definition"_ mouse-hover/menu-item/command, but there is also its newer brother which does the reverse, _"Goto Reference"_.

Just as what is considered a symbol definition by default is declared in `Default/Indexed Symbol List.tmPreferences`, what is considered a symbol reference by default is declared in `Default/Indexed Reference List.tmPreferences`:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>scope</key>
    <string>
        meta.function-call variable.function,
        meta.function-call support.function,
        meta.method-call variable.function
    </string>
    <key>settings</key>
    <dict>
        <key>showInIndexedReferenceList</key>
        <string>1</string>
    </dict>
</dict>
</plist>
```

I'm wondering, @mitranim , was it a deliberate decision not to scope function/method calls to be recognised as references? The _Goto Reference_ functionality is nice, but there will indeed be some false positives presented, due to name clashes.

I tried it by creating a file with this content:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>scope</key>
    <string>source.go variable.function</string>

    <key>settings</key>
    <dict>
        <key>showInIndexedReferenceList</key>
        <string>1</string>
    </dict>
</dict>
</plist>
```

**Comment by mitranim** [comment]
This is actually an oversight. Thanks for the heads-up. I've never used references, and forgot the feature ever existed. In languages like Go, simple text-based indexing that doesn't even take package names into account leads to vast amounts of false positives, conflating unrelated functions from different packages.

Anyway, there's no obstacle to adding this back. Should be able to make a PR in a few days.

**Comment by frou** [comment]
@wbond What do you think is preferable here? No Goto-Reference functionality, or Goto-Reference functionality with some false positives?

**Comment by frou** [comment]
We can get real language understanding via **gopls** now, so an approach with false positives is even less appealing.
