### ISSUE TITLE
[Java] Interfaces with multiple inheritance break highlighting

### ISSUE THREAD

**Issue by AaronAsAChimp** [sublimehq/Packages#1843]
Interfaces In Java can inherit from multiple parent interfaces even though it isn't allowed for classes.

In the following example the parent interface `BB` is scoped as `constant.other.java` when it should be `entity.other.inherited-class.java`

A minimal example:
```java
interface T extends A, BB {}
```

As rendered in Sublime Text:

![image](https://user-images.githubusercontent.com/60481/51279131-7a63b400-19aa-11e9-911e-c9b21d221778.png)

**Comment by djspiewak** [comment]
Confirmed. Should be an easy fix.
