### ISSUE TITLE
[Markdown] Javascript language highlighting not working

### ISSUE THREAD

**Issue by pydolan** [sublimehq/Packages#1845]
It appears that Javascript highlighting is not working in my markdown files (syntax type: "Markdown -> Markdown"):

<img width="454" alt="screen shot 2019-01-18 at 6 32 11 am" src="https://user-images.githubusercontent.com/467780/51401064-25898000-1b07-11e9-8159-3fcc7ea76709.png">

This differs from what one sees in Github (the below using 'javascript' and 'js'):

```javascript
var s = "JavaScript syntax highlighting";
alert(s);
```
 
```js
var s = "JavaScript syntax highlighting";
alert(s);
```

I'm using Sublime v3.1.1 build 3176.  The only packages I have installed are "Default File Type" and "Package Control".  Color Scheme: "Breakers", Theme: "Default.sublime-theme".

I tried adding some JS-highlighting 3rd-party packages (babel and jsUpdater), as well as changing my Color Scheme and Theme, but the issue remains.  Am I missing something?

**Comment by Thom1729** [comment]
This may be related to #1750, which was closed by #1782. To find out, try downloading [the latest JavaScript.sublime-syntax](https://raw.githubusercontent.com/sublimehq/Packages/master/JavaScript/JavaScript.sublime-syntax) into `Packages/JavaScript/JavaScript.sublime-syntax`.

**Comment by pydolan** [comment]
I tried swapping out the syntax file in my JavaScript package, but the behavior remains the same. I did this on OS X by unzipping "/Applications/Sublime Text.app/Contents/MacOS/Packages/JavaScript.sublime-package", replacing the syntax file, rezipping it, and restarting Sublime.

I also tried [starting with a fresh copy](https://www.sublimetext.com/docs/3/revert.html) of Sublime (v3.1.1 build 3176), deleting the data folder and re-downloading, but I'm seeing the same behavior:

<img width="636" alt="screen shot 2019-01-18 at 1 40 43 pm" src="https://user-images.githubusercontent.com/467780/51411859-aefc7a80-1b26-11e9-9c88-9d8fd04c9d8d.png">

Note: I updated the issue title to have "[Markdown]" in title; hopefully that's helpful.

**Comment by michaelblyons** [comment]
@pydolan I can confirm your situation on the Stable channel, and that @Thom1729's suggestion does not quite work. You need to do what he said, but with the Markdown folder (though having the JS one too doesn't hurt).

Also, you don't actually have to do that unzipping/rezipping. If you copy the Markdown folder out of this repo, you should be able to copy the whole thing to `~/Library/Application Support/Sublime Text 3/Packages` and it'll override the default. Alternatively, check out [the ReadMe](https://github.com/sublimehq/Packages/blob/master/README.md#os-x) for macOS symlinking instructions.

PS. Thanks for adding [Markdown].

**Comment by pydolan** [comment]
Thanks @michaelblyons that does indeed fix my issue!
