### ISSUE TITLE
[JavaScript] Imports scoped as keyword.operator.module

### ISSUE THREAD

**Issue by FichteFoll** [sublimehq/Packages#185]
I do not believe import statements should be marked as `keyword.operator.module`. Same applies to the other `#keywords-top-level` keywords.

Here's an overview on how some languages do it:

Language | scope
:-------- | :------
JavaScript | `keyword.operator.module`
Python | `keyword.control.import`.
C | `keyword.control.import.include`
Java | `keyword.other.import`
Php | `keyword.control.import.include`
Go | `keyword.control.import`

These should probably be unified (Java and JavaScript in particular).

**Comment by wbond** [comment]
This should be resolved by 412635a10fe39ae507656d6aee7e502180de2505

**Comment by FichteFoll** [comment]
How about Java though? New issue?
