### ISSUE TITLE
[Java] Goto Definition does not work if the class implements an interface whose first letter is in lowercase

### ISSUE THREAD

**Issue by j2nis** [sublimehq/Packages#1858]
Hi team,

I have noticed an issue on my project. I have a java class MyClassA which both extends class MyClassB and implements interface iMyInterface. In that case, goto symbol function (Ctrl + R) does not show any of my functions (does not matter is the function is public, private or protected) but only the ones inside "new object" of my function :

```
public class MyClassA
    extends MyClassB
    implements iMyInterface
{
    public void _MyMethod() {
        new Thread(new Runnable() {
            public void run() {
            }
        }).start();
    }
}
```

In this example, run method is found by Ctrl + R but not _MyMethod.

If i rename "iMyInterface" (first letter in lowercase) to "IMyInterface" (first letter in uppercase), it's now working. Magic!
Is this problem already known?

Thanks!

PS : i use the stable build 3176

**Comment by djspiewak** [comment]
Confirmed:

![](https://i.imgur.com/jWL6R7y.png)

I'm pretty sure this is related to some of the `implements` scoping issues.

**Comment by srbs** [comment]
Similarly, this will not find the `run` method as well:
```
public class Test {
    public void method() {
        new iMyInterface() {
            public void run() {}
        };
    }
}
```

<img width="809" alt="screen shot 2019-01-29 at 16 59 28" src="https://user-images.githubusercontent.com/297298/51946481-43988f80-23e7-11e9-8d8f-3fcb3fd2778c.png">
