### ISSUE TITLE
[Bash] `if` comparisons with negated command

### ISSUE THREAD

**Issue by michaelblyons** [sublimehq/Packages#1868]
This one is pretty minor, but I'm going to log it for the record. The second `!` is marked as the command instead of `git`.

``` sh
if [[ ! -z "$extra_status_args" ]] && ! git diff --cached --quiet; then
    echo "Staged files exist"
fi
```

All of these look right:

``` sh
if [[ ! -z "$extra_status_args" ]] && git diff --cached --quiet; then
    echo "Staged files (don't) exist"
fi

if ! git diff --cached --quiet; then
    echo "Staged files exist"
fi

if ! git diff --cached --quiet && [[ ! -z "$extra_status_args" ]]; then
    echo "Staged files exist"
fi
```

**Comment by deathaxe** [comment]
The fix is quite easy but might conflict with #1863 if posted via separate PR.

Can add it to this PR or wait until it was merged. Thoughts?

**Comment by michaelblyons** [comment]
It's fine with me if you add it to #1863. I'm not in any hurry, and I like the work on that PR.

**Comment by stdedos** [comment]
_From https://github.com/sublimehq/Packages/issues/1871 duplicate:_

```bash
# Replace `cd` to go to file's path if DIR is a file
cd() {
	# Breaking command line:
	# cd PATH [-L|[-P [-e]] [-@]]
	local file="${!#}"

	# echo $file

	if (( "$#" )) && ! [[ -d "$file" ]]; then
		# echo "'$#'"
		# for i in "${@:1:($#-1)}" ; do echo "'$i'" ; done
		# echo "'${file%/*}'"
		builtin cd "${@:1:($#-1)}" "${file%/*}"
	else
		builtin cd "$@"
	fi
}
```
_I know the example is stupid, bear with me ..._

![image](https://user-images.githubusercontent.com/133706/52489154-2ecbb100-2bca-11e9-88eb-24c34eee0a68.png)

_No need to say that `[[ !` are indeed highlighted correctly, I guess ..._

**Comment by michaelblyons** [comment]
It turns out not just to be in `if`s. 

``` sh
# works
! git diff --cached --quiet

# mis-highlighted
do-stuff && ! git diff --cached --quiet
do-stuff || ! git diff --cached --quiet
```
