### ISSUE TITLE
R's "ifelse" not colored as function

### ISSUE THREAD

**Issue by david-cortes** [sublimehq/Packages#1870]
In R language, there is a function called `ifelse` which is being colored the same as an `if` statement in Sublime3, rather than as a function.

**Comment by deathaxe** [comment]
Which version of ST do you use?

The issue does not exist in the master branch does not in ST 3184 as well.

![grafik](https://user-images.githubusercontent.com/16542113/52488961-58340f00-2bc1-11e9-9691-6647dc5a1f5e.png)

**Comment by david-cortes** [comment]
I was using build 3176. Guess it must have been fixed recently then.

**Comment by randy3k** [comment]
@david-cortes You are correct (if you consider half a year is recent).
https://github.com/sublimehq/Packages/pull/1518/files
