### ISSUE TITLE
Bash malformed bash-if condition

### ISSUE THREAD

**Issue by stdedos** [sublimehq/Packages#1871]
```bash
# Replace `cd` to go to file's path if DIR is a file
cd() {
	# Breaking command line:
	# cd PATH [-L|[-P [-e]] [-@]]
	local file="${!#}"

	# echo $file

	if (( "$#" )) && ! [[ -d "$file" ]]; then
		# echo "'$#'"
		# for i in "${@:1:($#-1)}" ; do echo "'$i'" ; done
		# echo "'${file%/*}'"
		builtin cd "${@:1:($#-1)}" "${file%/*}"
	else
		builtin cd "$@"
	fi
}
```
_I know the example is stupid, bear with me ..._

![image](https://user-images.githubusercontent.com/133706/52489154-2ecbb100-2bca-11e9-88eb-24c34eee0a68.png)

_No need to say that `[[ !` are indeed highlighted correctly, I guess ..._

**Comment by FichteFoll** [comment]
This was already reported at https://github.com/sublimehq/Packages/issues/1868.

**Comment by stdedos** [comment]
That's weird. I am not seeing anything out of order with this one:

![image](https://user-images.githubusercontent.com/133706/52490371-42c4e200-2bcd-11e9-99bd-385e58183461.png)

I did see the ticket before reporting it, but maybe my highlighting scheme doesn't catch this?

**Comment by FichteFoll** [comment]
Ah sorry, I didn't catch the `[[` being malformatted here. That's indeed a different issue, although I highly suspect it to be caused by the same underlying problem.

If you look closer, you can see that the second `!` in the first example is yellow instead of red.

**Comment by michaelblyons** [comment]
If you delete the `!` in @stdedos's code, it looks right to me. I think it's the same issue.

**Comment by stdedos** [comment]
> Ah sorry, I didn't catch the `[[` being malformatted here. That's indeed a different issue, although I highly suspect it to be caused by the same underlying problem.
> 
> If you look closer, you can see that the second `!` in the first example is white instead of red, as it is in your OP.

Oh, I didn't guess that negation is "always" red (and it is white because it is assumed to be a command name).

Posting forward then ...
