### ISSUE TITLE
[RFC] Numbers

### ISSUE THREAD

**Issue by deathaxe** [sublimehq/Packages#1877]
### ST3 Scope Naming Guideline

Numeric literals, including integers, floats, etc. should use one of:

    constant.numeric
    constant.numeric.integer
    constant.numeric.float
    constant.numeric.hex
    constant.numeric.octal

### Used Scopes by Syntaxes

The following list contains all kinds of `constant.numeric` which are used in the Default Syntaxes and are related to a specific data-type. Stuff like `constant.numeric.version` etc. is filtered out.

    constant
      numeric
        binary
        complex
        decimal
        float
        float.decimal
        float.hexadecimal
        floating-point
        hex
        hexadecimal
        imaginary
        imaginary.decimal
        imaginary.hexadecimal
        integer
        integer.base-<n>   ; n = 2..36
        integer.binary
        integer.decimal
        integer.decimal.base
        integer.generic-base
        integer.hexadecimal
        integer.int32
        integer.int64
        integer.long.binary
        integer.long.decimal
        integer.long.hexadecimal
        integer.long.octal
        integer.nativeint
        integer.octal
        octal
        preprocessor

#### Type and Base

Most (older) syntaxes seem to use the 3rd-level scope to distinguish the type (`integer`, `float`, `complex`) while the 4th-level scope provides information about the base (`base-<n>`, `generic-base`  `binary`, `decimal`, `hexadecimal`, `octal`).

The official ST documentaion instead mixes `type` and `base` in the 3rd-level scope and is applied to few recently reworked syntaxes only.

This leads to conflicts like `constant.numeric.decimal` vs. `constant.numeric.integer`. Both scopes describe an integer, but `decimal` means base 10 while integer can be anything. Same conflict exists for `hex` and `binary`.

#### Naming

While most (older) syntaxes use `hexadecimal` the official guideline says `hex`. But `binary` is not shortent to `bin`. 

### Proposal

1. All scopes should use consistant short or long names.
   
   `bin` or `binary`
   `dec` or `decimal`
   `hex` or `hexadecimal`
   `int` or `integer`
   `oct` or `octal`
   ...

2. Distinguish data type and base system.
   
   The majority of syntax definitions uses `constant.numeric.<type>.<base>` for a good reason. R even distinguishes the base for `float`. We should keep this naming scheme avoid mixing up _data types_ and _base systems_.

```
   constant
     numeric
       integer
         binary
         base-3
         base-4
         base-...
         octal
         decimal
         hexadecimal
       float
         binary
         base-3
         base-4
         base-...
         octal
         decimal
         hexadecimal
       complex
         real
         imaginary
```

### Alternative

   Based on the existing ST scope naming guideline, the following scheme can be created, which implicitely defines `bin`, `oct`, `dec` and `hex` as integers.

   The `real` and `imaginary` part of `complex` numbers is distinguished but may implicitely be assumed `float`.

   All integers with other base systems are grouped in `other`.

```
    constant
      numeric
        bin
        oct
        dec
        hex
        float
        complex
          real
          imag
        other
```

**Comment by wbond** [comment]
I think we are going to move forward with:

```
   constant
     numeric
       integer
         binary
         octal
         decimal
         hexadecimal
         other
       float
         binary
         octal
         decimal
         hexadecimal
         other
       complex
         real
         imaginary
```

I'm not convinced the fourth-level scopes are worth standardizing, but I guess most of the syntaxes are using them in some form.

**Comment by wbond** [comment]
This will be part of the docs in the next release
