### ISSUE TITLE
Haskell - highlighting of instance declaration following class declaration

### ISSUE THREAD

**Issue by tmcopeland** [sublimehq/Packages#1880]
### Description

I found some strange behavior in Sublime's Haskell highlighting. The [relevant code](http://learnyouahaskell.com/making-our-own-types-and-typeclasses) is from the _Learn You A Haskell_ book, specifically the paragraph called "A yes-no typeclass".
```haskell
class YesNo a where
    yesno :: a -> Bool

instance YesNo Int where
    yesno 0 = False
    yesno _ = True

instance YesNo [a] where
    yesno [] = False
    yesno _ = True

-- more instances ...
```
In the second code block, immediately following the typeclass declaration, the words `instance` and `where` do not highlight. This is irrespective of the order of the instance declarations. If I swap the instance declarations, the same thing happens, and additionally the expression `[]` does not highlight.

Oddly, this highlights as expected:
```haskell
class YesNo a where
    {yesno :: a -> Bool}
-- ...
```
as does
```haskell
class YesNo a where { yesno :: a -> Bool }
-- ...
```
but not if I break the line after the left brace.
```haskell
class YesNo a where {
    yesno :: a -> Bool }
-- ...
```
It highlights as expected in gedit. See the images below.

![haskell highlight 1](https://user-images.githubusercontent.com/505028/52829044-4b1f9000-3099-11e9-9946-27316e3ca4b3.png)
![haskell highlight 4](https://user-images.githubusercontent.com/505028/52829251-05af9280-309a-11e9-991b-db3a7c25e990.png)
![haskell highlight 2](https://user-images.githubusercontent.com/505028/52829045-4b1f9000-3099-11e9-8138-5b36ea05d9f0.png)
![haskell highlight 3](https://user-images.githubusercontent.com/505028/52829046-4b1f9000-3099-11e9-9d3d-1eae48e47d19.png)

### Environment

* Build 3176, Ubuntu 18.10, GNOME
* No packages installed that would affect Haskell highlighting

**Comment by jacksoncooper** [comment]
This is similar to #1320. I have a patch written and will open a pull request when I'm done with the test cases. I don't think the brackets affect the highlighting because they're ignored by the syntax file. The issue occurs because the context responsible for highlighting type signatures is not always popped when it should be.

**Comment by wbond** [comment]
This issue has been solved by a previous commit, hence it is being closed.
