### ISSUE TITLE
[PHP] Hightlight stopped working after calling a class method stored in an array

### ISSUE THREAD

**Issue by XecKiE** [sublimehq/Packages#1881]
I noticed in my code that all of my php code stopped being highlighted after calling a method of an object witch was stored in an array.

Here is a simple example to reproduce :

```php
<?php

class Example {
	public function method() {}
}

$array = [new Example()];

$array[0]::method();

echo "test";
```

Here is the result (highlighting stopped at line 11) : 
![screenshot_20190215_094350](https://user-images.githubusercontent.com/2796399/52844971-33cabc00-3106-11e9-8e86-57f525f22d37.png)

When pasted into Sublime Text, the code after `$array[0]::method();` is not highlighted anymore. I reproduced this issue on two different computers.

_Sublime Text Version : 3.1.1 Build 3176_

**Comment by jfcherng** [comment]
I believe this had been fixed in the current github repository.

![image](https://user-images.githubusercontent.com/6594915/52845287-ac9b3980-3141-11e9-96f5-39612f518187.png)

**Comment by XecKiE** [comment]
Indeed you're correct,

Thanks for the answer !
