### ISSUE TITLE
js erroneous highlighting

### ISSUE THREAD

**Issue by stdedos** [sublimehq/Packages#1887]
_Yeah, I know! Intuitive title, right? :stuck_out_tongue_closed_eyes: I am not familiar with the code or language. Might have something to do with regex match?_

```js
export const CheckMarkAvatar = withStyles(checkMarkStyles)(({ classes }) => (
    <Avatar classes={{
                root: classes.root
            }}>
        <Typography className={classes.text}>
            {"\u2714"}
        </Typography>
    </Avatar>
));
```
![image](https://user-images.githubusercontent.com/133706/53101047-acc87a00-3531-11e9-8ad7-36b8ce877363.png)

It seems that 

```js
        </Typography>/
    </Avatar>/
```
fixes the highlight

**Comment by wbond** [comment]
This is JSX, which is not supported by the JavaScript syntax. https://packagecontrol.io/packages/JSCustom is your best bet for JSX. The author (@Thom1729) is the primary maintainer of the default JavaScript syntax.
