### ISSUE TITLE
[D] Freeze due to variable name beginning with "function"

### ISSUE THREAD

**Issue by andy-hanson** [sublimehq/Packages#1909]
Create a D file:
```d
void f() {
	int x;
	int functionA = 0;
}
```

Place the cursor after `x` and before `;` and type ` =`. The editor will freeze. Appears to be happening because a variable name begins with `function`.

**Comment by keith-hall** [comment]
confirmed on build 3197. Most likely due to a non consuming `set` loop in the syntax definition, though I haven't checked - I just have seen it happen before for this reason.
