### ISSUE TITLE
[JavaScript] Different scopes for "this"

### ISSUE THREAD

**Issue by websash** [sublimehq/Packages#191]
In the following screenshots `this` is treated differently
![screen shot 2016-02-20 at 1 24 19 am](https://cloud.githubusercontent.com/assets/679341/13192651/063aeddc-d777-11e5-8bf0-98f3002a8708.png)
![screen shot 2016-02-20 at 1 24 39 am](https://cloud.githubusercontent.com/assets/679341/13192654/0bc590cc-d777-11e5-9bbe-753010d89826.png)
Shouldn't there be just one scope/color for `this`?

**Comment by wbond** [comment]
This should be resolved by 412635a10fe39ae507656d6aee7e502180de2505
