### ISSUE TITLE
Lua - unclosed strings are still disabling highlighting for too many lines

### ISSUE THREAD

**Issue by RheingoldRiver** [sublimehq/Packages#1916]
Screenshot - https://puu.sh/D2wqs.png

Code -
```lua
function h.parsePlayerData(row, i, j)
	row.Link = lang:ucfirst(row.Link or row.Name or '')
	row.Side = i
	row.Role_Number = j
	row.Role = m_role.rolename('scoreboard .. j)
	return row
end
```

The red error highlight is correctly one line now, but the unclosed string disables the return/end highlighting later in the function.

**Comment by FichteFoll** [comment]
So, the problem is that the unclosed string captures the closing parents of the function call and keywords aren't valid in expressions. I'll see if I can do something similar to what we do in Python in these situations.
