### ISSUE TITLE
[SQL] "is" not colored as keyword unless after "and"

### ISSUE THREAD

**Issue by david-cortes** [sublimehq/Packages#1926]
In SQL syntax highlight, the "is" keyword is not being colored as an sql keyword unless it comes after and and. Attached is a screenshot.
![sql_is_colors](https://user-images.githubusercontent.com/11860098/54917629-e14e9d80-4f04-11e9-9ef9-e24708607bc8.png)

**Comment by michaelblyons** [comment]
While you're in there, can you make `is` and `not` into `keyword.operator.logical` and `null` into a `constant.language`? 😉
