### ISSUE TITLE
[JavaScript] Issues with object literals and import statement

### ISSUE THREAD

**Issue by websash** [sublimehq/Packages#193]
In ES6 object literal we can omit a property value if it matches a property name. 
Therefore `{prop1, prop2}` is a valid expression. In the latest JavaScript.sublime-syntax
it's assumed the colon key-value separator is required which breaks highlighting

You can add this code to the syntax_test file:
```javascript
function foobar(obj) {
  const {prop1, prop2} = obj
  return {prop1, prop2, prop3: prop1*prop2}
}
```
Another issue is with this import statement:
```javascript
import './foobar'
```
this statement _with single quotes_ breaks everything. 
Even Sublime crashes when I type it in syntax_test_js.js

**Comment by wbond** [comment]
Import statement support was further revamped in c7c93140f49b0bf2332c91a6e96c40b2e3b50575.

ES6 shorthand property name support was added in a0ab9cfc2591a32025b4ae254ddebb3ac6a17208.

Thanks for reviewing the syntax and reporting issues! Please do keep reporting issues so we can continue to improve the syntax.
