### ISSUE TITLE
[Markdown] does not recognize links without dots

### ISSUE THREAD

**Issue by evandrocoan** [sublimehq/Packages#1930]
![image](https://user-images.githubusercontent.com/5332158/55271681-8368df80-528f-11e9-96d5-05695ec2a317.png)

```
http://server/user
https://github.com/
```

Github Markdown does:
http://server/user
https://github.com/

**Comment by keith-hall** [comment]
according to the [GFM docs](https://github.github.com/gfm/#extended-url-autolink):
> An extended url autolink will be recognised when one of the schemes `http://`, `https://`, or `ftp://`, followed by a [valid domain](https://github.github.com/gfm/#valid-domain), an a valid domain must contain at least one period.

So it may be a bug in the spec that GitHub linkifies `http://server/user`, or it may be a bug in the spec...

**Comment by evandrocoan** [comment]
Links without dot are accepted as valid for intranets while working inside an organization. Maybe for Internet they must have a dot because of how it was designed, but while working inside companies you can have links without a dot.

**Comment by keith-hall** [comment]
I realize the links are valid, I'm just opening a discussion about whether to follow the spec to the letter or deviate from it for "observed compatibility"/"common use", the implication being that other apps that work with/parse GFM may behave differently.
I personally also use intranet links in my Markdown documents, so I would be tempted to "fix" this issue, I just wanted more feedback first. :)
I wonder if anyone has filed an issue against the GFM spec regarding this.

**Comment by evandrocoan** [comment]
I do not think anyone has filled this issue. Is this their issue tracker? https://github.com/commonmark/CommonMark

The answer should be simple, does the spec for GFM is representing links for internet only or internet and intranets? If it is for both, then, GFM is bugged. If it is for internet only, then, is not a bug, therefore, an enhancement for GFM would be for it to also accept links for intranets too.

**Comment by keith-hall** [comment]
https://github.com/github/cmark-gfm/issues/93
https://github.com/github/cmark-gfm/issues/98

**Comment by michaelblyons** [comment]
Note that you can always force link-highlighting with `<>`:

``` md
<http://server/user>
<https://github.com/>
```

**Comment by deathaxe** [comment]
Bitbucket, Github, Gitlab, Python Markdown, MultiMarkdown all translate those links without dots, regardless what specs say.

MultiMarkdown requires another `/` to do so, but that's a detail, IMHO.

So from practical point of view, highlighting autolinks without dots would be fine.
