### ISSUE TITLE
[Lua] "!=" not equal operator - syntax highlighting

### ISSUE THREAD

**Issue by squanchy1337** [sublimehq/Packages#1939]
![64c9e82b0d91d892730acfc872bc204c](https://user-images.githubusercontent.com/49417642/55759826-aac36780-5a5a-11e9-8aec-18805f178819.gif)

I'm using the latest version of Sublime Text, with the default Lua syntax highlighter:
![1f089783643a5fc7c5ab77e133363cc4](https://user-images.githubusercontent.com/49417642/55759877-d5152500-5a5a-11e9-9679-cf48289b7047.png)

It was working just fine before the last update, so i don't know
Thanks!

**Comment by rwols** [comment]
For context, I believe I recommended you to post this issue here from a Reddit thread. In that Reddit thread you mention you use GLua. GLua is built on top of Lua. Among the allowable keywords are `!=`. But `!=` is truly not a keyword in Lua:

```
$ lua5.3
Lua 5.3.3  Copyright (C) 1994-2016 Lua.org, PUC-Rio
> x = 1
> y = 2
> x != y
stdin:1: syntax error near '!'
```

There doesn't seem to be a GLua package on packagecontrol.io, so somebody should write it.

**Comment by Thom1729** [comment]
It looks like GLua adds a number of nonstandard operators, plus nonstandard comment syntaxes and a new keyword. We shouldn't add all of that to the core syntax, but merely adding `!=` would not make the syntax work acceptably well for GLua.

It wouldn't be difficult to implement a third-party GLua syntax. If it were me, I'd use [YAML Macros](https://github.com/Thom1729/YAML-Macros) and write a small patch that can be applied to the core syntax; this would avoid copy-pasting the existing syntax.

**Comment by michaelblyons** [comment]
> If it were me, I'd use YAML Macros and write a small patch that can be applied to the core syntax; this would avoid copy-pasting the existing syntax.

Or in build 4xxx, the `extends` behaviour.

**Comment by FichteFoll** [comment]
By the way, the syntax should not error out as much as it does in the gif at the top, so the issue should probably remaind open until that is fixed, but I firmly believe it is not a good idea to match `!=`.
