### ISSUE TITLE
Error loading CMake syntax after upgrading to build 3207

### ISSUE THREAD

**Issue by vilya** [sublimehq/Packages#1940]
After updating to build 3207 I've started getting error dialogs when launching SublimeText that say (for example) "Error loading syntax file 'Packages/CMake/CMake.sublime-syntax': Unable to read Packages/CMake/CMake.sublime-syntax":

![image](https://user-images.githubusercontent.com/109662/55787256-c6a42900-5aad-11e9-9f0c-4f689e9f0788.png)

This is what I see in SublimeText's console:
```
DPI mode: per-monitor v2
startup, version: 3207 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/VilyaHarvey/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/VilyaHarvey/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/VilyaHarvey/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.0581014
startup time: 0.0891014
first paint time: 0.0901014
git: tracking working dir C:\Users\VilyaHarvey\Work\adfsculpt
error: Error loading syntax file "Packages/CMake/CMake.sublime-syntax": Unable to read Packages/CMake/CMake.sublime-syntax
```

There is no CMake.sublime-syntax file in any of those paths. Could the upgrade process have removed it, or moved it somewhere else? 

CMake syntax highlighting was working for me with SublimeText 3.1. I don't think I opened a project containing CMake files with the 3.2.0 release, so I'm not sure whether the problem started with the 3.1 to 3.2 upgrade or the 3.2 to 3.2.1 upgrade.

Here are my current version details, just for confirmation:
![image](https://user-images.githubusercontent.com/109662/55788631-90b47400-5ab0-11e9-9faa-05f26a3827fe.png)

**Comment by vilya** [comment]
It didn't wipe all packages, just some of them. CMake was installed through Package Control. I still have some of the other packages I'd installed through it (e.g. Alignment, OpenGL Shading Language), as well as Package Control itself. I also have a custom syntax definition in `AppData\Roaming\Sublime Text 3\Packages` which is still present. 

I installed Sublime Text for all users: it's in C:\Program Files\Sublime Text 3.

For what it's worth, reinstalling the CMake package fixes the problem. It's just surprising that an upgrade would cause the problem in the first place.

**Comment by FichteFoll** [comment]
Sounds more like a coincidence. Either way, this isn't related to the default packages since CMake is a third-party package, so you shoul close this issue.

**Comment by wbond** [comment]
Closing, since this is not related to default packages.
