### ISSUE TITLE
Syntax highlight is broken iterating on deconstructed tuples (C# 7.0)

### ISSUE THREAD

**Issue by mihaipopescu** [sublimehq/Packages#1946]
**Version info**

 - OS: macOS 10.14.4
 - Build: 1107

**Description**

Sublime merge syntax highlight breaks when it encounters iterations on deconstructed tuples.

**Steps to reproduce**

1. Create a new git repository
2. Create a new C# file, say `bug.cs`
3. Paste the following code https://pastebin.com/VVeQykmg
4. Add and commit the file to git repository
5. Edit the file again and apply this patch https://pastebin.com/FrB85G6V (so that the modified line is within the limit patch context range)
5. Observe that the syntax highlight is broken

N.B. if I add a space between `var` and `(x, y)` the bug doesn't reproduce anymore.

**Expected behavior**

Code is recognized as valid syntax.

**Screenshots**
my own experience https://gyazo.com/ec58ba9656775b8b3459ff494f1dca3a
the proposed reproduction steps https://gyazo.com/d6c8526d21546475dd36b13eea41045d

**Comment by keith-hall** [comment]
in case you want to submit a PR to fix this, I believe you just need to change the `\s+` at https://github.com/sublimehq/Packages/blob/e0952a1ec1dd692e72bc82145c57542eaa88af8e/C%23/C%23.sublime-syntax#L1957 to a `\s*` (and add a corresponding syntax test assertion)

**Comment by djspiewak** [comment]
Also, thank you for the very thorough ticket, but if you want to short-circuit some of this formatting in the future… :-) Usually we just need the following:

1. Which mode is it (usually we put this in the title of the issue, such as **[C#]**)
2. A relatively minimal text snippet (in this case, I think just the `var(...` line would have sufficed), or at least a snippet where the relevant failure is clear
3. A screenshot or (even better!) a clear description of which scopes are wrong (screenshot is honestly fine)

You provided all of that, so no criticisms, just offering some tips in case you don't want to build such a *massively* thorough issue report in the future!

**Comment by mihaipopescu** [comment]
@keith-hall That looks about right. I should've done the minimal code-digging investigation before submitting this ticket.

I think the problem was that I didn't know where to submit the ticket. It's not obvious the relation of this repo to the one indicated by the [support page](https://www.sublimemerge.com/support), thus also the verbose ticket template. But @djspiewak it's good to know the process is less rigid here.
