### ISSUE TITLE
[JavaScript] syntax high lighting issue 1: when new statement as an argument

### ISSUE THREAD

**Issue by wulechuan** [sublimehq/Packages#196]
Build 3103
==========
if a `new` statement lays inside a function call as an argument of that call, the syntax high lighting is not correct. For example:
`var abc = new ABC('my-name-is-abc', new (function () { var foo = 1; this.age = foo; }));`
The second `new` is not rendered as a preserved word.

![image](https://cloud.githubusercontent.com/assets/4899190/13211040/0454ca42-d970-11e5-8452-d4d5dd4f26b2.png)

**Comment by wbond** [comment]
This was generally resolved in 409ccb469bca8bcc2a5c70c562d1db3428d3015f, and made more consistent in 76cb2529a1c1bc318a3a5c7a351bf29da48e2723.

These changes are not yet part of a dev build, and you may run into some errors if you try to use them with 3103-3105. Once 3106 is out, the issues will be resolved. However, note that 3106 will be a dev build, not a beta build.

**Comment by wulechuan** [comment]
Thanks!
