### ISSUE TITLE
[PHP] array_column incorrectly highlighted

### ISSUE THREAD

**Issue by idleberg** [sublimehq/Packages#1975]
It's my understanding that `array_column` should be highlighted like other array functions, e.g. `array_sum`.

![Screenshot 2019-05-16 at 12 13 17](https://user-images.githubusercontent.com/1504938/57846223-04465100-77d4-11e9-8eb5-826a1c7fc9e6.png)

I would have loved to contribute a PR myself, but the syntax format isn't too human-friendly (btw, is it more performant or is it just saving space?)

**Comment by FichteFoll** [comment]
Premature optimization, mostly. While I think it does bring a slight performance improvement to group matches like they are in the PHP syntax, they severely hurt readability and the usage of capturing groups (over non-capturing ones) will actually result in degraded performance overall.

I believe someone should do a pass to split these regexes and group them into multi-line matches at some point for better maintainability and less merge conflicts.

**Comment by jfcherng** [comment]
> I would have loved to contribute a PR myself, but the syntax format isn't too human-friendly (btw, is it more performant or is it just saving space?)

Could be related https://github.com/sublimehq/Packages/pull/1740

**Comment by idleberg** [comment]
Closed by #1976
