### ISSUE TITLE
Version '11.0' of AppleClang is not supported yet

### ISSUE THREAD

**Issue by yash-s20** [sublimehq/Packages#1984]
The app asked me to open an issue for it.
OS: OSX Mojave 10.14.5

**Comment by wbond** [comment]
This sounds like a bug with a package you have installed. Can you provide a list?

Alternatively, can you reproduce with a fresh data dir? http://sublimetext.com/docs/3/revert.html

**Comment by yash-s20** [comment]
I'm sorry I didn't mention.
I'm trying to use the EasyClangComplete package

**Comment by FichteFoll** [comment]
You can find a package's issues page on the packagecontrol.io listing: https://packagecontrol.io/packages/EasyClangComplete

In fact, there already is an issue for this: https://github.com/niosus/EasyClangComplete/issues/611

**Comment by niosus** [comment]
Just for the reference. This should be fixed now. Sorry for the confusion with this @wbond and @FichteFoll 
I have also added an issue for myself to disambiguate messages coming from my plugin here: https://github.com/niosus/EasyClangComplete/issues/612
