### ISSUE TITLE
[JavaScript] meta.block scope consistency

### ISSUE THREAD

**Issue by jcberquist** [sublimehq/Packages#199]
In the `block-scope` context, and in several others that match a block scope themselves (e.g. the `switch` match), the opening `{` gets the scope `meta.block.js` but the closing `}` does not. I noticed that in some cases, at least with parenthesis you solved this issue by adding the meta scope directly to the closing brace.

In a related issue, in the `function-declaration-parameters` context, the opening `(` is directly assigned the scope `meta.function.declaration.js`, but then it also gets that scope via the `meta_scope` of the pushed context, so the `meta.function.declaration.js` scope gets doubled for that `(`.

**Comment by wbond** [comment]
Again, thanks for the review!

I believe I've fixed the issues in e03b1a3f2f8e7ff04ca61c7e292a6bd9fd11fa86.

Unfortunately there isn't currently a way to test for doubled scopes, I don't believe. This is due to how the scope matching works.
