### ISSUE TITLE
comment not styled in parameters list

### ISSUE THREAD

**Issue by guillermooo** [sublimehq/Packages#20]
Containing scope seems to be this one:

https://github.com/sublimehq/Packages/blob/231c6fbd7e178d76a5867146abed2990a8df8acb/Python/Python.sublime-syntax#L158

**Comment by kleinfreund** [comment]
Can you show an example snippet of how this is styled currently?

**Comment by guillermooo** [comment]
![bug-comments](https://cloud.githubusercontent.com/assets/684948/8272827/772ed1fe-1853-11e5-9a7c-2df7811146ad.png)

**Comment by FichteFoll** [comment]
When I find the time, I'll probably redo the Python syntax def completely, but not sure when that would be. Currently I'm more focused on the docs, since (my) ImprovedPython (fork) works fairly well for the moment.

**Comment by wbond** [comment]
This should be solved by efeee76137130a504f3091d97ea72d19f40ada1e
