### ISSUE TITLE
[JavaScript] Line of code hanging Sublime

### ISSUE THREAD

**Issue by websash** [sublimehq/Packages#200]
I have just found a line that is hanging Sublime up:
```javascript
width/2 + lineStart * Math.sin(i * 30 * π/180)
```

**Comment by ccampbell** [comment]
After updating to the latest master for the JavaScript package my sublime is also hanging. I am not sure how to find out which line is causing it, but at least for me it is something related to a0ab9cfc2591a32025b4ae254ddebb3ac6a17208. 

When I manually check out c7c93140f49b0bf2332c91a6e96c40b2e3b50575 it works correctly.

**Comment by wbond** [comment]
This is a edge case that will be handled by the next dev build. I should be able to add a work-around for now.

**Comment by ccampbell** [comment]
@wbond do you think the crash I am experiencing is the same issue? I'd be happy to open a new ticket or try to help debug further

**Comment by websash** [comment]
I don't know whether it's the same issue but here's another one 
```javascript
console.log(typeof (USERS_URL + Math.round(Math.random()*9)+1))
```
trying to delete any of the opening braces is hanging Sublime.

**Comment by wbond** [comment]
Most likely it is related. What happen is that there is a `(?=\))` lookahead that pops, but you can't pop in the `main` context. Thus an infinite loop is created. The temporary fix is to explicitly consume the `)` in the main scope, like I do with the `}`.

**Comment by wbond** [comment]
ac442836ce1a948b2c7c4a91ae50cf151b8fee5a may fix the issue you are seeing.

**Comment by ccampbell** [comment]
Fixes it for me :smile:

**Comment by websash** [comment]
yeah, that fixes the issue with braces, but highlighting in my first line is wrong now :)

**Comment by wbond** [comment]
@websash Can you provide an example of what is highlighted incorrectly?

**Comment by websash** [comment]
Sure
![screen shot 2016-02-23 at 6 32 50 pm](https://cloud.githubusercontent.com/assets/679341/13258513/1c8b2272-da5c-11e5-8bf4-ed19ffbf7690.png)

**Comment by wbond** [comment]
Interesting, so we need to improve regex detection. I'll look and see how the old syntax detected this and see if we can replicate without lookbehinds.

**Comment by wbond** [comment]
The hang should no longer happen as of c6cd372e5944e5078a03d1d47f6de146dbd8133d. I've opened #204 to track the regex issue.
