### ISSUE TITLE
[Rust] Syntax highlighting bug with macro_rules

### ISSUE THREAD

**Issue by Aloxaf** [sublimehq/Packages#2014]
## Code
```rust
macro_rules! vec {
    ($($x:expr), *) => {
        {
            let mut v = Vec::new();
            $(v.push($x);)*
            v
        }
    };
}

fn main() {
    let v = vec![1, 2, 3];
    println!("{:#?}", v);
}
```

## Result
It matches the wrong `*` 
![图片](https://user-images.githubusercontent.com/17017672/61725589-a40af700-ada2-11e9-8b68-e5aae5790b78.png)

## What it should be
(I removed a whitespace character so that it could be syntax highlighted correctly)
![图片](https://user-images.githubusercontent.com/17017672/61725686-ce5cb480-ada2-11e9-822a-4c41ddda1500.png)

**Comment by FichteFoll** [comment]
Thanks for the report. I also fixed the bug with `$x:expr` not being highlighted properly in #2015.
