### ISSUE TITLE
Questions regarding sublime-syntax

### ISSUE THREAD

**Issue by aziz** [sublimehq/Packages#202]
### [Javascript.sublime-syntax#390](https://github.com/sublimehq/Packages/blob/master/JavaScript/JavaScript.sublime-syntax#L390)
```
- meta_scope: meta.instance.constructor.js meta.function-call.constructor.js
```
Is it legal to have space separated scopes in `meta_scope`. It has not been documented and I though all scopes including meta ones are single block of words separated by dots. If it's valid can we document it somewhere. 

###  [Javascript.sublime-syntax#420-480](https://github.com/sublimehq/Packages/blob/master/JavaScript/JavaScript.sublime-syntax#L420-L480)
Some of  the match regexes are wierd here. some end with an extra `|` and some don't. 

No extra `|` at the end
```
    - match: |-
        (?x)
        <=   | # relational      left-to-right   both
        >=   | # relational      left-to-right   both
        <    | # relational      left-to-right   both
        >      # relational      left-to-right   both
      scope: keyword.operator.relational.js
```

Extra `|` at the end
```
    - match: |-
        (?x)
        %=   | # assignment      right-to-left   both
        &=   | # assignment      right-to-left   both
        \*=  | # assignment      right-to-left   both
        \+=  | # assignment      right-to-left   both
        -=   | # assignment      right-to-left   both
        /=   | # assignment      right-to-left   both
        \^=  | # assignment      right-to-left   both
        \|=  | # assignment      right-to-left   both
        <<=  | # assignment      right-to-left   both
        >>=  | # assignment      right-to-left   both
        >>>= | # assignment      right-to-left   both
```
I'm writing a new sublime-syntax parser in Ruby to replace the old one on tmThemeEditor and my parser is choking on all those extra pipes. it might be something related to Yaml 1.2 that I don't understand since I don't have a 1.2 parse in Ruby and I'm parsing files with an old 1.1 yaml parser.

**Comment by FichteFoll** [comment]
`meta_scope` can, just like the normal `scope` key, define multiple scope names - or at least I believe so because I didn't test. `.tmLanguage` could always do this.

The extra `|` pipes at the end are most likely an error from copy-pasting and should not be there.

**Comment by aziz** [comment]
> meta_scope can, just like the normal scope key, define multiple scope names - or at least I believe so because I didn't test. .tmLanguage could always do this.

This only happened recently in javascript syntax. Can't find any other example anywhere else. that's why I became suspisious.

**Comment by wbond** [comment]
As @FichteFoll mentioned, `scope`, `meta_scope`, `meta_content_scope` can all accept multiple scope names separated by spaces.

In 06ffdbbd6ba5bea913f1ce23b6bfe251d9072c36 I cleaned up the stray trailing `|`s in the operator context regexes. I'm not enough of a YAML expert to know how they affect parsing in the different versions, but we don't need them, so they are gone.
