### ISSUE TITLE
[JavaScript] minor issue with object-property context

### ISSUE THREAD

**Issue by jcberquist** [sublimehq/Packages#203]
The `object-property` context has a pop regex of `(?=.)`. But because `.` does not match newlines, if I do the following:
```
a = b.c 
d = e.f
```
where the only thing between `c` and `d` is a newline character, `d` will be scoped as `meta.property.object.js`. 

Obviously this is an edge case, sorry!

**Comment by FichteFoll** [comment]
Empty match pattern should work in this case.

**Comment by wbond** [comment]
This should be resolved by 6ac14237a21e24f8c2f39bbf2361c12c98e2d85c. I opted for an explicit lookahead since I figured the intent would be more obvious than just `''`.

**Comment by FichteFoll** [comment]
Are you sure this works? Dots in sets match literal dots and not "everything".

Honestly, I believe empty patterns would be just as telling as a look-ahead that matches everything but is more verbose.
