### ISSUE TITLE
SCSS CSS4 selector coloring wrong

### ISSUE THREAD

**Issue by mbomb007** [sublimehq/Packages#2034]
Certain [CSS4 selectors](https://css4-selectors.com/selectors/) have no highlighting after them, or mess up highlighting for following selectors.

This code highlights `:has(...)` correctly, but the `ul.links li.dismiss` part is white (wrong).

    .contextual-links-region:has(> .contextual-links-wrapper) ul.links li.dismiss {  
      top: 0px;  
      right: -30px;  
    }

Pasting a copy of the above code after itself will cause the 2nd occurrence to highlight `ul.links li.dismiss` correctly, but the `:has(...)` part is different. Also notice that some italics is missing inside on `top` in the first block.

![Image of code highlighting](https://i.imgur.com/YZ0EOiP.png)

The highlighting of the 2nd block is what it looks like when pasted into a CSS file. So it looks like SCSS has some improvement (styles the :has better, but only sometimes).

Most of the selectors from CSS4 have no highlighting yet, and they will eventually need to be added. While not all of the are supported by browsers yet, many of the new features are. You can check your browser's support here: https://css4-selectors.com/browser-selector-test/

**Comment by jfcherng** [comment]
LGTM?

![image](https://user-images.githubusercontent.com/6594915/62381997-46836100-b57f-11e9-973b-de5cfbeb6d3e.png)

**Comment by mbomb007** [comment]
Ah, it has to be within another selector. Something like this:

```
div {
  .contextual-links-region:has(> .contextual-links-wrapper) ul.links li.dismiss {
    top: 0px;
    right: -30px;
  }

  .contextual-links-region:has(> .contextual-links-wrapper) ul.links li.dismiss {
    top: 0px;
    right: -30px;
  }
}
```

**Comment by jfcherng** [comment]
> Ah, it has to be within another selector. Something like this:

I don't think this is legal even in CSS 4.

**Comment by michaelblyons** [comment]
Perhaps you should consider Braver's [Sass package](https://packagecontrol.io/packages/Sass)?

**Comment by deathaxe** [comment]
I saw some concept of nesting in CSS recently, but needs the selector to be prepanded by `&`.

**Comment by mbomb007** [comment]
This question is not about CSS, it's about SCSS code with CSS selectors.

**Comment by deathaxe** [comment]
I've answered https://github.com/sublimehq/Packages/issues/2034#issuecomment-517755767

> Is nested CSS allowed in CSS 4? 

Otherwise this issue is invalid here as SCSS is not a syntax supported by this repo.

**Comment by mbomb007** [comment]
Maybe it's another repo then. But I don't really care anymore as I got rid of Sublime Text and use VS Code now.

**Comment by deathaxe** [comment]
You can close the issue then.

**Comment by wbond** [comment]
Closing, since we don't support SCSS in the default packages
