### ISSUE TITLE
[C++] Syntax highlighting error after string ">>"

### ISSUE THREAD

**Issue by andy-hanson** [sublimehq/Packages#2042]
```cpp
#include <iostream>

int main(void) {
	std::cout << ">>" << std::endl;
}
```

The closing `}` is highlighted pink. No such error if `">>"` is changed to `"aa"`.

**Comment by bumfo** [comment]
This is due to a bug in "regular" defined in C++.sublime-syntax

the `[...]*` should be defined as `[...]+`, as '<<', '<<<' is not possible in generic expression
