### ISSUE TITLE
[JavaScript] Multiline object literals are highlighted incorrectly

### ISSUE THREAD

**Issue by ccampbell** [sublimehq/Packages#205]
Example:

```javascript
someFunction({
    prop1, prop2, prop3
});
```

In sublime the first two properties are scoped `variable.other.readwrite.js`, but the last property is scoped `entity.name.function.js`:

![](https://devi.vimeocdn.com/craig/c39l)

**Comment by wbond** [comment]
This should be resolved by 1da10d70c857dbee6d6c3db8e7ab7dfc5f077a52
