### ISSUE TITLE
[Makefile][sublime-syntax] back slash is a line continuation

### ISSUE THREAD

**Issue by shaik7abdul7khallik** [sublimehq/Packages#2056]
`# something \`
`temp := hello`

Back slash is a line continuation in Make files.
The second line `temp := hello` also becomes a comment that should look greyed out due to `\` in first line. But its not greyed out.

**Comment by jfcherng** [comment]
![image](https://user-images.githubusercontent.com/6594915/63343704-35a95c80-c381-11e9-9614-641492dba186.png)

cannot reproduce

**Comment by deathaxe** [comment]
Duplicate of issue #1938 fixed by PR #1944 which is not part of ST3207/3208.
