### ISSUE TITLE
[D] Struct initialisation syntax is unsupported

### ISSUE THREAD

**Issue by Just-Harry** [sublimehq/Packages#2062]
Structs in D can be statically and dynamically initialised with the syntax described here:
- https://dlang.org/spec/struct.html#static_struct_init
- https://dlang.org/spec/struct.html#dynamic_struct_init

Consider this example code where the second member of the struct initialiser is highlighted as an error, and everything after the comma of "Hello, World!" is highlighted as a string:

```d
struct MyStruct
{
	int a;
	int b;
	string c;
}

MyStruct theStruct =
{
	a: 1,
	b: 2,
	c: "Hello, World!"
};

void main ()
{
	import std.stdio : writefln;

	writefln("%s", theStruct);
}
```

Screenshot of highlighting: https://i.ibb.co/fQHxTKf/sublime-text-2019-08-23-03-03-13.png

Given that the first member of the initialiser is not highlighted as an error, it seems as though union-initialisation syntax is supported. https://dlang.org/spec/struct.html#static_union_init

**Comment by BenjaminSchaaf** [comment]
Looks like I completely missed this during the rewrite (and in all the D I've written). Sadly this syntax is quite ambiguous so the solution likely won't be perfect.

**Comment by Just-Harry** [comment]
> so the solution likely won't be perfect.

Thank you for your work on D's syntax-highlighting nevertheless :)
