### ISSUE TITLE
[JavaScript] Inherited class name scope

### ISSUE THREAD

**Issue by websash** [sublimehq/Packages#207]
Here:
```javascript
class Foo extends React.Component {
  // ...
}
```
both `Foo` and `Component` have the same scope: **`source.js meta.class.js entity.name.type.class.js`**. So `Component` can't be highlighted differently from `Foo`. 

`React` has correct **`source.js meta.class.js entity.other.inherited-class.js`** scope

`Component` should either have the same scope as `React` or more specific as **`source.js meta.class.js entity.other.inherited-class.js entity.name.type.class.js`**

**Comment by wbond** [comment]
This should be resolved by 53983b3b04dda1f6067a067a75c67f9633b457d7
