### ISSUE TITLE
Perl highlighting wrong after regex

### ISSUE THREAD

**Issue by lameventanas** [sublimehq/Packages#2074]
This Perl code shows a highlighting problem after a regex:
```
#!/usr/bin/perl

while (<CFG>) {
	next if /^\s*[#;]/ || /^\s*$/;
	chomp;
	/^\s*-{0,2}([^=\s]+)\s*=?\s*(.*?)\s*/;
	my ($key, $val) = ($1, $2);
	print "Highlighting is messed up after the regex\n";
}
```
![highlighing](https://user-images.githubusercontent.com/11934069/63765418-ed031d80-c903-11e9-991a-8344ce75f7bb.png)

**Comment by jfcherng** [comment]
LGTM, master branch

![image](https://user-images.githubusercontent.com/6594915/63767484-60a32b80-c900-11e9-9c31-627f0121a34d.png)

**Comment by lameventanas** [comment]
> LGTM, master branch
> 
> ![image](https://user-images.githubusercontent.com/6594915/63767484-60a32b80-c900-11e9-9c31-627f0121a34d.png)

What is LGTM?

**Comment by jfcherng** [comment]
@lameventanas looks good to me

**Comment by lameventanas** [comment]
> @lameventanas looks good to me

I tested with sublime 3 3207 for Linux, downloaded from the website, that's what it looks like.
I just started using this editor and wanted to see what it's capable of, so how do I fix this?

Also, @jfcherng and @michaelblyons , what font are you using?

**Comment by michaelblyons** [comment]
@lameventanas Look at [the README](https://github.com/sublimehq/Packages/blob/master/README.md) to see how to install pre-release versions of the syntax definitions.

I am using whatever font OSX decided I should have upon install.

**Comment by lameventanas** [comment]
Yes, it seems to have been fixed in master.
