### ISSUE TITLE
[JavaScript] non-latin character breaks highlighting

### ISSUE THREAD

**Issue by websash** [sublimehq/Packages#208]
Just in case you've missed my message in https://github.com/sublimehq/Packages/issues/204
```javascript
var angle = 2*π / count // angle between circles
```
here `/ count /` is detected as regex. It's interesting the problem arises when a non-latin character is used such as  π. 
I checked my alternative _JavaScript (Babel)_ syntax and this line is okay there

**Comment by wbond** [comment]
I did miss it, so thank you for posting it here as an issue.

The problem you were running into was fixed by d3baaed33fb5b098361aa4b4e4ef6db4245e2c0e.

However, I also added support for unicode identifiers in d6362b6a23638ebe07d17e5e85619dda217fadba.
