### ISSUE TITLE
List of resolved issues to close

### ISSUE THREAD

**Issue by deathaxe** [sublimehq/Packages#2082]
Not sure how to make an empty PR which just closes issues, so here is a list of issues, which are already resolved by merged PRs.

Closes #442
Closes #497
Closes #685
Closes #691 (invalid)
Closes #795
Closes #807
Closes #903
Closes #1141
Closes #1172
Closes #1245
Closes #1257
Closes #1286
Closes #1320
Closes #1357
Closes #1382 (wontfix)
Closes #1403
Closes #1451
Closes #1453 (maybe)
Closes #1472
Closes #1495
Closes #1540
Closes #1542
Closes #1565
Closes #1576
Closes #1625
Closes #1880
Closes #1898
Closes #1940 (invalid)
Closes #2111

**Comment by TheClams** [comment]
I think 2120 is solved as well.

**Comment by wbond** [comment]
These should all be closed off now. Thanks!
