### ISSUE TITLE
[JavaScript] distinguish between constructor name and params

### ISSUE THREAD

**Issue by websash** [sublimehq/Packages#209]
```javascript
var instance = new Constructor(param1, param2)
```
Can we distinguish between constructor name and its params? Currently they all have the same scope
```
source.js 
meta.instance.constructor.js 
meta.function-call.constructor.js 
variable.other.readwrite.js
```

**Comment by wbond** [comment]
Do you have a suggestion for the scope for `Constructor`? `variable.function.js` doesn't seem ideal since it could be an ES6 class.

**Comment by FichteFoll** [comment]
[`variable.type`](https://forum.sublimetext.com/t/a-convention-for-scope-naming/17105/11?u=fichtefoll)?

**Comment by wbond** [comment]
@FichteFoll Sounds good!

**Comment by websash** [comment]
yep, variable.type sounds okay to me too

**Comment by wbond** [comment]
280855d96b863ac02cc99ee29b83197021116a41 changes `Constructor` to `variable.type.js` and adds `meta.group.braces.round.js` to all constructor and function calls.
