### ISSUE TITLE
Add QML Syntax

### ISSUE THREAD

**Issue by S-B99** [sublimehq/Packages#2096]
Supporting the syntax out of the box would be really nice to QT theme developers. Thanks!

**Comment by FichteFoll** [comment]
>Supporting [syntax name] out of the box would be really nice to [framework] developers.

This sentence works with any language and is no compelling reason for Sublime Hq to add support for QML out of the box. There's a package mantained by the community that probably gets the job done well enough and is hopefully also maintained. https://packagecontrol.io/packages/QML

**Comment by wbond** [comment]
Unfortunately we don't have plans to add any new syntaxes to the default packages, except for possibly Swift and JSX. Working with the existing QML package, or working with other users on a new one would be the path forward.

If you visit https://forum.sublimetext.com/t/resources-and-bug-tracking/22985, there is a link to the Discord server, where a bunch of community members who contribute to the default packages hang out. They are generally very helpful if you have questions or want advice in regards to working on a syntax definition.
