### ISSUE TITLE
[JavaScript] missing 'dollar' scopes

### ISSUE THREAD

**Issue by jcberquist** [sublimehq/Packages#210]
For `$varname`, `$varname.someprop`, `$`, `$.someprop`, and `$()` some form of 'dollar' scope is applied to the `$` and to the rest of the variable name.

But for `$.each()` or `$varname.method()` there are no 'dollar' scopes. It is the same for a `$` used in a function declaration - for example `$.fn.new_plugin = function() {}`

**Comment by wbond** [comment]
This should be fixed by 89110d01833671c5ea15781436835fd29d8674d5

**Comment by jcberquist** [comment]
Thanks! I appreciate your thoroughness with this syntax.
