### ISSUE TITLE
Underscore in attribute values starts italics

### ISSUE THREAD

**Issue by Krinkle** [sublimehq/Packages#2117]
```
>
> One day, a [link](https://example.org){:target="_blank"} was made
>
```

<img width="614" alt="Screenshot 2019-10-05 at 18 01 15" src="https://user-images.githubusercontent.com/156867/66258204-25670880-e79a-11e9-9fed-cafc36e5bea0.png">

This uses Karmdown-style attributes, such as used by Jekyll and GitHub Pages.

**Comment by keith-hall** [comment]
[here is the Kramdown spec for this syntax](https://kramdown.gettalong.org/syntax.html#span-ials)
interestingly, Pandoc has a [similar syntax](https://pandoc.org/MANUAL.html#extension-link_attributes) but without the leading colon before the attribute names. I guess, if we will support this, we should cater for both styles (i.e. make the colon optional when scoping attributes inside curly braces after a link)
