### ISSUE TITLE
class name in declaration is not highlighted properly

### ISSUE THREAD

**Issue by safield** [sublimehq/Packages#2120]
When creating a c++ class in Sublime text, I have noticed that the color of the class name changes depending on whether it is proceeded by a namespace. Based on my color scheme, it seems like in both cases it should be green.

If there is no namespace, the class name will not be highlighted. If there is a namespace preceding the class name, the class name will be highlighted, but the namespace will not be.

The expected behavior is that the class and namespace be highlighted in all scenarios.

![c++_syntax](https://user-images.githubusercontent.com/12876404/66349997-c3381000-e91f-11e9-9ed1-fa659c1e5a89.jpg)

**Comment by rwols** [comment]
This was addressed in this pull request: https://github.com/sublimehq/Packages/pull/1661, and is now in the master branch. So it should end up in an official build some time soon.

**Comment by wbond** [comment]
Closing since this is fixed. The fix for this will be part of the next Sublime Text dev cycle, or you can use the master branch by following directions in the readme.
