### ISSUE TITLE
[Haskell] "&" does not get highlighted 

### ISSUE THREAD

**Issue by AllanZyne** [sublimehq/Packages#214]
![d8476d38-f973-455c-8c73-dc79f7552718](https://cloud.githubusercontent.com/assets/3166380/13348208/13507fd8-dcad-11e5-9b25-d7b10a839a7c.png)

and 

![rtx](https://cloud.githubusercontent.com/assets/3166380/13348489/c03a68a2-dcae-11e5-9aff-9c8dca693c16.png)

scope `meta.function.type-declaration.haskell` is wrong

**Comment by DrsExplorer** [comment]
I think we may match operactors in this way: ``[^\w\s_\(\)\[\]`"',:{}]+``

**Comment by wbond** [comment]
Is the `&` considered part of the same token as `==>`?

For example 2, what scope should that token receive?

**Comment by DrsExplorer** [comment]
Yes, I use code from this [tutorial](http://book.realworldhaskell.org/read/code-case-study-parsing-a-binary-data-format.html#id627853).

In example 2, I think that token could be "function parameter", but it can't be in "type-declaration".

**Comment by jrappen** [comment]
@AllanZyne The Haskell syntax is currently being rewritten in #2225. Maybe test that and give feedback there?
