### ISSUE TITLE
[Git Formats] Should we highlight other trailer fields?

### ISSUE THREAD

**Issue by FichteFoll** [sublimehq/Packages#2140]
Git commit messages allow for something called a "trailer", which the "Signed-off-by" feature of `git commit -s` utilizes and [`git interpret-trailers`](https://git-scm.com/docs/git-interpret-trailers) formalizes. Its use can be differen from project to project and the interpretation rules can be configured. I didn't find a mention about other trailer formats that git recommends besides "Signed-off-by", but I guess "Co-authored-by" is also quite popular, seeing how even [Github has special handling for it](https://help.github.com/en/github/committing-changes-to-your-project/creating-a-commit-with-multiple-authors). I've also seen "Reviewed-by".

My question is whether we should match such additional trailer fields and if yes, only specific ones (and which) or try to generalize, e.g. by matching `[\w-]+?-by: `.

**Comment by TheSecEng** [comment]
#### Located at: https://git-scm.com/docs/git-interpret-trailers

- `Co-authored-by: Bob <bob@example.com>`
- `Reviewed-by: Bob <bob@example.com>`
- `Acked-by: Alice <alice@example.com>`
- `See-also: fe3187489d69c4 (subject of related commit)`

**Comment by TheSecEng** [comment]
To clarify my above post, those are all trailers that are seen on the git-scm page. And I've seen `See-also` across various projects. I don't think we need to generalize it to allow for any match of that pattern but perhaps includes some very common cases wouldn't hurt.

We already have Signed-off-by and I don't think the above would hurt either. That said, I wouldn't want to include 20+ unique ones either.

**Comment by michaelblyons** [comment]
I confess I Ctrl+F'ed the page for `co-authored-by` and didn't find it, so I hadn't checked the others.

**Comment by michaelblyons** [comment]
We could do `\w[\w-]+\Bed-by:` to limit the generic one further in addition to the existing one(s) and `See-also:`.
