### ISSUE TITLE
[Rust] Ligatures mis-grouped

### ISSUE THREAD

**Issue by Shadlock0133** [sublimehq/Packages#2147]
- Sublime Version: 3.2.2
- OS Version: Windows 8.1

``` rust
bitmask >>= 1;
```

I'm using a Fira Code font.

In Rust file:
![image](https://user-images.githubusercontent.com/3766527/67568083-7b8cf300-f72b-11e9-9f53-c135820446f9.png)

For comparison, same line in C file:
![image](https://user-images.githubusercontent.com/3766527/67568124-9a8b8500-f72b-11e9-8179-ee7dd9dcac94.png)

**Comment by urschrei** [comment]
Does this problem also occur when using Rust-Enhanced? (https://github.com/rust-lang/rust-enhanced). If it does, you should open an issue there, as that's where the Rust syntax development happens.

**Comment by wbond** [comment]
@urschrei Unfortunately, no, Rust Enhanced generally does not upstream on contribute bug reports or fixes here, even after I have asked if they would work with us. They don’t like waiting for new builds to get fixes out, which is understandable, but also prefer not to follow the scope naming guidelines, so the syntaxes have diverged.

**Comment by Shadlock0133** [comment]
I tested it and the syntax file from Rust-Enhanced fixes the issue.

**Comment by jrappen** [comment]
@wbond Fixed by @TheClams in #2208.

**Comment by deathaxe** [comment]
Luckily #2305 doesn't break the fix by #2208.
