### ISSUE TITLE
[HTML] source.js.embedded.html scope starts inside script tag

### ISSUE THREAD

**Issue by jcberquist** [sublimehq/Packages#215]
In this syntax:
```html
<script type="text/javascript">
// code here
</script>
```
everything in the script tag after the opening `<script` gets the `source.js.embedded.html` scope. I think it should start after the `>` of the opening tag?

**Comment by wbond** [comment]
This should be resolved in d056ca685c90dfd0a8f55e1e76b52695c2ea043b
