### ISSUE TITLE
[JavaScript] multi-line have wrong scope

### ISSUE THREAD

**Issue by wprater** [sublimehq/Packages#216]
a function such as `fn(arg) {}` when cursor on the `fn` portion will have a scope of

* source.js 
* meta.group.braces.curly.js 
* meta.group.braces.round.js 
* meta.group.braces.round.js 
* meta.group.braces.round.js 
* meta.group.braces.curly.js 
* meta.method.js 
* string.unquoted.js 
* entity.name.function.js

and a multi-line
```
fn(
  arg) {}
```

* source.js
* meta.group.braces.curly.js 
* meta.group.braces.round.js 
* meta.group.braces.round.js 
* meta.group.braces.round.js 
* meta.group.braces.curly.js 
* meta.function-call.with-arguments.js 
* variable.function.js

Im not exactly sure what the difference is, but the syntax highlighting has broken for me on multi-line methods. perhaps we need to include the `meta.method.js` and `entity.name.function.js` scopes to a multi-line match?

**Comment by wbond** [comment]
Based on the scopes you pasted here, I believe you are using an older version of the syntax.

Additionally, I would need a more complete sample of your code, since the snippets you provide are missing many parent elements, which affect how the code is parsed.

**Comment by wprater** [comment]
Im using the babel syntax, so perhaps they are not actually including this one?  it should all be inherited, right?  Im using latest dev release.

they are being assiged to an object literal like

```
Object.assign(model, {
 fn() {}
});
```

**Comment by wbond** [comment]
I tested this code with the latest version of `JavaScript` and it highlights properly.

The Babel syntax is completely separate from JavaScript. It added various ES6 features before they were added to JavaScript, however within the past month or so JavaScript has significantly improved and now handles many edge cases not covered by the various third-party JS syntaxes on Package Control.
