### ISSUE TITLE
[JavaScript] forward slash in regex character classes

### ISSUE THREAD

**Issue by websash** [sublimehq/Packages#217]
Forward slash in regex character classes doesn't need to be escaped by a backslash. The following is a valid regex but in the current js syntax this slash terminates the regex prematurely
```javascript
var re = /^\/[^/]+/
//             ^ should be constant.other.character-class.set.regexp 
//               and should not terminate the regex here
```

**Comment by wbond** [comment]
This should be resolved by 97b0bd6f36d2250e6b20b6b045683b8b40516e59
