### ISSUE TITLE
[Python] Incomplete rules for dictionary unpacking

### ISSUE THREAD

**Issue by sconybeare** [sublimehq/Packages#2173]
I haven't fully learned how to read sublime-syntax files, but it seems to me that the code which attempts to disambiguate between dictionary and set literals is incomplete. Here's the case which it doesn't handle.

- Sublime Version: 3.2.2
- OS Version: macOS 10.14.6

``` python
{**x, 1: 2}
{**{}, 1: 1}
{**{1: 1}, 2: 2}
{**{x: y for x, y in pairs}, 1: 1}
```

![highlighting](https://user-images.githubusercontent.com/1170750/68061172-c3c68b00-fcc0-11e9-92c5-198ed36646e2.png)

**Comment by FichteFoll** [comment]
Thanks for the report. Fixed in #2174.
