### ISSUE TITLE
Arrow functions passed to functions produce

### ISSUE THREAD

**Issue by poke** [sublimehq/Packages#219]
foo(x => 'bar');

When passing an arrow function like this to a function, an error highlight is shown on the closing parenthesis. This essentially continues on all closing parentheses that occur outside of the arrow function, e.g.:

```js
baz(foo(x => x('bar')))
//                   ↑↑ both highlighted

baz(foo(x => x('bar')), 'other argument')
//                   ↑                  ↑ these two highlighted
```

**Comment by wbond** [comment]
What version of Sublime Text are you using? Are you using the latest JavaScript.sublime-syntax from this repo?

I can not reproduce the issue with the latest version of the syntax from this repo.

**Comment by wbond** [comment]
I added a test to confirm this in bdf3a442b5b0a838c617e1762609b4af00efeecd.

The version in this repo will be part of the next dev build. Alternatively you can use the instructions in this repo's readme to symlink/join the JavaScript directory into your `Packages/` directory. Just be sure to remove it after the next release so you do not get stuck on an old version.

**Comment by poke** [comment]
I am using the latest dev build (3107) and was assuming that it already got all the new JavaScript syntax fixes. Thanks for confirming that it’s already resolved and for adding a test!
