### ISSUE TITLE
[Scala] extends when Using Google Guice Framework

### ISSUE THREAD

**Issue by anhlt** [sublimehq/Packages#2197]
- Sublime Version: 3.2.2
- OS Version: Mac 10.14

![Screen Shot 2019-11-11 at 14 31 05](https://user-images.githubusercontent.com/1901110/68564483-17d92880-0494-11ea-90c0-81e84b2d9e3c.png)

``` scala
# Minimum code snippet to demonstrate the issue
import com.google.inject._
class A @Inject()(
    pool: RedisConnectionPool,
) extends B
```

``` lang
# Minimum code snippet to demonstrate the issue
```

**Comment by jfcherng** [comment]
![image](https://user-images.githubusercontent.com/6594915/68566358-11957d00-0491-11ea-80c5-9384ef7074b4.png)

Seems already fixed in the master branch.

**Comment by djspiewak** [comment]
Indeed it has been. When I rebuilt the Scala mode, I wasn't aware that annotations were a valid syntactic component in constructors in this fashion. Support was added in #2093
