### ISSUE TITLE
[HTML] Adding tag-class-attribute ?

### ISSUE THREAD

**Issue by subhaze** [sublimehq/Packages#220]
This is more of a question than issue.

Would you be against accepting a PR for adding `tag-class-attribute` to the current HTML.sublime-syntax file?

Main use case would be easily finding the scope of class to add auto-complete for known class names in style sheets. Instead of finding the generic scope, then backtracking in the code to see if we're at a class attribute.

**Comment by wbond** [comment]
I'm not quite sure what you mean by `tag-class-attribute`? Apologies!

**Comment by subhaze** [comment]
Oh sorry, was just feeding off the `tag-id-attribute` and `tag-style-attribute` in the syntax file. Basically just making a specific scope for `class="foo bar"`

where instead of:

```yaml
class="foo bar"
       ^^^^^^ text.html.basic meta.tag.any.html string.quoted.double.html
```

we would have:

```yaml
class="foo bar"
       ^^^^^^ text.html.basic meta.tag.any.html meta.attribute-with-value.class.html string.quoted.double.html meta.toc-list.class.html
```

(the above is taken from how id attributes are scoped `text.html.basic meta.tag.any.html meta.attribute-with-value.id.html string.quoted.double.html meta.toc-list.id.html`)

**Comment by wbond** [comment]
#223 has been merged, thanks!

**Comment by wbond** [comment]
FYI, I changed the scope names of the class names in 9d2ff48c8df42b42874360661e2c719e6278f3ec so not every tag with a class shows in the goto anything panel.

**Comment by subhaze** [comment]
Awesome, good catch, thanks!
