### ISSUE TITLE
[Lua] 'end' as table key un-indents itself and doesn't highlight properly

### ISSUE THREAD

**Issue by RheingoldRiver** [sublimehq/Packages#2203]
- Sublime Version: 3.2.2
- OS Version: Windows 7

``` lua
{
	end = "hello world"
}
```

![image](https://user-images.githubusercontent.com/18037011/68903346-7c002480-0700-11ea-932f-fe4967bcfb7a.png)

**Comment by FichteFoll** [comment]
This doesn't appear to be valid Lua code (tested in 5.3.5):
```
> {end="hello"}
stdin:1: unexpected symbol near '{'
```

**Comment by RheingoldRiver** [comment]
Oh ok, nvm then, yeah now that I try actually saving it mediawiki isn't happy with it either, though ["end"] = "hello" works
