### ISSUE TITLE
[c++] syntax highlighting problem with > follows a <

### ISSUE THREAD

**Issue by safield** [sublimehq/Packages#2216]
Example A: greater than and less than are properly colored
```
    if (a > b || c < d)
        return
```

Example B: great than and less than are both improperly color the default text color
```
    if (a < b || c > d)
        return
```

**Comment by rwols** [comment]
Instead of extending the `generic_lookahead` variable once more I think we should look into the new syntax features for this problem.

**Comment by deathaxe** [comment]
Closing this one in favour of #3113 as it provides some screenshots
