### ISSUE TITLE
[R] scope parens.begin not captured

### ISSUE THREAD

**Issue by jh-min** [sublimehq/Packages#2224]
- Sublime Version: 3.2.2 Build 3211
- OS Version: Windows 10

``` r
x<-c(1,2,3)
y<-c(1,2,3)
```
It seems that beginning parenthesis is not captured while ending parenthesis is properly captured.

![begin not](https://user-images.githubusercontent.com/57447828/69996844-3c598980-1596-11ea-8d59-9daa5401fd1e.PNG)
![end correct](https://user-images.githubusercontent.com/57447828/69996857-41b6d400-1596-11ea-9255-458c1bc192f4.PNG)

**Comment by randy3k** [comment]
It is fixed in `master`.
