### ISSUE TITLE
[JavaScript] after-operator context question

### ISSUE THREAD

**Issue by jcberquist** [sublimehq/Packages#224]
I noticed that in the `after-operator` context, the last pop pattern is `'(?=[\S\n])'`. Including the newline in there means that if I do something like this (admittedly somewhat odd):
```
var test =
{a: 1}
```
the object literal on the second line will be scoped as a block. Was there a reason that expression needs the newline in it?

**Comment by wbond** [comment]
That is a very good point. I've resolved the issue and added a test in c6c62e1e020acad2e7878acfac9615160e7d5421.
