### ISSUE TITLE
JavaScript Next syntax highlighting broken by backslash double-quote in a string

### ISSUE THREAD

**Issue by laukstein** [sublimehq/Packages#2245]
Ref https://github.com/sublimehq/sublime_text/issues/3170, https://github.com/Benvie/JavaScriptNext.tmLanguage/issues/9.

Try to add 

    window.foo = "{\"prop\": true}";

or

    sessionStorage.bar = "\"a\": 1";
    // here goes whatever code

before any JS code - you will notice Sublime Text syntax highlighting broken after that line.

![grabilla g13668](https://user-images.githubusercontent.com/183966/72044290-140f2a00-32bc-11ea-8eb6-cd9e28cab784.png)

**Comment by FichteFoll** [comment]
As you yourself already said in the references issue, this is a bug in the Javascript Nett syntax, not the default syntax bundled with Sublime Text, hence I'm closing this issue.

**Comment by wbond** [comment]
As you mentioned in the issue, this seems to be with the third-party syntax, JavaScript Next.

The JavaScript syntax that ships with Sublime Text (and that is part of this repo) does not have this bug.

<img width="404" alt="Screen Shot 2020-01-09 at 7 02 58 AM" src="https://user-images.githubusercontent.com/41734/72066297-300bcf00-32ae-11ea-8924-df167a002f85.png">
