### ISSUE TITLE
[Python] Classes and func'ns listed in symbol ref as "keywords"

### ISSUE THREAD

**Issue by michaelblyons** [sublimehq/Packages#2257]
I'm not totally sure whether this belongs here or at [sublimehq/sublime_text](https://github.com/sublimehq/sublime_text).

- Sublime Version: 4062
- OS Version: MacOS Catalina

## Expected behavior
<kbd>Cmd</kbd>+<kbd>R</kbd> shows classes with a `c` and functions with an `f`.

## Actual behavior
Both have a `k` (for keyword?) because the indexer is matching a `meta` scope that includes the `class` and `def`.

## Steps to reproduce

1. Open a Python file with ST4
2. <kbd>Cmd</kbd>+<kbd>R</kbd>

**Comment by wbond** [comment]
It belongs here. The syntax needs to be fixed to not mark the entire scope starting with `def` as the symbol. Only the function name should be marked as the symbol moving forward.

This will remove the indentation, `def` and `(...)` from the symbol list. I am sure that will take some getting used to, however most other syntaxes behave that way.
