### ISSUE TITLE
[Go] Syntax Highlighting Doesn't flag casts correctly

### ISSUE THREAD

**Issue by stevekuznetsov** [sublimehq/Packages#226]
When using a type to cast, such as `string(somevar)`, sometimes, `string` is highlighted as a type, sometimes as a method.

For example, purple highlighted fields are types, cyan are methods:
![screenshot from 2016-03-02 12 39 38](https://cloud.githubusercontent.com/assets/7328370/13469103/d99b753e-e073-11e5-8575-eeeddae1a71c.png)

Furthermore, when using custom types, it is always highlighted as a method. This may be correct?
![screenshot from 2016-03-02 12 41 01](https://cloud.githubusercontent.com/assets/7328370/13469159/08fef116-e074-11e5-86c5-7a8b433a7cbc.png)

**Comment by wbond** [comment]
The `string()` example is definitely an error. I will work on getting that fixed.

I'm not sure if there is going to be a way to detect the difference between a method call and type cast since we don't have a way to track the names of imported modules.

**Comment by stevekuznetsov** [comment]
Seems reasonable. A more targeted approach for syntax highlighting would leverage the Golang `ast` module instead of the Sublime syntax tools, but that's a discussion for another day.

**Comment by wbond** [comment]
@stevekuznetsov I'm not sure using the Go ast module would be possible. Currently Sublime Text can only highlight using grammars defined in `.tmLanguage` or `.sublime-syntax` files.

**Comment by stevekuznetsov** [comment]
I understand that - which is why I said it was a discussion for another day. An interface to allow for pluggable highlighters that could leverage language-specific tools would be much better than a sublime-specific highlighting language, in my opinion. That way there can be one package that generates highlighting metadata for a set of source code files, regardless of the editor.

**Comment by wbond** [comment]
This, plus a bunch of other Go warts should be resolved by db847cef8d906d43932d3e34924366155f40cb7f.

In terms of a pluggable highlighter, I don't see that being likely in the near future. This is mostly because of the essential nature of the highest performance possible, and the tight integration with the token storage memory used by the buffers.
