### ISSUE TITLE
async/await keywords from Python 3.5 are not properly highlighted

### ISSUE THREAD

**Issue by szastupov** [sublimehq/Packages#227]
Python 3.5 introduced native coroutines (https://docs.python.org/3/reference/compound_stmts.html#coroutines) and they should be properly highlighted.

**Comment by MattDMo** [comment]
I'll submit a PR for this soon.

**Comment by szastupov** [comment]
@MattDMo any update on this one? Maybe you need some help?

**Comment by wbond** [comment]
Support for: `async def`, `async for`, `async with`, `await` and the magic methods `__aenter__`, `__aexit__`, `__aiter__`, `__anext__`, `__await__` we added in 3a10e75c1d061d0eec3c5b2c3dd1cccede4f976c.
