### ISSUE TITLE
[Ruby] [SQL] Ruby inside SQL inside Ruby

### ISSUE THREAD

**Issue by nleo** [sublimehq/Packages#2279]
I'm sure `#{fields.map{|f| "'#{f}'"}.join(', ')}` should be highlighted as ruby code, not as comment

- Sublime Version: 3.2.2
- OS Version: Linux Mint 19.3 Tricia

``` ruby
execute <<-SQL
      CREATE TYPE user_notification_channel AS ENUM (
        #{fields.map{|f| "'#{f}'"}.join(', ')}
      );
    SQL
```

![image](https://user-images.githubusercontent.com/800970/74602302-34e74e00-50b8-11ea-8452-9f1af466e201.png)

**Comment by nleo** [comment]
It's really unreadable

![image](https://user-images.githubusercontent.com/800970/74603275-d2e01600-50c2-11ea-97db-fd96c11b512e.png)

**Comment by nleo** [comment]
Same in VS Code
![image](https://user-images.githubusercontent.com/800970/74603282-ea1f0380-50c2-11ea-9644-1bd14cc72247.png)

**Comment by deathaxe** [comment]
Most situations should have been fixed by https://github.com/sublimehq/Packages/pull/2054.

This is what it looks like in ST 4067

![grafik](https://user-images.githubusercontent.com/16542113/74606677-b2b85300-50d2-11ea-9e93-5fb2bfe67967.png)
