### ISSUE TITLE
 Syntax Highlight failure in D Scripts Technical Support

### ISSUE THREAD

**Issue by dataPulverizer** [sublimehq/Packages#230]
When programming in D highlighting fails when struct are created with no bracketing contents for example:

extern(C):
struct the_c_struct;

is perfectly acceptable D code but after the struct declaration referencing a struct in a c library highlighting fails for any subsequent code. Using

struct the_c_struct{};

allows highlighting to work but makes the struct opaque. In this case the syntax highlighting could lead to writing incorrect code.

DP

**Comment by wbond** [comment]
This should be fixed by 91e023c31eb090f9346177222104c6cc6a3da37e
