### ISSUE TITLE
[Python] Lambda in list is broken

### ISSUE THREAD

**Issue by gwenzek** [sublimehq/Packages#2301]
- Sublime Version: 4067
- OS Version: MacOS Catalina 10.15.3

Trying to write a lambda inside a list will break the syntax.
Not only the `]` is incorrectly marked as illegal, but it has a tendency to generate more error down the line.

``` py
    [lambda x, y: 10]
#   ^ punctuation.section.sequence.begin
#    ^^^^^^^^^^^^^^^ meta.function.inline
#    ^^^^^^ keyword.declaration.function.inline.python
#           ^^^^^ meta.function.inline.parameters
#           ^ variable.parameter
#            ^ punctuation.separator.parameters
#              ^ variable.parameter
#                 ^^ constant.numeric
#                   ^ punctuation.section.sequence.end
```

Packages/Python/syntax_test_python.py:1461:21: [punctuation.section.sequence.end] does not match scope [source.python meta.sequence.list.python meta.function.inline.body.python invalid.illegal.stray.brace.square.python]

**Comment by michaelblyons** [comment]
I was sure I had done this without the invalid marking. I had, but the closing `]` was on a new line.

I think the fix is a one-line change [right here](https://github.com/sublimehq/Packages/blob/master/Python/Python.sublime-syntax#L892) to add `\]` and `}`.

**Comment by wbond** [comment]
Also affects a `dict`:

```python
helpers = {'hello': lambda this: "foo"}
```
