### ISSUE TITLE
[Bash] Flags emphasis inconsistent for "merged" flag  `-o`

### ISSUE THREAD

**Issue by stdedos** [sublimehq/Packages#2306]
- Sublime Version: Sublime Text Build 3211
- OS Version: Ubuntu 16.04.6 LTS

```bash
# Minimum code snippet to demonstrate the issue
set -Eeuo pipefail
```

Flag emphasis is inconsistent for some reason when the `-o` flag is "glued" to others.
![image](https://user-images.githubusercontent.com/133706/75879337-e65de180-5e23-11ea-9b59-694675af235f.png)

Bug or feature?

(_I don't remember the term for writing the flags like that; feel free to educate/edit me_)

**Comment by michaelblyons** [comment]
I don't personally know _why,_ but it does look like `o` is "special"

https://github.com/sublimehq/Packages/blob/759d6eed9b4beed87e602a23303a121c3a6c2fb3/ShellScript/commands-builtin-shell-bash.sublime-syntax#L553

**Comment by deathaxe** [comment]
see: https://www.gnu.org/software/bash/manual/bash.pdf page 48

![grafik](https://user-images.githubusercontent.com/16542113/76454414-e6865000-63d4-11ea-89db-440946a10af0.png)

**Comment by michaelblyons** [comment]
@deathaxe That's the documentation for `test`. This ticket is special behavior for `set`, as generated from

https://github.com/sublimehq/Packages/blob/759d6eed9b4beed87e602a23303a121c3a6c2fb3/ShellScript/commands-builtin-shell-bash.yml#L114-L119

In [the Builtin docs](https://www.gnu.org/software/bash/manual/html_node/The-Set-Builtin.html), `-o`/`+o` looks different from the other options, but it's unclear to me whether this means that it's ineligible for use as a "compacted" option.

> ### `set`
>```
> set [--abefhkmnptuvxBCEHPT] [-o option-name] [argument …]
> set [+abefhkmnptuvxBCEHPT] [+o option-name] [argument …]
>```

Side notes:

- Is there a typo in the documentation usage? `[--a…]` or `[-a…]`?)
- Some browsers respect Adobe's hash arguments when loading PDFs. The most useful one is direct-linking pages. Try https://www.gnu.org/software/bash/manual/bash.pdf#page=52. (Sorry I don't remember where I found this or any of the other shortcuts.)

**Comment by deathaxe** [comment]
The `-o` is special in not being a switch only, but being followed by an option name. While `set -Eeuo pipefail` is valid, `set -Eeou pipefail` wouldn't be. The algorithm to generate the syntax would need to be tweaked to allow `short-options` at the end of `short-options-compact` only (if merged).

Maybe `match: (?:\s+|^)((\-|\+)(?:[o]|[abefhkmnptuvxBCEHPT]+o?))(?=\s|;|$|`|\))`

---

About `[--a...]` : I guess it denotes the `--` token in an unlucky way.

See usage output: `set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]`

---

About PDFs: DuckDuckGo just pushed me there. The Windows snipping tool just was the easiest way here. Just was to lazy to think about it more carefully ;-)
