### ISSUE TITLE
[Lua] Autocomplete closed parentheses before comma

### ISSUE THREAD

**Issue by RheingoldRiver** [sublimehq/Packages#2314]
- Sublime Version:3.2.2, build 3211
- OS Version:Windows 10

## Expected behavior

Before a `,` an `(` should be autocompleted by a `)` (same for brackets and braces)

## Actual behavior

The parenthesis isn't autocomplete-closed

## Steps to reproduce

1. Type ,
2. Press left arrow
3. Type (

![image](https://user-images.githubusercontent.com/18037011/77251070-2c83b500-6c1a-11ea-9846-2d704fcd012b.png)

```lua
		orderBy = (,
		types = {
			IsLegacy = 'boolean'
		}
```

**Comment by FichteFoll** [comment]
This behavior is the same for every language and not unique to Lua. Since it's a binding defined in the Default package, I suggest moving this to https://github.com/sublimehq/sublime_text.
