### ISSUE TITLE
[Python] Marking lambda in dict as invalid

### ISSUE THREAD

**Issue by wbond** [sublimehq/Packages#2333]
- Sublime Version: 4073
- OS Version: macOS 10.15.4

```python
helpers = {'hello': lambda this: "foo"}
```

<img width="294" alt="Screen Shot 2020-04-16 at 9 11 35 AM" src="https://user-images.githubusercontent.com/41734/79460076-4c608b80-7fc2-11ea-8286-33ad1de5ea97.png">

**Comment by michaelblyons** [comment]
Related: #2301

**Comment by wbond** [comment]
Should have looked harder 🙂
