### ISSUE TITLE
[JavaScript] Optional chaining does not work properly

### ISSUE THREAD

**Issue by ghost** [sublimehq/Packages#2349]
Examples:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

```js
object?.key;
object?.[key];
object?.(key);
```

Actual:

![](https://user-images.githubusercontent.com/64195804/80082748-13da2800-8555-11ea-9fc5-fa0311094cde.png)

Expected:

![](https://user-images.githubusercontent.com/64195804/80082763-176daf00-8555-11ea-85c2-1110e94d69a2.png)

or

![](https://user-images.githubusercontent.com/64195804/80082771-19d00900-8555-11ea-9365-4015293edaec.png)

Introduced in https://github.com/sublimehq/Packages/pull/2132

/cc author @Thom1729

**Comment by jfcherng** [comment]
In #2132, it uses `.?` as the accessor. But the correct one should be `?.`.

**Comment by fastcoder15** [comment]
Given that many JavaScript engines already support this feature, can we expect a reasonably fast fix? @Thom1729
