### ISSUE TITLE
[Clojure] Supporting ClojureScript

### ISSUE THREAD

**Issue by oconnor0** [sublimehq/Packages#2351]
ST supports ClojureScript by treating it as if it was Clojure (https://github.com/sublimehq/Packages/blob/master/Clojure/Clojure.sublime-syntax#L9). For the purposes of highlighting the source, this is probably the right choice.

Unfortunately it complicates tooling that wants to interact with Clojure vs ClojureScript. Both [Zeal](https://github.com/vaanwd/Zeal) and [SublimeLinter-contrib-clj-kondo](https://github.com/ToxicFrog/SublimeLinter-contrib-clj-kondo) _[^1]_ use the scope to determine what the contents of the file are and how to resolve them; meaning that they don't quite work for ClojureScript out of the box. [SublimeREPL](https://github.com/wuub/SublimeREPL) works around the issue by including a [partial definition of ClojureScript](https://github.com/wuub/SublimeREPL/blob/master/config/ClojureScript/clojurescript.tmLanguage).

Another complication is that ".cljc" files are either Clojure or ClojureScript depending on how/where they are executed. And the correct way to handle ".edn" files as they aren't quite Clojure or ClojureScript but a subset.

As an experiment, I copied https://github.com/sublimehq/Packages/blob/master/Clojure/ into /Packages/ClojureScript and renamed all references to "Clojure" or "clojure" to "ClojureScript" and "clojurescript" respectively. This appeared to work as I desired but is likely the wrong choice for a number of reasons (including pointless duplication of code).

I expect there is at least 1 cleaner way to do the above (probably embedding the Clojure syntax in ClojureScript) and maybe another (I've seen ".tmPreferences" that seem to do a similar embedding).

Anyway, I am trying to get a feel for the right way to proceed here. I'd like to see ST natively support ClojureScript, but it was handled differently than that so don't want to break things either. I can submit a PR to add ClojureScript. I can make a standalone ClojureScript package. I can work with the package authors to deal with seeing a Clojure scope when seeing ClojureScript code. There are probably other options I haven't considered.

[^1]: https://github.com/ToxicFrog/SublimeLinter-contrib-clj-kondo/issues/1

**Comment by michaelblyons** [comment]
At the bottom, see the sublime-syntax way of doing the [SublimeREPL tmLanguage](https://github.com/wuub/SublimeREPL/blob/master/config/ClojureScript/clojurescript.tmLanguage). I have personally never used either Clojure nor ClojureScript, so I would not know whether there are any additional rules one would need to add for cljs.

> Another complication is that ".cljc" files are either Clojure or ClojureScript depending on how/where they are executed. And the correct way to handle ".edn" files as they aren't quite Clojure or ClojureScript but a subset.

The "depending on how/where they are executed," part of that sounds like alternate build systems. But if they're linted differently, you'd need to identify them by file extension (or first line?). Once again, not knowing the details, I can't say whether this is feasible. If there's another way to identify them on the fly, _you_ could use [a third party package](https://packagecontrol.io/packages/ApplySyntax) to enable more "which syntax is this?" rules, but obviously that would not work for everyone out of the box.

For edn files, one could include specific contexts from Clojure into a new file, [`- include: source.clojure#match-noise`](https://github.com/sublimehq/Packages/blob/master/Clojure/Clojure.sublime-syntax#L190). (Assuming those particularly contexts are already built nicely, that is. You wouldn't be able to do this if edn was, say, "Clojure without numerical values," and you might also have to break some bigger blocks into smaller pieces to include just the ones you want.)

Packages/Clojure/ClojureScript.sublime-syntax:

```yaml
%YAML 1.2
---
# https://www.sublimetext.com/docs/3/syntax.html
name: ClojureScript
scope: source.clojurescript
# Maybe source.clojure.script?

file_extensions:
  - cljs

contexts:
  main:
    - include: source.clojure
```

**Comment by oconnor0** [comment]
> But if they're linted differently, you'd need to identify them by file extension (or first line?).

I would think that triggering off scope would be more general as it could support highlighting or linting in temporary buffers or REPLs or whatever that don't have a file extension.

**Comment by michaelblyons** [comment]
> I would think that triggering off scope would be more general [...]

Yes, but scope is determined by...:drum: file extension and first line. 😉
