### ISSUE TITLE
[Markdown] The latest update broke syntax highlight inside fenced blocks

### ISSUE THREAD

**Issue by evandrocoan** [sublimehq/Packages#2353]
After the latest commit https://github.com/sublimehq/Packages/commit/c08f85346a04d2e12990c3008e7666306b59a05b to the Markdown syntax, the fenced block syntax highlight is broken.

````
```sql
/**
 * Find all audio and video tags and run them through the callback parameter.
 * @param {Function} callback - to be called on each media.
 * @param {Array}    initial  - an additional list of items to be iterated over.
 */
function setAnkiMedia(callback, initial = undefined)

/**
 * Automatically add all media elements found and start playing them sequentially.
 * @param {string} where - pass "front" if this is being called on the card-front,
 *        otherwise, pass "back" if it is being called on the card-back.
 * @param {number} speed - the speed to play the audio, where 1.0 is the default speed.
 *        Each media element can also have a attribute as `data-speed="1.0"` indicating
 *        the speed it should play. The `data-speed` value has precedence over this parameter.
 */
addall(where, speed = 1.0)
```
````

Without that commit everything works fine:

![image](https://user-images.githubusercontent.com/5332158/80894963-684c7880-8cb6-11ea-9db2-b2fcb313f6c6.png)

With that commit, any language set on `` ```lang `` is complely ignored and the contents of the block is always highlighted the same way, with invalid scopes as:

1. `text.html.markdown markup.list.unnumbered.markdown meta.paragraph.list.markdown markup.italic.markdown`
1. `text.html.markdown markup.list.unnumbered.markdown meta.paragraph.list.markdown markup.italic.markdown invalid.illegal.non-terminated.bold-italic.markdown `

![image](https://user-images.githubusercontent.com/5332158/80895000-8914ce00-8cb6-11ea-9f2e-233c0865078f.png)

### Environment

* Operating system and version:
  * Windows `10 build 15063 x64`
  * Resolution `1920x1080`
  * dpi_scale `1.0`
  * Sublime Text:
  * Build `3207`
  * 64 bit

**Comment by jfcherng** [comment]
It requires you to use ST >= 4050.
