### ISSUE TITLE
[PHP] Multilining Exceptions in a try {...} catch () correctly breaks highlighting

### ISSUE THREAD

**Issue by Smudge3806** [sublimehq/Packages#2358]
- Sublime Version: 3.2.2
- OS Version: Darwin 19.4.0 aka macOS Catalina 10.15.4

``` php
/*
  According to the PSR standards, this is the correct way to multiline
  multiple exceptions within a single catch statement
*/

try {
    // some code
} catch (
    UnexceptedValueException |
    InvalidArgumentException |
    FirstPartyException |
    VendorException $exception
) {
    // some code
}
```

Working highlighting but non-compliant code
![Screenshot 2020-05-07 at 12 16 56](https://user-images.githubusercontent.com/1736867/81288495-ab16a380-905c-11ea-85fa-091897c2be94.png)

Broken highlighting but compliant code
![Screenshot 2020-05-07 at 12 16 18](https://user-images.githubusercontent.com/1736867/81288449-92a68900-905c-11ea-807d-ef22f0558906.png)

**Comment by jfcherng** [comment]
As you are nothing using ST 4, see https://forum.sublimetext.com/t/php-7-4-typed-properties-syntax-highlighting/50687/2?u=jfcherng.
