### ISSUE TITLE
[Clojure] ? > < = + etc not included in auto-completion

### ISSUE THREAD

**Issue by oconnor0** [sublimehq/Packages#2361]
- Sublime Version: 4074
- OS Version: Windows 10

## Expected behavior

Auto-completion recognizes the "special characters" that are part of a symbol name and doesn't exclude them.

## Actual behavior

A symbol defined with a ? < > = + in the name truncates the symbol in auto completion.

## Steps to reproduce

1. Create a Clojure file with

    ```clojure
    (def abc?)
    (def b->c)
    (def c-<d)
    ```

2. Below that type:

    ```clojure
    (if a
    ```

3. Observe the auto-completion popup that lists `abc` only.

4. Or

    ```clojure
    (b-
    ```

5. Observe the auto-completion popup that lists `b-` only.

Goto Definition appears to work correctly (e.g., `abc?` or `b->c`); and does not work if I just type `abc` or `b-`.
Goto Symbol lists the correctly defined symbols: (e.g., `abc?` and `b->c`).

There may be other characters that aren't supported. As I investigated, it looked like most non-alphanumeric characters aren't being included in auto-completion. It also appears that symbols comprised entirely of operator characters aren't included in auto-completion even when defined as "goto"-able things by the language definition.

**Comment by deathaxe** [comment]
The symbols - defined by the syntax - are correctly indexed which makes them appear in the Goto Symbol panel, so this is more likely a core issue. The AC system does a lot of general heuristics beyond using the tokens defined by the syntax to try to guess what to add to completions, which IMHO must fail for syntaxes with less common grammers.

The _Clojure.sublime-settings_ defines `"word_separators": "/\\()[]{}\"'`,:;@#^~."`. Maybe the AC does not make use of that custom set of separators and therefore doesn't recognize the function identifiers?

**Goto Symbol**

![grafik](https://user-images.githubusercontent.com/16542113/82116562-08040f00-976b-11ea-87f9-e16a53bbef1c.png)

**Completions**

It apears only word completions are suggested. The tokens of scope `entity.name.function` are comletely missing.

![grafik](https://user-images.githubusercontent.com/16542113/82116590-3bdf3480-976b-11ea-9d45-b9ddf0d6976a.png)

**Comment by oconnor0** [comment]
Does that mean this issue should be moved to https://github.com/sublimehq/sublime_text/issues/?

**Comment by deathaxe** [comment]
I think so. Don't see how to change the syntax or any meta data to make completions work.

**Comment by oconnor0** [comment]
Moved to https://github.com/sublimehq/sublime_text/issues/3352
