### ISSUE TITLE
Bash comment

### ISSUE THREAD

**Issue by haraldh** [sublimehq/Packages#2367]
I think this:
https://github.com/sublimehq/Packages/blob/f36b8f807d5f30d2b8ef639232a9fc5960f550fa/ShellScript/Bash.sublime-syntax#L85

should be:
```
        - match: '(?=\n)'
          scope: comment.line.number-sign.shell
          pop: true
```

the effect can be seen with:

```bash
echo "Hello World" # comment
echo "Hello World"
```

which does not color `echo` again.

**Comment by haraldh** [comment]
as can be seen here, too..
https://harald.hoyer.xyz/console/

**Comment by michaelblyons** [comment]
Cannot reproduce.

<img width="239" alt="Screen Shot 2020-05-19 at 3 23 23 PM" src="https://user-images.githubusercontent.com/2701605/82369249-3e10ef80-9a06-11ea-8586-0245621b1244.png">

I have two active branches with Bash changes merged into my live setup: #2309 and a local one to highlight escape characters in strings like the snippet below. Neither should be affecting your bug report.

``` bash
echo -e "\e[33m+\e[0mAhead and \e[31m-\e[0mBehind commits compared to..."
```

**Edit:** Tested `master`, too, and still NOREPRO.

**Comment by haraldh** [comment]
Ok, thanks! Then let's close this. Must be the [syntect](https://github.com/trishume/syntect) engine somehow then..

**Comment by rwols** [comment]
Off-topic perhaps, but I think that `\n` workaround can be removed for st40xx builds.

**Comment by FichteFoll** [comment]
Since somewhere around 7073, yes.
