### ISSUE TITLE
[Python] wrong hot pink highlighting for regex/f-string

### ISSUE THREAD

**Issue by fersarr** [sublimehq/Packages#2368]
The regex and the program below work fine but 2 lines are getting highlighted with hot pink as if they were incorrect.

- Sublime Version: 3.2.2 build 3211
- OS Version: mac

``` Python
import re


def myfunc(text):

    number = '[0-9]'
    regex1 = fr"[\[]{number}[\]]"
    regex2 = fr"[\{{]{number}[\}}]"

    text = re.sub(regex1, 'HERE1', text)
    text = re.sub(regex2, 'HERE2', text)
    return text


print(myfunc('test [3] test {3}'))
```
I have simplified the program above to show the issue and remove the noise. So it might look like a ridiculous way of doing that, but it's just because I have removed all the context.

<img width="449" alt="Screen Shot 2020-05-22 at 1 15 32 PM" src="https://user-images.githubusercontent.com/3913371/82667089-0a64de00-9c2f-11ea-9ee5-7afce7d2b46e.png">

Is there a way I can disable this hot pink in the mean time?

UPDATE:
It also affects subsequent function definitions:
![Screen Shot 2020-05-22 at 2 41 11 PM](https://user-images.githubusercontent.com/3913371/82673895-6b45e380-9c3a-11ea-9d0b-a1772a4b0215.png)

**Comment by jfcherng** [comment]
LGTM with `master` branch. `st3` branch untested.

**Comment by fersarr** [comment]
Cool, thanks for checking. So, does that mean that it's just a matter of time until there's a new release?

**Comment by jfcherng** [comment]
The `st3` branch seems good on my test. So you can follow the step in README to use the "latest" syntax definition. Or if you know the fact that syntaxes are just built-in plugins and you can override a plugin file.

**Comment by fersarr** [comment]
worked perfectly! thank you!
