### ISSUE TITLE
[Question] How to export highlighting?

### ISSUE THREAD

**Issue by AhmedYusuf99** [sublimehq/Packages#2373]
- Sublime Version: any
- OS Version: any

Hello. Is there a way to export highlighting to a file, so that it can be used by a 3rd party software?

Given a syntax definitions file (for example `Python.sublime-syntax`) and given a source file (for example `test.py`), I would like to somehow generate a text file (or JSON, or CSV, or any other format) that contains mapping from source code positions to colors that would be displayed when opened in ST. Something like this:

```
test.py: line 1 chars[0-5] color: red
test.py: line 1 chars[6-11] color: white
test.py: line 2 chars[0-3] color: green
test.py: line 3 (empty)
test.py: line 4 chars[0-2] color: blue
...
```

It can be in any format, I can easily parse it once I find out how to generate such a thing. Is there an easy way to do so? I see there are some automatic tests that check correct scopes in this repo, so how that actually works and can scopes information be exported somehow?

**Workaround**

Currently I use the following workaround. I created a program to start a Linux virtual machine in the background, then copy syntax definitions file and source file into the virtual machine, then start ST inside the VM. Then the program captures the VM screen, then scrolls one page down, captures the screen again, and so on, until the end of the file is reached. Then the program processes all the images to extract colors. It works, but it is extremely slow and inefficient and involves a lot of complex image processing algorithms. Is there an easier way?

**Comment by jfcherng** [comment]
i think the ExportHTML plugin is kinda doing that but the exported format is rendered HTML. but maybe you can modify the plugin to fit your needs.

**Comment by AhmedYusuf99** [comment]
@jfcherng I would like to avoid external plugins with a lot of dependencies. The command for extracting scopes sounds better. But I get an error:

```console
>>> view.extract_tokens_with_scopes(sublime.Region(0, len(view)))
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'View' object has no attribute 'extract_tokens_with_scopes'
```

What is the problem here? Does my version ST 3.0 3143 support that feature?

**Comment by jfcherng** [comment]
> Does my version ST 3.0 3143 support that feature?

It looks like no. Not sure when is `view.extract_tokens_with_scopes()` introduced but it works in build 3211. Maybe you can use `view.extract_scope()` to iterate the whole file instead.

**Comment by AhmedYusuf99** [comment]
@jfcherng Hey, you are correct! Thank you very much. The problem was old version. I just downloaded a fresh cracked ST 3211 from The Pirate Bay

![](https://user-images.githubusercontent.com/65954396/83322010-9345d000-a254-11ea-989a-9b72dcbb83e4.png)

Then I open console and paste your command and it works perfectly:

![](https://user-images.githubusercontent.com/65954396/83321984-6a253f80-a254-11ea-9022-10a67c3d95ae.png)

Now I can save it to a file and process it later. Thanks again for help!

**Comment by Ultra-Instinct-05** [comment]
Why do you need to use a cracked version of 3211 (also using pirated software is wrong. You are basically kicking the developer's belly who have put so much effort into the tool) when you can download the official release from the following website : https://www.sublimetext.com/3 ?

**Comment by wbond** [comment]
This is the incorrect place to ask questions about using Sublime Text. Those should be posted at https://forum.sublimetext.com.

I've removed a comment discussing pirating of Sublime Text. That has no place here.
