### ISSUE TITLE
[JavaScript] Wrong bracket highlighting with arrow functions

### ISSUE THREAD

**Issue by jlegewie** [sublimehq/Packages#238]
This looks like a problem with arrow functions. The brackets are actually correct and shouldn't be red. Sublime Text Build 3107. Here are the scopes: source.js meta.object-literal.js meta.block.js meta.conditional.js meta.group.braces.round.js meta.function-call.method.js meta.block.js invalid.illegal.stray.brace.round.js

```
if (!base_folders.map(dir => f.path.startsWith(dir)).some(x => x === true)) return;
```

<img width="596" alt="screen shot 2016-03-14 at 6 17 48 pm" src="https://cloud.githubusercontent.com/assets/1292401/13763069/735a2b92-ea11-11e5-8ebe-a9afbe71bd18.png">

**Comment by FichteFoll** [comment]
I guess this is already fixed in the current version here.

**Comment by wbond** [comment]
Yes, this is fixed in the master branch.
