### ISSUE TITLE
[Makefile] Shell flag highlighting

### ISSUE THREAD

**Issue by GiovanH** [sublimehq/Packages#2388]
- Sublime Version: 3.2.2 b3211
- OS Version: Windows 10

There's a bug in the built-in makefile syntax. Specifically, color highlighting. 
The first flag in a command is properly colored blue, but any following flags aren't. 

See the test string:
    
``` Makefile
html:
	$(PELICAN) $(INPUTDIR) -o $(OUTPUTDIR) -s $(CONFFILE) $(PELICANOPTS)
```
In Sublime Text, -o is correctly highlighted, but -s is not.

This may be related to #1699

**Comment by deathaxe** [comment]
I'd rather say the `-o` is scoped wrong, while `-s` and any following option is scoped `variable.parameter` as expected.

![grafik](https://user-images.githubusercontent.com/16542113/88570288-16f52080-d03c-11ea-935b-ec4dc7e887d2.png)
