### ISSUE TITLE
A file icon for PHP wont' be loaded.

### ISSUE THREAD

**Issue by jfcherng** [sublimehq/Packages#24]
Currently in my test, to set the file icon for a `.php` file which starts with `<?php`, we need to use the scope `embedding.php` rather than `source.php`.

Will this be changed back to `source.php` or just use `source.php, embedding.php` for the icon settings in the future?

**Comment by sublimehq** [comment]
I'd recommend the "source.php, embedding.php" for past and future compatibility. The old-style system where "source.php" worked relied on a series of ugly hacks, that had some unfortunate side effects, just as JavaDoc including PHP, which made no sense.
