### ISSUE TITLE
[JavaScript] Syntax error for arrow functions in arrays in certain locations

### ISSUE THREAD

**Issue by rluba** [sublimehq/Packages#241]
The following (valid) JavaScript code is considered invalid by the current version (d8120135) of the JavaScript package:
```JavaScript
'use strict';

someFunction(() => [() => 'X']);
```

The last parenthesis is marked as invalid:
<img width="286" alt="array arrows" src="https://cloud.githubusercontent.com/assets/4600573/13813395/a111bd04-eb81-11e5-8265-1256fdde14ff.png">

**Comment by wbond** [comment]
This should be resolved by cb9742ff7ec7d78e6d8a0addfa3fb8a690fc29ee
