### ISSUE TITLE
[Ruby] Wrong scope name for nested classes 

### ISSUE THREAD

**Issue by joseramonc** [sublimehq/Packages#2410]
- Sublime Version: 3.2.2 build 3211
- OS Version: MacOS Catalina 10.15.6

``` ruby
SomeClass::Nested
```

![image](https://user-images.githubusercontent.com/1993929/87704233-b4f60a80-c761-11ea-8101-6965b4686e4c.png)

I'd expect the above to have `support.class.ruby`, the same as `SomeClass`

**Comment by danillos** [comment]
I agree, this is really annoying. 😢

**Comment by wbond** [comment]
These packages are open source and primarily developed and maintained by the community, but with some help from Sublime HQ (who employs me).

Currently we don't really have any active community members maintaining the Ruby syntax. If one of you, or anyone else, is keen on getting involved, it would be great to see some improvements to `Ruby.sublime-syntax`.

If someone is interested in getting involved, reading over the following is probably a good place to start in terms of understanding what goes into a syntax:

 - https://www.sublimetext.com/docs/syntax.html
 - https://www.sublimetext.com/docs/scope_naming.html
