### ISSUE TITLE
[JavaScript] Block comment is not highlighted as expected if previous line doesn't end with ;

### ISSUE THREAD

**Issue by predragnikolic** [sublimehq/Packages#2413]
- Sublime Version: 4079
- OS Version: Ubuntu 19.10

``` javascript
function function_name(argument) {
    numbers = [1,2,3]

    /*
     * Block Comment
     */

    numbers = numbers.map(x => x * x)
}

```
Note: Missing a `;` at this line `numbers = [1,2,3]`

![image](https://user-images.githubusercontent.com/22029477/87885266-f530e380-ca14-11ea-99a3-61c3d8a578e7.png)

Here is an even minimal example (just indent one tab to the right):

``` javascript

    numbers = [1,2,3]

    /*
     * Block Comment
     */

    numbers = numbers.map(x => x * x)
```

There are two ways to fix this highlighting issue:
1. put a  `;` at the end of the line  `numbers = [1,2,3];`

![image](https://user-images.githubusercontent.com/22029477/87885288-23aebe80-ca15-11ea-9a64-098843be4cfc.png)

2. Have no indentation to in the code:
``` javascript

numbers = [1,2,3]

/*
 * Block Comment
 */

numbers = numbers.map(x => x * x)
```

**Comment by Thom1729** [comment]
Looks like a bug in the code that handles automatic semicolon insertion. The linked PR should fix it.

**Comment by predragnikolic** [comment]
Thanks @Thom1729, that was really quick :)

**Comment by Thom1729** [comment]
Thanks for the report (and for the copy-pastable test cases).

This bug must have been there awhile; I'm surprised that it hasn't come up before. The ASI logic is one of the tricker bits of the syntax, so I'm glad that it was an easy fix.
