### ISSUE TITLE
[Git Formats] Regression in aliases with embedded shell

### ISSUE THREAD

**Issue by michaelblyons** [sublimehq/Packages#2419]
- Sublime Version: 4079
- OS Version: MacOS 10.15.5

``` cfg
[alias]
    clean-merge-artefacts = "!find . -name *.orig -type f -delete"
    #                         ^^^^^^^^^^… Used to embed Bash, but now does not.
```

It's funny that all the tests pass because they only check for `source.shell` and none of the actual mechanics of Bash.

**Comment by deathaxe** [comment]
Sure?

Seems to work fine on a vanilla ST 4079 and with _Git Formats_ and _ShellScript_ from current master here.

![grafik](https://user-images.githubusercontent.com/16542113/88096106-6d72e280-cb96-11ea-8fd6-2dcff8fb13d2.png)

**Comment by michaelblyons** [comment]
<img width="595" alt="Screen Shot 2020-07-21 at 3 15 06 PM" src="https://user-images.githubusercontent.com/2701605/88096694-9ab79480-cb86-11ea-91aa-21c0c683c019.png">

I probably have something weird going on, then, but I haven't figured out what it is. I've tried my integration branch as well as master. Both of them are symlinked to Packages. 🤔

**Comment by michaelblyons** [comment]
You are right. It's just a local problem, but still not clear exactly what, yet. https://github.com/sublimehq/Packages/pull/2425

**Comment by michaelblyons** [comment]
Okay. So in case anyone else has this problem: It's a cache of the `ShellScript/Shell-Unix-Generic.sublime-syntax`. You need to open up that file, make a trivial change, save, revert, and save again.
