### ISSUE TITLE
[Erlang] Comparison operators have the wrong scope

### ISSUE THREAD

**Issue by jwortmann** [sublimehq/Packages#2428]
Comparison operators like `==` or `<` have the scope [keyword.operator.logical](https://github.com/sublimehq/Packages/blob/db6bd3d8b2433e0f8bfa242619d81c0ce460a64c/Erlang/Erlang.sublime-syntax#L1908) currently. It's not explicitly mentioned in the scope naming guidelines, but I believe all other syntaxes use `keyword.operator.comparison` for those instead. Using the latter scope would also allow color schemes to distinguish from word-based logical operators (`and`, `or`, ...), which use the exact same scope name currently.

There seem to be two items in the linked regex match that probably should get special casing and another scope: `!` ([send operator](https://erlang.org/doc/reference_manual/expressions.html#send)) and `=!` (I don't know what this one is used for).

Note: I've never used Erlang, just found this while trying to tweak my color scheme.

**Comment by deathaxe** [comment]
Good catch. Seems to be missing in PackageDev's tree of scopes.
