### ISSUE TITLE
[PHP] Invalid scope

### ISSUE THREAD

**Issue by akalongman** [sublimehq/Packages#244]
Example:
```php
public function myFunc(
        $param1,
        $param2,
        $param3
    ) {
```
Scope of $param3 is invalid: embedding.php text.html.basic meta.embedded.block.php source.php meta.function.php meta.function.arguments.php

Must be: embedding.php text.html.basic meta.embedded.block.php source.php meta.function.php meta.function.arguments.php meta.function.argument.no-default.php variable.other.php

**Comment by akalongman** [comment]
@wbond

**Comment by FichteFoll** [comment]
As an aside, that mention was completely unnecessary. I'm sure Will knows by himself how to keep track of the issues here and how to prioritize.
