### ISSUE TITLE
javascript havent highlight docblock

### ISSUE THREAD

**Issue by jingyuexing** [sublimehq/Packages#2445]
# vscode
![图片](https://user-images.githubusercontent.com/19589872/89878360-058f4500-dbf4-11ea-8123-77b30757ac88.png)

#sublime
![图片](https://user-images.githubusercontent.com/19589872/89878436-2061b980-dbf4-11ea-963a-edaef636e8c6.png)

**Comment by keith-hall** [comment]
see https://github.com/sublimehq/Packages/issues/618 for a discussion

**Comment by jingyuexing** [comment]
> 
> 
> see #618 for a discussion

ok

**Comment by michaelblyons** [comment]
Close as duplicate?
