### ISSUE TITLE
[PHP] Improve variable scope

### ISSUE THREAD

**Issue by andremacola** [sublimehq/Packages#2459]
The second dollar sign should be in the same scope as the first one or in a different scope from the string name.

The second dollar sign and string scopes are the same: `embedding.php text.html.basic meta.embedded.block.php source.php punctuation.definition.variable.php variable.other.class.php`

![php-scope-issue](https://user-images.githubusercontent.com/3408809/90971863-34f25b80-e4ea-11ea-9b80-5603d58f466e.png)

- Sublime Version: 4
- OS Version: 4084

See for example, Github:
``` php
$timber              = new \Timber\Timber();
$timber::$dirname    = array( 'views' );
$timber::$autoescape = false;

self::$somevar
```

**Comment by andremacola** [comment]
You right, the scope for the dollar sign is the same but not for the name. If the goal is to colorize only the `$` this has to change I think.

- The 1st one `embedding.php text.html.basic meta.embedded.block.php source.php variable.other.php`
- The 2nd one `embedding.php text.html.basic meta.embedded.block.php source.php punctuation.definition.variable.php variable.other.class.php`

**Comment by jfcherng** [comment]
I don't know but someone can always file a PR if he/she thinks something should be fixed and @wbond will review it. Or he/she just tweaks his/her own color scheme to highlight something in his/her favor.
