### ISSUE TITLE
[c++] st4 build 4085 hangs while compiling

### ISSUE THREAD

**Issue by xMichel** [sublimehq/Packages#2474]
option "/cgthreads6" for cl.exe seems to cause st4 hanging; reproduced on another machine of same type (Win10, x64) with no extra packages installed (except package manager). The number of extra threads (6) in this option has no effect (1...n).

- Sublime Version: 4085
- OS Version: Windows x64 (19041.450)

## Expected behavior
identical to st3 (3211)

## Actual behavior
st4 hangs and its process must be killed by hand under task manager

## Steps to reproduce
using following entry in C++ Single File.sublime-build with any simple .cpp:

{
			"name": "Cl.exe (2019)",
			"cmd": ["C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe", 
				"/cgthreads6",
				"/I", "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.27.29110/include",
				"/I", "C:/Program Files (x86)/Windows Kits/10/Include/10.0.19041.0/ucrt",
				"${file}",
				"/link", 
				"/LIBPATH:C:/Program Files (x86)/Windows Kits/10/Lib/10.0.19041.0/ucrt/x64", 
				"/OUT:${file_path}/${file_base_name}.exe"],
			"working_dir": "${file_path}",
			"file_regex": "^(..[^:]*):([0-9]+):?([0-9]+)?:? (.*)$",
			"selector": "source.c, source.c++, source.cpp",
			"shell": true,
},

**Comment by wbond** [comment]
Is it possible your antivirus is doing something here? I've heard reports of similar issues before on new builds. Some antivirus systems see a new build of Sublime Text and having it do things like launch compilers, and considers is suspicious behavior.

How many cores does your CPU have? Does it support hyper threading? It sounds like it could be tying up the CPU and preventing ST from doing much, but that shouldn't require killing Sublime Text, just waiting for the code generation to end.

**Comment by xMichel** [comment]
> 
> 
> Is it possible your antivirus is doing something here? I've heard reports of similar issues before on new builds. Some antivirus systems see a new build of Sublime Text and having it do things like launch compilers, and considers is suspicious behavior.
> 
> How many cores does your CPU have? Does it support hyper threading? It sounds like it could be tying up the CPU and preventing ST from doing much, but that shouldn't require killing Sublime Text, just waiting for the code generation to end.

Will, thanks for that quick reply.
I am using Win Defender with all sort of security enabled, eg ransom protection which would usually complain at first start of a program (like with st3/4 when accessing protected folders, and I then grant access).
My cpu is a i7-8700k with 6+6 cores (physical, hyper threading). The other machine is i7-9700 with 8 phys cores with same restrictions. I copied the source folder to an unprotected area but the problem remains.
The code generation does not end as it seems. Even a minimal example like int main() {return 0;} hangs. I could offer a dmp file done with procdump -w "sublime_text.exe" -mp if this could be of any help.

**Comment by wbond** [comment]
I would try temporarily disabling your antivirus. I can't think of any changes that went into 4085 that should in any way be influenced by launching a subprocess, which is what a build system does.

**Comment by xMichel** [comment]
> 
> 
> I would try temporarily disabling your antivirus. I can't think of any changes that went into 4085 that should in any way be influenced by launching a subprocess, which is what a build system does.

no change; I'll try few things, and maybe I can spot the problem.

**Comment by xMichel** [comment]
> 
> 
> > I would try temporarily disabling your antivirus. I can't think of any changes that went into 4085 that should in any way be influenced by launching a subprocess, which is what a build system does.
> 
> no change; I'll try few things, and maybe I can spot the problem.

So, tried it now on a few different computers (2x Win10/Win 7, x64), and also with VS 2017. Including the option /cgthreads ST4 hangs, and removing it results in a successful compilation. 
With a debugger I can see still activity but the main window gets this typical whitish color when win messages won't be handled any more by the app when I click on it. With ST3 there's no such problem.

**Comment by rwols** [comment]
Did you manage to fix your issue, @xMichel?

**Comment by xMichel** [comment]
well...it seems that the issue vanished with one of the latest 
build...sorry I haven't tested for this behavior for some time now. It 
now compiles without any problem.

------ Original Message ------
