### ISSUE TITLE
[python] missed unpacking.sequence operator in function call

### ISSUE THREAD

**Issue by ric-evans** [sublimehq/Packages#2475]
- Sublime Version: 3.2.2
- OS Version: Ubuntu 20.04.1 LTS

The unpacking sequence operator is being interpreted as `keyword.operator.arithmetic.python` instead of `keyword.operator.unpacking.sequence.python`.

![rsz_2screenshot_from_2020-09-09_14-15-05](https://user-images.githubusercontent.com/19216225/92643527-8b5fe800-f2a7-11ea-960a-ce9205c482f5.png)

**Comment by michaelblyons** [comment]
He's right. Minimum repro just needs

```py
foo(*args)
```

I would never have noticed because Mariana uses the same color.
