### ISSUE TITLE
[Typescript] "extends" on the interface not supported

### ISSUE THREAD

**Issue by rchl** [sublimehq/Packages#2477]
The "extends XXX" part seems unsupported. By that, I mean that neither color changes within that part, nor scopes are any different on either `extends` or `XXX` part.

- Sublime Version:4085
- OS Version: OSX

```ts
interface Foo extends Bar {
  baz: string
}
```

![Screenshot 2020-09-10 at 19 23 34](https://user-images.githubusercontent.com/153197/92771384-22599c80-f39b-11ea-9de3-2613c70aa776.png)

**Comment by rchl** [comment]
Here is a class, for comparison:
![Screenshot 2020-09-10 at 19 24 36](https://user-images.githubusercontent.com/153197/92771544-44ebb580-f39b-11ea-9c00-3d9e7c16cd4f.png)

**Comment by Thom1729** [comment]
Thanks for the report. Should be fixed in #2491.
