### ISSUE TITLE
[Typescript] Argument decorators not supported

### ISSUE THREAD

**Issue by rchl** [sublimehq/Packages#2480]
- Sublime Version: 4086

```ts
class Controller {
    public async get(@Args() { id, credits }: GetArgs): Promise<Artist> {
        const url = `{id}`
        const b = callme();
    }
```

![Screenshot 2020-09-15 at 15 18 02](https://user-images.githubusercontent.com/153197/93215405-a67a9e00-f766-11ea-889a-7b69b3a649e4.png)

The `@Args` decorator seems to be what is breaking the syntax.

@Thom1729

**Comment by Thom1729** [comment]
Thanks for the report. Should be fixed in #2492.
