### ISSUE TITLE
Incorrect syntax highlighting for .bash_aliases

### ISSUE THREAD

**Issue by a1346054** [sublimehq/Packages#2482]
I was told to report this here.

https://github.com/sharkdp/bat/issues/1158

**Comment by michaelblyons** [comment]
Can you paste a screenshot? Mine does not look like your description.

``` bash
alias -- -='cd -'
alias mv='mv -v'
alias 'mv'='dfs'
```

<img width="143" alt="Screen Shot 2020-09-16 at 9 32 59 AM" src="https://user-images.githubusercontent.com/2701605/93344422-35e48780-f821-11ea-8b1d-d6d8bc70aeb6.png">

**Comment by a1346054** [comment]
![image](https://user-images.githubusercontent.com/36859588/93353964-09823880-f82c-11ea-842d-ab8962263295.png)

You can see it on your end as well, the `-=` should have `-` colored same as `mv' in `mv=`
