### ISSUE TITLE
Javascript 'Jump to symbol (R)' is broken

### ISSUE THREAD

**Issue by karolyi** [sublimehq/Packages#249]
Hi,

coming from https://forum.sublimetext.com/t/dev-build-3109/18581, I'd like to report that the javascript jump to symbol functionality is still broken.

more information here: https://forum.sublimetext.com/t/dev-build-3106/17982/25?u=karolyi

**Comment by wbond** [comment]
I can not replicate the issue.

Are you certain you are using the JavaScript syntax (not Babel or JS Next, etc)? Also, be sure you don't have an override in `Packages/JavaScript/JavaScript.sublime-syntax`. If so, remove it and you should fall back to the version shipped with 3109.

**Comment by karolyi** [comment]
I have no such file, as described in my config repo (linked earlier).

Let me have a look at this with a new sublime install, and see if I can reproduce.

Mind you, I'm on OSX, where things go a bit differently.

I'll report back with the results.

**Comment by wbond** [comment]
Yes, I am on OS X also. I used your file in testing the syntax, and just used it a few minutes ago to confirm the functions are present in the goto anything panel.

If there is a specific function you are not seeing, or there is a more subtle issue, please be specific with the line number.

I didn't see you specifically mention it, so double check you are using the "JavaScript" syntax. Anything else will function differently in tokenizing your file, resulting in the Goto Anything panel showing different results.

**Comment by karolyi** [comment]
Good news!

It seems that it's indeed not the default Javascript syntax that's broken, BUT: installing the babel extension corrupts the original javascript syntax. babel defines its own syntax which one can switch to (yes, I was using the _original_ syntax), but in the same time corrupts the original syntax highlight somehow, which is yet to be figured out how.

I'll create an issue report there, and link it to this one: maybe there's a need to communicate on this issue.
