### ISSUE TITLE
[TypeScript] generic highlighting

### ISSUE THREAD

**Issue by princemaple** [sublimehq/Packages#2515]
- Sublime Version: 4086
- OS Version: Win10

**Note:** I'm using the latest TS and JS from master branch of this repo, not what v4086 has.

*it is incorrect to pass `''` to this constructor - I just wasn't paying attention while writing the example. Please ignore it...*

``` typescript
class Example {
  x = new BehaviorSubject<Map<string, number>>('');
}
```

![image](https://user-images.githubusercontent.com/1329716/93736074-92c9ae80-fc22-11ea-9fce-170766939e3d.png)

![image](https://user-images.githubusercontent.com/1329716/93736081-965d3580-fc22-11ea-810d-f5ca1f865b9f.png)

While this highlighting looks OK-ish, the scope is wrong.
![image](https://user-images.githubusercontent.com/1329716/93736215-f18f2800-fc22-11ea-844b-d2280249b211.png)

This is correct
![image](https://user-images.githubusercontent.com/1329716/93736202-e9cf8380-fc22-11ea-87f9-b54a3e64c624.png)

**Comment by Thom1729** [comment]
Thanks for the report. Should be fixed in the linked issue.
