### ISSUE TITLE
[TypeScript] Function definition wrapped in parenthesis issue

### ISSUE THREAD

**Issue by rchl** [sublimehq/Packages#2526]
- Sublime Version: 4086

**Note**: This is reported in 4086 build, but with Javascript/Typescript syntax from this repo as of September 21 (fba16b223e206dc7f8cc20f95e581e20275e2258).

```ts
export type ExternalOption = ((source: string, importer: string | undefined, isResolved: boolean) => boolean);
```

![Screenshot 2020-09-21 at 20 45 36](https://user-images.githubusercontent.com/153197/93807787-68401b80-fc4b-11ea-9d9e-74ec98dcaee8.png)

**Note2**: This example is a slightly minimized example taken from https://github.com/rollup/rollup/blob/f6b14efa882c486d3814c06f02f2c78cfc8e5257/src/rollup/types.d.ts#L466-L474 . That file has also other highlighting issues below. Probably the same issues.

**Comment by Thom1729** [comment]
Looks like I never implemented parenthesized types, probably because the original implementation predated branching. The linked PR should fix it, and that definition file looks good now. Thanks for the report and for the example file.

**Comment by rchl** [comment]
Looking good with the fix. Thank you.
