### ISSUE TITLE
[PHP] Typed properties (Class object)

### ISSUE THREAD

**Issue by Juhlinus** [sublimehq/Packages#2537]
- Sublime Version: 3.2.2, Build 3211
- OS Version: macOS: 10.15.6

``` php
<?php

namespace App;

use Illuminate\Support\Collection;

class MyClass
{
    private Collection $my_collection;

    public function __construct(Collection $collection)
    {
        $this->my_collection = $collection;
    }
}
```

![Screen Shot 2020-09-24 at 10 34 54 AM](https://user-images.githubusercontent.com/12988164/94121449-a018b000-fe51-11ea-9d23-c518f5bd8cf9.png)

The class object properties color is different from for example namespace use statements, or as a parameter.

**Comment by jfcherng** [comment]
The latest syntax definition in this repo should've even supported PHP 8.0. However, it's not for ST 3.

![image](https://user-images.githubusercontent.com/6594915/94122852-a3c62a00-fe85-11ea-826a-ee7889273236.png)

**Comment by jfcherng** [comment]
It's up to a color scheme to color something, unless you are reporting that something is incorrectly scoped.

**Comment by Juhlinus** [comment]
> It's up to a color scheme to color something, unless you are reporting that something is incorrectly scoped.

Well, I just assumed that it's scoped incorrectly since it doesn't match up on any color scheme I've used.

**Comment by jfcherng** [comment]
Yeah, it's wrongly scoped given the fact that the built-in PHP syntax in ST 3 hasn't been updated for a long time and it won't receive any syntax update I believe. 

If you has to stick with ST 3, then I suggest use [my old PHP syntax](https://github.com/jfcherng-sublime/ST-my-settings/blob/2214ed365bdf5f3628f50a28299e5de668167c5e/Packages/PHP/PHP%20Source.sublime-syntax), which even partially supports PHP 8 syntax. That commit is the last commit which ST 3 supports. After that, I've used new syntax definition features from ST 4 and never go back.

**Comment by Juhlinus** [comment]
> Yeah, it's wrongly scoped given the fact that the built-in PHP syntax in ST 3 hasn't been updated for a long time and it won't receive any syntax update I believe.
> 
> If you has to stick with ST 3, then I suggest you use [my old PHP syntax definition](https://github.com/jfcherng-sublime/ST-my-settings/blob/2214ed365bdf5f3628f50a28299e5de668167c5e/Packages/PHP/PHP%20Source.sublime-syntax) (I call it old because I've used ST 4 new features since then and never go/port back) or [the latest ST 3 PHP syntax definition](https://raw.githubusercontent.com/sublimehq/Packages/st3/PHP/PHP%20Source.sublime-syntax). Both of them should fully supports PHP 7.4 syntax and partially supports PHP 8 syntax.

The latest ST3 one has different inconsistencies, so I went with yours. Looks great!
