### ISSUE TITLE
[Python] Opening Triple Quotes not colored

### ISSUE THREAD

**Issue by vmuriart** [sublimehq/Packages#255]
Just noticed that this bug was introduced with https://github.com/sublimehq/Packages/commit/8e8831f13ba46f1a30a99d1114b8148e6a481a82

```
""" The quotes to the left aren't colored""" 
''' neither are the ones that opened this string '''
```

**Comment by wbond** [comment]
This should be fixed by 76c4d5fcf31956c41d061b4daaef60c1ad4b67a3
