### ISSUE TITLE
Indentation regression for the Julia language in ST4?

### ISSUE THREAD

**Issue by PetrKryslUCSD** [sublimehq/Packages#2550]
- Sublime Version: 4088
- OS Version: Windows 10

## Expected behavior
Re-indent the code in this MW E: https://github.com/JuliaEditorSupport/Julia-sublime/issues/90#issuecomment-707996405

## Actual behavior
Only the definition of the function without the comment is indented correctly.
ST3 can indent both functions correctly.

## Steps to reproduce

Install the Julia package.
Create a Julia source file with
```
function f(x)
y = x^2 # comment
end

function f(x)
y = x^2 
end
```
Select all, and choose "Reindent".

**Comment by PetrKryslUCSD** [comment]
The same failure to re-indent also occurs in
```
function f(x)
y = x^2 # why
z = 2 * y 
end
```
In this case
```
function f(x)
y = x^2
z = 2 * y  # why
end
```
the result of the re-indent is
```
function f(x)
    y = x^2
z = 2 * y  # why
end
```
So `z = 2 * y  # why` is the line that fails to re-indent properly.

**Comment by deathaxe** [comment]
Julia is not part of this repo, thus this issue is invalid here.

**Comment by PetrKryslUCSD** [comment]
True. But I could not decide whether the failure was due to ST4 itself or to the specific language.

**Comment by wbond** [comment]
Closing, since we don't maintain Julia here
