### ISSUE TITLE
[GitHub Actions]  Content-Disposition header?

### ISSUE THREAD

**Issue by ratijas** [sublimehq/Packages#2552]
In the GitHub workflow ci.yml, there's an invocation of wget with an experimental (according to wget docs) `--content-disposition` option. It should instruct wget to "honor the Content-Disposition header when choosing local file names".

https://github.com/sublimehq/Packages/blob/7608ae7d6c33850d680a0e2a07d49f409b6c817f/.github/workflows/ci.yml#L19

Either I'm missing something, or the server's response doesn't even contain such header:

```http
HTTP/1.1 200 OK
Server: nginx
Date: Wed, 14 Oct 2020 13:58:52 GMT
Content-Type: application/octet-stream
Content-Length: 1118840
Last-Modified: Mon, 14 Sep 2020 06:18:34 GMT
Connection: keep-alive
ETag: "5f5f0b3a-111278"
Accept-Ranges: bytes

...rest is tar.gz binary content...
```

On the other hand, why using this option at all? Automation scripts are no place for random filenames dictated by the server. It would be much more robust approach to use deterministic file names, e.g. with `-O/--output-document` option:

```sh
wget -O st_syntax_tests.tar.xz https://url...
```

**Comment by ratijas** [comment]
Using `-O` option would also solve the problem of parsing output from `ls` two lines later:

https://github.com/sublimehq/Packages/blob/7608ae7d6c33850d680a0e2a07d49f409b6c817f/.github/workflows/ci.yml#L21

This approach is flawed, because in general `ls` [can not be trusted](https://mywiki.wooledge.org/BashPitfalls#for_f_in_.24.28ls_.2A.mp3.29) to do globbing for later argument expansion. Even if right now there is a reason to believe there would only ever be one matching file — such assumption might simply break in different environment (such as a future evolution of this ci flow).

**Comment by michaelblyons** [comment]
I'm not sure whether you're concerned about this repo or one you work on yourself. If it's one of yours, you may be interested in https://github.com/marketplace/actions/sublime-text-syntax-tests

**Comment by wbond** [comment]
I have no opinion - the GitHub action was just copied from the previous Travis config. PRs welcome!

**Comment by wbond** [comment]
That’s a community project - you are welcome to inquire there. I don’t know the reason off of the top of my head.

**Comment by ratijas** [comment]
I found out the reason why `--content-disposition` flag is used in SublimeText/syntax-test-action project. It's because there are several different links to various `*.tar.{bz2,gz,etc...}` archives, plus one for the `latest` endpoint which redirects to, well, actually to the latest archive — format of which is not known in advance.

I feel like it needs a better solution that globbing. Extension reported by the server should be preserved, so that tar knows which kind of archive it is, but guessing a filename via `st_*_*.tar.*` just doesn't feel right.

**Comment by ratijas** [comment]
> I have no opinion - the GitHub action was just copied from the previous Travis config. PRs welcome!

Hi @wbond :eyes: 

This PR is stalling.

**Comment by FichteFoll** [comment]
The origin of the `--content-disposition` parameter was, as you correctly found out, the usage of a `latest` endpoint for ST3 syntax test builds. Since ST4 is still in semi-private alpha, there is also no `latest` endpoint for ST4 yet and the syntax test build numbers need to be adjusted manually, if desired.

I decided to stick with globs in the action because they work.
