### ISSUE TITLE
[D] Ternary statement incorrectly marks as syntax error

### ISSUE THREAD

**Issue by TheGag96** [sublimehq/Packages#2558]
### Description

The changes to syntax definitions in ST4 have greatly improved parsing D code. However, ternary statements now mark as though they're a syntax error.

### Steps to reproduce

Type this code into a D source file:

```d
void func() {
  int a = b ? c : d;
}
```

Result:

![Image](https://i.imgur.com/02lp4QA.png)

### Environment

* Build: 4088
* Operating system and version: Elementary OS 5.1
* Linux Desktop Environment and/or Window Manager: Pantheon/Gala

**Comment by BenjaminSchaaf** [comment]
I've transferred the issue.
