### ISSUE TITLE
Inconsistencies with .sublime-settings' "extensions" and the syntax def's "file_extensions" lists

### ISSUE THREAD

**Issue by FichteFoll** [sublimehq/Packages#261]
The following packages have differences in this regard:

- C++
- Lisp
- XML

Imo they should all be in the syntax definitions.

---

Additionally, the XML package's settings file sports a setting named `hidden_extensions`. What does it do exactly?

**Comment by Briles** [comment]
The `hidden_extensions` setting seems to hide the extensions when opening a file of type or saving a file as type.

The `hidden_extensions` will not be listed with the XML syntax for the following commands:
- `File > Save As`
- `File > Open File`

These are the only effects I could find after limited testing; there may be more.

**Comment by wbond** [comment]
Removed `extensions` after speaking with Jon. At this point that setting should only be used by users to configure certain file types to open with a specific syntax.

**Comment by FichteFoll** [comment]
All right.

`.sublime-syntax` files don't support an equivalent to the `hidden_extensions` setting, do they?

I'm not sure where I would want to use it though. Maybe someone else can thing of an example.

**Comment by FichteFoll** [comment]
Created a separate issue for this at https://github.com/SublimeTextIssues/Core/issues/1326.

The most practical use case seems to be for a long list of extension support (for automatic highlighting) such as https://github.com/sublimehq/Packages/pull/581 without cluttering the file dialogs, as @Briles explained.
