### ISSUE TITLE
Another issue with Javascript 'Jump to symbol (R)'

### ISSUE THREAD

**Issue by goldfire** [sublimehq/Packages#262]
The last few dev builds have been giving me issues with jump to symbol. I thought it had mostly been worked out by 3109, but It still isn't working correctly in some instances. None of the prototype methods in the following file are working: https://github.com/goldfire/howler.js/blob/2.0/src/howler.core.js.

**Comment by wbond** [comment]
This should be resolved by fe8f4a6ee994ebd92d18350891f464acbdd980a0
