### ISSUE TITLE
[TypeScript] literal negative number as type

### ISSUE THREAD

**Issue by princemaple** [sublimehq/Packages#2632]
- Sublime Version: 4093
- OS Version: Windows 10, 19042

```typescript
class SignedNumberComponent {
  sign: 1 | -1 = 1;
          //^^ not highlighed
}

class SomeOtherClass {
  filterBySign(sign: 1 | -1) {
    // parameter type `-1` not highlighted, same as above
  }
}
//^invalid closing brace of class
```

![image](https://user-images.githubusercontent.com/1329716/99923036-f8076080-2d87-11eb-9aa8-7f5fe2a90660.png)

![image](https://user-images.githubusercontent.com/1329716/99923052-05244f80-2d88-11eb-8f60-3dd0ab525e20.png)

**Comment by princemaple** [comment]
cc @Thom1729

**Comment by Thom1729** [comment]
Thanks for pointing this out.

As far as I can tell, negative numeric literal types are totally undocumented. They're not described in the handbook, which only uses positive numbers. They're not in the release notes — actually, the release notes don't seem to mention numeric literal types at all. And they were introduced after Microsoft abandoned the spec. The only mention I can find of negative numeric literal types is in https://github.com/microsoft/TypeScript/pull/9407. As a result, I'm working almost entirely from [AST Explorer](https://astexplorer.net/).

**Comment by princemaple** [comment]
Indeed, I can't find any explicit documentation either.

I guess because how numbers work in dynamic languages, unlike in C where difference exists between signed and unsigned, when they said `number literals` they just implied both positive and negative are included 🤷‍♂️ https://www.typescriptlang.org/docs/handbook/literal-types.html#numeric-literal-types

Thanks for the effort and the great work, BTW!
