### ISSUE TITLE
[TypeScript] Arrow function syntax highlighting issue.

### ISSUE THREAD

**Issue by ivansvlv** [sublimehq/Packages#2634]
- Sublime Version: 4093
- OS Version: 11.0.1

This issue is related to:
https://github.com/sublimehq/Packages/issues/2573
https://github.com/sublimehq/Packages/issues/2468

New issue is created after being confirmed, as an appropriate approach, with @Thom1729 .

Recent (4092-4093) update to the TypeScript syntax fixed issues besides the one described here. Identifiers for an arrow function that has a return value type annotation, are not highlighted as function, but rather general variable.

>I'm guessing the remaining issue is that closeDialog isn't scoped entity.name.function.
That's a known bug, and the proper solution is probably to completely rewrite the way we mark variables &c as function names.
@Thom1729 _(copied from Discord)_

``` typescript
// with return type annotation `closeDialog` is highlighted as a general variable.
  const closeDialog = (): void => {
    setDialogOpen(false)
  }

// without return type annotation it is highlighted as a function name.
  const closeDialog = () => {
    setDialogOpen(false)
  }
```

Broken syntax:
![image](https://user-images.githubusercontent.com/16175855/99995014-800a5c00-2dc2-11eb-800a-5fac1ad81812.png)

Correct syntax:
![image](https://user-images.githubusercontent.com/16175855/99995114-9fa18480-2dc2-11eb-9730-d9d8001e0a4b.png)

**Comment by ivansvlv** [comment]
It looks like to be resolved in the build 4095. Please let me know if you want me to close the issue, or feel free to close it yourself. Thank you for the fix!

**Comment by FichteFoll** [comment]
I can confirm this is fixed in 4095.

**Comment by rchl** [comment]
Can close this now I think.

**Comment by ivansvlv** [comment]
Closed as it's been fixed. Thank you 🤘
