### ISSUE TITLE
[Haskell] Highlighting issues

### ISSUE THREAD

**Issue by SlavKing98** [sublimehq/Packages#2659]
```haskell
class Test val where
  ctor1 :: val a
  ctor2 :: a -> val a -> val a
  evalm :: val a -> b -> (a -> val a -> b) -> b

run :: (Test a) => (Int -> b) -> a b
-- run f n = run1 f n 0 where
--   run1 f n i
--     | i == n = Data1
--     | otherwise = Data2 (f i) (run1 f n (i + 1))

readx :: Int -> String
readx a = s a [] True where
  s :: Int -> String -> Bool -> String
  s a x y
    | False = []
    | True  = []
```

![](https://user-images.githubusercontent.com/73323009/102682736-2122e180-41cc-11eb-8c91-8cc4832e5b98.png)

* Lines 3-4: not colored as function type signature
* Line 7: not colored as comment
* Line 16: guard not colored
* Line 16: constructor False not colored

**Comment by deathaxe** [comment]
It looks like those issues have been fixed in this repo. The following screenshot is what it looks with ST 4094 which ships with revision from master branch.

![grafik](https://user-images.githubusercontent.com/16542113/102693636-55be8980-421c-11eb-8b06-9cd54691749f.png)

**Comment by SlavKing98** [comment]
@deathaxe I am using version 3211 and I literally downloaded packages from git master from this repo and it display wrong highlighting. Maybe the `Haskell.sublime-syntax` is using something that is available only in ST 4?

How and where did you download ST 4094? When I go to https://www.sublimetext.com/ and click `Download` it redirectes me to https://www.sublimetext.com/3, which is only for ST 3. Even when I click `Dev Builds`, it does not offer anything beyond ST 3. Where did you get ST 4?

**Comment by deathaxe** [comment]
With a short view into source, I'd say it should work with ST3 as well. In fact your code sample looks well in ST 3211 and the current Haskell from master on my machine. Did you place the downloaded syntax into _Data/Packages/Haskell_ to make sure the builtin syntax is overridden? (Note: I call "Data" the folder where packages are located. Maybe `%APPDATA%/sublime text 3` or `~/.config/sublime-text-3`)

Otherwise you can find ST 4 builts on [Discord](https://discord.gg/D43Pecu), if you want to help finding bugs. Yes, there are still some, but overall experience is far superior to ST3. Haven't used ST3 for month.

**Comment by SlavKing98** [comment]
@deathaxe Ok, the problem was that `Haskell.sublime-syntax` is not enough. I had to put all files from the Haskell folder from this repo into my Data folder. This issue is resolved, but I opened another one https://github.com/sublimehq/Packages/issues/2670 which is still observable with the git master Haskell syntax file.

Regarding ST 4, I don't have a discord account, but I found the link on the internet: https://download.sublimetext.com/sublime_text_build_4094_x64.zip. Is this the correct link? When I download it, ST asks me for license and I then enter my ST 3 license, but then nothing happens. ST just closes without any messages. And when I open again it asks me again for license. No matter what I paste, it always just close without saying anything. What may be the problem and where should I report it?

**Comment by michaelblyons** [comment]
If you have a valid license key, you shouldn't even need to paste it in. If you're using a leaked license, that might be what happens.

**Comment by SlavKing98** [comment]
@michaelblyons Sorry, I don't understand what you mean. I just downloaded ST 4 zip file from the link and unpacked it on my desktop and when I double click `sublime_text.exe` it asks me for license and no matter what I write when I click ok it just closes and nothing happens.

> you shouldn't even need to paste it in

What do you mean by this? The PC on which I downloaded ST 4 has no previous ST installations, and literally when I open ST 4 it dont open it just asks me for license and keeps closing when I press ok. Editor is not opened at all.

**Comment by michaelblyons** [comment]
> The PC on which I downloaded ST 4 has no previous ST installations

My mistake. I assumed you were putting it on a computer with a licensed ST3.

**Comment by deathaxe** [comment]
> ...  it asks me for license and no matter what I write when I click ok it just closes and nothing happens.

It just means your license key is not accepted. Maybe it leaked out to the web an therefore was black listed. You may want to contact sales@sublimehq.com to solve that.

**Comment by SlavKing98** [comment]
> It just means your license key is not accepted. Maybe it leaked out to the web an therefore was black listed. You may want to contact sales@sublimehq.com to solve that.

I spent two days trying to run ST 4 and failed. And still got no response from that email. So I had to patch ST 4 using Cheat Engine to simply remove the license check. I know it is a bad practice, but I just lack time...

![](https://user-images.githubusercontent.com/73323009/103043807-7ec57e00-457e-11eb-8365-e6df69eee2fc.png)
