### ISSUE TITLE
[JavaScript] object literal issue with greedy matching

### ISSUE THREAD

**Issue by jcberquist** [sublimehq/Packages#267]
Given this syntax:
```javascript
var obj = {
	key: 'str' + (true ? 'true' : 'false')
}
```
Because [Line 920](https://github.com/sublimehq/Packages/blob/master/JavaScript/JavaScript.sublime-syntax#L920) has the lookahead containing `'.*'` (checking to see if it is followed by a `:`), in an example like the above that will match from `'str'` to `'true' :` and the context pops off. This obviously messes with the syntax in numerous ways as the scopes of everything following `key:` are problematic.

**Comment by wbond** [comment]
This should be fixed by 5e06ebb36dc2cd04fd3d2a5e67f693dfe77219d7
