### ISSUE TITLE
[C++] Several Issues

### ISSUE THREAD

**Issue by jbw3** [sublimehq/Packages#268]
I've tried out the new C++ syntax on the c-rewrite branch. First of all, nice job! There have definately been a lot of improvements. I still noticed a few things, though, that need to be fixed:

- [x] Comments in namespace declarations are not highlighted

```c++
namespace abc /* Neither this comment... */
// ...nor this comment is highlighted
{
}
```

- [x] The override and final keywords are not highlighted with C++11 trailing return types

This is highlighted correctly...
```c++
class Test
{
    int f() override final;
};
```

...but _not_ this
```c++
class Test
{
    auto f() -> int override final;
};
```

**Comment by wbond** [comment]
Comments in namespace fixed by 91072a18b87eee927201f73d8f77a36cd7ac3164.

Trailing return type support added in 4f4421a2431391d5449f32811b5641b3752e7ce1.
