### ISSUE TITLE
[TypeScript] extending multiple interfaces not highlighted correctly

### ISSUE THREAD

**Issue by rchl** [sublimehq/Packages#2714]
- Sublime Version: 4097
- OS Version: OSX

```ts
interface Sprite extends Jumpable, Duckable {}
```

![Screenshot 2021-02-09 at 17 19 40](https://user-images.githubusercontent.com/153197/107393357-ffbee180-6afa-11eb-8486-2ac600041eee.png)

Example from: https://www.typescriptlang.org/docs/handbook/mixins.html

**Comment by FichteFoll** [comment]
I suppose this can be closed.

**Comment by rchl** [comment]
Fixed by #2715
