### ISSUE TITLE
[macOS] ST crashing when changing layout

### ISSUE THREAD

**Issue by orangecoloured** [sublimehq/Packages#2721]
When I change the layout columns/rows from a higher number to lower the app crashes.
If I start from 2 cols and go to 4, it's fine. If I have 2 cols and go to single or 4 -> 2, it crashes.

ST build 4098
macOS 11.2.1

**Comment by Ultra-Instinct-05** [comment]
This is the `Packages` repo. For Sublime Text related issues that are not related to the Default Packages, please use the official issue tracker https://github.com/sublimehq/sublime_text/issues

**Comment by rwols** [comment]
Note that repository owners can “transfer issues” (bottom-right link somewhere)
