### ISSUE TITLE
[Javascript] Arrow function arguments split across lines get wrong scope

### ISSUE THREAD

**Issue by dsl101** [sublimehq/Packages#2724]
- Sublime Version: 3.2.2. Build 3211
- OS Version: Windows 10 64-bit

``` javascript
const oneLine = (p1, p2 = false) => {
  // etc
}

const oneLineDestructured = ({ p1, p2 = false }) => {
  // etc
}

const multiLine = (
  p1,
  p2 = false
) => {
  // etc
}

const multiLineDestructured = ({
  p1,
  p2 = false
}) => {
  // etc
}

```

![image](https://user-images.githubusercontent.com/900542/108505978-0cd49100-72b0-11eb-8604-d4ceb4765466.png)

Scope Hunter reports the function `multiLine` as `source.js meta.binding.name.js variable.other.readwrite.js` whereas `oneLine` is (correctly) `source.js meta.function.declaration.js entity.name.function.js variable.other.readwrite.js`. There are similar differences for all the other incorrectly highlighted elements. Let me know if it's useful to list them all.

**Comment by dsl101** [comment]
Also I found this similar issue in a different repo. I guess it's the same underlying problem (regex engine)? https://github.com/babel/babel-sublime/issues/340

**Comment by rchl** [comment]
This is how it looks in ST4 build 4098:

![Screenshot 2021-02-19 at 14 57 40](https://user-images.githubusercontent.com/153197/108513381-d0f6f700-72c2-11eb-875a-3d253bb7ae8e.png)

Looks like the arguments look good now.
The variables don't `get entity.name.function` assigned though.

**Comment by Thom1729** [comment]
Yep, the current version of the JavaScript syntax fixes multiline arrow function. It relies on a new feature from ST4, so the fix cannot be backported to ST3.

The syntax still uses regexp lookaheads to scope function names in e.g. `const f = () => {}`, so in that example `f` won't get `entity.name.function`. I'd like to fix that, but I haven't worked out the best way to do it without blowing up the syntax definition size. See #2267.

**Comment by dsl101** [comment]
Fantastic—I will give ST4 a go. Many thanks.
