### ISSUE TITLE
[LaTex] Snippets insert double backslash

### ISSUE THREAD

**Issue by LDAP** [sublimehq/Packages#2730]
- Sublime Version: 4098
- OS Version: Windows 10

## Expected behavior
Only one backslash is inserted

## Actual behavior
When typing `\begin`, pressing Tab
```latex
\\begin{env}
        
\end{env}
```
is inserted.
Same for item, equation, and any other environment
## Steps to reproduce

1. Start ST in safe mode
2.  See actual behavior

**Comment by LDAP** [comment]
Actually, I noticed that the triggers are set to `begin` instead if `\begin` because of that I get double backslashes. Is there something like context aware replacement which could be used to prevent this?

**Comment by michaelblyons** [comment]
There are weird complications with completions starting with non-word characters. I think snippets may be immune. If so, it's conceivable that you could add a `\` to the `<tabTrigger>` here and also add a `*.sublime-completions` file with the bare `begin` snippet so other people's muscle memory isn't sacrificed for yours.

HTML has some Python to do tag completions triggered by `<`. That's also a possibility, but someone else can't turn them off without overriding the package.

**Comment by LDAP** [comment]
I am not that familiar with sublime-completions. `trigger` would be the command with `\` and `contents` the snippet?
