### ISSUE TITLE
[TypeScript] Template Literals within Object Literals

### ISSUE THREAD

**Issue by alihsaas** [sublimehq/Packages#2740]
- Sublime Version: 4098
- OS Version: Windows 10 Build 19042

``` ts
type SomeObjectLiteral = {
	[K in keyof Instances]: `${}`
}
```

![image](https://user-images.githubusercontent.com/40891677/110254875-b77bcd80-7f99-11eb-9326-949282ec6693.png)

**Comment by Thom1729** [comment]
Apparently TypeScript 4.1 added [template literal types](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-1.html#template-literal-types).

I'll see if I can put an implementation together this evening. Unfortunately, there's no language spec and AST Explorer doesn't support 4.1 yet, so it might be a bit rough.
