### ISSUE TITLE
[Python] Keywords immediately after numbers

### ISSUE THREAD

**Issue by FichteFoll** [sublimehq/Packages#2763]
To my great surprise, the following is legal in Python, but the current syntax definition does not allow for it.

```py
5in range(10)
5if 0else 6
```

Low priority, since I've *never* seen code like this, but an issue nonetheless.

**Comment by deathaxe** [comment]
Same as https://github.com/sublimehq/Packages/pull/2308, when someone argued for breaks, hehe.

**Comment by FichteFoll** [comment]
Interestingly, this has actually been deprecated in Python 3.10 (shortly after the creation of this issue), but since it's been valid syntax in the past, we'll have to highlight it for the forseeable future anyway. Just wanted to document this here since I randomly stumbled upon it today.

https://github.com/python/cpython/issues/87999
