### ISSUE TITLE
[D] No syntax coloring for pointers / arrays

### ISSUE THREAD

**Issue by RUSshy** [sublimehq/Packages#2764]
- Sublime Version: 3.2.2 Build 3211
- OS Version: Windows 10 x64

``` lang
D
```

Types for pointers / arrays aren't colored, see screenshot bellow:

![image](https://user-images.githubusercontent.com/18348637/113227675-868a7200-9293-11eb-9e82-6dcb93ef876b.png)

``Engine`` is a struct
``GameState`` is an enum

**Comment by deathaxe** [comment]
The following syntax tests pretend this to be desired behavior. 

https://github.com/sublimehq/Packages/blob/5d23044ce2ec37f3d6ad3b015070e728b5a5ef58/D/tests/syntax_test_d.d#L570-L583

They explicitly scope tokens in front of asterisk and brackets `variable.other`.

**Comment by RUSshy** [comment]
Wow that was fast, thanks a lot @deathaxe
