### ISSUE TITLE
[JSX] Scope native element and component names differently

### ISSUE THREAD

**Issue by Thom1729** [sublimehq/Packages#2770]
From https://github.com/babel/babel-sublime/issues/307.

The JSX syntax currently scopes both native element names and component names the same way — `entity.name.tag`. It would make a lot of sense to scope them differently so that they could be distinguished at a glance. Both Atom and VSCode do this, and I think it looks good.

For our purposes, a “native tag” is any tag whose name is a single token not beginning with a capital letter, and a “component” is anything else. This is a purely syntactic distinction; we don't care whether `<arglebarf>` is actually a native HTML element or somesuch.

How should we scope this? I think the best answer is probably to leave native elements as they are and add an extra scope to component names. The trick is that we'd want one that's colored in most schemes. `support.class` would work, but I feel that it's not really correct. Thoughts?

**Comment by deathaxe** [comment]
I'd use a scope which looks different from normal code tokens by default (in most legacy color schemes).

CSS uses `entity.name.tag.html` vs. `entity.name.tag.svg` for the same type of tag distinction and so could JSX probably do, too. Maybe something like `entity.name.tag.[component|react|other|..?]` ?

CSS also provides the most up to date list of valid html tag names categorized by the same scheme MDN uses - if accuracy of matching valid html tags matters.

HTML distinguishes `entity.name.tag.[block|inline|other]`. Components are foreign tags from HTML perspective, even though this may not be a perfect comparison - would mean `entity.name.tag.other`. But I guess the CSS way would be just enough.

**Comment by Thom1729** [comment]
`entity.name.tag.*` makes sense, but it wouldn't be visible for most users.

**Comment by deathaxe** [comment]
But we shouln't fall back to choose scope names by desired colors in certain color schemes.

Luckily choosen or not, all kinds of tags in most/all syntaxes use `entity.name.tag`. The proposed tags may not be distinguishable out of the box, but it shouldn't be a big deal once each type uses different scope names.

Not sure if XML/HTML like tags should receive a totally different scope/color than in other syntaxes.

I guess you proposed `support.class` because it is stacked onto `entity.name.tag` in VS Code?

How would we want to distinguish different types of tags in general (all syntaxes)? I asked that myself, when working on some XSL stylesheets. All tags XSL or XML,HTML,... look pretty much the same way, which makes it hard to distinghish template content from xsl rules.

**Comment by Thom1729** [comment]
> But we shouln't fall back to choose scope names by desired colors in certain color schemes.

> Luckily choosen or not, all kinds of tags in most/all syntaxes use entity.name.tag. The proposed tags may not be distinguishable out of the box, but it shouldn't be a big deal once each type uses different scope names.

I'm inclined to agree — but if there's a solution that both makes logical sense and works with existing color schemes, then that would be even better.

> I guess you proposed support.class because it is stacked onto entity.name.tag in VS Code?

Yep. It used to be more common even in core syntaxes to use `support.class` for references to classes, regardless of whether `support` is appropriate. We've mostly stopped doing that, which is good and correct, but at times like this it does seem inconvenient.

> How would we want to distinguish different types of tags in general (all syntaxes)? I asked that myself, when working on some XSL stylesheets. All tags XSL or XML,HTML,... look pretty much the same way, which makes it hard to distinghish template content from xsl rules.

I think this might not generalize well between JSX and HTML/XML. For JSX, the distinction is mostly lowercase-native versus uppercase-component. For general XML, it might make sense to have a special scope for namespaced tags, which (when tastefully colored) would probably help the XSL use case. (JSX actually supports namespacing via colons, but *React* doesn't, so it's basically unused.) For HTML, we care about the block/inline distinction, maybe with another case for SVG.

On the other hand, the scope pattern `entity.name.tag.*` would seem to work for any of them.

**Comment by frou** [comment]
Seems like the specific motivation for this issue got resolved by PR #3000
