### ISSUE TITLE
[CSS] Don't work auto-fill grid in Sublime Text 3

### ISSUE THREAD

**Issue by shchemer** [sublimehq/Packages#2771]
Hello. I am making a website where I need to arrange blocks of 4 in an unlimited number of lines. And I need the blocks to be transferred if there is no space, but the auto-fill does not work. Why?

- Sublime Version: Version 3.2.2 Build 3211
- OS Version: Windows 10 Home
![Screenshot_1](https://user-images.githubusercontent.com/82022582/114016243-4f0f5d00-9873-11eb-87c6-c799918345e0.png)

**Comment by deathaxe** [comment]
`auto-fill` is scoped correclty as `support.keyword` and your screenshot looks well.

If you expect `auto-fill` to be suggested by auto-completion, it may be worth mensioning, the default completions plugin provided by this repository doesn't provide completions for function arguments.

Even though technically possible it is a quite huge effort to keep up to date with the on-going development of the CSS pseudo-standard. PR #2737 intents to update all of it, but parsing sources and maintaining backward compatibility with older CSS versions and keys which are no longer part of the documentation is a barely automatable job and needs much manual and time expensive work.
