### ISSUE TITLE
[C++] Highlight of function call with template

### ISSUE THREAD

**Issue by TheClams** [sublimehq/Packages#278]
When a function uses template parameters, it is not correctly highlighted:

Here is an example where the second Print is not correctly highlighted (Github has the same issue btw :P)
```c++
void Foo() {
	Print("Hello");
	Print<int>(3);
}
```

**Comment by jfcherng** [comment]
Actually, `A<3>(4)` can be view as `(A < 3) > (4)` as well without knowing what `A` is. Of course, no one wants to do `(A < 3) > (4)` lol... but it's legal.

**Comment by wbond** [comment]
@jfcherng Yes, unfortunately there are some (well, more than most other languages) corner cases with C-family languages that we just won't ever be able to handle. This is especially true with the preprocessor, which messes with everything.

In general we just try to target reasonable, real-world codebases. I did a bit of testing with the SQLite and Python codebases when making the revisions to C. For C++ I was using the Sublime Text and Boost codebases, along with bug reports.

I'll get this fixed up later today. With all of the work that has gone into these syntaxes recently, we really have come a long way in terms of correctness and breadth of coverage from the `.tmLanguage` files of old. My goal is to continue to work on all of these default syntaxes to make them as correct and fast as possible. That way *Goto Definition* works in as many cases as possible, and the indexer can scan projects nice and fast.

**Comment by wbond** [comment]
This should be fixed by 4c1212aa5c251cdacb727df27532a3fe7a022f0a
