### ISSUE TITLE
[TypeScript] `readonly` as object key highlights as keyword and breaks line after it

### ISSUE THREAD

**Issue by princemaple** [sublimehq/Packages#2790]
- Sublime Version: 4102
- OS Version: win10

```typescript
const myObject = {
  normalKey: 'something',
  readonly: true
};
```

![image](https://user-images.githubusercontent.com/1329716/114856592-a2148180-9e2a-11eb-88fd-807662291016.png)

**Comment by Thom1729** [comment]
Thanks for the report. The code around modifiers in general needed some cleaning; the linked PR should fix this issue.

**Comment by princemaple** [comment]
Thanks for another quick response!

**Comment by deathaxe** [comment]
Guess this one can be closed.
