### ISSUE TITLE
[Python] Relax decorator matching

### ISSUE THREAD

**Issue by FichteFoll** [sublimehq/Packages#2796]
With Python 3.9, syntax restrictions on decorators have been lifted, allowing most notably item access and other generic expressions, including assignment expressions.

See [PEP 614](https://www.python.org/dev/peps/pep-0614/) for details. Specifically, the following is now legal:

``` py
@buttons[0].clicked.connect
def spam():
    ...

def _(x): return x

@(y := _)
def test(x):
    print(x)

@z := _
def test(x):
    print(x)

```

**Comment by deathaxe** [comment]
Why must all syntaxes evolve to mess. Is that entropy of development?

**Comment by FichteFoll** [comment]
Python, in general, gives you a lot of tools to play around with. All the tools have a written noticed attached to it: "Use responsibly". It just so happens that most people follow this advice. :wink:
