### ISSUE TITLE
[Typescript] problem when variadic types are involved with decorators receiving parameters

### ISSUE THREAD

**Issue by jgburet** [sublimehq/Packages#2799]
- Sublime Version: 4102
- OS Version: MacOS Big Sur 11.2.3 (20D91)

<img width="389" alt="Screenshot 2021-04-28 at 15 08 07" src="https://user-images.githubusercontent.com/1304987/116409693-628b6380-a834-11eb-9d68-b689a6268515.png">

OK
<img width="752" alt="Screenshot 2021-04-28 at 15 04 04" src="https://user-images.githubusercontent.com/1304987/116409738-6d45f880-a834-11eb-8f84-8a94536a6b28.png">
<img width="550" alt="Screenshot 2021-04-28 at 15 13 58" src="https://user-images.githubusercontent.com/1304987/116409775-759e3380-a834-11eb-873b-7e8c7a9ec759.png">

KO
<img width="752" alt="Screenshot 2021-04-28 at 15 04 14" src="https://user-images.githubusercontent.com/1304987/116409829-8353b900-a834-11eb-9ea9-157a82becbfa.png">

```typescript
import * as GQL from 'type-graphql';

@GQL.Resolver()
export class MyResolver {
    @GQL.Mutation(() => String)
    @GQL.Authorized<any>({})
    async someCommand(): Promise<String> {
        return "hell" // "o"
    }
}
```

**Comment by Thom1729** [comment]
Thanks for the report (and especially for the working example).

The problem was that there's special handling for decorator expressions, and it didn't include the code that regular TypeScript expressions use to detect function type arguments. The linked PR should fix it.
