### ISSUE TITLE
[Python] Strange highlighting with capitalized word "WITH" at beginning of string

### ISSUE THREAD

**Issue by supergra** [sublimehq/Packages#2812]
- Sublime Version: 4105
- OS Version: MacOS 11.2.3

``` 'python'
"with SOMETHING"
"With SOMETHING"
"WITH SOMETHING"
'WITH SOMETHING'
f'WITH SOMETHING'
"SOMETHING WITH"
"    WITH"
"A WITH"
```
<img width="277" alt="Screen Shot 2021-05-10 at 13 00 10" src="https://user-images.githubusercontent.com/2165840/117717566-d2ccaa00-b18f-11eb-8d89-f6444ac9789f.png">

**Comment by rwols** [comment]
I believe the syntax is written in such a way that it tries to highlight SQL constructs when it detects an SQL keyword. In this case “WITH” is such a keyword.

**Comment by deathaxe** [comment]
wontfix, can be closed.

**Comment by FichteFoll** [comment]
You may disable any special highlighting with an upper-case raw string, i.e. `R"WITH"`. I don't know whether this convention is universally followed, but iirc it was present in the initial `Python.tmLanguage` and should thus be present in all editors that based on it.

**Comment by deathaxe** [comment]
The only solution was to apply some kind of heuristics as PHP does.

see: #2962

**Comment by deathaxe** [comment]
PHP and Python now use the same heuristic to detect beginning of SQL query strings. That's the way the syntax is designed. False positives can't be avoided except using uppercase `F"..."`, `R"..."`, `U"..."` strings which explicitly disable embedded syntax highlighting.
