### ISSUE TITLE
Unwanted new autocomplete behavior in ST4

### ISSUE THREAD

**Issue by user93702699** [sublimehq/Packages#2813]
- Sublime Version: 4081
- OS Version: Ubuntu 20.04 LTS

In ST3 when I enter `.` after an identifier, it does not display the autocomplete suggestions, but in ST4 it does. It breaks my macros that relied on the old behavior. Is there a way to fix this?

After extensive search, I found https://github.com/sublimehq/sublime_text/issues/3716, which seems like a useful use case. Is there a workaround? Can I suppress autocomplete when a macro is about to be executed, but keep it otherwise? Or at least do not trigger autocomplete after the `.` character, instead only  trigger it immediately after an identifier?

![abc](https://user-images.githubusercontent.com/81395232/117768197-5343e700-b232-11eb-8ce9-5d0f8b56a166.png)

**Comment by deathaxe** [comment]
Situations when auto completions trigger automatically is controlled by the following settings the same way it is for ST3.

That's the only way to control when completions trigger while typing, if not by calling `auto_complete` from a plugin, I am aware of.

```
	// Controls what scopes auto complete will be triggered in
	"auto_complete_selector": "meta.tag, source - comment - string.quoted.double.block - string.quoted.single.block - string.unquoted.heredoc",

	// Additional situations to trigger auto complete
	"auto_complete_triggers":
	[
		{"selector": "text.html, text.xml", "characters": "<"},
		{"selector": "punctuation.accessor", "rhs_empty": true},
	],
```

It triggers as the `.` is scoped `punctuation.accessor` which is a quite common situation one might expect completions.

You have `.` bound to a `"run_macro"` command?

**Comment by keith-hall** [comment]
You could try setting `auto_complete_when_likely` to false in your user preferences, see if it makes a difference

**Comment by rwols** [comment]
I'm fairly certain it's due to `punctuation.accessor`. Run **Preferences: Settings - Syntax Specific** while viewing a C++ file from the command palette and in the right-most view, put

```js
{
    "auto_complete_triggers": []
}
```

this'll disable `punctuation.accessor` only for the C++ syntax. Note that plugins may alter this json array anyhow.

**Comment by user93702699** [comment]
Added the following settings:

```json
"auto_complete_triggers": [],
"auto_complete_cycle": true,
"auto_complete_use_index": true,
"auto_complete_trailing_symbols": false,
"auto_complete_trailing_spaces": false,
"auto_complete_include_snippets": false,
"auto_complete_include_snippets_when_typing": false,
"auto_complete_when_likely": false,
```

It no longer displays autosuggestions after `.` but it still displays after `()`, for example like this:

![](https://user-images.githubusercontent.com/81395232/118249095-5266bb80-b4a5-11eb-9da6-1c73a3afa50c.png)

How to disable this?

Also, one more question: I see that ST4 no longer sorts the autosuggestions based on my previous choices. For example, if I have identifiers `abc` and `abd` and I type `ab`, then ST3 displays `abc` and `abd` in that order. When I choose `abd` few times, it then pulls `abd` to the top and the next time I type `ab`, the order will be `abd`, `abc`. However, ST4 does not respect that order, it always displays the same order. I noticed there is `auto_complete_preserve_order` option in ST4, which is set to `some` by default, but it doesn't exist in ST3. What value should I set to that option so that it matches the behavior from ST3? Thanks.

**Comment by keith-hall** [comment]
> Also, one more question: I see that ST4 no longer sorts the autosuggestions based on my previous choices. For example, if I have identifiers `abc` and `abd` and I type `ab`, then ST3 displays `abc` and `abd` in that order. When I choose `abd` few times, it then pulls `abd` to the top and the next time I type `ab`, the order will be `abd`, `abc`. However, ST4 does not respect that order, it always displays the same order. I noticed there is `auto_complete_preserve_order` option in ST4, which is set to `some` by default, but it doesn't exist in ST3. What value should I set to that option so that it matches the behavior from ST3?

`none` is the ST3 behavior :)

**Comment by user93702699** [comment]
@keith-hall 

> that's quite old, have you considered trying the most recent version?

I updated to 4107, it works fine now. But it displays this in title: LICENSE UPGRADE REQUIRED

I cannot upgrade currently. Can you please tell me what functionalities are disabled for non-upgraded licenses? Should I expect "evaluation expired" message in the near future? Will I get random nags telling me to upgrade? Or is the software going to work perfectly normal, except having this reminder in the title? Please tell me so I know what to expect

**Comment by user93702699** [comment]
@keith-hall please answer the question above ^

**Comment by keith-hall** [comment]
> Or is the software going to work perfectly normal, except having this reminder in the title?

Pretty sure it's this - SublimeHQ aren't likely to want to treat (previously) paying customers worse than people whom have never bought a licence
