### ISSUE TITLE
[Lua] Putting default sublime-syntax file into user packages fails: regex error.

### ISSUE THREAD

**Issue by zainthemaynnn** [sublimehq/Packages#2818]
- Sublime Version: Build 3211
- OS Version: Windows 10

## Expected behavior
adding a default sublime-syntax file, from my understanding, should highlight exactly the same way when put into the `Packages/User` directory. in particular, I am trying to use `Lua.sublime-syntax` (and make a few modifications thereafter).

## Actual behavior
my editor throws the error attached:  
`Error loading syntax file "Packages/User/Lua.sublime-syntax": Error in regex: invalid backref number/name in regex \]\1\]`  
![sublime-regex-error](https://user-images.githubusercontent.com/69121865/118308172-a54a6e00-b4b9-11eb-9673-a478ab94ef39.png)  
indeed, it works when I remove the backreferences (they occur twice throughout the file), however strings no longer format properly. see here.
![sublime-regex-error-2](https://user-images.githubusercontent.com/69121865/118309315-176f8280-b4bb-11eb-95e3-22e9521ee986.png)

## Steps to reproduce
1. [retrieve the sublime-syntax file at this link](https://raw.githubusercontent.com/sublimehq/Packages/master/Lua/Lua.sublime-syntax)
2. move this into a sublime-syntax file at `Packages/User`
3. try to render a lua file

thanks.

**Comment by rchl** [comment]
For ST3-compatible code you should check the [st3 branch](https://github.com/sublimehq/Packages/tree/st3).
`master` branch is for ST4.

**Comment by zainthemaynnn** [comment]
oh shoot. I apologize, it looks like I was using the st4 syntax file then. the other branch's version works. thank you :)
