### ISSUE TITLE
[Regular Expression] x{num} is not highlighted

### ISSUE THREAD

**Issue by jfcherng** [sublimehq/Packages#282]
![image](https://cloud.githubusercontent.com/assets/6594915/14519839/e5970acc-0253-11e6-8b2e-043713023098.png)
![image](https://cloud.githubusercontent.com/assets/6594915/14519954/78cb1a86-0254-11e6-9861-fff9c4009938.png)
`{2}` should be highlighted.

**Comment by keith-hall** [comment]
https://github.com/sublimehq/Packages/pull/281
