### ISSUE TITLE
[XML] false positives on tag names

### ISSUE THREAD

**Issue by keith-hall** [sublimehq/Packages#283]
ST build 3111

[According to the XML specification, an XML tag name cannot start with a digit or a dash.](https://www.w3.org/TR/REC-xml/#NT-Name)

ST3 currently highlights these as though they are legal (and apparently GitHub does too!):

```xml
<1test>

</1test>
```

![xml tag name starts with digit in st3](https://cloud.githubusercontent.com/assets/11882719/14524034/24bfcabe-023f-11e6-9fb1-59eea1c4856d.png)

but if you try to parse such xml, it will fail.

Ideally, Sublime would set an `invalid.illegal` scope for the tag name or at least the digit at the beginning.

**Comment by wbond** [comment]
This should be solved by fe943080e895bfbeedd5f6277dbacef33474b7ab and 927d494d9ca2995eabf9cc3d84b0895c7aa60e2d
