### ISSUE TITLE
[C#] Method expression-bodies members

### ISSUE THREAD

**Issue by beautifulcoder** [sublimehq/Packages#2832]
- Sublime Version: 3.2.2, Build 3211
- OS Version: Windows 10 19042.985

Hi, I am seeing this issue in C# where method expressions show a syntax error on deeply-nested code.

``` csharp
[Fact]
public void ApplyValidationFail() =>
  Assert.Equal(
    "[[fail_1], [fail_2]]",
    (
      Success<Seq<string>, Option<int>>(3),
      Fail<Seq<string>, Option<int>>(Seq1("fail_1")),
      Success<Seq<string>, Option<int>>(3), Fail<Seq<string>,
      Option<int>>(Seq1("fail_2"))
    )
    .Apply((a, b, c, d) =>
      from w in a
      from x in b
      from y in c
      from z in d
      select w + x + y + z)
    .FailToSeq()
    .ToString()
  ); // <-- Syntax error
```

Seems to work fine on simple expressions.

```chsarp
[Fact]
public void BindProp() =>
  Assert.Equal(
    None,
    Optional(1)
      .Bind<int>(o => o + 2)
      .Bind<int>(_ => None)
      .Bind<int>(_ => 1)
  ); // <-- No syntax error
```

Attached are screenshots of how this shows in Sublime.

![image](https://user-images.githubusercontent.com/5228509/119372899-76808480-bc7d-11eb-9653-7594ffb003dd.png)
![image](https://user-images.githubusercontent.com/5228509/119373015-957f1680-bc7d-11eb-9f0a-8fd5b43edead.png)

**Comment by jfcherng** [comment]
not sure whether this is related: https://github.com/sublimehq/Packages/issues/2471

**Comment by keith-hall** [comment]
> not sure whether this is related: #2471

unlikely, because that issue relates to C, not C#.

In this example, the newline after the `(` for the tuple (i.e. before the `Success<Seq<string>, Option<int>>(3),` line) seems to be the issue. With that removed, it works. So maybe we need to use branching to detect tuples instead of relying on same-line heuristics.

**Comment by keith-hall** [comment]
I have a fix at https://github.com/sublimehq/Packages/pull/2838, but in order for me to add tests to ensure it isn't regressed in future, it'd be great to have a more complete example which I can look at, to understand what C# is doing in this situation. Like, definitions for `Success`,  `Seq`, `Option`, `Fail` and `Seq1` would be super helpful if possible, please :)

**Comment by beautifulcoder** [comment]
Hey @keith-hall Thanks! I have the original code out on GitHub:

https://github.com/beautifulcoder/func-csharp-api/blob/master/Bank.Tests/Basics.cs#L56

The static methods are from the LanguageExt library via a static using statement.
