### ISSUE TITLE
[Markdown] The `meta.link.reference.def.markdown` Selector Doesn't Catch All Markdown Reference Links

### ISSUE THREAD

**Issue by RoyiAvital** [sublimehq/Packages#2835]
### Description

The `meta.link.reference.def.markdown` selector doesn't Catch all Markdown reference links.
Namely `ref_links = self.view.find_by_selector("meta.link.reference.def.markdown")` won't hold all cases in Markdwon.

### Steps to reproduce

1. Start Sublime Text (Build `4107`).
2. Create a new Markdown document (Open an empty `.md` file).
3. Copy the following text:

```
Some list...

 *  Examining Deep Learning (DL) Based Methods  
  Always some text on Deep Learning.
 *  Hyper Parameters  
  Adding an exhaustive search of the optimal Hyper Parameters.


  [001]: https://en.wikipedia.org/wiki/Root-mean-square_deviation "Wikipedia - RMSE"
  [002]: https://en.wikipedia.org/wiki/Mean_absolute_error        "Wikipedia - MAE"
```

### Expected behavior

If the caret is before `[001]: https://en.wikipedia.org/wiki/Root-mean-square_deviation "Wikipedia - RMSE"` or `[002]: https://en.wikipedia.org/wiki/Mean_absolute_error        "Wikipedia - MAE"` the scope is expected to be a Markdown reference link.

### Actual behavior

The scope is a list:

![image](https://user-images.githubusercontent.com/7347975/119832860-3fbd9f00-bf07-11eb-9f30-8545d83c3fa7.png)

It seems the issue is being after a list and having spaces.

### Environment

* Build: 4107.
* Operating system and version: Windows 10 21H1.

**Comment by deathaxe** [comment]
Sure you are using builtin Markdown syntax?

This is what it looks with ST4107 in safe mode.

![grafik](https://user-images.githubusercontent.com/16542113/119864354-d9427c00-bf1a-11eb-8550-6ad9a8088655.png)

![grafik](https://user-images.githubusercontent.com/16542113/119864433-ea8b8880-bf1a-11eb-8bfc-35a6580c0aaa.png)

**Comment by RoyiAvital** [comment]
@deathaxe , I am not sure what you show.
It seems your line isn't with spaces as my code above.

Make sure you copy one to one what I pasted (Mind the space before `[001]:` and `[002]:`).

**Comment by deathaxe** [comment]
I missed discussion on Discord. Wasn't even aware of reference definitions being valid nearly everywhere in the document.

**Comment by RoyiAvital** [comment]
@deathaxe , Forgetting the discussion aside for a moment, it doesn't make sense even to say the bug isn't there while you don't even follow the MWE to the letter (Space in this case).

**Comment by deathaxe** [comment]
There are several Markdown syntaxes out in the wild one of those MarkdownEditing overriding default syntax, while shipping with exactly this kind of issues - several constructs not being supported when indented. I don't know how I missed that indentation, but with all that sometimes dump issues being reported I was busy working on, please forgive me that oversight.

**Comment by RoyiAvital** [comment]
I always check the syntax I use against [CommonMark official implementation](https://spec.commonmark.org/dingus/).
My above is parsed correctly hence it should be parsed correctly by Sublime Text.

**Comment by deathaxe** [comment]
That's for sure.
