### ISSUE TITLE
[C/C++] Wrong syntax highlighting for blocks in nested preprocessor conditionals

### ISSUE THREAD

**Issue by mrim5** [sublimehq/Packages#284]
The following code is not highlighted correctly in Dev Build 3111. `int b = 3;` active and so should not be dimmed/greyed out but it is, and vice versa for `int b = 2;` and `int d = 4;`. Only `int a = 1;` is correctly highlighted. Also, the `0` on the third line is not highlighted as a number.
```
#if 1
    int a = 1;
    #if 0
        int b = 2;
    #else
        int c = 3;
    #endif
#else
    int d = 4;
#endif
```
![cbug](https://cloud.githubusercontent.com/assets/18471485/14543599/f08694ac-0262-11e6-9d8b-d930c9dec1e2.png)

**Comment by wbond** [comment]
This is fixed by 413a584959c658fa99b06c7476a105141a6e6c45
