### ISSUE TITLE
[MATLAB] Missing Support for MATLAB `argument` Block

### ISSUE THREAD

**Issue by RoyiAvital** [sublimehq/Packages#2843]
MATLAB has added in the last year support for a new [Function Argument Validation](https://www.mathworks.com/help/matlab/matlab_prog/function-argument-validation-1.html).

It creates a block of the form:

```
arguments
    <Arguments to Validate>
end
```

- Sublime Version: 4107.
- OS Version: Windows 10 21H1.

Currently Sublime Text's MATLAB packages doesn't recognize this:

``` matlab
arguments
    mX (:, :) {mustBeNumeric}
end
```

It will be great if it will have a dedicated scope as well.

P. S.
The product is called `MATLAB` and not `Matlab`. So it might be a good idea to also rename the folder.

**Comment by jwortmann** [comment]
Would be fixed by #2650.

> P. S.
> The product is called MATLAB and not Matlab. So it might be a good idea to also rename the folder.

Yes, but it would be a breaking change and would invalidate all user-overrides for this package. The Syntax name is correctly displayed as MATLAB in the right corner of the status bar.
Btw, Tcl is actually named Tcl, and not TCL like in this repository.

**Comment by RoyiAvital** [comment]
@jwortmann , What's stopping your PR to be accepted?

**Comment by jwortmann** [comment]
> 
> 
> @jwortmann , What's stopping your PR to be accepted?

Nothing. Maybe the relatively low popularity of MATLAB compared to some other languages?

In general, PRs are merged in large heaps only once or twice a year or so. So it might take a while until fixes/improvements from this repo are included in the program, which is especially true for non-trivial changes like this one that may take some time to review.

**Comment by jwortmann** [comment]
This is fixed on master and should be available in a future release, so I think this issue can be closed now.
