### ISSUE TITLE
[Ruby] & [Ruby On Rails] Syntax Highlighting Incorrectly Handle Bitwise Left Shift (<<)

### ISSUE THREAD

**Issue by maurice-does-software** [sublimehq/Packages#2871]
### Description
I opened a file in my project for editing, and the syntax highlighting colored about half the file as if it were a long code comment. The class in question functions as expected, passes automated specs, and has not been recently changed, so it does not have any syntax errors which would explain this behavior. This is the first time I have opened the file in question since updating SublimeText via Ubuntu's "Software Updater" app, which I believe uses the apt repository. Upon opening the file, "Ruby" syntax highlighting was auto selected. I changed that to "Ruby on Rails", hoping that might fix the issue, but the errant coloring didn't change.

* Sublime Build: 4107
* OS: Ubuntu 20.04.2 LTS
* Windowing System: X11

``` lang
ruby
```
![Screenshot from 2021-06-16 09-13-30](https://user-images.githubusercontent.com/5034033/122258290-bd7d2680-ce85-11eb-8cf7-fe7cd91667bd.png)

I did notice after experimental editing of the line, that:
- removing the comment at the end of the line made no difference
- commenting out the entire line corrected the highlighting
-replacing the entire conditional statement with `true` corrected the highlighting
-so, seems to be an issue highlighting bitwise operations specifically

Breaks highlighting for all following lines:
`return true if (pre.to_i & (1<<bit)) != (post.to_i & (1<<bit)) # check if there are changes for this bit`
Does not break highlighting for all following lines:
`return true if x != y # check if there are changes for this bit`
Alo does not break highlighting for all following lines:
`return true if (pre.to_i & (x)) != (post.to_i & (y)) # check if there are changes for this bit`

**Comment by rwols** [comment]
Is https://github.com/sublimehq/Packages/pull/2854 the dus?

**Comment by themilkman** [comment]
I can confirm that (with the latest revision of @deathaxe) it fixes your example code.

Hopefully the Ruby changes (also other PRs) provided by him will be merged soon.
