### ISSUE TITLE
[C++] `<` and `>` are mis-parsed as template

### ISSUE THREAD

**Issue by jfcherng** [sublimehq/Packages#2890]
![image](https://user-images.githubusercontent.com/6594915/124201365-6bd1ce80-db0a-11eb-98fd-8721db68137e.png)

```c++
if (a < 1 || a > 2) {}
```

- Sublime Version: 4109
- OS Version: Win10 21H1 x64

**Comment by Mivik** [comment]
![Bug](https://user-images.githubusercontent.com/54128043/125871365-e2c8ab05-74c4-4780-b30a-38e8990782b0.png)

```cpp
int main() {
	std::string str;
	auto a = str < "> qwe";
}
```

Similar problem here.

- Sublime Version: 4113
- OS Version: Ubuntu 20.04.2 LTS

**Comment by rwols** [comment]
The template detector needs branching.

**Comment by jfcherng** [comment]
close as duplicate https://github.com/sublimehq/Packages/issues/2890
