### ISSUE TITLE
[Java] Syntax Highlighting text blocks not supported at all, it seems

### ISSUE THREAD

**Issue by StrangeNoises** [sublimehq/Packages#2919]
Java now supports text blocks in code. Sublime Text 4 doesn't appear to know anything about this and tries to highlight it as if it's code.

(I held off on reporting this while I was still on ST3, but now seems the time... Needless to say vscode OOTB does it right. 😉 I note github does too, in the example code block below...)

- Sublime Version: 4113
- OS Version: MacOS 11.5.1 (but expect is everywhere)

This complete program compiles and runs in java 16, and likely back to whichever java version text blocks appeared in.

``` java
public class textblock {
    private static final String USAGE = """
        textblock [options] [args...]

          --help
            Show this text.
        """.stripIndent();
    public static void main(String... args) {
        System.out.println(USAGE);
    }
}
```

<img width="887" alt="image" src="https://user-images.githubusercontent.com/1295001/127319557-f13b3ef1-3f6e-4085-a139-0b1c9883b726.png">

**Comment by deathaxe** [comment]
The linked PR fully supports Java 16 language features.
