### ISSUE TITLE
[TSX] String Interpolation in ternary operation when rendering JSX in TypeScript React

### ISSUE THREAD

**Issue by uicrafts** [sublimehq/Packages#2929]
- Sublime Version: Sublime Text 4, build 4113
- OS Version: macOS Big Sur 11.4
- Description: see the screenshot, I annotated the issue there for clarity. I've tried different themes and the issue persists. I've also disabled extensions such as `Emmet` and the issue persists. My file extension is `TSX` and I'm using `LSP-typescript`. Worth nothing that removing the interpolation `${styles.class2}` in line 29 fixes the rest of the file and this issue.

```typescript
import * as React from 'react'

// import * as styles from './TestComponent.module.scss'

// Mocking the above CSS Module `styles` object
const styles = {
  class1: '',
  class2: ''
}

type Props {
  conditionalValue1: boolean
  conditionalValue2?: boolean
}

export const TestComponent = (props: Props) => {
  const { conditionalValue } = props

  return (
    <li>
      {conditionalValue ? (
        <span
          className={`some-other-css-class ${styles.class1}`}
        >
         good morning
        </span>
      ) : (
        <div
          className={`another-css-class ${styles.class2}`}
        >
          good night
        </div>
      )}

      {conditionalValue2 !== undefined && (
        <div>
          incorrect syntax highlighting
        </div>
      )}
    </li>
  )
}
```

![CleanShot 2021-08-01 at 20 33 19@2x](https://user-images.githubusercontent.com/4595734/127801296-3980918d-24a7-438c-8431-71aba3689f96.png)
*Note: line 17 in the screenshot/snippet should also destructure `conditionalValue2` from props.

**Comment by uicrafts** [comment]
@Thom1729 Thank you very much for taking the time to look into this! This pattern of conditional rendering is common in React, so I imagine it would be common for developers to run into it and fixing it would be a nice improvement.

**Comment by Thom1729** [comment]
Should be fixed in the linked PR. Thanks for the detailed report.

**Comment by uicrafts** [comment]
@Thom1729 Thank you Thomas! Out of curiosity, how often do PRs like this one get merged in your experience?

**Comment by Thom1729** [comment]
Hard to say. Generally, they're merged shortly before a release or dev build, so timeframe could vary greatly. This is a pretty obscure bug (the code required to produce it is rather specific), so I wouldn't expect an emergency patch. However, if the bug is a major problem for you (which it seems to be, given that it breaks the rest of the file), you can check out the branch from the PR in the mean time.

**Comment by uicrafts** [comment]
@Thom1729 Sounds good. I appreciate the context and thanks again for being generous with your time taking a look at this.
