### ISSUE TITLE
[bash] A leading backlash (`\`) before a command appears to escape the first character

### ISSUE THREAD

**Issue by zx8** [sublimehq/Packages#2948]
From https://tldp.org/LDP/GNU-Linux-Tools-Summary/html/c1195.htm:

<img width="1451" alt="image" src="https://user-images.githubusercontent.com/8544900/129015627-75e5a972-82ec-4d7b-a6ff-53ab39dfe22d.png">

Also StackOverflow: https://stackoverflow.com/questions/15691977/why-start-a-shell-command-with-a-backslash/16506263

---

Actual syntax highlighting:

<img width="156" alt="image" src="https://user-images.githubusercontent.com/8544900/129015799-e094605f-c217-4a8f-a5ba-e0e86b7b7736.png">

This suggests the backlash is escaping the `c` of `curl`, but it's not.

**Comment by deathaxe** [comment]
While we probably might give a command's leading backslashes a special meaning, Bash specification doesn't inclue any statement about it. According to https://www.gnu.org/software/bash/manual/bash.html#Escape-Character it just prevents the following character from being expanded, which implicitly disables alias expansion, too.

This is basically also what the second answer at stackoverflow says. By quoting any character of the command alias expansion is disaled. Esacaping is treated as special kind of quoting then.

So from technical perspective current syntax highlighting is ok.

You could also write

```sh
'c'url example.com
```

which would have the same effect.

Also note that this kind of alias-overriding is said to be effective in interactive shells only, while this syntax is probably more likely used for scripts.
