### ISSUE TITLE
[PHP] SELECT string highlighting

### ISSUE THREAD

**Issue by amiklny** [sublimehq/Packages#2956]
### Description

Incorrect highlight

### Steps to reproduce

1. Start Sublime Text
2. Paste code
```
<?
$res = CUser::GetList(
	'LAST_NAME',
	'ASC',
	$userFilter,
	[
		'SELECT' => ['UF_DEPARTMENT'],
		'FIELDS' => ['ID', 'LAST_NAME', 'WORK_POSITION']
	]
);
?>
```

### Expected behavior

Correct highlight ('SELECT' is highlighted in green)

### Actual behavior

Incorrect highlight ('SELECT' is highlighted in magenta)

### Environment

4113, windows 11 (10)

**Comment by BenjaminSchaaf** [comment]
Looks like it's highlighting the SELECT as SQL, which generally makes sense except in the case where the string is just "SELECT".

**Comment by keith-hall** [comment]
partially relevant to the case where the string is just "SELECT" for example: https://github.com/sublimehq/Packages/issues/572
