### ISSUE TITLE
[PHP] Why use branching for regexp vs. sql strings?

### ISSUE THREAD

**Issue by deathaxe** [sublimehq/Packages#2957]
It appears quoted regexp patterns are clearly identified by quotation marks directly followed by slashes.

https://github.com/sublimehq/Packages/blob/43081b3494a3d743b9aeb4b60e971b3f1f5528eb/PHP/PHP%20Source.sublime-syntax#L1566-L1567

Why is branching applicated to distinguish them from ordinay quoted strings?

https://github.com/sublimehq/Packages/blob/43081b3494a3d743b9aeb4b60e971b3f1f5528eb/PHP/PHP%20Source.sublime-syntax#L1703-L1713

This is an unnecessary amount of overhead added to the syntax definition.

**Comment by jfcherng** [comment]
if you want to assume all strings begin with a slash is a regex.

**Comment by deathaxe** [comment]
Regexp branch just only fails if not, isn't it?

Maybe I miss something?

**Comment by jfcherng** [comment]
line 1579-1580 will go the fail too. (i am on mobile so i am not able to do a good reference code)

**Comment by deathaxe** [comment]
Thank's, I see.
