### ISSUE TITLE
<HTML>

### ISSUE THREAD

**Issue by MarkAgb** [sublimehq/Packages#2965]
<fin>
    Please search existing issues to avoid creating duplicates. Also, if you
    are able, follow the directions at https://github.com/sublimehq/Packages#installation
    to check the latest version of this language highlighting.

    If the problem persists, please begin the issue title with the language in
    square brackets, e.g. "[XML] Tags with underscores"
-->

- Sublime Version:
- OS Version:

``` lang
# Minimum code snippet to demonstrate the issue
```

**Comment by jfcherng** [comment]
Please fill information about the issue and use a proper title.
