### ISSUE TITLE
[Markdown] Do not insert two backticks when the cursor is on a word

### ISSUE THREAD

**Issue by weichuliu** [sublimehq/Packages#2973]
### Problem description

In Sublime Text 4, if you type backtick ("`") in a Markdown file, ST will insert two backticks.

This is meant to be convenient, but when you want to backtick-quote an existed word, you type "`" at the beginning of a word, ST still inserts two, and you have to delete one (Actually, you will delete both if you hit backspace. Then, you need to move the cursor right, and delete the second one). This is very annoying.

### Preferred solution

Backtick insertion should follow the same behavior as single/double quotes, that is, when the cursor is at the beginning, in the middle or at the end of a word, only one "`" should be inserted.

```
😢(CURSOR)word  -> ``word
😄(CURSOR)word  -> `word

😢word(CURSOR)  -> word``
😄word(CURSOR)  -> word`

😢wo(CURSOR)rd  -> wo``rd
😄wo(CURSOR)rd  -> wo`rd
```

**Comment by rwols** [comment]
You could select the word first with ctrl+left, then press your backtick key. But I can see how this can be annoying.
