### ISSUE TITLE
[INI] cannot set syntax for all files with a certain extension

### ISSUE THREAD

**Issue by dannftk** [sublimehq/Packages#2990]
- Sublime Version: Build 4113
- OS Version: Gentoo/Linux x86_64

I do not know if it's been done intentionally or not, but I am able to set INI syntax highlighting for a specific file opened using Command Palette, but I am unable to set the syntax for a specific file or for all files with a certain extention using control elements on the ST window

Does anyone observe such a peculiarity?

Thank you in advance

**Comment by jfcherng** [comment]
INI is not a builtin syntax btw.
