### ISSUE TITLE
Will there be hidden syntax files?

### ISSUE THREAD

**Issue by buildersbrewery** [sublimehq/Packages#30]
Hello Jon,

will there be something like `*.hidden-sublime-syntax` files? With the old TextMate files you could hide syntax files from the menu.

**Comment by jfcherng** [comment]
Doc: https://www.sublimetext.com/docs/3/syntax.html

Are you finding something like this?
``` hidden: true```
```
%YAML 1.2
---
name: MY_SYNTAX
hidden: true
scope: source.my_syntax
contexts:
  main: ...
```

**Comment by buildersbrewery** [comment]
Oh, I missed that one. Thanks @jfcherng
