### ISSUE TITLE
[Java/Python/TS] can't match decorator name or annotation name in the gammar

### ISSUE THREAD

**Issue by jingyuexing** [sublimehq/Packages#3012]
I want to highlight the Annotation or Decorator in the grammar，but can't math Annotation name. just only match the `@` symbol

The themes colors is:
```json
{
            "name": "Decorators/Annotation",
            "scope": "meta.decorator meta.decorator punctuation.decorator, storage.type.annotation, variable.annotation, punctuation.definition.annotation",
            "foreground": "#ffb454"
        }
```
but this theme can't render syntax,because the syntax file can't match this mode,like
```
@some_decorator 
@some_annotation
@message(title='hello')
```

**Comment by jfcherng** [comment]
In Java, somehow there is an extra `-` in the syntax definition.
https://github.com/sublimehq/Packages/blob/c70117be6402c54ccf860ab8edfcba8aade46c9e/Java/Java.sublime-syntax#L176-L185

**Comment by jingyuexing** [comment]
maby should like this
![image](https://user-images.githubusercontent.com/19589872/131965218-ddb63c8f-25a2-4acc-90c6-40e0a423ad5f.png)
