### ISSUE TITLE
[Syntax] why we not use ANTLR to generate grammar files(sublime-syntax) ?

### ISSUE THREAD

**Issue by jingyuexing** [sublimehq/Packages#3017]
## same with title

**Comment by jfcherng** [comment]
From what I saw, the highest hope for 3rd-party `.sublime-syntax` generator is https://github.com/BenjaminSchaaf/sbnf.

**Comment by jingyuexing** [comment]
> From what I saw, the highest hope for 3rd-party `.sublime-syntax` generator is https://github.com/BenjaminSchaaf/sbnf.

look like is awesome,but ,if that is plugin maby better

**Comment by michaelblyons** [comment]
> look like is awesome,but ,if that is plugin maby better

Not to be flippant, but you're welcome to _make_ an ANTLR to sublime-syntax generator plugin. No one (to my knowledge) has done so yet. Several people would definitely try it. Some people might even use it for real.

**Comment by deathaxe** [comment]
I guess the answer may be the same as for "Why does ST not use TreeSitter to generate syntaxes". It just uses another approach.

With some knowledge about DTD files, which are basically a kind of BNF to define structure/grammer of XML files, I doubt an BNF grammer to be able to represent/handle all those weird special cases of some syntaxes. All those meta scopes used to specify the meaning of expressions are another challange for such a BNF representation.

Also the heavy need of quotes, and all kinds of brackets to write a BNF int plain text is just a pain, IMHO.

The generated sublime-syntax files I've seen so far often look weird and hard to read. I wouldn't want such generated mess in a core package.
