### ISSUE TITLE
[TypeScript] type mapping not highlighted correctly.

### ISSUE THREAD

**Issue by deathaxe** [sublimehq/Packages#3019]
- Sublime Version: 4114
- OS Version: Windows 10

```ts
/// <reference no-default-lib="true"/>


type FlatArray<Arr, Depth extends number> = {
    "done": Arr,
    "recur": Arr extends ReadonlyArray<infer InnerArr>
        ? FlatArray<InnerArr, [-1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20][Depth]>
        : Arr
}[Depth extends -1 ? "done" : "recur"];
```

The content in braces is highlighted pretty plain.

![grafik](https://user-images.githubusercontent.com/16542113/132123279-ff0e47ca-9550-4cb4-9c7b-f558ae151e26.png)

The construct was found in `typescript` node_module, which is shipped with `language-server` package of LSP-html package.

local path: Package Storage\LSP-html\14.3.0\language-server\node_modules\typescript\lib\lib.es2019.array.d.ts

**Comment by Thom1729** [comment]
The bug here is that the object type isn't recognizing the quoted keys as keys. I'll fix it.
