### ISSUE TITLE
[PHP] Using namespace bug

### ISSUE THREAD

**Issue by jbrooksuk** [sublimehq/Packages#302]
Imported namespaces are being highlighted incorrectly:

![image](https://cloud.githubusercontent.com/assets/246103/14701422/3d80b3a2-079d-11e6-9923-f095a0906e3e.png)

**Comment by wbond** [comment]
Thanks for the report, I should have this fixed up shortly.

**Comment by wbond** [comment]
This should be fixed by 04172c0f56dcb5d027f7982a12571a036dfe486f

**Comment by jbrooksuk** [comment]
Yay, thanks Will!
