### ISSUE TITLE
[PHP] List of std class names

### ISSUE THREAD

**Issue by Alexey-T** [sublimehq/Packages#3043]
### What happened?

The PHP file has word list, it has these 
```
DOMAttr
DomAttribute
DOMCharacterData
DOMComment
DomDocument
DOMDocument
DOMDocumentFragment
DomDocumentType
DomElement
DOMElement
DOMEntityReference
DOMImplementation
DOMNamedNodeMap
DomNode
DOMNode
DOMNodelist
DomProcessingInstruction
DOMProcessingInstruction
DOMText
DOMXPath
DomXsltStylesheet
```
DOM* and Dom* names. E.g. DOMElement and DomElement. is it OK?

**Comment by jfcherng** [comment]
https://www.php.net/manual/en/book.dom.php

The official docs uses all capital `DOM`. Duplicate ones can be removed safely as that regex is case-insensitive.
