### ISSUE TITLE
[PHP] No Syntax highlight

### ISSUE THREAD

**Issue by elnath78** [sublimehq/Packages#3048]
### What happened?

Starting out a new plug-in for Wordpress, there is no syntax colorization at all: http://share.creoweb.it/92f41a2d.jpg

I tried demoving part of code / comments with no result, I also tried opening the file alone and not as a project or folder. Other syntax are working fine, tried that too but switching back and forth didn't fix it.

**Comment by jfcherng** [comment]
In PHP, everything out of `<?php ... ?>` are HTML.
