### ISSUE TITLE
[SQL] "CREATE DATABASE IF NOT EXISTS `name-with-dash`" breaks highlighting

### ISSUE THREAD

**Issue by jfcherng** [sublimehq/Packages#3072]
### What happened?

![Snipaste_2021-10-04_16-46-11](https://user-images.githubusercontent.com/6594915/135821081-fc067f78-1eed-4ebd-9da8-3bcdf18b99ad.png)

Removing the `-` in `` `...` `` fixes this.

```sql
CREATE DATABASE IF NOT EXISTS `ust-enroll` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
```

**Comment by keith-hall** [comment]
this is already fixed in https://github.com/sublimehq/Packages/pull/3046
