### ISSUE TITLE
[Markdown] Parens in link dests break angle brackets

### ISSUE THREAD

**Issue by ISSOtm** [sublimehq/Packages#3073]
### What happened?

```markdown
[text](<ab>)
```
Correctly underlined as a link dest

```markdown
[text](<a b>)
```
Not underlined, but apparently still recognized as a link dest?

```markdown
[text](<a (b)>)
```
`(b)` is treated as a link title, [which does not match CommonMark 0.30](https://spec.commonmark.org/0.30/#links).

**Comment by deathaxe** [comment]
This issue is already fixed in MarkdownEditing package and may be merged back into this repo in a future release.
