### ISSUE TITLE
[XML] attribute equals sign has no specific scope

### ISSUE THREAD

**Issue by keith-hall** [sublimehq/Packages#309]
from discussion https://github.com/sublimehq/Packages/pull/308

I think it would be a good idea to give the equals sign between the attribute name and value a scope, maybe something like `punctuation.separator.attribute.xml`, which shouldn't affect highlighting if I understand right because most color schemes don't color punctuation separators :)

**Comment by jcberquist** [comment]
@keith-hall: I just want to note that in the HTML syntax the equals sign gets the scope `punctuation.separator.key-value.html` so another possibility here would be `punctuation.separator.key-value.xml`.

**Comment by keith-hall** [comment]
@jcberquist nice one, I think makes sense to keep them consistent :) for some reason, I didn't think of checking the HTML syntax! thanks for your input :)
