### ISSUE TITLE
[JavaScript] Highlighting does not work after excessive bracket depth

### ISSUE THREAD

**Issue by incertia** [sublimehq/Packages#3100]
### What happened?

When opening a file that nests many brackets, the deeply nested ones fail to highlight. I'm unsure if this is a JS package problem or an issue with sublime itself.

![](https://i.imgur.com/cssBys3.png)

**Comment by Thom1729** [comment]
I'm sure this is an engine limitation.

On the off chance that this is your code, I strongly recommend using the [`fs/promises`](https://nodejs.org/api/fs.html#promises-api) API instead of nesting like this.

**Comment by incertia** [comment]
cool. i'll close this then.

it is not my code but some code i pulled from some malware that steals discord tokens

**Comment by FichteFoll** [comment]
Via the back-referencing issue https://github.com/sublimehq/sublime_text/issues/5283, this is a problem with ST core when the scope stack becomes too large.
