### ISSUE TITLE
[C#] Constant string in attribute parameter with comment marker is parsed incorrectly

### ISSUE THREAD

**Issue by rolfbjarne** [sublimehq/Packages#3105]
### What happened?

See screenshot:

<img width="220" alt="Screenshot 2021-10-28 at 10 23 01" src="https://user-images.githubusercontent.com/249268/139216967-2846e63d-fbe8-4609-bd11-64918fbb7286.png">

The double slash in the second attribute seems to make Sublime Text think it's a comment, when it's a string.

It's even more obvious with a block comment:

<img width="244" alt="Screenshot 2021-10-28 at 10 25 49" src="https://user-images.githubusercontent.com/249268/139217289-4d597f38-5075-4dd3-8eeb-9a5dcba9ee51.png">

I'm running into the former though, with URLs in the string constants.

This is with 543a822b9b019e457bd5458455d6e5deac7330da.

**Comment by keith-hall** [comment]
Fixed by https://github.com/sublimehq/Packages/pull/3107
