### ISSUE TITLE
[R] Native Pipe |> Ligature

### ISSUE THREAD

**Issue by christophsax** [sublimehq/Packages#3119]
### What happened?

R 4.1 ships the native pipe (`|>`) which Fira Code renders as a triangle ligature. However, the R syntax of Sublime breaks this apart. It works fine in other syntax definitions or with plain text.

I asked [a question on SO](https://stackoverflow.com/questions/69810963/sublime-text-to-display-r-native-pipe-ligature-with-fira-code) and got the recommendation to open an issue here.

Thanks for your support!

**Comment by michaelblyons** [comment]
Should be easy. You can even make the pull request if you want. Add or modify an appropriately-scoped match [somewhere around here](https://github.com/sublimehq/Packages/blob/master/R/R.sublime-syntax#L155-L160). It just needs to be above the `\|\|?` match in line 161. I don't know what kind of operator that is, so I don't know what scope it should have.
