### ISSUE TITLE
[Git Formats] Git Commit highlights "C#10" as an issue reference when it isn't one

### ISSUE THREAD

**Issue by keith-hall** [sublimehq/Packages#3123]
### What happened?

```text
[C#] Add support for C#10 features
```

![image](https://user-images.githubusercontent.com/11882719/140403285-f0d1f97c-d2e9-4cb4-9787-4e3e536b09d4.png)

**Comment by jwortmann** [comment]
There is an explicit syntax test which insists on this highlighting:
https://github.com/sublimehq/Packages/blob/50b03b3970f0daca8dd982bb41dcdd21790f9a68/Git%20Formats/tests/syntax_test_git_commit#L50-L55

Also compare the regex for repository references, where the "user" part is deliberately made optional:
https://github.com/sublimehq/Packages/blob/50b03b3970f0daca8dd982bb41dcdd21790f9a68/Git%20Formats/Git%20Common.sublime-syntax#L13

That said, GitHub seems to require the "user" part to be present for its autolink functionality (both for issues as well as for commit hashes):

`#3123` -> #3123

`sublimehq/Packages#3123` -> sublimehq/Packages#3123

`Packages#3123` -> Packages#3123

So maybe the regex should be adjusted to match the behavior from GitHub?

**Comment by deathaxe** [comment]
Changing the pattern will only end up in `C` not being highlighted. `#10` would still receive references scope.

**Comment by jwortmann** [comment]
> 
> 
> Changing the pattern will only end up in `C` not being highlighted. `#10` would still receive references scope.

To prevent this, I think it would work to adjust the pattern in the `issue` context from `{{repository_ref}}?` to `{{repository_ref}}|\B`

**Comment by deathaxe** [comment]
As `user#issue` is a valid auto-link format the only possible solution was to add a black-list for tokens like `C#10`. I am uncertain, whether we want to open such a door though.

**Comment by michaelblyons** [comment]
`user#issue` is not mentioned in [the GitHub docs I found](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/autolinked-references-and-urls), but it is valid in [the GitLab docs](https://docs.gitlab.com/ee/user/markdown.html#gitlab-specific-references). Is that what you mean?

**Comment by deathaxe** [comment]
Github resolves it, too. See https://github.com/sublimehq/Packages/pull/3127#issuecomment-962460586
