### ISSUE TITLE
[Ruby] SQL Heredoc not handled correctly

### ISSUE THREAD

**Issue by odydoum** [sublimehq/Packages#3124]
### What happened?

Having a simple SQL heredoc that is indented messes up syntax highlighting:

```ruby
def test
  sql = <<-SQL
    users.username LIKE :like OR
    users.email LIKE :like
  SQL
end
```
![Screenshot from 2021-11-05 16-27-32](https://user-images.githubusercontent.com/14910034/140527176-5e04bf99-03c9-4325-820a-df57d4947185.png)

if the end tag is not indented, the highlighting is correct:

```ruby
def test
  sql = <<-SQL
    users.username LIKE :like OR
    users.email LIKE :like
SQL
end
```
![Screenshot from 2021-11-05 16-31-36](https://user-images.githubusercontent.com/14910034/140527283-b988f01e-0d4f-43e0-9d4e-a188c0f970ad.png)

**Comment by michaelblyons** [comment]
Interestingly, the highlighting is correct if you use `SH` as the heredoc delimiter. 

```ruby
def test
  sql = <<-SH
    users.username LIKE :like OR
    users.email LIKE :like
  SH
end
```

Working:
- [x] SH
- [x] HTML
- [x] RUBY
- [ ] SQL
- [ ] JS
- [ ] CSS
- [x] (Other strings)

**Comment by deathaxe** [comment]
CSS is working fine here.

JS fails as we need to include `scope:source.js#script`.

The provided SQL example fails as the trailing `:like` seems to push into a context, so finalizing SQL tag is consumed by SQL.sublime-syntax for some reason.

**Comment by michaelblyons** [comment]
![Screen Shot 2021-11-05 at 12 49 48 PM](https://user-images.githubusercontent.com/2701605/140547907-4693234e-7f6c-43c8-9eb3-7ad7dc0ba2d3.png)

Obv, this is not normal CSS. I wonder if it is also pushing into something it does not escape from, like SQL.

> All HEREDOCs share the same style of patterns!

I noticed. 😅 Wasn't sure why some spilled out and some stayed in the local context.

**Comment by michaelblyons** [comment]
Could the `push`/`pop` instructions be converted to `embed`/`escape` to lock the heredoc highlighting inside the space?

**Comment by deathaxe** [comment]
Looking into it, atm. May also be used to better support interpolation.
