### ISSUE TITLE
Python higlighting of control characters in raw strings is wrong

### ISSUE THREAD

**Issue by johnburnett** [sublimehq/Packages#3133]
### What happened?

Escape characters in raw strings seem to highlight incorrectly.  Paste the following into a python buffer in Sublime:

```
# Standard string escape sequences look good (invalid ones are correctly highlighted):
'\a\b\c\d\e\f\g\h\i\j\k\l\m\n\o\p\q\r\s\t\u\v\w\x\y\z'
'\\'      # slash
'\''      # quote
'\"'      # quote
'\xaf'    # hex
'\1'      # one digit octal
'\12'     # two digit octal
'\123'    # three digit octal
'\1234'   # three digit octal with single trailing decimal digit
'\12345'
'\123456'
'\1\2\3\4\5\6\7\8\9\0'

# Taking the above and making them raw strings shows some issues:

# Characters b, d, h, s, w, and z look wrong:
r'\a\b\c\d\e\f\g\h\i\j\k\l\m\n\o\p\q\r\s\t\u\v\w\x\y\z'
r'\\'
r'\''
r'\"'
r'\xaf'
# All of these look wrong in some way:
r'\1'
r'\12'
r'\123'
r'\1234'
r'\12345'
r'\123456'
r'\1\2\3\4\5\6\7\8\9\0'
```
...this renders like this:
![image](https://user-images.githubusercontent.com/945935/142331831-1a41edfd-105f-4a12-8aef-0d8d4ad56c16.png)

**Comment by jfcherng** [comment]
`r'blahblahblah'` is treated as regex in ST's syntax def.

**Comment by rwols** [comment]
Note you can make the syntax treat them as non-regex by prefixing them with an uppercase letter `R`, instead of your lowercase `r`. https://github.com/sublimehq/Packages/issues/2365#issuecomment-630378377

**Comment by FichteFoll** [comment]
As a quick note, if you don't want regex highlighting for raw strings, you may use an upper-case `R` instead.
