### ISSUE TITLE
[Regular Expressions] Dot (.) should have a scope

### ISSUE THREAD

**Issue by michaelblyons** [sublimehq/Packages#314]
I think that the `.` character should have a scope when not a part of a `[]` expression or otherwise escaped. It is an important part of regular expression syntax, and it would be a shame not to scope it and have someone imagine `.` to be a literal in their find/replace.

I do not, however, have strong opinions about what its scope should be... `keyword.other.any.regexp`? `constant.character.non-newline.regexp`? Something else?

**Comment by wbond** [comment]
This should be resolved by 0bb48851a1fe4f88498373a79e9e52789ce2b11f
