### ISSUE TITLE
[PHP] Closing `)` of a `for` loop is not scoped.

### ISSUE THREAD

**Issue by Ultra-Instinct-05** [sublimehq/Packages#3142]
### What happened?

The closing `)` punctuation of a simple `for` loop is not scoped. It should be scoped as `punctuation.section.group.end.php`

```php
<?php 
    for ($i = 0; $i < 10; $i++) {
        echo $i;
    }
 ?>
``` 
![image](https://user-images.githubusercontent.com/34304644/143600619-b1f9d559-4b6c-4c9d-ad5a-6e85382b5537.png)

![image](https://user-images.githubusercontent.com/34304644/143600455-450f929b-c8a5-493d-a463-c913fa9a8696.png)

**Comment by deathaxe** [comment]
Looks like `for` statements need special treatment. The expression within parentheses is terminated by the first `;` as it is interpreted as end of statement, which pops expressions off stack atm.
