### ISSUE TITLE
 RegEx highlighting is wrong for slashes within sets/ranges

### ISSUE THREAD

**Issue by lornally** [sublimehq/Packages#3150]
### Description of the bug

just like this: https://stackoverflow.com/questions/9226731/escape-forward-slash-in-jscript-regexp-character-class

sublime highlight regex error when slash without escape  as character class  enclosed in the square brackets

### Steps to reproduce

any language, regex is wrong, just like this: 
```ruby
/[\\/]node_modules[\\/]/
```
### Expected behavior
```ruby
# high light this
/[\\/]node_modules[\\/]/

# just as
/[\\\/]node_modules[\\\/]/
```

### Actual behavior

broken highlight

### Sublime Text build number

4142

### Operating system & version

macos 12.0.1

**Comment by deathaxe** [comment]
Both patterns highlight the same with ST4122 and default JavaScript.

![grafik](https://user-images.githubusercontent.com/16542113/143919671-9ad346bf-e8c1-4298-923f-a767d3b01adc.png)

As node doesn't complain about any of those, I'd say ST is highlighting them correctly.

**Comment by deathaxe** [comment]
Both patterns also highlight as expected when using _Regular Expressions.sublime-syntax_

![grafik](https://user-images.githubusercontent.com/16542113/144714603-a92a50ab-7545-497c-8d0f-e87eb369dfef.png)

So without further elaboration about which exact syntax is causing issues under which circumstances, I'd close this issue as "working as expected".
