### ISSUE TITLE
[C/C++] Add ld(1) syntax highlighting

### ISSUE THREAD

**Issue by mamins1376** [sublimehq/Packages#3151]
### What happened?

Add support for [ld(1)](https://linux.die.net/man/1/ld), [the GNU linker](https://ftp.gnu.org/old-gnu/Manuals/ld-2.9.1/html_chapter/ld_3.html) (although a pretty standard format for writing linker scripts and widely used).

As an example, there is a [small vimscript](https://github.com/neovim/neovim/blob/master/runtime/syntax/ld.vim) that implements this.

This is a simple format, so adding it does not seem to take much time.

Thanks!

**Comment by deathaxe** [comment]
Do you probably look for something like https://packagecontrol.io/packages/LinkerScript?

**Comment by mamins1376** [comment]
Yes, it seems good.
