### ISSUE TITLE
[Markdown] Not all code-blocks are syntax-highlighted

### ISSUE THREAD

**Issue by Alexey-T** [sublimehq/Packages#3157]
### What happened?

In this file not all blocks are handled.
[fenced-nice.md](https://github.com/sublimehq/Packages/files/7660685/fenced-nice.md)

Blocks for CSS and Cmd (Batch) are bad

![Screenshot from 2021-12-06 15-36-56](https://user-images.githubusercontent.com/4154978/144847229-48507bf7-b147-4c23-bd9e-3e6c076581ae.png)

**Comment by Alexey-T** [comment]
'cmd' alias is from here!
https://github.com/highlightjs/highlight.js/blob/main/SUPPORTED_LANGUAGES.md

**Comment by Alexey-T** [comment]
Is this solved ?

**Comment by deathaxe** [comment]
The missing syntaxes are part of the linked PR. Solution is prepared and pending for review>merge>release.
