### ISSUE TITLE
[Rust] `union` keyword not recognized

### ISSUE THREAD

**Issue by cbiffle** [sublimehq/Packages#3159]
### What happened?

Hi! I'm using your syntax definitions rather indirectly, via the Rust syntect crate compiled into the Zola static site generator.

I note that [in the first source listing in this section of my blog](https://cliffle.com/p/dangerust/4/#type-punning-via-union), the `union` keyword is not recognized/attributed. It appears in the Rust definition in this repo, the word `union` does not appear, so I believe it's an issue with the syntax definition.

**Comment by michaelblyons** [comment]
Try PR #2305

**Comment by cbiffle** [comment]
Diff looks plausible -- unfortunately (1) I'm stuck on a version of Zola that can't load syntax files at runtime because the newer versions were released with catastrophic bugs and (2) it's not straightforward to build against that PR to update the compiled-in syntax file because it's in a submodule of a dependency of a dependency. :-\

**Comment by michaelblyons** [comment]
If you're stuck on an old version, how does updating this repo help you?

**Comment by Alexey-T** [comment]
@cbiffle Thanks for your note (just improved my own tool which had the same issue)

**Comment by cbiffle** [comment]
> If you're stuck on an old version, how does updating this repo help you?

Well, I figured it improves this repo's syntax definitions and once Zola fixes some bugs I might also benefit? If you'd rather I didn't report the bugs, I can close this, I'm a little confused.

**Comment by michaelblyons** [comment]
Please feel free to report bugs here. I am just unsure how improvements will help you, given your constraints.

If you are later able to use newer versions of Zola and they *do* allow you to wire in alternative syntax definitions, you are welcome to try out PRs and unreleased versions.

**Comment by cbiffle** [comment]
That PR looks to have been open for quite a while, is it in need of verification? If that's what it's blocked on I could try to cobble together a custom build of the world. But the final comment on the PR suggests that it's hung up on other procedural things.

**Comment by deathaxe** [comment]
Fixed by #2305
