### ISSUE TITLE
[Ruby] SQL Heredoc comments not highlighting properly

### ISSUE THREAD

**Issue by gregblass** [sublimehq/Packages#3168]
### What happened?

The Ruby SQL heredoc could use some improvement in regards to comments:

Multi-line format (/* */):

![image](https://user-images.githubusercontent.com/279927/146250457-a80328cb-5ac0-4a9b-8dfb-dbc148480f59.png)

Single-line format (--):
![image](https://user-images.githubusercontent.com/279927/146250496-8113ebfc-ca4d-4698-955d-ba8597da6d3e.png)

I would expect sublime to turn all of the text yellow inside of those comments.

In addition, one `'` character in the comments turns the rest of the entire heredoc block yellow:
![image](https://user-images.githubusercontent.com/279927/146251185-eaf345d1-ddf7-4a12-ad83-9b53474cc1ea.png)

**Comment by keith-hall** [comment]
probably fixed by https://github.com/sublimehq/Packages/pull/3046 - where multiple dialects of SQL are supported.

**Comment by deathaxe** [comment]
While comments look ok, the WITH keyword is not highlighted

![grafik](https://user-images.githubusercontent.com/16542113/146413006-b67d4a3d-2085-4363-b622-dff2a4680dbe.png)

**Comment by michaelblyons** [comment]
Make an override for `SQL.sublime-syntax` to shim T-SQL into `source.sql` rather than MySQL.

**Comment by deathaxe** [comment]
Is this really what we want to in the long term?

**Comment by michaelblyons** [comment]
> Is this really what we want to in the long term?

Good question. I do not know, but there's no real way to tell which flavor of SQL the "main" one should be. If I remember right, Will talked about having some way to "pick" which one you want for embeds. (Can't find it now.) We could make a command palette entry that builds/changes the shim for you.

I'd be happy to hear a better system, but this is what I'm doing now and it's been working nicely for me.

**Comment by deathaxe** [comment]
Hmm. The idea about a quick panel is not too bad. We already have a [SQL (for Ruby).sublime-syntax](https://github.com/sublimehq/Packages/blob/master/Ruby/Embeddings/SQL%20(for%20Ruby).sublime-syntax) which is derived from SQL.sublime-syntax. It should be easy to write a template and create an override with given base syntax.

So users could decide for a flavor to use.

I here the requests for project or file specific settings already though.

**Comment by gregblass** [comment]
> While comments look ok, the WITH keyword is not highlighted
> 
> ![grafik](https://user-images.githubusercontent.com/16542113/146413006-b67d4a3d-2085-4363-b622-dff2a4680dbe.png)

So weird - mine to not look okay at all. Could this be color scheme dependent (I'm using Monokai?)

**Comment by michaelblyons** [comment]
All the comments after your first post have been about using PR #3046 and various implications of that. You should try it out, possibly with the shim. DeathAxe's screenshot is #3046 without the shim.

**Comment by michaelblyons** [comment]
> If I remember right, Will talked about having some way to "pick" which one you want for embeds. 

[Found it](https://forum.sublimetext.com/t/inheritance-for-sql-syntax-variants/31659/4?u=michaelblyons)

**Comment by br4nnigan** [comment]
Here's another one I won't open a separate issue for: inconsistent highlighting between heredoc and "normal". This is php though but does it make a difference, is this depedant on the ruby package? Or is the sql syntax managed via a sql package?

![Screenshot 2022-11-24 144038](https://user-images.githubusercontent.com/10244835/203798281-b4b8a470-254c-4594-b9bf-7df45aff67ec.png)

**Comment by michaelblyons** [comment]
Looks like the Heredoc version doesn't use a string scope underneath the SQL. That would be easy to change, for consistency, but I worry a little about hordes of PHP users enraged by the new coloring.

**Comment by deathaxe** [comment]
Must be a quite old PHP syntax then. Both ST4126 and ST4143 render it well, without `string` scope.

![grafik](https://user-images.githubusercontent.com/16542113/203821645-2e49fed5-c115-4260-9764-dc8c947cc4b4.png)

**Comment by deathaxe** [comment]
Fixed by #3046.
