### ISSUE TITLE
[ShellScript] "`A > will break scope stack`"

### ISSUE THREAD

**Issue by michaelblyons** [sublimehq/Packages#317]
If you have a redirect (`<` or `>`) in a `` "` ``-escaped shell script expression, the rest of the file will be scoped as a string. I think it may be because of a `meta.reset.color` right after the `>`:

``` bash
if [[ ! "`git status 2> /dev/null`" ]]; then
    #                  ^ meta.reset.color ??
    #                            ^^ These just push more string openers onto the stack.
    cd - > /dev/null
    return
fi
```

**Comment by jfcherng** [comment]
This should be an issue to `ShellScriptImproved`.

**Comment by michaelblyons** [comment]
Oops. You're right.
