### ISSUE TITLE
[JavaScript] TypeScript: Add inline type imports support

### ISSUE THREAD

**Issue by shelimov** [sublimehq/Packages#3181]
### What happened?

TypeScript 4.5 added a new feature [`type Modifiers on Import Names`](https://devblogs.microsoft.com/typescript/announcing-typescript-4-5/#type-on-import-names).
At this moment, syntax highlighting does not work for inline imports:
![image](https://user-images.githubusercontent.com/4550843/147753703-8e78df96-c9fe-48d8-b528-e340ca132bc8.png)

The same code example on GitHub:
```typescript
import { type Foo as SomeType } from 'bar';
import type { Foo as SomeType } from 'bar';
```

**Comment by deathaxe** [comment]
Fixed by #3185
