### ISSUE TITLE
[Markdown] no highlight for the most of the file

### ISSUE THREAD

**Issue by Alexey-T** [sublimehq/Packages#3183]
### What happened?

Linux v 4126.

file
[index.zip](https://github.com/sublimehq/Packages/files/7793503/index.zip)

this file is highlighted only at the end (last 2 lines) but 98% of file is white text.
![Screenshot from 2021-12-30 18-05-55](https://user-images.githubusercontent.com/4154978/147763444-fbe20f6d-feb2-41d7-af6c-b31c13021957.png)

**Comment by Alexey-T** [comment]
at least, we need to see HEADERS colored.

```
Python-Markdown
===============
```

**Comment by Alexey-T** [comment]
and, list-markers is good to see colored. I mean leading star-chars. or the entire lines.

```
* __International Input__
```

**Comment by Alexey-T** [comment]
and, REFs are not hilighted!
```
possible (see [differences](#differences) for a few exceptions).

* Provide an [Extension API](extensions/api.md) which makes it possible
  to change and/or extend the behavior of the parser.
```

**Comment by jfcherng** [comment]
I guess the color scheme you use is outdated. Working fine on my side.

**Comment by Alexey-T** [comment]
Tried to change to different via 'Prefs / Color theme...' - no result.

**Comment by deathaxe** [comment]
Works fine with ST4125 in SAFE MODE!

![grafik](https://user-images.githubusercontent.com/16542113/147765579-7ec2c5a9-ff0d-41ba-994c-663891035d99.png)

What does `view.syntax()` return?

**Comment by Alexey-T** [comment]
See my screenshot, statusbar tells that syntax.

**Comment by Alexey-T** [comment]
OK, close this issue- seems my setup is 'bad'.

**Comment by Alexey-T** [comment]
reinstalled the ST4. all is Ok.

**Comment by deathaxe** [comment]
> See my screenshot, statusbar tells that syntax.

This doesn't mean anything. 

If several packages provide the same syntax, it is easily possible an unexpected syntax file to have been applied which may be outdated and thus causing issues.

**Comment by Alexey-T** [comment]
I had the ~/.config/sublime-text-3 dir with old packages. deleted this. solved.
