### ISSUE TITLE
[CSS] no folding for some blocks

### ISSUE THREAD

**Issue by Alexey-T** [sublimehq/Packages#3184]
### What happened?

file
```
/* The first line of every <p> element. */
p::first-letter {
  color: blue;
  text-transform: 'uppercase test';
}
body::cue-region {
  all: revert;
}
/* Any button over which the user's pointer is hovering */
button:hover {
  color: blue visitedtext marktext graytext #02f;
  background-position-x: x-start center fixed initial scroll var();
  all: var();
  flex-basis: auto;
  -pie-background: Grey rgba();
  -moz-border-bottom-colors: none;
  background-image:  url() url("") !important;
  
}

body{
    color: #0F2;
}
```

folding works for 1st and 3rd blocks, but not for 2nd and 4th. screen.
![Screenshot from 2021-12-30 18-36-11](https://user-images.githubusercontent.com/4154978/147766058-9694e3f9-1371-431f-9d61-bb81e2ea599f.png)

**Comment by jfcherng** [comment]
I vaguely remember that this is by design. You just can't fold codes which has only one line.

**Comment by Alexey-T** [comment]
Ok, so you can close it.

**Comment by jfcherng** [comment]
Ref: https://forum.sublimetext.com/t/why-cant-i-collapse-fold-code-with-only-one-nested-line/23498
