### ISSUE TITLE
[CSS] Add special highlight for .name and #name

### ISSUE THREAD

**Issue by Alexey-T** [sublimehq/Packages#3188]
### What happened?

VSCode has special styles of `#nnn` and `.nnn`, not the same style as `nnn` has. It looks OK, let's do it too?

![vs2](https://user-images.githubusercontent.com/4154978/148640864-157b86d0-eec7-4fcd-aa6a-2f3970d38498.png)

```
#firstname {
  background-color: yellow;
}
body {
  background-color: yellow;
}
.firstname {
  background-color: yellow;
}

```

**Comment by deathaxe** [comment]
Your request is already implemented.

- `.firstname` is scoped as `entity.other.attribute-name.class`
- `#firstname` is scoped as `entity.other.attribute-name.id`

It's up to color schemes to provide different colors for these tokens.

## Example

```
{
	"rules": [
		{
			"scope": "entity.other.attribute-name.class.css",
			"foreground": "var(orange2)",
		},
		{
			"scope": "entity.other.attribute-name.id.css",
			"foreground": "var(pink)",
		}
	],
}
```

![grafik](https://user-images.githubusercontent.com/16542113/148641394-1b08825e-8f43-4fdd-acf1-6715aedf7314.png)
