### ISSUE TITLE
[Rust] Add support for strings in generics

### ISSUE THREAD

**Issue by deathaxe** [sublimehq/Packages#3191]
### What happened?

As a follow-up of #2323 we should probably look into supporting strings within generics at some point, if that syntax feature becomes stable.

```rust
State<"accumulate">
```

**Comment by FichteFoll** [comment]
Const generics have been stabilized in 1.51, which was released almost a year ago, however `&'static str` are not allowed with it currently. The code in #2323 only compiles in nightly with a feature flag at the moment (and additionally the feature is marked as "incomplete").

**Comment by FichteFoll** [comment]
Relevant upstream tracking issue for documentation: https://github.com/rust-lang/rust/issues/76560
