### ISSUE TITLE
[D] Conditional containing binary expressions are not highlighted properly.

### ISSUE THREAD

**Issue by deadalnix** [sublimehq/Packages#3192]
### What happened?

The following code snippet contains a conditional containing a binary expression:

```d
int x = a ? b - c : d;
```

This is not highlighted properly. The `;` at the end is highlighted as a syntax error.

The D grammar defines them as
```
ConditionalExpression
  BinaryExpression
  BinaryExpression ? Expression : ConditionalExpression
```

**Comment by deadalnix** [comment]
By any chance, do you know who that is?

Unfortunately, moist of your comment made no sense to me, so fixing this myself is likely to be very difficult. I have a lot to learn before I can do anything, and you seems to think this is on the difficult side. Maybe i can track down the author and see if there is something that can be done.

**Comment by deathaxe** [comment]
The artist is @BenjaminSchaaf.

**Comment by deadalnix** [comment]
Well i contacted him a few ways, and it doesn't looks like he's going to respond. Unfortunate. Let's keep this open, we'll see what comes out of it.
