### ISSUE TITLE
[rust] No `const` highlighting in struct

### ISSUE THREAD

**Issue by ismell** [sublimehq/Packages#3193]
### What happened?

```
bitflags! {
    struct Flags: u32 {
        const A = 0b00000001;
        const B = 0b00000010;
        const C = 0b00000100;
        const ABC = Self::A.bits | Self::B.bits | Self::C.bits;
    }
}
```

There is currently no highlighting in the above code.
![Screenshot from 2022-01-10 10-20-14](https://user-images.githubusercontent.com/562978/148809922-63a5b6c6-ddc8-4e80-bac5-feec3e9957c2.png)

I would expect `A`, `B`, `C`, and `ABC` to be marked as entities and appear in the global symbol list.

**Comment by deathaxe** [comment]
With PR #2305 merged the struct looks like...

![grafik](https://user-images.githubusercontent.com/16542113/148828105-81880047-6eed-4f7f-b05f-e6c6942e62cb.png)

The constants' identifiers are scoped `entity.name.module.rust` and could therefore easily be indexed.

**Comment by ismell** [comment]
Yay! Thanks.

**Comment by deathaxe** [comment]
With #3195 constants are indexed. Thus closing this issue as resolved.
