### ISSUE TITLE
[Git Formats] Adding new rebase instruction is hard.

### ISSUE THREAD

**Issue by michaelblyons** [sublimehq/Packages#3194]
### Expected behavior

I want to add another line with a new instruction

### Actual behavior

Autocompletion keeps replacing the words I try to type with the "magic" other words. `e` => `edit`, etc.

### Steps to reproduce

```
pick 1234567 |
pick 2345678
```
With cursor at `|`, hit <kbd>enter</kbd> and try to type `break`.

**Comment by deathaxe** [comment]
I guess this issue needs to go into https://github.com/deathaxe/sublime-gitformats/issues

**Comment by michaelblyons** [comment]
Haha, oops. Thanks!
