### ISSUE TITLE
[JavaScript] TypeScript: Add inline type exports support

### ISSUE THREAD

**Issue by shelimov** [sublimehq/Packages#3207]
### What happened?

Three weeks ago in #3181, I reported an issue with inline type imports, but forget to mention that the same problem exists within typed exports.

This is how it looks now with the master branch applied:
<img width="534" alt="image" src="https://user-images.githubusercontent.com/4550843/150436983-ca580205-a89a-489a-b423-e71f64b6a1a1.png">

The same code example on GitHub:
```ts
import { type Foo } from './someFile';
export { type Foo as Bar };
```

**Comment by michaelblyons** [comment]
Tangentially related: #2719
