### ISSUE TITLE
[C family] Alt + Q hard-line-wrap feature doesn't work for comments which begin with 3 slashes `///` (Doxygen comments)

### ISSUE THREAD

**Issue by ElectricRCAircraftGuy** [sublimehq/Packages#3215]
### Description of the bug

Any comments in C or C++ which begin with 3 slashes (`///`) make the <kbd>Alt</kbd> + <kbd>Q</kbd> hard-line-wrap feature not work right.

### Steps to reproduce

Put this into a C or C++ file:
```c
/// This is a really long doxygen comment This is a really long doxygen comment This is a really long doxygen comment This is a really long doxygen comment 
```

Place your cursor on that line, then press <kbd>Alt</kbd> + <kbd>Q</kbd> to hard-line-wrap. It does this:
```c
/// This is a really long doxygen comment This is a really long doxygen comment This is a really
//  long doxygen comment This is a really long doxygen comment 
```

That's not right. The 2nd line has only 2 slashes, not 3, and it has an extra space in it. It should have done this instead:

```c
/// This is a really long doxygen comment This is a really long doxygen comment This is a really
/// long doxygen comment This is a really long doxygen comment 
```

### Expected behavior

see above

### Actual behavior

see above

### Sublime Text build number

4126

### Operating system & version

Ubuntu 18.04

### (Linux) Desktop environment and/or window manager

Gnome

### Additional information

My clunky work-around, which is time-consuming, is to use the multi-line cursor mode to remove 1 slash per line, making each line begin with `//`. I then hit <kbd>Alt</kbd> + <kbd>Q</kbd> to hard-line-wrap, then I use the multi-line cursor mode to add 1 slash per line back to the beginning of each line, making them all begin with `///` again.

**Comment by ElectricRCAircraftGuy** [comment]
Any fix for this? I've been fighting with it for years.

**Comment by deathaxe** [comment]
See the linked PR #3217. Unfortunatelly C/C++ reviewers are rare.

**Comment by ElectricRCAircraftGuy** [comment]
@jwortmann , what does `[/!]?` mean?

**Comment by jfcherng** [comment]
@ElectricRCAircraftGuy it matches "a `/` or a `?` appears  0 or 1 time". It's called regular expression if you are interested.

**Comment by ElectricRCAircraftGuy** [comment]
@jfcherng , it doesn't appear to be a proper regular expression. Regex101.com doesn't like the forward slashes unescaped:  https://regex101.com/r/sATC3R/1

And what about the `!`? What's it do there?

**Comment by jfcherng** [comment]
@ElectricRCAircraftGuy we are not talking about javascript.

**Comment by ElectricRCAircraftGuy** [comment]
What are we talking about then?

And what about the `!`? What's it do there? The `/!` part seems to want to match a `/` literal char _or_ a `!` literal char.

**Comment by jfcherng** [comment]
lgtm.

**Comment by jwortmann** [comment]
Yes, I put the exclamation mark there because it's one of the possible ways to write Doxygen comments in C-like languages, according to https://www.doxygen.nl/manual/docblocks.html#cppblock

**Comment by ElectricRCAircraftGuy** [comment]
@jwortmann , understood. Thanks for explaining and posting the link!

**Comment by ElectricRCAircraftGuy** [comment]
I'm still hoping to see this feature added to the Alt + Q hardwrap in sublime text. Meanwhile, I'm moving to VSCode and the Rewrap extension to do this for me: 

![image](https://github.com/sublimehq/Packages/assets/6842199/31fd6e0a-8b7f-4667-866b-b3f4d3c34e91)

**Comment by ElectricRCAircraftGuy** [comment]
Note: I still use Sublime Text a ton--more than VSCode, so I still need Alt + Q text wrapping in Sublime Text all the time, including these features.

**Comment by deathaxe** [comment]
Maybe https://packagecontrol.io/packages/Wrap%20Plus can help you out.
