### ISSUE TITLE
[PHP] Default keyword is not highlighted

### ISSUE THREAD

**Issue by jbrooksuk** [sublimehq/Packages#322]
![image](https://cloud.githubusercontent.com/assets/246103/14883966/a3e4a382-0d39-11e6-9bba-25f7820bc717.png)

**Comment by keith-hall** [comment]
looks like [this commit](https://github.com/sublimehq/Packages/commit/04172c0f56dcb5d027f7982a12571a036dfe486f) broke it - the scope is now `entity.name.label.php`

**Comment by keith-hall** [comment]
simple test case (I'm assuming `default` is a valid name for a label):

    // SYNTAX TEST "Packages/PHP/PHP.sublime-syntax"
    <?php
      default:
    //^^^^^^^ entity.name.label.php - keyword.control.php
    switch (1) {
        case 1:
        default: 
      //^^^^^^^ keyword.control.php - entity.name.label.php
      // this currently fails because the scope is entity.name.label.php
    }
    ?>

**Comment by wbond** [comment]
This is fixed by 463b400bfbbdc0772a3d6a350a5761a3fb1593c8. Thanks for the report and the test case!
