### ISSUE TITLE
[PHP] No more highlighting at all

### ISSUE THREAD

**Issue by ldlgds2** [sublimehq/Packages#3225]
### What happened?

In default dark mode, PHP syntax is no more highlighted at all.
Files all have the PHP extension, opening php anchor (`<?php`) and are identified as PHP by Sublime 4.

**Comment by jfcherng** [comment]
Example code snippet for reproduction?

**Comment by ldlgds2** [comment]
Do you want me to provide you with my settings file for instance?
I just tried the Celeste theme and it does not work either.
I will try Sublime Text in safe mode in order to check.

**Comment by jfcherng** [comment]
> Do you want me to provide you with my settings file for instance?

No. I am more of believing something wrong in the code or there is another PHP syntax which overwrites ST's.

Could you run `view.syntax()` in ST's console with a problematic file opened?

**Comment by ldlgds2** [comment]
OK, opening in safe mode solved the problem.
Furthermore, something weird happened: I have in lieu of the problematic Sublime PHP window that closed a garbled display.
Last, when I reopened all windows in normal mode, the following message popped up:
`Error loading syntax file "Packages/PHP/PHP.sublime-syntax": Apparent recursion within a with_prototype action: 25000 context sanity limit hit`

**Comment by jfcherng** [comment]
> Error loading syntax file "Packages/PHP/PHP.sublime-syntax": Apparent recursion within a with_prototype action: 25000 context sanity limit hit

If you go main menu > Browse Packages, is there a PHP folder or HTML folder? If there is `PHP/PHP.sublime-syntax` or `HTML/blahblahblah.sublime-syntax` then you are likely using your own syntax, which you are responsible to maintain them.

**Comment by ldlgds2** [comment]
No user-installed PHP or HTML folder when browsing through packages.
Te only installed packages are `BeautifyRuby`, `C Improved`, `ESLint`, `Gutter Color`, `JSHint`, `jsonschema`, `markupsafe`, `mdpopups`, `python-jinja2`, `shellenv` && `A File Icon`.

**Comment by jfcherng** [comment]
I am run out of ideas at this moment, except that your code is not valid PHP.

**Comment by ldlgds2** [comment]
I'll give a try with a plain vanilla 'Hello world!' PHP file...

**Comment by ldlgds2** [comment]
Doesn't work either.

**Comment by jfcherng** [comment]
> Error loading syntax file "Packages/PHP/PHP.sublime-syntax": Apparent recursion within a with_prototype action: 25000 context sanity limit hit

Does ST still shows `PHP` in the bottom right corner even if this error? What's the output of `view.sytnax()` in the console?

**Comment by ldlgds2** [comment]
Yes, Sublime Text still shows the `PHP` symbol in the bottom right corner.
There is no output to the `view.syntax()` command.

**Comment by jfcherng** [comment]
Could you go `Main menu > Preferences > Package Settings > Package Control > Settings` and post things in `installed_packages` here?

**Comment by jfcherng** [comment]
`"JavaScriptNext - ES6 Syntax"` is the culprit. I don't think people need it anymore since the built-in is better than it now...

**Comment by ldlgds2** [comment]
Yes, it worked!
Many thanks.

**Comment by jfcherng** [comment]
FWIW,

| Plugin name | Why I don't recommand it |
|-------------------|---|
| All Autocomplete  | ST 4 seems do this by default. |
| Babel             | I don't think people need this anymore. Built-in JS syntax should be the best now. |
| C Improved        | I don't know but there are various changes since `C Improved` was invented. |
| PHP-Twig          | Looks like quite outdated. https://packagecontrol.io/packages/Twig is a maintained one. |
| SublimeLinter-php | I used to use it until I met `LSP` + `LSP-intelephense`. |

**Comment by ldlgds2** [comment]
Thank you.
