### ISSUE TITLE
[DXL] Title

### ISSUE THREAD

**Issue by Zaby1990** [sublimehq/Packages#3232]
### Expected behavior

any syntax highlightning for DXL-Files

### Actual behavior

![grafik](https://user-images.githubusercontent.com/47629476/153135830-0e0ff14a-d864-425e-9e9a-cc297146d569.png)

### Steps to reproduce

1. right-click on any *.dxl-file
2. click "Open with Sublime"
3. error occurs during opening
4. after confirming the error there is no syntax highlightning

**Comment by jfcherng** [comment]
It has been claimed fix. Did you try the latest release of ST?

**Comment by Zaby1990** [comment]
thanks for your fast answer.
I uses Build 4126 (installed with scoop) und Win10.
![grafik](https://user-images.githubusercontent.com/47629476/153137172-49b65b61-2504-44e7-97e1-b91f555467d2.png)

**Comment by jfcherng** [comment]
@BenjaminSchaaf it looks like it's the `$$?` conversion issue again.

**Comment by jfcherng** [comment]
Could you try to delete the `%localappdata%\Sublime Text\Cache\DXL\` folder and restart ST?

**Comment by Zaby1990** [comment]
On my system there is no `%localappdata\Sublime Text` directory. I think scoop installed the portable version of sublime text.

**Comment by jfcherng** [comment]
You can run `import shutil; shutil.rmtree(sublime.cache_path() + '/DXL' ,ignore_errors=True)` in the console or manually go to where `sublime.cache_path()` is and delete the `DXL\` folder.

**Comment by Zaby1990** [comment]
found it in `%userprofil%\scoop\apps\sublime-text\4-4126\Data\Cache`

It solved the problem. Thank you.
