### ISSUE TITLE
[JavaScript] possible enhancement: distinguish uses of square brackets

### ISSUE THREAD

**Issue by jcberquist** [sublimehq/Packages#324]
With the addition of the `after-identifier` context, it looks to me like it is possible to distinguish the use of square brackets in a property accessor (or array index) and square brackets used to denote a literal array. Does that seem right? If so, is that something you would be interested in adding?

**Comment by wbond** [comment]
Yes, that seems like a reasonable addition. I'll likely be adding such support to C/C++ and PHP soon also since those are now in better shape for more context-specific enhancements.

**Comment by jcberquist** [comment]
I added a commit that implements this on a basic level: https://github.com/jcberquist/Packages/commit/3240bcb5ea4162e5acc2a4a8c0efbc93adde9088

I didn't create a pull request because I wasn't sure of the scopes you wanted to use, or if this was a satisfactory way to go about it (especially since you plan to do the same in C/C++ and PHP).

**Comment by keith-hall** [comment]
The scoping for this is being discussed here: https://github.com/sublimehq/Packages/issues/790

**Comment by Thom1729** [comment]
Counterexample to jcberquist@3240bcb:

```js
1 /**/ [a]
```
The `[a]` is incorrectly scoped `meta.array-literal.js`. The cause is the same as #885.
