### ISSUE TITLE
[Python] Trailing commas in assignments break highlighting

### ISSUE THREAD

**Issue by FichteFoll** [sublimehq/Packages#3243]
### What happened?

```py
class Test:
    __slots__ = "items",
    
    def func():
        pass
```

![2022-02-23_01-06-15](https://user-images.githubusercontent.com/931051/155240838-b7890b52-415d-4c3d-ba01-a8878d139531.png)

A trailing comma in an assignment implicitly denotes a tuple, so the above would be equivalent to `__slots__= ("items",)`.

**Comment by keith-hall** [comment]
it would be nice if we can scope the comma in such a way as to allow color schemes to highlight it differently than the normal/explicit tuple syntax, to help it stand out :)

**Comment by FichteFoll** [comment]
Imo that would be the job of a linter, since this may also occur during typing `a, b = b, a`, which to me is a fine application of implicit tuple creation and destructoring.

Furthermore, what kind of scope name would be fitting here and, ultimately, which color scheme would target such a scope? I don't see much value in this. Furthermore, we need to check whether `a, *b = a, b, *c` is valid.

**Comment by michaelblyons** [comment]
> Furthermore, what kind of scope name would be fitting here

`invalid.deprecated.well-it-should-be`

**Comment by michaelblyons** [comment]
> > Furthermore, what kind of scope name would be fitting here
> 
> `invalid.deprecated.well-it-should-be`

This actually happened to me yesterday. I was refactoring to change a tuple into an object. I accidentally left a stray `,` in an assignment line, and the member became a tuple. 🤦‍♂️


### Old
```py
return (a, b, c)  # yes, I used explicit parens.
```

### New
```py
class Foo(object):
    def __init__(a, b=None, c=None):
        self.a = a
        self.b = b,  # bug from bad copy-paste
        self.c = c
```
```py
return Foo(a)  # its b is (None,) instead of None
```
