### ISSUE TITLE
[PHP] wrong opening php tag

### ISSUE THREAD

**Issue by Alexey-T** [sublimehq/Packages#3246]
### What happened?

```
<?phpzzz
	echo "test"
?>
```

should not give the OK highlight for "phpzzz" becase "php" must be checked with `\b` on the right.

2) what about `<?PHP` in uppercase? is it valid opening?

**Comment by jfcherng** [comment]
Interestingly, it looks like the official PHP interpreter considers `phpzzz` as a constant since `<?` is a valid php short open tag.

I.e., the following code is valid and run-able.

```php
<?php const phpzzz = 'just a constant'; ?>

<?phpzzz
?>
```
