### ISSUE TITLE
[HTML] "onfocusout" event

### ISSUE THREAD

**Issue by EntityPlantt** [sublimehq/Packages#3248]
### Expected behavior

When having events at HTML elements, we have (for example): `onclick`, `onfocus`, ...
So I expect to have the [`onfocusout`](https://developer.mozilla.org/en-US/docs/Web/API/Element/focusout_event) event, with JavaScript highlighting in it.

### Actual behavior

There isn't an `onfocusout` attribute, neither JavaScript highlights in it.

### Steps to reproduce

1. Go to file [HTML\html_completitions.py](https://github.com/sublimehq/Packages/blob/master/HTML/html_completions.py)
2. Go to line 401
3. Add `, 'onfocusout'` to the end of the line
4. Save, compile & release
![image](https://user-images.githubusercontent.com/92634082/155603507-a990bded-fbc3-47d1-9ca5-3e0444f64ac2.png)

##### Edit
Forgot to add `oncopy` and `onpaste`.
But, `oncopy` and `onpaste` needs to be for the `<input>` HTML tag. Example:
```html
<textarea type="text" name="message" onpaste="formatText(this.value)"></textarea>
```

**Comment by EntityPlantt** [comment]
@deathaxe Forgot to add `oncopy` and `onpaste`. Sorry.
But, `oncopy` and `onpaste` needs to be for the `<input>` HTML tag. Example:
```html
<textarea type="text" name="message" onpaste="formatText(this.value)"></textarea>
```

**Comment by deathaxe** [comment]
Added it to the PR.
