### ISSUE TITLE
[Markdown] Highlight of $$...$$ math blocks

### ISSUE THREAD

**Issue by Alexey-T** [sublimehq/Packages#3251]
### What happened?

1.    Expected two separated highlighted blocks:
```
This is $x_1$ and $y_2$.
```
2.    Expected two separated highlighted blocks:
```
This is $$x_1$$ and $$y_2$$.
```
3.    Expected highlighted as math block:
```
$$
c=\sqrt{a^2+b^2}
$$
```

@cser FYI.

**Comment by Alexey-T** [comment]
now it is no highlight:

![Screenshot from 2022-03-01 16-12-30](https://user-images.githubusercontent.com/4154978/156175206-2bd86a2c-01d8-40e1-a21b-69678c9c3e4c.png)

**Comment by michaelblyons** [comment]
Is this a LaTeX thing?

**Comment by Alexey-T** [comment]
@cser - ?

**Comment by Alexey-T** [comment]
It is extension of markdown - https://stackoverflow.com/questions/17111421/how-to-display-math-equations-in-block-with-markdown

**Comment by deathaxe** [comment]
MarkdownEditing includes it, already. Not sure if we want to add all the different kinds of extensions to the core syntax though.

**Comment by cser** [comment]
![image](https://user-images.githubusercontent.com/655339/156213385-fb1b8de1-be72-48e9-8248-c47d6b2cbfef.png)

For Google Chrome extension "Markdown Viewer" math is optional (mathjax checkbox) - so I don't know how much this is needed in Sublime Text core.

But CudaText main markdown lexer needed this because it hasn't another lexer with math highlighting.

**Comment by jrappen** [comment]
@deathaxe Just to confirm. You said MarkdownEditing supports this, but it doesn't seem to be part of #3167, does it?

**Comment by jrappen** [comment]
@Alexey-T @cser Can you confirm that #3397 fixes the issue described above for you?

**Comment by Alexey-T** [comment]
sorry, but I use ST4 not the last build and don't know how to update the syntax file.

**Comment by FichteFoll** [comment]
See https://github.com/sublimehq/Packages#installation for instructions.

**Comment by Alexey-T** [comment]
I followed the instructions, but I still don't have Markdown package updated when I do 'git clone';
i will wait until PR is merged

**Comment by deathaxe** [comment]
An alternative way might be to just copy content from [Markdown.sublime-syntax](https://raw.githubusercontent.com/sublimehq/Packages/7ec8e28462f9dfa7c8db506fcfda398c1365df6f/Markdown/Markdown.sublime-syntax) into _Packages/Markdown/Markdown.sublime-syntax locally.

**Comment by Alexey-T** [comment]
done it... yes - looks much better.
IMO it's solved.

**Comment by cser** [comment]
> @Alexey-T @cser Can you confirm that #3397 fixes the issue described above for you?

Yes, I confirm
