### ISSUE TITLE
[Python] Wrong scope for boolean keyword arguments in inherited class list 

### ISSUE THREAD

**Issue by jfcherng** [sublimehq/Packages#3252]
### What happened?

For example, the following test should pass.

```py
class EventModifierKeysDict(TypedDict, total=False):
#                                            ^^^^^ constant.language.boolean
    primary: bool
    ctrl: bool
    alt: bool
    altgr: bool
    shift: bool
    super: bool
```

Now it's scoped as `entity.other.inherited-class.python`.

**Comment by FichteFoll** [comment]
It's been an issue for quite a while indeed and I wonder whether it is time to phase our `entity.other.inherited-class.python` for good, but what scope should be used instead? A quicker fix would of course be to match for language constants first here.

**Comment by deathaxe** [comment]
How is the scope name of inherited classes related with the issue of `False` not being matched as boolean constant?
