### ISSUE TITLE
[CSS] poor highlight on this css file

### ISSUE THREAD

**Issue by Alexey-T** [sublimehq/Packages#3258]
### What happened?

CSS snippet
```
@property --light-blue { syntax: '<color>'; inherits: false; initial-value: #ace; }
p { syntax: '<color>'; inherits: false; initial-value: #123; }
```
![css1](https://user-images.githubusercontent.com/4154978/156917931-c95a9cc9-4962-448b-88d6-53d92af2d0eb.png)

the 1st line has poor highlight

- no hilite for `--lite-blue` var
- no hilite for `#ace` color 
- no hilite for `false`
- and for colons

**Comment by Alexey-T** [comment]
2nd file. also has many vars.
```
:root {
  --first-color: #16f;
  --second-color: #ff7;
  --bad1
--good1: #ff7;
bad--too: ttt;
}

#firstParagraph {
  background-color: var(--first-color);
  color: var(--second-color);
}

#container {
  --new-color: #290;
}

#thirdParagraph {
  background-color: var(--second-color);
  color: var(--second-color);
}
```

**Comment by deathaxe** [comment]
ST doesn't traditionally support bleeding edge experimental syntax features which are supported by none or single applications/browsers only.

`@property` is such a feature with regards to https://developer.mozilla.org/en-US/docs/Web/CSS/@property

We might add support when it leaves its `experimental` state.

---

Your second snippet looks good on my end. All but `bad--too` custom properties are properly scoped `entity.other.custom-property`

![grafik](https://user-images.githubusercontent.com/16542113/156918251-790fbb94-82fa-4e0f-87a0-e84bf3201a82.png)

**Comment by michaelblyons** [comment]
In the meantime, the Less or Sass package may help. The shiny experimental CSS features seem to often come from SCSS and whatever Less calls them.
