### ISSUE TITLE
Typescript / tsx generic component syntax problem

### ISSUE THREAD

**Issue by bs85** [sublimehq/Packages#3267]
### Description of the bug

Supplying generic type arguments within JSX is not intepreted correctly, causing incorrect syntax highlighting.

Without type arguments:
![image](https://user-images.githubusercontent.com/3041431/158030227-a49a7429-8954-40ee-bf1d-185f7a296050.png)

WIth explicit type arguments:
![image](https://user-images.githubusercontent.com/3041431/158030260-e1ec1003-83b9-4367-a891-33eab7fe781c.png)

### Steps to reproduce

1. Start ST in safe mode
2. Set syntax highlighting to Javascript -> Tsx
3. Paste the following (valid) code

```
function GenericComponent<T>(props: React.PropsWithChildren<{ prop: T }>) {
  return <>{props.prop}</>
}

<GenericComponent<string> prop={'value'}>

</GenericComponent>
```

### Expected behavior

`<GenericComponent>` gets the component highlighting

### Actual behavior

`<GenericComponent>` gets strange colors, which vary depending on the context

### Sublime Text build number

4126

### Operating system & version

Ubuntu 18

### (Linux) Desktop environment and/or window manager

Gnome

**Comment by deathaxe** [comment]
Closing it, as it is already resolved in this repo. Hopefully will be shipped with one of the next ST dev builts.

**Comment by bs85** [comment]
Cheers!
