### ISSUE TITLE
[JavaScript] TypeScript type casting with <>

### ISSUE THREAD

**Issue by monkape** [sublimehq/Packages#3283]
### What happened?

Casting "twice" with `<>` operator breaks syntax highlighting. Using `as` to cast works as expected.

Expected behaviour
```ts
let a = 10
;<any>(<any>a)
let b = 10
```

Actual behaviour
![Screenshot from 2022-03-22 10-38-08](https://user-images.githubusercontent.com/23129307/159451146-db8f958c-7ddd-4b24-bade-dea4a82397c4.png)

**Comment by monkape** [comment]
It's the `;` and `()` that are causing problems as this one works:

```ts
let a = 10
<any>(<any>a).b
let b = 10
```

But these don't:

```ts
let a = 10
(<any>(<any>a).b)
let b = 10
```

```ts
let a = 10
;<any>(<any>a).b
let b = 10
```

```ts
let a = 10
;(<any>(<any>a).b)
let b = 10
```

**Comment by Thom1729** [comment]
Thanks for the report. It turned out to be a simple mistake in the type assertion code. The linked PR should fix it.

**Comment by Thom1729** [comment]
(I'm not generally a fan of the “StandardJS” style, but it sure is good at finding syntax corner cases.)
