### ISSUE TITLE
[3111] #ifdef inside C functions is breaking the parser

### ISSUE THREAD

**Issue by MarcoNovaro** [sublimehq/Packages#329]
Some #ifdef inside C functions is breaking the parser (and the syntax highlight). For instance, this is a test case showing the problem: the first function is correctly highlighted, the second one is not (as it is recognized as a `meta.function-call.c`.

    static void MCU_SetSysClock()
    {
        #define THIS_IS_FINE        55

        /* PLL prescalers configuration settings */
    #if( EXTAL == 40000 )                       /* 40 MHz */

        #if( PLL_0_CLOCK == 200000 )
            #define PLL_MFD         40
            #define PLL_PREDIV      4
            #define PLL_RFD_PHI     2
            #define PLL_RFD_PHI1    10      // PLL0_PH1 = 40MHz
        #else
            #error "Unsupported PLL0 clock frequency (PLL_0_CLOCK)"
        #endif

        /* Note: configuration below assumes use of PLL0_PH1 @40MHz as reference */
        #if( PLL_1_CLOCK == 260000 )
            #define PLL_1_MFD       26
            #define PLL_1_RFD_PHI   2

            /* Progressive clock switching values (ref. MPC5777M_PCS.xlsx) */
            #define PCS_SDUR_VAL    0x10
            #define PCS_PLL1_RATE   0x30
            #define PCS_PLL1_INIT   0x4DF
            #define PCS_PLL1_DIVE   0x3F79
            #define PCS_PLL1_DIVS   0x45B7

        #else
            #error "Unsupported PLL1 clock frequency (PLL_1_CLOCK)"
        #endif

    #else

        #error "Unsupported oscillator frequency (EXTAL)"

    #endif

        /* Other code here */
        return;

    } /* MCU_SetSysClock */

    static void MCU_InitCache(void)
    {

    }

**Comment by keith-hall** [comment]
a bit more info on this test case is available here: https://forum.sublimetext.com/t/bug-3111-c-called-functions-not-highlighted-correctly/19521/10

**Comment by wbond** [comment]
This is fixed by 4f5120bf1233b95e993f9bdaf2334f22de21e916.

Thanks for reporting the issue!
