### ISSUE TITLE
[Turtle] Does not recognize RDF-star syntax

### ISSUE THREAD

**Issue by cheligon** [sublimehq/Packages#3298]
### What happened?

RDF-star and associated Turtle-star syntax are not recognized properly in Sublime, notably the quoted triple "<< pre:post pre:post pre:post>> pre:post pre:post . See  https://w3c.github.io/rdf-star/cg-spec/editors_draft.html#turtle-star-ebnf 

Exemple:
@prefix dcterms: <http://purl.org/dc/terms/#>.
@prefix xsd: <http://www.w3.org/2001/XMLSchema#>.
@prefix eco: <http://purl.obolibrary.org/obo/ECO_>.
@prefix ro: <http://purl.obolibrary.org/obo/RO_>.

<<eco:6239 dcterms:version "283">> dcterms:date "2022-03-30"^^xsd:date . 
<<eco:0006818 ro:0002332 eco:0003167>> eco:000628 eco:000003092 .

-------------------------
In the previous example:
. the quotes "<<" are not well displayed, the first "<" is white, the second "<" is red. They should be one object.
. A red full box is displayed between eco:6239 and dcterms:version, it should only display a space.
. The ">>" is displayed in red full boxes when preceeded by a " as it is not the case in the last lane.

**Comment by jfcherng** [comment]
For what it worth, you are talking about a 3rd-party plugin: https://packagecontrol.io/packages/Turtle%20RDF%20Syntax

I mean wrong repo to report your issue. https://github.com/e-e-e/sublime-turtle-syntax
