### ISSUE TITLE
[Perl] Missing Postscript include

### ISSUE THREAD

**Issue by wbond** [sublimehq/Packages#330]
Perl tries to include Postscript, but it is not currently included.

**Comment by Briles** [comment]
I've begun working on a PostScript syntax but before I continue I wanted to check in and see if introducing a new syntax was the solution you had in mind.

**Comment by wbond** [comment]
I removed Postfix as an include in Perl for now with a493e90787e876d4f221e2bf621b47cb3505b99a.

@Briles I think that for now publishing it via Package Control is probably the right answer.
