### ISSUE TITLE
[HTML/XML] Unify CDATA scope tags

### ISSUE THREAD

**Issue by michaelblyons** [sublimehq/Packages#3305]
### What happened?

Can you make it easier for color schemes to target the open/close tags and the content of CDATA? HTML and XML have slightly divergent scopes, which leads to a rather ugly rule in my color defs.

**Comment by michaelblyons** [comment]
The rule in question looks like this:

```jsonc
{
    "name": "CDATA punctuation",
    "scope": "(meta.tag.cdata | meta.tag.sgml.cdata) & (entity.name.tag.cdata | punctuation.definition.tag.begin | punctuation.definition.tag.end | keyword.declaration.cdata)",
    "foreground": "var(white4)",
    "font_style": "",
},
```

to get 

<img width="149" alt="Screen Shot 2022-04-02 at 12 20 56 PM" src="https://user-images.githubusercontent.com/2701605/161391928-8c79d089-0f35-496b-bd29-04e4e94fce25.png">

(I'm now considering making the tag punctuation comment-colored and the contents normal-foreground colored, but the same principle holds true.)

**Comment by deathaxe** [comment]
Not sure which XML syntax you use, but the default ones shipped with ST both are totally identical.

### HTML

https://github.com/sublimehq/Packages/blob/886f8b6ef045c0397e79b6654e735244f9dea4c9/HTML/HTML%20(Plain).sublime-syntax#L101-L116

### XML

https://github.com/sublimehq/Packages/blob/886f8b6ef045c0397e79b6654e735244f9dea4c9/XML/XML.sublime-syntax#L154-L170

Note, that PackageDev and maybe other inherited syntaxes may provide other scopes. `meta.tag.sgml` was choosen as this was a scope used for all `<!...` like tags in XML.

`keyword.declaration` is used as this is the proper scope for all `<!DOCTYPE`, `<!ENTITY` directives in DTD.

**Comment by michaelblyons** [comment]
My mistake. Thank you.
