### ISSUE TITLE
[Diff] Add support for comparing two buffers

### ISSUE THREAD

**Issue by keith-hall** [sublimehq/Packages#3313]
### Expected behavior

Currently it is possible to compare two files which exist on disk by selecting them in the sidebar and selecting "Diff Files..."
But there is no way to compare the contents of two tabs (which may or may not be saved / exist on disk etc.).

Ideally, having two tabs multi-selected and opening the tab context menu should show a "Diff Tabs..." option.
Having one tab selected and right-clicking on another tab should show a "Diff with current tab..." option.

### Actual behavior

Have to save the files before comparing them.

### Steps to reproduce

1. Open a tab, paste some text
2. Open another tab, paste some similar text
3. Right click the first tab and there's no option to "Diff with current tab..."

**Comment by deathaxe** [comment]
How about https://packagecontrol.io/packages/EasyDiff?

**Comment by keith-hall** [comment]
Will give that a try, thanks. My main reasoning for opening this issue is that I believe it should be built-in, as we have built-in support for diffing *files*, just not *tabs/buffers* :)

Meanwhile I shared the solution I use in case SublimeHQ would be interested. https://github.com/sublimehq/Packages/pull/3315

**Comment by deathaxe** [comment]
Agree. I'd however prefer a solution which uses something like the diff view used by SM.
