### ISSUE TITLE
[Java] Generics scope changed from punctuation.definition.generic to punctuation.section.generic

### ISSUE THREAD

**Issue by Flaze07** [sublimehq/Packages#3327]
### What happened?

The syntax highlighting for a generic type failed. The generic bracket should have had a color instead of just white. However, it managed to work when it's in a block comment

![java sublime text screenshot](https://user-images.githubusercontent.com/12490480/163079133-8b1c5696-cf45-49fc-9fd9-2e99a1a5b031.png)

the file contains just the following code:
[code]
```Java
package com.aetherwars.model;

import java.util.*;

class IllegalCardPlacementException extends Exception {
	public IllegalCardPlacementException(String str) {
		super(str);
	}
}

/**
 * assumption that there'll be two board
 * variable in main
 */
public class Board extends Container {
	public Board() {
		cards = new ArrayList<Card>();

		/**
		 * using null to say initialize the cards variable
		 * null is used to denote that the cards are empty
		 */
		for(int i = 0; i < 5; ++i) {
			cards.push(null);
		}
	}

	/**
	 * set card to a specific location in board
	 */

	public void setCard(Card card, int index) {
		/**
		 * if the card type is spell card,
		 * checks if there're Character type card in the
		 * board, and throws if there's none
		 */
		if(card.getType() == CardType.SPELL) {
			boolean hasCharacter = false;
			for(int i = 0; i < cards.size(); ++i) {
				if(cards.get(i).getType() == CardType.CHARACTER) {
					hasCharacter = true;
					break;
				}
			}
			if(!hasCharacter) {
				throw new IllegalCardPlacementException("Placing Spell card when there's no character");
			}
		}
		cards.set(index, card);
	}	

	/**
	 * destroy card at a location at i
	 * by setting to null
	 */
	public void destroyCard(int index) {
		cards.set(index, null);
	}
}
```

**Comment by jwortmann** [comment]
While @deathaxe's answer above gives a good explanation, there might be a bit of confusion about the used scope name for the angle brackets of generic types. The [scope naming guidelines](https://www.sublimetext.com/docs/scope_naming.html#meta) explicitly describe to use `punctuation.definition` for the angle brackets, which would be blue in Mariana, and not `punctuation.section` (white in Mariana).

![scope](https://user-images.githubusercontent.com/6579999/163249402-b66b5924-fc13-48dd-89d5-7afbc2e45cea.png)

But the guidelines are not really known to be super up-to-date, and most syntaxes use the `punctuation.section` scope. Two exceptions which still follow the guidelines are [C#](https://github.com/sublimehq/Packages/blob/5d23044ce2ec37f3d6ad3b015070e728b5a5ef58/C%23/tests/syntax_test_c%23.cs#L88) and [Scala](https://github.com/sublimehq/Packages/blob/5d23044ce2ec37f3d6ad3b015070e728b5a5ef58/Scala/syntax_test_scala.scala#L765), as well as did the Java syntax before your rewrite. Therefore the color for the angle brackets in Mariana might change if you switch between syntaxes or in Java from ST3 to ST4.

I guess the (historic?) reason against `punctuation.section` would be that the generic type between the brackets is usually only a single word, and not an entire code section like it is often the case for e.g. squiggly braces pairs.

However, I would vote to update the scopes in C# and Scala to `punctuation.section`, which is commonly used for all bracket types. And ideally the scope naming guidelines should be updated from a SublimeHQ member too, with the latest conventions established over the recent months/years to avoid confusion for new syntax developers.

**Comment by deathaxe** [comment]
TBH, I've not really been aware of `definition` being used here. But I have this rule about everything containing expressions to be called scoped `section`. With the following example being valid code, I find "generics patterns" some kind of expression, especially as they even allow logical combination and chainig, very much like normal expression groups do.


```java
class GenericTest<A> extends @Anno com . @Anno Foo<@Anno ? extends @Anno SuperClass . @Anno SubClass & @Anno OtherClass>, @Anno OuterClass {}
```
