### ISSUE TITLE
[Go] Syntax Highlighting Doesn't Work With Channels in Function Signatures

### ISSUE THREAD

**Issue by stevekuznetsov** [sublimehq/Packages#335]
![chanstruct](https://cloud.githubusercontent.com/assets/7328370/14921612/0f0202be-0e01-11e6-8441-f6e1da98a356.png)

I am using Sublime 3103

**Comment by wbond** [comment]
Thanks for the report. I'll get it fixed up shortly.

**Comment by stevekuznetsov** [comment]
Are your latest changes released in a build? I am running an older version

**Comment by wbond** [comment]
No, dev build 3112 hasn't come out yet. You can get them by following the instructions in the readme of this repo.

**Comment by stevekuznetsov** [comment]
The highlighting works until the braces at 
```
<- chan struct{}
              ^
```
are added. I don't have the bandwidth to update to a release candidate just now, sorry!

**Comment by wbond** [comment]
Oh, so this is with the old version of the syntax?

**Comment by wbond** [comment]
Actually, the most useful thing you can do is provide the literal code, as opposed to a screenshot. Then I can just copy-paste and create a test out of it.

**Comment by stevekuznetsov** [comment]
Let me write up a minimal working example. I'm on Sublime 3103.

**Comment by wbond** [comment]
Yeah, I've basically rewritten the syntax since 3103.

**Comment by stevekuznetsov** [comment]
Minimal example:
```go
package main

type Foo struct{}

func (f *Foo) Go(arg <-chan struct{}) {}
```

Notes:
 - as noted above, highlighting breaks at the addition of the braces at `...struct{}`
 - without a `struct` receiver, highlighting works fine.

**Comment by wbond** [comment]
Here is what it looks like now:

<img width="379" alt="screen shot 2016-04-29 at 12 01 09 pm" src="https://cloud.githubusercontent.com/assets/41734/14921815/2018a9d0-0e02-11e6-8794-26ca161aac99.png">

**Comment by stevekuznetsov** [comment]
Awesome :)

**Comment by wbond** [comment]
Yes, the old Go syntax was… rough

**Comment by stevekuznetsov** [comment]
I'm glad you've made the improvements!

**Comment by wbond** [comment]
Goto Definition and Goto Symbol are now far more useful since it picks up all different types.
