### ISSUE TITLE
Label highlight issue

### ISSUE THREAD

**Issue by rarodja** [sublimehq/Packages#3350]
### What happened?

When you work with html syntax, the tags beyond "class", such as "style", are not highlighted for example in green like the others with the Mariana theme:

![Mariana](https://user-images.githubusercontent.com/74628132/164776315-854fb75b-d6c3-4cbf-a420-c31b8c0cc62b.png)

I think it should be all highlighted in green in this case like the others.

P.D. Is it possible to change the `<?php` and `?>` color tags so that they are not blank and the highlighting is better seen?

Thank you very much.

**Comment by deathaxe** [comment]
That's working as expected and won't be changed.

- `style` attribute values are highlighted using CSS (`source.css`) syntax. 
- `onclick` etc. attribute values are highlighted using JavaScript (`source.js`) syntax.

The colors for all those embedded syntaxes' tokens are specified by color scheme. Syntax definitions of this package just specify scope names which can be used to define highlighting.

If you don't want embedded syntaxes such as CSS/JSON/JS to be highlighted you could try _HTML (Plain)_ instead. Won't work with PHP though.

PHP tags (`<?php`)  are scoped `punctuation.section.embedded` and can be tinted by color schemes in any desired color. 

also see: https://www.sublimetext.com/docs/color_schemes.html

**Comment by michaelblyons** [comment]
@rarodja I will suggest to you a color scheme tweak that I've found very helpful: tinting the background color for `text source` (and optionally `source source`). It will make sections using a different language stand out substantially.
