### ISSUE TITLE
[Go] Struct Member Function Signatures Don't Highlight Correctly

### ISSUE THREAD

**Issue by stevekuznetsov** [sublimehq/Packages#336]
Seen here:
![funcs](https://cloud.githubusercontent.com/assets/7328370/14923637/4327b3e4-0e0c-11e6-8bf1-649e89070018.png)

Code:
```go
package main

type FuncContainer struct {
	FirstFunc  func(arg string)
	SecondFunc func(arg string)
}

type FuncContainer struct {
	FirstFunc   func(arg string)
	SecondFunc  func(arg interface{})
	SeventhFunc func(arg string)
}

type FuncContainer struct {
	FirstFunc  func(arg string)
	SecondFunc func(arg interface{})
	ThirdFunc  func(arg string)
}
```

As seen on the last two examples, the level of indentation seems to matter somehow.

Seen on Sublime 3103

/cc @wbond hopefully this is also fixed in the new patch!

**Comment by stevekuznetsov** [comment]
Interestingly enough the GitHub syntax highlighting seems to suffer from the same bug!

**Comment by wbond** [comment]
This is in better shape in the new version, but can still be improved some (the `func` should be highlighted). Here is what we have now.

<img width="287" alt="screen shot 2016-04-29 at 1 17 59 pm" src="https://cloud.githubusercontent.com/assets/41734/14923773/18733e2e-0e0d-11e6-95fb-91ffa32df864.png">

Depending on what color scheme you are using, the struct name and fields are highlighted.

The tmLanguage file that Sublime used before is likely used by GitHub. There are a number of bugs we've fixed that have shown up in the GitHub fenced code blocks.

**Comment by wbond** [comment]
This has been further improved in 1c8d6605ebcd58b3df5cb0ef513b3f570605cce8
