### ISSUE TITLE
Rmd vertical pipe, then curly brace, then underscore leads to red bar under code

### ISSUE THREAD

**Issue by pdbailey0** [sublimehq/Packages#3360]
### What happened?

I'm writing an .Rmd and this code is marked as not correctly formatted (a red bar appears beneath it).
```
\begin{align}
|{Y}_i
\end{align}
```
<img width="114" alt="image" src="https://user-images.githubusercontent.com/14575300/165860900-6b0964de-8e2f-4d12-b466-f92222d7371d.png">

This is a MWE, so no, I have no need to put Y in curly braces, but I may want to style it or use curly braces for any of a variety of LaTeX objects. And the vertical pipe (|) character also doesn't make sense here, but I may want to do something like this where it shows up as well:

```
\begin{align}
X|{\rm Y}_i \sim N(0,1)
\end{align}
```

**Comment by jwortmann** [comment]
Your code examples seem to work fine for me with the built-in LaTeX syntax.

![Unbenannt](https://user-images.githubusercontent.com/6579999/165862207-d687b5da-e2ab-4e0f-9fdb-e22d1335faab.png)

Assuming .Rmd stands for R Markdown, you would need to file this report at the issue tracker of the package which provides that syntax.

**Comment by michaelblyons** [comment]
I am not familiar with Rmd. Your code looks kind of like LaTeX. Is that what you're choosing as the highlight language? That looks fine for me.

<img width="115" alt="Screen Shot 2022-04-28 at 7 13 23 PM" src="https://user-images.githubusercontent.com/2701605/165862422-f9cd50d6-bc3f-4e3d-90ac-93718e0dc9b0.png">

**Comment by deathaxe** [comment]
Closing as it is no issue related to this repo.
