### ISSUE TITLE
[C++] Last enum constant is not highlighted / indexed if not followed by comma or equal sign

### ISSUE THREAD

**Issue by sfc-gh-mjendruk** [sublimehq/Packages#3369]
### What happened?

The new enumeration constant indexing is broken for the last value if it is on its own line followed neither by a comma nor equal sign.

```c++
enum class MyEnum {
    ONE,
/*  ^ entity.name.constant.c++ */
    TWO,
/*  ^ entity.name.constant.c++ */
    THREE
/*  ^ this should be entity.name.constant.c++ too but isn't */
};
```

I noticed that it is because of the macro-style uppercase naming. Camel case like below works. 

```c++
enum class MyEnum {
    One,
/*  ^ entity.name.constant.c++ */
    Two,
/*  ^ entity.name.constant.c++ */
    Three
/*  ^ entity.name.constant.c++ */
};
```

Introduced in: https://github.com/sublimehq/Packages/pull/3299

**Comment by deathaxe** [comment]
`THREE` has been scoped as macro before #3299, too. It just wasn't that obvious as the other members haven't been scoped at all.
