### ISSUE TITLE
[PHP] The SQL keywords `WITH` is not recognized a valid SQL. 

### ISSUE THREAD

**Issue by Luuk34** [sublimehq/Packages#3375]
### What happened?

The string is not formatted as SQL 

```
<?php

$sql = "WITH RECURSIVE cte as (
            SELECT 1 as x
            UNION ALL
            SELECT x+1 FROM cte WHERE x<10)
        SELECT * FROM cte;";
```

When using a string that starts with `SELECT` then syntax coloring is working, as expected, but with the keyword `WITH` it stops working.

        
This bug-report was caused by this (stackoverflow)question: [How to make PHP handeling my "WITH CTE as" SQL?](https://stackoverflow.com/questions/72158928/how-to-make-php-handeling-my-with-cte-as-sql)

**Comment by jfcherng** [comment]
and `DROP` btw. I am used to add `DROP` for my own.

**Comment by deathaxe** [comment]
Maybe sync with Python.
