### ISSUE TITLE
Syntax highlighting bash: HERE delimiter turns rest of the script green

### ISSUE THREAD

**Issue by sbo79** [sublimehq/Packages#3380]
### What happened?

```
  elif [[ $TYPE -eq "remote" ]]; then
    #                                                               TODO
    ssh -q -p $TARGETPORT $TARGETUSER@$TARGETDOMAIN << HERE
      cd /backup
      ./waitandlock.sh
      ./backup.sh -t=backup --mount
    HERE


  elif [[ $TYPE -eq "timecapsule" ]]; then
    #                                                               TODO
    ARCHIVENAME=
```
everthing is highlighted correct till the ... << DELIMITER directive. The code within the block is green. The block ends at the DELIMITER (in the example above the delimiter is HERE). After this block I expect regular highlighting, but everthing remains green till end of the file.

**Comment by jfcherng** [comment]
![image](https://user-images.githubusercontent.com/6594915/168191900-80ae3c8f-6437-4d39-93c2-0ed06485df2e.png)
