### ISSUE TITLE
[JavaScript] TypeScript syntax breaks after method parsing

### ISSUE THREAD

**Issue by rwols** [sublimehq/Packages#3384]
### What happened?

Apologies for the vague title. I can't pin down the problem any better as I don't know much of TypeScript, nor its sublime-syntax.

In the below snippet, the function `fromPartial` causes the rest of the code to not be highlighted.

```ts
export const SearchRequest = {

  toJSON(message: SearchRequest): unknown {
    const obj: any = {};
    message.query !== undefined && (obj.query = message.query);
    message.pageNumber !== undefined &&
      (obj.pageNumber = Math.round(message.pageNumber));
    message.resultPerPage !== undefined &&
      (obj.resultPerPage = Math.round(message.resultPerPage));
    return obj;
  },

  fromPartial<I extends Exact<DeepPartial<SearchRequest>, I>>(object: I): SearchRequest {
    const message = createBaseSearchRequest();
    message.query = object.query ?? "";
    message.pageNumber = object.pageNumber ?? 0;
    message.resultPerPage = object.resultPerPage ?? 0;
    return message;
  },
};
```

<img width="648" alt="image" src="https://user-images.githubusercontent.com/2431823/168494315-779630fb-8b83-42aa-8a9e-9a1e05fe99c8.png">

This code was generated from a protobuf file with the following content

```protobuf
syntax = "proto3";

message SearchRequest {
  string query = 1;
  int32 page_number = 2;
  int32 result_per_page = 3;
}
```

Using this protobuf compiler plugin: https://github.com/stephenh/ts-proto

Invoked like this:

```
protoc --proto_path=. --proto_path=/usr/local/include/google/protobuf --plugin=../ts-proto/protoc-gen-ts_proto --ts_proto_out=. api.proto --ts_proto_opt=esModuleInterop=true
```

**Comment by michaelblyons** [comment]
Breaks for me slightly differently, and does not kill later highlighting. Interestingly, commenting out `toJSON()` doesn't make a difference. @rwols Are you sure the text you've included matches your screenshot?

<img width="733" alt="Screen Shot 2022-05-15 at 6 56 18 PM" src="https://user-images.githubusercontent.com/2701605/168497470-11338cfc-baaf-4c57-9c9e-35edae87a760.png">

**Comment by Thom1729** [comment]
I'm sure it's some weird branching case in the second method type
parameters.

**Comment by Thom1729** [comment]
Actually, it looks like generic methods in object literals don't work at all.

**Comment by Thom1729** [comment]
Should be fixed. Thankfully it didn't turn out to be a hard problem.
