### ISSUE TITLE
[YAML] Explicit mappings are not terminated properly

### ISSUE THREAD

**Issue by FichteFoll** [sublimehq/Packages#3395]
### What happened?

Sets in yaml are specified using a mapping with no values for the keys, which is easily accomplished in a multi-line layout of prefixing the items with an explicit key indicator `?`. However, the `meta.mapping.key` scope is not properly terminated.

```yaml
set: !!set
  ? this
  ? is
  ? a
  ? set

list:
  - this
  - is
  - a
  - list
```

![2022-05-20_16-17-17](https://user-images.githubusercontent.com/931051/169548291-dbd47ac7-0e70-4867-bbd1-ef3a712d2bde.png)

~~The same can also be observed when there are values for the keys~~
**Edit**: The following is actually correct behavior! I even added a test for it and then forgot about the behavior.

```yaml
map:
  ? this: value
  ? is: value
  ? a: value
  ? set: value
```

![2022-05-20_16-23-09](https://user-images.githubusercontent.com/931051/169548658-d1bb3d04-fac9-45be-88b2-382103b2ce39.png)

Likely a regression from #2564.

**Comment by deathaxe** [comment]
It appears at least some of those issues have existed before, already, but haven't been that obvious due to `meta.mapping.key` not being present.

There's even a test case for explicit keys not being followed by values in the same line (related with: your second screenshot)

https://github.com/sublimehq/Packages/blob/9e35426d39030880ddf952caab000ec7a5eadf24/YAML/tests/syntax_test_block.yaml#L130-L135

**Comment by deathaxe** [comment]
Also found:

![grafik](https://user-images.githubusercontent.com/16542113/169645954-3025949f-0fe8-4e14-86d3-afa2869aa58e.png)

from: https://perlpunk.github.io/slides.tpcia2017/the-state-of-the-yaml/slide026.html

**Comment by FichteFoll** [comment]
> There's even a test case for explicit keys not being followed by values in the same line (related with: your second screenshot)

Right, I totally forgot about that. With a line break before the colon, this example works correct (as we also have tests for that. However, empty/missing values are seemingly not supported. I only recently learned about this syntax for sets (never used it before) and thus didn't consider it during development of the syntax.
