### ISSUE TITLE
[PHP] Regression: short arrow functions with return types scoped/highlighted incorrectly

### ISSUE THREAD

**Issue by bakerkretzmar** [sublimehq/Packages#3407]
### What happened?

Since build 4134, PHP short arrow functions with return types are not scoped properly. I haven't dug into the scopes for every different part of the short arrow syntax yet, but it appears to affect the `fn` keyword, the arguments passed to the function, the return type of the function, and sometimes `)` characters following the function.

I would guess these come from #3331. I'll look into a fix but someone more familiar with the new syntax definition (@deathaxe 👀) might be able to find the issue faster.

Demo in safe mode:

<img width="1315" alt="Screen Shot 2022-05-28 at 8 25 26 PM" src="https://user-images.githubusercontent.com/18192441/170847005-d3892896-ea0c-4c5e-8e44-91a254fd517b.png">

**Comment by michaelblyons** [comment]
Excellent bug report. Can you paste the code into the issue, so it doesn't need to be transcribed from your screenshot? GitHub code fences can indicate language:

````markdown
```php
# code here
```
````

**Comment by bakerkretzmar** [comment]
Yep my bad. Working on a fix now too, looks pretty simple actually.

```php
<?php

use Carbon\CarbonImmutable;

// Looks right
$func = function ($value): ?CarbonImmutable {
	$value ? CarbonImmutable::parse($value) : null;
}

// Looks right
$fn = fn ($value) => $value ? CarbonImmutable::parse($value) : null;


// `fn`, `$value`, and `?CarbonImmutable` highlighted wrong
$fn = fn ($value): ?CarbonImmutable => $value ? CarbonImmutable::parse($value) : null;

// still wrong without nullable return
$fn = fn ($value): CarbonImmutable => CarbonImmutable::parse($value);

// still wrong with nullable native/scalar type
$fn = fn ($value): ?bool => $value ? true : null;

// return type looks right but `fn` and `$value` still wrong
$fn = fn ($value): bool => true;


$wrap = fn ($value) => $value;


// next `)` after a `fn (): ...` scoped with invalid.illegal.stray.php
$wrapped = $wrap(fn ($value): ?CarbonImmutable => $value ? CarbonImmutable::parse($value) : null);
```
