### ISSUE TITLE
[JavaScript] Folded symbols disappear in some cases

### ISSUE THREAD

**Issue by maboloshi** [sublimehq/Packages#3429]
### What happened?

Folding symbols disappear
![image](https://user-images.githubusercontent.com/7850715/173975322-ebb9a112-a9b0-4af1-92a7-2e9aa37d3f11.png)
![image](https://user-images.githubusercontent.com/7850715/173975585-7698073d-7990-4381-bdea-7e714c633b96.png)

SC ST4126: No problem
DC ST4134: Exist

**Comment by jfcherng** [comment]
Interestingly, if you manually run the folding comment, it still folds.

**Comment by maboloshi** [comment]
I tried shortcuts and menus but could not collapse the commented code blocks.

ST4126:
![image](https://user-images.githubusercontent.com/7850715/173981913-3a67fafe-14e6-461d-825c-758f9098bb85.png)

ST4134:
![image](https://user-images.githubusercontent.com/7850715/173982026-8c2246fb-f526-4adc-b888-5708eea4823d.png)

**Comment by jfcherng** [comment]
![image](https://user-images.githubusercontent.com/6594915/173989854-73e387dc-9804-45e2-8306-b8222c2dec1c.png)

This is what I get after doing `ctrl+shift+[` on the block comment.
