### ISSUE TITLE
[Scala] Jumping to `val`s no longer works

### ISSUE THREAD

**Issue by djspiewak** [sublimehq/Packages#3433]
### Expected behavior

Hit `Cmd-Shift-R` and type the name of a `val`. I would expect the results to contain the symbol.

### Actual behavior

The results only include `def`s, `class`es, `trait`s, `type`s, and `object`s, but no `val`s.

Sublime Text takes the prescriptive line that *fields* of classes should not be returned in global symbol results (only local, within the buffer). This makes a lot of sense in languages like Python, Java, and C++, but applying this semantic to Scala represents a misunderstanding of what `val` is in Scala.

`val` and `def` are the same construct, and even compile to nearly the same bytecode. The only two differences are that `def` may take parameters and is evaluated on demand, while `val` cannot take parameters and evaluated eagerly. But beyond that, the following two classes are almost the same:

```scala
class A {
  def foo = 42
}

class B {
  val foo = 42
}
```

To make matters even more confusing, it is possible to replace a `def` with a `val` (and often vice-versa) when overriding inherited members, or simply when refactoring code! In other words, `val` and `def` are used interchangeably, and there is no meaningful difference between them. Thus, the fact that Sublime Text indexes `def`s but not `val`s is a pretty serious oversight. It is also a regression from the previous behavior, where it *did* index `val`s.

Note that Scala has an additional construct, `var`, which is much closer to a conventional object oriented field, and Sublime Text is generally correct to not index it (though I can see arguments in both directions).

### Steps to reproduce

See above.

**Comment by djspiewak** [comment]
To make a slightly more concrete example btw, consider the following three:

```scala
// scala
class A {
  val foo: Int = 42
}
```

```java
// java
public class A {
  public final int foo = 42;
}
```

```haskell
-- haskell
foo :: Int
foo = 42
```

It is tempting to liken the Scala `foo` to the Java one (which is not indexed), but it is actually much closer to the Haskell `foo` (which *is* indexed, and correctly so).

**Comment by deathaxe** [comment]
Seems to work in ST 4134. Both the function and constant are indexed and accessible via _Goto Symbol in Project_.

![grafik](https://user-images.githubusercontent.com/16542113/174459234-f9e9d3c1-b1f1-4c55-97f0-b74266658d33.png)

Related `variable.other.constant` scope is part of indexed symbols.

See: https://github.com/sublimehq/Packages/blob/43d77b2b8ed4c946a7188ae0775a510034e6c29e/Scala/Symbol%20List.tmPreferences#L10

I am not very confident whether that's correct for all of them though. I wouldn't expect `thing` or `other`to be indexed as symbol definition in following expression for instance:

https://github.com/sublimehq/Packages/blob/43d77b2b8ed4c946a7188ae0775a510034e6c29e/Scala/syntax_test_scala.scala#L1255-L1257

**Comment by djspiewak** [comment]
> I wouldn't expect thing or other to be indexed as symbol definition in following expression for instance:

Neither would I. Hmm. I'll check and see if I can figure out what's going on locally...

**Comment by deathaxe** [comment]
Closing this as goto definition and goto reference are working as expected in SAFE MODE.
