### ISSUE TITLE
[C] The last function argument highlighting

### ISSUE THREAD

**Issue by codemeow** [sublimehq/Packages#3437]
### What happened?

The last function argument is highlighted wrong if the closing parentheses is placed on the line after the last argument
```c
void function(
    type arg1,
    type arg2,
    type arg3
) {
  ///
}
```
![Снимок экрана_2022-06-20_16-37-22](https://user-images.githubusercontent.com/5464720/174613930-9f255163-dc6e-4b9a-ae3e-1084320ff999.png)

**Comment by jfcherng** [comment]
duplicate of https://github.com/sublimehq/Packages/issues/1070
