### ISSUE TITLE
text 3 cannot recognize function correctly

### ISSUE THREAD

**Issue by crystalYY** [sublimehq/Packages#344]
when the codes like this , cannot recognize `randomBuildData` as a  function type,just like the picture below.
![这里写图片描述](https://segmentfault.com/img/bVvgPp)
And when you edit ,the prompt will show like this
![这里写图片描述](https://segmentfault.com/img/bVvgPw)
However,when the codes  like this , it can recognize   `randomBuildData` as  a function type
![这里写图片描述](https://segmentfault.com/img/bVvkEu)
And when you edit ,the prompt will show like this
![这里写图片描述](https://segmentfault.com/img/bVvgRX)

why and thanks.

**Comment by wbond** [comment]
What syntax are you using, and what version of Sublime Text are you using?

**Comment by crystalYY** [comment]
the syntax is javaScript,and the version is Sublime Text 3

**Comment by wbond** [comment]
Can you paste the actual code into a fenced code block so I can copy and paste?

Also, what build of Sublime Text 3 are you using? There have been significant changed since build 3103.

**Comment by crystalYY** [comment]
OK,I am sorry. My Sublime Text 3'build is 3095.
`
	
		function getDateStr(dat) {
		  var y = dat.getFullYear();
		  var m = dat.getMonth() + 1;
		  m = m < 10 ? '0' + m : m;
		  var d = dat.getDate();
		  d = d < 10 ? '0' + d : d;
		  return y + '-' + m + '-' + d;
		}
		function randomBuildData(seed) {
		  var returnData = {};
		  var dat = new Date("2016-01-01");
		  var datStr = '';
		  for (var i = 1; i < 92; i++) {
		    datStr = getDateStr(dat);
		    returnData[datStr] = Math.ceil(Math.random() * seed);
		    dat.setDate(dat.getDate() + 1);
		  }
		  return returnData;
		}

`
getDateStr and randomBuildData are both function type,but when you want use randomBuildData, 

the code prompt will not recognize the randomBuildData as a function,just as a generic variable.

However, if you delete the getDateStr function totally ,the code prompt can recognize the 

randomBuildData as a function correctly.

**Comment by wbond** [comment]
The latest dev builds handle this code properly and show both functions in the symbol list.

You can upgrade to a [dev build](https://www.sublimetext.com/3dev) if you have a license, or wait for the next beta build.
