### ISSUE TITLE
Syntax highlighting is HTML in spite of saying it's PHP when there's no <?php present

### ISSUE THREAD

**Issue by dominiklenne** [sublimehq/Packages#345]
action
--------
create new file, copy a php function code into it, but without <?php at the start, save it as .php file.

expected result
--------------------
Syntax highlighing is for PHP

actual result
---------------
Syntax highlighting is for HTML

**Comment by keith-hall** [comment]
It seems that [the `<?php` is necessary](http://stackoverflow.com/questions/1385878/php-without-start-end-tags), so I think that the current behavior is correct.

**Comment by jfcherng** [comment]
Everything out of `<?php` is HTML. That's how a PHP interpreter works.

**Comment by wbond** [comment]
This doesn't appear to be a bug with the PHP syntax, but rather how the PHP interpreter works.

**Comment by dominiklenne** [comment]
I thought, sublime-text is an editor, not an interpreter. But - yes - if you have html and php mixed, the program needs to discrimiate one from another. Sorry to have bothered.
