### ISSUE TITLE
[Python] Case statement doesn't auto-dedent

### ISSUE THREAD

**Issue by dgw** [sublimehq/Packages#3456]
### Expected behavior

```py
match thing := "one":
	case "one":
		stuff
	case "two":
		stuff
```

### Actual behavior

```py
match thing := "one":
	case "one":
		stuff
		case "two":
			stuff
```

### Steps to reproduce

1. Start a `match` block with whatever condition (I used a `:=` as part of it but that doesn't affect the result)
2. Enter at least two `case`s, without manually entering/deleting any indentation

### Environment
Windows 10 x64, ST Portable 4134

**Comment by keith-hall** [comment]
It's possible to tweak it so the case statements would like up with the `match` statement:
```diff
diff --git a/Python/Indentation Rules.tmPreferences b/Python/Indentation Rules.tmPreferences
index 03a84d2e..e0afd19d 100644
--- a/Python/Indentation Rules.tmPreferences	
+++ b/Python/Indentation Rules.tmPreferences	
@@ -6,7 +6,7 @@
 	<key>settings</key>
 	<dict>
 		<key>decreaseIndentPattern</key>
-		<string>^\s*(elif|else|except|finally)\b.*:</string>
+		<string>^\s*(elif|else|except|finally|case)\b.*:|^\s*\}[;\s#,]*$</string>
 		<key>increaseIndentPattern</key>
 		<string><![CDATA[(?x)
 			^\s*
```

```python
match thing := "one":
case "one":
    stuff
case "two":
    stuff
```

but to get the case statements indented as well would be trickier. I guess we'd need to scope the first `case` in the `match` specially so it can receive a different rule.

**Comment by deathaxe** [comment]
Would we add such special treatment to all the other syntaxes as well?
