### ISSUE TITLE
[Python] Keyword arguments confusing with existing variables

### ISSUE THREAD

**Issue by Balu-SomeNumbers** [sublimehq/Packages#3459]
### What happened?

```py
def multiplication(*numbers : int | float, max_deviation : int | float = 1) -> typing.NoReturn:
    recurse_permutations(numbers, operator.mul, operator.truediv, 1, max_deviation = max_deviation)
```

![image](https://user-images.githubusercontent.com/87214366/182292466-967c9a5f-ed25-4aeb-8301-1a009db0dab6.png)

In this case, `max_deviation` is a common name that I used for this function `multiplication` and the other function `recurse_permutations`. But the pointer `max_deviation` used as the name of the keyword argument for the function call in the second line is not the same as the variable `max_deviation` that already exists as a parameter of `multiplication` from the first line. Both these should be treated as independent even though they have the same name.

**Comment by jfcherng** [comment]
Not sure what's the issue here. Coloring issue? (but I don't see one)

**Comment by Balu-SomeNumbers** [comment]
My bad, I misinterpreted the colouring. Everything works fine
