### ISSUE TITLE
[JavaScript] Use meta.function-call.arguments scope

### ISSUE THREAD

**Issue by jwortmann** [sublimehq/Packages#3460]
## Enhancement request

It would be useful for plugins\* if the `meta.function-call.arguments` scope could be used within the parentheses of function/method calls in JavaScript & TypeScript. Currently, the syntax only uses `meta.group.js` instead. Despite not being explicitly described in the scope naming guidelines (it would be great to add it there), various syntaxes like Python, PHP, Java, Lua, Erlang and others already use `meta.function-call.arguments`. 

![scope](https://user-images.githubusercontent.com/6579999/182383652-fd632bc8-91d3-4a1f-a60a-f66b262b15c6.png)

Possible implementation:
```diff
diff --git a/JavaScript/JavaScript.sublime-syntax b/JavaScript/JavaScript.sublime-syntax
index 057dc164..f6f3b500 100644
--- a/JavaScript/JavaScript.sublime-syntax
+++ b/JavaScript/JavaScript.sublime-syntax
@@ -1909,7 +1909,8 @@ contexts:
         1: punctuation.accessor.js
         2: punctuation.section.group.begin.js
       set:
-        - meta_scope: meta.group.js
+        - clear_scopes: 1
+        - meta_scope: meta.function-call.arguments.js
         - match: \)
           scope: punctuation.section.group.end.js
           pop: 1
```
(But due to using `clear_scopes` to prevent doubling of `meta.function-call` scopes, this would have the implication to lose some information about the kind of the function call between the span of the argument parentheses - the syntax currently distinguishes between `meta.function-call.js`, `meta.function-call.method.js`, `meta.function-call.constructor.js`)

---

\* The LSP package has this feature called "signature help", which displays a popup with descriptions of the function arguments when the user types them in a function call. The scope name can be used to improve the logic to decide when to show/hide this popup (https://github.com/sublimelsp/LSP/pull/2006#issuecomment-1200421250).

**Comment by deathaxe** [comment]
> ... lose some information about the kind of the function call ...

Those are not standardized as well and of lower priority, IMHO. It doesn't even make much sense in conjunction with `arguments` sub-scope or the `identifier` and `return-type` sub scopes which are used in other syntaxes as well.

With some more modification with regards to pushed context orders `clear_scopes` could probably even be avoided.

**Comment by jwortmann** [comment]
This seems to be fixed now on master.
