### ISSUE TITLE
[Python] Enable meta_prepend / meta_append usage.

### ISSUE THREAD

**Issue by gnat** [sublimehq/Packages#3462]
### What happened?

Currently my HTML highlighter plugin overrides the SQL highlighter :cry:  which is unfortunate. Discord says we need support for `meta_prepend` and `meta_append` for Python.

https://discord.com/channels/280102180189634562/280102180189634562/1005140944565321848

Ideally I would love to see HTML in Python added to core, but enabling `meta_prepend` and `meta_append` would be fine in the interim.

https://github.com/gnat/sublime-python-html

![183111942-9d6e8dc7-6b82-47fb-9492-07d25ffc6523](https://user-images.githubusercontent.com/24665/183117786-1b1ac4a7-5ae3-49b1-9cd9-56246646c79f.png)

**Comment by gnat** [comment]
Updated my plugin with a more specific regex. Also now properly exits the highlighting mode at the end of the comment.

Feel free to bring this into core!

**Comment by michaelblyons** [comment]
The change here is to make the context(s) `push`ed for strings with special highlighting into a named context instead of an anonymous one, so `extends`ed syntaxes can add additional special cases.
