### ISSUE TITLE
[JavaScript] implicit self-closing html tags break highlighting of JSX 

### ISSUE THREAD

**Issue by deathaxe** [sublimehq/Packages#3473]
### What happened?

The `img` tag breaks highlighting by never popping `meta.jsx` off stack. Closing `))` are not scoped `punctuation`!

```jsx
    data.slice(data.length - 1).map((review) => (
      <div class="review grid-sm">
        <img src={review.avatar} alt={review.name} class="review-avatar">
      </div>
    ))
//  ^^ punctuation
```

![grafik](https://user-images.githubusercontent.com/16542113/184478818-444350f3-477f-4d6c-b613-0a69411f511f.png)

Adding a `</img>` fixes it. So I guess special treatment for certain kinds of html tags such as `img`, `hr`, `br`, ... is needed or pushing contexts onto stack for each opening tag needs to be removed.

**Comment by Thom1729** [comment]
JSX does not implicitly close tags like `<img>`. All JSX tags must be explicitly closed, either self-closed or with a closing tag. It looks like this is a difference between JSX and Astro syntax (though I don't see it in their [list of differences](https://docs.astro.build/en/core-concepts/astro-components/#differences-between-astro-and-jsx)).

It looks like the PR would break highlighting of valid JSX, such as `<img></img>`. Probably most people would write these tags in self-closing style, but close tags are valid and I would hesitate to break them.

We could make this work by special-casing each of the tags that implicitly self-closes in Astro. For e.g. `<img>`, we'd push a special version of `jsx-body` that would see any closing tag other than `</img>` and pop without consuming it. This would be a lot of extra code, and I don't think we'd want to do it just to support Astro syntax. We also might be able to do something clever with backreferences that would work for any tag (or any subset of tags), but there would be a complexity and performance cost there. In addition, I think that any such solution might not handle e.g. `const x = <img>;` in the way that Astro does.

I think that this will probably have to be handled in the Astro package, probably by extending the JSX syntax.

**Comment by deathaxe** [comment]
My impression (up to now) was Astro using plain JSX/TSX syntax for its templating purposes.

I am uncertain whether I want to start maintining an extended version of JSX/TSX.
