### ISSUE TITLE
[HTML] Missed some highlight for this webpage

### ISSUE THREAD

**Issue by Alexey-T** [sublimehq/Packages#3477]
### What happened?

webpage: 
[itsfoss.zip](https://github.com/sublimehq/Packages/files/9473486/itsfoss.zip)

here we see white parts, where it must be CSS tokens:
line 9

![s1](https://user-images.githubusercontent.com/4154978/188015376-b112854f-0cec-4070-aa83-b738eb4dfba7.png)

line 21: missed highlight for JSON block, it's white here

![s2](https://user-images.githubusercontent.com/4154978/188015502-27183c49-a071-490b-8be1-c528697c074d.png)

**Comment by deathaxe** [comment]
1. Mariana defines white color for all those tokens. It's not a syntax issue.

   The following screenshot is made with a modified Breakets Dark color scheme, for instance.

   ![grafik](https://user-images.githubusercontent.com/16542113/188077286-0bb10e52-aef8-4ae7-b7c6-e51b2379b0c1.png)

2. `application/ld+json` can be highlighted as plain JSON (without the LD- specific extensions) by tweaking (fixing) the `json_mime_type` pattern.

**Comment by Alexey-T** [comment]
>Mariana defines white color for all those tokens. It's not a syntax issue.

then it is the Mariana issue, right?

**Comment by deathaxe** [comment]
It's just the way Mariana has choosen to tint those tokens. Not sure if it can be called a bug, as color schemes are always a thing of taste and personal preferences.

You can easily customize those colors if you don't like them via `UI: Customize Color Scheme`.
