### ISSUE TITLE
[Regex] "Find in Files" support for new `//` marker

### ISSUE THREAD

**Issue by michaelblyons** [sublimehq/Packages#3482]
### What happened?

Add scopes to the find-in-files widget to support https://github.com/sublimehq/sublime_text/issues/5517

**Comment by deathaxe** [comment]
What's missing?

![grafik](https://user-images.githubusercontent.com/16542113/190425999-d9bb74c0-66ee-42f4-a2dd-a7fe694cc51b.png)
