### ISSUE TITLE
[Python] Type annotations with PEP-604 union types causes 'illegal' highlighting

### ISSUE THREAD

**Issue by FichteFoll** [sublimehq/Packages#3486]
### What happened?

```py
a: str | None = None
b: str | None = 'b'
```

![2022-09-20_17-53-11](https://user-images.githubusercontent.com/931051/191306408-8844b5d3-4202-4a60-8bf5-3f6adf1ed2e5.png)

https://peps.python.org/pep-0604/

This might be a regression because I think it wasn't like that before.

**Comment by jfcherng** [comment]
Maybe similar to https://github.com/sublimehq/Packages/issues/3290

**Comment by kaste** [comment]
I'm really skeptical when the syntaxes want to be fast linters.  `None = None` produces a syntax error in flake8 and mypy.  

IMO `invalid.` should be used (like a raise/panic) when the syntax cannot solve the puzzle anymore.  It cannot produce valid or sensible colors here and maybe on the following line(s) anymore so it marks red.  That also means as the syntaxes improve here over time we get _less and less_ invalid reds/states.  (I remember modern Javascript and ST3 produced a lot red states.)  If we do the linters work here, we do get more and more red states.  We should not do this.  We also see that the invalid states are rendered usually unreadable.  That should guide us.
