### ISSUE TITLE
[markdown] Sublime text 4 hangs in some cases

### ISSUE THREAD

**Issue by pdanford** [sublimehq/Packages#3494]
### What happened?

- Sublime Text 4 (Dev Channel, Build 4137)
- macOS 12.6
- Intel

Sublime Text 4 complety hangs and must be `kill -9` to exit. To reproduce, create a file `hang.md` with the following:

```
- [] note

test  
===========================================

```
---> Note there are 2 spaces after "test".

1. open `hang.md` in Sublime Text
2. ensure `markdown` syntax highlighting is selected
3. try to add another `=` to the end of the `====` line
4. Sublime Text 4 hangs

**Comment by deathaxe** [comment]
Appears to be a result of https://github.com/sublimehq/sublime_text/issues/5415

It's triggered by 2 branch patterns (setext-or-paragraph vs. math-blocks) being stacked onto each other.

Commenting out the following line fixes the issue, but disables mathml blocks.

https://github.com/sublimehq/Packages/blob/a6e21c01be3dad952bba5b9cafdce7449c7a94b0/Markdown/Markdown.sublime-syntax#L922

**Comment by deathaxe** [comment]
It's actually the mensioned core issue, but the trigger are the hard line break patterns, instead of the math block.

**Comment by pdanford** [comment]
Thanks for finding that so quickly :)
