### ISSUE TITLE
[Markdown] Skip highlighting in html literals

### ISSUE THREAD

**Issue by hyrious** [sublimehq/Packages#3513]
### What happened?

HTML fragments in markdown should prevents any further token scanning:

```html
<code>```math</code>
```

Rendered in Sublime Text 4126:

![Snipaste_2022-10-28_10-20-56](https://user-images.githubusercontent.com/8097890/198465302-cbc20c27-02e2-4187-a893-d552b2a3537e.jpg)

Several examples:

#### Inlines

Should render:

```html
<span>**test**</span>
```

Should not:

```html
<p>**test**</p>
<code>**test**</code>
```

#### Blocks

Should render:

```html
<details>

**test**

</details>
```

Should not:

```html
<pre>

**test**

</pre>
```

The parsing / no-parsing rules are very complex, I'm even wondering if it was possible to implement it in just .sublime-syntax.

**Comment by Alexey-T** [comment]
No for `<code>` - this should render, but only in fixed font. I tested it on Markdown Preview plugin.

**Comment by jfcherng** [comment]
In GitHub comment, ```` <code>```math</code> ```` is rendered as <code>```math</code>

**Comment by deathaxe** [comment]
While HTML blocks are strictly implemented (see how both examples of `<detail>` and `<pre>` are highlighted) CommonMark doesn't specify any special treatement for content between inline html tags. So something like "skip highlighting in html literals" is not part of the specification when we talk about inline html. 

_It is not the `<code>` tag which is responsible to render the following 3 backticks as plain text._

1. Open https://spec.commonmark.org/dingus/
2. paste `- This <code>```marks</code> is``` working.` 
3. see HTML output on the right.

   ```html
   <ul>
   <li>This <code><code>marks&lt;/code&gt; is</code> working.</li>
   </ul>
   ```

> Note:
> Github may not always be the best reference to check Markdown syntax as they claim to but not always accuratly follow CommonMark.

The reason for this happening is basically the same as for #3147. The syntax currently assums any `**`, `__`, ` ``` ` etc. to start an inline formatting/emphasis. The reason is limitations of ST3's syntax engine capabilities. Markdown could be refactored to use ST4's branching feature to probably solve most of the issues. While it was quite straight forward for inline code blocks it quickly becomes a challange with inline emphasis (italics/bold) which can be mixed into each other.

Investigations revealed it would significantly increase syntax complexity and would likely have noticible impact on performance. I paused working on trying to apply branching on emphasis for those reasons.

**Comment by hyrious** [comment]
I agree that implementing _correct_ markdown highlighting would be hard in just .sublime-syntax and may introduce bad performance.

However I don't think common mark is the only markdown people would like to write. Markdown is not like many programming languages that could have strict spec (like java or ecmascript) or have reasonable official impl (like ruby). Most of the time we're writing a markdown with many extensions including GFM (or let's say it's rendered by GitHub\.com).

To minimize the workload if we're about to _solve_ the straight problem, we could add a special treatment to `<code>` fragments that only allows html literals inside its body which stops at `</code>` EOL.

**Comment by deathaxe** [comment]
The example provided was choosen to illustrate that exactly this request is not feasable.

**Comment by FichteFoll** [comment]
If all you wanted was to render ```` ```math```` you could use four backticks to start the inline code segment. That's universally supported by GFM  (exactly what I did in this comment) and specified by CommonMark.
