### ISSUE TITLE
[PHP] `?>` in multiline comment should not be treated as a closing tag

### ISSUE THREAD

**Issue by jfcherng** [sublimehq/Packages#3535]
### What happened?

Reported on https://forum.sublimetext.com/t/code-highlighting-php-in-4142-broken/65903/2

![image](https://user-images.githubusercontent.com/6594915/201086762-22cc91b0-70e0-4e49-92bf-bef0e77e4f5a.png)

The following `?>` is not a closing PHP tag (GitHub handles this correctly).

```php
<?php

/* ?> */
// ^^ - punctuation.section.embedded.end

echo 1;
// <- support.function
```

---

Interestingly, `?>` in single-line comment is a closing PHP tag (ST and GitHub handle this correctly atm).

```php
<?php

// ?>
// ^^ punctuation.section.embedded.end

echo 1;
// <- - support.function
```

**Comment by Adomph** [comment]
![image](https://user-images.githubusercontent.com/23532776/201134358-02502df0-ba88-4203-a562-1e7ce628b6be.png)
Problem with the new update
