### ISSUE TITLE
[PHP] string arg in `define(...)` is not scoped as string

### ISSUE THREAD

**Issue by jfcherng** [sublimehq/Packages#3536]
### What happened?

https://github.com/sublimehq/Packages/issues/3535#issuecomment-1310457726

![image](https://user-images.githubusercontent.com/6594915/201139646-de99955b-b8b9-4e2f-a876-c47042a06c53.png)

```php
<?php define('FOO', '');
//            ^^^ string
```

**Comment by deathaxe** [comment]
`entity.name.constant` is assigned by intent. Treating it as quoted macro identifier is is what makes "Goto Definition" possible for macros.

So I'd call this working as expected.

**Comment by jfcherng** [comment]
Closed as this is by design.
