### ISSUE TITLE
[PHP] Syntax highlighting broken in build 4142

### ISSUE THREAD

**Issue by fatg3erman** [sublimehq/Packages#3539]
### What happened?

The following perfectly valid PHP breaks the syntax highlighting. Also Go To Definition cannot find any function definition that follows this line.

`
$extrabit = ' AND (Title LIKE "%'.urldecode($_REQUEST['searchterm']);
`

The highlighting thinks that anything after the 'u' character is a string and highlights it as such. Swapping the " for ' and the ' for " un-confuses it, but this is valid PHP and worked before.

Also the assignment operator => is no longer highlighted as an operator, it used to be the same colour as, say, =.

I know you want to keep improving the software and this is not a complaint but please be very very careful with syntax highlighting. For some of us with poor colour vision correct highlighting is the difference between being able to do our jobs and not.

**Comment by jfcherng** [comment]
I can confirm that `%'.u` is treated as a whole somehow.

**Comment by michaelblyons** [comment]
`https://example.com/index.php?searchterm=Bobby";DROP+TABLE+users+--`
