### ISSUE TITLE
 [PHP] PHP tags in block comments 

### ISSUE THREAD

**Issue by jfcherng** [sublimehq/Packages#3540]
### What happened?

Reported from https://forum.sublimetext.com/t/php-comment-syntax-highlighting/65960

```php
<?php /*if (! empty($var)) { ?>
//    ^^ punctuation.definition.comment.begin
//                           ^^ - punctuation.section.embedded.end
    <h1>Title in multiple-lines comment block.</h1>
<?php } else {*/ ?>
// <- - punctuation.section.embedded.begin
//            ^^ punctuation.definition.comment.end
    <h1>Title not in comment block.</h1>
<?php //} ?>
```

## Golden result
![image](https://user-images.githubusercontent.com/6594915/201314411-4840fe4f-73a5-4302-8483-fec20af34e84.png)

## How it looks like on the `master` branch
![image](https://user-images.githubusercontent.com/6594915/201314506-4edddea5-e5f8-4494-85d3-345a43ad168d.png)

**Comment by jfcherng** [comment]
Close as fixed by https://github.com/sublimehq/Packages/pull/3537 as well.

**Comment by Terail** [comment]
Syntax highlighting also stopps from something like this:

/*$xml = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'."\n";*/

All code after this line is shown as unformatted plain text.

Guess the ?> is the Problem here?

**Comment by jfcherng** [comment]
> Syntax highlighting also stopps from something like this:
> 
> `/*$xml = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'."\n";*/`
> 
> All code after this line is shown as unformatted plain text.
> 
> Guess the ?> is the Problem here?

![image](https://user-images.githubusercontent.com/6594915/201372398-3456fa0f-0f5d-4d0e-a33d-d738deedc47a.png)

**Comment by Terail** [comment]
![grafik](https://user-images.githubusercontent.com/12572023/201375259-5992a3c6-3f6f-4718-bd6e-63e54b5201e9.png)

**Comment by jfcherng** [comment]
As state in https://github.com/sublimehq/Packages/issues/3540#issuecomment-1311778962, do you use the patch?

**Comment by Terail** [comment]
I installed the latest version of ST which is 4143. I am on maOS Monterey.

**Comment by jfcherng** [comment]
> I installed the latest version of ST which is 4143. I am on maOS Monterey.

This doesn't include that patch.

**Comment by Terail** [comment]
oh , I dont know about a patch , I’ll check for it now. Sorry, I am not a github user at all.

**Comment by Terail** [comment]
I dont know how o install those patches correctly nor where to get them. I will wait for an official hotfix or upcoming update. Feel free to close the github’s thread if you like so. And thank you for the support! cheers.

**Comment by jfcherng** [comment]
> Feel free to close the github’s thread if you like so. And thank you for the support! cheers.

It was already closed.

> I dont know how o install those patches correctly nor where to get them.

https://github.com/sublimehq/Packages#installation

Or I wrote a script to update all syntax to whichever commit you would like to use.
https://github.com/jfcherng-sublime/ST-my-settings/blob/master/update_st_official_packages.sh
Just put it in the `Data/` directory and execute it. Admin privilege may be required.
