### ISSUE TITLE
PHP - Does not recognize variables in SQL queries

### ISSUE THREAD

**Issue by DiegoBima** [sublimehq/Packages#3543]
### Description of the bug

In PHP, apparently in SQL queries, variables enclosed in single quotes, inside
double quotes are colored green, as if they were strings, whereas before it detected them and colored them red.

![image](https://user-images.githubusercontent.com/118059169/201476434-19a2c759-30e4-45ce-b606-2ce97cae4a45.png)

### Steps to reproduce

```
<?php

$LandingPage = 'xxx';

$Variable = 'yyy';

$Text = "Aca voy a poner una '$Variable' encerrada en texto";

$Otro = "UPDATE base SET LandingPage = '$LandingPage'";

?>
```

### Expected behavior

Colored variables in red

### Actual behavior

Colored variables as text

### Sublime Text build number

4142 / 4143

### Operating system & version

Windows 11

**Comment by deathaxe** [comment]
I've transfered the issue as it is related to color schemes

**Comment by deathaxe** [comment]
It looks like the variable is missing the `variable` scope.

![grafik](https://user-images.githubusercontent.com/16542113/201484539-5ba3d0ee-591a-401d-acb7-2684a8134744.png)

**Comment by jfcherng** [comment]
> It looks like the variable is missing the variable scope.

True... affected by the single quote.

**Comment by deathaxe** [comment]
Yes, SQL contains various anonymous string contexts which exclude the `prototype` context. They need special treatment.
