### ISSUE TITLE
[PHP] `yield` not recognised while used as expression.

### ISSUE THREAD

**Issue by Endermanbugzjfc** [sublimehq/Packages#3549]
### What happened?

`yield` is a PHP expression. It can return a value like functions and other expression operators, such as `+`.

However, while it is in a bracket pair, the close-bracket is highlighted as a syntax error.

# Sample code
```php
function yielder(){
    a(yield);
}

function a(mixed $_){
}
```

# Test in safe mode
![image](https://user-images.githubusercontent.com/53002741/201512236-bdea4e30-bb75-40ea-9499-6d3cf6c16719.png)

![image](https://user-images.githubusercontent.com/53002741/201512162-2f591127-470f-48c0-8eff-528cfe12e6e3.png)

# Environment
**Sublime Text:** Build 4143.

**Comment by jfcherng** [comment]
Minimal reproducer:

```php
<?php

(yield);
//    ^ - invalid
[yield];
//    ^ - invalid

```

**Comment by Endermanbugzjfc** [comment]
Thank you for replenishing.

**Comment by deathaxe** [comment]
None of the examples at https://www.php.net/manual/en/language.generators.syntax.php#control-structures.yield.from seems to give any indication this is valid PHP code. Hence `yield` is currently treated like `return` or other control flow keywords.

**Comment by Endermanbugzjfc** [comment]
> None of the examples at https://www.php.net/manual/en/language.generators.syntax.php#control-structures.yield.from seems to give any indication this is valid PHP code. Hence `yield` is currently treated like `return` or other control flow keywords.

https://3v4l.org/3XHtY
Code from https://sof3.github.io/await-generator/master/generators.html#calling-another-generator
