### ISSUE TITLE
[Python] Cmd+R thinks ":" is a function

### ISSUE THREAD

**Issue by michaelblyons** [sublimehq/Packages#356]
The Goto Symbol command now thinks the `:` at the end of every function definition is its own function.

```python
def foo(bar):
#^^^^^^       Symbol 1 (Highlighted on Cmd+R)
#           ^ Symbol 2 (Highlighted on first down-arrow after Cmd+R)
   pass
```

**Comment by wbond** [comment]
This if fixed by 2c577428eb3759f5341c0365b6c8ef08bf51a930

**Comment by michaelblyons** [comment]
After pulling your changes, the effect is still there. I tried reloading the file and quitting/reloading Sublime.

**Comment by wbond** [comment]
What are the contents of your `Packages/Python/Symbol List.tmPreferences` file?

**Comment by michaelblyons** [comment]
```xml
<?xml version="1.0" encoding="UTF-8"?>
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Symbol List</string>
	<key>scope</key>
	<string>source.python meta.function - meta.function.decorator, source.python meta.class</string>
	<key>settings</key>
	<dict>
		<key>showInSymbolList</key>
		<integer>1</integer>
		<key>symbolTransformation</key>
		<string>
		s/class\s+([[:alpha:]_][[:alnum:]_]*.+?\)?)(\:|$)/$1/g;
		s/(?:async\s+)?def\s+([[:alpha:]_][[:alnum:]_]*).*/$1\(…\))/g;
		</string>
	</dict>
</dict>
</plist>
```

**Comment by wbond** [comment]
I can not reproduce the error you are seeing with the latest syntax and tmPreferences file.

Can you try opening a new buffer, pasting the code from your bug report and trying goto symbol again? Perhaps the tokens for the file are cached in memory?

What OS are you on, and what version of ST3 are you using?

**Comment by michaelblyons** [comment]
A new buffer with the NOOP function from my first post still has the issue.

### My environment

* Operating system:
    * [ ] Windows
    * [x] Mac OS
    * [ ] Linux
* Sublime Text Build:
  * branch:
    * [x] stable
        * I have a couple languages symlinked into `~/Library/Application Support/Sublime Text 3/Packages` from a checkout of the `master` of this repository, including Python.
    * [ ] dev
  * number:
    * Build `3103`

**Comment by wbond** [comment]
Try build 3112 and see if that helps.

**Comment by michaelblyons** [comment]
Confirmed fixed in 3114.
