### ISSUE TITLE
Wrong markdown highlighting of mixed code

### ISSUE THREAD

**Issue by tsymbal** [sublimehq/Packages#3563]
### Description of the bug

Sorry for my english. 
New version of Sublime highlights mixed syntax (html in php, php in js, etc) with mistakes.

### Steps to reproduce

Example screenshots:
1. https://dump.tsymbal.su/16-11-2022%20082213.jpg html and php
2. https://dump.tsymbal.su/16-11-2022%20082539.jpg js and php

### Expected behavior

example 1. Comment highlighting should start with "/\*" and end with "\*/" regardless of the presence of html code inside this area.
example 2. Nested double quotes referring to different programming languages must not conflict.

Highlight system in previous stable version (4126) worked fine for described situations. And when running scripts, we do not observe errors, despite their presence in the highlight.

### Actual behavior

example 1. See example 1 screenshot. When we try to comment block of php code containing html inclusions, comment highlighting (gray colored text) ends with first php ending construction "?>".
example 2. See example 2 screenshot. When we include php code in js code, double quotes, that refer to php code, cause highlighting error.

### Sublime Text build number

4143

### Operating system & version

Windows 11

**Comment by jfcherng** [comment]
Can't see screenshots but I guess this has been fixed by https://github.com/sublimehq/Packages/pull/3537
