### ISSUE TITLE
[Markdown] The ending quote for a link is scoped as a part of the link

### ISSUE THREAD

**Issue by jfcherng** [sublimehq/Packages#3564]
### What happened?

![image](https://user-images.githubusercontent.com/6594915/202108942-270c8b62-88cb-4fca-9e22-6b53901c9511.png)

```md
"https://example.com"
#                   ^ - meta.link
```

The above test should pass?

**Comment by rchl** [comment]
I also don't understand why certain characters within a link are scoped differently, resulting in different color.
