### ISSUE TITLE
C++ anonymous namespaces not recognized

### ISSUE THREAD

**Issue by sunnyps** [sublimehq/Packages#358]
Sublime Text 3112 on Ubuntu 14.04.

See this file: https://code.google.com/p/chromium/codesearch#chromium/src/cc/raster/one_copy_raster_buffer_provider.cc&l=26

It looks like this with Monokai:
![screenshot from 2016-05-05 14 18 57](https://cloud.githubusercontent.com/assets/1481819/15057637/a50a4fee-12cc-11e6-8a08-accd8ccc6a0d.png)

**Comment by sunnyps** [comment]
Maybe it's nested namespaces in general and not anonymous namespaces.

**Comment by wbond** [comment]
This should be fixed by e68b1881a2e4f516fdbd5ec58246f5e3c712a5e9

**Comment by sunnyps** [comment]
Thanks!
