### ISSUE TITLE
[C] Dollar sign ($) in middle of identifier names causes improper syntax highlighting

### ISSUE THREAD

**Issue by Monochrome-Sauce** [sublimehq/Packages#3580]
### What happened?

When writing an identifier name with a dollar sign ($) in the middle/end (completely valid C/C++), the identifier is not properly colored.

#### Example:
```
void print_$tr(const char *my$tr)
{
	fputs(my$tr, stdout);
}

#define MY_FO$O(x) x
#define MY_BA$R 10

```
#### Variables:
The 3 first characters of `my$tr` will appear white, while the last 2 will appear orange (with the theme I use).

#### Functions:
As for functions, `print_str` (no dollar sign) will be colored green, but `print_$tr` will be colored white (as described in **Variables**) and the letters after the dollar sign will be colored blue.

#### Macros:
Macro functions (i.e `MY_FO$O`) will have the parts before the dollar sign appear orange, but after it blue, with the dollar sign itself white. \
Normal macros (i.e `MY_BA$R`) will have the parts before the dollar sign appear orange, but the dollar sign and after it white.

**Comment by deathaxe** [comment]
None of the Cxx specs contains any evidence for that.

- https://www.open-std.org/jtc1/sc22/wg14/www/projects#9899
- https://learn.microsoft.com/en-us/cpp/c-language/c-identifiers?view=msvc-170

**Comment by Monochrome-Sauce** [comment]
I will close the issue.

I seem to have mixed **6.4.2 Identifiers** and **6.4.3 Universal character names** due to GCC and clang accepting "$" as part of an identifier name.
