### ISSUE TITLE
PhP Syntax Issue

### ISSUE THREAD

**Issue by club589** [sublimehq/Packages#3597]
### What happened?

in php MySQL Syntax Highlight issue. MySQL Syntax Not Show Properly. Old Sublime Working Fine. 

![image](https://user-images.githubusercontent.com/118815163/205292829-3bfe1021-acc7-427d-b0cc-85fb34e184af.png)

Same Code Properly Show in VS Code.
![Screen Shot 2022-12-02 at 6 00 44 PM](https://user-images.githubusercontent.com/118815163/205293714-c2a47cc4-0c27-4bad-bf88-e753223e32c0.png)

i'm Use Sublime Version is 4143 Stable Version.
File Language is "PhP" And Syntax Not Show Properly MySQL Syntax.

**Comment by jfcherng** [comment]
has been fixed by https://github.com/sublimehq/Packages/pull/3541
