### ISSUE TITLE
Hang while pressing `(` with `auto_match_enabled: false` in TypeScript files

### ISSUE THREAD

**Issue by Jimbly** [sublimehq/Packages#3598]
### Description of the bug

The process hangs, all windows becoming unresponsive, killing Sublime Text is required, when doing the following:

### Steps to reproduce

1. Start ST in Safe Mode
2. Open Preferences and set it to:
```json
{
  "auto_match_enabled": false,
}
```
3. Create a new file, set syntax to TypeScript, enter the following:
```typescript
type Foo = {
  // With the cursor at the end of the next line, press open parentheses
  bar: (cb:
};
```
4. Press `(` with the cursor after `cb:`

### Expected behavior

Doesn't hang =)

### Actual behavior

Sublime Text hangs

### Sublime Text build number

4143

### Operating system & version

Windows 11 22H2 22621.819

**Comment by deathaxe** [comment]
Transfered the issue as it is primarily caused by TypeScript syntax implementation.
