### ISSUE TITLE
C++ 

### ISSUE THREAD

**Issue by DolphinDream** [sublimehq/Packages#361]
Sublime Text 3103 
Ubuntu 14.04 64 bit

The C++ methods are not highlighted properly and the (the @R command does not show many of the methods). It seems that if the method has a return type the syntax highlighter misses it (and also it is not displayed the drop down method list). Also it seems that if command does not get highlighted or even other function calls (See the screen capture and the sample code).

[sampleCode.cpp.zip](https://github.com/sublimehq/Packages/files/253233/sampleCode.cpp.zip)

![c -highligtingbug](https://cloud.githubusercontent.com/assets/2083719/15089678/2f794580-13d7-11e6-8700-27e4ce6546b6.png)

**Comment by wbond** [comment]
This code is correctly highlighted using dev build 3112 and the latest syntax definition.

<img width="577" alt="screen shot 2016-05-07 at 8 46 10 am" src="https://cloud.githubusercontent.com/assets/41734/15092169/3766ffb8-1430-11e6-88fa-0dcf9ef8d66f.png">
