### ISSUE TITLE
[PHP] Comment highlighting doesnt show properly

### ISSUE THREAD

**Issue by afwork92** [sublimehq/Packages#3610]
### What happened?

Hello, whats wrong with my sublime?
After one of the last updates php comment highlighting doesnt show properly
I have default theme and color scheme (sixteen). I tried install another scheme - it doesnt work.

How it shows now - ![2022-12-07_17-26-44](https://user-images.githubusercontent.com/42000085/206205019-58c264cc-c45a-40a5-97f8-36b0f14883b2.png) (closing php tag break comment highlight)

How it should be - 
![2022-12-07_17-28-03](https://user-images.githubusercontent.com/42000085/206205220-0d1b62a1-0310-4521-8d46-92cd976d15b5.png)

**Comment by michaelblyons** [comment]
Fixed by #3541
