### ISSUE TITLE
[PHP] SublimeText 4 doesn't highlight mixed syntax anymore

### ISSUE THREAD

**Issue by BrwGamer** [sublimehq/Packages#3623]
### What happened?

If in a .php file there are also HTML, CSS and Javascript or also only some of these, the syntax highlight does not color them properly **anymore**. <u>In the previous versions of sublime text (e.g. months ago) it worked good.</u>

I have the latest version 4143 on Ubuntu 20.04 LTS and on Ubuntu 22.04 LTS.
I already tried to change color scheme to a default one.

```
<?php
// TODO
if($_SERVER['REMOTE_ADDR'] != '...') { $highlightedPhp = false; }
?>
<html lang='<?=$lang?>'>
<head>
	<title>title</title>
	<?php /*TODO: comment*/ ?>
	<META NAME="copyright" CONTENT="Copyright <?= date("Y"); ?>">
	<script src="https://ajax.googleapis.com/..."></script>
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/...">
</head>
<body>
<?php
	$highlightedPhp = false;
?>
<center>
<h1 id='idH1'><?php $highlightedPhp = false; ?></h1> 
<a class='classTest' style='padding-left:10px;'>Some text</a>
<script>
console.log('some text in console');
$('#idH1').on('someEvent', function() {
	testFunction();
});
$(function() {
	// js comment
});
function testFunction(param) {
	if(param) {
		console.log(param);
		$('#something').trigger('change', function() {
			// ...
			<?php $highlightedPhp = "true?"; $var2 = join([1,2,3,4,5]); $_SERVER['REMOTE_ADDR']; ?>
		});
	}
}
```

Highlight with "PHP" syntax (the default when I open the file):
![Schermata del 2022-12-14 08-50-08](https://user-images.githubusercontent.com/66242883/207537318-14865c09-e7a6-457f-a495-97ff0bf7f157.png)

Highlight with "CSS (PHP)" syntax:
![image](https://user-images.githubusercontent.com/66242883/207537895-9e2242f3-0f0d-43bf-ba4c-2c070440c7d0.png)

Highlight with "Javascript (PHP)" syntax:
![image](https://user-images.githubusercontent.com/66242883/207538056-d1ac07d6-07cb-457b-ad2e-f226a6023d01.png)

Thanks a lot

**Comment by BrwGamer** [comment]
On Mac it seems working, how can I solve on Ubuntu?

**Comment by deathaxe** [comment]
The correct syntax to use is PHP.sublime-syntax. PHP has been significantly updated between ST 4126 and 4143 to reduce RAM usage by 75% and to improve parsing performance. The update comes along with various structural changes (e.g. changed file names, ...).

The file provided is highlighted well on ST4143 in SAFE MODE on Windows and Linux on my box.

You probably want to check whether a _PHP_ folder exists in your _Packages_ directory, which contains some old files.

1. Main Menu > Preferences > Browse Packages ...
2. Look for PHP folder
3. Remove it if it exists

**Comment by deathaxe** [comment]
Why unlabeling? It is probably a syntax related support issue.

**Comment by BrwGamer** [comment]
> You probably want to check whether a _PHP_ folder exists in your _Packages_ directory, which contains some old files.
> 
>     1. Main Menu > Preferences > Browse Packages ...
> 
>     2. Look for PHP folder
> 
>     3. Remove it if it exists

It works after removed the file in the PHP folder and reopened Sublime.

Thanks a lot!
