### ISSUE TITLE
[Python] Spell checking enabled by default even when spell check is "off" in the menu

### ISSUE THREAD

**Issue by dragos240** [sublimehq/Packages#3624]
### What happened?

Spell check if off by default, as you can see here
![image](https://user-images.githubusercontent.com/704081/207583069-b30451cb-f818-4714-9b22-8c7dc5546f1f.png)

But it still registers as "on"
![image](https://user-images.githubusercontent.com/704081/207583236-1b3d3c28-73e4-4df1-b9f1-028284a83f1d.png)

I can fix this by pressing F6 twice to turn it "on", then "off", but I need to do this every session. I haven't tested it with other languages, but Python is affected. Build is 4143 Linux x64.

**Comment by deathaxe** [comment]
Does it happen when starting ST in SAFE MODE?

Spell Checking is enabled when opening a file if `spell_check: true` is set in user settings, project specific settings or syntax specific settings. Check box is checked then and spell checking is disabled by pressing F6 once.

Maybe a plugin is involved?

**Comment by dragos240** [comment]
It only started happening last time I updated sublime. It wasn't doing this before in the last build I was using and I haven't installed any new plugins. I will check safe mode though and report back.

**Comment by dragos240** [comment]
This doesn't happen in Safe Mode, so it's likely a user config/plugin issue. Closing.
