### ISSUE TITLE
[Graphviz] Syntax highlighting not properly terminated when multiple html tags used

### ISSUE THREAD

**Issue by julianbarg** [sublimehq/Packages#3627]
### What happened?

Syntax highlighting for the use of html in labels only works properly if all tags apply to the whole label. For example, this label breaks the syntax highlighting for all subsequent lines because sublime thinks that the html input has not been terminated, even though it is a valid input.

```graphviz
label = <<u>this is underscored</u><br/>this is not>
```

**Comment by michaelblyons** [comment]
Remembering how I did this before, I expect you are correct. (Sorry I'm on a phone right now and cannot verify.) The trouble is detecting unmatched `>` in the appropriate places. It might now be easier with syntax inheritance, which did not exist at the time.

Or if someone was feeling super overachieving, they could make a special implementation of the HTML subset supported by Graphviz.

**Comment by deathaxe** [comment]
No need for inheritance. Just include HTML instead of embedding it in order to make sure to pop HTML if a `>` is found at top-level.

**Comment by michaelblyons** [comment]
Oh neat. 👍
