### ISSUE TITLE
[C]  syntax error in scanf format string

### ISSUE THREAD

**Issue by mrkrossxdx** [sublimehq/Packages#363]
%[, ] and %*[, ] are valid scanf format string placeholders but are reported invalid by Sublime.
![scanf](https://cloud.githubusercontent.com/assets/12089978/15100557/4bb02e5e-1575-11e6-817e-c81266518f33.png)

**Comment by wbond** [comment]
Support for scanset placeholders was added in a70bbec4c3f9c907a1157b723136c4bc68ba5f2d
