### ISSUE TITLE
[Sublime text] Syntax highlighting

### ISSUE THREAD

**Issue by Adomph** [sublimehq/Packages#3633]
### What happened?

![image](https://user-images.githubusercontent.com/23532776/209126376-86cfad69-c03a-4832-b9cd-1c550608d442.png)
![image](https://user-images.githubusercontent.com/23532776/209126537-8fc21de4-a08c-47d2-bc4a-6019361f11b3.png)

**Comment by deathaxe** [comment]
It's working as expected.

1. `define('ABSPATH')` is scoped `entity.name.macro` to drive _Goto Definition_, while all other 
references (e.g.: `defined('ABSPATH')`) keep being scoped normal strings.

2. The `%d` format placeholder is scoped `constant.other.placeholder`, which various color schemes assign a dedicated color to. _The improvement could rather be to also scope `%M` within `strftime()`.

You would need to modify your color scheme using _UI: Customize Color Scheme_ to change highlighting to whatever you want. Required scopes can be determined via `ctrl+shift+alt+p` while caret is on a token.

see also: https://forum.sublimetext.com/t/color-schemes-doesnt-work-properly/66479/2

Missing strftime() format placeholders are proposed via #3634.

**Comment by deathaxe** [comment]
see also: #3536
