### ISSUE TITLE
[C#] Wrong closing brace indentation following a line that already had whitespaces

### ISSUE THREAD

**Issue by ssoher** [sublimehq/Packages#3657]
In the video below, the first time an if statement is written, the following line is indented correctly. After deleting the statement back to the leading whitespace, consequent if statement closing braces are indented incorrectly.

edit: doesn't have to have any leading whitespace, also happen on a deleted line with no indentation.

note: also encountered in other c-like syntaxes. may be an ST bug.

https://user-images.githubusercontent.com/4283979/216778442-10a56a5e-49ec-40d3-9a02-6dfae40a3dfd.mp4

**Comment by jfcherng** [comment]
To reproduce, you have to set `"auto_match_enabled": false,` and one crucial thing: you MUST use mouse to select codes to delete before the second time test.

**Comment by ssoher** [comment]
I don't use mouse

**Comment by jfcherng** [comment]
Your video shows you are not writing C# but likely plain text, which `auto_match_enabled` probably has no effect. I can reproduce this with `auto_match_enabled: false` when writing codes.

**Comment by ssoher** [comment]
This seems to be a core issue and not limited to a specific syntax package, will report on sublime_text repo.

**Comment by jfcherng** [comment]
> This seems to be a core issue and not limited to a specific syntax package, 

Agree because how you delete text before the second round is a crucial thing too, from my experiments.
