### ISSUE TITLE
[C++] Regression: function declaration and control structures parsed as calls

### ISSUE THREAD

**Issue by cschreib** [sublimehq/Packages#366]
Using the current master branch, function declarations and control structures (if/for, etc) are parsed as function calls (except in some specific cases also illustrated below):
```c++
//// Functions
int foo(); // bad
//  ^^^ meta.function-call.c++, variable.function.c++
int* foo(); // bad
//   ^^^ meta.function-call.c++, variable.function.c++
int *foo(); // good
//   ^^^ meta.function.c++, entity.name.function.c++

//// Control structures
// Global scope
    if (true) foo(); // good
//  ^^ keyword.control.c++ 

// In a function
int foo() {
    if (true) foo(); // bad
//  ^^ meta.function-call.c++, variable.function.c++
}
```

**Comment by wbond** [comment]
I can not reproduce what you are describing. I tried both the C and C++ syntax.

Are you using dev build 3112?

**Comment by cschreib** [comment]
No, I am using the stable build 3103.
I just checked on another computer that was still using a pulled master branch from April 24: the parsing was correct, and updating to the current master branch broke it.

**Comment by wbond** [comment]
I'll update the readme to reflect the fact that the syntaxes are tested with the latest dev build.

In this case we've added features and fixed bugs in our custom regex engine since 3103. Once the next beta build is out, the engine should be fairly stable moving forward.
