### ISSUE TITLE
[PackageName] `/usr/share/bash-completion/bash_completion` is not correctly highlighted

### ISSUE THREAD

**Issue by stdedos** [sublimehq/Packages#3661]
### What happened?

![image](https://user-images.githubusercontent.com/133706/217810965-f3506615-40bb-43e2-964f-1cef8df9ec4d.png)

[bash_completion.tar.gz](https://github.com/sublimehq/Packages/files/10696983/bash_completion.tar.gz)

**Comment by jfcherng** [comment]
# Minimal Reproducer

```bash
[[
    # '
    -z $xxx
]] && echo hi
```

Currently, `# '` is not treated as comment line.

**Comment by stdedos** [comment]
... And remind me, those fixes "auto-land", or require a Sublime Text version bump? 😕

**Comment by michaelblyons** [comment]
> ... And remind me, those fixes "auto-land", or require a Sublime Text version bump? 😕

Version bump, or you can [get them right now.](https://github.com/sublimehq/Packages#installation)

**Comment by jfcherng** [comment]
There are more issues from the file. I will create another one.

**Comment by stdedos** [comment]
> > ... And remind me, those fixes "auto-land", or require a Sublime Text version bump? 😕
> 
> Version bump that includes syntax updates[1](#user-content-fn-1-31c2775734ac0411703f0bb65b8108be), or you can [get them right now.](https://github.com/sublimehq/Packages#installation)

Sweet! "I guess" I won't know if/when next Sublime with this plans to land so ... manual install it is 😅

**Comment by jfcherng** [comment]
I have a script to literally "replace" (rather than override) ST's built-in packages to a specific commit in this repo if you need it: https://github.com/jfcherng-sublime/ST-my-settings/blob/master/scripts/update_official_packages.sh

**Comment by stdedos** [comment]
I like the "quick cadence" of minor/bugfix updates like that 😊
