### ISSUE TITLE
[PHP] Concatenating a single-quote string ending in %

### ISSUE THREAD

**Issue by dsarratt** [sublimehq/Packages#3677]
### What happened?

When a single-quoted string ends with a %, Sublime tries to interpret it as a printf string placeholder, and if successful means the string never terminates. This breaks all syntax highlighting after the string. A minimal reproduction is:

```php
$a = '%'.date(0);
```

I believe Sublime is interpreting the `%'.d` sequence as:
* % = start of placeholder
* '. = pad the result with .
* d = decimal specifier

Some similar code snippets that do not trigger the bug:
```php
# t is not a valid printf specifier
$a = '%'.time();

# double-quote is not a valid printf flag
$a = "%".date(0);

# space is not a valid specifier
$a = '%'. date(0);
```

I think this is the relevant syntax definition inside the sublime-package file:
```
  string-placeholders:
    # https://www.php.net/manual/en/function.printf.php
    - match: '%%'
      scope: constant.character.escape.php
    # %[argnum$][flags][width][.precision]specifier
    - match: |-
        (?x)
        (%)                         # punctuation
        (?: \d+\$ )?                # argnum
        [-+]? (?: [ 0] | '. )?      # flags
        \d*                         # width
        (?: (\.) \d* )?             # precision
        [bcdeEfFgGhHosuxX]          # specifier
      scope: constant.other.placeholder.php
      captures:
        1: punctuation.definition.placeholder.php
        2: punctuation.separator.decimal.php
```

**Comment by jfcherng** [comment]
![image](https://user-images.githubusercontent.com/6594915/224929599-b9e1912f-d41d-401b-994c-19a880ce97f6.png)

Looks good to me in ST 4138.

**Comment by dsarratt** [comment]
Ah sorry, yes you're right. I think this is a dupe of #3539 .
