### ISSUE TITLE
[Python] Char is marked as invalid escape in raw string

### ISSUE THREAD

**Issue by jfcherng** [sublimehq/Packages#3682]
### What happened?

```python
R"""
Foo:

C:\Users
"""
```

`\U` is in raw string so it's not an escape.

![image](https://user-images.githubusercontent.com/6594915/227095268-c9b53c0e-00d4-4c4d-80e2-368d9b417102.png)

Or is there a special intention for this?

**Comment by FichteFoll** [comment]
Probably a regression from the Python refactorings in #3650.
