### ISSUE TITLE
[TypeScript] Highlighting failing for declaration of function

### ISSUE THREAD

**Issue by rchl** [sublimehq/Packages#3683]
### What happened?

```ts
import { Mp3WorkerConfig } from '../types/config.type';
export declare const initMp3MediaEncoder: ({ vmsgWasmUrl }: Mp3WorkerConfig) => void;
```

![Screenshot 2023-03-23 at 09 05 53](https://user-images.githubusercontent.com/153197/227140724-e487e2d0-321b-4990-a83a-df39939c9947.png)

**Comment by Thom1729** [comment]
Huh. I suspect that the function type code doesn't expect binding patterns there. Not sure what the use is in that context, but AST Explorer confirms that it's real. (I'd check the spec, if there were one.)
