### ISSUE TITLE
[CSS] Support CSS Nesting

### ISSUE THREAD

**Issue by iccir** [sublimehq/Packages#3688]
### What happened?

Both Chrome 112 and Safari Technical Preview 162 now implement [CSS Nesting](https://www.w3.org/TR/css-nesting-1/).

More information is available here:
https://developer.chrome.com/articles/css-nesting/
https://webkit.org/blog/13813/try-css-nesting-today-in-safari-technology-preview/

Sublime doesn't yet highlight nested selectors. In the following example, `color` lacks the `support.type.property-name.css` scope:

```
.foo { .bar { color: red; } }
```

I worked around this in my local `CSS.sublime-syntax` file by appending the following to `rule-list-body`:

```
    - match: (?=[&:.*#\[]|{{combinators}})
      push: main
```

**Comment by deathaxe** [comment]
Once nesting becomes a stable enough feature, support might be added. A draft filed at just now, is not intended to be supported.

**Comment by iccir** [comment]
Note that this will be enabled by default in browsers shipping next week.

Chrome 112: 2023-04-04
Edge 112: Week of 2023-04-06
Safari 16.5, iOS WebKit 16.5: In beta now, likely shipping in the next few months.
Firefox: No estimate.

**Comment by deathaxe** [comment]
Doesn't change its draft state.

**Comment by deathaxe** [comment]
FWIW, nested CSS files are supported by [Tailwind CSS](https://github.com/SublimeText/TailwindCSS)

It extends ST's default CSS adding tailwind related at-rules and nesting.

**Comment by gnat** [comment]
The modification of `CSS.sublime-syntax` mentioned in OP seems to work well, for people waiting.

Not yet in Sublime as of build 4154

**Comment by gnat** [comment]
Thanks but I'll pass. OP's is 1 line and works.

The official change should hurry up into core.
