### ISSUE TITLE
[C#] using declaration and string interpolation issue

### ISSUE THREAD

**Issue by beautifulcoder** [sublimehq/Packages#3708]
### What happened?

Hi,

The following code snippet fails to highlight correctly:

```csharp
using var resp = await client.GetAsync(new Uri($"http://localhost:5000/events?start={start}&end={end}"));
```

When I take out the using _declaration_ everything highlights correctly. I suspect it has something to do with string interpolation and the the using declaration without braces introduced in C# 8.

![Screenshot 2023-04-23 113959](https://user-images.githubusercontent.com/5228509/233852702-211bf052-ad03-442c-9383-20d0e01ecc55.png)

**Comment by deathaxe** [comment]
I see that statement failing only, when used as first global statement in a file. As soon as being used within a function body etc. it highlights correctly.

![grafik](https://user-images.githubusercontent.com/16542113/233856463-a3e19c41-eaea-4df6-83b9-a9439d54d880.png)

**Comment by beautifulcoder** [comment]
Ah, I think I see what's happening here. C# 9 introduced top-level statements. So, when the using declaration goes outside the method braces, it fails to highlight.

![Screenshot 2023-04-23 204528](https://user-images.githubusercontent.com/5228509/233881241-ed0424c9-cab3-4b0f-b2bb-1d392babb352.png)

Apologies, should have been more clear.
