### ISSUE TITLE
[PHP] misleading comments in syntax test

### ISSUE THREAD

**Issue by keith-hall** [sublimehq/Packages#373]
To fix issue #322, the [PHP syntax test was updated](https://github.com/sublimehq/Packages/commit/463b400bfbbdc0772a3d6a350a5761a3fb1593c8#diff-704c2dc0506af29e37902450ea766d79R481) and contains a comment that is now misleading/incorrect because the test now passes.
Probably the comments on lines 473 and 477 can also be removed :)

**Comment by wbond** [comment]
Thanks for pointing this out. Fixed with 124a39613044c87453e54298bb89727548d3461b.
