### ISSUE TITLE
[JavaScript] Indentation rules trigger in mapping objects

### ISSUE THREAD

**Issue by rchl** [sublimehq/Packages#3747]
Typing `default` as the key name in an object triggers dedent:

### Expected behavior

```js
const x = {
    default|
}
```

### Actual behavior

```js
const x = {
default|
}
```

### Steps to reproduce

Write `default` inside an object:

```js
const x = {
    default
}
```

The scopes are ```source.js meta.mapping.js``` in this location so I guess dedent rules could exclude `meta.mapping` but then it would also disable it in code like:

```js
const x = {
    default() {
        switch (x) {
            default|
        }
    }
}
```

**Comment by deathaxe** [comment]
Fixed by #4015
