### ISSUE TITLE
[RFC] Path wildcard scope

### ISSUE THREAD

**Issue by michaelblyons** [sublimehq/Packages#3766]
```bash
cat *.txt
```

For `*` and `?` as wildcards[^1], we have several schemes:

| Scope | Syntaxes | Comments |
|-|-|-|
| `constant.other.placeholder` | Batch | |
| `keyword.operator.path.asterisk` | Git ||
| `keyword.operator.quantifier` | Bash, _lots_ of Regex syntaxes | It's used twice in Bash: Once as regex quantifier and once as argument wildcard for paths. |
| `keyword.operator.wildcard` | File Patterns, SQL, Java | File patterns single level, SQL `LIKE` strings |
| `variable.language.wildcard` | File Patterns, SQL, Makefile | File patterns multilevel, SQL `SELECT *` |

I think Regex is its own thing and should stay as `keyword.operator.quantifier`, but for the others, should they be consolidated to one or two scopes?

I suggest that `**`-type multilevel ones use `variable.language.wildcard` and `*`-type short ones use `keyword.operator.wildcard`, but that's just what I did for File Patterns for the "Find in Files" paths. Other opinions welcome.

[^1]: In SQL, `%` and `_`.

**Comment by deathaxe** [comment]
1. `constant.other.placeholder` seems most likely being used for placeholders in format strings (e.g.: `%s`). IIRC, this scope was also used for path wildcards in older syntaxes, which is not wrong, but hard for color schemes to distinguish them, in case both appear next to each other.

    As such a dedicated scope is appriciated.

2. As `?` and `*` don't denote placeholders or wildcards, but operators in regexp, the chosen scope is ok as is.

3. I have been struggling with `keyword.operator.wildcard` vs. `variable.language.wildcard` various times in the past.

   Which scope is more suitable, semantically?

   With regards to paths we might also take into account special signs like `~`, `.` or `..` and how they look compared to wildcards - using simple color schemes. Are they even of same category? 
   
   - `~` = `variable.language.environment` (Git Link)
   - `.`, `..` = `constant.language.path`
  
   Wildcards look like operators and "manipulate" a string in some way.
   
   They can also be interpreted as some kind of interpolation or expansion, thus `variable` is suitable, too.
   
   Why would you distinguish `*` vs. `**`? Both are just wildcards, aren't they?


What we might take into account with regards to highlighting using simple color scheme rules is:

1. wildcards may appear together with placehilders in format strings
2. wildcards may appear in strings, which are part of complicated string concatination expressions with many normal operators in between.
3. In some syntaxes it's sometimes not easy to distinguish a regexp pattern from path strings using fnmatch.

**Comment by deathaxe** [comment]
With a look at CSS using Mariana color scheme `variable.language.wildcard` seems to be the better choice for wildcards, especially when appearing in expressions together with chaining (or other) operators.

see: https://github.com/sublimehq/Packages/pull/3781#issuecomment-1586188629

```CSS
* > * { ... }
```

![grafik](https://github.com/sublimehq/Packages/assets/16542113/21ccacc4-1166-496d-ad7f-169d21894c35)

Of course a color scheme could address `keyword.operator.wildcard` to achieve the same, but with different 1st-level scope `variable` chances are higher a distinct highlighting is achieved for broader range of existing and maybe more simple color schemes.

**Comment by deathaxe** [comment]
The final conclusion about scope naming of wildcards and path separators according to https://github.com/sublimehq/Packages/pull/3803#issuecomment-1627711666 is:

```
constant
  other
    path
      parent
      self
    wildcard
      asterisk
      questionmark
```

Note: Path separators are optional scope names which can be used in strings which denote (only) paths or urls. HTML and some other syntaxes introduced special highlighting of path separators in urls as a result of a feature request. It is however not intended to enforce path separator scoping under all circumstances. It should however only applied if path strings can be identified reliably and scoping them doesn't disturb the overall highlighting.
