### ISSUE TITLE
[JavaScript] "this" argument in definition highlighted as invalid

### ISSUE THREAD

**Issue by rchl** [sublimehq/Packages#3772]
### What happened?

```ts
interface ModuleDefinition {
    setup?: (this: void, resolvedOptions: T) => void
}
```

Highlighted as:

![Screenshot 2023-05-20 at 19 04 32](https://github.com/sublimehq/Packages/assets/153197/87bc3724-ac5b-4f96-94e4-afc823b8373b)

**Comment by Thom1729** [comment]
Should be fixed in #3773.
