### ISSUE TITLE
[C#] C#11's raw string literals (multi-line strings) are not handled

### ISSUE THREAD

**Issue by Jackenmen** [sublimehq/Packages#3788]
### What happened?

![image](https://github.com/sublimehq/Packages/assets/6032823/151f8db8-a5ce-4cb9-9ce6-44373ba0a556)

```csharp
string longMessage = """
    This is a long message.
    It has several lines.
        Some are indented
                more than others.
    Some should start at the first column.
    Some have "quoted text" in them.
    """;
```

This feature was first available in C#11 Preview in April 2022 and has since been released as part of the .NET 7 update on November 2022:
https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-11#raw-string-literals

**Comment by deathaxe** [comment]
Support for raw literals was added by https://github.com/sublimehq/Packages/pull/3659 and was released with ST4149.

**Comment by Jackenmen** [comment]
@deathaxe Hi, I've noticed an issue on ST 4150 with how this works with an interpolation:
![image](https://github.com/sublimehq/Packages/assets/6032823/1d121cb6-5337-4e40-8c79-2e9a7935645e)
```
var location = $"""
   You are at {{{Longitude}}, {{Latitude}}}
   """;
```

Is this something that #3720 is supposed to track or should I make another issue for it?

**Comment by deathaxe** [comment]
That's a separate issue. #3720 is about structuring syntax definition like python, as the new raw literals seem equaly complex.

There may be more issues, as PR #3659 claims to be a start for literal support only.
