### ISSUE TITLE
[Python] Relax f-string restrictions for upcoming Python 3.12 (PEP 701)

### ISSUE THREAD

**Issue by FichteFoll** [sublimehq/Packages#3792]
### What happened?

[PEP 701](https://peps.python.org/pep-0701/) implements proper parsing of f-strings and allows nesting them in a way that the quotation mark used in an outer f-string may be used inside it. We currently have restrictions on this in the syntax definition.

**Comment by deathaxe** [comment]
What details of PEP 701 are missing in current Python implementation?

**Comment by michaelblyons** [comment]
I think we consider these to be invalid:
```python
f"abc{def["ghi"]}"
f'abc{def['ghi']}'
```
Because right now you have to use the other string quote style inside interpolations.

**Comment by deathaxe** [comment]
Keyword `def` is scoped illegal as it is not expected to be used as variable.

![grafik](https://github.com/sublimehq/Packages/assets/16542113/3b6ae59c-9ebc-47d8-b0f7-8536c456b131)

But using any other name would be perfect valid, already.

![grafik](https://github.com/sublimehq/Packages/assets/16542113/9c3c6a81-db6e-4bc8-97cc-dcb2ae786b4d)

Current syntax implementation globally scopes and reserves keywords whether they are treated as such in a certain context or not by python. Changing that would probably have a significant impact on syntax complexity.

**Comment by FichteFoll** [comment]
Yeah, my bad for not checking first. This is already handled correctly.

![image](https://github.com/sublimehq/Packages/assets/931051/0252f316-0d2b-4b6b-bbd3-3d7295796819)

As I was reading the upcomping changes to 3.12 I was remembering that there was a restriction for this before (back when I initially implemented f-string highlighting iirc) and forgot to check whether that is still the case.
