### ISSUE TITLE
Build 3112 breaks goto definition for PHP class names

### ISSUE THREAD

**Issue by danwall** [sublimehq/Packages#380]
Prior to build 3112 it was possible to place the cursor over the string `ClassA` in test.php and perform the `goto_definition` command to be taken to the file and class declaration in ClassA.php.

It has been suggested that recent changes to the PHP syntax could have affected this https://forum.sublimetext.com/t/dev-build-3112/19778/10.

test.php:
```php
<?php

$a = new ClassA;
```

ClassA.php:
```php
<?php

class ClassA
{
    //
}
```

**Comment by keith-hall** [comment]
It seems that this isn't limited to separate files - the following example doesn't show any symbols in "Goto Symbol":

    <?php
    
    class ClassA
    {
        //
    }
    
    $a = new ClassA;

**Comment by wbond** [comment]
Fixed by #382
