### ISSUE TITLE
[ShellScript] Arguments to `[` and `test` incorrectly have `variable` scope

### ISSUE THREAD

**Issue by FichteFoll** [sublimehq/Packages#3804]
### What happened?

```sh
# Source xprofile
[ -f /etc/xprofile ] && . /etc/xprofile
[ -f ~/.xprofile ] && . ~/.xprofile

# source xinitrc.d files
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi
```

![2023-07-10_11-01-23](https://github.com/sublimehq/Packages/assets/931051/fcade6ab-7666-4aa0-b698-0d26524a0bc7)

**Comment by deathaxe** [comment]
Current syntax doesn't treat any token like `-d`, `-f` special by pushing a dedicated context.

https://github.com/sublimehq/Packages/blob/13c51aeca81e4f8eb66b95cddb07287c97343b9e/ShellScript/Bash.sublime-syntax#L816-L821
