### ISSUE TITLE
[Bash] Here document termination 

### ISSUE THREAD

**Issue by scomer1** [sublimehq/Packages#3808]
### Description of the bug

A shell (sh, bash, csh, zsh, etc.) "Here Document" <<word form has a requirement that the word which terminates the document appear on a line by itself. Any other characters are not allowed. Sublime Text colors them accordingly, highlighting word where it appears at the start of the document and the end. When using the <<-word form, subsequent lines may start with tabs which are removed, including any tabs on the final line. This allows you to indent them so they look nice. Sublime Text colors this form, too.

However, Sublime Text colors the <<-word form incorrectly when there is a space among the tabs that indent the final word. it highlights the word like everything is ok, but it is not. the shell does not allow the space, and the word is not seen as terminating the document.

### Steps to reproduce

enter the text as shown into a file named test.bash. ensure the third "Here Document" started at line 16 with word CHERRY is attempted to be terminated by a line which is space, tab, C, H, E, R, R, Y, newline

<img width="396" alt="Screenshot 2023-07-18 at 11 02 02 AM" src="https://github.com/sublimehq/sublime_text/assets/130488916/8eeb2f61-1f7d-471f-9a37-fb6837c45171">

i've searched for the regular expression '^\t* ', and you can see the highlighting of the space which matched the search and blocking the proper termination of the "Here Document".

### Expected behavior

line 18, the word CHERRY should be green, but is colored red.

it should be green because it isn't terminating the third :Here Document" started at line 16, because the line contains a space character.

### Actual behavior

sublime text thinks the third "here document" is properly terminated but it is not. if you run the script it will fail.

### Sublime Text build number

4143

### Operating system & version

13.4.1 (c) 

### (Linux) Desktop environment and/or window manager

Apple M1 Pro

**Comment by deathaxe** [comment]
It would require to match leading whitespace of (maybe nested multiline-)statements and store them for re-use by a context (which parses HEREDOCS).

That's not possible with ST's general purpose syntax engine.

**Comment by michaelblyons** [comment]
Would it be possible to match `[ ]\t` and `\t[ ]` as invalid in the closing line? Is that even helpful?

**Comment by deathaxe** [comment]
We don't know style and amount of opening line's statement. If it would contain the same kind of mixed indentation, I guess the closing one containing it would be fine.

That's just replacing one edge case by another thus not worth the effort or increased complexity.

**Comment by deathaxe** [comment]
🤔 https://www.oreilly.com/library/view/bash-cookbook/0596526784/ch03s04.html

Seems restricting to `\t` could be a sane improvements as only those are allowed for indentation. Counting them seems not required.

**Comment by Alexey-T** [comment]
file
https://github.com/sublimehq/Packages/blob/master/ShellScript/test/syntax_test_bash.sh
has HEREdoc tests. one of them has the space-chars in indentation.

![su](https://github.com/sublimehq/Packages/assets/4154978/4e06dcd5-73a1-4411-96c4-e9bb4e8b7c31)


is it correct test?

**Comment by jfcherng** [comment]
> tests are OK?

Depends on the design goal.
