### ISSUE TITLE
[Python] Use Python Launcher on Windows for build system

### ISSUE THREAD

**Issue by FichteFoll** [sublimehq/Packages#381]
Currently, the build system invokes `python` via shell_cmd. However, on Windows this should _definitely_ use the `py` launcher that any Python version >=3.3 installs globally and into the PATH by default, which is capable of a couple neat things but most importantly interprets shebang lines and is on the PATH by default, which afaik a normal installation is not.

Now, here comes a problem: Any Python version lower than that does not get the launcher installed and thus the build system will fail for those users that only have older versions installed. Since everyone still using Py2 is either living under a rock, using a (possibly old) (and LTS) Linux version that still only comes with Py2 (unimportant since this is Windows-only) or otherwise ... whatever, I suppose the number of people affected by this is rather small. Just for compatibility's sake, we could define a variant that always calls `python` even on Windows, so that users only have to modify their PATH and select the legacy build variant instead of modifying the build system directly. The disadvantage of that is that the variant would also be displayed for non-Windows platforms.

Thoughts?

**Comment by michaelblyons** [comment]
IronPython [doesn't have a v3 install][1] yet.

[1]: https://github.com/IronLanguages/ironpython3#installation

**Comment by michaelblyons** [comment]
I rescind any objection I had. IronPython is still not done, but 🤷‍♂. Welcome to the future.
