### ISSUE TITLE
php multiple line comment is not working well

### ISSUE THREAD

**Issue by arasanoutdoinc** [sublimehq/Packages#3811]
### What happened?

php multiple line comment is not getting highlighted properly if there is any php tag is inside the commented code

![Screenshot from 2023-07-20 17-17-17](https://github.com/sublimehq/Packages/assets/51149415/5ae82d07-971f-4ce0-8e00-9ed50c691530)

this is working fine on sublime text 3. but subliment text 4 has this issue

**Comment by arasanoutdoinc** [comment]
After applying the patch from this GitHub repository: https://github.com/jfcherng-sublime/ST-my-settings/blob/master/scripts/update_official_packages.sh, the overall functionality seems to be working fine. 

However, there is an issue with the PHP block inside the script, which is not functioning correctly.

![image](https://github.com/sublimehq/Packages/assets/51149415/32a0d9f4-9dfa-4fc5-be4d-878e67ca74f3)

**Comment by jfcherng** [comment]
I can confirm your screenshot illustrates a bug. But please file another issue for it.
