### ISSUE TITLE
Support flexbox in CSS

### ISSUE THREAD

**Issue by PixelT** [sublimehq/Packages#383]
Add flexbox properties / values to CSS autocomplete

**Comment by Briles** [comment]
The following flexbox properties and their values should be autocompleting in both the latest [stable](https://www.sublimetext.com/3) and [dev](https://www.sublimetext.com/3dev) versions of Sublime Text:

- align-content
- align-items
- align-self
- flex
- flex-basis
- flex-direction
- flex-flow
- flex-grow
- flex-shrink
- flex-wrap
- justify-content
- order

Do you have any packages installed that would conflict with autocompletion?

**Comment by PixelT** [comment]
Unfortunatelly, still doesn't have this position in autocomplete

**Comment by wbond** [comment]
This seems to be working on my machine with 3114:

<img width="338" alt="screen shot 2016-06-01 at 5 52 41 am" src="https://cloud.githubusercontent.com/assets/41734/15705395/23aa68de-27bd-11e6-8e5a-de68c70dbaa6.png">

**Comment by PixelT** [comment]
I tested it now in 3114 end they work in CSS
It's possible to support it also in SASS / SCSS / Less files? (there doesn't work also)

**Comment by wbond** [comment]
@PixelT That depends on the SASS/SCSS package you are using.

**Comment by PixelT** [comment]
OK, I understand - thanks

**Comment by ellipticaldoor** [comment]
@wbond which package should I used to get this working with SASS/SCSS ?

**Comment by FichteFoll** [comment]
https://packagecontrol.io/packages/Sass probably?
