### ISSUE TITLE
[Java] How do I run my program?

### ISSUE THREAD

**Issue by KyawSoeNing** [sublimehq/Packages#3833]
### Expected behavior

i write some code in sublime text but after coding i can't run my java file 
and i can't build a new system in sublime 
please help me 
please.....................................................................

### Actual behavior

i write some code in sublime text but after coding i can't run my java file 
and i can't build a new system in sublime 
please help me 
please.....................................................................

### Steps to reproduce

i write some code in sublime text but after coding i can't run my java file 
and i can't build a new system in sublime 
please help me 
please.....................................................................

**Comment by deathaxe** [comment]
ST ships two simple build system files. One of them just calls `javac` to compile the active file and the other one invokes `ant.bat` batch file.

None of them is intented to run a code nor may at least javac be insufficient to build a complete project consisting of multiple sources.

For more sophisticated build tasks I'd recommend to learn how to write custom sublime-build files to invoke custom shell/build scripts (such as maven) or run a file once it has been built.

Note that ST's build system is just an entry point to run shell scripts.

see: https://www.sublimetext.com/docs/build_systems.html

Note that ST's build output panel is designed to display compiler output. It doesn't accept input and therefore can't run console apps.
