### ISSUE TITLE
[Shell] String in `[[ ... ]]` should has `string.quoted` as it's in `[ ... ]`

### ISSUE THREAD

**Issue by jfcherng** [sublimehq/Packages#3853]
### What happened?

The following tests should pass.

```shell
[[ ${JENKINS_DEBUG} == 'true' ]]
#                      ^^^^^^ string.quoted.single
[[ ${JENKINS_DEBUG} == "true" ]]
#                      ^^^^^^ string.quoted.double
```

Offending commit: https://github.com/sublimehq/Packages/commit/b58ab9da035134319b00c3fb0d6c6072bf0b658a

**Comment by deathaxe** [comment]
The term to the right of `==` or `!=` is a shell pattern, with quoted parts being treated literal. Thus it is scoped `meta.string.regexp` (see: https://github.com/sublimehq/Packages/pull/3827/commits/89c889987e6ac5e8d04e0eeab87bb62bd14c6264).

Examples:

```sh
if [[ "Hello World" == Hello" "World ]] ; then echo matched; fi
#                      ^^^^^^^^^^^^^ meta.string.regexp
# >> matched

if [[ "Hello World" == "Hello "World ]] ; then echo yes; fi
#                      ^^^^^^^^^^^^^ meta.string.regexp
# >> matched

if [[ "Hello World" == Hello" World" ]] ; then echo yes; fi
#                      ^^^^^^^^^^^^^ meta.string.regexp
# >> matched

if [[ "Hello World" == "Hello"?[Ww]orld ]] ; then echo yes; fi
#                      ^^^^^^^^^^^^^^^^ meta.string.regexp
# >> matched
```

The reason why literal parts of patterns or whole patterns are NOT scoped  `string`, is given in related PR's OP (see: https://github.com/sublimehq/Packages/pull/3827).

We could apply a string scope in test expressions, but this would result in patterns being highlighted differently, than in other contexts. While it is doable in `case` statements, too, pattern matching is scoped globally via `expansions-and-strings` context, which is it not so easy to apply string without introducing other issues.
