### ISSUE TITLE
[Python] Trailing single `\` in `R"...\"` should be a syntax error

### ISSUE THREAD

**Issue by jfcherng** [sublimehq/Packages#3860]
### What happened?

![image](https://github.com/sublimehq/Packages/assets/6594915/675649d2-2e5d-46af-9030-151fdf7ea1d9)

When using `R"...\"` or `R'...\'`, ST consider the second `"` as an ending quote, but it's actually escaped in Python and will causes syntax error.

The handling for `r"...\"` and `r'...\'` are correct in ST.

**Comment by FichteFoll** [comment]
Similarly, `R"a\" string"` is also a proper string in Python but ST stops the string highlighting after `\"`.
```
>>> R"a\" string"
'a\\" string'
>>> R"a\"
  File "__main__", line 1
    R"a\"
        ^
SyntaxError: EOL while scanning string literal
```
