### ISSUE TITLE
[D] Can't  fold/unfold arrays

### ISSUE THREAD

**Issue by ryuukk** [sublimehq/Packages#3878]
### What happened?

I can't fold/unfold this array:

```D
int[] test = [
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
];
```

Very annoying when arrays are very long

**Comment by deathaxe** [comment]
related with #3626

caused by disabling indentation based folding in conjunction with not enough scope for syntax based folding.

A quick fix would be to re-enable indentation folding

see: https://github.com/sublimehq/Packages/blob/65dde23edf82ec0ae2092193e4a45731b8294ff9/D/Fold.tmPreferences#L9
