### ISSUE TITLE
[C++] Initializing a class member with a left bitshift breaks syntax highlighting.

### ISSUE THREAD

**Issue by pgrit** [sublimehq/Packages#388]
Putting something like this inside a class:
`static const int = 1 << 4;`
breaks syntax highlighting in the subsequent lines of code. Other operators, especially the right shift, do not create this problem.
![example](https://cloud.githubusercontent.com/assets/12607894/15244737/eff5452c-1902-11e6-8f3c-7ef793b78109.png)

**Comment by wbond** [comment]
This is almost certainly that we are incorrectly matching `<` as the beginning of a generic type.

**Comment by wbond** [comment]
This is fixed by f2c2806185898ef5d44fad967a8afd0fabe85b7a
