### ISSUE TITLE
[NOT IMPORTANT] Python f-strings do not highlight as SQL syntax

### ISSUE THREAD

**Issue by grinheckerdev** [sublimehq/Packages#3885]
### Problem description

<img width="884" alt="Снимок экрана 2023-12-13 в 10 56 54 AM" src="https://github.com/sublimehq/sublime_text/assets/148703318/63a3af47-4763-41be-b1a5-16d41f5d9d36">

### Preferred solution

f-strings should be highlighted with SQL syntax.

### Alternatives

N/A

**Comment by keith-hall** [comment]
I personally see it as a feature that SQL is not highlighted inside fstrings. This form of interpolation can easily lead to SQL injection bugs/vulnerabilities. Instead it's better to pass parameters. Plus it helps with the SQL plan cache to have fewer distinct queries.

**Comment by deathaxe** [comment]
I am rather concerned about amount of contexts in conjunction with #3046 as SQL is pushed `with_prototype`. Python's syntax cache already grows from 640kB to 2.9MB with that PR and might significantly grow further with more SQL contexts being added.

Adding SQL highlighting within f-strings is easy copy&paste though.
