### ISSUE TITLE
3114 Syntax php highlighting miss some keywords

### ISSUE THREAD

**Issue by bodinsamuel** [sublimehq/Packages#389]
Hi,

since update 3114 php syntax highlighter seems to have trouble coloring some keywords.

As you can see in the screenshot below,
![screenshot_218](https://cloud.githubusercontent.com/assets/1637651/15247968/ce6fc084-1917-11e6-8288-ee6b84fdb67f.png)

Thanks :)

**Comment by KvanSteijn** [comment]
The same issue as my issue #391. Sorry for my duplicate.

**Comment by KvanSteijn** [comment]
I have found a other syntax issue. Numbers in array's don't have the correct syntax color. It's now the same color as the array.
```php
$test = array();
$test[1] = 'test';
```

**Comment by wbond** [comment]
This is likely an issue with the color scheme. Using Monokai, you'll see `static` and `self` before `::` colored orange. They are scoped `variable.language`. It is up to the color scheme what color those scopes are set to.

The `1` in your second example is scoped as `constant.numeric` and is colored properly in the color schemes I tried. Most likely, again, this is an issue with the color scheme being used.

**Comment by danielbachhuber** [comment]
Here are some keywords that are missing for me:

Build 3114:

![image](https://cloud.githubusercontent.com/assets/36432/15320204/1f362142-1be4-11e6-9531-f22433a0b80c.png)

![image](https://cloud.githubusercontent.com/assets/36432/15320207/24b38632-1be4-11e6-88a1-cb8198576e04.png)

Build 3013:

![image](https://cloud.githubusercontent.com/assets/36432/15320279/7ee44326-1be4-11e6-8775-5f8e0153b99f.png)

![image](https://cloud.githubusercontent.com/assets/36432/15320286/874edc1a-1be4-11e6-98d7-4d5f82f4fe33.png)

**Comment by keith-hall** [comment]
@danielbachhuber I believe your `use` statements will be covered by my PR here: https://github.com/sublimehq/Packages/pull/385

**Comment by wbond** [comment]
@danielbachhuber This seems like a separate issue from the OP, could you open a new issue please and provide snippets of code that can be copy-pasted?
