### ISSUE TITLE
[TypeScript] `!.` is incorrectly scoped as `punctuation.accessor`

### ISSUE THREAD

**Issue by frou** [sublimehq/Packages#3890]
(ST 4169)

As I understand it, TypeScript's `!` is a postfix unary operator, so `foo!.bar` is really just `foo!` that happens to have a subsequent property access chained onto it.

For that reason, I think `!` in `foo!.bar` should be given the scope `keyword.operator.type`, as it already is in `foo!`

Or to put it another way, `!.` is not an atomic piece of syntax in the way that `?.` is. (safe property access in JS)

**Comment by Thom1729** [comment]
You are absolutely correct and I don't know what I was thinking.
