### ISSUE TITLE
[Markdown] Add support for GFM alert blocks

### ISSUE THREAD

**Issue by jwortmann** [sublimehq/Packages#3891]
### What happened?

GitHub recently introduced a new feature for alert blocks in Markdown and the syntax is finalized now:

* [Blogpost](https://github.blog/changelog/2023-12-14-new-markdown-extension-alerts-provide-distinctive-styling-for-significant-content/)
* [Docs](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts)

TLDR; the syntax looks like this:
```markdown
> [!NOTE]
> Useful information that users should know, even when skimming content.

> [!TIP]
> Helpful advice for doing things better or more easily.

> [!IMPORTANT]
> Key information users need to know to achieve their goal.

> [!WARNING]
> Urgent info that needs immediate user attention to avoid problems.

> [!CAUTION]
> Advises about risks or negative outcomes of certain actions.
```

Since GFM extensions are included in Sublime's Markdown syntax, it would be nice to have support for the alert blocks.

Some ideas/suggestions for the scope names:

* Note: `markup.quote.markdown markup.info.note.markdown`
* Tip: `markup.quote.markdown markup.info.tip.markdown`
* Important: `markup.quote.markdown markup.info.important.markdown`
* Warning: `markup.quote.markdown markup.warning.markdown`
* Caution: `markup.quote.markdown markup.error.markdown`

From the CommonMark point of view those alert blocks are still regular blockquotes, so I think the new scope parts should be stacked on top of `markup.quote`. This also ensures that the blocks receive the color scheme's standard highlighting for blockquotes if there are no special rules for `markup.info` etc. in the color scheme.

A question would be whether to apply the scopes only to the `[!NOTE]`, etc. part, or to the entire block. I don't have a strong preference about that, but in case it's applied to the entire block, then the `[!NOTE]` part should probably get another dedicated scope like for example `keyword.declaration.note` on top. And the example scopes from above are meant to include the existing `markup.paragraph` in that case, i.e. the final scope could be `markup.quote.markdown markup.info.note.markdown markup.paragraph.markdown` for the text. But I would tend to apply the new scope parts only to the `[!NOTE]` part of the block; then it would resemble how it's rendered on GitHub. On the other hand, the text is part of the alert box, so I guess semantically it makes more sense to apply the scope to the whole blockquote. And this would allow the color scheme for example to apply a background color to the alert block.

**Comment by deathaxe** [comment]
Scopes such as `markup.error`, `markup.warning` etc. should probably keep reserved for markups added byy linters to avoid conflicts with normal content.
