### ISSUE TITLE
[Godot] Add syntax highlighting support for Godot's languages

### ISSUE THREAD

**Issue by tuto193** [sublimehq/Packages#3895]
### What happened?

# Problem description
Languages from the Godot Engine have no syntax highlighting support at all (GDscript (`.gd`), Godot Resource (`.res`) and Godot Shader Language (`.gdshader`)).

# Preferred solution
Add syntax support for `GDScript`, `Godot Resources` and `Godot Shaders`.

**Comment by michaelblyons** [comment]
https://packagecontrol.io/packages/GDScript%20(Godot%20Engine)

**Comment by tuto193** [comment]
> https://packagecontrol.io/packages/GDScript%20(Godot%20Engine)

That package is a bit outdated and doesn't take into account new GDScript conventions that arrived with the major Godot 4 release this year.

**Comment by deathaxe** [comment]
Anyway a maintainer would be required.

3rd-party packages have the advantage not to require review from at least two more maintainers and can move on independently from ST releases.
