### ISSUE TITLE
Go syntax doesn't load in Build 3093

### ISSUE THREAD

**Issue by mikattack** [sublimehq/Packages#39]
On OS X (10.10.3) I see the Go package at `/Applications/Sublime Text.app/Contents/MacOS/Packages/Go.sublime-package`, but within the editor I get the error message:

> Error loading syntax file "Packages/Go/Go.tmLanguage": Unable to open Packages/Go/Go.tmLanguage.

This originally happened on an auto-update but persists after a reinstallation.

When I manually clone the packages repository and move/link the Go package (per the "Installation" instructions), thing work immediately.

**Comment by FichteFoll** [comment]
Did you reopen the .go file you were editing? Old syntax file references are (obviously) not preserve between updates but cached anyway.

**Comment by mikattack** [comment]
The Go syntax option didn't even show up in the `View -> Syntax` menu until I manually copied the package from the repo.

**Comment by jfcherng** [comment]
Fixed in 3094.
