### ISSUE TITLE
[C++] Syntax highlighting bug with default constructor

### ISSUE THREAD

**Issue by oconnor0** [sublimehq/Packages#390]
The following class definition, on dev build 3113, shows a syntax highlighting bug on the closing `}`. Removing the `void` parameter fixes this issue.

```c++
class X {
  X(void) = default;
};
```

**Comment by wbond** [comment]
Currently I believe this will be detected as a macro call because we look for a single identifier/token to detect macros in class bodies. We should add a special case for the keyword `void` to not be detected as a macro so it falls through to match as a constructor.

**Comment by wbond** [comment]
This should be fixed by 08e69e4407982663a603d64cdbd42b1c52a60f61
