### ISSUE TITLE
Python Highlighting - `type` is matched too aggressively as a keyword

### ISSUE THREAD

**Issue by justin-snyder-slgg** [sublimehq/Packages#3902]
### Description of the bug

I noticed that recently, Sublime started highlighting `type` as a keyword, but this causes some issues because it is officially only a soft keyword that also happens to share a name with a builtin function. Depending on context, `type` could be a keyword or an identifier, and this has some minor rippling effects on later highlights in the line (and sometimes spilling onto later lines)

### Steps to reproduce

1. Start in safe mode
2. Set language to python
3. Type the following:
```python
class Foo:
	type: list[str] = ['a']
```

Observe the weird highlighting that acts as if `type` is a keyword here even though it isn't

### Expected behavior

The official grammar for type statements is as follows:

> type_stmt ::=  'type' [identifier](https://docs.python.org/3.12/reference/lexical_analysis.html#grammar-token-python-grammar-identifier) [[type_params](https://docs.python.org/3.12/reference/compound_stmts.html#grammar-token-python-grammar-type_params)] "=" [expression](https://docs.python.org/3.12/reference/expressions.html#grammar-token-python-grammar-expression)

Therefore I propose that `type` should only be highlighted as a keyword in the following situations:

- when it is the only token on the line (the assumption being that you are about to type out a type statement)
- when it is the first token on the line and is followed immediately by another identifier

As soon as `type` is followed by anything other than an identifier, it should revert to being highlighted as a builtin or identifier. (Ideally it should be highlighted as a regular identifier when it is on the left side of an assignment or type annotation, but being highlighted as a builtin (as it was before) didn't cause any cascading issues with syntax highlighting and is tolerable)

### Actual behavior

Currently, it appears that `type` is treated as a keyword when it is the first token on a line, regardless of what tokens follow it on that line.

<img width="213" alt="Screenshot 2024-01-10 at 3 59 43 PM" src="https://github.com/sublimehq/sublime_text/assets/104024666/5d7fdd89-122c-461b-9a68-350e55df55a8">

### Sublime Text build number

4169

### Operating system & version

MacOS Sonoma 14.1.1

**Comment by deathaxe** [comment]
Despite `type` possibly being a normal variable, depending on context, it has been scoped `support.function` before even if not looking like a function call. So are all tokens, which denote python 2 or 3 builtins.

As a result it used to be highlighted comparable prominent various color schemes, before.

With a restriction applied to `type` only being scoped `keyword.declaration` if followed by an identifier as proposed in OP, situation wouldn't change significantly for such color schemes.

Mariana:

![grafik](https://github.com/sublimehq/Packages/assets/16542113/f9ae84e7-d2f1-437f-a444-885789133733)

Monokai

![grafik](https://github.com/sublimehq/Packages/assets/16542113/c3cb7538-3931-48b1-9ed9-bc6db320ef4c)

Brackets

![grafik](https://github.com/sublimehq/Packages/assets/16542113/11c87e17-e329-41eb-9e1f-6def0cc69230)

**Comment by FichteFoll** [comment]
Scoping it as `support.function` is definitely better than as `keyword.declaration` (because that would just be wrong) so I don't think we need to argue about that.

As for whether or not we should scope the target of assigmnets as `support.function` when it's the same as a built-in, I strongly think yes, because in most cases you're shadowing the built-in type in that case and it only *kinda* works out in a class definition, because outiside of the class definition itself you can only access that `type` attribute via attribute access. However, within the class definition, it still makes a difference if you do:
```py
class A:
  type = 'a'
  other = type
# vs
class B:
  other = type
```

**Comment by deathaxe** [comment]
Both scopes are sub-optimal and I rather tend to also dislike scoping builtin-function-identifiers special in non-function-call expressions. Shadowing existing globals is not a syntax error or disallowed in any way and fully within responsibility of the author.
