### ISSUE TITLE
[PHP] self and static

### ISSUE THREAD

**Issue by KvanSteijn** [sublimehq/Packages#391]
The syntax color for `self` and `static` is incorrect. It's not the same as new X();
```php
self::$test;
$test = new self();
static::$test;
$test = new static();
```
X have different color then`self` and `static`.
```php
X::$testl
$test = new X();
```

**Comment by wbond** [comment]
This is most likely an issue with the color scheme being used.

`self` is scoped `variable.language` as is `static`. `X` is scoped `support.class`.

It is up to the color scheme to color them the same way.
