### ISSUE TITLE
[Markdown] LaTeX code block not highlighted

### ISSUE THREAD

**Issue by ditek** [sublimehq/Packages#3915]
### What happened?

Not sure if this an issue in the LaTeX package or the Markdown package, so feel free to suggest changing the issue title if needed.
Files with `.tex` extension are highlighted properly, but Latex code blocks in Markdown files are not highlighted. I tried using `tex` and `latex` as the language name with the same result.

![image](https://github.com/sublimehq/Packages/assets/10835824/01d3fb17-c59a-4b7f-ba10-07553cae625d)

I'm using Sublime Text build 4143

**Comment by ditek** [comment]
Thanks @michaelblyons  for fixing the title. Now that I know which package is the problem I think I know how to fix it and I'm happy to create a PR. I followed the README instructions to create a directory junction on Windows, but it doesn't seem like my changes are being reflected in Sublime. Is it enough to restart the program or I need to force reloading the packages somehow?

**Comment by deathaxe** [comment]
LaTeX is excluded from being highlighted in fenced codeblocks by intent, as it also supports fenced code-block like expressions, which used to easily cause maximum allowed complexity to be exceeded due to including foreign syntaxes.

It shouldn't be an issue anymore, now that ST loads `embed`ded syntaxes lazily.

**Comment by ditek** [comment]
Could you clarify? By "it shouldn't be an issue anymore", do you mean that it no longer needs to be excluded?

**Comment by deathaxe** [comment]
Exactly.

**Comment by ditek** [comment]
Great! So should I just prepare a PR with the fix?
In that case I would appreciate a quick advice on how to get changes to the package to take effect. A simple Sublime restart doesn't seem to do the trick. I followed the relevant instructions in the README to create a directory junction.
(I tried a simple test of removing the Python highlighting definitions which still worked after restart)

**Comment by michaelblyons** [comment]
Deleting the file just means the default one is used. You could keep the Python file there and empty out its `main` context of the matches and includes.

**Comment by ditek** [comment]
Yes, that's what I meant. I removed the Python part of `Markdown\Code Block Syntaxes.sublime-completions` file and I still got highlighting for Python blocks, meaning the changes didn't take effect. I'm wondering if it's enough to just restart Sublime Text or there is some sort of cache I need to clear.

**Comment by deathaxe** [comment]
Creating a junction `Markdown` in Packages folder is enough. All files in that directory override default package. Removing completions (Code Block Syntaxes.sublime-completions) doesn't affect syntax definitions.
