### ISSUE TITLE
[OCaml] "Quoted string" literals are not recognized

### ISSUE THREAD

**Issue by henrikt-ma** [sublimehq/Packages#3958]
### What happened?

The "quoted string" literals described at https://ocaml.org/manual/5.1/coreexamples.html are not recognized as strings.  This is particularly problematic when the string literal contains unbalanced `"` characters, as this will mess up syntax highlighting until the next unbalanced `"` in a quoted string is encountered.

Here is a simple example of a "quoted string" from the reference above:
```
{|This is a quoted string, here, neither \ nor " are special characters|}
```

There is also the more guarded form which I'm afraid could be more difficult to make work with syntax highlighting and which might therefore make more sense to track in a separate issue:
```
 {delimiter|the end of this|}quoted string is here|delimiter}
```

**Comment by henrikt-ma** [comment]
Fantastic!  I realized I forgot to mention the combination with [extension nodes](https://ocaml.org/manual/5.1/extensionnodes.html):
> Furthermore, quoted strings {|...|} can be combined with extension nodes to embed foreign syntax fragments. Those fragments can be interpreted by a preprocessor and turned into OCaml code without requiring escaping quotes. A syntax shortcut is available for them:
> ```
> {%%foo|...|}               === [%%foo{|...|}]
> let x = {%foo|...|}        === let x = [%foo{|...|}]
> let y = {%foo bar|...|bar} === let y = [%foo{bar|...|bar}]
> ```
Am I reading the new rules correctly if I think the first two of these are now supported, while the third one along with `{bar|foo|bar}` are still considered unterminated by the syntax processor?

**Comment by deathaxe** [comment]
We somehow need sane rules to distinguish normal `{ ... }` blocks from those `{| ... |}` quotes. Anything beyond the current fix requires deeper investigation about how to do so reliably without breaking other expressions' highlighting.

This would probably require a maintainer for this syntax.
