### ISSUE TITLE
[PackageName] C++ syntax not applying by default

### ISSUE THREAD

**Issue by arjun-prs** [sublimehq/Packages#3977]
### What happened?

Even when i enabled open all .log .cpp files with c++ syntax, the editor is still opening those files in plain text by default.

<img width="786" alt="image" src="https://github.com/sublimehq/Packages/assets/32735294/ffab3cbd-fe50-47db-8d3c-c9330548a627">

<img width="1840" alt="image" src="https://github.com/sublimehq/Packages/assets/32735294/47839e51-6269-4429-8d2d-33f9272631e6">

**Comment by deathaxe** [comment]
If those log files are larger than `"syntax_detection_size_limit"` setting, they are automatically loaded with Plain Text only.

Another possibility would be a plugin dynamically applying syntax after opening file.

That said, syntax definitions in this repository provide sane sets of default file extension associations, but those are not involved in "Open all with current extension as..." ST core functionality, which just applies a syntax-specific setting.

**Comment by arjun-prs** [comment]
Hi,

Is there a way to modify the “syntax_detection_size_limit” field?

--
Regards,
Arjun R
***@***.******@***.***>
Sent from Outlook for Mac.



From: deathaxe ***@***.***>
Date: Thursday, 2 May 2024 at 21:11
To: sublimehq/Packages ***@***.***>
Cc: Arjun R ***@***.***>, Author ***@***.***>
Subject: Re: [sublimehq/Packages] [PackageName] C++ syntax not applying by default (Issue #3977)

If those log files are larger than "syntax_detection_size_limit" setting, they are automatically loaded with Plain Text only.

Another possibility would be a plugin dynamically applying syntax after opening file.

That said, syntax definitions in this repository provide sane sets of default file extension associations, but those are not involved in "Open all with current extension as..." ST core functionality, which just applies a syntax-specific setting.

**Comment by deathaxe** [comment]
Sure. Just open _Preferences: Settings_, copy the setting from left view to the right and edit size value to your needs.
