### ISSUE TITLE
Use stable releases in 3dev

### ISSUE THREAD

**Issue by karolyi** [sublimehq/Packages#398]
Hey,

I just figured 3114 is out, but since I'm on 3dev, I had to install it manually since 3dev doesn't have it.

could you please release the stable in 3dev too in the future? I'd like to keep using 3dev.

**Comment by keith-hall** [comment]
The stable releases are just the latest dev release with a different build number, so you don't miss out on anything by being in the dev channel.

**Comment by karolyi** [comment]
I see. then closing this, thx.
