### ISSUE TITLE
[Lisp] The keyword override the normal variable in some cases

### ISSUE THREAD

**Issue by ccqpein** [sublimehq/Packages#3987]
### What happened?

Hi, I just found the Common Lisp keyword syntax isn't correct. 

Example: 

```lisp
:a-from-b
```

the `from` inside are red as the keyword. However, the whole `:a-from-b` should be the var. I think it comes from the `operator keywords`?  

https://github.com/sublimehq/Packages/blob/3c25c09be470ccfcab059b895bfffe8b0f806e3c/Lisp/Lisp.sublime-syntax#L642

**Comment by deathaxe** [comment]
Can you please provide a more complete example with more context in which you see errors?

That's what it's looking like for me on ST4175:
![grafik](https://github.com/sublimehq/Packages/assets/16542113/f042660e-06f7-4468-94c7-2f94d0b2838b)

**Comment by ccqpein** [comment]
@deathaxe Thanks for your reply and testing on your side! 

I checked around and figured out it was because my installation of Package was wrong. Right after I install the Package/Lisp to the current path, sublime shows me the correct syntax color. 

Thanks
