### ISSUE TITLE
[Haskell] Some tweaks needed on comments

### ISSUE THREAD

**Issue by freinn** [sublimehq/Packages#399]
Hi!

I sometimes develop Haskell programs and I always use ST. There are two errors that I wish to be fixed when you can:

1) When you use the "toogle comment" option of ST, it just inserts two dashes in the beginning of each marked line. There are situations where you get a GHC error for doing this, so I think is better to put two dashes followed by one space on each line, to prevent those errors (sorry I don't find any GHC error use case, I've tried to and all my code compiles :(). Anyways, taking a look on [the Traversable typeclass code on Hackage](https://hackage.haskell.org/package/base-4.8.2.0/docs/src/Data.Traversable.html#Traversable) you can see they put a space after the two dashes on each line. I consider that the best practice for single line comments and I always do it that way.

2) ST does not hightlight well code snippers like:

```
{-
class (Functor t, Foldable t) => Traversable t where
{-# MINIMAL traverse | sequenceA #-}

-- | Map each element of a structure to an action,
-- evaluate these actions from left to right, and
-- collect the results. For a version that ignores
-- the results see 'Data.Foldable.traverse_'.
traverse :: Applicative f =>
(a -> f b)
-> t a
-> f (t b)
traverse f = sequenceA . fmap f
-- | Evaluate each action in the structure from
-- left to right, and collect the results.
-- For a version that ignores the results see
-- 'Data.Foldable.sequenceA_'.
sequenceA :: Applicative f => t (f a) -> f (t a)
sequenceA = traverse id
-}
```
On that code, there is a pragma indicating that the Foldable typeclass must be instantiated implementing one of those two methods. A pragma in Haskell has the form *{-# PragmaName #-}*. But the comments parser that ST uses does not parse that like a pragma expression but like the comment end *-}* and so the highlighting is incorrect. I see on ST code like not commented when it really is, and the code compiles fine.

**Comment by keith-hall** [comment]
After playing around on https://tryhaskell.org/, I can see that:

any `{-` needs to have a closing `-}`, and this includes in nesting.

Works:

- `{- {-# #-} -} 23*36`
- `{- {- #-} -} 23*36`
- `{- {- -} -} 23*36`
- `{- {-# -} -} 23*36`

Indeed, it seems [nested block comments are supported, but only if they aren't followed by a `#`](https://github.com/sublimehq/Packages/blob/master/Haskell/Haskell.sublime-syntax#L188-L198).

@freinn, I can see that this is an easy fix, and I will make a PR in a minute :)

**Comment by freinn** [comment]
thanks @keith-hall, you are so fast xD

**Comment by wbond** [comment]
@freinn Could you perhaps take a look at #110 and perhaps provide some example snippets of code that we could use as tests to prevent regressions on the issue?

**Comment by wbond** [comment]
Actually, as of #400, we now have some basic tests.

Perhaps just confirm that those unicode symbol are in fact, valid replacements for the ascii constructs?

**Comment by freinn** [comment]
sorry @wbond but I don't understand what you want. What unicode symbols? What are those ascii construct? I thought my code was formed by ASCII chars only.
