### ISSUE TITLE
The D Syntax Highlighter Does Not Recognize A Number Of Keywords

### ISSUE THREAD

**Issue by JackStouffer** [sublimehq/Packages#40]
Many keywords in D are not recognized by the default D syntax highlighter and are displayed as regular text. Here is a list of all of the keywords that I have encountered that are not recognized:

* string
* shared
* __gshared
* ref
* immutable
* @safe
* @property
* @trusted
* @system
* @nogc
* pure
* nothrow
* ~~assert~~

~~While the last one is technically a function, the Python highlighter recognizes the assert statement and it would be nice if it was in D as well.~~

Also, it does not recognize long literals like `1_000_000_000` as numbers.

**Comment by FichteFoll** [comment]
The Python `assert` is actually a keyword and designates a statement.

**Comment by JackStouffer** [comment]
@FichteFoll you're right; I guess it could be left how it currently is. 

I should also mention that while `@safe @property @trusted @system @nogc` are all checks enforced by the compiler, there can also be user defined function attributes using the `@` syntax, much like Python. In a perfect world, these five native function attributes would have a different coloring than user defined function attributes, but that would be a purely a "nice to have" feature.

**Comment by JackStouffer** [comment]
Also `synchronized` is marked as a type rather than a keyword.

**Comment by wbond** [comment]
@JackStouffer

As I discovered while looking into #112, the D syntax is rather poor. In addition to the keywords you've found, the detection of methods gets tripped up on `typeof()` and `const()`. Additionally, in some situations `else if ()` is detected as a method definition.

I spent a little time working around some of those issues, however I haven't worked in D very much, so I'm not a very good candidate for making extensive changes.

If you are interested in contributing to the syntax, I can post my current tweaks. Ideally changes should include a test file to ensure we don't regress over time. Here is some more info about the format: http://www.sublimetext.com/docs/3/syntax.html.

**Comment by wbond** [comment]
I've fixed a number of things in b84e922b408a8b6191d3c1ce6be8bc57f75f4594. If you check out the latest version and can provide some samples of any remaining failures so that I can add a test for them, I should be able to get them fixed up.

**Comment by JackStouffer** [comment]
@wbond Cool! How can I use this in my version of sublime so I can test it?

**Comment by wbond** [comment]
@JackStouffer There are some instructions at https://github.com/sublimehq/Packages#installation which should help.

**Comment by JackStouffer** [comment]
Thanks for doing this.

This code sample shows all of the remaining problems:

```
__gshared int a = 5_000;
shared int b = 5_000;

template testTemplate(X)
{
    static if (is(X))
    {
        enum test = true;
        immutable int c = 0;
    }
    else static if (!is(X))
    {
        enum test = true;
        string d = "test";
    }
    else
        enum test = false;
}

@safe pure nothrow @nogc unittest {}

auto takeByRef(ref int a)
{
    synchronized
    {
        a += 1;
    }
}

void main() {}
```

With your changes it appears like this:
<img width="370" alt="screen shot 2016-01-25 at 2 25 05 pm" src="https://cloud.githubusercontent.com/assets/680068/12561694/791aaf52-c36f-11e5-9b91-b2786e01a0f5.png">

This has the following problems:
* both `static if`'s are colored incorrectly
* the attributes `pure` and `nothrow` are not recognized.
* D has user defined attributes (think Python function decorators), which use the `@` symbol; in the example the builtins `@safe` and `@nogc` are used as examples. `pure`, `nothrow`, `const`, and the `@` attributes can be applied to any function, method, or template.
* `shared`, `__gshared`, `ref`, and `immutable` are type qualifiers and are not recognized
* `synchronized` is highlighted as a type rather than a keyword
* `string` is not recognized
* When underscores are added in number literals, which is legal in D, the parser no longer recognizes it as a number literal

I hope this helps!

**Comment by wbond** [comment]
@JackStouffer Are you sure you have the latest version running there? Also, what color scheme are you using?

I see `shared in b` highlighted properly. I also see both `if` statements in `testTemplate` highlighted with the same scope and color.

I'll work on some of the others for now,

**Comment by wbond** [comment]
What is `unittest` in the line `@safe pure nothrow @nogc unittest {}`? It doesn't seem to match any of the existing patterns for struct, class, function, method.

**Comment by JackStouffer** [comment]
I am using the Sunburst theme. Also, I believe I am using the most recent version. I ran this command after `git clone`-ing the repo

```
$ ln -s `pwd`/Packages/D ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/D
```

and restarted Sublime. Am I missing a step?

> What is unittest in the line @safe pure nothrow @nogc unittest {}? It doesn't seem to match any of the existing patterns for struct, class, function, method.

A `unittest` block is, well a block where you put unit tests! D has unit tests as a language feature rather than a library feature. If I wanted to test features of say a sum function, I would do this

```
auto sum(int[] a) {
    //what ever
}

unittest
{
    assert(sum([1, 2, 3, 4]) == 10);
    assert(sum([-10, 5]) == -5);
}
```

The block will be run when the file is compiled with the `-unittest` flag.

**Comment by wbond** [comment]
@JackStouffer Try pull down the latest changes now, and make sure the language you are using is `D`.

I should have all of the examples you provided working properly. You can look at the test file at [D/syntax_test_d.d](https://github.com/sublimehq/Packages/blob/master/D/syntax_test_d.d). It shows the various scopes that are applied to the different tokens in the file.

**Comment by JackStouffer** [comment]
I'll take your word for it that the issues are fixed, so I'll close this. But, I can't seem to get this to work locally.

**Comment by wbond** [comment]
@JackStouffer What version of Sublime Text are you using? You'll need to be used a dev build for these to work: https://www.sublimetext.com/3dev.

**Comment by JackStouffer** [comment]
That fixed it :). Everything looks great 

One nitpick though, the `synchronized` keyword is still highlighted like a type when it's a block declaration. See my code sample above for an example.

**Comment by wbond** [comment]
So synchronized is currently scoped as a `storage.modifier`. Is there a scope from https://manual.macromates.com/en/language_grammars#naming_conventions that you think makes more sense?

**Comment by JackStouffer** [comment]
`keyword.control`, because `synchronized` basically creates an implicit mutext around your code. For example:

```
synchronized
{
    do_something(1, 2);
    something_else();
}
```

Is equal to

```
m = new Mutex;

m.lock();
do_something(1, 2);
something_else();
m.unlock();
```
