### ISSUE TITLE
[PHP] __callStatic is not in the correct scope in its entirety

### ISSUE THREAD

**Issue by mrliptontea** [sublimehq/Packages#401]
**Problem**:
Magic function `__callStatic` is not being highlighted correctly:
the part `__call` has the correct scope - `entity.name.function.php support.function.magic.php`,
but the word `Static` does not - `meta.class.php meta.block.php`.

**Fix**:
In [PHP Source.sublime-syntax](https://github.com/sublimehq/Packages/blob/18a3e29/PHP/PHP%20Source.sublime-syntax#L543) make sure that `callStatic` is being matched *before* `call`.

**Additional**:
Please also correct the spelling of magic method `__toString` (it's all lowercase now), and add support for `__debugInfo`, as listed in [documentation](http://php.net/manual/en/language.oop5.magic.php#object.debuginfo).

**Comment by keith-hall** [comment]
I've added these changes to my [PR here](https://github.com/sublimehq/Packages/pull/385)

**Comment by mrliptontea** [comment]
Thanks! I thought this is too small of an issue to create PR, so that's brilliant.

**Comment by keith-hall** [comment]
The smaller PRs are easier to review ;)

**Comment by mrliptontea** [comment]
I will keep that in mind in the future :wink:
