### ISSUE TITLE
Errors loading syntax files

### ISSUE THREAD

**Issue by xaun** [sublimehq/Packages#402]
Since updating to build 3114, a lot of my syntax files are not loading.

`error: Error loading syntax file "Packages/Ruby/Ruby.sublime-syntax": Apparent recursion within a with_prototype action: 25000 context sanity limit hit`

`error: Error loading syntax file "Packages/Markdown Extended/Syntaxes/Markdown Extended.sublime-syntax": Apparent recursion within a with_prototype action: 25000 context sanity limit hit`

Any ideas? 

Thanks!

**Comment by FichteFoll** [comment]
If there is a "HTML/HTML.sublime-syntax" file in your packcages folder, delete it.

**Comment by xaun** [comment]
Thanks for your reply @FichteFoll, these all the `HTML.` files in my sublime packages and installed packeges files with no `HTML.sublime-syntax` file.
```
10:48:31 ~/Dropbox/App/Settings/Sublime Text 3 $ find . -name HTML*
./Installed Packages/HTML Page Snippets.sublime-package
./Installed Packages/HTML Snippets.sublime-package
./Installed Packages/HTML5.sublime-package
./Packages/HTML
./Packages/HTML/HTML (Angular.js).tmLanguage
./Packages/Rails/HTML (Rails).tmLanguage
./Packages/User/HTML.sublime-settings
```

**Comment by xaun** [comment]
Ok fixed this with a nuke that seems to not have done much damage xD

`find Installed\ Packages/ Packages/ -name HTML* | xargs rm -rf`

**Comment by tisba** [comment]
Seeing this with Sublime 3126 too. Removing `HTML/HTML.sublime-syntax` does not seem to help much. Can you elaborate, on why to delete that specific file, @FichteFoll?

In `/Users/basti/Library/Application Support/Sublime Text 3` I see somewhat similar files:

```
➜ find . -name HTML\* | grep sublime-syntax
./Cache/ASP/HTML-ASP.sublime-syntax.cache
./Cache/Erlang/HTML (Erlang).sublime-syntax.cache
./Cache/Rails/HTML (Rails).sublime-syntax.cache
./Cache/Rails/HTML (Rails).sublime-syntax.rcache
./Cache/TCL/HTML (Tcl).sublime-syntax.cache
```

**Comment by FichteFoll** [comment]
@tisba, it could have been created either by a package or the user themselves when trying to edit the syntax definition at some point. Since it has been updated upstream, this would cause changes to be ignored since an override file exists.
Either way, this didn't appear to be the issue for @xaun. Instead, it is likely that some other HTML flavor provided by a different package included the original HTML syntax in a way that was incompatible and created an infinite loop upon compilation of said file.

Cached files don't really matter in this case.

**Comment by tisba** [comment]
Is there any chance to debug this further? I'm still having this issue.

**Comment by michaelblyons** [comment]
@tisba Is either [this][1] or [this][2] relevant?

[1]: https://github.com/sublimehq/Packages/issues/642
[2]: https://github.com/jonschlinkert/sublime-markdown-extended/issues/141

**Comment by tisba** [comment]
Yes, that helped, thanks, @michaelblyons!
