### ISSUE TITLE
[PHP] Incorrect error highlight for arrow functions that throws in function argument

### ISSUE THREAD

**Issue by Bocom** [sublimehq/Packages#4026]
### What happened?
Using an arrow function that throws an exception as a function argument causes the last parenthesis after the `throw` key to be incorrectly highlighted as an error.

### Code snippet
```php
$exception = new Exception('Test exception');
some_function(fn() => throw $exception);
some_function(fn() => throw $exception, 'some other argument');
```

### Screenshot
![image](https://github.com/user-attachments/assets/d981875c-cadb-4dcf-9d9e-3a831426d5cf)

**Comment by jfcherng** [comment]
Fwiw, `throw ...` is an expression as of PHP 8.0. Previously, it's a statement.
https://wiki.php.net/rfc/throw_expression
