### ISSUE TITLE
[Go] Missing `punctuation.accessor` scope after typing a dot

### ISSUE THREAD

**Issue by imax9000** [sublimehq/Packages#4032]
### What happened?

Minimal example to reproduce:

```go
package main

import "fmt"

func main() {
	fmt.
}
```

When the cursor is right after the dot, `punctuation.accessor` scope is not present, so the default auto-complete trigger for it doesn't work:

![image](https://github.com/user-attachments/assets/67af7dee-633e-4063-9326-4cb9af179512)

Curiously, that scope is present *before* the dot (but only if the dot is already there):

![image](https://github.com/user-attachments/assets/83e3f639-db2f-4060-b6c8-4fbc61af8866)

I'm currently using stable channel, build 4180.

**Comment by imax9000** [comment]
> The "Scope Name" popup displayes scope of tokens after carets. Hence first screenshot displays scope of whitespace after the `.` token. Only `.` token is scoped `punctuation.accessor`, but obviously not the whitespace after - per design.
> 
> Scopes are applied as expected.
> 
> Completions are correctly triggered when typing `.` in SAFE MODE.
> 
> Maybe a plugin is resetting it. LSP for instance adjusts `auto_complete_triggers` to what it gets from language servers.

I've changed `auto_complete_selector` to  `"meta.tag, source variable, source constant"` and completion wasn't triggering for me. (default value of `"meta.tag, source - comment - string.quoted.double.block - string.quoted.single.block - string.unquoted.heredoc"` over-zealous to my taste)

**Comment by deathaxe** [comment]
List item values are fully overridden. So it's likely you just removed `.` trigger.
