### ISSUE TITLE
[JavaScript] Syntax highlighting in function name, params and statement

### ISSUE THREAD

**Issue by jonschlinkert** [sublimehq/Packages#404]
The params, and everything inside the function statement has the same scope (`source.js meta.class.js meta.block.js meta.function.declaration.js entity.name.function.js`), except for the `cacheName` parameter and `.set()` inside the function statement.

<img width="822" alt="screen shot 2016-05-17 at 2 15 29 am" src="https://cloud.githubusercontent.com/assets/383994/15312894/70247432-1bd5-11e6-87c5-28d2ad42b1b4.png">

Here is another screen with more context. All of the function names should be the same scope and color, but some are white, one blue, one green. 

<img width="972" alt="screen shot 2016-05-17 at 2 23 07 am" src="https://cloud.githubusercontent.com/assets/383994/15313030/7a5dd0e6-1bd6-11e6-89b2-a1372ee32d78.png">

The `has` and `get` function names have the scope `source.js meta.function-call.js variable.function.js`, which is the same scope as `require` in `var foo = require('bar');`

Let me know if you need more detail.

**Comment by keith-hall** [comment]
Please can you provide the code snippets as text for easier reproduction (through copy and paste).

**Comment by jonschlinkert** [comment]
No prob, [here is the source](https://github.com/jonschlinkert/fragment-cache/blob/master/index.js#L24-L117)

**Comment by keith-hall** [comment]
Thanks, looks like having a class method named `get` or `set` causes the issue. Seems like an easy fix, I'll make a PR in a minute. :)

**Comment by jonschlinkert** [comment]
> Thanks, looks like having a class method named get or set causes the issue

thanks! fwiw, although that might be true in this case, the highlighting is inconsistent in a number of places since the last patch. I'm holding off creating more issues to see if some of the intermediate fixes resolve some of the inconsistencies. no worries here, you guys are awesome and I appreciate all the work you put into this. I love ST
