### ISSUE TITLE
[Go] Definitions for indexed fmt verbs are incorrect

### ISSUE THREAD

**Issue by kortschak** [sublimehq/Packages#4044]
### What happened?

The definitions for indexed fmt verbs are incorrect; this is driven by the test cases being incorrect. The correct syntax for an indexed fmt verb has the argument indexing immediately before the verb. This is not what the definitions are tested against.

For example, https://github.com/sublimehq/Packages/blob/bc9e712e859054d5d6d82d09755ef559dfe4455c/Go/tests/syntax_test_go.go#L4503
and https://github.com/sublimehq/Packages/blob/bc9e712e859054d5d6d82d09755ef559dfe4455c/Go/tests/syntax_test_go.go#L4506

The syntax shown in the tests can be demonstrated to be incorrect by running the following program (or reading the fmt docs, but this is quicker). In the two examples, the syntax corresponding to the tests here gives incorrect output.
```
package main

import "fmt"

func main() {
	fmt.Printf("incorrect: %[1]+v\n", map[string]int{})
	fmt.Printf("correct:   %+[1]v\n", map[string]int{})
	fmt.Printf("incorrect: %[1]1.2d\n", 1)
	fmt.Printf("correct:   %1.2[1]d\n", 1)
}
```
https://go.dev/play/p/LIFcr4GbQZj
output:
```
incorrect: map[]v
correct:   map[]
incorrect: %!d(BADINDEX)
correct:   01
```

The tests should look like this (with other tests that should also pass added).

```diff
diff --git a/Go/tests/syntax_test_go.go b/Go/tests/syntax_test_go.go
index be5985f3..de540103 100644
--- a/Go/tests/syntax_test_go.go
+++ b/Go/tests/syntax_test_go.go
@@ -4490,6 +4490,9 @@ by accident, but if necessary, such support could be sacrificed.
 //       ^^ constant.other.placeholder.go
     "one %+v two"
 //  ^^^^^^^^^^^^^ meta.string.go string.quoted.double.go
+//       ^^^ constant.other.placeholder.go
+    "one %#v two"
+//  ^^^^^^^^^^^^^ meta.string.go string.quoted.double.go
 //       ^^^ constant.other.placeholder.go
     "one %1.2d two"
 //  ^^^^^^^^^^^^^^^ meta.string.go string.quoted.double.go
@@ -4500,10 +4503,13 @@ by accident, but if necessary, such support could be sacrificed.
     "one %[1]v two"
 //  ^^^^^^^^^^^^^^^ meta.string.go string.quoted.double.go
 //       ^^^^^ constant.other.placeholder.go
-    "one %[1]+v two"
+    "one %+[1]v two"
+//  ^^^^^^^^^^^^^^^^ meta.string.go string.quoted.double.go
+//       ^^^^^^ constant.other.placeholder.go
+    "one %#[1]v two"
 //  ^^^^^^^^^^^^^^^^ meta.string.go string.quoted.double.go
 //       ^^^^^^ constant.other.placeholder.go
-    "one %[1]1.2d two"
+    "one %1.2[1]d two"
 //  ^^^^^^^^^^^^^^^^^^ meta.string.go string.quoted.double.go
 //       ^^^^^^^^ constant.other.placeholder.go
     "foo %*f bar"
```

It's been at least a couple of years since I made a contribution here, and I have no recollection of where to get the testing tools from, and I don't see it in the README.

**Comment by michaelblyons** [comment]
> I have no recollection of where to get the testing tools from,

It's built in. Run a build from the syntax file.

**Comment by kortschak** [comment]
> It's built in. Run a build from the syntax file.

Is there some documentation?

**Comment by michaelblyons** [comment]
https://www.sublimetext.com/docs/syntax.html#testing

**Comment by kortschak** [comment]
@michaelblyons I read that previously. I can see that it says that the tests can be run with the `build` command, but gives no instructions for where that command exists or how to invoke it. The README gives no indication either AFAICS.

**Comment by michaelblyons** [comment]
<kbd>Ctrl</kbd>+<kbd>b</kbd> (Mac: <kbd>Cmd</kbd>+<kbd>b</kbd>)

**Comment by kortschak** [comment]
Ah, that's a nice addition. It might be worth linking to that from the testing page.
