### ISSUE TITLE
[Tcl] Syntax 3114

### ISSUE THREAD

**Issue by cherubrock** [sublimehq/Packages#406]
I encountered this funny bug after updating to 3114.
Context is totally lost. Please see the last switch statement in example.
Its hard for me to identify exactly the root cause. It is a mix of XPath syntax, bracket escaping, parenthesis, and variable dereference with $. I guess the part is causing problems is the one highlighted on image below.
Image:
![image](https://cloud.githubusercontent.com/assets/13544849/15325426/a9d56388-1c4a-11e6-850f-8a2459cdce9e.png)
Tcl file:
[syntax_test.txt](https://github.com/sublimehq/Packages/files/268373/syntax_test.txt)

**Comment by keith-hall** [comment]
It looks to me like the `\[` after `//*` is not recognized as an escape.

**Comment by wbond** [comment]
This should be fixed by a2067ab391c995532576bf9955903dbd36b2c702
