### ISSUE TITLE
C syntax highlighting error

### ISSUE THREAD

**Issue by danieljabailey** [sublimehq/Packages#408]
The following function signature is valid C:

```c++
Glib::ustring Node::_getDragTip(GdkEventMotion */*event*/);
```

Sublime text shows the star-slash-star and the star-slash with a red background.
Adding a space between the first star and the first slash makes it highlight as expected with the comment in grey and no red backgrounds:

```c++
Glib::ustring Node::_getDragTip(GdkEventMotion * /*event*/);
```

presumably this is because it detects an end-comment star-slash and doesn't consider the possibility that it is a pointer definition or dereference when it is followed by a slash.

**Comment by wbond** [comment]
This is fixed by 2439d86dd2ea0e7da3160218e42d1a00fc2fce22
