### ISSUE TITLE
[Ruby] Multiline regex highlighting on ST3

### ISSUE THREAD

**Issue by Victorcorcos** [sublimehq/Packages#4086]
### Description of the bug

The ruby syntax highlighting is not working properly when using regexes.

* Here is the ruby syntax highlighting issue:

[![enter image description here][1]][1]

It looks like multiple issues are happening here.

1. It seems that it interprets string interpolations inside regexes as a comment (`#`) and messes up the whole syntax highlighting from that point on on that line.
2. It seems that the combination of `"` and `'` in the line of the `string_literal` is messing up from that point on until the end of the file. Which is much more serious.

* Here is the example as a code:

```rb
class Tokenizer
  def initialize(expression)
    @expression = expression
  end

  TOKEN_REGEX = /
    (?<whitespace>\s+) |
    (?<parenthesis>[\(\)]) |
    (?<comparison_operator>#{ComparisonNode::OPERATORS.map { |op| Regexp.escape(op) }.join('|')}) |
    (?<logical_operator>\b(?:#{LogicalNode::OPERATORS.join('|')})\b) |
    (?<boolean_literal>\b(?:#{ValueNode::BOOLEAN_LITERALS.join('|')})\b) |
    (?<number_literal>\d+) |
    (?<string_literal>"[^"]*"|'[^']*') |
    (?<identifier>[a-z_][a-z0-9_\.]*) |
    (?<unknown>.)
  /ix.freeze

  def tokenize
    tokens = []
    @expression.scan(TOKEN_REGEX) do
      match_data = Regexp.last_match
      if match_data[:whitespace]
        next
      elsif match_data[:parenthesis]
        tokens << Token.new(:parenthesis, match_data[0])
      elsif match_data[:comparison_operator]
        tokens << Token.new(ComparisonNode::TYPE, match_data[0])
      elsif match_data[:logical_operator]
        tokens << Token.new(LogicalNode::TYPE, match_data[0].upcase)
      elsif match_data[:boolean_literal]
        tokens << Token.new(:literal, match_data[0].downcase)
      elsif match_data[:number_literal]
        tokens << Token.new(:literal, match_data[0])
      elsif match_data[:string_literal]
        value = match_data[0][1...-1] # Remove surrounding quotes
        tokens << Token.new(:literal, value)
      elsif match_data[:identifier]
        tokens << Token.new(FieldNode::TYPE, match_data[0])
      else
        raise "Unexpected character: #{match_data[0]}"
      end
    end
    tokens
  end
end
```

Initially, this is happening with the builtin ruby syntax highlight from the Sublime Text 3 (Version 3.2.2, Build 3211). I tried to install ruby syntax highlighting specific packages that tries to fix this issue, such as [Sublime Better Ruby][2], but without success.

Is there someone with the same issue? If so, how did you fix it?
Thanks!

  [1]: https://i.sstatic.net/IYtFKhwW.png
  [2]: https://github.com/fnando/sublime-better-ruby

### Steps to reproduce

Just add this code to sublime and see the mess happening:

```rb
class Tokenizer
  def initialize(expression)
    @expression = expression
  end

  TOKEN_REGEX = /
    (?<whitespace>\s+) |
    (?<parenthesis>[\(\)]) |
    (?<comparison_operator>#{ComparisonNode::OPERATORS.map { |op| Regexp.escape(op) }.join('|')}) |
    (?<logical_operator>\b(?:#{LogicalNode::OPERATORS.join('|')})\b) |
    (?<boolean_literal>\b(?:#{ValueNode::BOOLEAN_LITERALS.join('|')})\b) |
    (?<number_literal>\d+) |
    (?<string_literal>"[^"]*"|'[^']*') |
    (?<identifier>[a-z_][a-z0-9_\.]*) |
    (?<unknown>.)
  /ix.freeze

  def tokenize
    tokens = []
    @expression.scan(TOKEN_REGEX) do
      match_data = Regexp.last_match
      if match_data[:whitespace]
        next
      elsif match_data[:parenthesis]
        tokens << Token.new(:parenthesis, match_data[0])
      elsif match_data[:comparison_operator]
        tokens << Token.new(ComparisonNode::TYPE, match_data[0])
      elsif match_data[:logical_operator]
        tokens << Token.new(LogicalNode::TYPE, match_data[0].upcase)
      elsif match_data[:boolean_literal]
        tokens << Token.new(:literal, match_data[0].downcase)
      elsif match_data[:number_literal]
        tokens << Token.new(:literal, match_data[0])
      elsif match_data[:string_literal]
        value = match_data[0][1...-1] # Remove surrounding quotes
        tokens << Token.new(:literal, value)
      elsif match_data[:identifier]
        tokens << Token.new(FieldNode::TYPE, match_data[0])
      else
        raise "Unexpected character: #{match_data[0]}"
      end
    end
    tokens
  end
end
```

### Expected behavior

It was expected to highlight the ruby syntax properly without messing it until the end of file.

### Actual behavior

<img width="713" alt="Screenshot 2024-11-05 at 14 53 50" src="https://github.com/user-attachments/assets/31b58ae4-0bcd-4180-8ce2-0d6902e89ac8">

### Sublime Text build number

Version 3.2.2, Build 3211

### Operating system & version

MacBook Pro (Sonoma 14.5 (23F79)), Apple M3 Max.

**Comment by michaelblyons** [comment]
As I understand it, ST3 is out of scope. You may however find that the package in this repo works better than the one shipped with ST3. There may not be any ST4 stuff in it yet.

**Comment by deathaxe** [comment]
Provided example is highlighted without issues on current ST4 releases.

![grafik](https://github.com/user-attachments/assets/debbe657-4309-4c5d-b94b-8333b628b54d)

Syntax definitions in this repo are likely no longer compatible with ST3 as they make use of features, which have been introduced with ST4.

It is not planned to maintain ST3 specific fixes.
