### ISSUE TITLE
[MAT]Scope for global variables

### ISSUE THREAD

**Issue by PeterPablo** [sublimehq/Packages#411]
## MATLAB behavior: global variable is colored
![image](https://cloud.githubusercontent.com/assets/4340267/15395750/4e04fee8-1dd9-11e6-9388-e85059b5268b.png)

## ST3 3114: global variable is not colored
![image](https://cloud.githubusercontent.com/assets/4340267/15395763/57594fee-1dd9-11e6-9ab8-1b641c99f9a9.png)

## Code
```
global MYGLOBAL
local = 1;
MYGLOBAL = local;

```
Is it possible to dynamically apply a scope to global variables, so that they could be displayed with a separate color?

**Comment by FichteFoll** [comment]
Not possible.

**Comment by PeterPablo** [comment]
No, that is no official convention. A pitty! Would make it easier...

**Comment by wbond** [comment]
Unfortunately while the syntax parsers are context sensitive, they do not maintain state in such a way this could be accomplished. Highlighting is done in such a way that a change in the middle of a document does not require re-lexing the whole document, which would be required if some sort of hash table was maintained with such information.
