### ISSUE TITLE
[C++] friend function and stray bracket error

### ISSUE THREAD

**Issue by Zooce** [sublimehq/Packages#412]
I'm seeing an error where having a friend function inside of a class, causes the bracket at the end of that class to be a stray bracket.

![stray_bracket](https://cloud.githubusercontent.com/assets/5490155/15405575/530cf3ae-1db7-11e6-9dbc-43d03cebcc07.png)

I selected the bracket and ran the following in the console:
```
>>> view.scope_name(view.sel()[0].b)
'source.c++ meta.class.c++ meta.block.c++ invalid.illegal.stray-bracket-end.c++ '
```

Here is the same without the `friend` modifier:

![no_stray_bracket](https://cloud.githubusercontent.com/assets/5490155/15405666/b3404ece-1db7-11e6-8caf-7dec2208562c.png)

```
>>> view.scope_name(view.sel()[0].b)
'source.c++ meta.class.c++ meta.block.c++ punctuation.definition.block.end.c++ '
```

**Comment by wbond** [comment]
I can certainly get this fixed, however I need a little better understanding so that I can make the fix properly.

My understanding was that the `friend` modifier was followed by a function or class declaration. This would allow the function or class to access private members.

In the example you provided, `friend` is followed by a function with a body. Currently when `friend` is defined, we don't scope the function or class name in such a way that it appears in the symbol list or index. However, in your example I would think that it should be present in both lists. Is the example with the function body some different sort of construct?

The second example you provided is just a method that accepts another instance of the class `ReallyCool`, correct?

**Comment by Zooce** [comment]
The first example shows the same kind of construct as one with no function body, so the answer to your first question is, no - it's the same construct.

For the second question, I simply removed the `friend` modifier. That code wouldn't actually compile. It should have been something like this:

![no_stray_bracket_no_code_bug](https://cloud.githubusercontent.com/assets/5490155/15434434/adce4d60-1e6b-11e6-8fd7-73c12a16f70d.png)

I wanted to show that it was the keyword `friend` that was causing this issue, and I guess I kind of overlooked the fact that the code in the body didn't make sense without that keyword (my bad).

Thanks for looking into this!

**Comment by Zooce** [comment]
On another note, I actually noticed a side effect of this issue, however, I'm guessing the fix will propagate to this as well, but just in case, the side effect is that the keyword `namespace` seems to be overlooked after the invalid scope. Here's a screenshot:

![stray_bracket_and_side_effect](https://cloud.githubusercontent.com/assets/5490155/15434688/f1f72e52-1e6c-11e6-9dd5-d7629864c176.png)

The interesting thing, is that the namespace identifier, `TooCool` is recognized as a method when the bracket is on a new line, but not when the bracket is on the same line:

```
source.c++ meta.class.c++ meta.block.c++ meta.class.c++ meta.block.c++ meta.class.c++ meta.block.c++ meta.method.c++
```
![stray_bracket_and_side_effect_2](https://cloud.githubusercontent.com/assets/5490155/15435572/ed75bbbe-1e71-11e6-8956-db401c29a8d2.png)

```
source.c++ meta.class.c++ meta.block.c++ meta.class.c++ meta.block.c++ meta.class.c++ meta.block.c++
```

Just for reference, namespaces should look like this for my color scheme:

![namespace](https://cloud.githubusercontent.com/assets/5490155/15435658/6fa3dcba-1e72-11e6-9f5a-c826551e8364.png)

```
# namespace keyword
source.c++ meta.namespace.c++
```

```
# namespace identifier
source.c++ meta.namespace.c++ entity.name.namespace.c++
```

**Comment by wbond** [comment]
This should be fixed by 4bbd538e869025244857ced1aba1ae12baa905b2

**Comment by ooJerryLeeoo** [comment]
@wbond I have this problem too, it's not fix yet

**Comment by ooJerryLeeoo** [comment]
@wbond I have this problem too, it's not fix yet.

**Comment by rwols** [comment]
Can you provide an example where `friend` is not highlighted?

**Comment by ooJerryLeeoo** [comment]
``` cpp
#include <iostream>
class Example {
public:
  friend void example();
  friend bool operator==(const Example &e1, const Example& e2);
};
```

**Comment by rwols** [comment]
![schermafbeelding 2017-07-22 om 16 21 47](https://user-images.githubusercontent.com/2431823/28491949-f0a38044-6ef9-11e7-9917-53d2b5fae0eb.png)

Works fine here. Maybe these changed haven't been merged into a build yet.

**Comment by ooJerryLeeoo** [comment]
Sorry, I forgot the description:

The scope of `example` should be 
```
source.c++ meta.class.c++ meta.block.c++ meta.method.c++ entity.name.function.c++
```
 but it is actually
```
source.c++ meta.class.c++ meta.block.c++
```
and the scope `operator==` has same problem too.

**Comment by rwols** [comment]
Thanks!

There seem to be some strange decisions regarding `friend` in the syntax tests:

```cpp
    friend int func(int a, int b);
/*  ^ storage.modifier */
/*         ^ storage.type */
/*             ^ - entity.name.function */
/*             ^ - meta.function-call */
```
this is inside a class, so `func` should definitely be an `entity.name.function`.

**Comment by ooJerryLeeoo** [comment]
@rwols I just realized my problem is different with this issue, should I open another issue for this ?

**Comment by rwols** [comment]
Yeah, please do that 👍

**Comment by ooJerryLeeoo** [comment]
#1082
