### ISSUE TITLE
[Javascript] Inconsistent scope for `.`?

### ISSUE THREAD

**Issue by michaelblyons** [sublimehq/Packages#414]
The scope in Javascript for the `.` is different depending on whether it is a direct object accessor or an object accessor for a function call:

```javascript
foo.bar().baz
// ^ punctuation.accessor.js
//       ^ keyword.other.accessor.js
```

It seems fishy to me, considering that both cases are object property accessors. However, if it is by-design, I will happily close this issue.

**Comment by wbond** [comment]
This is fixed by 24bc3576dcb57802df31591b0e5b73197248fad8
