### ISSUE TITLE
[JavaScript] Exporting a variable using another name is not highlighted correctly

### ISSUE THREAD

**Issue by ccampbell** [sublimehq/Packages#416]
Example code:

```javascript
import { something as SomethingElse };
export { something as SomethingElse };
```

In Sublime:

![tmyd](https://cloud.githubusercontent.com/assets/259316/15416247/2f69c55c-1e17-11e6-9e47-df5566b8008b.png)

**Comment by wbond** [comment]
This is fixed by e016f401b91a1cfeab0942dce009ccc2501eaf10
