### ISSUE TITLE
[C++] Incorrect indention after preprocessor statements and block comments

### ISSUE THREAD

**Issue by tobiasbrunner** [sublimehq/Packages#417]
The following has been tested with C source and header files and indention using tabs (tab size 4).

For instance, pressing enter on a line containing a preprocessor statement like `#include <stdlib.h>` or `#define XYZ` will cause an indention of a single space on the next line. Pressing tab a few lines further down will also first insert a space and only then tabs, even if the lines in between are empty - but strangely only if the line is empty, if it already contains content a tab is inserted. If a preprocessor statement is indented with tabs itself the next line will just be indented by a single space.

    #include <stdlib.h>
     ^--- this line starts here after a single space
    ^--- pressing tab here will indent by a single space first, then tabs are inserted
    |--- but if the cursor is at the beginning of the line below (following the line above) a tab is inserted
    #include <stdio.h>

        #include <unistd.h>
     ^ --- we end up here (one space indented)

This is very similar for block comments:

    /* asdf */
     ^ --- we end up here instead of
    ^ --- here
    | --- pressing tab here will indent by a single space first

    /**
     * comment
     */
     ^--- we end up here instead of
    ^--- here

**Comment by wbond** [comment]
What version of Sublime Text are you using? I can not reproduce on build 3114, and previously had tried to reproduce on dev build 3110.

**Comment by tobiasbrunner** [comment]
Sorry, should have mentioned that. I use build 3114 (64-bit) on Ubuntu 14.04. To rule out that a third-party package or my own customizations cause it I now moved my config directory and let ST create a new one - and it still happens.

**Comment by tobiasbrunner** [comment]
Just noticed something. We begin our files with a copyright  and license header contained in a block comment:

    /*
     * Copyright ...
     *
     * This program...
     */

If I remove that it doesn't happen anymore for preprocessor instructions or single line block comments. However, adding such a multi-line block comment anywhere in the file starts triggering it again for lines following it.

So it turns out what triggers it are the `^\s+\*.*$` lines, which are not matched by the _unIndentedLinePattern_ of the C++ package. I'll create a pull request.

**Comment by tobiasbrunner** [comment]
Just noticed that this fix is not ideal. Because assigning a value to a pointer will result in lines beginning with whitespace followed by a star:

    int *x;
    *x = 42;

So maybe instead of `|\*|` `|\*\s|` would be better as I guess when dereferencing a pointer there is usually no whitespace between the star and the variable, on the other hand, the star in block comments is usually followed by at least a space.

I don't know how the indention rules work exactly, but they seemed to be scoped. So would it be possible to define separate rules for e.g. `source.c comment.block`?

**Comment by tobiasbrunner** [comment]
It looks like my concerns above might not actually be warranted. Unless a pointer assignment is deliberately indented more than surrounding lines this seems not to be a problem. Even if it is the first statement in a block the lines following in that block are correctly indented (so it seems _increaseIndentPattern_ takes precedence).

**Comment by wbond** [comment]
I ended up reverting this change and fixing it a different way with 3e0faa01dca88b8076bcb3aea879a9d2617d3c66 to handle block comments where each line does not start with a `*`.

**Comment by tobiasbrunner** [comment]
Thanks for the update Will. Unfortunately, that fix doesn't seem to work for me. As soon as there is a line in a block comment that starts with `\s+\*[^/]` lines following the block are indented incorrectly. So perhaps I'm doing something wrong when trying to add these new indentation rules (tried adding the new file in `Packages/User` and `Packages/C++`, neither seems to change anything).
