### ISSUE TITLE
[python, python3] Auto-indentation fails on async functions

### ISSUE THREAD

**Issue by Klim314** [sublimehq/Packages#419]
###Summary

Auto-indentation fails when defining async functions

### Expected behavior
enter after "async foo():" should autoindent next line

### Actual behavior
no autoindent
...

### Steps to reproduce

1. Type async def foo():
2. Press Enter

### Environment

* Operating system and version:
  * [X] Windows ...
  * [ ] Mac OS ...
  * [ ] Linux ...
* Sublime Text:
  * Build 3114

**Comment by Briles** [comment]
I just added #420 which should address this as well as `async for:` & `async with:`
