### ISSUE TITLE
[C++] Function parameters not scoped if arrays

### ISSUE THREAD

**Issue by cschreib** [sublimehq/Packages#422]
The parameter ```param``` in the following function is not identified as ```variable.parameter.c++```:
```c++
void fun(char param[]) {}
```

It's an easy fix. This is because the regex does a lookahead that does not include brackets:
https://github.com/sublimehq/Packages/blob/43baa9b7600c4e21ed2423b1214334b868327898/C%2B%2B/C%2B%2B.sublime-syntax#L821

**Comment by wbond** [comment]
This should be fixed by 4bf48aca8e3ed2ec0c446607ddf408c799ec12b1
