### ISSUE TITLE
[PHP] incorrect snippets and comments shown for HTML inside PHP control structures

### ISSUE THREAD

**Issue by keith-hall** [sublimehq/Packages#424]
A few issues have been reported on the forum, regarding the incorrect snippets and comments being shown for HTML inside PHP control structures.

I think all the PHP snippets (and the HTML autocompletion plugin) need to be updated to use a new scope selector to prevent this problem.

Examples:

- Toggle comment function: https://forum.sublimetext.com/t/toggle-comment-bug-between-php-brackets/20341
- `php` -> `<?php ?>` snippet: https://forum.sublimetext.com/t/php-tag-shortcut-not-available-in-unclosed-tags/20302
- `html` tag autocompletion: https://forum.sublimetext.com/t/3114-php-syntax-highlighting-change/20016/10

You can see in those posts the suggestions I have made about what selector to use, but I'm no expert - maybe someone has some better ideas? :)

**Comment by wbond** [comment]
These should be solved by cd7f8c24ef8c785fc9ff01c1c157beadb35278d8
