### ISSUE TITLE
[PHP/JS] Syntax highlighting - variables and functions (Build 3114)

### ISSUE THREAD

**Issue by Sechgulo** [sublimehq/Packages#427]
Since the latest update the syntax highlighting sets the same color for variables and function calls which is very confusing.
(The same goes for JS syntax)

Before:
![before](https://cloud.githubusercontent.com/assets/7997736/15473665/7c5068de-2101-11e6-9d4c-efdb90c2baeb.jpg)

After:
![after](https://cloud.githubusercontent.com/assets/7997736/15473673/81b4bfaa-2101-11e6-9cf1-b45e749e12e8.jpg)

**Comment by keith-hall** [comment]
What color scheme are you using?

**Comment by Sechgulo** [comment]
Any but for this example [bold](http://colorsublime.com/?q=bold)

**Comment by keith-hall** [comment]
The variables have distinct scopes: `variable.function.php` vs `variable.other.php` so probably the color schemes need to be updated to work with the recent syntax changes, and you should log an issue at the color scheme repos.

**Comment by wbond** [comment]
Unfortunately in the process of improving syntaxes and fixing bugs with them we need to make some changes. Some of these changes are fixing scope names, which is what color schemes use to pick the color to display a given token.

Both PHP and JavaScript have had a major rewrite between build 3103 and 3114. I wouldn't expect such a large change to happen again. So once the color schemes are updated, you should be in good shape.
