### ISSUE TITLE
[HTML] Question: auto_complete_trigger discrepency

### ISSUE THREAD

**Issue by keith-hall** [sublimehq/Packages#438]
In the Default `Preferences.sublime-settings` shipped with Sublime Text, there is the following preference:

```
"auto_complete_triggers": [ {"selector": "text.html", "characters": "<"} ]
```

however, as things stand, triggering HTML auto completion when/after typing `<` has no effect, because:
- The [`html_completions.py` file returns nothing if there is no `prefix` - i.e. nothing typed after the `<` character.](https://github.com/sublimehq/Packages/blob/6a5e2d46d01df3c5da0d3cd181ea62fffdc7aa76/HTML/html_completions.py#L236)

So my question is, was it intended that it would show all available tags? Or is it just in the default preferences to serve as an example of how to configure this preference?

It's presence confused me somewhat, because it triggers even when in a `source` scope i.e. `embedding.php text.html.basic meta.embedded.block.php source.php`, except that the HTML tags are [correctly not listed by `on_query_completions` because the first thing it does is check that it is not in a source scope.](https://github.com/sublimehq/Packages/blob/6a5e2d46d01df3c5da0d3cd181ea62fffdc7aa76/HTML/html_completions.py#L202). However, other plugins may still decide to show completions at this stage, so maybe the preference should be either removed or the selector changed to `text.html - source`?

I thought I would ask about it here, to know whether it is a potential issue that it does not popup a completions window for all HTML tags when typing the <kbd>&lt;</kbd>.

**Comment by sentience** [comment]
This definitely worked (popping up a list of all tags) in Sublime Text 2. I'm currently updating my lynda.com video course for ST3 and was surprised to find this not working in the current build.

**Comment by michaelblyons** [comment]
Is this fixed by recent changes?

**Comment by keith-hall** [comment]
Partially - typing `<` in HTML now shows available tags in the completion popup, but ST still brings up autocomplete when typing `<` in a `text.html source` scope, for example:

- create a new file
- set syntax to PHP
- type `html` <kbd>Tab</kbd>
- <kbd>Esc</kbd> out the snippet field mode
- type `php` <kbd>Tab</kbd>
- type `if (a <` and see autocomplete popup undesirably (correctly without HTML tag suggestions except those from the buffer)

However, this is now a core issue (`Packages/Default/Preferences.sublime-preferences`) so maybe makes sense for me to open a new issue on the core tracker about changing the default `auto_complete_triggers` and close this one.

**Comment by michaelblyons** [comment]
> However, this is now a core issue (`Packages/Default/Preferences.sublime-preferences`) so maybe makes sense for me to open a new issue on the core tracker about changing the default `auto_complete_triggers` and close this one.

Do you think it's the main preferences, or this?

https://github.com/sublimehq/Packages/blob/master/HTML/html_completions.py#L451-L458

**Comment by deathaxe** [comment]
`auto_complete_triggers` are only used to tell ST when to automatically query completions while typing. Plugins need to decide when to offer something. If handling via Preferences a syntax specific `auto_complete_selector` might be a possible solution - or another `default_completions_selector` ?

Already disabled completions to trigger html completions in plain markdown as I found it annoying and useless. Looks like we need to further extend it.
