### ISSUE TITLE
[HTML/XML?] Add meta scopes for tag closing

### ISSUE THREAD

**Issue by FichteFoll** [sublimehq/Packages#442]
#441 just made me aware of the fact that closing tags, at least in HTML, have no meta scope (or otherwise district selector). I would probably be advantageous to have a meta scope for closing tags for example to highlight them in a different color or render them in italics.

**Comment by keith-hall** [comment]
Not sure if you also want a separate scope for self closing tags or not, but just wanted to note that this won't be possible for self closing tags that have the `/>` "punctuation" on a separate line, due to the regexs only being able to see one line at a time.

i.e.

    <foobar
        attr="hello" />

**Comment by FichteFoll** [comment]
Yes, that is why I didn't specifically include self-closing tags as well. I'm not a huge fan of giant look-aheads either, but sometimes they just can't be avoided.

The closing punctuation of the self-closing tag should get a distinct scope however.

**Comment by LeonardoGentile** [comment]
Related to #439?

**Comment by wbond** [comment]
This issue has been solved by a previous commit, hence it is being closed.
