### ISSUE TITLE
SQL highlighting not working when string is inside 2 functions

### ISSUE THREAD

**Issue by MiChAeLoKGB** [sublimehq/Packages#454]
As title says, SQL highlighting does not work when you wrap the statement in 2 or 3 functions (works with 1 or 4+).

Just try this piece of code:

function2(function1("SELECT * FROM table WHERE something='$variable'"));

Here is an image: 
![sublime-sql_highlighting](https://cloud.githubusercontent.com/assets/6197503/15805432/708e5140-2b2a-11e6-9fa3-b1fd78befd05.png)

**Comment by FichteFoll** [comment]
Possibly an occurence of #403.

**Comment by wbond** [comment]
If this is PHP, then I can confirm this will be fixed by dev build 3115.

**Comment by MiChAeLoKGB** [comment]
Yes this is PHP.

I am glad at least this will be fixed, as SQL highlighting kinda sucks really hard in PHP, mainly when you use PHP variables and it just stops highlighting after the double/single quote...

Thanks.

**Comment by wbond** [comment]
Alright, I'm going to close this now, dev build 3115 will contain the fix.
