### ISSUE TITLE
Tcl escaping braces inside a braced string can break Syntax Highlighting

### ISSUE THREAD

**Issue by bitwisecook** [sublimehq/Packages#457]
```tcl
proc somthing {path} {
    set string "blah blah blah blah doesn't matter"
    regsub -all "data " $string "|" string
    regsub -all {\}|\{| |a thing|something \{|\{thing all /Broken/now \{} $string "" string
    regsub -all "\r\n|\r|\n" $string "~" string
}

proc other {broke} {
	puts "still bad here"
}
```

The escaped open braces inside the Tcl string of the second break highlighting of everything following.

<img width="699" alt="thing" src="https://cloud.githubusercontent.com/assets/2267430/15824311/858783e2-2bf6-11e6-929f-9cd8e0a56dad.png">

Sublime Text 3 build 3114

**Comment by bitwisecook** [comment]
Very likely a dupe of https://github.com/sublimehq/Packages/issues/406

**Comment by wbond** [comment]
This is fixed in the current version of the syntax in this repo. It will be part of dev build 3115.

<img width="686" alt="screen shot 2016-06-06 at 1 34 53 pm" src="https://cloud.githubusercontent.com/assets/41734/15831423/95769f46-2beb-11e6-9bad-8e3ee7771294.png">
