### ISSUE TITLE
[R] build system typo

### ISSUE THREAD

**Issue by matthiasdiener** [sublimehq/Packages#471]
There is a typo in the build system for R, in the file https://github.com/sublimehq/Packages/blob/master/R/R.sublime-build

     "shell_cmd": "RScript \"$file\"",

should be 

     "shell_cmd": "Rscript \"$file\"",

with a lowercase "s" in Rscript, as per the [documentation](https://stat.ethz.ch/R-manual/R-devel/library/utils/html/Rscript.html).

This bug prevents people from running R scripts on Linux and probably Mac OS.

**Comment by wbond** [comment]
This is fixed by f9d4da39a53c95ecfa994399d5c1449115e7a469
