### ISSUE TITLE
[LaTeX] lstinline should behave like verb

### ISSUE THREAD

**Issue by mwillsey** [sublimehq/Packages#472]
`lstinline` (from the popular `listings` package for code listings) behaves like a verbatim environment that also highlights code. It should be highlighted like the `verb` macro, but more importantly, things inside the `lstinline` macro should not mess up the highlighting outside of it.

`verb{code with $ symbol} regular words` highlights as expected, with ` symbol} regular words` not put in math mode.

`lstinline{code with $ symbol} regular words` does not highlight this way; instead, the `$` puts you in math mode, breaking the highlighting for the rest of the file until another `$` (which may not exist).

I propose that `lstinline` should just behave identically to `verb`. I wrote a [pull request for this behavior in TextMate](https://github.com/textmate/latex.tmbundle/pull/151); it's a very simple change.

**Comment by wbond** [comment]
Check out #370. There is a massive rewrite of LaTeX in progress.

**Comment by randy3k** [comment]
It has been handled in #370.

**Comment by wbond** [comment]
Alright, I'm going to close this then.
