### ISSUE TITLE
Solarized Light color scheme tweaks

### ISSUE THREAD

**Issue by sunnyps** [sublimehq/Packages#475]
There are a number of issues with the default Solarized Light color scheme:
1. The storage scope has style bold and foreground color #073642 which is the same as the selection background color which means that when you select say "const" in C++ code you cannot read it. I suggest removing the foreground color for storage and just keep the bold style.
2. Even with the above tweak the selection background color is too dark compared to the default foreground text color. I suggest changing the default selection (background) to #586E75 (i.e. the default foreground color) and selectionForeground to #EEE8D5 (a lighter shade of the default background color). This has the effect of (kinda) inverting colors for selected text and matches what this color scheme does in other editors and terminals.

P.S. These colors match what Solarized Light looks like in my terminal.

**Comment by wbond** [comment]
This is not the correct repository for this issue since the built-in color schemes are not currently open source.

I would file it at https://github.com/SublimeTextIssues/Core/issues.
