### ISSUE TITLE
[Python] try Snippets

### ISSUE THREAD

**Issue by buildersbrewery** [sublimehq/Packages#479]
In all 4 Python `try` snippets it says:

```python
except Exception, e:
```

instead of:

```python
except Exception as e:
```

---

The original gave me invalid Python code, the fixed code below worked just fine. Is there anything I am missing?

**Comment by buildersbrewery** [comment]
Compare buildersbrewery/linden-scripting-language@ea7266e.

**Comment by FichteFoll** [comment]
The comma syntax is from Python 2 and has been deprecated, eventually leading to invalid syntax in Python 3. They should be updated for the new syntax since that also works in all relevant versions of Python 2.

**Comment by wbond** [comment]
This is fixed with 103def280a29e15bdb5fea6d702c57518bcd8bfc

**Comment by buildersbrewery** [comment]
Thanks @wbond.

Btw the first seven chars of a hash will do for linking, alternatively `user/repo@hash` for linking to commits elsewhere.

**Comment by wbond** [comment]
Yeah, I just hit the copy button on the commit list :smile:. By grabbing it from there, I double check that I pushed my commits up and others will see them.
