### ISSUE TITLE
Auto-indent configuration?

### ISSUE THREAD

**Issue by djspiewak** [sublimehq/Packages#492]
I've been hunting for any documentation on this, and I just can't find it.  Here's the setup:

```ruby
# ruby
def foo
  |
```

And this…

```scala
// scala
def foo
|
```

The pipe indicates where the auto indentation feature will put the cursor when you press <kbd>Return</kbd> on the `def` line.  Does Sublime just have special magic support for auto-indenting Ruby?  Or is there something in the language configuration that I've missed?

I ask specifically because the auto-indentation settings for Scala are actually kinda terrible.  There are several things that are not auto-indented but should be (e.g. `case .... =>\n`) and a few other things that are excessively indented in an almost Lisp style but which should not be (e.g. anonymous inner classes spread over multiple lines within a function parameter actuals block surrounded by parentheses).

**Comment by michaelblyons** [comment]
Is [this][1] what you're looking for?

[1]: https://github.com/sublimehq/Packages/blob/master/Ruby/Miscellaneous.tmPreferences

**Comment by djspiewak** [comment]
@michaelblyons Yep.  I looked through the `Ruby/` folder and somehow missed that.  Thanks!
