### ISSUE TITLE
Batch file syntax color issues in build 3117

### ISSUE THREAD

**Issue by chaskim** [sublimehq/Packages#495]
With build 3117 (Mac OS X, El Capitan), I get color syntax issues with Windows batch files (.bat). The issues occur with the **set** command when both the variable and value are enclosed in one set of quotes. Only the first set keyword is highlighted properly. Also the space at the end of each line has a filled-in color. Everything was working fine before (3114, I believe is what I was using).

<img width="713" alt="batch" src="https://cloud.githubusercontent.com/assets/12981330/16281064/dbf6e744-38c2-11e6-8dfb-68a7782220b5.png">

**Comment by keith-hall** [comment]
I've done some testing in Command Prompt to see how it handles certain inputs, which should help us decide how to handle them in the syntax definition:

    set "hello"="world"
    set hello
    echo %hello"%

> hello"="world
> "world

    set  foo = bar
    set foo
    echo %foo %

> foo = bar
>  bar

    set  hello world = bar
    set hello world
    echo %hello world %

> hello world = bar
> hello"="world
>  bar

    set abc /a = 1+2
    set abc /a
    echo %abc /a %

> abc / a = 1+2
>  1+2

    set "foobar=test"
    set foobar
    echo %foobar%

> foobar=test
> test

    set test rem = hi
    set test rem
    echo %test rem %

> test rem = hi
>  hi

    set /A hello_world
    echo %hello_world%
    set hello_world

> 0
> %hello_world%
> Environment variable hello_world not defined

    set /A hello_world=7+2
    set hello_world
    set /A hello_world
    echo %hello_world%
    set hello_world=test
    set /A hello_world
    set /A test rem 
    set /A "test rem "

> 9
> hello_world=9
> 9
> 9
> 0
> Missing operator.
> Missing operator.

things to note:

- whitespace before the variable name is ignored, even in quotes
- whitespace between the variable name and the `=` is remembered
- set /A without an equals sign shows the numeric value of the expression. it is an error if the expression contains spaces.

therefore, I think the following tests will all have to pass:

    set "hello"="world"
    :: <- keyword.command
    ::  ^ - variable.other.readwrite
    ::   ^^^^^^ variable.other.readwrite
    ::         ^ keyword.operator.assignment
    ::                ^ punctuation.definition.string.end
    ::                 ^ - string

    set foo=bar
    :: <- keyword.command
    ::  ^^^ variable.other.readwrite
    ::     ^ keyword.operator.assignment

    set  foo = bar
    :: <- keyword.command
    ::  ^ - variable.other.readwrite
    ::   ^^^^ variable.other.readwrite
    ::       ^ keyword.operator.assignment

    set  hello world = bar
    :: <- keyword.command
    ::  ^ - variable.other.readwrite
    ::   ^^^^^^^^^^^^ variable.other.readwrite
    ::               ^ keyword.operator.assignment

    set abc /a = 1+2
    :: <- keyword.command
    ::  ^^^^^^^ variable.other.readwrite
    ::         ^ keyword.operator.assignment - meta.expression.set

    set "foobar=test"
    :: <- keyword.command
    ::  ^ - variable.other.readwrite
    ::   ^^^^^^ variable.other.readwrite
    ::         ^ keyword.operator.assignment
    ::              ^ punctuation.definition.string.end

    set  " foo = bar"
    :: <- keyword.command
    ::   ^^ - variable.other.readwrite
    ::     ^^^^ variable.other.readwrite
    ::         ^ keyword.operator.assignment
    ::              ^ punctuation.definition.string.end

    set test rem = hi
    :: <- keyword.command
    ::       ^^^^^^^^^ - comment
    ::  ^^^^^^^^^ variable.other.readwrite
    ::           ^ keyword.operator.assignment

    set hello_world
    :: <- keyword.command
    ::  ^^^^^^^^^^^ variable.other.readwrite.dosbatch

    set /A hello_world
    :: <- keyword.command
    ::     ^^^^^^^^^^^ meta.expression.set
    ::                ^ - meta.expression.set

**Comment by wbond** [comment]
This should be resolved by 7af3189edac61ec5df0cff45774d65299dd7a026

**Comment by wbond** [comment]
Thanks @keith-hall for all of the examples and testing, that was very helpful.
