### ISSUE TITLE
Bad Haskell syntax colors

### ISSUE THREAD

**Issue by csoroz** [sublimehq/Packages#497]
The default syntax for Haskell shows wrong colors in some situations. Seems to be related with the pattern guards '|' in function definitions: 
[test.zip](https://github.com/sublimehq/Packages/files/329018/test.zip)

-- test.hs

```
max3 :: Int -> Int -> Int -> Int
max3 x y z                      -- wrong colors
    | (x <= z) && (y <= z) = z  -- wrong colors
    | (x <= y) && (z <= y) = y
    | (y <= x) && (z <= x) = z

test :: Int -> Int
test x               -- wrong colors
  | x < 0 = 0        -- wrong colors
  | otherwise = x

test :: Int -> Int
test x =  -- inserting a '=' fix colors
  | x < 0 = 0
  | otherwise = x
```

**Comment by wbond** [comment]
This issue has been solved by a previous commit, hence it is being closed.
