### ISSUE TITLE
Issue with quotes in Rust extern functions when used as a type parameter

### ISSUE THREAD

**Issue by Manishearth** [sublimehq/Packages#499]
If you have the following Rust file:

```
type Foo = Bar<extern "C" fn()>;
```

will cause the first quote to get a red "error" highlight, and a string is started at the second quote, which basically messes up the formatting of everything. This doesn't happen with `type Foo = extern "C" fn()`

cc @wbond

**Comment by wbond** [comment]
This should be fixed by b5ac24ab8ba66aebf32921bfadfcefb1030b684d

**Comment by Manishearth** [comment]
Thanks! :smile:
