### ISSUE TITLE
[C#] Inconsistent comment handling

### ISSUE THREAD

**Issue by OdatNurd** [sublimehq/Packages#501]
I've noticed some instances in which comments in C# code are not handled correctly. I'm by no means an expert in C#, but the compiler seems to accept the code just fine so I assume that it's syntactically correct even though I'm not much of a fan of the style, personally.

In the sample code below, the comments inside the enumeration are broken by the open parenthesis that they contain, which causes the syntax highlighter to assume that the text before are the names of methods; such methods show up in the symbol list as well.

This doesn't seem to be an issue if the comments are not on the same line as the enumeration constant itself however. When the comment is on it's own line or prior to the enumeration constant, it works just fine.

Additionally, the highlighter does not like comments that are (for example) inside the parenthesis of a method's argument list. In this case, the comment is not properly highlighted but otherwise has no adverse effects on anything.

``` C#
namespace Sample
{
    // This seems to work (right?)
    enum SampleEnum
    {
        Value1,  // Comment for Value 1
        Value2,  // Comment for Value 2 (is broken)
        Value3,  /* Comment for Value 3 (also broken) */

        // Works on in this position (like so)
        /* And here (ditto) */ Value4,

        /* And also here (like so) */
        Value5
    }

    class SampleClass
    {
        SampleClass () // This also works (yep)
        {

        }

        void method1 (int value /* Goes here */) // So does this (yep)
        {
            int first;  // The first thing (of two)
            int second; // The second thing (of two)
        }
    }
}
```

**Comment by michaelblyons** [comment]
Maybe related:

```c
foo(bar, (1 + baz));
//^^^^^^^^^^^^^^^^  meta.method-call
//                ^ - meta.method-call
```

**Comment by wbond** [comment]
@michaelblyons The C# syntax has not had a rewrite yet, so I am going to guess there are probably a lot of little issues like this.

That said, I think working on fixing these issues and adding tests is a good idea. That way when the rewrite happens, we can ensure we aren't breaking a bunch of edge cases.

**Comment by FichteFoll** [comment]
There's a PR with a C# rewrite here: https://github.com/sublimehq/Packages/pull/93

I don't know if it fixes the reported issue already. @gwenzek?

**Comment by gwenzek** [comment]
My PR doesn't have this issue.
Comments are treated with a prototype and can be inserted anywhere.

`foo(bar, (1 + baz));` is also highlighted correctly.

**Comment by wbond** [comment]
#93 just landed in master and this issue now seems resolved
