### ISSUE TITLE
python: string formatting support in raw strings

### ISSUE THREAD

**Issue by pdknsk** [sublimehq/Packages#503]
Basically a combination of the first and second line in each example.

![1](https://cloud.githubusercontent.com/assets/1097609/16391870/5b9918ca-3ca9-11e6-8f62-32d59b03e5bc.png)

In the first example, `%s` is ignored, but in the second, `{0}` is incorrectly colored per `re` syntax IMO.

**Comment by FichteFoll** [comment]
`"{0}"` is a format string placeholder in Python's formatting mini-language: https://docs.python.org/3/library/string.html#format-string-syntax

**Comment by pdknsk** [comment]
Yes, that's precisely why I use raw strings, to get nice highlighting. In the second case I still maintain that it's a bug, as `{0}` never becomes part of the regex string, so shouldn't be highlighted as such.

**Comment by FichteFoll** [comment]
There is no way to know parse-time what you intend to do with a string. At the time `{0}` is seen in the string, it is assumed to be a quantifier (http://www.regular-expressions.info/repeat.html) and highlighted as such. You *could* be using `.format` with that, but we don't know that.

This will eventually be solvable with Python 3.6's f-strings that have a definitive syntax `f"string"` and even compining that with r (`rf"raw format"`) requires `{0}` to be interpreted as a format placeholder. Until then, this is not solvable.

**Comment by pdknsk** [comment]
> There is no way to know parse-time what you intend to do with a string. 

It knows `format` is next, so I assume it is either too expensive or complicated. (Of course it does not know what's next as the string is written.)

**Comment by FichteFoll** [comment]
Well, yes, single-line lookaheads are a possibility, but here are a few examples where this might surface:

```
# could use look-ahead
r'{0}[^b]'.format(x)

# cannot, only single-line
(r'{0}[^b]'
 .format(x))

# cannot, only single-line
r"""
{0}[^b]
""".format(x)

# cannot, only single-line
(r'{0}[^b]'
 r''.format(x))

# cannot, obviously
y = r'{0}[^b]'
y.format(x)
```

Besides this one single-line example, this is not possible to implement. And imo consistency is worth more here.

**Comment by pdknsk** [comment]
Hmm yes, this example in particular convinces me. 

> ```
> y = r'{0}[^b]'
> y.format(x)
> ```

(I guess it's theoretically possible with code intelligence.)
