### ISSUE TITLE
[Ruby] Broken Regex scope detection since 3114

### ISSUE THREAD

**Issue by mitio** [sublimehq/Packages#505]
Ruby regular expressions as values of (1.9+ style) hashes are not detected properly as `source.ruby string.regexp.classic.ruby` but only as `source.ruby`.

Example Ruby snippet showing the erroneous scope detection:

```ruby
{foo: /bar/}
```
<img width="262" alt="screenshot 2016-06-28 19 35 55" src="https://cloud.githubusercontent.com/assets/129307/16424163/b2c06d1a-3d67-11e6-9ff5-eba521048f78.png">

The regex in this Ruby snippet is properly detected:

```ruby
{:foo => /bar/}
```
<img width="386" alt="screenshot 2016-06-28 19 37 51" src="https://cloud.githubusercontent.com/assets/129307/16424193/d11ca7e2-3d67-11e6-9777-a163b8efb086.png">

I think this appeared in build 3114 or one version earlier. It's still an issue in 3118.

**Comment by wbond** [comment]
This is resolved by 5f8895514d963e966378b941d62dd0db2ee47262
