### ISSUE TITLE
[Python] == is scoped as keyword.operator.assignment, not keyword.operator.comparison

### ISSUE THREAD

**Issue by MattDMo** [sublimehq/Packages#508]
This tests all the comparison operators:
```python
1 > 2
1 >= 2
1 < 2
1 <= 2
1 == 2
1 != 2
```
Using PythonImproved, everything is scoped correctly:
![comparison pi](https://cloud.githubusercontent.com/assets/1776358/16548782/a40cb624-4164-11e6-821f-6e73d9a0b4d6.png)

However, using the latest `Python.sublime-syntax`, `==` is scoped as `keyword.operator.assignment`, which is orange, as you can see from an actual assignment below:
![comparison ss](https://cloud.githubusercontent.com/assets/1776358/16548803/f80e2d5c-4164-11e6-8c7e-d8f1e87f393f.png)

A PR that I am about to submit fixes this. The old code is
```yaml
320  - match: '='
321    scope: keyword.operator.assignment.python
```
while the fix is simply:
```yaml
320  - match: '=(?!=)'
321    scope: keyword.operator.assignment.python
```

**Comment by wbond** [comment]
Fixed by #509
