### ISSUE TITLE
[PHP] ›› HTML ›› JS ›› PHP   nested syntax highlighting issue

### ISSUE THREAD

**Issue by stev0thegreat** [sublimehq/Packages#510]
### Issue
Within a `.php` document syntax highlighting breaks when:
`php` is used as parameter of a `javascript` function that is used inside of an `html` element's attribute __AND__ is nest in one or more `php` blocks `{ }`.

### Example:
```php
<?php foreach ($arrayOfItems as $item) { ?>
<button type="button" class="btn btn-link btn-remove" onclick="addToCart(event, <?php echo $item['ID']; ?>);"> </button>
<?php } ?>
```

### Screenshot of Syntax Highlighting Issue
![image](https://cloud.githubusercontent.com/assets/3529613/16622055/b04e086c-4366-11e6-85d1-cc91b950893b.png)

### The Likely Culprit
I believe the issue lies with the php closing closing tag `?>` of the `<?php echo $item['ID']; ?>`. The current regex for this must not recognize the `?>` as closing a php statement when nested as it is.

In this context the closing `>` of `<?php echo $item['ID']; ?>` shows the following scope name: 
```yaml
scope: embedding.php text.html.basic meta.embedded.line.php source.php meta.block.php punctuation.section.embedded.end.php
```

When the same code snip for the button is taken out of the context of the php block `{ }` the syntax highlighting retains its integrity and the closing `>` of `<?php echo $item['ID']; ?>` shows the following scope name: 
```yaml
scope: embedding.php text.html.basic meta.tag.inline.form.html meta.attribute-with-value.event.html source.js meta.function-call.js meta.group.js punctuation.definition.group.js
```

I'd love to fix this myself, but I'm a noob to the .sublime-syntax. Until I find more time to sit down with the docs I'm still confused with its flow. If I find time to do so I'll pound out a fix and submit a pull request for this. Till then if anyone has any suggestions for this or can fix it.. THANKS!

**Comment by wbond** [comment]
What version of ST are you using?

**Comment by wbond** [comment]
From my testing, this seems to work properly with build 3118.

**Comment by stev0thegreat** [comment]
DOH! I hadn't even thought of checking the dev builds. I was using the latest stable build: 3114 and pulling latest from this repo. Feelin' ridiculous now :sweat_smile:. I've been flailing helplessly in a sea of text for several weeks. 

I updated to 3118, removed the directory junction I created (per the README), and restarted Sublime. 

All better!!! :tada: Thanks a ton @wbond!
