### ISSUE TITLE
[Regular Expressions] Syntax bug

### ISSUE THREAD

**Issue by Kristinita** [sublimehq/Packages#514]
ST Build 3114, Windows 10.

Text:

```
^((8|\+7)[\- ]?)?(\(?\d{3}\)?[\- ]?)?[\d\- ]{7,10}$  - телефоны

.*?(<img.*?>)</a> — извлечь картинки из тега a

(<a.*?)(target="_blank")(.*?</a>) — убрать target_blank
$1$3
```

![Example1](http://i.imgur.com/drq6Qh7.png)

If I delete `-`:

```
^((8|\+7)[\- ]?)?(\(?\d{3}\)?[\- ]?)?[\d\- ]{7,10}$  телефоны

.*?(<img.*?>)</a> — извлечь картинки из тега a

(<a.*?)(target="_blank")(.*?</a>) — убрать target_blank
$1$3
```

![Example2](http://i.imgur.com/JcfTeYV.png)

If i delete first string, everything is good:

```

.*?(<img.*?>)</a> — извлечь картинки из тега a

(<a.*?)(target="_blank")(.*?</a>) — убрать target_blank
$1$3
```

![Example3](http://i.imgur.com/ttHRGvM.png)

Thanks.

**Comment by michaelblyons** [comment]
What happens when you add a `\` to `[\- ]` to make it `[\\- ]`? And (unless you _want_ a range of `\` to ` `) rearrange it to be something like `[ \\-]`.

Everything after that clause is already broken.
