### ISSUE TITLE
There is no license

### ISSUE THREAD

**Issue by FichteFoll** [sublimehq/Packages#52]
Just a quick reminder that there is no license included in this repo, nor in any file afaik. This is quite an issue, since it legally limits us to only use github to refer to this code, or host it basically, and host modifcations of it, because you granted this right to github when you first pushed the repo. Basically, we can fork it and change our forks. I think.

Disclaimer: not license expert!

There might also be concerns with the .tmLanguage files you likely aquired from other sources that have no license attached to them. While most casual programmers don't care about one or another license, Sublime Text being a commercial and proprietary product and potentially violating licenses is a lot more concerning. I'm just raising awareness on this issue.

**Comment by sublimehq** [comment]
FYI, there is a file called LICENSE in the root directory

**Comment by FichteFoll** [comment]
I swear it wasn't there when I looked for it. I swear...
