### ISSUE TITLE
Goto Symbol on C++ member functions

### ISSUE THREAD

**Issue by JaschaWetzel** [sublimehq/Packages#523]
Member function definitions are not recognized if the fully qualified name contains (legal) whitespace.
Builds 3110 through 3118 are affected.

// Class::foo not recognized
void Class::
foo() {
}

// Class::bar not recognized (fixed in build 3111)
void Class:: bar() {
}

// Class::baz is recognized
void Class::baz() {
}

**Comment by wbond** [comment]
My testing with 3118 indicates example 1 is not currently detected, but example 2 and 3 are.

**Comment by JaschaWetzel** [comment]
Indeed, example 2 was fixed in build 3111.
Also, to be clear, build 3109 handles all 3 cases correctly. So the problem seems to have been introduced in 3110.

**Comment by wbond** [comment]
Yes, the C family of syntaxes was completely rewritten in 3010 to fix numerous issues.

**Comment by wbond** [comment]
This should be resolved by 6a8c97b3c251cbb2485d52058badff465ff9ecde
