### ISSUE TITLE
Minor highlight glitch with javascript syntax when instantiating anon functions

### ISSUE THREAD

**Issue by Francute** [sublimehq/Packages#531]
### Summary

Usually, everytime i write well "function() {}" it gets highlighted with different color to recognize it fast and simply.
But, this not happening when instantiating an anonymous function. And instantiating it inside object declaration mess up a little more.
If i surround the bad highlighted code with () works good, but it makes feel the above code is uncompilable.
I downloaded previous fresh builds and had the same issue.
### Actual behavior

![messeduphighlightedcode](https://cloud.githubusercontent.com/assets/19559862/16894418/ef1951ba-4b2b-11e6-9ee1-3d37ba76b442.png)
### Expected behavior

![goodhighlightedcode](https://cloud.githubusercontent.com/assets/19559862/16894438/68ebe5a2-4b2c-11e6-9993-472fd6d91d8b.png)
### Environment
- Operating system and version:
  - Windows 7 - Service Pack 1 - 64 bits 
- Sublime Text:
  - Build 3114

**Comment by wbond** [comment]
This is fixed by ce8c528e55ec7ff4d0c511f5c6b7109355192d38 and will be part of the next dev build
