### ISSUE TITLE
[Batch File] "shell" scope

### ISSUE THREAD

**Issue by keith-hall** [sublimehq/Packages#535]
`shell` is given a scope in batch files, despite having no special meaning.

Examples:

    python manage.py shell
    adb shell

Trying to execute the command `shell` in Windows 7 CMD gives:

> 'shell' is not recognized as an internal or external command,
operable program or batch file.

So I think the scope should be removed in all circumstances.

**Comment by wbond** [comment]
This should be resolved by 920e5f41181313814ba5319bf19eb69b86854348
