### ISSUE TITLE
python: {{ and }} not handled correctly

### ISSUE THREAD

**Issue by pdknsk** [sublimehq/Packages#536]
![1](https://cloud.githubusercontent.com/assets/1097609/16965297/ce2a9974-4dff-11e6-9618-d4804f0086e2.png)

```Python
>>> print '{{!}}{0}'.format(1)
{!}1
```

**Comment by pdknsk** [comment]
I guess this is somewhat ambiguous.

```Python
>>> re.search('{{1}}{1}', '{}').group()
'{}'
```

**Comment by FichteFoll** [comment]
If there is support for formatting placeholders by default, the placeholder excapes should also be highlighted imo. I guess this qualifies as a "bug".

Two consequtive braces are rare enough not to be confused with two actual literal braces. But `{}` is already highlighted anyway (for good reason).
