### ISSUE TITLE
<script> in PHP comments should not trigger JavaScript context

### ISSUE THREAD

**Issue by Krinkle** [sublimehq/Packages#537]
Whenever the a `<script>` is mentioned in an inline or block comment in PHP, Sublime triggers JavaScript context which causes linters to start adding warnings all over.

<img width="951" alt="screen shot" src="https://cloud.githubusercontent.com/assets/156867/16970315/0c5eb104-4e13-11e6-8522-73e1410fe149.png">

Is there a way to resolve this?

* Sublime Text 3 (Stable Channel, Build 3114) 
* Package Control v3.1.2
 * SublimeLinter v3.7.4
 * SublimeLinter-jscs v2.2.0
 * SublimeLinter-jshint v1.2.1
 * SublimeLinter-contrib-eslint v1.10.0

**Comment by wbond** [comment]
Please try dev build 3118.

**Comment by wbond** [comment]
I don't believe this is a bug with the current version of the PHP syntax - the comment and surrounding code appear to be scoped and highlighted correctly. You can try dev build 3118 to see if it helps SublimeLinter in some way.

If you are seeing it with 3118 and you believe there is an issue with the PHP syntax, please open a new issue with the complete contents of the file that triggers it, plus the scope names of the area you are seeing the trouble with.
