### ISSUE TITLE
python: Syntax Highlighing Multi-line Strings (Possible Regression)

### ISSUE THREAD

**Issue by ishunyu** [sublimehq/Packages#538]
Sublime (Build 3114) seems to have trouble syntax highlighting this piece of code. I see red strips after the characters on the first two lines. The code is runnable. I believe I didn't see this happening until about a few months ago after a Sublime upgrade.

```
s = "Hello \
World!"

print s
```

<img width="286" alt="screen shot 2016-07-19 at 4 53 58 pm" src="https://cloud.githubusercontent.com/assets/1459666/16970511/6e465b98-4dd1-11e6-8bcb-f3f83fa32f13.png">

**Comment by wbond** [comment]
Please try dev build 3118.

**Comment by ishunyu** [comment]
Ah sorry but I don't have a license for the dev builds.

**Comment by FichteFoll** [comment]
https://github.com/sublimehq/Packages/issues/396

**Comment by ishunyu** [comment]
Cool, looks like it's been worked on. Feel free to close.
