### ISSUE TITLE
Bad coloring for Perl regexes beginning with a space

### ISSUE THREAD

**Issue by zort** [sublimehq/Packages#541]
Perl regexes beginning with a space (or any whitespace) don't get colored properly. I'm using build 3114.

Good:
![1](https://cloud.githubusercontent.com/assets/535865/17036390/1cd045aa-4f5a-11e6-9cb8-7be0889119d1.PNG)

Bad:
![2](https://cloud.githubusercontent.com/assets/535865/17036396/20990ab4-4f5a-11e6-8e35-3f8081deae4e.PNG)

Worse if you have a tilde before:
![3](https://cloud.githubusercontent.com/assets/535865/17036410/2e41f4b4-4f5a-11e6-89d3-5ae3aac6ee92.PNG)

I think the culprit is this regexp: https://github.com/sublimehq/Packages/blob/a493e90787e876d4f221e2bf621b47cb3505b99a/Perl/Perl.sublime-syntax#L342

To anyone else who runs into this, I solved it by installing https://packagecontrol.io/packages/ModernPerl and doing View > Syntax > Open all with current extension as ... > ModernPerl.

**Comment by wbond** [comment]
Yes, regex literals can be kind of a pain. We fixed them in JavaScript by tracking the state more explicitly, so a `/` following an operator or other non-identifier is considered the start of a regex, and never a division operator.

The rules are slightly more complicated than that to deal with them being passed as parameters, and allowing division to happen on function call return values, but you get the idea.
