### ISSUE TITLE
[Java] String syntax highlighting issue.

### ISSUE THREAD

**Issue by mgarrettm** [sublimehq/Packages#542]
Hi, I think I found a Java string highlighting issue. It seems to be related to combining inline array initialization with strings. In the following code:

```
public class Bug {
    public static void main(String[] args) {
        func(new int[0], "Hello World!");
        func((new int[0]), "Hello World!");
        int[][] arr = new int[1][0];
        func(arr[0], "Hello World!");
    }

    public static void func(int[] arr, String str) {
        System.out.println(arr.length + " " + str);
    }
}
```

"Hello World!" in the first func invocation is not highlighted as a string, whereas the second and third "Hello World!" occurrences are highlighted correctly. Here is a screenshot of the highlighting in the code above:

![image](https://cloud.githubusercontent.com/assets/1860008/17050010/72855ad0-4fa5-11e6-82c3-3b2c2e1179ac.png)

**Comment by wbond** [comment]
Thanks for the bug report!

**Comment by wbond** [comment]
This issue has been fixed by some recent work on the Java syntax. The fixes will be part of the next dev build.
