### ISSUE TITLE
[LaTeX] Wrong highlighting of $ inside \path command

### ISSUE THREAD

**Issue by merlinthered** [sublimehq/Packages#544]
Using a $ inside a \path command leads to the following text being highlighted as math mode. This is incorrect. \path takes special characters as-is, just like the \url command provided by the hyperref and url packages.

I have created a pull request #543 for a straight-forward fix. I would be interested if anyone is aware of any side effects this might have. Perhaps there are other packages that also define the \path command, which behave differently?

**Comment by wbond** [comment]
#543 has been merged, closing
