### ISSUE TITLE
[JavaScript] Scopes brake after certain input

### ISSUE THREAD

**Issue by rchl** [sublimehq/Packages#553]
Sublime 3 build 3119
```
([a,
  b]) => {
  // Everything after this point has broken scopes.
  let a = this.a(a, b);
  let b = this.a.b;
  let c = new Set(xxx.map(x => A.b(x.y)));
  for (let i of [l, m]) {
    c.push({a: x, b: y});
  }
  console.log(`Aaaa ${b.map(s => s.y).join(' ')}`);
  this.a.b = c;
}
```
Removing linebreak from the first line fixes the problem.
More sensible example would look more like:
```
Promise.resolve().then(...snippet...);
```
but I've tried to simplify it as much as possible.

**Comment by wbond** [comment]
Yes, unfortunately Sublime Text (for performance reasons) only scans one line at a time when tokenizing, and arrow functions require a lookahead to find the `=>`. Since you've broken that onto another line, it is unable to tell it is an arrow function.

**Comment by FichteFoll** [comment]
The `=>` sequence shouldn't be valid for anything else, so matching it as a parameter-less function should suffice to fix the issue.

**Comment by wbond** [comment]
The issue is the parens before are the parameters, so if we wait for =>, we've already failed.

**Comment by FichteFoll** [comment]
Yes, I realize that. Still better than what happens now.

**Comment by wbond** [comment]
As of 32f692e207358ebc5736d184ab0c8364903959c0 we no longer fail spectacularly, but we also can't detect `a` and `b` as parameters.
