### ISSUE TITLE
[Ruby] Regex matching never ends when escaping a parenthesis

### ISSUE THREAD

**Issue by pgrippi** [sublimehq/Packages#555]
Version: Sublime Text 3, Dev Build 3119

When using a regex and escaping a parenthesis the regex scope never ends: (cursor is at the end of line 3)

![screen shot 2016-07-26 at 3 37 37 pm](https://cloud.githubusercontent.com/assets/1180841/17152864/ca71bc70-5347-11e6-811c-fd7061f3ebf3.png)

If I remove the paren it correctly highlights the next line:

![screen shot 2016-07-26 at 3 44 45 pm](https://cloud.githubusercontent.com/assets/1180841/17152885/e60adafc-5347-11e6-8d81-68fc8d87fb55.png)

Example code:

```ruby
['a()', 'b()'].select { |var| /^a\(/ =~ var }
[1, 2, 3]
```

**Comment by FichteFoll** [comment]
Related: https://github.com/sublimehq/Packages/issues/505

**Comment by wbond** [comment]
This is resolved by b42da58d75f1516aad37a4ac0833e0232e9145d9
