### ISSUE TITLE
JavaScript syntax highlighting issue

### ISSUE THREAD

**Issue by caub** [sublimehq/Packages#556]
The following valid javascript expression `const test = ({a, b, c=()=>({active:false})})=> {}`

![image](https://cloud.githubusercontent.com/assets/3134574/17156158/9fca9848-5388-11e6-93eb-43e5172a4faa.png)

isn't highlighted correctly at the end, it stays in pink

**Comment by wbond** [comment]
This should be resolved by bbc49d9721dfb7f9151062d7422eb9a7a3879647
