### ISSUE TITLE
bug in latex syntax highlighting, since 3093

### ISSUE THREAD

**Issue by pierodancona** [sublimehq/Packages#56]
Is it just me?

![screenshot 2015-07-05 00 06 19](https://cloud.githubusercontent.com/assets/2694041/8509571/3ea2aab6-22aa-11e5-90b8-cb0723a71faa.png)

**Comment by kleinfreund** [comment]
No, I can confirm this.

**Comment by TheClams** [comment]
I was looking at it and it is surprising it ever worked: the match for end exists but there is no capture part to assign scope ...
This is true for many begin/end block: the file is small enough that i should be able to look at all of them and propose a complete fix today

**Comment by FichteFoll** [comment]
This is most likely a result from converting the syntaxes (#23) and the old syntax using "captures" for both begin and end captures, which was not converted correctly (i.e. not added to the pop match).

**Comment by aziz** [comment]
> This is most likely a result from converting the syntaxes (#23) and the old syntax using "captures" for both begin and end captures, which was not converted correctly (i.e. not added to the pop match).

YES! I've also seen bug in some other languages, namely Ruby, and I send some PRs to fix them in the past. like [this one](https://github.com/sublimehq/Packages/commit/043923ccefe38f09ffad3370346b9f3b615f85c0)

I've just discovered another subtle one that end part of punctuation in interpolated strings in ruby does not get the scope. same issue!

I hope Jon see this and fix the converter and reapply all those scopes to the pop match as well.

**Comment by FichteFoll** [comment]
Yes, all tmLanguage files from before #23 need to be recovered and reconverted. Hopefully without merge conflicts.

**Comment by jrappen** [comment]
I added PR #23 and wasn't aware of this issue. Hopefully it'll be reverted and redone properly.
