### ISSUE TITLE
[Scala] "new Foo" highlighted as entity.name

### ISSUE THREAD

**Issue by djspiewak** [sublimehq/Packages#560]
I have a fix for this locally that is part of a broader overhaul of type highlighting.  Just filing this bug to make the issue known.

`new` in Scala is purely instantiation, not declaration, so the correct highlighting for `Foo` in `new Foo` would be `support.class` or `support.type`.  `new` *can* declare new classes, but these classes are anonymous (identical to Java/C# semantics) and do not have a name.

**Comment by wbond** [comment]
I believe this was fixed in #563
