### ISSUE TITLE
Ruby syntax parsing error

### ISSUE THREAD

**Issue by phts** [sublimehq/Packages#564]
```
error parsing lexer: Packages/Ruby/Ruby.sublime-syntax: expected match or include at line 1452 column 7
```

Error on the [line 1452](https://github.com/sublimehq/Packages/blob/master/Ruby/Ruby.sublime-syntax#L1452) and Ruby is missing from the syntax selector.

This happens since #466 has been merged. If I revert commit 1dbd645 locally then everything works fine.

----

Tested: ST3 build 3114 (Debian and Windows 7)

**Comment by phts** [comment]
As I understood that pull request contains a new syntax that will be supported by 3115 and is not supported by 3114.

But why have you merged it to master if 3115 is not released yet?

**Comment by FichteFoll** [comment]
There is a dev release channel which is at 3120 already and can be downloaded here: http://www.sublimetext.com/3dev. It requires having a license.

**Comment by wbond** [comment]
The readme indicates that you will likely need the latest dev build to use the syntaxes, so I don’t think there is anything to fix here.
