### ISSUE TITLE
[Shell] Apparent recursion within a with_prototype action

### ISSUE THREAD

**Issue by BarbUk** [sublimehq/Packages#565]
I have this error with version 3119 and 3120 with any bash script:

error: Error loading syntax file "Packages/ShellScript/Shell-Unix-Generic.sublime-syntax": Apparent recursion within a with_prototype action: 25000 context sanity limit hit.

**Comment by keith-hall** [comment]
Have you overridden any packages? It works for me in 3120. 

Similar problems were [reported on the forums](https://forum.sublimetext.com/t/syntax-highlighting-problem-with-3113-apparent-recursion-within-a-with-prototype-action-25000-context-sanity-limit-hit/19914/21) for people overriding the HTML syntax definition. The issue there was for PHP, but Shell also includes the HTML syntax amongst others so is likely related.

**Comment by BarbUk** [comment]
Yep, I just reverted to a clean install and don't have the problem anymore.
I will try to find the culprit, but I don't have any overridden packages.

**Comment by BarbUk** [comment]
I found the problem, in my preferences.sublime-settings, i have this block:
```
 "ignored_packages":
[
     "Markdown",
     "Vintage"
],
```
If I remove the Markdown package from here, the problem goes away.

**Comment by BarbUk** [comment]
I don't have the error with build 3118 and the Markdown package ignored.
The error is visible in 3119 and 3120 but goes away if remove the markdown package from ignored_packages.

I don't remember adding anythings in ignored_packages.

Should I report that upstream in the sublime text issues tracker ?

**Comment by keith-hall** [comment]
I just added Markdown to my ignored_packages list and didn't get this problem in 3120.

Do you perhaps have any Markdown related packages installed via Package Control (maybe they override the `text.html.markdown` scope)?

**Comment by deathaxe** [comment]
Have realized the same issue. In my case I replaced "Markdown" with "Markdown Extended". As soon as I disable "Markdown Extended" the world is ok.

**Comment by BarbUk** [comment]
@keith-hall yes, I have "Markdown Extended".
If I remove this package, the problem is gone.

I'm going to close this issue and report it to https://github.com/jonschlinkert/sublime-markdown-extended

Thanks

**Comment by BarbUk** [comment]
see https://github.com/jonschlinkert/sublime-markdown-extended/issues/138 to follow on this issue.

**Comment by hypergig** [comment]
Today I ran into...
```
Error loading syntax file "Packages/ShellScript/Shell-Unix-Generic.sublime-syntax": Apparent recursion within a with_prototype action: 25000 context sanity limit hit
```
...and removing `Markdown` from my preferences.sublime-settings fixed it.  

I also have markdown extended and am with st3 > 3118
