### ISSUE TITLE
[Tcl] syntax format issue

### ISSUE THREAD

**Issue by rjorgs** [sublimehq/Packages#567]
I noticed this after the [Tcl Syntax Rewrite](https://forum.sublimetext.com/t/tcl-syntax-rewrite-feedback/19891), where the formatting is quite off.  I've found a workaround to place commented open quotations (#") throughout my scripts to correct it, but that gets annoying.  Here's an example:

This...

![screen shot 2016-08-03 at 10 38 51 am](https://cloud.githubusercontent.com/assets/4334050/17371753/b8d496d4-5966-11e6-8708-3ad7d0a3283f.png)

Should look like this...

![screen shot 2016-08-03 at 10 39 40 am](https://cloud.githubusercontent.com/assets/4334050/17371764/c0af17d0-5966-11e6-8e66-17d19808818b.png)

[tcl_format_sample_code.tcl.zip](https://github.com/sublimehq/Packages/files/399794/tcl_format_sample_code.tcl.zip)

**Comment by wbond** [comment]
This should be fixed by be5074affc52a2b0a2ae84b634a3dab2671ac6a9
