### ISSUE TITLE
[Python] Can't collapse function when arguments are placed on several lines

### ISSUE THREAD

**Issue by vient** [sublimehq/Packages#569]
Example:
```python
def func(
        longArgumentName1,
        longArgumentName2,
        longArgumentName3,
        longArgumentName4,
        longArgumentName5):
    ret = 2 + 2 * 2
    return ret
```
collapses to
```python
def func(...
    ret = 2 + 2 * 2
    return ret
```
It happens with all combinations of parameters of different lines, the only working case is when everything is on one line like usual `def f(a, b, c, d):`.

Build 3114.

**Comment by keith-hall** [comment]
Code folding is indentation based and not syntax related...

You could write it like this so that it will fold the entire function, although it is not as readable:

    def func(
        longArgumentName1,
        longArgumentName2,
        longArgumentName3,
        longArgumentName4,
        longArgumentName5
        ):
        ret = 2 + 2 * 2
        return ret

**Comment by vient** [comment]
> Code folding is indentation based and not syntax related...

Ouch, folding worked so good previously that I always thought it's based on syntax. So it's not an issue in this case I guess.
