### ISSUE TITLE
[PHP] SQL Syntax highlighting breaks at first appearance of matching quote

### ISSUE THREAD

**Issue by 2mnyzs** [sublimehq/Packages#572]
```
<?
$query_1 = "SELECT * FROM Database.dbo.test WHERE 1=1;";
$query_2 = "SELECT * FROM ".DATABASE_MAIN.".dbo.test WHERE 1=1;";
```

![image](https://cloud.githubusercontent.com/assets/6033112/17415172/3c6db290-5a4e-11e6-8dfd-4f434f463fb7.png)

I'm not sure how feasible it would be for syntax highlighting to cover everything between the assignment operator(=) and instruction terminator(;) during an assignment but I(and my team) would greatly appreciate it.

Regardless of feasibility, thanks for an amazing product!

**Comment by FichteFoll** [comment]
Not feasable in my opinion. Normally I'd say "use prepared statements" but I'm not sure if you can insert the table name using that.
