### ISSUE TITLE
[Scala] Scope clearing in interpolated strings has no effect

### ISSUE THREAD

**Issue by djspiewak** [sublimehq/Packages#580]
It's just clearing the wrong number of scopes.  If you change the `1` to a `2`, it works fine.  At present though, it has no effect on the resulting scopes, which means that interpolated string highlighting is… not very useful.

**Comment by wbond** [comment]
Can you provide an example?

**Comment by djspiewak** [comment]
This test fails:

```scala
s"testing ${things} and more!"
//          ^^^^^^ - string
```

So in practice, the whole string ends up being colored identically by most schemes, which is unsurprising since `things`, `testing` and `and more!` all have the same scope.

**Comment by wbond** [comment]
Which version of the `.sublime-syntax` are you working from?

**Comment by djspiewak** [comment]
> Which version of the .sublime-syntax are you working from?

At present, my unmerged branch (#563), but swapping to master quickly reproduces the same issue.

**Comment by wbond** [comment]
Seems to be functioning properly if `1` does not clear `string`, but `2` does.

I presume it is this rule: https://github.com/sublimehq/Packages/blob/master/Scala/Scala.sublime-syntax#L410

With a value of `1`, that will clear https://github.com/sublimehq/Packages/blob/master/Scala/Scala.sublime-syntax#L404.

With a value of `2` it will also clear https://github.com/sublimehq/Packages/blob/master/Scala/Scala.sublime-syntax#L388.

**Comment by djspiewak** [comment]
The reason I opened the bug was not to complain about `clear_scopes` not being functional, but to track the fact that the Scala mode doesn't currently use it correctly.

**Comment by wbond** [comment]
Ok, I'll reopen.

**Comment by wbond** [comment]
This seems to have been fixed by #563
