### ISSUE TITLE
Split Packages respoitory into individual package repositories

### ISSUE THREAD

**Issue by gerardroche** [sublimehq/Packages#584]
There was discussion about this while back, I can't find it.

Some reasons I'd like to see the repository split into individual packages.

* Easier to maintain only relevant specific packages without the noise of everything else
* Easier for package authors to monitor only relevant packages without the noise of everything else
* Easier to work on and develop a package by simply cloning it into the Sublime Packages directory
* Easier to port a development versions of packages version by adding them as a [submodule](https://github.com/gerardroche/sublimefiles) to dotfiles

**Comment by wbond** [comment]
Honestly, trying to keep up with 30 different issue trackers and lists of pull requests would just reduce the amount of time I have to deal with the packages, resulting in slower progress.

**Comment by gerardroche** [comment]
The reason I'm asking is I want to remove a custom PHP syntax from one of packages and default to the default PHP one which is going through lots of changes and breaking some things. 

I'm trying to decide if I want to bother trying to keep the package up to date with the default one. 

Right now the PHP package is only one I'm interested. Maybe also the HTML one. The noise of this repository is a lot.

**Comment by wbond** [comment]
Now that the PHP syntax has been rewritten, I don't foresee many changes. Likewise HTML has had significant work, and it in pretty good shape.

There are a number of syntaxes that will see significant work moving forward, but a bunch have been modernized already.

**Comment by gerardroche** [comment]
That's good. 

The package I want to remove the custom syntax from is [php-grammar](https://github.com/gerardroche/sublime-php-grammar). It adds quiet a few features and fixes to PHP that the default package doesn't have. The syntax is no longer near compatible with the default one so the fixes and features can't be easily ported.

Can you make definitive decision about splitting the packages? I mentioned that it could be done on a case by case basis. Having thought about it, if  they will be split, then it's probably better to split them all sooner than later. Otherwise it just causes issues later like moving issues from the issue tracker.

**Comment by wbond** [comment]
Considering it is just Jon and I on the SublimeHQ side, and there is plenty for us to do, I don't think adding overhead would be wise at this point. I don't want to slow development down, or spend more time juggling through UIs that aren't designed for our use case.

Thus, my answer would be no, I don't believe splitting the repos would be good.

**Comment by gerardroche** [comment]
Cool. Thanks.
