### ISSUE TITLE
[Tcl] line break 

### ISSUE THREAD

**Issue by chubio** [sublimehq/Packages#585]
I sometimes write dictionaries in a way similar to the following one so it is relatively clean to read.
```
set MyDict [list\
    Key1 {Key Value 1}\
    Key2 {Key Value 2}\
    Key3 {Key Value 3}\
    Key4 {Key Value 4}\
]
```
After the  Tcl Syntax Rewrite, the '\' characters used to break the single command into multiple lines are marked as invalid.illegal.tcl when placed right next to the '}' characters. I think this is valid Tcl and my Tcl interpreter takes it just fine. Thanks

**Comment by wbond** [comment]
This should be fixed by be5074affc52a2b0a2ae84b634a3dab2671ac6a9
