### ISSUE TITLE
Reindent adding 1 extra tab on every line

### ISSUE THREAD

**Issue by Radivarig** [sublimehq/Packages#592]
Using `sublime-text-dev 3.3114-1` on `Arch Linux` and **reindent** inserts a `\t` tab character before every line

![sdfdsf](https://s4.postimg.io/qesen0jwt/Screenshot_20160818_201107.png)

**Comment by wbond** [comment]
Seems to be working fine with dev build 3120. I believe it was fixed by dee518c94e1ec45666d8571d37af4c36b0617bc2, which was part of dev build 3115.
