### ISSUE TITLE
[LaTeX] Quotation mark followed by closing angle bracket causes highlighting bug

### ISSUE THREAD

**Issue by jeanineharb** [sublimehq/Packages#608]
Hi,

When using the `\begin{minted}` block, the symbols `">` at the end of the line (quotation mark and closing angle bracket) change the color of the highlighting. The syntax coloring breaks from that point until the end of the file.

![screen shot 2016-08-30 at 1 09 03 am](https://cloud.githubusercontent.com/assets/7924513/18069243/66bb1a10-6e4e-11e6-9456-796ecf62b99c.png)

The issue was previously documented here: https://forum.sublimetext.com/t/latex-highlighting-bug/13106

**Comment by randy3k** [comment]
#370 has fixed the root of this issue, however, embedding xml is not supported yet.
