### ISSUE TITLE
[PHP] Nested functions

### ISSUE THREAD

**Issue by jbrooksuk** [sublimehq/Packages#612]
PHP nested functions are still highlighting incorrectly.

![](https://cldup.com/4zY-bT8Xd7.png)

The code is just a normal class, with some nested functions.

**Comment by wbond** [comment]
Can you provide the source file? The scopes appear to indicate three levels of embedding, but the screenshot doesn't.

Also, what version of ST?

**Comment by scottkimGit** [comment]
I have a similar case here. The test code is:

```
<?php
class A {

    public function someFunc()
    {
        $this->someMethod(
            function ($arg) {
                $this->someMethod(
                    function ($arg) {
                        $this->someMethod(
                            function ($arg) {
                                if ($arg === 1) {
                                    echo "Syntax highlighting breaks\n";
                                } else if ($arg === 2) {
                                    $this->someMethod(
                                        function ($arg) {
                                            if ($arg) {
                                                echo "Syntax highlighting works again";
                                            }
                                        }
                                    );
                                }
                            }
                        );
                    }
                );
            }
        );

    }

}
```

![php syntax highlighting issue](https://cloud.githubusercontent.com/assets/76902/18692045/e7158f90-7fda-11e6-863c-144706f619b7.png)

**Comment by wbond** [comment]
Are you using build 3122? I can't replicate the issue there, although I'm not sure which color scheme you are using. I tried Monokai and Base16 eighties dark.

**Comment by wbond** [comment]
This seems to be visually similar to #431, which was fixed with build 3116.

**Comment by scottkimGit** [comment]
I'm using the build 3114

The theme is:
"theme": "Lanzhou.sublime-theme",
"color_scheme": "Packages/Theme - Lanzhou/base16-ocean.dark.tmTheme"

If it's been already fixed, then I will wait for the stable release.

Thanks.

**Comment by wbond** [comment]
If anyone has issues with build 3126, please open a new issue. (I am unable to replicate.)
