### ISSUE TITLE
[JavaScript] Constructor invocation not recognized

### ISSUE THREAD

**Issue by rchl** [sublimehq/Packages#615]
Only first variant is scoped properly. Rest doesn't have `meta.instance.constructor.js` scope or other related ones.

```
new Foo(1);
new function() {}(1);
new class Foo {}(1);
```

**Comment by wbond** [comment]
These are fixed by feea2d8fa93d64b7fb0d8d37aece3b95a7bbb067 (which supersedes ce8c528e55ec7ff4d0c511f5c6b7109355192d38). They will be part of the next dev build.
