### ISSUE TITLE
Feature Request: systemd syntax highlighting support

### ISSUE THREAD

**Issue by DJviolin** [sublimehq/Packages#62]
It would be nice to see systemd services syntax highlighting and linting in Sublime Text:
https://atom.io/packages/language-systemd

**Comment by FichteFoll** [comment]
Just create it yourself? That doesn't look too hard to me: https://github.com/arbourd/language-systemd/blob/master/grammars/systemd%20service.cson

http://www.sublimetext.com/docs/3/syntax.html

There is no process for adding new default packages yet (most specifically for criteria, #2), so just add it to Package Control instead. (https://packagecontrol.io/docs/submitting_a_package)
