### ISSUE TITLE
[JavaScript] Backtick in regex causes highlighting issues

### ISSUE THREAD

**Issue by subhaze** [sublimehq/Packages#621]
If you pasted the code from the fetch polyfill you'll see that it breaks the scoping/coloring of the file. (it being backtick in regex used)

https://github.com/github/fetch/blob/v0.11.1/fetch.js#L12

```js
    if (/[^a-z0-9\-#$%&'*+.\^_`|~]/i.test(name)) {
      throw new TypeError('Invalid character in header field name')
    }
```

**Comment by FichteFoll** [comment]
![2016-09-19_17-51-10_sublime_text](https://cloud.githubusercontent.com/assets/931051/18638778/ad40a97a-7e91-11e6-9a74-07b6e4da4f4e.png)

**Comment by subhaze** [comment]
OK, yup closing, was an old plugin I thought I had disabled. Was re-enabled when I was trouble shooting build 3121 issues with macOS.
