### ISSUE TITLE
[PHP] Apply a scope as `entity.name.variable.php` for `MY_CONSTANT` at the `define('MY_CONSTANT', 'HELLO')` variable creation function call, for symbols navigation

### ISSUE THREAD

**Issue by evandrocoan** [sublimehq/Packages#625]
### [PHP] Apply a scope as `entity.name.variable.php` for `MY_CONSTANT` at the `define('MY_CONSTANT', 'HELLO')` variable creation function call, for symbols navigation

This is to allow locote those symbol within the PHP's `Symbol List.tmPreferences` file. This problem was originally discussed here: https://forum.sublimetext.com/t/why-use-ctags-while-there-is-the-built-in-sublime-text-symbols/22917/7

After this enhancement, the file would need look like this, containing the `entity.name.variable.php` as symbol selector:

``` json
<?xml version="1.0" encoding="UTF-8"?>
<plist version="1.0">
<dict>
    <key>name</key>
    <string>Symbols List: Indent Functions</string>
    <key>scope</key>
    <string>entity.name.function.php, support.function.magic.php, entity.name.class.php, entity.name.interface.php, entity.name.trait.php, entity.name.variable.php</string>
    <key>settings</key>
    <dict>
        <key>showInSymbolList</key>
        <integer>1</integer>
        <key>showInIndexedSymbolList</key>
        <integer>1</integer>
    </dict>
</dict>
</plist>
```

**Comment by wbond** [comment]
Should probably be `entity.name.constant`: http://www.sublimetext.com/docs/3/scope_naming.html#entity
