### ISSUE TITLE
[YAML] Numeric at tail of one-line dictionary scopes as string

### ISSUE THREAD

**Issue by djspiewak** [sublimehq/Packages#628]
Example:

```yaml
{ bar: 1 }
```

Interestingly enough, if I remove one of the spaces, it works:

```yaml
{ bar: 1}
```

**Comment by FichteFoll** [comment]
That's ... interesting.

**Comment by FichteFoll** [comment]
This is resolved by https://github.com/sublimehq/Packages/pull/629/commits/f51cb9d09ae0f6fcfe2039ff07b180ecba1ff1f0 in #629.
