### ISSUE TITLE
Sublime 3 PHP/HTML syntax highlighting

### ISSUE THREAD

**Issue by alibasheer** [sublimehq/Packages#631]
This image sums it up. Whenever I write a PHP tag "inside" a PHP tag that ends in open brackets [if, else, for, ...], the rest of the line becomes white.

http://i.stack.imgur.com/456RB.png

**Comment by keith-hall** [comment]
Which version of Sublime Text are you using? Also, please can you share the code in that image as plain text, for easy copy and pasting.

**Comment by wbond** [comment]
This probably indicates you are using an old version of Sublime Text, or an old version of the PHP package. This should have been fixed in build 3116.

**Comment by alibasheer** [comment]
Thank you!!! I updated sublime and worked out perfect :D


________________________________

**Comment by alibasheer** [comment]
Thank you!!! I updated sublime and worked out perfect :D




________________________________
