### ISSUE TITLE
[Scala] Broken highlighting when last opening-parenthesis for parameters/args on a separate line

### ISSUE THREAD

**Issue by krnhotwings** [sublimehq/Packages#633]
It seems that the latest ST3 release (build 3124) has broken some syntax coloring. If you define a def or class where the last opening-parenthesis (ie. curried function) is on a new line, syntax highlighting for the parameters will be incorrect (param name's color will be white instead of orange)

Works fine:
```scala
class Test1(a: String) {
  lazy val thing = "blah"
}

class Test2(
    a: String) {
  lazy val thing = "blah"
}

class Test3(a: String)(b: String) {
  lazy val thing = "blah"
}

class Test4(a: String)(
    b: String) {
  lazy val thing = "blah"
}
```

Breaks:
```scala
class Test1
    (a: String) {
  lazy val thing = "blah"
}

class Test2(a: String)
    (b: String) {
  lazy val thing = "blah"
}

def test
    (arg: String) = arg
```

Further, if a class' set of parameters is on a separate line and is defined with vals, various areas of the body of the class will break:

```scala
class Test(val correctColor: String)
    (val incorrectColor: String) {
  lazy val allIncorrect = """
    not yellow
  """
}
```

**Comment by djspiewak** [comment]
On it…
