### ISSUE TITLE
[LaTeX] Math environments not highlighted in `newcommand` scopes

### ISSUE THREAD

**Issue by Phidica** [sublimehq/Packages#636]
Using ST3 build 3124

Inline math environments are correctly highlighted if they appear in the braces of normal commands, but if they occur within a call to `\newcommand` or `\renewcommand` they are not

![Image showing example of incorrect highlighting](http://i.imgur.com/CksfF2z.png)

**Comment by randy3k** [comment]
It is intentional to avoid things like

```latex
\newcommand{\bg}{\begin{equation}}
\newcommand{\eg}{\end{equation}}
```

**Comment by Rhotias** [comment]
Ahh, I see. That's unfortunate, but I can understand now why it's necessary

**Comment by jrappen** [comment]
@Phidica Please close this issue if the explanation fixed your issue.
