### ISSUE TITLE
ES2015 (ES6) Syntax highlighting in template literals (i.e. instead of string concatenation)

### ISSUE THREAD

**Issue by darkred** [sublimehq/Packages#640]
Using ST3 build 3125 x64 in win10 x64.
For example (from [here](http://eslint.org/docs/rules/prefer-template))

```
var str = "Hello, " + name + "!";
var str = `Hello, ${name}!`;
```

Here is how it's highlighted in ST3: (see the `name` variable in line 2) 
![2016-09-24_182558](https://cloud.githubusercontent.com/assets/723651/18809458/704b8b60-8284-11e6-8890-7d120e3f6731.jpg)

And, for reference, here is in VSCode 1.5.3, i.e. correctly:
![2016-09-24_182809](https://cloud.githubusercontent.com/assets/723651/18809467/ad3fcf68-8284-11e6-8b1b-bb9c2a46e355.jpg)

---

And another example:

```
let arr = [], temp;
$.each(arr, (index, value) => {

    arr[index].innerHTML = '(' + temp + ') ' + arr[index].innerHTML;
    arr[index].innerHTML = `(${temp} ) ${arr[index].innerHTML}`;
});
```

In ST3: (see both `temp` and `arr[index].innerHTML` in line 5)
![2016-09-24_183030](https://cloud.githubusercontent.com/assets/723651/18809481/fde553b6-8284-11e6-8ec6-53fdafca8c2d.jpg)

and for reference, here is in VSCode:
![2016-09-24_184055](https://cloud.githubusercontent.com/assets/723651/18809535/76bdc4d4-8286-11e6-823d-1c00315c593b.jpg)

<br>
Related issue: #213

**Comment by philipbordallo** [comment]
This is more to do with your color scheme than Sublime itself.

Mine is showing as:
<img width="667" alt="screen shot 2016-09-24 at 10 15 19 am" src="https://cloud.githubusercontent.com/assets/9970403/18810000/1f92658e-8240-11e6-9998-a2f19d828787.png">

with the declarations:
```xml
<dict>
	<key>name</key>
	<string>JS Template Expression Definition</string>
	<key>scope</key>
	<string>string.template.js punctuation.definition.template-expression</string>
	<key>settings</key>
	<dict>
		<key>foreground</key>
		<string>#515151</string>
	</dict>
</dict>
<dict>
	<key>name</key>
	<string>JS Template Embedded Expression</string>
	<key>scope</key>
	<string>string.template.js source.js.embedded.expression</string>
	<key>settings</key>
	<dict>
		<key>foreground</key>
		<string>#d3d0c8</string>
	</dict>
</dict>
```

**Comment by darkred** [comment]
I'm using the Monokai scheme (=the default one) which is in its initial status (I haven't modified it at all),

**Comment by FichteFoll** [comment]
Iirc @wbond wanted to clear the string scope name (using `clear_scopes`) for embedded expressions like these.

**Comment by keith-hall** [comment]
related discussion: https://github.com/sublimehq/Packages/issues/715
