### ISSUE TITLE
Error Loading Syntax File error after updating to build 3126

### ISSUE THREAD

**Issue by mediter** [sublimehq/Packages#642]
> Error loading syntax file "Packages/Markdown Extended/Syntaxes/Markdown Extended.sublime-syntax": Apparent recursion within a with_prototype action: 25000 context sanity limit hit

**Comment by keith-hall** [comment]
looks like it is being handled at https://github.com/jonschlinkert/sublime-markdown-extended/issues/141

**Comment by wbond** [comment]
This isn't a syntax that we control, it will have to be addressed at the link @keith-hall provided.
