### ISSUE TITLE
Bad PHP syntax highlighting inside a HTML attribute's double quotes

### ISSUE THREAD

**Issue by roelvermeulen** [sublimehq/Packages#643]
When using `<?= ... ?>` and `<?php ... ?>` inside a HTML attribute's double quotes `"..."`, the syntax doesn't highlight correctly. The PHP code does get parsed however, and thus should highlight using PHP syntax, and not according to HTML syntax.

```
<?= $isImportant ? "important" : "notsoimportant" ?>
<div class="myclass <?= $isImportant ? "important" : "notsoimportant" ?>"></div>
```

In the following image, the two `<?= ... ?>` should highlight the syntax equally, as they get both parsed as PHP.

![image](https://cloud.githubusercontent.com/assets/6392884/18830908/27abc2a2-83e3-11e6-9dba-a3616adc58e9.png)

**Comment by keith-hall** [comment]
Looks like a job for `clear_scopes`. I'm guessing we would clear all scopes and then just re-add the base PHP scopes.

**Comment by neokio** [comment]
Here's a variant of the problem, though slightly more complex:
Opening and closing `"` in multiple scopes causes style highlighting to howl at the moon.

This is minutely more efficient code, but renders poorly:

![screen shot 2016-12-19 at 4 07 20 pm](https://cloud.githubusercontent.com/assets/146623/21317408/431c5894-c605-11e6-92ec-6c64719fe178.png)

This, of course, works fine:

![screen shot 2016-12-19 at 4 09 35 pm](https://cloud.githubusercontent.com/assets/146623/21317826/1300ae56-c607-11e6-91b2-d982b95187d3.png)

**Comment by FichteFoll** [comment]
I doubt this particular example will ever be highlighted correctly since you are generating the closing part of the tag within Php code. Since that could be *anything* (a variable, a string substitution, ect.) you cannot possibly lex it.

Besides it's bad style since it not as obvious as directly stating the syntactically meaningful the string fragment in HTML itself.

**Comment by wbond** [comment]
Unfortunately @keith-hall the current implementation of PHP won't allow using `clear_scopes` since `with_prototype` is used with the `HTML` syntax.
