### ISSUE TITLE
[TCL] Syntax highlighting stops working after \

### ISSUE THREAD

**Issue by joherv** [sublimehq/Packages#645]
Using build 3126 

When using \ to indicate that the row continues after the line break the syntax highlighting stops working. The funny thing though is that this only happens after a while. It typically works fine in the beginning of the TCL file but after around 1200-1500 lines (in the examples I have seen) it breaks the syntax highlighting. Also the syntax highlighting gradually disappears. Usually starts with that the first hashtag of a comment has the wrong color, then more syntax loses its color.

Working syntax highlighting:
![screen shot 2016-09-27 at 12 08 40](https://cloud.githubusercontent.com/assets/22449723/18869268/d92ab254-84ab-11e6-8d11-eeff1adbf5aa.png)

Gradually stops working (line 1439):
![screen shot 2016-09-27 at 12 09 14](https://cloud.githubusercontent.com/assets/22449723/18869219/a273e758-84ab-11e6-8805-591ce3ad3383.png)

Completely stops working:
![screen shot 2016-09-27 at 12 10 03](https://cloud.githubusercontent.com/assets/22449723/18869225/ac4fdbd8-84ab-11e6-87dc-ab2ea24b3723.png)

Maybe related to #630 #639

**Comment by wbond** [comment]
Can you paste the raw code of an example that doesn't work so that I can copy-paste for the sake of writing tests?

**Comment by joherv** [comment]
It's rather big but it seems the syntax highlighting stops work after a thousand rows or so.

[iflib.txt](https://github.com/sublimehq/Packages/files/495212/iflib.txt)

The file is called iflib.tcl, but I changed the suffix to .txt so that I could upload it to the issue.

**Comment by joherv** [comment]
Just want to point out that the syntax highlighting works fine in build 3114.

**Comment by wbond** [comment]
This is fixed by 7cd5257984231e6965cea027eec9c58e6da11177, which will be part of the next dev build
