### ISSUE TITLE
"Show Definitions" only from same language

### ISSUE THREAD

**Issue by flux627** [sublimehq/Packages#647]
When I'm writing Python code for my Django project, and I hover over a `request` object, I get tons of definitions listed from my javascript files. This isn't useful at all, and I can't imagine when it would ever be useful. I'd guess it's more often just noise for most users.

I suggest that we have a "scope_definitions_by_language" setting that is `true` by default. Thoughts?

**Comment by wbond** [comment]
This issue should be opened at https://github.com/SublimeTextIssues/Core/issues. In fact, I believe there is already an issue discussing this, so be sure to search through the list.
