### ISSUE TITLE
Setting to move inline errors to gutter

### ISSUE THREAD

**Issue by flux627** [sublimehq/Packages#648]
I'm currently a fan of the *idea* of inline errors, but not a fan of it's current *implementation*.

Problem
-
Currently, the extra space added by the inserted line puts a significant amount of extra energy needed to recognize my own code in the affected area, and forces me to re-understand what's happening in that part of the code. When debugging, this error insertion often jumps around to other places in the code, furthering my disorientation.

Also, in Python (can't speak for other languages), it currently inserts an error line in *every affected call up the stack*, so it's often not useful for quickly finding where the real error resides. If you want to clear out one of the innocent calls, then all the other errors disappear too (in another sudden, disorienting way).

Solution
-
I propose that instead of disrupting the visibility of the code by inserting a new line, instead on the offending line we either:

* Show a red dot in the gutter 
* Change the background color

Since it might be hard to figure out what color to change the background in a universally pleasant way on all color themes, the gutter option is cleaner. In addition, in non-primary offending lines (calls up the stack), we could show a hollow red circle instead.

For the message, we can simply show it either in a hover box, or in the status bar.

In addition to the `show_errors_inline` option, we could have another `inline_errors_style` which can be one of `box`, `gutter`, or `highlight`.

Thoughts?

**Comment by wbond** [comment]
This should be moved to https://github.com/SublimeTextIssues/Core/issues.
