### ISSUE TITLE
[Batch File] \ not always scoped properly when using SET

### ISSUE THREAD

**Issue by keith-hall** [sublimehq/Packages#649]
when writing a batch file to set a variable to a subfolder of another variable, for example:

```
set folder=%TEMP%\subfolder\
```

the `\` immediately after the `%` is not scoped as `variable.other.readwrite.dosbatch`. This is due to the `\b` at the beginning of the regex: https://github.com/sublimehq/Packages/blob/2157bdc412d21763eeebfaccef4090d4f1748962/Batch%20File/Batch%20File.sublime-syntax#L84

**Comment by wbond** [comment]
This was fixed (and improved upon) by 01278712b3a20dab0e360823fa355e4d07f7dd58, which will be part of the next dev build
