### ISSUE TITLE
[Rust] Incorrect highlighting of brackets in template parameters

### ISSUE THREAD

**Issue by tommit** [sublimehq/Packages#653]
I'm using Sublime Text 3, Dev Build 3125 on macOS Sierra. The first opening bracket of a template type parameter/argument is marked as an error. Here's what I'm talking about:
![st3-rust-syntax-highlighting-bracket-error](https://cloud.githubusercontent.com/assets/7393895/19022957/ce4a73ee-88eb-11e6-8ab9-a92d1eca4b82.png)

**Comment by wbond** [comment]
This has been fixed by b69477be90811ad2b248bd5e36b4774aea8ae892 and will be part of the next dev build
