### ISSUE TITLE
Regex parenthesis bug since 3126

### ISSUE THREAD

**Issue by narusFR** [sublimehq/Packages#656]
Hi,
Since 3126, it seems there's an issue with regex Scope.
Opened parenthesis equals **punctuation.definition.group.regexp** but closed parenthesis equals **meta.group.regexp** :
opened :
![image](https://cloud.githubusercontent.com/assets/20612331/19044430/8e1944fe-8994-11e6-8b78-df1397cb94b4.png)
closed :
![image](https://cloud.githubusercontent.com/assets/20612331/19044456/aa182b5c-8994-11e6-805b-c8592285151c.png)

Just to clarify, opened **and closed** parenthesis were scoped **punctuation.definition.group.regexp** in build 3114.
Could you please have a look ?

Regards !

**Comment by wbond** [comment]
Can you paste the literal code in a fenced code block here and indicate what syntax this is part of?

**Comment by narusFR** [comment]
Sure,
`match=re.search(r"(.*?)\=(.*)",line)`
I'm using Python.
