### ISSUE TITLE
CSS: unquoted font-family value 

### ISSUE THREAD

**Issue by pdknsk** [sublimehq/Packages#660]
https://www.w3.org/TR/CSS2/fonts.html#value-def-family-name

> Font family names must either be given quoted as strings, or unquoted as a sequence of one or more identifiers.

So `700` in this example shouldn't be colored separately. 

![1](https://cloud.githubusercontent.com/assets/1097609/19162094/c6010fd2-8bf6-11e6-9a4a-5336402b4164.png)

**Comment by wbond** [comment]
This should be resolved by fcdffa8cb598e17a5ad1d6579d37f25a85643ff3 and will be part of the next dev build.
