### ISSUE TITLE
[Rust] - Sublime still using .tmLanguage?

### ISSUE THREAD

**Issue by Jayflux** [sublimehq/Packages#662]
When doing some debugging, i couldn't work out why the .sublime-syntax file inside Rust was not working properly (when i pulled it out and put it into another package).

After what feels like hours on this task, it looks like sublime isn't even using the sublime-syntax file??
<img width="416" alt="screen shot 2016-10-07 at 15 36 02" src="https://cloud.githubusercontent.com/assets/936006/19193985/09b30408-8ca4-11e6-99a7-8eb37496c520.png">
The .tmLanguage file doesn't exist here:
https://github.com/sublimehq/Packages/tree/master/Rust

So i am wondering where sublime is pulling this file from
Build Dev Channel: 3125
@wbond

**Comment by wbond** [comment]
This will happen if you have https://github.com/rust-lang/sublime-rust installed as `Installed Packages/Rust.sublime-package`. That causes the default `Rust.sublime-package` to be overridden, and thus only files from https://github.com/rust-lang/sublime-rust will be visible.

**Comment by Jayflux** [comment]
@wbond but i don't have sublime-rust installed....
I removed it prior to debugging this, (also removed from the packages folder and PC)

**Comment by wbond** [comment]
Can you provide a file listing of `Packages/` and `Installed Packages/`?

**Comment by Jayflux** [comment]
```
mc-s102752:Sublime Text 3 willij87$ ls Installed\ Packages/
0_package_control_loader.sublime-package
ApacheConf.tmLanguage.sublime-package
Cucumber.sublime-package
Dockerfile Syntax Highlighting.sublime-package
EJS.sublime-package
EditorConfig.sublime-package
Extract Sublime Package.sublime-package
GitHub Flavored Markdown Preview.sublime-package
Gitignore.sublime-package
Hyperion for gettext.sublime-package
INI.sublime-package
Markdown HTML Preview.sublime-package
MarkdownEditing.sublime-package
PHP-Twig.sublime-package
Package Control.sublime-package
PackageDev.sublime-package
Pretty JSON.sublime-package
RPM Spec Syntax.sublime-package
Rust.sublime-package
SCSS.sublime-package
TOML.sublime-package
nginx.sublime-package
mc-s102752:Sublime Text 3 willij87$ ls Packages/
GoSublime	Pretty JSON	User		pyyaml		rust-test
mc-s102752:Sublime Text 3 willij87$ 
```

**Comment by wbond** [comment]
(You don't need to mention me in posts to this repo. I regularly review it when I am working.)

As I suspected, you have an `Installed Packages/Rust.sublime-package` on your machine.

**Comment by Jayflux** [comment]
I don't know where that's come from though?
Package control shows no Rust package installed, should i try deleting it?

**Comment by wbond** [comment]
Did you use Package Control to remove it, or did you simply delete it from disk?

Package Control keeps a list of installed packages in `Packages/User/Package Control.sublime-settings` and installs packages that are listed there. This allows users to sync their configuration across machines without accidentally copying packages for an incorrect OS or architecture.

If you simply deleted it from disk, Package Control will reinstall it the next time Sublime Text is started.

**Comment by Jayflux** [comment]
Ok that i think ive sorted (removed the installed package), but back to the original problem

I still don't think its using your sublime-syntax file, because when i convert the tmLanguage to a sublime-syntax file, it looks fine.
But when i swap it out for yours (https://github.com/sublimehq/Packages/blob/master/Rust/Rust.sublime-syntax), the syntax goes messed up.
http://imgur.com/a/aYxYk

Doesn't make sense

**Comment by Jayflux** [comment]
ok, I've loaded a bare Sublime Text 3 inside a VM with nothing (no PC or any plugins installed).
Its basically the default Rust.sublime-syntax file is not looking good syntax wise (see image in post above) compared to the old tmLanguage file.  
There is no bug, sublime-syntax just needs sorting out.

We may be better off just porting the old tmLanguage file as that shows better syntax highlighting

**Comment by wbond** [comment]
We have a test suite for the new syntax, and it handles many things that the tmLanguage from sublime-rust had trouble with. It also correctly assigns our standardized scope names. Most likely, however, you've hit a bug in the syntax that needs to be fixed.

We aren't going to throw out all of the improvements because of one little bug. Instead, please open a new issue and provide the Rust code that isn't being lexed properly and we can get it fixed up.
