### ISSUE TITLE
[JavaScript] syntax highlighting

### ISSUE THREAD

**Issue by caub** [sublimehq/Packages#667]
![image](https://cloud.githubusercontent.com/assets/3134574/19325899/835d3dfa-90c8-11e6-9c89-ef24ea55d0c0.png)

```js
for (let e of el.querySelectorAll('[style*="foo("]')){
}
// or
for (let e of el.querySelectorAll("[style*='foo(']")){
}
// or
for (let e of el.querySelectorAll(`[style*="foo("]`)){
}
```

Build 3126

**Comment by keith-hall** [comment]
seems fine to me on 3125...

![js highlighting for let](https://cloud.githubusercontent.com/assets/11882719/19337525/8efbaff6-911e-11e6-8ce1-e2cb6ce04b0e.png)

**Comment by caub** [comment]
Oh sorry forgot I had the babel plugin on -> https://github.com/babel/babel-sublime/issues/287
