### ISSUE TITLE
Feature request: Add additional syntax for LESS

### ISSUE THREAD

**Issue by jasjuang** [sublimehq/Packages#669]
It would be great to add an additional support for LESS syntax. LESS is a powerful css preprocessor, more info can be found here http://lesscss.org/

Currently I am opening all .less files with css syntax, which works fine for the most case but the problem is packages such as SublimeLinter-csslint is linting my .less files because it thought it is a css file and I am getting linter errors all over the place. 

The main linter used to lint less code is lesshint, and I attempted to create a SublimeLinter-contrib-lesshint package but again I ran into the problem that it couldn't recognize the .less file because sublime thinks it's a css file because the syntax is chosen as css.

Would be great if we can get a standalone syntax for LESS.

**Comment by michaelblyons** [comment]
Are you using a syntax plugin for LESS? https://packagecontrol.io/packages/LESS

**Comment by jasjuang** [comment]
oops my bad, this solves it for me
