### ISSUE TITLE
[Python] Reindent for def and class not working

### ISSUE THREAD

**Issue by deathaxe** [sublimehq/Packages#672]
Try to run _Indention: Reindent Lines_ command from command pallet for the following peace of code:

``` python
import sublime_plugin


def tabs_to_spaces(view, set_translate, only_leading):
    view.run_command('expand_tabs', {
                     'set_translete_tabs' : set_translate,
                     'only_leading' : only_leading })


def spaces_to_tabs(view, set_translate, only_leading):
    view.run_command('unexpand_tabs', {
                     'set_translete_tabs' : set_translate,
                     'only_leading' : only_leading })


class SetTabsizeCommand(sublime_plugin.TextCommand):

    def run(self, edit, tab_size = 4):
        view = self.view

        translate_tabs = view.settings().get('translate_tabs_to_spaces', False)
        if translate_tabs:
            spaces_to_tabs(view, False, True)
            view.settings().set('tab_size', tab_size)
            view.run_command('reindent')
            tabs_to_spaces(view, False, True)

        else:
            view.settings().set('tab_size', tab_size)
            tabs_to_spaces(view, False, True)
            view.run_command('reindent')
            spaces_to_tabs(view, False, True)

        # restore settings as 'expand_tabs' does not
        view.settings().set('translate_tabs_to_spaces', translate_tabs)

```

This will break indention as follows:

``` python
import sublime_plugin


def tabs_to_spaces(view, set_translate, only_leading):
    view.run_command('expand_tabs', {
                     'set_translete_tabs' : set_translate,
                     'only_leading' : only_leading })


    def spaces_to_tabs(view, set_translate, only_leading):
        view.run_command('unexpand_tabs', {
                         'set_translete_tabs' : set_translate,
                         'only_leading' : only_leading })


        class SetTabsizeCommand(sublime_plugin.TextCommand):

            def run(self, edit, tab_size = 4):
                view = self.view

                translate_tabs = view.settings().get('translate_tabs_to_spaces', False)
                if translate_tabs:
                    spaces_to_tabs(view, False, True)
                    view.settings().set('tab_size', tab_size)
                    view.run_command('reindent')
                    tabs_to_spaces(view, False, True)

                else:
                    view.settings().set('tab_size', tab_size)
                    tabs_to_spaces(view, False, True)
                    view.run_command('reindent')
                    spaces_to_tabs(view, False, True)

        # restore settings as 'expand_tabs' does not
        view.settings().set('translate_tabs_to_spaces', translate_tabs)
```

As _reindent_ seems to be a built-in function of Sublime Text I guess this is an issue caused by the Indention Rules of python.

Adding the _class_ keyword to decreaseIndentPattern made things a bit better.

``` xml
        <key>decreaseIndentPattern</key>
        <string>^\s*(class|elif|else|except|finally)\b.*:</string>
```

But I can't find a solution for _def_ which works well with comments etc. Maybe someone else has an idea?

**Comment by keith-hall** [comment]
In Python, it is possible to define classes and other functions inside a function, so having it automatically change indentation when typing `class` or `def` won't be desirable.

**Comment by deathaxe** [comment]
You are basically right, but unfortunately this means built-in _reindent_ command is most commonly useless for python language as it breaks indention due to lack of detecting embedded function or class definitions.

There is no way to tell _reindent_ to try to keep the current indention level as it always makes use of _increaseIndentPattern_ and _decreaseIndentPattern_ only?

Hmm. Seems I need an alternative strategy to fix indention after tab_size change.

I basically wanted to update a view's content, if the user clicks on Main Menu / View / Indention / Tab Width ... as changing the _tab_size_ setting only causes different issues with functions that assume this setting to match the current content such as translate_tabs_to_spaces.

**Comment by FichteFoll** [comment]
There isn't much helping re-indenting code with significant whitespace since your tool would have to be able to predict semantics. Furthermore, code has to be indented in the first place in order to work.

Chances are you'll be able to fix indentation using a regular expression replace instead.

**Comment by wbond** [comment]
Automatic indenting rules are an area that Sublime Text needs some better conventions, and possibly functionality around.

Currently we have what we inherited from TextMate, however that isn't capable of handling lots of different situations and doesn't really allow for certain indentation conventions.

**Comment by FichteFoll** [comment]
I don't think this is actually solveable for a language with significant whitespace like Python, so imo this issue should be closed.

**Comment by kyshel** [comment]
A pop dialog tip is recommend before _re-indent_   python codes, instead of a silent inproper re-indentation.
Is it worthy to sacrifice sublime-dev-code simplicity for user-friendly?
Confilcts like this choice always consume huge time on my dev-road 😳

**Comment by wbond** [comment]
If reindent doesn't work, then just Undo.

**Comment by Phoenax** [comment]
It's 2023 and I'm still having this issue, I'm guessing they still didn't find a way. It's sad, but also I don't know how easy to implement it would be (and having worked with compilers before, I'm guessing not that much, because of Hierarchy).

Anyways, if they manage to get it right, someone @ me please <3
