### ISSUE TITLE
Default/Preferences.sublime-settings lists wrong scope for spellcheck

### ISSUE THREAD

**Issue by rchl** [sublimehq/Packages#678]
"spelling_selector" preference by default includes `- meta.preprocessor.c.include` while currently syntaxes use `meta.preprocessor.include.c` and `meta.preprocessor.include.c++` so the default should be updated. Probably to just list `- meta.preprocessor.include` (not sure why c++ is not excluded currently).

**Comment by wbond** [comment]
This will be addressed in the next dev build
