### ISSUE TITLE
[SQL syntax in PHP] CREATE not highlighting unless on a new line; TRUNCATE doesn't highlight

### ISSUE THREAD

**Issue by jhaagsma** [sublimehq/Packages#681]
Hi! I stumbled across a weird bug in the sql syntax highlighting within PHP; when I put CREATE after a ", as in:

` "CREATE TABLE `version` ...
`
it doesn't highlight, whereas if I put it on a newline after the quote as in:

```
"
CREATE TABLE `version`...
```

Also, it appears TRUNCATE doesn't highlight at all. 

(sorry for the orange overlay on the image, that's a gnome-screenshot bug... lol)

![image](https://cloud.githubusercontent.com/assets/2095320/19977840/a9e05572-a1ba-11e6-937e-8c66d78acc1c.png)

**Comment by wbond** [comment]
Most likely `truncate` won’t be supported, just because it starts getting impractical to try and match every SQL keyword at the beginning of a string to enter SQL mode.

Not matching `CREATE` on a single line definitely seems like a bug.

**Comment by jhaagsma** [comment]
I would like to add that the bizarre **CREATE** behaviour above is **also** present for the **ALTER** keyword.

**Comment by wbond** [comment]
This is resolved by 77a5d112d5af05feb78f7d5c8759df9e241ce8f9 and will be part of the next dev build.

(The issue was actually with the SQL syntax not allowing CREATE, DROP or ALTER to be anywhere but at the beginning of a line.)
