### ISSUE TITLE
[C] Go to definition to enum value?

### ISSUE THREAD

**Issue by puetsua** [sublimehq/Packages#689]
```
enum {
   VALUE_1 = 0,
   VALUE_2,
   VALUE_3
}
```
It seems 'Go to definition' is not working in this case in *.c *.h files. Any help?

**Comment by wbond** [comment]
Currently enum values aren't indexed by the indexer, thus "Go to definition" doesn't work with them. This is probably a pretty reasonable addition, assuming it is a C enum and not a C++ enum class.

Are you familiar with syntax definitions for Sublime Text at all? If so, I can give you some pointers that may help in creating a PR to add this functionality.

**Comment by speeder** [comment]
I have no idea what I am doing, but I am trying to do this. Where I edit the indexer?

**Comment by hankofficer** [comment]
@wbond Thanks! However I have no idea how to add syntax definition for sublime text. ^^;
Is there anything I should look for or I should be aware of? I'd love to try it myself.

**Comment by wbond** [comment]
It going to require some learning, but here are some resources:

 - The syntax format: http://www.sublimetext.com/docs/3/syntax.html
 - How symbols are "extracted": http://docs.sublimetext.info/en/latest/reference/symbols.html
 - Scope naming guidelines: http://www.sublimetext.com/docs/3/scope_naming.html
 - Code that will be affected:
   - https://github.com/sublimehq/Packages/tree/master/C%2B%2B
   - https://github.com/sublimehq/Packages/tree/master/Objective-C
   - C++ gets all changes from C
   - Objective-C gets all changes from C
   - Objective-C++ gets all changes from C++ and Objective-C
 - For any scope name changes, be sure to add syntax tests for all four syntaxes (see the last section of the Syntax documentation)

**Comment by rwols** [comment]
There's a PR to address this here: https://github.com/sublimehq/Packages/pull/976

**Comment by LinuxDevon** [comment]
PR #976 has been open for far too long and no response from original poster. I opened a new PR #3299  to address this issue.
