### ISSUE TITLE
Javascript wrong scope name

### ISSUE THREAD

**Issue by ptcong** [sublimehq/Packages#69]
Have a problem with javascript scope,
in first line, scope of `/class="\s*"/` is *storage.type.js*
but it should be *string.regexp.js*

```js
var test = [
    // source.js storage.type.js 
    [/class="\s*"/]
    // source.js string.regexp.js 
    [
        /class="\*s"/
    ]
];
```

**Comment by aziz** [comment]
This has been fixed in the latest JavaScript.sublime-syntax file. You're probably using an old one.
