### ISSUE TITLE
[CSS] Completions broken

### ISSUE THREAD

**Issue by philipbordallo** [sublimehq/Packages#690]
CSS values completions are no longer coming up correctly. Going back through the commit history it seems like something in #483 is causing the issue.

![css](https://cloud.githubusercontent.com/assets/9970403/20297554/f17c7320-aac5-11e6-84f2-8a28ef708569.gif)

**Comment by keith-hall** [comment]
see also https://forum.sublimetext.com/t/css-autocomplete-suggests-properties-instead-of-values/24334/3

**Comment by wbond** [comment]
This is fixed by 69549082dfb4d958f61f819bd8285af1aed5ed86 and will be part of the next dev build

**Comment by FichteFoll** [comment]
https://github.com/sublimehq/Packages/commit/c6393dbd117173ebd82ef7f56986b281dfe39c86 is the actual commit where this was fixed (parent commit).
