### ISSUE TITLE
[comment.py] Toggle Comment line bug

### ISSUE THREAD

**Issue by TheClams** [sublimehq/Packages#691]
The toggle comment can sometime behave strangely if there is block comment embedded:
For example, let's take the following code in C (happens with any language with both line and block comment):
```C
i = 0 /* 0 */;
j = 1 /* 1 */;
k = 2 /* 2 */;
```

If the three lines are selected and the command toggle line comment is called (ctrl+/ by default) then the block comment around 1 is removed. If only two lines are selected then the two line are correctly commented with a // at the beginning of the line.

Looking at the code in comment.py this seems to comes from the way the remove block_block_comment works: it try to extract the scope from the middle of the selection and if the middle is a block comment then it gets toggled ...

I am not sure exactly how to fix this issue properly (apparently it was done this way instead of looking directly at start and beginning of the region to avoid some issue with HTML comment ...), but at least when the toggle comment is called with block to false it should never affect the block comment, so a beginning of a fix is provided here:
```diff
@@ -203,7 +203,7 @@
                 # region spans languages, nothing we can do
                 continue
 
-            if self.remove_block_comment(self.view, edit, comment_data, region):
+            if block and self.remove_block_comment(self.view, edit, comment_data, region):
                 continue
 
             if self.is_entirely_line_commented(self.view, comment_data, region):
```
The problem still appears when toggle comment is called with block true, but since block comment cannot be embedded one in another, this is less of a concern.

**Comment by MattDMo** [comment]
This issue is not relevant to this repo. As [stated in the README](https://github.com/sublimehq/Packages#missing-packages):
> **Missing Packages**
> This repository only contains syntax-definition-focused packages. Notably, packages such as *Default* and *Theme - Default* are not included.

I would suggest reposting this in [SublimeTextIssues/Core](https://github.com/SublimeTextIssues/Core), which deals with general bug reports. Make sure to search first to see if it has already been reported.

**Comment by wbond** [comment]
This appears to not really be a syntax issue, but rather a command issue that is part of the C++ codebase or the Default packages (which is not open source here). A report at https://github.com/SublimeTextIssues/Core would be appropriate, although there may already be one there.
