### ISSUE TITLE
[Python] Python 3.6 hits 2016-12-16 (with new syntax)

### ISSUE THREAD

**Issue by FichteFoll** [sublimehq/Packages#694]
According to [PEP 494](https://www.python.org/dev/peps/pep-0494/), Python 3.6 will hit in one month with a couple new syntax features to sport. Nothing breaking, however. The list of changes is available here: https://docs.python.org/3.6/whatsnew/3.6.html.

Syntax changes:

- [x] https://www.python.org/dev/peps/pep-0498 (https://github.com/sublimehq/Packages/issues/726)
- [x] https://www.python.org/dev/peps/pep-0515 (#728)
- [x] https://www.python.org/dev/peps/pep-0526 (#730)
- [x] https://www.python.org/dev/peps/pep-0530 (#729)

The remaining changes would include adding a couple identifiers to special highlighting, which is trivial.

I am volunteering to work on this as soon as either my other PRs are merged or I start using 3.6 (which will most likely happen on the release day). Or in case you intend to plan a new dev release soon.

**Comment by wbond** [comment]
This appears to be done. Thanks @FichteFoll!
