### ISSUE TITLE
[D] Regex string breaks coloration

### ISSUE THREAD

**Issue by CromFr** [sublimehq/Packages#695]
```d
string sA = r"$";
// or
string sB = r"asdf";
```
breaks the coloration for the rest of the file

Note: a whitespace just before the ending `"` restores the coloration

**Comment by keith-hall** [comment]
this was fixed by https://github.com/sublimehq/Packages/commit/a768ce40cfbaf1e92a51f0f9034d3bd7ce60e89f

**Comment by CromFr** [comment]
Awesome ! thanks :)
