### ISSUE TITLE
python: standalone print colored function-like

### ISSUE THREAD

**Issue by pdknsk** [sublimehq/Packages#699]
Changed somewhat recently I think. I guess there is no universal solution for both `2` and `3`.

![1](https://cloud.githubusercontent.com/assets/1097609/20533891/7fce7c62-b0df-11e6-9a92-e6ffb0815a38.png)

**Comment by FichteFoll** [comment]
I didn't know a bare `python` statement was valid. I suppose that is more common than using `print` as a function in a bare line, like this:

```py
functools.partial(
    print,
    print
)
```

**Comment by pdknsk** [comment]
There's still a mini-bug here in that the following print is also colored function-like, which can probably not be helped.

```Python
print (a or b) and c
```

**Comment by FichteFoll** [comment]
Indeed, that will always be highlighted as a function. Not to mention that this is actually ambiguous and can be both.
