### ISSUE TITLE
Add support for vagrant syntax offically

### ISSUE THREAD

**Issue by shivapoudel** [sublimehq/Packages#70]
Vagrant ship the filename `Vagrantfile` which has `ruby` syntax. But while opening in sublime no synatx is set. Please have it offically set.

**Comment by vmrob** [comment]
I'm fairly certain that the Vagrantfile is actually a Ruby script.

**Comment by shivapoudel** [comment]
@vmrob Yeh, its ruby script. I have updated the syntax is the above comment of mine :P

**Comment by FichteFoll** [comment]
It's already there: 1700a087822a8655c4c04683d1754793b25f3e56 (https://github.com/sublimehq)/Packages/pull/64

**Comment by shivapoudel** [comment]
Closed in favour of #64
