### ISSUE TITLE
[Matlab]Fix the block comment scope for the Matlab

### ISSUE THREAD

**Issue by evandrocoan** [sublimehq/Packages#700]
Originally started on the pull request: https://github.com/sublimehq/Packages/pull/650

Here:
```
<string>%{\n</string>
...
<string>%}\n</string>
```
It is obligatory a new line to be inserted, otherwise the the block comment does not work. How could a new line to be inserted?

There is also a missing new line on the opening and the closing does also need new lines:
```
<string>\n%{\n</string>
...
<string>\n%{\n</string>
```

I am gonna try:
```
<string>
%{
</string>
...
<string>
%}
</string>
```
Take care also when inserting the new lines for `\n%{\n`, to keep `%{` correctly indented.

____
## The  Syntax

The syntax also need to be fixed to not allow anything than spaces/tabs, before and after the symbols `%{` and `%}`.

**Comment by FichteFoll** [comment]
The latter may work, although I never tried. The former two won't because property lists don't have any string escape sequences besides the usual XML stuff, afaik.

**Comment by evandrocoan** [comment]
Fixed with: 

1. https://github.com/sublimehq/Packages/pull/718
