### ISSUE TITLE
Isn't that a great idea to assign a scope named "entity.name.function..." addtionally to a element with "meta.function-call...."?

### ISSUE THREAD

**Issue by sandogeek** [sublimehq/Packages#705]
![image](https://cloud.githubusercontent.com/assets/16507453/20633665/186322f6-b384-11e6-9273-1455a687deea.png)
so that the abc in line 4 can be colored rightly.
more discusion on [https://forum.sublimetext.com/t/hightlight-functions-name/24600/4](https://forum.sublimetext.com/t/hightlight-functions-name/24600/4)

**Comment by FichteFoll** [comment]
No.


`entity` scopes are for *definitions*. Usages are within `variable`, as emphasized by `variable.function`. `meta.function-call` is just something the entire function call gets (including arguments) for more fine-grained control. Plugins (or ven color schemes) could use that, if they wish.

**Comment by wbond** [comment]
@FichteFoll is correct here. Also, see http://www.sublimetext.com/docs/3/scope_naming.html for more discussion of the current standards for scope naming.
