### ISSUE TITLE
[javascript] Syntax highlight issue

### ISSUE THREAD

**Issue by caub** [sublimehq/Packages#706]
```js
Object.assign(o, {['iii'+(true==false?'italic':'')]:3})

```
![image](https://cloud.githubusercontent.com/assets/3134574/20635146/5a05d710-b359-11e6-9164-6ee8a6cf1b75.png)

**Comment by wbond** [comment]
Confirmed that this occurs with build 3126

**Comment by wbond** [comment]
This is fixed by 8e5cad7f7e3ee02f898ddb506d3c9034bef3a8dd and will be part of the next dev build
