### ISSUE TITLE
[Sublime Text Key Map] Breaking for regex expression

### ISSUE THREAD

**Issue by evandrocoan** [sublimehq/Packages#711]
### [Sublime Text Key Map] Breaking for regex expression

Create the file `Default.sublime-keymap` using this contents and open it with Sublime Text:
```javascript
[
  // extend a docblock by adding an asterisk at the start
  { "keys": ["enter"], "command": "insert_snippet", "args": {"contents": "\n${TM_CURRENT_LINE/^\\s*(\\*\\s*).*$/$1/}"},
    "context": [
      { "key": "setting.auto_indent",   "operator": "equal",          "operand": true,              "match_all": true },
      { "key": "selector",              "operator": "equal",          "operand": "comment.block",   "match_all": true },
      { "key": "auto_complete_visible", "operator": "equal",          "operand": false,             "match_all": true },
      { "key": "preceding_text",        "operator": "regex_contains", "operand": "^\\s*\\*\\s*\\S", "match_all": true }
    ]
  },
  // extend a docblock by adding an asterisk at the start
]
```

### Current Behavior:

The file is correctly parsed by Sublime Text and the `Key Map` is working properly, however the syntax highlighting on the Sublime Text editor is broken for all the remaining file contents after the specified block on the image below.

![image](https://cloud.githubusercontent.com/assets/5332158/20674227/3ff3d044-b56f-11e6-8aa1-7850b02f7841.png)

**Comment by wbond** [comment]
It appears you may have a custom syntax you are using for `.sublime-keymap`? Sublime Text ships with JSON as the syntax used for `.sublime-keymap`, and it does not highlight any of the elements differently than basic JSON. It is also possible you are using a custom JSON syntax.

**Comment by evandrocoan** [comment]
Yes, I just noticed, the package PackageDev has several syntaxes and this is one of them.
