### ISSUE TITLE
[PHP] Closing tag does not act as semicolon

### ISSUE THREAD

**Issue by jfi** [sublimehq/Packages#719]
According to the [PHP manual](http://www.php.net/manual/en/language.basic-syntax.instruction-separation.php):

> The closing tag of a block of PHP code automatically implies a semicolon; you do not need to have a semicolon terminating the last line of a PHP block.

I'm seeing an issue with Syntax Highlighting in build 3126 (may have been in previous builds?) whereby if you have code similar to the following the syntax highlighting is broken:

    <th><?= $record->id ?></th>

This is only rectified if you use a semicolon:

    <th><?= $record->id; ?></th>

**Comment by jfi** [comment]
According to the [docs][http://www.php.net/manual/en/language.basic-syntax.instruction-separation.php]:

_The closing tag of a block of PHP code automatically implies a semicolon; you do not need to have a semicolon terminating the last line of a PHP block._

I'm seeing an issue with Syntax Highlighting in build 3126 (may have been in previous builds?) whereby if you have code similar to the following the syntax highlighting is broken:

                            <th><?= $record->id ?></th>

This is only rectified if you use a semicolon:

                            <th><?= $record->id; ?></th>

**Comment by wbond** [comment]
What build of Sublime Text are you using? Are you sure you are using the default PHP syntax?

I can not reproduce any differences in highlighting between the two code snippets you provided while running build 3126.

**Comment by wbond** [comment]
Feel free to re-open with more info if you believe this is happening with the default PHP syntax in 3126.

**Comment by FichteFoll** [comment]
(Iirc you can't re-open issues that were closed by a collaborator, but commenting will suffice.)
