### ISSUE TITLE
[Java] Correctly scope fully-qualified identifiers

### ISSUE THREAD

**Issue by djspiewak** [sublimehq/Packages#736]
The Java mode currently uses a `qualified_id` regex to scope identifiers.  This has two problems.  First, it doesn't allow fully-qualified identifiers to split across lines (which is valid in Java).  Second, it incorrectly manages both the meta scopes and the punctuation scopes (since the `.` will be scoped as part of the identifier).

This is non-trivial to correct, due to the stateful contexts which use `qualified_id`, but still worth doing.

**Comment by ismell** [comment]
How do we see this working?

foo.bar.MyClass.SubClass

what scopes should be applied to `foo`, `bar`, `MyClass` and `SubClass? Is there a meta scope wrapping the entire thing?

Do we have a scope for foo.bar that denotes it as a class path?

**Comment by djspiewak** [comment]
> what scopes should be applied to foo, bar, MyClass and `SubClass?

I would have to look up exactly what is correct here, but off the top of my head:

```java
   foo.bar.MyClass.SubClass
// ^^^ variable.package.java
//    ^ punctuation.accessor.java
//     ^^^ variable.package.java
//        ^ punctuation.accessor.java
//         ^^^^^^^ support.class.java
//                ^ punctuation.accessor.java
//                 ^^^^^^^^ support.class.java
// ^^^^^^^^^^^^^^^^^^^^^^^^ meta.identifier.java
```

Something to that effect, anyway.

**Comment by ismell** [comment]
if we had foo.bar.MyClass.SubClass.myStaticMethod(). I would assume myStaticMethod would not be inside the meta.identifier.

This gets interesting when referencing variables:

    class Node {
        Parent parent;
    }

    Node node = ...;

    node.parent.parent = new Node();
    
    node.parent // <- Can't tell here if this is a meta.identifier, or just a variable with an accessor
        .parent = new Node();

**Comment by rwols** [comment]
Might want to look at how Python handles qualified paths.

**Comment by FichteFoll** [comment]
Python handles them well in general, but the scope names are quite unconventional since I just needed *something* to test against. They will likely change in the future to something suggested here or similarly.

**Comment by lastsecondsave** [comment]
Is anyone here working on it right now? I'm experimenting with scoping packages in Java (I want all dots be the same color), maybe publish it in a week or two. Don't want to clash with someone's work.

**Comment by ismell** [comment]
Not working on it. Let me know how it goes!
