### ISSUE TITLE
JavaScript - Division formatted like a regex

### ISSUE THREAD

**Issue by WsDwA1022** [sublimehq/Packages#742]
In the lates version of Sublime Text 3 (built 3126) when division character `/` is placed after `undefined` or literal string, the rest of the code is formatted like a regex. You can see here how it looks:

![1][1]

You may ask "Who would ever divide a string or undefined with something?" Well, the first reason is why not to make text editor cover all cases, not only the ones people usually uses. Second reason: in some very rare cases, dividing undefined and string can actually make sense. For example, we can name a variable `undefined` and actual `undefined` value bacomes shadowed. Dividing string could make sense if we override `String.prototype.valueOf` function, but is very rare case.

More about this bug and how I've found it you can find here: [https://forum.sublimetext.com/t/javascript-division-again-formatted-like-a-regex/25039](https://forum.sublimetext.com/t/javascript-division-again-formatted-like-a-regex/25039)

# Edit

There are a few scripts which have absolutelly correct ES7 syntax, but highlighted wrong. See [here](https://github.com/WsDwA1022/wsdwa1022.github.io/blob/master/1.zip?raw=true).

[1]: http://i.imgur.com/PU0uisZ.png

**Comment by wbond** [comment]
Please post code snippets here of any incorrectly highlighted JS. That way I don't have to go hunting or re-type them.

**Comment by wbond** [comment]
Fixed by 632046cf8483530ae6186f45f9614e04c1c9100a and a59983b2c22ec7fbad1293bc9ac90da9d2a22836. These will be part of the next dev build.

**Comment by WsDwA1022** [comment]
@wbond My code was too large, that is why I didn't post as snippet, but instead I've added a link to forum where you can find snippet.

Also, did you noticed that I've attached link to `rar` file of five very large JS files which are not highlighted at all (some lines are totally black)? I am pretty sure these bugs are different from this one. You can download it and check every, in all files at least one line is black.

**Comment by wbond** [comment]
Yes, once I got to a computer I downloaded the zip and all of the bugs are fixed by those two commits.
