### ISSUE TITLE
HTML-ASP.sublime-syntax - error loading syntax file

### ISSUE THREAD

**Issue by Silly-V** [sublimehq/Packages#745]
Just got this error today - all html/asp files have no highlighting now.

Error loading syntax file "Packages/ASP/HTML-ASP.sublime-syntax": Apparent recursion within a with_prototype action: 25000 context sanity limit hit

**Comment by wbond** [comment]
Most likely you have a custom HTML or ASP syntax file that is causing recursion. Look in `Packages/` for files named:

 - `Packages/HTML/HTML.sublime-syntax`
 - `Packages/HTML/HTML.tmLanguage`
 - `Packages/ASP/ASP.sublime-syntax`
 - `Packages/ASP/ASP.tmLanguage`

If you find any, try moving them out of the Packages folder. That should help.

Alternatively you can try using the Sublime Text Console to run the following Python code, which can detect files places in other folders:

```python
sublime.find_resources('HTML.sublime-syntax')
sublime.find_resources('HTML.tmLanguage')
sublime.find_resources('ASP.sublime-syntax')
sublime.find_resources('ASP.tmLanguage')
```

If you continue to have trouble, I recommend posting on the forum.

**Comment by Silly-V** [comment]
The files inside the Packages folder are with a 'sublime-package' extension. I can look inside by unarchiving with 7-Zip, and then I am able to see one file which you mention: "ASP.sublime-syntax"
But how do I delete this file and turn the folder of files back into a "sublime-package" file to put back into the Packages folder?

**Comment by wbond** [comment]
Since this isn't about the development of the default packages or bugs in them, let's move this to the forum. That way more eyes are on it and other users who have run into the same problem as you can help.

**Comment by Silly-V** [comment]
This is my first time, where is this forum you speak of, please?

**Comment by wbond** [comment]
https://forum.sublimetext.com/
