### ISSUE TITLE
[C#] `let` and `orderby` Linq Query Syntax keywords missing

### ISSUE THREAD

**Issue by keith-hall** [sublimehq/Packages#746]
class Test {
        void Main() {
            List<Book> books = new List<Book>() {
              new Book { Title = "LINQ in Action" },
              new Book { Title = "LINQ for Fun" },
              new Book { Title = "Extreme LINQ" } };

            var titles =
              books
                .Where(book => book.Title.Contains("Action"))
                .Select(book => book.Title);

            titles.Dump();

            var results = from book in books
                     let titlelen = book.Title.Length // <-- `let` should be support.function.sql.cs
                     select new { book.Title, titlelen }.Dump();
            results.Dump();

            results = (from book in books
                       let title = book.Title
                       orderby title.Length descending // <-- `orderby` should be support.function.sql.cs
                       select new { title, title.Length }).Dump();
        }
    }

Also it seems a bit odd that the `{` after `new List<Book>()` is `punctuation.section.block.begin.cs` instead of `punctuation.section.braces.begin.cs` as it is without the optional `()`.

**Comment by wbond** [comment]
This is fixed by f8ddc914a7eb48f02b87d6305061b62296bf9676 and 31cd956d4bb35ad995a9ebd76bc91a51808528e4
