### ISSUE TITLE
[C#] Generic scoping inconsistency and breakage on delegates

### ISSUE THREAD

**Issue by keith-hall** [sublimehq/Packages#747]
public interface ISessionChannel<TSession>
    {
        TSession Session { get; }
    }

    public class Test
    {
        static void Swap<T>(ref T lhs, ref T rhs)
        {
            T temp;
            temp = lhs;
            lhs = rhs;
            rhs = temp;
        }
        
        static KeyValuePair<TKey, TValue> Pair<TKey, TValue>(TKey key, TValue value) where TKey : string
        {
            return new KeyValuePair<TKey, TValue>(key, value);
        }
        
        public delegate TOutput Converter<TInput, TOutput>(TInput from);
        
    }

I would expect all generics to get scope `support.type` but currently, the ones that come after the method name are `variable.other.generic.cs`.

i.e. `TSession` should be `support.type` as should `TKey, TValue` after `Pair` and `T` after `void Swap`. They are all types/type placeholders after all.

also delegates with generic parameters break the highlighting - the closing `}` of the class is not scoped and `Converter` doesn't get scope `variable.other.member.delegate.cs` EDIT: the scope for delegates should probably be `entity.name.delegate`, just like enums get `entity.name.enum`

Also, I'm not sure why `value` is a `variable.language`?

**Comment by wbond** [comment]
This was pulled in from work by gwenzek. Originally they were scoped at `variable.parameter`. I suppose most people won't want partial distinction since we can only sometimes tell if a type name is from the generic, or if it is stand-alone.

**Comment by wbond** [comment]
The scope names are fixed by 6e1a6df

**Comment by wbond** [comment]
Support for generic delegates was added in 35e5c15

**Comment by wbond** [comment]
I chose not to scope delegates as `entity.name` since it is just a member of the class that accepts a method instead of a value. Hence the scope `variable.other.member.delegate`, which shares the first three labels with other members.
