### ISSUE TITLE
[C/C++] #include syntax highlighting

### ISSUE THREAD

**Issue by artifactz** [sublimehq/Packages#748]
`#include<iostream>` is valid C/C++ syntax, but is not considered valid by syntax highlighting. Only includes with separating whitespace are accepted (`#include <iostream>`).

The error is probably located here: https://github.com/sublimehq/Packages/blob/master/C%2B%2B/C.sublime-syntax#L1116

**Comment by wbond** [comment]
This should be resolved by 1a0211f5b5b02540104354874d667589e0d55769
