### ISSUE TITLE
[C#] `nameof` scoped as variable.function but it is built in to the language

### ISSUE THREAD

**Issue by keith-hall** [sublimehq/Packages#750]
https://msdn.microsoft.com/en-us/library/dn986596.aspx

    public class Test {
        void TestMethod(int argument) {
            if (argument <= 0)
                throw new ArgumentException("Value must be positive", nameof(argument));
        }
    }

**Comment by wbond** [comment]
This is fixed by 4f8374ac7af3cf8c8e4333db30aa6c0dd3d523b5 and dc30a3c84d50c5fb9d77cf99e50e10332c520d91
