### ISSUE TITLE
[C#] lambdas scope the `)` wrongly

### ISSUE THREAD

**Issue by keith-hall** [sublimehq/Packages#752]
class Test {
        void Main () {
            var items1 = new[] { 1, 2, 3};
            var items2 = new[] { "a", "b", "c"};
            foreach (var row in items1.Zip(items2, (item1, item2) => Tuple.Create(item1, item2)))
                Console.WriteLine(row.Item2 + row.Item1.ToString());
        }
    }

the scope of the `)` after `item2` (before `=>`) is `meta.group.cspunctuation.section.group.end.cs` with no space between the two scopes.

**Comment by wbond** [comment]
This is fixed by 29e1264
