### ISSUE TITLE
JavaScript - Object formatted like a regex

### ISSUE THREAD

**Issue by WsDwA1022** [sublimehq/Packages#764]
Latest dev build JavaScript syntax sublime package produces wrong highlighted expressions. For example, if we divide newly created object property with undefined, the rest of the code is formatted like a regex. This is the minimal code which reproduces the bug:

    +{
      '': +{} / undefined
    };

One weird thing here: all JavaScript highlighters I currently use format this piece of code wrong. However, this is absolutelly correct ES7 syntax.

Sublime
![1][1]

JSFiddle
![2][2]

JSBeautifier
![3][3]

CodePen
![4][4]

Oh! Even Chrome
![5][5]

[1]: http://i.imgur.com/jz6rA5M.png
[2]: http://i.imgur.com/BJIA6VE.png
[3]: http://i.imgur.com/0g1NMj1.png
[4]: http://i.imgur.com/dnq79Ae.png
[5]: http://i.imgur.com/LgJv1SU.png

**Comment by wbond** [comment]
This is fixed by 26b7b4da1b0b4e4683a9100d8c756df09f666e0f
