### ISSUE TITLE
JavaScript - Regex formatted like a comment

### ISSUE THREAD

**Issue by WsDwA1022** [sublimehq/Packages#769]
One regex flag is missing from "JavaScript.sublime-syntax" regex notation. For example, the following code

    /\//u + 0;

is formatted like a comment. In ES7 possible regex flags are "g" for global, "m" for multi line, "i" for case insensitive, "y" for sticky match and "u" for unicode. However, in "JavaScript.sublime-syntax" at line 519 it says:

    regexp-complete:
      - match: '/(?=(?:[^/\\\[]|\\.|\[([^\]\\]|\\.)+\])+/(?![/*])[gimy]*(?!\s*[a-zA-Z0-9_$]))'
        scope: punctuation.definition.string.begin.js
        push: regexp

I think changing `[gimy]` to `[gimyu]` should solve the problem.

**Comment by wbond** [comment]
This was fixed by 26b7b4da1b0b4e4683a9100d8c756df09f666e0f, and I added the flag you identified in d01082b4063708ea1ac9fa5b76b4eb65eae17914
