### ISSUE TITLE
[XML] Question: does ST support highlightPairs in tmPreferences?

### ISSUE THREAD

**Issue by keith-hall** [sublimehq/Packages#772]
I notice that the [XML tmPreferences file contains `highlightPairs`](https://github.com/sublimehq/Packages/blob/c55cf5662bb00020acdd5af32cf774d0217ec940/XML/Miscellaneous.tmPreferences#L35-L57), but in my experience they don't seem to do anything in ST.

If ST doesn't support `highlightPairs`, should we remove this part of the file to avoid confusion? It seems like ST instead just respects the configuration options `match_brackets`, `match_brackets_square`, `match_brackets_braces` and `match_brackets_angle`, such that matching the double quotes (`"`) isn't possible without a Python plugin anyway.

**Comment by wbond** [comment]
Just for the record, I see no reference to `highlightPairs` in the Sublime Text 3 codebase.
