### ISSUE TITLE
[Python] * and ** in method definitions are unscoped

### ISSUE THREAD

**Issue by keith-hall** [sublimehq/Packages#773]
https://docs.python.org/dev/tutorial/controlflow.html#keyword-arguments

    def example(test, *args, **kwargs): # <- scope my asterisks please!
        print(test)
        print(*args)
        print(list(range(*args)))
        print(*kwargs)
        blah = { 'def': 2, 'testing123': 'TEST' }
        combined = { **kwargs, **blah }
        print(combined)
    example('hello world', 3, 6, testing123='test', abc=1)

**Comment by FichteFoll** [comment]
I fixed this already in a local branch, but didn't submit it yet because it kind of depends on https://github.com/sublimehq/Packages/pull/743 and also runs into the same ST bug iirc. I could submit it, but decided to wait on that being merged instead.
