### ISSUE TITLE
[Java] jsp syntax highlighting issue

### ISSUE THREAD

**Issue by fmwight482** [sublimehq/Packages#775]
I believe I have found a couple of issues with syntax highlighting for jsp files, apparently caused by nested tags, comments, and brackets. Attached is a copy of the syntax_test_jsp test file with a couple new lines demonstrating the issue. This file was converted from .jsp to .txt in order to upload it, and should be changed back for testing. I am using Sublime Text 3 Build 3126.

[syntax_test_jsp.txt](https://github.com/sublimehq/Packages/files/702034/syntax_test_jsp.txt)

A brief rundown:
- Line 10 is a comment and is properly highlighted as such.
- Line 28 is also a comment and should be highlighted the same as line 10. 
- Line 30 is highlighted correctly except for the closing scriptlet tag at the end, which should not be interpreted as part of the comment and should instead close the scriptlet. Because it is not interpreted properly, everything from line 31 down is highlighted incorrectly.

This demo file is highlighted correctly in Notepad++ if an example is needed.

**Comment by keith-hall** [comment]
This issue has been resolved by https://github.com/sublimehq/Packages/commit/ef069a64b4cdb088832a4b6628c164add444ff99 and can be closed.
