### ISSUE TITLE
[Go] Syntax Highlighting Bug When Printing Shorthand Assignment in String

### ISSUE THREAD

**Issue by seantcanavan** [sublimehq/Packages#776]
Try the below text in sublime to verify:

	fmt.Println("case message := <- obj.channel")

It breaks the syntax going forward as soon as the ":=" is typed in the string.

This is on build 3126

**Comment by keith-hall** [comment]
I guess the fix for this would be to change the `.*` on this line: https://github.com/sublimehq/Packages/blob/debc983da97b1870dc418249a26e591e57b151ff/Go/Go.sublime-syntax#L282 to `\s*`

**Comment by wbond** [comment]
Should be fixed be d694a0b1ac222c3de998ede23c380898b165136b
