### ISSUE TITLE
Syntax highlight issue in ternaries (JavaScript)

### ISSUE THREAD

**Issue by caub** [sublimehq/Packages#778]
Using JavaScript syntax, special values like primitives, null, true, ... are not highlighted  below:

```js
var query = {
	type: type==undefined ? null : {$in: type.split(',')}
};
```
![image](https://cloud.githubusercontent.com/assets/3134574/21965861/9138b40a-db68-11e6-8ca4-ed866d72b278.png)

**Comment by keith-hall** [comment]
please can you mention the language in your issue somewhere, i.e. in this case, JavaScript. Makes it easier to find stuff when searching :)
