### ISSUE TITLE
Syntax hightlight issue with object shorthands (JavaScript)

### ISSUE THREAD

**Issue by caub** [sublimehq/Packages#780]
the field is highlighted (in green in the image below) is a comment follows, for no specific reason
```js
var pop = 1;
var o = {
	pop // ok
}
```
![image](https://cloud.githubusercontent.com/assets/3134574/21996915/c61d5954-dc2c-11e6-9460-d71d026e9a41.png)

**Comment by keith-hall** [comment]
If you write it all on one line, it gets it right:

    var a = "foo", 
        b = 42, 
        c = {};

    // Shorthand property names (ES2015)
    var o = { a, b, c };

    // In other words,
    console.log((o.a === { a }.a)); // true

same with no comments on multiple lines:

    var o = {
        a,
        b,
        c
    }

but as soon as you add a comment to an item without a comma after it, the identifier before the comment gets scoped as `entity.name.function.js`:

    var o = {
        a,
        b, // variable.other.readwrite.js
        c // entity.name.function
    }

**Comment by caub** [comment]
So it's not a 'bug'? I'm still surprised that something after `//` would be interpreted as function name, it's clearly a comment, line return or not, and trailing comma or not

**Comment by kleinfreund** [comment]
> So it's not a 'bug'?

I don’t think that was what they meant. It seems that the merely explored on *when* the bug happens in more detail.
