### ISSUE TITLE
[All - tmPreferences] RFC: wrap regular expressions in CDATA?

### ISSUE THREAD

**Issue by keith-hall** [sublimehq/Packages#785]
Hi,

I've recently been working on a syntax definition for Plist files, so that scope selectors and regular expressions will be highlighted, making it much easier to work with indentation rules etc. (I'm hoping it would be gratefully received in the PackageDev package, if not here, on this repo.)

However, some `.tmPreferences` contain regular expressions with lookbehinds (for example), but the `<` is escaped for XML to `&lt;`, so it appears as an invalid regex. Rather than try to build the syntax definition to work with character escapes, I thought perhaps we could change the `tmPreferences` files in this repo to wrap the expressions in XML `<![CDATA[`...`]]>` segments where appropriate instead, to avoid the need to escape these characters. I'm happy to make the changes myself and submit a PR, but I wanted to check what people think about it, first.

![regex highlighting in tmpreferences](https://cloud.githubusercontent.com/assets/11882719/22142752/2091241c-df00-11e6-8457-45c4d59ee6d2.png)

I've tested and can confirm that ST correctly parses all CDATA segments inside Plist files, as does the Python `plistlib` module, so making these changes shouldn't adversely affect anything. Arguably, even without the syntax highlighting I am working on, the regexs would be easier to read without the XML character/entity escapes.

If people are not opposed to this idea, how much do you think we should wrap in CDATA segments? Should we wrap all indent patterns, for consistency? or only those that use the XML entities? or not just indent patterns, but everything with XML entities like `shellVariables`, `symbolTransformation`s and `scope` selectors? (I'm also working on scoping/highlighting symbol transformations / regex replacements, so the answer I am hoping for would be either "wrap everything" or "wrap everything that currently contains an XML entity [that would affect the highlighting] [and we'll try to wrap things in future when we introduce something that would otherwise need escaping]" 😉 )
Wrapping everything may simplify "Find in Files" searches, where one wants to find every location where a particular token is used, and not have to remember to search the escaped XML version of the token too. :)

Thanks in advance for your feedback! :)

**Comment by keith-hall** [comment]
To be concrete, what I'm proposing is that this: https://github.com/sublimehq/Packages/blob/458e0764063a885cf8f7c2da3b41ac3d81fdfa57/Ruby/Miscellaneous.tmPreferences#L13-L46

would become:

    <string><![CDATA[(?x)^
        (\s*
            (
                module|class|def
                |unless|if|else|elsif
                |case|when
                |begin|rescue|ensure
                |for|while|until
                |
                (?=.*? \b(do|begin|case|if|unless)\b )
                # the look-ahead above is to quickly discard non-candidates
                (
                    "(\\.|[^\\"])*+"      # eat a double quoted string
                    | '(\\.|[^\\'])*+'    # eat a single quoted string
                    | [^#"']              # eat all but comments and strings
                )*
                (
                    \s   (do|begin|case)
                    | [-+=&|*/~%^<>~](?<!\$.) \s*+ (if|unless)
                )
            )\b
            (?! [^;]*+ ; .*? \bend\b )
            |
            (
                "(\\.|[^\\"])*+"          # eat a double quoted string
                | '(\\.|[^\\'])*+'        # eat a single quoted string
                | [^#"']                  # eat all but comments and strings
            )*
            (
                \{ (?!  [^}]*+ \} )
                | \[ (?! [^\]]*+ \] )
            )
        ).*$
    ]]></string>

```diff
--- before.tmPreferences

+++ after.tmPreferences

@@ -1,4 +1,4 @@

-<string>(?x)^
+<string><![CDATA[(?x)^
 (\s*
 (
 module|class|def
@@ -49,7 +49,7 @@

 \s
 (do|begin|case)
 |
-[-+=&amp;|*/~%^&lt;&gt;~](?&lt;!\$.)
+[-+=&|*/~%^<>~](?<!\$.)
 \s*+
 (if|unless)
 )
@@ -101,4 +101,4 @@

 )
 )
 ).*$
-</string>
+]]></string>
```

**Comment by deathaxe** [comment]
As it is common practice to wrap all <content> elements of sublime-snippet files into CDATA I find it consistent to do so with all _string values_ in plists, too, which contain at least regex patterns. It improves readability and avoids mixed up encodings of different "languages".

I am wondering if replacing &amp; in scope selectors by CDATA wrapping brings along noticable advantages for readability. IMHO it would at least make logically accociated scopes look better and being equal to their JSON representation in *.sublime-completions files.

Now - without CDATA:
```xml
<key>scope</key>
<string>source.s840d_gcode &amp; (meta.definition.variable | meta.redefinition)</string>
```

Then - with CDATA:
```xml
<key>scope</key>
<string><![CDATA[source.s840d_gcode & (meta.definition.variable | meta.redefinition)]]></string>
```

JSON:
```js
{"scope":"source.s840d_gcode & (meta.definition.variable | meta.redefinition)", ...
```

**Comment by keith-hall** [comment]
Agreed completely - consistency makes sense for copy/paste and comparison reasons - it's just a shame that CDATA isn't supported in the `sublime-snippet` `<scope>`.
