### ISSUE TITLE
[JavaScript] Control word following construction without parentheses or semicolon is not highlighted

### ISSUE THREAD

**Issue by calebsander** [sublimehq/Packages#791]
These two work as expected:
````javascript
const abc = new Set()
console.log('abc') //"console" is highlighted as a special object
````
and
````javascript
const abc = new Set;
if (true) console.log('abc') //"if" is highlighted as a control word
````
But neither of these work:
````javascript
const abc = new Set
console.log('abc') //"console" is not highlighted
````
````javascript
const abc = new Set
if (true) console.log('abc') //"if" is not highlighted
````
![image](https://cloud.githubusercontent.com/assets/4256376/22407988/2b1eb02a-e63f-11e6-80bc-6557c5b9e295.png)
These are all valid ways to write the same thing.

**Comment by keith-hall** [comment]
Recommended reading:
https://www.ecma-international.org/ecma-262/5.1/#sec-7.9
https://www.codecademy.com/blog/78

**Comment by calebsander** [comment]
Not sure what your point is. According to the ECMAScript specification, it is valid to omit the semicolon after invoking a constructor if it terminates the line. The parentheses are also optional when invoking a constructor with no arguments.

**Comment by keith-hall** [comment]
The point is to reference the rules, so that we know what rules to follow when updating the syntax definition...
