### ISSUE TITLE
[CSS]: Completions not working in meta-scope

### ISSUE THREAD

**Issue by idleberg** [sublimehq/Packages#794]
First, please consider the following snippet:

    <snippet>
        <content><![CDATA[
    /* this is a test */
    ]]></content>
        <tabTrigger>test</tabTrigger>
        <scope>source.css meta.property-list.css</scope>
    </snippet>

This will expands as expected at this cursor position (`|` marks the cursor):

    body {
        |
    }

Now, consider the following completions file:

    {
      "completions": [
        {
          "contents": "/* this is a test */", 
          "trigger": "test"
        }
      ], 
      "scope": "source.css meta.property-list.css"
    }

I would expect this to expand at the same cursor position, but it does not work at all. The same completion using `source.css` will expand only outside a CSS selector.

**Comment by keith-hall** [comment]
Seems like this is by design: https://github.com/sublimehq/Packages/blob/69549082dfb4d958f61f819bd8285af1aed5ed86/CSS/css_completions.py#L504

**Comment by keith-hall** [comment]
Actually, it seems like it is enough to prevent `|` being seen as a valid property name, and this solves everything - colons and hyphens don't cause problems here: 

```diff
--- Packages\CSS\css_completions.py
+++ Packages\CSS\css_completions.py
@@ -416,7 +416,7 @@
         # Append values that are allowed for all properties
         allowed_values += ['all', 'inherit', 'initial', 'unset']
 
-        for name in names.split():
+        for name in names.split(' | '):
             props[name] = sorted(allowed_values)
 
     return props
```

**Comment by idleberg** [comment]
> Actually, it seems like it is enough to prevent | being seen as a valid property name

Not sure what this means. I used `|` in my example above to mark the cursor position.

**Comment by keith-hall** [comment]
I realise that, I'm talking about e.g. https://github.com/sublimehq/Packages/blob/69549082dfb4d958f61f819bd8285af1aed5ed86/CSS/css_completions.py#L139
