### ISSUE TITLE
[Ruby] highlighting breaks with backtick in regex

### ISSUE THREAD

**Issue by buildersbrewery** [sublimehq/Packages#797]
Syntax highlighting breaks with backtick in regex.

Compare:

* [jneen/rouge`/lib/rouge/lexers/javascript.rb`#160](https://github.com/jneen/rouge/blob/e9599c4735236a086cf913379a29607ebb12b00d/lib/rouge/lexers/javascript.rb#L160)

**Comment by wbond** [comment]
This is fixed by 4325016
