### ISSUE TITLE
Shell Syntax Highlighting Bux On Default

### ISSUE THREAD

**Issue by stevekuznetsov** [sublimehq/Packages#80]
When using double quotes (`"`) to expand a variable in the default setting for a environment variable, syntax highlighting fails for the rest of the file:
![bash](https://cloud.githubusercontent.com/assets/7328370/8834378/d8a9a274-3081-11e5-816f-c37c7e8759a2.png)

**Comment by jfcherng** [comment]
If you don't mind to use a temporary solution, [here](https://github.com/sublimehq/Packages/pull/47) it is.

It looks like there would be a complete rewrite from Jon or whoever.
