### ISSUE TITLE
[Go] syntax highlighting broken when string literal contains `:=`

### ISSUE THREAD

**Issue by tamird** [sublimehq/Packages#809]
Reproduction:

```go
package main

func main() {
	foo(" := ")
}

func foo(string) {}
```

Here's what it looks like on my machine:
![sublime_go_syntax](https://cloud.githubusercontent.com/assets/1535036/22950407/7fa12222-f2d3-11e6-8812-ad5f64816c66.png)

**Comment by wbond** [comment]
This was fixed with d694a0b1ac222c3de998ede23c380898b165136b, which will be part of the next dev build.
