### ISSUE TITLE
[Ruby] Some words behave unexpectedly when used as variable names

### ISSUE THREAD

**Issue by cuzox** [sublimehq/Packages#812]
This portion was taken from Packages/Ruby/Ruby.sublime-syntax:
```ruby
# Methods that may be followed by a regex
    - match: |-
        (?x:
          \b(
            gsub!|
            sub!
          )(?=\s)
          |
          \b(
            assert_match|
            gsub|
            index|
            match|
            scan|
            sub
          )\b
        )
      scope: support.function.builtin.ruby
      push: try-regex
```

When any of those words are followed by a division sign, everything after it will show commented. 

Say here:

```Ruby
  def bubble_up(index)
    parent_index = (index / 2)

    # return if we reach the root element
    return if index <= 1

```

Anything after "/" will be shown commented.

**Comment by wbond** [comment]
This is going to be very hard to get right. There is no way to know with ruby that index is not a method call accepting a multi-line regex.

**Comment by djspiewak** [comment]
@wbond As a first thought, we could try duplicating some of the expression rules: one set for inside parens, one for outside. When the regex rule inside parens hits an unbalanced trailing paren, it pops out.
