### ISSUE TITLE
[C++] Casts to template types are not always matched correctly

### ISSUE THREAD

**Issue by imoraru** [sublimehq/Packages#817]
There seems to be a bug with matching casts of template types. For example, in the screenshot, the first cast matches correctly, but the second one does not:

![image](https://cloud.githubusercontent.com/assets/827824/23567220/29b8fee0-000a-11e7-9f2a-0293f5aaf871.png)

**Comment by wbond** [comment]
This should be fixed by 5b325fa

**Comment by imoraru** [comment]
Verified, thanks!
