### ISSUE TITLE
[C++] wrong syntax coloring involving multiple inheritance and macros

### ISSUE THREAD

**Issue by rwols** [sublimehq/Packages#818]
### Summary

This fails to render correctly:

```c++
#define version 2
class A {};
class B {};
class C 
    : public A
#if version < 3
    , public B
#endif
{

};
```
![schermafbeelding 2017-03-04 om 23 39 42](https://cloud.githubusercontent.com/assets/2431823/23582824/e7ab2980-0133-11e7-846a-0b11ae5a8f71.png)

### Expected behavior

The line `    , public B` should be colored the same way as the line `    : public A`. The macro `#if version < 3` should be colored like any other macro.

### Actual behavior

`    : public A` is rendered correctly. `#if version < 3` trips and subsequently `    , public B` is wrong too. The behaviour from then onwards is correct again.

### Steps to reproduce

1. Open new file
2. Paste above snippet
3. Set syntax to C++

### Environment

macOS, build 3126.

**Comment by rwols** [comment]
It seems to also affect namespace endings:

![schermafbeelding 2017-03-05 om 01 27 01](https://cloud.githubusercontent.com/assets/2431823/23583390/64961de2-0143-11e7-9157-7ff8cc9bf587.png)

**Comment by TheClams** [comment]
This seems fixed in the latest dev build (3129)

**Comment by rwols** [comment]
Can confirm it looks to be fixed in build 3129. Great work!

**Comment by wbond** [comment]
Is the meta scoping for the namespace block correct?

I don’t recall a specific fix for this being applied…

**Comment by rwols** [comment]
Yes, everything seems to be correct; here are some scopes:

```cpp
#define version 2
namespace X {
class A {};
class B {};
class C 
    : public A
#if version < 3
    , public B
/*    ^ source.c++ meta.namespace.c++ meta.block.c++ meta.class.c++ storage.modifier.c++ */
#endif
{

};
} // namespace X
/* <- source.c++ meta.namespace.c++ meta.block.c++ punctuation.section.block.end.c++ */
```
