### ISSUE TITLE
C - Pre-pocessor directives are not highlighted if written without space

### ISSUE THREAD

**Issue by WsDwA1022** [sublimehq/Packages#819]
The latest sublime syntax package. If there is a space after **include** directive, it is highlighted correctly:
```C
#include <stdio.h>
```
But, if space is missing, the whole line stays black, like this:
```
#include<stdio.h>
```
while it should look like this:
```C
#include<stdio.h>
```
C syntax specification allows missing space, so this is correct syntax.

**Comment by keith-hall** [comment]
https://github.com/sublimehq/Packages/issues/748

**Comment by WsDwA1022** [comment]
@keith-hall So, if that issue is already fixed, feel free to close this one.

**Comment by keith-hall** [comment]
I am just a contributor to this repo, I don't have powers to close issues. But I can assure you, that if you use the latest syntax from the master branch, your `#include` will be highlighted correctly. Feel free to verify and close the issue yourself :)
