### ISSUE TITLE
C - Highlighting problem with closed braces

### ISSUE THREAD

**Issue by WsDwA1022** [sublimehq/Packages#829]
Minimal code which reproduces the issue:
```C
#define a {
int main(void)a return 0;}
```
This is correct C syntax. The closing brace here is misinterpreted and highlighted like there is no open one.

![1](https://i.imgur.com/7eP5kTV.png)

**Comment by wbond** [comment]
There is a lot of C that we won't ever be able to handle because of preprocessor macros.

This seems like it is destined to be one of them.

**Comment by WsDwA1022** [comment]
What about storing all macro definition in some internal data structure and then internaly replacing all occurences of them in source before applying regex test? (of course there can be used cache and other optimization techniques to make it fast) Microsoft Visual Studio has pretty good way to handle this type of syntax, so it doesn't look very hard to introduce it in Sublime too.

This type of syntax is not so rare. It appears a few times in some Linux kernel source code scripts. This "dangling" brace highlinghting can be very annoying and also sometimes can cause the rest of the code to be highlighted wrong.

**Comment by wbond** [comment]
@WsDwA1022 The complexity and performance impact of what you describe is at odds with the implementation of the syntax highlighting engine.

I spent some time working on trying to deal with some usages of the C-preprocessor using the techniques you have alluded to, but it was going to require completely re-architecting how the engine worked, which would have effectively destroyed performance, and the way to expose such functionality to the `.sublime-syntax` format was not obvious to me.

**Comment by wbond** [comment]
I mean, in one sense you are asking the syntax highlighting engine to do a project-wide C-preprocessor pass of the code, on the fly, and then to track exactly what changed, and throw away all of that information to try and leave the scope information correct.

**Comment by WsDwA1022** [comment]
@wbond Ok, I am closing this issue because it is obviously harder to solve than I thought.
