### ISSUE TITLE
[JavaScript] Should the comma operator be highlighted as an operator?

### ISSUE THREAD

**Issue by Thom1729** [sublimehq/Packages#831]
In JavaScript, the comma is most often used as separator punctuation: in array and object literals, function formal parameters, function arguments, and variable declarations. However, the language also has a comma operator. It is described as an operator in the spec and it behaves like any other binary operator.

The built-in JavaScript syntax does not distinguish between the comma operator and the other uses of the comma. One consequence of this is that two very different constructions may be highlighted identically:

```js
myVar;
[1, 2, 3];
```
```js
myVar
[1, 2, 3];
```

In the former example, the commas are punctuation separating array elements. In the latter example, the commas are operators. There is an enormous semantic difference between these examples. In the latter case, because the commas are not highlighted as operators, someone reading the code is likely to misinterpret it as equivalent to the former case.

One might argue that the latter is probably a mistake by the programmer. I concur, but to me this makes it even more important to clearly distinguish the comma operator.

It seems to me that the comma operator should be marked as `keyword.operator.comma.js` (while other uses of the comma remain `punctuation.separator.comma.js`).

**Comment by FichteFoll** [comment]
Could you explain what exactly the "comma operator" it is and when it is used? So far, it appears to be for slicing, but that's just a guess.

**Comment by Thom1729** [comment]
The comma operator takes two arguments and evaluates to the latter. It does not short-circuit.

```js
var x;
x = (1,2,3);
console.log(x); // 3
```

JavaScript doesn't have a slice syntax. The statement `myVar[1, 2, 3];` is equivalent to `myVar[3];` (because the expressions `1` and `2` have no side effects). Deliberate use of the comma operator is fairly rare in written JavaScript, although I see it more often in minified code. *Accidental* use of the comma operator as a result of missing semicolons is probably more common. Distinguishing the comma operator from the comma punctuation that is used in function calls etc. would visually distinguish constructions with identical text but very different semantics.

**Comment by wbond** [comment]
There are many little edge cases like these that come up when trying to write syntaxes for different languages, but sharing a set of scope name conventions.

In this case, I think most users would find having some instances of `,` scopes as an operator and others as a separator very odd, and would likely consider it a bug.

For the default JavaScript syntax I don't think we'll want to do this.

**Comment by FichteFoll** [comment]
>In this case, I think most users would find having some instances of , scopes as an operator and others as a separator very odd, and would likely consider it a bug.

@Thom1729's argument was that it most likely *is* a bug in their code and that the different scope and highlighting should reflect that. They do a very different thing after all.

So, I do think there is value in matching the comma operator and it merely depends on whether it is worth implementing, depending on how much effort it would be.

**Comment by Thom1729** [comment]
That's the idea. The default syntax even does the same thing for the colon: the key-value separator is scoped differently from the ternary conditional operator, even though they're both represented by the colon.

```js
({
    foo: true ? 1 : 0
//     ^ punctuation.separator.key-value.js
//                ^ keyword.operator.ternary.js
})
```

As far as implementation, it would probably be as easy as:

- Changing the current highlighting for the comma in `expressions` to `keyword.operator`.
- Creating an `expression-list` context that marks the comma as a separator and includes `expressions`.
- Updating various other contexts to refer to `expression-list` rather than `expression`.

I can try to put together a brief PR tomorrow.

**Comment by Thom1729** [comment]
The JavaScript syntax does not currently distinguish between array literals and property accesses (#324). This should itself be a reasonably simple change, although the correct scope seems to be ambiguous (#790). I will look into this.

Without #324, this proposal cannot be implemented.
