### ISSUE TITLE
C - Assembler template string highlighted like a bad escaping sequence

### ISSUE THREAD

**Issue by WsDwA1022** [sublimehq/Packages#864]
Code which causes issue:

```C
int main(void){
  unsigned int a;

  __asm__("mov 4(%%ebp),%0" : "=r"(a) : :);
  printf("%d\n", a);

  return 0;
}
```

The problem is **%0** which is highlighted like a wrong escaping sequence (probably Sublime is expecting a letter after the number **0**). But, this is correct syntax. **%0** is not escaping sequence, but instead C assembler template character sequence representing operators coresponding to the C expression (in this case output variable).

Screenshot:

![](https://i.imgur.com/sDsJc5j.png)

**Comment by wbond** [comment]
This should be resolved by 7e9eece
