### ISSUE TITLE
[C] Wrong auto-indentation level after a loop without body

### ISSUE THREAD

**Issue by ghost** [sublimehq/Packages#868]
Example:

```c
int main(void){
  int a;

  for(a = 0; a < 1; printf("%d\n", a++));

  return 0;
}
```

If cursor is set to position at the end of the line containing for loop and enter is pressed, indentation level increases like we are in a new code block. But actually, this for loop has no body, so indentation level should remain the same.

OTOH in the following example while loop works correctly:

```c
int main(void){
  int a = 1;

  while(printf("%d\n", --a), a);

  return 0;
}
```

Here after while loop indentation level stays the same, which means that the problem is related only to for loops;

**Comment by keith-hall** [comment]
You could change [this regex](https://github.com/sublimehq/Packages/blob/59d749c1d73198cd848357d7c89740c915ee8b6a/C%2B%2B/Indentation%20Rules.tmPreferences#L26) to `^ \s* \bfor\b \s* (?:[^;]++|;[ ]+(?!$))+ \s* $` to get it to ensure a `;` isn't at the end of the line before deciding to indent the next line.

**Comment by WsDwA1022** [comment]
@keith-hall So, should I create a PR?

**Comment by keith-hall** [comment]
A regex like this would seem to cover most scenarios, including comments (as long as the parens are balanced before the closing `for` paren):

```regex
^ \s* for\b \s* \(

(?<balanced_parens>
    [^()]++
    (?:\(\g<balanced_parens>\)[^()]*+)?
)

\)
(?<eol_or_comment>\s*(?:$|//|/\*(?:(?:(?!.*\*/).*$|.*?\*/\g<eol_or_comment>))))
```
