### ISSUE TITLE
[Java] storage classes are ignored after final atribute

### ISSUE THREAD

**Issue by evandrocoan** [sublimehq/Packages#869]
You should see something like this missing:

![image](https://cloud.githubusercontent.com/assets/5332158/24584065/97943112-1736-11e7-8936-f3730fc25767.png)

Create a file called `java.java` and put this as its contents:
```java
/**
 * @author Grafo
 */
public class Grafo
{
   private static final Logger LOG = Logger.getLogger( Grafo.class.getName() );

   public Grafo()
   {
      this.éOrientado = false;
   }

   public Grafo( final boolean éOrientado )
   {
      this();
      this.éOrientado = éOrientado;
   }
}
```

Sublime version 3114, with default Java syntax.

**Comment by keith-hall** [comment]
Looks like this has been fixed here since build 3114 was released.

**Comment by evandrocoan** [comment]
Yes, I just installed.
