### ISSUE TITLE
[JavaScript] Regex with escaped backslash is formatted like a comment

### ISSUE THREAD

**Issue by ghost** [sublimehq/Packages#874]
Multiplying and dividing a regex with escaped backslash by a literal number results in wrong highlighting.

```js
console.log(/\//*1);
```

and

```js
console.log(/\///1);
```

**Comment by aziz** [comment]
While these things are getting fix here, if you want the most correct syntax highlighting of JS try [Ecmascript-Sublime](https://packagecontrol.io/packages/Ecmascript%20Syntax)

It can also parse the other bug you reported correctly.

**Comment by WsDwA1022** [comment]
@aziz Nice, I didn't know for that package. It seems to be the most detailed highlighting engine for JavaScript. However, it took me about a hour to find a [bug](https://github.com/bathos/Ecmascript-Sublime/issues/30) there ;)
