### ISSUE TITLE
PHP syntax highlighting ('?>')

### ISSUE THREAD

**Issue by vaxo** [sublimehq/Packages#88]
### question mark is black.
![Alt text](https://i.gyazo.com/66bcc38e6f31a323bd5e6e6e62d9d2f4.png)

Espresso Soda.tmTheme fragment for php start/end tags:
``` xml
<dict>
  <key>name</key>
  <string>PHP Tags</string>
  <key>scope</key>
  <string>punctuation.section.embedded.begin.php, punctuation.section.embedded.end.php</string>
  <key>settings</key>
  <dict>
    <key>fontStyle</key>
    <string>bold</string>
    <key>foreground</key>
    <string>#d5474f</string>
  </dict>
</dict>
```

Sublime Text version: **3, DevChannel, Build 3095**

**Comment by wbond** [comment]
This should be solved by d761420c96963b808fb7f72c4d344d67d07e6f89.
