### ISSUE TITLE
diff: doesn't work on some color schemes

### ISSUE THREAD

**Issue by pdknsk** [sublimehq/Packages#887]
Notably on _Blackboard_, and a few others. I don't know why.

**Comment by keith-hall** [comment]
some(/many/all?) of the legacy color schemes don't target `markup` scopes at all, but my understanding is that all the color schemes except Monokai that ship with ST3 are now considered obsolete. As there are so many decent third party color schemes out there, it doesn't make sense for our favorite 2 developers to spend time tweaking these color schemes - and thus taking time away from the core ST work they do - when the community does such an awesome job creating and maintaining color schemes.

**Comment by pdknsk** [comment]
​Thanks for the explanation. Where can I find those third party color
schemes? Also I think ST3 should perhaps not ship the legacy schemes then,
or display a warning at least.​

**Comment by keith-hall** [comment]
Agreed :)

Third party color schemes can be found at https://packagecontrol.io/browse/labels/color%20scheme

**Comment by pdknsk** [comment]
Unfortunately I couldn't find a _Blackboard_-like theme, at least in the most used themes. So I copied and adapted the missing sections from _Monokai_.
```XML
<dict>
    <key>name</key>
    <string>diff.header</string>
    <key>scope</key>
    <string>meta.diff, meta.diff.header</string>
    <key>settings</key>
    <dict>
        <key>fontStyle</key>
        <string></string>
        <key>foreground</key>
        <string>#AEAEAE</string>
    </dict>
</dict>
<dict>
    <key>name</key>
    <string>diff.deleted</string>
    <key>scope</key>
    <string>markup.deleted</string>
    <key>settings</key>
    <dict>
        <key>foreground</key>
        <string>#FF6400</string>
    </dict>
</dict>
<dict>
    <key>name</key>
    <string>diff.inserted</string>
    <key>scope</key>
    <string>markup.inserted</string>
    <key>settings</key>
    <dict>
        <key>foreground</key>
        <string>#61CE3C</string>
    </dict>
</dict>
```
