### ISSUE TITLE
[Python] Function call scope regression

### ISSUE THREAD

**Issue by michaelblyons** [sublimehq/Packages#898]
I'd been using the `variable.function.python` to highlight function/method calls in Python:

```python
some_obj.its_method(param)
#        ^^^^^^^^^^ variable.function.python
```

This stopped working in the current `master`. A bisect suggests that it was merged with #743.

```
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
484576c1e864df06c48d17808388f571f77f4258
ae0bfdb228128b4b49f65b60c0d0adea514c54a3
fa29a796d2fe681ad21f77cbb0b0c8224cd8e3c5
We cannot bisect more!
```
I'd like to have it back, please.

**Comment by keith-hall** [comment]
This seems to be working for me - are you using build 3128? if not, then probably this bug (fixed in 3128) is causing it: https://github.com/SublimeTextIssues/Core/issues/1190

**Comment by michaelblyons** [comment]
You are correct. Thanks, Keith.
