### ISSUE TITLE
[C#] Wrong syntax highlighting for final letter of switch cases

### ISSUE THREAD

**Issue by bdjones** [sublimehq/Packages#902]
Any `case` in a `switch` statement that's more than 1 letter long receives the wrong syntax highlighting for the final letter.

```
switch( activeContext ) {
	case BLBodyBattleLibrary.ContextType.TapUp:
		break;
	// ...
```

![Example](http://i.imgur.com/zIAAbrF.png)

(Build 3129)

**Comment by keith-hall** [comment]
Looks like the bug is here: https://github.com/sublimehq/Packages/blob/d15cd7fb209c5ff7a53f47d1fac235f406f903b5/C%23/C%23.sublime-syntax#L1701
