### ISSUE TITLE
makefile: built-in functions bug

### ISSUE THREAD

**Issue by pdknsk** [sublimehq/Packages#903]
![1](https://cloud.githubusercontent.com/assets/1097609/25075022/b5f1ef98-230a-11e7-970b-f3501c56a2a7.png)

The `:` apparently opens a scope without closing it. Works with other functions too.
```Makefile
$(warning Bug: $(BUG))
```

**Comment by rwols** [comment]
A naive fix would be to include the `variable` context in the `main` context, but I'm not sure if other things will start breaking in that case.

Just leaving this syntax test here for reference.

```makefile
$(warning he:llo)
# ^ meta.support.function support.function.builtin
#         ^ meta.support.function
#               ^ meta.support.function punctuation.definition.variable.end

all: deps
	$(warning he:llo)
	# ^ meta.function.body meta.support.function support.function.builtin
	#         ^ meta.function.body meta.support.function
	#               ^ meta.function.body meta.support.function punctuation.definition.variable.end
deps:
	$(warning he:llo)
```

**Comment by deathaxe** [comment]
@wbond: This issue is closed by https://github.com/sublimehq/Packages/pull/974

**Comment by wbond** [comment]
This issue has been solved by a previous commit, hence it is being closed.
