### ISSUE TITLE
[Scala] Broken index and code navigation since dev build 3127

### ISSUE THREAD

**Issue by agemooij** [sublimehq/Packages#908]
I'm running 3129 at the moment and index-based navigation is completely broken. I can't jump to the definition of any class, method, functional, val, or anything anymore. Some things are still reachable through direct search but not everything that used to work before 3127.

Context: ST3 3129 for MacOS (10.12.4)

**Comment by wbond** [comment]
Can you provide some examples?

@djspiewak would mind taking a look?

**Comment by djspiewak** [comment]
On it.

@agemooij An example snippet (or repo) would be most helpful.  Just double checking: are you sure indexing completed? Most complex scala repos seem to take around 5-10 seconds to index, so I'm assuming it did, but just checking.

**Comment by agemooij** [comment]
What I've seen so far is a complete breakdown of cross-code navigation for both in-project resources (e.g. between entities in two different Scala files in the same project) and library code linked in through sbt-sublime. 

Restarts of ST don't work and things don't improve over time. I've tried loading different projects and they all show the same behavior.

For some projects I get the following status bar index status:

<img width="243" alt="screen shot 2017-04-18 at 17 24 49" src="https://cloud.githubusercontent.com/assets/46568/25138897/030a9896-245c-11e7-8d91-2c605f39b794.png">

But other projects show the normal state:

<img width="274" alt="screen shot 2017-04-18 at 18 03 33" src="https://cloud.githubusercontent.com/assets/46568/25140649/5ee04968-2461-11e7-800f-e476cca6efc2.png">

Perhaps I'm just experiencing a broken index? Is there a way to reset an index? Where are they stored?

**Comment by wbond** [comment]
Can you provide the source code of a file that contains code you would expect to be indexed?

You can see the status of the indexer via the *Help > Indexing Status…* menu. What you provided a screenshot of is some third-party package.

Are you using the built-in symbol navigation, or is it provided by another package?

**Comment by agemooij** [comment]
I don't have a _Help > Indexing Status…_ menu. Here's a screenshot of my help menu:

<img width="617" alt="screen shot 2017-04-18 at 18 28 01" src="https://cloud.githubusercontent.com/assets/46568/25141782/ef0313ba-2464-11e7-921a-1f3928c27ae5.png">

I'm using the builtin symbol navigation, e.g. "Goto Definition" aka "Alt+Cmd+ArrowDown"

My project is a run of the mill Scala project that is hard to extract into an example. Everything worked fine with this functionality for multiple years and many projects over multiple machines and multiple OS versions and it's only after the 3127 dev build landed that I could no longer use symbol navigation.

I'll try to downgrade to a pre-3127 version to see whether that solves the problem.

**Comment by wbond** [comment]
You must have a menu override in place, so it may be that you have other overrides in place that are preventing the current preferences files that control indexing to work properly.

Can you try seeing if indexing works in a reverted state? Be sure to save your data dir instead of deleting it. http://www.sublimetext.com/docs/3/revert.html

**Comment by agemooij** [comment]
OK, everything works with a fresh state. I also have the index item in the Help menu now. 
I'm now reinstalling my essential packages but there is no obvious candidate for the source of these so I'm very curious which combination of packages caused this.

I'll update here with how that works out before I close the issue.

**Comment by agemooij** [comment]
I've reinstalled my packages and reloaded my preferences on top of an empty install and I cannot reproduce the problem anymore. This means it was clearly something in my local install and not a bug in ST or the Scala package.

The root cause is still unknown but I have been carrying that configuration across from multiple laptops ever since using ST2 and over the years Ive installed and uninstalled many packages so I guess at some point somewhere something broke.

Thanks for helping me debug this!

**Comment by wbond** [comment]
If you copied configuration from ST2, that is almost certainly the issue. ST2 used unpacked packages, which would act like overrides in ST3.

**Comment by velvia** [comment]
Thanks for the instructions here.  I was having similar problems, cleared out the state per the link above, reinstalled packages, and now option-command-down to go to definition works.   So happy.  :)
