### ISSUE TITLE
SQL Keywords

### ISSUE THREAD

**Issue by jbrooksuk** [sublimehq/Packages#92]
- `LESS THAN`
- `MORE THAN`

**Comment by wbond** [comment]
What database engine supports these?

Also, FYI, I just pushed up a bunch of additions to the SQL grammar.

**Comment by wbond** [comment]
@jbrooksuk Ping

**Comment by jbrooksuk** [comment]
MySQL for sure.

**Comment by wbond** [comment]
Can you link to some docs?

```
mysql> select * from phpbb_users where user_id LESS THAN 10;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'LESS THAN 10' at line 1
```

**Comment by jbrooksuk** [comment]
Sorry, my comment was incorrect.

**Comment by wbond** [comment]
If you do know of any engines that support this, I'm happy to add it. I looked into MySQL, SQLite, PostgreSQL and SQL Server.

**Comment by FichteFoll** [comment]
DB2 has a few more like "UNIQUE" and indentity stuff. Not sure if you want to implement those too.
