### ISSUE TITLE
CSS: calc() highlighting incorrect beyond first parenthesis

### ISSUE THREAD

**Issue by pdknsk** [sublimehq/Packages#925]
It gets gradually worse for each parenthesis.

![1](https://cloud.githubusercontent.com/assets/1097609/25428759/00cc4ce8-2a77-11e7-8219-31504e9d555e.png)

**Comment by keith-hall** [comment]
Basically it just doesn't handle nested parens at the moment

**Comment by pdknsk** [comment]
I didn't know `calc` can be nested. It's not in the syntax definiton you linked, which only lists regular parenthesis. It's defined [elsewhere](https://drafts.csswg.org/css-values/#calc-notation) however.
> Components of a `calc()` expression can be literal values or `attr()` or `calc()` expressions.

**Comment by deathaxe** [comment]
Not sure whether this is related, but I have unlighted parentheses here, too.

![screenshot](https://cloud.githubusercontent.com/assets/16542113/25563975/c7b6313c-2da8-11e7-97ed-a75289b76547.png)
