### ISSUE TITLE
[Ruby] incorrect highlighting with slash and string

### ISSUE THREAD

**Issue by jslabovitz** [sublimehq/Packages#933]
Using build 3131, I'm noticing a regression in parsing code like this:

    a = b / 'c'
    d = e

It seems the combination of the slash and the quoted string (whether single or double quoted) is causing the entirety of the next few lines lines to be interpreted as a string.

(If you're curious, the above syntax is common when using the Path gem, and concatenating pathnames together.)

**Comment by randy3k** [comment]
I can confirm this.

**Comment by ZogStriP** [comment]
Happening to me too in Version 3.0, Build 3143 (on macOS if that matters)

**Comment by ZogStriP** [comment]
These issues are similar/related: #923, #1006

**Comment by randy3k** [comment]
#1142 should fix it.
