### ISSUE TITLE
[LaTeX] Bad document rendering after dollar sign $

### ISSUE THREAD

**Issue by evandrocoan** [sublimehq/Packages#937]
This document is rendered wrong after the dollar sign `$`, the scope `string.other.math.tex` is pushed into the stack, but should not:
```latex
\documentclass{article}
\usepackage{array}
\newcolumntype{$}{>{\global\let\currentrowstyle\relax}}
\newcolumntype{^}{>{\currentrowstyle}}
\newcommand{\rowstyle}[1]{\gdef\currentrowstyle{#1}%
  #1\ignorespaces
}

\begin{document}
\begin{tabular}{$l^c^r}
\rowstyle{\bfseries}
a & a & a \\
b & b & b \\
c & c & c \\
\end{tabular}
\end{document}
```

![image](https://cloud.githubusercontent.com/assets/5332158/25506494/52485510-2b7d-11e7-9fe0-4e47f5d9f1eb.png)

This code is from: 

1. https://tex.stackexchange.com/questions/4811/make-first-row-of-table-all-bold

**Comment by FichteFoll** [comment]
Works for me on 3131. Do you perhaps have an override in place? (Check with [OverrideAudit](https://packagecontrol.io/packages/OverrideAudit))

![img](https://x0.at/-Ep.png)

**Comment by evandrocoan** [comment]
Thanks for testing. I will check it.

Sorry, I forgot to mention, may be it could be because I am using the build 3114.
