### ISSUE TITLE
[CSS] Nested comments break highlighting

### ISSUE THREAD

**Issue by deathaxe** [sublimehq/Packages#957]
Adding a `/* ... */` within an existing comment, results in the final `*/` not being matched anymore.

![screenshot](https://cloud.githubusercontent.com/assets/16542113/25563999/54102d22-2da9-11e7-93be-f15dc1223a02.png)

**Comment by rwols** [comment]
I'm not too familiar with CSS, but isn't it supposed to work like this? You end the comment block at the first `*/`, and then the one after that is just considered a stray end-of-comment-block token. Do browsers render this correctly?

**Comment by rwols** [comment]
[Comments may not be nested](https://www.w3.org/TR/CSS2/syndata.html#comments).

**Comment by deathaxe** [comment]
Understand. So it is an `illegal.invalid` instead?

Did not see any parse errors or something like that, so I expected it to be a valid construct.  Not that I intend to use something like that normally. It was just the result of some investigations.

**Comment by rwols** [comment]
> So it is an `illegal.invalid` instead?

Well, ideally yes, but the current syntax def doesn't account for that it seems.

**Comment by wbond** [comment]
I'm hesitant to add too many `invalid` scopes. We've been bitten by a number of false positives in the past. I'd rather rely on a linter than have false-positives.

**Comment by deathaxe** [comment]
I honestly was not aware of CSS not supporting such constructs by the specs. Just was wondering why it was not highlighted. As @rwols correctly pointed on the specs, this is not a real issue.
