### ISSUE TITLE
[HTML] Stop indexing every tag attribute

### ISSUE THREAD

**Issue by michaelblyons** [sublimehq/Packages#958]
With the Goto Anything command in an HTML file<sup>1</sup>, every single tag attribute (afaik) is in the list, which makes it rather noisy without much benefit.

When I tried to fix this with a Symbol List Banned, I ended up breaking indexing of embedded CSS. Presumably, If you have a `<style>` tag, the CSS in it should be indexed, including selectors with classes `div.like-this.or-this`.

<sup>1</sup> And derivatives?

**Comment by keith-hall** [comment]
My experience is that only the `id` attribute is indexed, which I think makes sense. Maybe you have some third party packages installed that is adding noise to the symbol list?
https://github.com/sublimehq/Packages/blob/54340707ecbf7de99ab5b02b9414258bd27ed403/HTML/Symbol%20List%20-%20ID.tmPreferences

Can you perhaps share a specific example please, of a HTML document and a screenshot of what shows up in Goto Anything? Then you can prove me wrong :D

**Comment by michaelblyons** [comment]
You're right. It must be one of my packages, though I haven't worked out which one.

**Comment by kleinfreund** [comment]
Are we talking about *Goto Symbol* instead of *Goto Anything*? I have every attribute listed there as well.

**Comment by keith-hall** [comment]
Yes, we are indeed talking about Goto Symbol :) probably you both have an installed package in common?

**Comment by michaelblyons** [comment]
@kleinfreund: Yes, I misspoke earlier. So <kbd>cmd</kbd>+<kbd>P</kbd>, <kbd>@</kbd>.
@keith-hall: Klein is right. On a fairly minimal Sublime Text 3, <kbd>cmd</kbd>+<kbd>P</kbd>, <kbd>#</kbd> _does_ show a bunch of attribute names (but this was not my complaint). On that system, <kbd>cmd</kbd>+<kbd>P</kbd>, <kbd>@</kbd> only shows what I would want.

Is there a way to `grep` all the installed package contents without unzipping a bunch of `foo.sublime-package` files?

**Comment by keith-hall** [comment]
Maybe something like

```python
[(file_path, contents) for (file_path, contents) in ((file_path, sublime.load_resource(file_path)) for file_path in sublime.find_resources('*.tmPreferences')) if 'SymbolList' in contents]
```

**Comment by michaelblyons** [comment]
Thanks Keith. That helped me track it down. I don't use the ST console much, and I forget it's just a python interpreter. The problem turned out to be [a Sass package.](https://packagecontrol.io/packages/Syntax%20Highlighting%20for%20Sass)

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Goto Symbol in Project</string>
	<key>scope</key>
	<string>entity.name.tag.css.sass.symbol, entity.other.attribute-name, comment.tag.sass</string>
	<key>settings</key>
	<dict>
		<key>showInSymbolList</key>
		<integer>1</integer>
		<key>showInIndexedSymbolList</key>
		<integer>1</integer>
	</dict>
	<key>uuid</key>
	<string>71B52B90-82BB-11E2-9E96-0800200C9A66</string>
</dict>
</plist>
```

**Comment by keith-hall** [comment]
Seems like by design:
https://github.com/P233/Syntax-highlighting-for-Sass/issues/15#issuecomment-27174459

> Added support for Sublime Text 3 'Goto Symbol in Project'. Now 'Goto Symbol' will list all HTML tags, ID selectors, Class selectors, and Comment Tags in current file, and 'Goto Symbol in Project' will list all `@mixin`, `@function`, and Comment Tags in current project.
