### ISSUE TITLE
[TCL] foreach for can't highlighted in proc body

### ISSUE THREAD

**Issue by ZhiPing-S** [sublimehq/Packages#963]
![default](https://cloud.githubusercontent.com/assets/16476209/25737512/d9e2f466-31aa-11e7-888d-336c527fd9e1.png)

**Comment by keith-hall** [comment]
Please include the text used in the screenshot for easier reproduction via copy and paste.

**Comment by joherv** [comment]
To clarify a bit on this. Sytax highlighting does not work for TCL inside while loops, for loops and foreach loops (maybe other bodies as well). I'm using build 3133, but have also tested with 3127 with the same results. Could this be a result of the fix for issue #645 ?

```
proc test {} {

	set saoid [svcmap_saoid sm]

	# Syntax highligting works inside an if statement:
	if {[defvar cpe_uplink_ifoid 0] == 0} {

        array set cpe_param [objectGetField -oid $cpeoid -fieldname parameters]
        if {[info exists cpe_param(model)]} {
            set cpe_model $cpe_param(model)
        } else {
            error "ERROR: Model not set"
        }
    }

    # but not within for example a foreach loop:
    foreach cpe_ifoid [objectTreeFind -oid $cpeoid -walkdown 0 -classmask interface] {
        set cpe_if_role [objectGetField -oid $cpe_ifoid -fieldname role]
        if {[string match "uplink.running" $cpe_if_role]} {
            set cpe_uplink_ifoid $cpe_ifoid
            set cpe_uplink_name [objectGetField -oid $cpe_uplink_ifoid -fieldname name]
            break
        }
    }
}
```

**Comment by keith-hall** [comment]
I don't know TCL at all, but it seems one can fix it by changing [this `pop`](https://github.com/sublimehq/Packages/blob/03dff079bce4eb861d2b3a4d922ffb86bae84400/TCL/Tcl.sublime-syntax#L115) to

```yaml
      set:
        - match: '(?={{end_chars}})'
          pop: true
        - include: commands
```

**Comment by joherv** [comment]
That didn't change anything. Not sure if I edited the correct file though. I run OSX and edited /Applications/Sublime Text.app/Contents/MacOS/Packages/TCL.sublime-package
I restarted ST3 after the change.

This works fine in 3114 where syntax file just has the single pop statement. Must have been something introduced in the fix for #645 that broke this.

**Comment by keith-hall** [comment]
The fix for that issue doesn't seem to be related, you can try manually reverting it and see it makes no difference to the code snippet you posted here.

My suggestion works for me on build 3133:

![image](https://cloud.githubusercontent.com/assets/11882719/26780027/7c8ea432-49f0-11e7-9a87-5b63920b645f.png)

**Comment by joherv** [comment]
I edited the syntax file using PackageResourceViewer. That worked much better. Looks correct now. Thanks!

**Comment by joherv** [comment]
This fixed while, for and foreach loops, but the code inside a "switch" body is not highlighted correctly. Example:
`switch -- $parclass {
		"element-attach" {
			# CPE SA

			return [svcmap_hook_return sm]

		}

		"interface" {
			set ifoid $paroid
			set eaoid [elm_oid_by_iface $ifoid]
			set earole [objectGetField -oid $eaoid -fieldname role]
`
This looks like this:

![screen shot 2017-06-08 at 12 54 28](https://user-images.githubusercontent.com/22449723/26925334-b56c8aac-4c49-11e7-8752-ab528cb5a719.png)

**Comment by keith-hall** [comment]
How about, changing my suggestion of `- include: commands` to `- include: expr-body`? it looks like it fixes `switch` as well as `for` :)

**Comment by joherv** [comment]
Yes, works fine. Thanks again!
