### ISSUE TITLE
[Batch File] Word wrap not respected by content in this syntax

### ISSUE THREAD

**Issue by durgante** [sublimehq/Packages#967]
In user settings, wrap_width and rulers are set to 80 so the content should wrap at the ruler. But it never wraps.

![image](https://cloud.githubusercontent.com/assets/6627461/25755045/d2148e6a-3197-11e7-9082-8259be6e5aa9.png)

**Comment by keith-hall** [comment]
Can you check your syntax specific settings, maybe something there is overriding it for batch files

**Comment by durgante** [comment]
I did, it is empty. But I noticed that the word-wrap is not working in the config files. It does work in LaTeX content though.

![image](https://cloud.githubusercontent.com/assets/6627461/25762986/5a609dbc-31b7-11e7-8cd1-ce48d17231c3.png)

**Comment by keith-hall** [comment]
Sounds like `word_wrap` is set to `auto` when you want it `true`?

**Comment by durgante** [comment]
Exactly! Thank you so much for your help Keith!
