### ISSUE TITLE
[C++] Curly brackets in initializer list

### ISSUE THREAD

**Issue by pgrit** [sublimehq/Packages#979]
Using curly brackets to initialize a variable in a constructor initializer list yields incorrect syntax highlighting for the subsequent elements.
To me, it seems that the curly brackets are misinterpreted as the body of the constructor, and the subsequent items thus highlighted as function calls.
Example:
![screenshot from 2017-05-16 17-04-42](https://cloud.githubusercontent.com/assets/12607894/26113240/50bbd578-3a5a-11e7-9736-c8acab47ee5d.png)

**Comment by wbond** [comment]
This was fixed by #998
