### ISSUE TITLE
Language file for PHP doesn't support typehinted arrays with bracket syntax

### ISSUE THREAD

**Issue by MarianoGappa** [sublimehq/Packages#98]
The language file for PHP doesn't seem to support the "new" bracket syntax for arrays introduced on PHP 5.4 (http://php.net/manual/en/migration54.new-features.php).

Fortunately, the colouring still mostly works anyway; except when a function argument is typehinted.

##### Issue
![Issue](http://i.imgur.com/sDcLkkv.png)

##### I've created a Pull Request with a fix for it
https://github.com/sublimehq/Packages/pull/97

Thanks for your time.

**Comment by wbond** [comment]
Fixed via 4a62ad977ffd63ef2fd53e97709a0e123d184221, thanks!
