### ISSUE TITLE
CSS Grid & Custom Properties: var() inside repeat() breaks highlighting

### ISSUE THREAD

**Issue by kleinfreund** [sublimehq/Packages#987]
Syntax highlighting for CSS breaks when combining CSS Grid and Custom Properties features as follows. Using any CSS language feature containing parenthesis (e.g. `var()`) within the CSS Grid `repeat()` function (I just call it that now, because I have no internet connection to verify terminology right now) will break the syntax highlighting after the statement.

I can only observe this behavior for `repeat()`. Other nested *function calls* in my code work (e.g. `var()` within `calc()`).

```
.sample {
  display: grid;
  --size: 50%;

  grid-template: var(--size) var(--size) / var(--size) var(--size);
  /* ↑ This highlights correctly */

  grid-template: repeat(2, 50%) / repeat(2, 50%);
  /* ↑ This highlights correctly as well */

  grid-template: repeat(2, var(--size)) / repeat(2, 50%);
  /* ↑ Highlighting breaks as soon as `()` appears within repeat */
}
```

P.S.: I’m not sure whether this is a duplicate of https://github.com/sublimehq/Packages/issues/925.

**Comment by keith-hall** [comment]
I've included a fix for this in https://github.com/sublimehq/Packages/pull/926
