### ISSUE TITLE
[JavaScript] captures?

### ISSUE THREAD

**Issue by unreal666** [sublimehq/Packages#99]
for example, a piece of code:

    - match: '(?<!\.)[_$a-zA-Z][$\w]*\s*(?=[\[\.])'
      scope: variable.other.object.js
      captures:
        1: variable.other.object.js
    - match: '(?<=\.)\s*[_$a-zA-Z][$\w]*'
      scope: meta.property.object.js
      captures:
        2: variable.other.property.js

Capturing parentheses do not.

**Comment by wbond** [comment]
Could you perhaps include an example snippet of code, along with the desired behavior and the current behavior?

**Comment by unreal666** [comment]
In the above, there is a code "captures: ...".
But themselves capturing parentheses in "match:" are absent.

**Comment by wbond** [comment]
Thank you for the explanation. This should be resolved in 11ca312c279e95db74e0ae2585b164419f47c599.
