### ISSUE TITLE
[PHP] DNS_CAA type constant missing from PHP/PHP Source.sublime-syntax

### ISSUE THREAD

**Issue by alister** [sublimehq/Packages#991]
```
echo DNS_CAA, DNS_A, DNS_CNAME, DNS_HINFO, DNS_MX, DNS_NS, 
     DNS_PTR, DNS_SOA, DNS_TXT, DNS_AAAA, DNS_SRV, DNS_NAPTR,
     DNS_A6, DNS_ALL, DNS_ANY;
```

If the above line is put into `PHP/syntax_test_php.php`, the first item, `DNS_CAA` is highlighted differently to the rest of the line. According to the [dns_get_record#type](http://php.net/manual/en/function.dns-get-record.php#refsect1-function.dns-get-record-parameters) parameter list, it is a valid constant.

**Comment by jfcherng** [comment]
We can show all PHP constants by
```php
print_r(get_defined_constants(true));
```

[Here](https://pastebin.com/raw/2YYseWR9)'s the output on my machine.
Maybe we can add/check all built-in (and some common extensions) constants.
