### ISSUE TITLE
CSS Grid: grid-template-rows highlighting incomplete

### ISSUE THREAD

**Issue by kleinfreund** [sublimehq/Packages#992]
The property `grid-template-rows` is highlighted incompletely. Specifically, the `rows` portions is not treated as `support.type.property-name.css`.

Oddly enough, the sister property `grid-template-columns` is highlighted correctly.

```
.rule {
    grid-template-rows: none;
    /*            ^^^^ not highlighted */
    grid-template-columns: none;
}
```

**Comment by pdknsk** [comment]
> Oddly enough, the sister property `grid-template-columns` is highlighted correctly.

Almost.
```CSS
grid-row-gap:;
        ^^^^
grid-template-areas:;
             ^^^^^^
grid-template-columns:;
             ^
grid-template-rows:;
             ^^^^^
```
