### ISSUE TITLE
[Rust] Incorrect error highlighting with nested array template arguments

### ISSUE THREAD

**Issue by tommit** [sublimehq/Packages#995]
I'm using Sublime Text 3, Dev Build 3131 on macOS Sierra. The second semicolon gets erroneously highlighted as error in the last two cases:
![incorrect-highlighting](https://cloud.githubusercontent.com/assets/7393895/26461445/d4dba45a-4185-11e7-9276-f6aa76e1863d.png)

**Comment by keith-hall** [comment]
I don't know Rust syntax well enough to be confident about how to fix it, but it looks like it is this pattern here that causes it: https://github.com/sublimehq/Packages/blob/b506d85ef0badfbdbe18f75f02cfa4588b18d574/Rust/Rust.sublime-syntax#L472-L473

Removing that pop pattern completely means that the `+` no longer gets scoped though, so I guess it needs to copy the `+` scoping from https://github.com/sublimehq/Packages/blob/b506d85ef0badfbdbe18f75f02cfa4588b18d574/Rust/Rust.sublime-syntax#L478-L479 in place of the `\S` lookahead pop pattern.

**Comment by FichteFoll** [comment]
Am I right to assume that Rust allows array lengths in type declarations that are known at compile time, including compiler optimizations like resolving constants such as `N` above or simple arithmetics, as seen with `5+1`? (Consequently, `N+1` as well?)

In that case, it might make sense to introduce a special `size` context that matches the allowed expressions in array declarations.

**Comment by tommit** [comment]
@FichteFoll 
> Am I right to assume that Rust allows array lengths in type declarations that are known at compile time, including compiler optimizations like resolving constants such as N above or simple arithmetics, as seen with 5+1? (Consequently, N+1 as well?)

Your assumption is correct. The Rust (fixed-sized) array type notation `[T; N]` means an array of `N` elements of type `T`, where `N` must be a compile-time known expression of type `usize` (which is basically an unsigned integer). `Box` is basically a type template (in C++ speak) which is parameterized by one type parameter, and therefore the notation `Box<T>`, where `T` is some actual type, means an actual type instantiation. Compile-time constant values can be created with the notation `const MY_VALUE: T = N;`, where `T` is a type and `N` is a compile-time known expression (the convention is to name constants using screaming snake case). For example, the following is legal albeit unlikely Rust code:
```Rust
const FOO: usize = 5;

let _: Box<[[bool; (FOO + 1) / 2]; FOO * 3 % 12 - 1]>;
```
